### ISSUE TITLE
File Policy looks changing after a time but why ?

### ISSUE THREAD

**Issue by iznotek** [minio/minio#11046] opened 2020-12-07 18:52 UTC
## Expected Behavior
Just need an upload with presignedurl keep is policy all the time...

## Current Behavior
after few hours or days i get a 403 rejected the file... but the file is still there in the bucket.

## Steps to Reproduce (for bugs)
Here is the code i use to prepare the upload on the backend

```

function addPolicy(resolve, reject, client, bucket, key, returnData) {
  var policy = {
    Version: '2012-10-17',
    Statement: [
      {
        Sid: 'Public',
        Effect: 'Allow',
        Principal: { AWS: '*' },
        Action: ['s3:GetObject'],
        Resource: [`arn:aws:s3:::${bucket}/${key}`],
      },
    ],
  }
  client.setBucketPolicy(bucket, JSON.stringify(policy), function(err, data) {
    if (err) {
      reject(err)
    } else {
      resolve(returnData)
    }
  });
}

function presignedUrl(resolve, reject, client, bucket, key) {
  client.presignedPutObject(bucket, key, 60, function(err, data) {
    if (err) {
      reject(err)
    } else {
      const parsedUrl = url.parse(data);
      const returnData = {
        signedRequest: data,
        url: `${parsedUrl.protocol}//${parsedUrl.host}${parsedUrl.pathname}`,
      };

      console.log(returnData);
      // resolve(returnData);
      addPolicy(resolve, reject, client, bucket, key, returnData)
    }
  });
}

async function signRequestForUploadMinio({ fileName, fileType, prefix, bucket }) {
  const randomStringForPrefix =
    Math.random()
      .toString(36)
      .substring(2, 12) +
    Math.random()
      .toString(36)
      .substring(2, 12);

  const key = `${prefix}/${randomStringForPrefix}/${fileName}`;

  console.log(key, bucket);

  var minioClient = new minio.Client({
    endPoint: process.env.MINIO_ENDPOINT ?? 'play.min.io',
    port: Number(process.env.MINIO_PORT) ?? 9000,
    useSSL: (process.env.MINIO_SECURE ?? 'false') === 'true',
    accessKey: process.env.MINIO_ACCESSKEYID,
    secretKey: process.env.MINIO_SECRETACCESSKEY
  }); 

  return new Promise((resolve, reject) => {
    minioClient.bucketExists(bucket, function(err, exists) {
      if (err) {
        reject(err)
      } else {
        if (exists) {
          presignedUrl(resolve, reject, minioClient, bucket, key);
        } else {
          minioClient.makeBucket(bucket, function(err) {
            if (err) {
              reject(err)
            } else {
              // console.log('Bucket created successfully.')
              presignedUrl(resolve, reject, minioClient, bucket, key);
            }
          });
        }
      }
    });
  });

```

## Your Environment
I have the same pb on my mac in dev with the latest docker
than on my production server with minio/minio:RELEASE.2020-12-03T05-49-24Z

PS: lastely i even get another pb on my mac dev compose stack that from my frontend, minio seams even not accept any upload file from the generated presigned url ( code above ) even if the request return a success code and no trace log under minio... but i can't find the file in the volume...????

**Comment by harshavardhana** [comment] 2020-12-25 07:11
Not able to reproduce this in any meaningful way, please upgrade to latest release - test and let us know if the issue persists. Closing this issue.

**Closed as completed by harshavardhana** 2020-12-25 07:11 UTC
Labels: working as intended, community
