### ISSUE TITLE
[distributed] Replacing a server on a cluster

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3102] opened 2016-10-26 15:03 UTC
Replacing a server (IP change) in a cluster should be possible.
I used names instead of ip and restarted a machine (the ip change on restart).
The machine with the same name (dns resolution is correct) can't re-join the cluster.
The cluster is dead, the only solution is to copy on a new cluster and destroy this one.

Ideally it should even be possible to change the ips without a restart and not to rely on dns changes.

```
+ exec app server 3016530e-e296-448a-8675-3fa492637881.priv.cloud.scaleway.com:/minio dc00aebd-e010-44ce-b5f1-baee80ff60b1.priv.cloud.scaleway.com:/minio 67777f71-c188-49ed-bd4b-9c332c731311.priv.cloud.scaleway.com:/minio 88b39a74-4db1-400d-8019-2c475f4c0c3c.priv.cloud.scaleway.com:/minio

Initializing data volume.
[01/04] 3016530e-e296-448a-8675-3fa492637881.priv.cloud.scaleway.com:/minio - 46 GiB online
[02/04] dc00aebd-e010-44ce-b5f1-baee80ff60b1.priv.cloud.scaleway.com:/minio - 0 B offline
[03/04] 67777f71-c188-49ed-bd4b-9c332c731311.priv.cloud.scaleway.com:/minio - 46 GiB online
[04/04] 88b39a74-4db1-400d-8019-2c475f4c0c3c.priv.cloud.scaleway.com:/minio - 46 GiB online
panic: runtime error: index out of range

goroutine 136 [running]:
panic(0xac1a40, 0xc4200120b0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func1(0xc4203d2240, 0x4, 0xc420474080, 0x4, 0x4, 0xc4202abb60, 0x0, 0xa86d01, 0xefcfc0, 0xc420417a80)
    /go/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:170 +0x69b
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
    /go/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:191 +0xf4

```

**Comment by krishnasrinivas** [comment] 2016-10-26 15:13
If dc00aebd-e010-44ce-b5f1-baee80ff60b1.priv.cloud.scaleway.com is pointing to the new IP then minio should handle this transparently, we'll check.

**Comment by dcharbonnier** [comment] 2016-10-26 15:31
retrying to start it now succeed so it may be a problem of dns cache somewhere this solution is not elegant but at least it works

**Comment by dcharbonnier** [comment] 2016-10-26 15:45
it started but the rpc return :

```
{
  "jsonrpc": "2.0",
  "result": {
    "storageInfo": {
      "Total": 73620412416,
      "Free": 67528888320,
      "Backend": {
        "Type": 2,
        "OnlineDisks": 3,
        "OfflineDisks": 1,
        "ReadQuorum": 2,
        "WriteQuorum": 3
      }
    },
    "uiVersion": "2016-10-15T15:16:16Z"
  },
  "id": 1
}
```

or the rpc is wrong or something is still failing

**Comment by dcharbonnier** [comment] 2016-10-26 15:48
restarting again I got  
Data volume requires HEALING. Please run the following command:
`MINIO_ACCESS_KEY=xxx MINIO_SECRET_KEY=xxx minio control heal http://10.2.219.147:9000`

**Comment by krishnasrinivas** [comment] 2016-10-26 16:07
@dcharbonnier was any of the backend disk changed? with the new IP did it also get a new backend disk? In which case you have to run the specified heal command

**Comment by dcharbonnier** [comment] 2016-10-26 16:22
yes, the disk was erased, the heal command did nothing after more than 30 minutes

```
root@scw-40b4c5:~# docker exec -t minio go-wrapper run control service status http://10.2.219.147:9000
+ exec app control service status http://10.2.219.147:9000
Drive Capacity: 63 GiB Free, 69 GiB Total
Status:         3 Online, 1 Offline. We can withstand [1] more drive failure(s).
```

**Comment by dcharbonnier** [comment] 2016-10-26 16:54
it came back but it took a very long time and the bucket contain a 200Mo file only

**Comment by harshavardhana** [comment] 2016-10-26 17:32
Reopened for further investigation.

**Comment by GarimaKapoor** [comment] 2016-11-05 17:29
@krishnasrinivas were you able to investigate this issue?

**Comment by krishnasrinivas** [comment] 2016-11-07 11:52
I was not able to see `minio control heal http://host:9000` causing delay. But seeing some other problem related to healing, investigating more.

**Comment by krishnasrinivas** [comment] 2016-11-09 14:58
status: `minio control heal http://host:9000` was quick. But there are other issues opened w.r.t healing, once that is fixed we can check with @dcharbonnier to see if the delay is reproducible.

**Comment by harshavardhana** [comment] 2016-11-10 02:23
@dcharbonnier do you still have the setup handy which can reproduce this issue? - Thanks

**Comment by harshavardhana** [comment] 2016-11-16 02:17
This issue will be moved and addressed in `mc admin heal` command which will be implemented post distributed server release.

**Comment by GarimaKapoor** [comment] 2016-12-04 21:32
@harshavardhana can we close this issue as we are going to track it in mc admin issue?

**Comment by harshavardhana** [comment] 2016-12-04 21:34
> @harshavardhana can we close this issue as we are going to track it in mc admin issue?

`mc admin` heal patches will reference this bug as `fixes #<this>` so that it automatically closes and notifies the parties involved in the issue so it is kept here.

**Comment by harshavardhana** [comment] 2016-12-20 23:06
Closing as duplicate of #3395

**Closed as completed by harshavardhana** 2016-12-20 23:06 UTC
