### ISSUE TITLE
Unable to heal deleted files in distributed mode

### ISSUE THREAD

**Issue by miketonks** [minio/minio#6000] opened 2018-06-01 13:32 UTC
## Expected Behavior
In distributed mode, when a node is taken out of the cluster for maintenance or due to outage, the node can be returned to the cluster and healed using the Heal API.

After healing, cluster should be restored to 100% Green state.

## Current Behavior

If a file has been deleted from Minio while a node was offline, the heal result will report Grey for that file.  Heal status can never be restored to Green.

## Possible Solution
Heal should be able to sync the deleted state.
In addition, some documentation of the Heal API and expected usage would be helpful.

## Steps to Reproduce (for bugs)

1.  Start up minio in distributed mode.  I have 6 modes, but 4 should be enough.
2.  Create a bucket with several files.
3.  Shut down one node.
4. Delete one or more files.
5. Bring the node back online.
6. Run a  Heal command.  The files deleted will appear Grey.

## Context
We are testing the new Heal API and need to ensure our systems will be stable in normal usage.
In production it is expected that nodes will be taken offline for maintenance, or may be down for some reason.  The cluster must survive this.  We need to be able to recover from this scenario and return to a healthy state, without the need to restore from backup.

## Your Environment
* Environment name and version (e.g. nginx 1.9.1): MINIO_VERSION=RELEASE.2018-05-16T23-35-33Z
* Server type and version: Cloud Virtual Servers
* Operating System and version (uname -a):Linux 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2018-06-01 16:44
What was the exact command used to heal ?

**Comment by deekoder** [comment] 2018-06-05 18:32
ping @miketonks. Please can you tell us the exact heal command you typed in.

**Comment by miketonks** [comment] 2018-06-12 10:39
Heal is started from code in our go project.  We heal automatically when a node comes back online:

```
	ac, err := madmin.New(host, m.accessKey, m.secretKey, m.ssl)
	....

	healOpts := madmin.HealOpts{Recursive: true, DryRun: false}
	healStart, healTaskStatus, err := ac.Heal("", "", healOpts, "", true)
	...
```

I can reproduce using command line tools.  minio6 is the node that was taken offline for the test.

```
mc admin heal -r minio5/
 ◐  00000000-0000-0000-0000-00000000000…thdt92sd0j9flts9a1ii0/1.3.0/main.js
    0/1,605 objects; 140 MiB in 29s
    ┌────────┬───────┬─────────────────────┐
    │ Green  │ 1,634 │  99.9% ████████████ │
    │ Yellow │     0 │   0.0%              │
    │ Red    │     0 │   0.0%              │
    │ Grey   │     1 │   0.1% █            │
    └────────┴───────┴─────────────────────┘
mc admin heal -r minio6/
 ◑  00000000-0000-0000-0000-00000000000…tcvp30t1r50f3hg31t4c/1.24.0/main.js
    0/1,605 objects; 140 MiB in 27s
    ┌────────┬───────┬─────────────────────┐
    │ Green  │ 1,634 │  99.9% ████████████ │
    │ Yellow │     0 │   0.0%              │
    │ Red    │     0 │   0.0%              │
    │ Grey   │     1 │   0.1% █            │
    └────────┴───────┴─────────────────────┘

```

I tried healing specific bucket and folder:
```
mc ls minio5/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
[2018-06-11 13:30:44 UTC] 371KiB Screen Shot 2018-06-05 at 11.40.33.png
[2018-06-12 10:10:44 UTC]  19KiB bart.png
[2018-06-12 10:10:52 UTC] 9.1KiB lisa.png
[2018-06-12 10:11:07 UTC] 6.3KiB marge.png

mc admin heal -r minio5/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
 ◓  00000000-0000-0000-0000-00000000000…l563897bjv2t1ml6s/default/marge.png
    0/5 objects; 414 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 6 │  85.7% ███████████  │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 1 │  14.3% ██           │
    └────────┴───┴─────────────────────┘

mc admin heal -r minio6/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
 ◓  00000000-0000-0000-0000-00000000000…l563897bjv2t1ml6s/default/marge.png
    0/5 objects; 414 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 6 │  85.7% ███████████  │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 1 │  14.3% ██           │
    └────────┴───┴─────────────────────┘

```

To confirm what's going on, I repeated the test after stopping our application which does the automatic healing.  First I stop node 6, then delete the 'bart.png' file

```
mc rm minio5/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/bart.png

mc ls minio5/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
[2018-06-11 13:30:44 UTC] 371KiB Screen Shot 2018-06-05 at 11.40.33.png
[2018-06-12 10:10:52 UTC] 9.1KiB lisa.png
[2018-06-12 10:11:07 UTC] 6.3KiB marge.png

mc ls minio4/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
[2018-06-11 13:30:44 UTC] 371KiB Screen Shot 2018-06-05 at 11.40.33.png
[2018-06-12 10:10:52 UTC] 9.1KiB lisa.png
[2018-06-12 10:11:07 UTC] 6.3KiB marge.png

mc admin heal -r minio5/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
 ◓  00000000-0000-0000-0000-00000000000…l563897bjv2t1ml6s/default/marge.png
    0/3 objects; 386 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 0 │   0.0%              │
    │ Yellow │ 5 │ 100.0% ████████████ │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```
So far so good.  Bart is removed from all nodes, heal status is yellow, this is expected as node6 is offline.  It is interesting to see at this stage that the 'grey' files disappeared.  I guess they are associated with node6.  Now I bring node6 back online.

File is removed from node6, as we would expect.

```
mc ls minio6/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
[2018-06-11 13:30:44 UTC] 371KiB Screen Shot 2018-06-05 at 11.40.33.png
[2018-06-12 10:10:52 UTC] 9.1KiB lisa.png
[2018-06-12 10:11:07 UTC] 6.3KiB marge.png
```

Running heal in dry-run mode on each node reports the same - we now have 2 grey / missing files.

```
mc admin heal -r -n minio6/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
 ◓  00000000-0000-0000-0000-00000000000…l563897bjv2t1ml6s/default/marge.png
    0/5 objects; 414 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 5 │  71.4% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 2 │  28.6% ████         │
    └────────┴───┴─────────────────────┘

mc admin heal -r -n minio4/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
 ◓  00000000-0000-0000-0000-00000000000…l563897bjv2t1ml6s/default/marge.png
    0/5 objects; 414 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 5 │  71.4% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 2 │  28.6% ████         │
    └────────┴───┴─────────────────────┘

mc admin heal -r minio6/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
 ◓  00000000-0000-0000-0000-00000000000…l563897bjv2t1ml6s/default/marge.png
    0/5 objects; 414 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 5 │  71.4% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 2 │  28.6% ████         │
    └────────┴───┴─────────────────────┘
```

Running the heal without dry-run, can be repeated, but the grey files always remain.  I tried different options, with and without bucket / folder.

```
mc admin heal -r minio6/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/default/
 ◓  00000000-0000-0000-0000-00000000000…l563897bjv2t1ml6s/default/marge.png
    0/5 objects; 414 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 5 │  71.4% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 2 │  28.6% ████         │
    └────────┴───┴─────────────────────┘

mc admin heal -r minio6/00000000-0000-0000-0000-000000000001-0nm2jt36pl563897bjv2t1ml6s/
 ◓  00000000-0000-0000-0000-00000000000…l563897bjv2t1ml6s/default/marge.png
    0/5 objects; 414 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 5 │  71.4% █████████    │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 2 │  28.6% ████         │
    └────────┴───┴─────────────────────┘

mc admin heal -r minio6/
 ◒  00000000-0000-0000-0000-00000000000…h7c95ppefl0bss7uo/1.26.0/index.html
    0/1,605 objects; 140 MiB in 28s
    ┌────────┬───────┬─────────────────────┐
    │ Green  │ 1,633 │  99.8% ████████████ │
    │ Yellow │     0 │   0.0%              │
    │ Red    │     0 │   0.0%              │
    │ Grey   │     2 │   0.1% █            │
    └────────┴───────┴─────────────────────┘

```

**Comment by donatello** [comment] 2018-06-12 22:31
As the object was deleted when minio6 was down, if minio6 is brought back up and heal is run, the part of the object that was in minio6 is detected - however, the rest of the object cannot be reconstructed, as it was cleanly deleted on the other servers.

The problem is that the server cannot distinguish between deleted files and file parts damaged due to disk corruption, and as minio only uses the file-system, it does not keep track of objects that were deleted.

Healing reports the data as grey meaning it belongs to un-recoverable objects. The server does not yet implement a facility to clear such files or to move them to a user-accessible location.

**Comment by harshavardhana** [comment] 2018-06-14 09:36
Currently, this is not implemented as @donatello suggested since implementing this requires us to be extra careful we had moved this for future implementation.  We will have to discuss this internally and will propose a solution here.

**Comment by CAFxX** [comment] 2018-10-12 04:49
@harshavardhana was any progress made on the discussion? I'm sure there can be better ways of dealing with explicitly deleted files, but how about something "simple" like this:

1. every object gets some kind of internal unique id during creation
2. assuming there is a quorum of online nodes, when an object is deleted all online nodes delete it locally and record the unique id in a list of deleted objects
3. when a node comes back online, it will fetch the list of deleted objects from all other online nodes and it will proceed to delete locally any locally-existing object that is present in the union of the received deleted objects list; when an object is deleted (or verified to not exist locally) it is added to the local list of deleted objects
4. to prevent the deleted objects list from growing forever, when all nodes in the cluster confirm that they have all deleted a certain object, that object is removed from the deleted object list
5. if a node somehow loses the list of deleted objects (e.g. missing disk) the node will simply fetch it from the other online nodes when it comes online and resume (as in point 3)
6. during heal the nodes will also sync their deleted objects lists and perform any local deletions as appropriate (as in point 3)

Just to clarify, this is meant to address the case of explicitly deleted files, not the case of files that go missing because there's not enough parity to reconstruct the data.

**Comment by harshavardhana** [comment] 2018-10-19 01:46
This is already fixed and being addressed in https://github.com/minio/minio/pull/6670

**Comment by harshavardhana** [comment] 2018-10-20 03:30
This is merged and fixed in master. Closing.

**Closed as completed by harshavardhana** 2018-10-20 03:30 UTC
Labels: fixed, priority: medium
