### ISSUE TITLE
Cannot replicate eTag in TypeScript (Node)

### ISSUE THREAD

**Issue by TAINCER** [minio/minio#8244] opened 2019-09-15 17:54 UTC
I have an application that is creating an eTag of a file, so the application knows, whether the local files are different from the files on the server. (minio)

## Expected Behavior
The local file should have the same eTag as the file on the minio server.

## Current Behavior
The eTag on the server is different from the eTag on the client.

## Steps to Reproduce (for bugs)
I'm using the libary [etag-stream](https://www.npmjs.com/package/etag-stream) to generate the eTag (This already worked with AWS S3 and DO Spaces)
````typescript

  async calculateETAG(filePath: string) {
    const stream = this.stream = new ETagStream({ partSizeInMb: 5, mode: 'through' });
    let result = null;
    
    let etag = new Promise((resolve, reject) => {
      stream.on('etag', async (data) => {
        result = data.toString();
        let splitted = result.split('-');

        if (parseInt(splitted[1]) <= 5) {
          let nextHash = new Promise((resolve, reject) => {
            md5File(filePath, (err, hash) => {
              if (err) reject(err);

              resolve(hash);
            });
          });

          resolve(await nextHash)
        }

        resolve(result);
        return;
      });
    });
    
    
    createReadStream(filePath).pipe(stream);
    return await etag;
  }
````
Returns locally:
`29bc792abbf5192bdc703fd00c1b6583`
and the same file on the minio server (I got the eTag through the PHP AWS S3 SDK)
`0fce35defe4369f06a1d641b3c908b92-1`
and the same file on DO Spaces
`29bc792abbf5192bdc703fd00c1b6583`

## Context
I'm trying to compare files from a client PC with the files on the server and download (sync) the missing and or corrupt files.

## Environment
Minio version: 2019-09-11T19:53:16Z
Nodejs version: v12.7.0
etag-stream version: 1.0.4
uname -a: Linux cServer 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Comment by kannappanr** [comment] 2019-09-16 01:36
@TAINCERcs You need to start `MinIO` with `--compat` flag. This check against AWS and DO also will work only if the whole object was uploaded as a single part.

**Comment by harshavardhana** [comment] 2019-09-16 07:09
ETag shouldn't be used as a checksum for your content, content integrity based on md5sum will lead to bugs.

If you are interested in ETag to be md5sum make sure to set it as content-md5 during uploads.

**Comment by kannappanr** [comment] 2019-09-16 18:31
@TAINCERcs closing this as working as intended. Please feel free to reach out to us at https://slack.min.io if you have further questions.

**Closed as completed by kannappanr** 2019-09-16 18:31 UTC
Labels: community, triage
