### ISSUE TITLE
Running Minio on port "0" should print the right port allocated by the OS, not "0"

### ISSUE THREAD

**Issue by yhafri** [minio/minio#3314] opened 2016-11-22 16:16 UTC
I'm trying to use Minio without specifying any fixed port number during startup.
For this, I'm relying on the OS to give me back a free port to use.

## Expected Behavior
$ minio server --address "127.0.0.1:0" /tmp/.s3share

Endpoint:  http://127.0.0.1:57088
AccessKey: KM6074YUX3OB5BK06D02
SecretKey: LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5
Region:    us-east-1
SqsARNs:

Browser Access:
   http://127.0.0.1:57088

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://127.0.0.1:57088 KM6074YUX3OB5BK06D02 LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5

And as you can see, it works as expected.

## Current Behavior

What i'm getting now is this (which is OK but kind of useless):

$ minio server --address "127.0.0.1:0" /tmp/.s3share

Endpoint:  http://127.0.0.1:0
AccessKey: KM6074YUX3OB5BK06D02
SecretKey: LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5
Region:    us-east-1
SqsARNs:

Browser Access:
   http://127.0.0.1:0

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://127.0.0.1:0 KM6074YUX3OB5BK06D02 LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5

## Possible Solution
Once the OS gave us an automatic free port (in this case "57088"), use that one instead of "0". 

Actually, I'm using netstat to discover which port Minio is using, which is very tedious:
I'm trying to use Minio without specifying any fixed port number during startup.
For this, I'm relying on the OS to give back me a free port to use.

## Expected Behavior
$ minio server --address "127.0.0.1:0" /tmp/.s3share

Endpoint:  http://127.0.0.1:57088
AccessKey: KM6074YUX3OB5BK06D02
SecretKey: LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5
Region:    us-east-1
SqsARNs:

Browser Access:
   http://127.0.0.1:57088

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://127.0.0.1:57088 KM6074YUX3OB5BK06D02 LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5

## Current Behavior

What i'm getting now is this (which is OK but kind of useless):

$ minio server --address "127.0.0.1:0" /tmp/.s3share

Endpoint:  http://127.0.0.1:0
AccessKey: KM6074YUX3OB5BK06D02
SecretKey: LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5
Region:    us-east-1
SqsARNs:

Browser Access:
   http://127.0.0.1:0

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://127.0.0.1:0 KM6074YUX3OB5BK06D02 LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5

## Possible Solution
Once the OS gave us an automatic free port (in this case "57088"), use that one instead of "0". 
Currently, I'm using netstat to discover which port my Minio instance is using (tedious, and error prone):

$ netstat -ant | grep LISTEN
tcp4       0      0  172.20.10.3.57088      *.*                    LISTEN

## Steps to Reproduce (for enhancement)
1. On Linux:
minio server --address "127.0.0.1:0" /tmp/.s3share

2. On OSX:
minio server --address "127.0.0.1:0" /tmp/.s3share

## Context
It'll be super helpful if Minio can display the right port, and not "0".

## Your Environment
* Linux: any
* OSX: any
* FreeBSD: not tested yes, but should be the same
## Steps to Reproduce (for enhancement)
1. On Linux:
minio server --address "127.0.0.1:0" /tmp/.s3share

2. On OSX:
minio server --address "127.0.0.1:0" /tmp/.s3share

## Context
It'll be super helpful if Minio can display the right port, and not "0".

## Your Environment
* Linux: any
* OSX: any
* FreeBSD: not tested yet, but should be the same

**Comment by vadmeste** [comment] 2016-11-22 20:48
I am taking this

**Comment by harshavardhana** [comment] 2016-11-23 01:01
Fixed by #3318

**Closed as completed by harshavardhana** 2016-11-23 01:01 UTC

**Comment by yhafri** [comment] 2016-11-23 04:43
Why forbid port 0 guys?

By opening this issue, I simply wanted to display the right information, not to forbid this neat OS feature.

Can you pleas eput back this option in place?

**Comment by harshavardhana** [comment] 2016-11-23 04:52
> Why forbid port 0 guys?
> 
> By opening this issue, I simply wanted to display the right information, not to forbid this neat OS feature.
> 
> Can you pleas eput back this option in place?

Dynamically changing ports is a problem for single node and distributed setup.  If the servers in any moment gets restarted all your configured Apps, clients will fail since the endpoint comes with the port.  So it was a bug in the first place to allow this to happen.

**Comment by yhafri** [comment] 2016-11-23 06:08
I completely understand this use case, but our is very different.

In your case, you simply don't have to rely on port=0 at all, and problem's solved.
Just used any port than 0. It was like that since day one.

In our case, we're offering a sharing service based on ephemeral ports to hundred of clients.
When the system's up, they all received an email (or pagerduty, etc.) with the newly created EndPoint information (i.e HOST:PORT). Not only the PORT number can be different, but even the HOST can be to increase security and reduce potential attack surface. The system is more complex than, but i just wanted to scratch the surface.

Anyway, it's working perfectly for many months now, and forbidding port "0" means we have to redesign the whole logic.

Hope you can reconsider closing this issue.

**Comment by harshavardhana** [comment] 2016-11-23 06:39
> In your case, you simply don't have to rely on port=0 at all, and problem's solved.
> Just used any port than 0. It was like that since day one.
> 
> In our case, we're offering a sharing service based on ephemeral ports to hundred of clients.
> When the system's up, they all received an email (or pagerduty, etc.) with the newly created EndPoint information (i.e HOST:PORT). Not only the PORT number can be different, but even the HOST can be to increase security and reduce potential attack surface. The system is more complex than, but i just wanted to scratch the surface.
> 
> Anyway, it's working perfectly for many months now, and forbidding port "0" means we have to redesign the whole logic.

We can handle this separately for only FS but the problem is that the logic of free port assignment is not Minio's responsibility. If the port assigning is managed properly outside of the Minio then this issue never occurs. For example a simple wrapper function which calls Minio with right free port as needed.

Can you explain more how does a restart is handled in your application basically if 'minio' is restarted with 'port' '0' wouldn't it get the new port? how is the configuration updated across the clients? how are the existing in-transit calls are handled? i.e how the transparent reconnect happens from clients if the server is restarted and gets a new port?

**Comment by yhafri** [comment] 2016-11-23 07:09
> We can handle this separately for only FS but the problem is that the logic of free port assignment is not Minio's responsibility.

Totally agree, It's our responsibility as Minio users to decide whether to use port 0 or not.

> If the port assigning is managed properly outside of the Minio then this issue never occurs. For example a simple wrapper function which calls Minio with right free port as needed.

And this is exactly why i originally opened  this request for enhancement (**not a bug**).
This is a neat OS feature provided for free.

We've a wrapper: we call it a **supervisor** and it's more than a simple wrapper.

> Can you explain more how does a restart is handled in your application basically if 'minio' is restarted with 'port' '0' wouldn't it get the new port?

We use a homemade supervisor process to start Minio instances. The supervisor handles restart after crash, figure our which new port is used by the new started instances, etc.

Let say for example Minio is start with port 0 and gets assigned port 8888 by the OS.
The supervisor keeps this port 8888 on his state. If for whatever reason the supervised Minio crashes, it gets restarted using port 8888 of course. The client will never notice that.

> how is the configuration updated across the clients?

Depending on policies in place, a customer's share can be forced to restart on the same node (or a remote one) once a week for example. When it does happen, the supervisor will **always restart** the share with port 0 to get a new Endpoint which is then sent to the customer.

> how are the existing in-transit calls are handled?

We only allow shares to be available during certain period of the day, Ex:
_3.00am - 4:30am_

So not a real issue here.

> i.e how the transparent reconnect happens from clients if the server is restarted and gets a new port?

Nope, it can't happen (see above) unless stated by the policy in place.

**Comment by yhafri** [comment] 2016-11-23 07:23
One more thing: currently, we rely on external tool/script to detect the PORT number assigned to the Minio instance (started with port 0).

But this can be solved in an even simpler way. See this:

```
$ minio server --address "127.0.0.1:0" /tmp/.s3share

Endpoint: http://127.0.0.1:8888
AccessKey: KM6074YUX3OB5BK06D02
SecretKey: LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5
Region: us-east-1
SqsARNs:

Browser Access:
http://127.0.0.1:8888

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
$ mc config host add myminio http://127.0.0.1:8888 KM6074YUX3OB5BK06D02 LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5
```

Assume the above output is fixed (displaying 8888 instead of 0), the *supervisor* or any wrapper can parse this output to figure out the port 8888.

Even better, if in the future *minio* can be shipped with an option *--json* to display the same output in JSON format,  something more or less like that:

```
$ minio server --json --address "127.0.0.1:0" /tmp/.s3share

[ 
{"endpoint" : "http://127.0.0.1:8888"},
{"access_key" : "KM6074YUX3OB5BK06D02",
{"secret_key" : "LuQwctJmvJQUyPA6ogYWKtkMLFo9uEBez6/5Y/o5",
{"region" : "us-east-1"},
{"port", "8888"}              <<<<------------- our guy
...
]
```

Parsing will be simplified.

The *mc* has this option already in place. Why not *minio* ;-) ?

**Comment by harshavardhana** [comment] 2016-11-23 07:53
Okay now i see what the supervisor is doing - rather than remembering what was assigned to and then restarting the minio server with that port. It is better for supervisor to know which port it is going to assign to Minio. 

A simple function like this can do the job, this way ports are managed outside for example even a bug in your system when the state never gets saved due to an issue in capturing the port used by minio server.

```
package	main

import (
        "fmt"
        "net"
)

// Ask the kernel for a free open port.                                                                                                           
func getFreePort() string {
	addr, err := net.ResolveTCPAddr("tcp", "localhost:0")
	if err != nil {
		panic(err)
	}

        l, err := net.ListenTCP("tcp", addr)
	if err != nil {
		panic(err)
	}
        defer l.Close()
	return fmt.Sprintf("%d", l.Addr().(*net.TCPAddr).Port)
}
func main() {
        fmt.Println(getFreePort())
}
```

Now supervisor also becomes more meaningful in this scenario where it can manage a pool of ports  (security) and only assign port to Minio from a particular given range.

All of this rich functionality can never be implemented cleanly in Minio server. It is our design philosophy that we don't allow multiple ways to do the same thing basically allowing single disk alone to run with this feature and in distributed we restrict it. 

JSON printing is a good idea we will think about that in future..  you can open a bug on this.

**Comment by yhafri** [comment] 2016-11-23 15:46
Hi

Thanks for the hint. Our supervisor is much more complex and works in a distributed manner: cross-nodes and cross-data center.

Happy you're keeping this neat OS feature, and hope you'll also fix Minio's output when port is set to 0.

**Comment by yhafri** [comment] 2016-11-26 19:29
Hi  harshavardhana
Any update on this? I'm asking because the issue is still tagged as closed.
```
$ wget https://dl.minio.io/server/minio/release/linux-amd64/minio && chmod +x minio
$ ./minio server --address ":0" /tmp
FATA[0000] Invalid port `0`, please use `--address` to pick a specific port  cause=Invalid arguments specified source=[server-main.go:379:serverMain()]

```
Thank you.
