### ISSUE TITLE
[notify] Redis: changing format will prevent Minio next restart with an error

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4257] opened 2017-05-04 19:26 UTC
## Expected Behavior
Changing format from access to namespace shouldn't (?) be a problem.

## Current Behavior
Changing format from access to namespace shows an error

```
FATA[0001] Initializing object layer failed              cause=Unable to initialize event notification. Redis: Error dialing server: Redis: Key=bucketevents has type list, but we expect it to be a hash source=[server-main.go:276:serverMain()]

```

## Possible Solution
Associate different redis keys to differnet formats?

## Steps to Reproduce (for bugs)
1. Enable Redis in config.json
2. Start Minio
3. Stop minio and change format field in redis
4. Start Minio again

## Context
Testing.

## Your Environment
All.
master

**Comment by donatello** [comment] 2017-05-04 21:14
This is an expected behaviour.

Detailed response is available [here](https://github.com/minio/minio/issues/4253#issuecomment-299310485) - we can continue the discussion there too.

**Comment by harshavardhana** [comment] 2017-05-04 21:59
Closing this as working as intended.

**Closed as completed by harshavardhana** 2017-05-04 21:59 UTC
Labels: working as intended, priority: medium
