### ISSUE TITLE
Caching doesn't work for Google Cloud

### ISSUE THREAD

**Issue by mikhail-matrosov** [minio/minio#7667] opened 2019-05-18 22:04 UTC
In Google Cloud bucket names can contain underscores ("_") and dots ("."), e.g. "my_bucket" (see https://cloud.google.com/storage/docs/naming).

When Minio caching is enabled, It fails to return requested files because `object-api-utils.IsValidBucketName()` does not validate bucket name.

## Expected Behavior
For Google Storage and turned on caching Minio should return requested files from bucket "my_bucket".

`IsValidBucketName()` should be able to validate Google bucket names.

## Current Behavior
```
API: GetObjectNInfo(bucket=tardis_bucket, object=kupivip_history_updator/20190101/results.json)
Time: 19:10:11 UTC 05/18/2019
RequestID: 159FDCA834EC2F99
RemoteHost: 10.233.75.35
UserAgent: Minio (Linux; x86_64) minio-py/4.0.13
Error: Bucket name invalid: tardis_bucket
       1: cmd/object-api-input-checks.go:40:cmd.checkBucketAndObjectNames()
       2: cmd/object-api-input-checks.go:28:cmd.checkGetObjArgs()
       3: cmd/fs-v1.go:743:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:760:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/disk-cache-fs.go:297:cmd.(*cacheFSObjects).Exists()
       6: cmd/disk-cache.go:137:cmd.diskCache.getCachedFSLoc()
       7: cmd/disk-cache.go:191:cmd.cacheObjects.GetObjectNInfo()
       8: cmd/object-handlers.go:333:cmd.objectAPIHandlers.GetObjectHandler()
       9: pkg/handlers/http-tracer.go:144:handlers.TraceReqHandlerFunc.func1()
      10: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: GetObject(bucket=tardis_bucket, object=kupivip_history_updator/20190101/results.json)
Time: 19:10:11 UTC 05/18/2019
RequestID: 159FDCA834EC2F99
RemoteHost: 10.233.75.35
UserAgent: Minio (Linux; x86_64) minio-py/4.0.13
Error: Bucket name invalid: tardis_bucket
       1: cmd/object-api-input-checks.go:40:cmd.checkBucketAndObjectNames()
       2: cmd/object-api-input-checks.go:28:cmd.checkGetObjArgs()
       3: cmd/fs-v1.go:463:cmd.(*FSObjects).GetObjectNInfo()
       4: cmd/disk-cache.go:196:cmd.cacheObjects.GetObjectNInfo()
       5: cmd/object-handlers.go:333:cmd.objectAPIHandlers.GetObjectHandler()
       6: pkg/handlers/http-tracer.go:144:handlers.TraceReqHandlerFunc.func1()
       7: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()

API: GetObject(bucket=tardis_bucket, object=kupivip_history_updator/20190101/results.json)
Time: 19:10:11 UTC 05/18/2019
RequestID: 159FDCA834EC2F99
RemoteHost: 10.233.75.35
UserAgent: Minio (Linux; x86_64) minio-py/4.0.13
Error: io: read/write on closed pipe
       1: cmd/api-errors.go:1660:cmd.toAPIErrorCode()
       2: cmd/api-errors.go:1685:cmd.toAPIError()
       3: cmd/object-handlers.go:385:cmd.objectAPIHandlers.GetObjectHandler()
       4: pkg/handlers/http-tracer.go:144:handlers.TraceReqHandlerFunc.func1()
       5: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
[REQUEST objectAPIHandlers.GetObjectHandler-fm] [155820661.109410] [2019-05-18 19:10:11 +0000]
GET /tardis_bucket/kupivip_history_updator/20190101/results.json
Host: minio.kube-system:9000
X-Amz-Date: 20190518T191011Z
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=tardis-minio/20190518/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=4c44850c118d63a443f977283932cf7cbf8abdf16c05e08c0dee0b464971366f
Accept-Encoding: identity
User-Agent: Minio (Linux; x86_64) minio-py/4.0.13
```

## Possible Solution
Implement IsValidBucketName() as a regex, introduce an environment variable for changing it.

## Steps to Reproduce (for bugs)
1. Create a bucket in Google Storage named "my_bucket"
2. Start Minio server with env
    - MINIO_HTTP_TRACE=/dev/stdout
    - MINIO_CACHE_DRIVES=/mnt/cache
    - MINIO_CACHE_EXPIRY=90
3. Request a file
```
GET http://minio.local/my_bucket/example.txt
```

## Context
The bug makes impossible caching with Google Cloud.

## Environment
* Version used (`minio version`):
```
Version: 2019-03-27T22:35:21Z
Release-Tag: RELEASE.2019-03-27T22-35-21Z
Commit-ID: 6df05e489dc789cf26e82810cf5cfeefb1d90761
```

**Comment by harshavardhana** [comment] 2019-05-18 22:08
@mikhail-matrosov thank you for opening an issue, we are addressing caching under gateway when ETag mismatches here https://github.com/minio/minio/pull/7575 

But we cannot support bucket names which have `_` in them as those names are not AWS S3 compatible bucket names, it is unfortunate but if you could please avoid bucket names which are non DNS compliant names.

**Comment by mikhail-matrosov** [comment] 2019-05-18 22:54
@harshavardhana I agree with you. Though I cannot rename my bucket. In python client there is a possibility to avoid this check by writing
```python
import minio, re
minio.helpers._VALID_BUCKETNAME_REGEX = re.compile('.*')
```

I think it would be great to have a similar setting in the server. Let's enable google-users to use their existing buckets.

**Comment by harshavardhana** [comment] 2019-05-18 23:56
> @harshavardhana I agree with you. Though I cannot rename my bucket. In python client there is a possibility to avoid this check by writing
> 
> ```python
> import minio, re
> minio.helpers._VALID_BUCKETNAME_REGEX = re.compile('.*')
> ```
> 
> I think it would be great to have a similar setting in the server. Let's enable google-users to use their existing buckets.

@mikhail-matrosov Current code is stricter about AWS S3 spec. Although existing buckets can be allowed which we already do in some form, we can work on such a fix. 

// cc @kannappanr

**Comment by kannappanr** [comment] 2019-06-08 14:45
ping @sinhaashish

**Comment by sinhaashish** [comment] 2019-10-18 06:47
@mikhail-matrosov  : This is working fine. 

Step 1:  Run `export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json`
Step 2: Run `export MINIO_ACCESS_KEY=minioaccesskey`
Step 3: Run `export MINIO_SECRET_KEY=miniosecretkey`
Step 4: Run `export MINIO_CACHE_DRIVES=/tmp/gcscache`
Step 4: Run `export MINIO_CACHE_EXPIRY=90`
Step 6 : Run   `./minio gateway gcs <<Project_id>>`




**Steps to replicate using `minio-py`** : 
1. Modified `_VALID_BUCKETNAME_REGEX = re.compile('^[a-z0-9][a-z0-9\\.\\-]+[a-z0-9]$')` to 
`_VALID_BUCKETNAME_REGEX = re.compile('.*')` in helpers.py
2. Run sudo python3 setup.py install
3.  Edit the get-object.py file and run  : `python3  examples/get_object.py`
```
from minio import Minio
from minio.error import ResponseError

client = Minio('localhost:9000',
               access_key='minioaccesskey',
               secret_key='miniosecretkey',
               secure=False)

# Get a full object
try:
    data = client.get_object('sinha_minio', 'AFile218.txt')
    with open('/tmp/dummy', 'wb') as file_data:
        for d in data.stream(32*1024):
            file_data.write(d)
except ResponseError as err:
    print(err)
```

Got the below o/p in the cache folder
``` ashish@minio:/tmp/gcscache$ tree -a
.
├── e5d9a0b0f07c09e43dd467595e45405e02db950cb0a1f92eb58ef93d4b94442a
│   ├── cache.json
│   └── part.1
└── .minio.sys
    └── format.json

2 directories, 3 files
```

**Steps to replicate using `mc`** : 

Step 1 . Configure mc usingthe command :  `mc config host add mygcs <<Address>> minioaccesskey miniosecretkey`
Step 2:  Run `./mc cp mygcs/sinha_minio/auth.txt ~/Downloads` 

The cache folder is populated with new entry :+1: 
```
ashish@minio:/tmp/gcscache$ tree -a
.
├── d1e916394289e735bf993ea26d6bf2d36b7ac8c80e05197a6066b088dfa8a9d6
│   ├── cache.json
│   └── part.1
├── e5d9a0b0f07c09e43dd467595e45405e02db950cb0a1f92eb58ef93d4b94442a
│   ├── cache.json
│   └── part.1
└── .minio.sys
    └── format.json

3 directories, 5 files
```
In both the scenario the bucket name conained the `_` i.e. `sinha_minio` and the cache was being created. IMO we can close this issue.

**Comment by harshavardhana** [comment] 2019-10-18 06:53
Closing this issue working as intended..

**Closed as completed by harshavardhana** 2019-10-18 06:53 UTC
Labels: working as intended, community, priority: medium
