### ISSUE TITLE
help me  .\mc.exe policy public minio/xzspfj/20190328/ erro

### ISSUE THREAD

**Issue by lanjiachuan** [minio/minio#7802] opened 2019-06-18 17:12 UTC
When I set the public permission, the picture still cannot be accessed, and the picture file becomes the folder path, may I ask how to solve this problem

**Comment by lanjiachuan** [comment] 2019-06-18 17:13
The demo provided by the official play.minio has the same problem

**Comment by kannappanr** [comment] 2019-06-18 18:13
@lanjiachuan Can you please give us the version of `mc` that you are using? How are you trying to access the picture? Since you can reproduce the issue on play, can you try it out on Play and let us know here?

I will need to know the exact bucket and object that you are trying it on and the mechanism that you are trying this out with.

**Comment by kannappanr** [comment] 2019-06-18 18:14
I have made the bucket `test-minio` public on `play`. There is a file called `a/b/c.txt` and used `curl` to display the contents.

```
$curl https://play.min.io:9000/test-minio/a/b/c.txt
hello test minio
```

**Comment by lanjiachuan** [comment] 2019-06-19 02:35
https://play.min.io:9000/minio/test-minio/a/b/ljl.jpg   I put a JPG file access in this directory and it still can't be opened or downloaded online

**Comment by lanjiachuan** [comment] 2019-06-19 02:35
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/29550961/59732714-f88bf580-927d-11e9-96d8-af49183d746e.png">

**Comment by lanjiachuan** [comment] 2019-06-19 02:36
<img width="866" alt="image" src="https://user-images.githubusercontent.com/29550961/59732765-22ddb300-927e-11e9-96e7-422a7297f421.png">

**Comment by lanjiachuan** [comment] 2019-06-19 02:41
The function I hope to achieve is that the video, audio and pictures uploaded by my instant messaging APP can be directly accessed to the video audio files of the picture through the APP, which can be used after I built it before. Yesterday, the system informed me that I can upgrade to a new version, and now it cannot be used. At present, my version is 2019-06-15 t23.07:18z

**Comment by kannappanr** [comment] 2019-06-19 02:48
You should try `https://play.min.io:9000/test-minio/a/b/ljl.jpg` instead of `https://play.min.io:9000/minio/test-minio/a/b/ljl.jpg`

**Comment by lanjiachuan** [comment] 2019-06-19 02:58
I see. Thank you. But there is a small problem. In addition, does our product support image compression strategy?

**Comment by kannappanr** [comment] 2019-06-19 03:02
Can you elaborate what your problem is? Also, not sure what you mean by image compression strategy

**Comment by lanjiachuan** [comment] 2019-06-19 03:07
My business logic is like this: I upload the original picture about 2M or 32M, due to the delay of the comparison of pictures, I hope to achieve the image proportional compression, for example, add @x2 after the file name and reduce it by twice, so as to speed up the loading speed of pictures by referring to the OSS server of alibaba

**Comment by kannappanr** [comment] 2019-06-19 03:12
So, you will be upload images of two different qualities and depending on speed, you want to display appropriate image.

**Comment by lanjiachuan** [comment] 2019-06-19 03:17
Not, for example, I uploaded a picture of a 32 m, through the URL to access the picture could be 10 seconds or so, if I increase after images @ x2 oss server will help me to generate a temporary compressed image size may only 100 k so I access speed is much faster, if you want to access the artwork as long as I take the back of the @ x2 can get the original image

**Comment by lanjiachuan** [comment] 2019-06-19 03:18
https://segmentfault.com/a/1190000008656825     You can refer to the net friends of a realization, I hope our products also have such a function, as far as this function is very necessary

**Comment by kannappanr** [comment] 2019-06-19 04:03
The link talks about MinIO and Thumbor. I am not very familiar with Thmbor, but looks like it will be in front of MinIO and that will handle this feature that you are talking about.  So, essentially you will be talking to 
 Thumbor. Also, I feel this is outside the scope of S3 object storage. Please let us know what you feel.

**Comment by lanjiachuan** [comment] 2019-06-19 04:25
https://help.aliyun.com/document_detail/44686.html?spm=a2c4g.11174283.2.37.4e747da2hewmxR

**Comment by kannappanr** [comment] 2019-06-19 04:30
I believe this is outside the scope of S3. Is there an API in OSS that allows you to do this and you want MinIO to expose it in the Gateway?

**Comment by lanjiachuan** [comment] 2019-06-19 04:45
I think if the image compression function can be achieved, it can better enable the business system to load the image function faster. If you think it is beyond the scope of oss, this is just my personal suggestion for your reference. Thank you for your help

**Closed as completed** 2019-06-19 05:32 UTC
Labels: working as intended, community
