### ISSUE TITLE
Error too many open files (ECONNRESET)

### ISSUE THREAD

**Issue by danielfdsilva** [minio/minio#5093] opened 2017-10-20 17:19 UTC
## Expected Behavior
It should be able to delete multiple files without crashing.

## Current Behavior
When trying to remove multiple files from minio (circa 10.000) the client (minio-js) throws an error:
```
Unhandled rejection Error: getaddrinfo ENOTFOUND localhost localhost:9000
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)
```
and the server logs:
```
ERRO[0336] Unable to delete an object rra/tiles/b/14/6472/8685.pbf  cause=open /guts/projects/rra/.resources/test-minio/minio-data/.minio.sys/buckets/rra/tiles/b/14/6472/8685.pbf/fs.json: too many open files in system source=[object-handlers.go:1077:objectAPIHandlers.DeleteObjectHandler()] stack=fs-v1.go:647:fsObjects.DeleteObject <autogenerated>:424:(*fsObjects).DeleteObject object-handlers-common.go:241:deleteObject object-handlers.go:1076:objectAPIHandlers.DeleteObjectHandler api-router.go:62:(objectAPIHandlers).DeleteObjectHandler-fm
```

## Steps to Reproduce (for bugs)
To delete the files I'm getting the list with `listObjectsV2` (storing them in an array) and then looping over the array and deleting each file with `removeObject`.

## Your Environment
Happens both with the minio docker container and installed locally on a Mac OS Sierra 10.12.6
Doesn't seem to happen if I use an S3 bucket with the js client.

**Comment by harshavardhana** [comment] 2017-10-20 17:32
what version of minio server are you running? @danielfdsilva  with `docker run --rm minio/minio version` ?  also what can you provide the system limit here? like `ulimit -n` ?

**Comment by danielfdsilva** [comment] 2017-10-20 17:45
@harshavardhana I installed the server today using homebrew:
```
Version: 2017-09-29T19:16:56Z
Release-Tag: RELEASE.2017-09-29T19-16-56Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21
```
The docker version is the same:
```
Version: 2017-09-29T19:16:56Z
Release-Tag: RELEASE.2017-09-29T19-16-56Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21
```

`ulimit -n` = 7128

**Comment by harshavardhana** [comment] 2017-10-20 18:12
You need to increase the ulimit -n to more than the amount of files you are deleting in parallel @danielfdsilva - set the value to perhaps `ulimit -Hn 65535`  should solve this problem.

**Comment by danielfdsilva** [comment] 2017-10-20 18:32
@harshavardhana I'm only deleting about 10 files in parallel. I call the delete function on 10 files and it only picks up more once it's finished.
The same happens if I delete the files in series.

**Comment by harshavardhana** [comment] 2017-10-20 18:42
> @harshavardhana I'm only deleting about 10 files in parallel. I call the delete function on 10 files and it only picks up more once it's finished.
> The same happens if I delete the files in series.

Hmm this looks different do you have a sample code that i can use to reproduce this problem?

**Comment by harshavardhana** [comment] 2017-10-23 09:54
> Hmm this looks different do you have a sample code that i can use to reproduce this problem?

@danielfdsilva do you have a sample code to reproduce this issue?

**Comment by danielfdsilva** [comment] 2017-10-23 10:00
This is the code I have. I tried this on another computer and the result is the same.
```
'use strict';
var Minio = require('minio');

const s3 = new Minio.Client({
  endPoint: 'localhost',
  port: 9000,
  secure: false,
  accessKey: 'minio',
  secretKey: 'miniostorageengine'
});
const BUCKET = 'rra';

var objects = [];
var stream = s3.listObjectsV2(BUCKET, '', true);

stream.on('data', obj => {
  objects.push(obj);
});

stream.on('error', err => {
  throw err;
});

stream.on('end', () => {
  remove(objects);
});

function remove (items) {
  if (items.length) {
    let item = items.pop();
    s3.removeObject(BUCKET, item.name, err => {
      if (err) {
        throw err;
      }
      remove(items);
    });
  }
}
```

**Comment by harshavardhana** [comment] 2017-10-23 10:03
> This is the code I have. I tried this on another computer and the result is the same.

Do you have code on how the data set was generated? @danielfdsilva

**Comment by danielfdsilva** [comment] 2017-10-23 10:05
My dataset is just a bunch of vector tiles, I this case they were generated with `tippecanoe`

**Comment by harshavardhana** [comment] 2017-10-23 11:02
Thanks @danielfdsilva

**Comment by danielfdsilva** [comment] 2017-10-23 11:04
@harshavardhana I can actually send you the files, if you need a test dataset.

**Comment by harshavardhana** [comment] 2017-10-23 22:26
> @harshavardhana I can actually send you the files, if you need a test dataset.

That would be helpful as well

**Comment by harshavardhana** [comment] 2017-10-23 22:42
Reproduced it @danielfdsilva 

```
2017/10/23 22:34:04 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 5ms
2017/10/23 22:34:04 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 10ms
2017/10/23 22:34:04 http: Accept error: accept tcp [::]:9000: accept4: too many open files; retrying in 5ms
ERRO[0056] Unable to delete an object testbucket/app-install/desktop/plasma-widget-amule:plasmamule-engine-feeder.desktop__plasmamule-engine-feeder.desktop  cause=open /home/harsha/test/.minio.sys/buckets/testbucket/app-install/desktop/plasma-widget-amule:plasmamule-engine-feeder.desktop__plasmamule-engine-feeder.desktop/fs.json: too many open files source=[object-handlers.go:1090:objectAPIHandlers.DeleteObjectHandler()] stack=fs-v1.go:692:fsObjects.DeleteObject <autogenerated>:1:(*fsObjects).DeleteObject object-handlers-common.go:241:deleteObject object-handlers.go:1089:objectAPIHandlers.DeleteObjectHandler api-router.go:62:(objectAPIHandlers).DeleteObjectHandler-fm
```

The problem is because of minio-js client keeps the connection active and we run out of number of fd's.  Sort of causing an fd leak,  it doesn't close the connection properly. 

For example `mc rm -r --force home/testbucket`  runs fine on the same data set. I tried with all our other   SDKs we do not have this problem.

**Comment by harshavardhana** [comment] 2017-10-23 23:54
Basically look at this 

```
ls -l /proc/$(pidof minio)/fd/ | wc -l
1025
```

nodejs client is in-fact making 1025 new connections which is incorrect and should be connection pooling which i think is not happening, this is a classic case and server will run out of fd's. 

The fix currently that works is https://github.com/minio/minio-js/blob/master/src/main/minio.js#L120 setting 'keepAlive: false'  , perhaps we are not reusing the agents correctly, not sure needs further investigation but this is not a server problem for now.

**Comment by danielfdsilva** [comment] 2017-10-24 09:19
@harshavardhana Thanks for looking into this. I'll try that and see if it solves the problem.
Should I open an issue for the js client or you keep track of it?

**Comment by harshavardhana** [comment] 2017-10-24 09:39
> @harshavardhana Thanks for looking into this. I'll try that and see if it solves the problem.
> Should I open an issue for the js client or you keep track of it?

Feel free to open an issue we need to figure out what is the issue with minio-js with keep-alives.

**Comment by harshavardhana** [comment] 2017-11-04 07:52
Closing this, since this is a bug in https://github.com/minio/minio-js/issues/641 and the relevant PR https://github.com/minio/minio-js/issues/640

**Closed as completed by harshavardhana** 2017-11-04 07:52 UTC
Labels: working as intended, priority: medium
