### ISSUE TITLE
Unable to upgrade storage between versions

### ISSUE THREAD

**Issue by mrsrvman** [minio/minio#8968] opened 2020-02-08 04:41 UTC
## Expected Behavior

Upgrade between minor versions without pain

## Steps to Reproduce (for bugs)

1. Update to minio.RELEASE.2020-02-07T23-28-16 or RELEASE.2020-02-07T04-56-50Z
2. Run the command `systemctl restart minio` on the one node.
3. Run the command `systemctl status minio` or look at the logs.
4. Error ...
```
Feb  8 03:44:17 doc-node01 minio: Exiting on signal: TERMINATED
Feb  8 03:44:17 doc-node01 systemd: Stopped Minio.
Feb  8 03:44:17 doc-node01 systemd: Starting Minio...
Feb  8 03:44:17 doc-node01 systemd: Started Minio.
Feb  8 03:44:19 doc-node01 minio: Waiting for a minimum of 2 disks to come online (elapsed 1s)
Feb  8 03:44:20 doc-node01 minio: Waiting for a minimum of 2 disks to come online (elapsed 1s)
Feb  8 03:44:20 doc-node01 minio: 2020/02/08 03:44:20 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:44:20 doc-node01 minio: 2020/02/08 03:44:20 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:44:20 doc-node01 minio: Waiting for a minimum of 2 disks to come online (elapsed 2s)
Feb  8 03:44:21 doc-node01 minio: Waiting for a minimum of 2 disks to come online (elapsed 2s)
Feb  8 03:44:21 doc-node01 minio: Waiting for a minimum of 2 disks to come online (elapsed 3s)
Feb  8 03:44:22 doc-node01 minio: Waiting for a minimum of 2 disks to come online (elapsed 3s)
Feb  8 03:44:22 doc-node01 minio: Waiting for a minimum of 2 disks to come online (elapsed 4s)
Feb  8 03:44:23 doc-node01 minio: Waiting for a minimum of 2 disks to come online (elapsed 4s)
```
5. Repeat step 2-3 on other machines in the cluster.
5. Logs
```
Feb  8 03:45:31 doc-node01 minio: API: SYSTEM()
Feb  8 03:45:31 doc-node01 minio: Time: 03:45:31 UTC 02/08/2020
Feb  8 03:45:31 doc-node01 minio: Error: Authentication failed, check your access credentials
Feb  8 03:45:31 doc-node01 minio: endpoint=http://10.101.x.xx:9000/data
Feb  8 03:45:31 doc-node01 minio: 6: cmd/prepare-storage.go:50:cmd.glob..func5.1()
Feb  8 03:45:31 doc-node01 minio: 5: cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()
Feb  8 03:45:31 doc-node01 minio: 4: cmd/xl-sets.go:326:cmd.newXLSets()
Feb  8 03:45:31 doc-node01 minio: 3: cmd/xl-zones.go:76:cmd.newXLZones()
Feb  8 03:45:31 doc-node01 minio: 2: cmd/server-main.go:453:cmd.newObjectLayer()
Feb  8 03:45:31 doc-node01 minio: 1: cmd/server-main.go:373:cmd.serverMain()
Feb  8 03:45:31 doc-node01 minio: API: SYSTEM()
Feb  8 03:45:31 doc-node01 minio: Time: 03:45:31 UTC 02/08/2020
Feb  8 03:45:31 doc-node01 minio: Error: Authentication failed, check your access credentials
Feb  8 03:45:31 doc-node01 minio: endpoint=http://10.101.x.xx:9000/data
Feb  8 03:45:31 doc-node01 minio: 6: cmd/prepare-storage.go:50:cmd.glob..func5.1()
Feb  8 03:45:31 doc-node01 minio: 5: cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()
Feb  8 03:45:31 doc-node01 minio: 4: cmd/xl-sets.go:326:cmd.newXLSets()
Feb  8 03:45:31 doc-node01 minio: 3: cmd/xl-zones.go:76:cmd.newXLZones()
Feb  8 03:45:31 doc-node01 minio: 2: cmd/server-main.go:453:cmd.newObjectLayer()
Feb  8 03:45:31 doc-node01 minio: 1: cmd/server-main.go:373:cmd.serverMain()
Feb  8 03:45:54 doc-node01 minio: Status:         3 Online, 1 Offline.
```

```
Feb  8 03:45:49 doc-node02 systemd: Stopped Minio.
Feb  8 03:45:49 doc-node02 systemd: Starting Minio...
Feb  8 03:45:49 doc-node02 systemd: Started Minio.
Feb  8 03:45:50 doc-node02 minio: API: SYSTEM()
Feb  8 03:45:50 doc-node02 minio: Time: 03:45:50 UTC 02/08/2020
Feb  8 03:45:50 doc-node02 minio: Error: Authentication failed, check your access credentials
Feb  8 03:45:50 doc-node02 minio: endpoint=http://10.101.x.xx:9000/data
Feb  8 03:45:50 doc-node02 minio: 6: cmd/prepare-storage.go:50:cmd.glob..func5.1()
Feb  8 03:45:50 doc-node02 minio: 5: cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()
Feb  8 03:45:50 doc-node02 minio: 4: cmd/xl-sets.go:326:cmd.newXLSets()
Feb  8 03:45:50 doc-node02 minio: 3: cmd/xl-zones.go:76:cmd.newXLZones()
Feb  8 03:45:50 doc-node02 minio: 2: cmd/server-main.go:453:cmd.newObjectLayer()
Feb  8 03:45:50 doc-node02 minio: 1: cmd/server-main.go:373:cmd.serverMain()
Feb  8 03:45:55 doc-node02 minio: 2020/02/08 03:45:55 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:56 doc-node02 minio: 2020/02/08 03:45:56 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:56 doc-node02 minio: 2020/02/08 03:45:56 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:56 doc-node02 minio: 2020/02/08 03:45:56 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:59 doc-node02 minio: Status:         3 Online, 1 Offline.
Feb  8 03:45:59 doc-node02 minio: Endpoint:  http://10.101.x.xxx:9000  http://127.0.0.1:9000
Feb  8 03:45:59 doc-node02 minio: SQS ARNs:  arn:minio:sqs::1:webhook
Feb  8 03:45:59 doc-node02 minio: Browser Access:
```

```
Feb  8 03:45:30 doc-node03 systemd: Stopped Minio.
Feb  8 03:45:30 doc-node03 systemd: Starting Minio...
Feb  8 03:45:30 doc-node03 systemd: Started Minio.
Feb  8 03:45:31 doc-node03 minio: API: SYSTEM()
Feb  8 03:45:31 doc-node03 minio: Time: 03:45:31 UTC 02/08/2020
Feb  8 03:45:31 doc-node03 minio: Error: Authentication failed, check your access credentials
Feb  8 03:45:31 doc-node03 minio: endpoint=http://10.101.x.xx:9000/data
Feb  8 03:45:31 doc-node03 minio: 6: cmd/prepare-storage.go:50:cmd.glob..func5.1()
Feb  8 03:45:31 doc-node03 minio: 5: cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()
Feb  8 03:45:31 doc-node03 minio: 4: cmd/xl-sets.go:326:cmd.newXLSets()
Feb  8 03:45:31 doc-node03 minio: 3: cmd/xl-zones.go:76:cmd.newXLZones()
Feb  8 03:45:31 doc-node03 minio: 2: cmd/server-main.go:453:cmd.newObjectLayer()
Feb  8 03:45:31 doc-node03 minio: 1: cmd/server-main.go:373:cmd.serverMain()
Feb  8 03:45:31 doc-node03 minio: API: SYSTEM()
Feb  8 03:45:31 doc-node03 minio: Time: 03:45:31 UTC 02/08/2020
Feb  8 03:45:31 doc-node03 minio: Error: Authentication failed, check your access credentials
Feb  8 03:45:31 doc-node03 minio: endpoint=http://10.101.x.xx:9000/data
Feb  8 03:45:31 doc-node03 minio: 6: cmd/prepare-storage.go:50:cmd.glob..func5.1()
Feb  8 03:45:31 doc-node03 minio: 5: cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()
Feb  8 03:45:31 doc-node03 minio: 4: cmd/xl-sets.go:326:cmd.newXLSets()
Feb  8 03:45:31 doc-node03 minio: 3: cmd/xl-zones.go:76:cmd.newXLZones()
Feb  8 03:45:31 doc-node03 minio: 2: cmd/server-main.go:453:cmd.newObjectLayer()
Feb  8 03:45:31 doc-node03 minio: 1: cmd/server-main.go:373:cmd.serverMain()
Feb  8 03:45:33 doc-node03 systemd: Stopping Minio...
Feb  8 03:45:55 doc-node03 minio: 2020/02/08 03:45:55 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:56 doc-node03 minio: 2020/02/08 03:45:56 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:56 doc-node03 minio: 2020/02/08 03:45:56 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:56 doc-node03 minio: 2020/02/08 03:45:56 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:59 doc-node03 minio: Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: Config encryption process stopped gracefully'
Feb  8 03:45:59 doc-node03 minio: Server switching to safe mode
Feb  8 03:45:59 doc-node03 minio: Please use 'mc admin config' commands fix this issue
Feb  8 03:45:59 doc-node03 minio: Status:         3 Online, 1 Offline.
Feb  8 03:45:59 doc-node03 minio: Endpoint:  http://10.101.x.xx:9000  http://127.0.0.1:9000
```

```

Feb  8 03:45:20 doc-node04 minio: Time: 03:45:20 UTC 02/08/2020
Feb  8 03:45:20 doc-node04 minio: DeploymentID: 2193f469-c66a-4faa-9964-7835f80eedd1
Feb  8 03:45:20 doc-node04 minio: Error: Authentication failed, check your access credentialsinvalid request
Feb  8 03:45:20 doc-node04 minio: 2: cmd/notification.go:279:cmd.(*NotificationSys).BackgroundOpsStatus()
Feb  8 03:45:20 doc-node04 minio: 1: cmd/daily-lifecycle-ops.go:84:cmd.startDailyLifecycle()
Feb  8 03:45:31 doc-node04 minio: 2020/02/08 03:45:31 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:31 doc-node04 minio: 2020/02/08 03:45:31 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:31 doc-node04 minio: 2020/02/08 03:45:31 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb  8 03:45:32 doc-node04 minio: 2020/02/08 03:45:32 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)

```
## Regression
 Yes

## Your Environment

* Version used (`minio version`): RELEASE.2020-02-07T23-28-16Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: OEL 7.6 
* Operating System and version (`uname -a`): Linux doc-node01 3.10.0-957.21.3.el7.x86_64 #1 SMP Mon Jun 17 15:42:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment] 2020-02-08 08:31
This is expected, we have breaking changes between these versions and rolling upgrade is not supported as mentioned in release notes.

Closing this issue as working as intended.

**Comment by harshavardhana** [comment] 2020-02-08 08:33
Upgrade process is very simple, just do `mc admin update` and `mc admin restart` 

If you don't have internet access, then just replace the binary on all servers and systemctl restart minio

**Comment by mrsrvman** [comment] 2020-02-08 09:29
That is exactly what I do.
Manual update of the binary in the system and restart.
If there is no breaking change in the release description, everything worked without errors until the RELEASE.2020-01-25T02-50-51Z version

**Comment by harshavardhana** [comment] 2020-02-08 09:31
> That is exactly what I do.
> Manual update of the binary in the system and restart.
> If there is no breaking change in the release description, everything worked without errors until the RELEASE.2020-01-25T02-50-51Z version

We forgot to mention that @mrsrvman we will update the release notes // cc @kannappanr

**Comment by harshavardhana** [comment] 2020-02-08 09:35
> Manual update of the binary in the system and restart.

I don't think that is what you did 

> Feb  8 03:45:59 doc-node03 minio: Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: Config encryption process stopped gracefully'

Here you stopped server in between before it was even fully up. 

> Feb  8 03:45:31 doc-node03 minio: Error: Authentication failed, check your access credentials

Looks like you have some older servers running in which you were restarting one server. What I meant is you should restart all of them because older versions won't be able to talk to each other.

**Comment by harshavardhana** [comment] 2020-02-08 13:14
Reopening this issue until we clarify our release notes.

**Comment by kannappanr** [comment] 2020-02-10 17:27
release notes have been updated

**Closed as completed by kannappanr** 2020-02-10 17:27 UTC
Labels: community, triage

**Comment by mrsrvman** [comment] 2020-02-21 05:12
RELEASE.2020-02-20T22-51-23Z
Again, updates without specifying "Breaking Change"?

**Comment by harshavardhana** [comment] 2020-02-21 05:21
There are no breaking changes in the newer release @mrsrvman

**Comment by mrsrvman** [comment] 2020-02-21 05:26
```
Feb 21 04:53:10 doc-node01 minio: API: SYSTEM()
Feb 21 04:53:10 doc-node01 minio: Time: 04:53:10 UTC 02/21/2020
Feb 21 04:53:10 doc-node01 minio: DeploymentID: 2193f469-c66a-4faa-9964-7835f80eedd1
Feb 21 04:53:10 doc-node01 minio: Error: Authentication failed, check your access credentialsinvalid request
Feb 21 04:53:10 doc-node01 minio: 2: cmd/notification.go:279:cmd.(*NotificationSys).BackgroundOpsStatus()
Feb 21 04:53:10 doc-node01 minio: 1: cmd/daily-lifecycle-ops.go:84:cmd.startDailyLifecycle()
Feb 21 04:53:20 doc-node01 minio: 2020/02/21 04:53:20 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb 21 04:53:20 doc-node01 minio: 2020/02/21 04:53:20 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb 21 04:53:20 doc-node01 minio: 2020/02/21 04:53:20 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb 21 04:53:20 doc-node01 minio: 2020/02/21 04:53:20 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb 21 04:53:20 doc-node01 minio: 2020/02/21 04:53:20 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
```
```
Feb 21 04:53:10 doc-node02 minio: 2020/02/21 04:53:10 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb 21 04:53:10 doc-node02 minio: 2020/02/21 04:53:10 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb 21 04:53:10 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 1s)
Feb 21 04:53:11 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 1s)
Feb 21 04:53:11 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 2s)
Feb 21 04:53:12 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 2s)
Feb 21 04:53:12 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 3s)
Feb 21 04:53:13 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 3s)
Feb 21 04:53:13 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 4s)
Feb 21 04:53:14 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 4s)
Feb 21 04:53:14 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 5s)
Feb 21 04:53:15 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 5s)
Feb 21 04:53:15 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 6s)
Feb 21 04:53:15 doc-node02 minio: 2020/02/21 04:53:15 http: superfluous response.WriteHeader call from github.com/minio/minio/cmd.(*recordTrafficResponse).WriteHeader (http-traffic-recorder.go:50)
Feb 21 04:53:16 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 6s)
Feb 21 04:53:16 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 7s)
Feb 21 04:53:17 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 7s)
Feb 21 04:53:17 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 8s)
Feb 21 04:53:18 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 8s)
Feb 21 04:53:18 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 9s)
Feb 21 04:53:19 doc-node02 minio: Waiting for a minimum of 2 disks to come online (elapsed 9s)
Feb 21 04:53:19 doc-node02 minio: API: SYSTEM()
Feb 21 04:53:19 doc-node02 minio: Time: 04:53:19 UTC 02/21/2020
Feb 21 04:53:19 doc-node02 minio: Error: Authentication failed, check your access credentials
Feb 21 04:53:19 doc-node02 minio: endpoint=http://10.101.6.65:9000/data
Feb 21 04:53:19 doc-node02 minio: 6: cmd/prepare-storage.go:50:cmd.glob..func5.1()
Feb 21 04:53:19 doc-node02 minio: 5: cmd/xl-sets.go:183:cmd.(*xlSets).connectDisksWithQuorum()
Feb 21 04:53:19 doc-node02 minio: 4: cmd/xl-sets.go:326:cmd.newXLSets()
Feb 21 04:53:19 doc-node02 minio: 3: cmd/xl-zones.go:75:cmd.newXLZones()
Feb 21 04:53:19 doc-node02 minio: 2: cmd/server-main.go:453:cmd.newObjectLayer()
Feb 21 04:53:19 doc-node02 minio: 1: cmd/server-main.go:373:cmd.serverMain()
```
Cured after restarting all minio nodes
