### ISSUE TITLE
Minio server with TLS

### ISSUE THREAD

**Issue by pierremartins507** [minio/minio#4693] opened 2017-07-19 09:41 UTC
* Version used (`minio version`): 
Version: 2017-06-13T19:01:01Z
Release-Tag: RELEASE.2017-06-13T19-01-01Z
Commit-ID: 353f2d3a6e30f595a721abcd9cf1b108b041ee21

* Server type and version: Docker (minio/minio:latest)
* Operating System and version (`uname -a`):
* Link to your project: https://prefiles.goodship.eu:9000/minio/login

Hello,

I have read the documentation (https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls) for generate key/certificate avec Openssl. I have installer certificat on /.minio/certs
So, when I want used https, I have this error : SSL_ERROR_INTERNAL_ERROR_ALERT

I have installed the Docker Minio in Rancher environment.

Thanks for your help.

Pierre.

**Comment by vadmeste** [comment] 2017-07-19 11:51
@pierremartins507, Minio is not responsible for this issue. 

You need to follow this link https://docs.minio.io/docs/generate-let-s-encypt-certificate-using-concert-for-minio to create free TLS certificates for your domain prefiles.goodship.eu:9000 that can be validated by all clients.

**Comment by donatello** [comment] 2017-07-19 12:18
@pierremartins507 If I access your server over http, I see that the login page is served. This means that the server has not picked up the tls certificates that you have configured. Minio server expects the certificates to be at `$HOME/.minio/certs`. So if you are running as root within your container, the certs should be at `/root/.minio/certs/`.

**Comment by pierremartins507** [comment] 2017-07-19 13:20
I have installed tls certificates here : /root/.minio/certs
I have :  private.key  public.crt

**Comment by krishnasrinivas** [comment] 2017-07-19 19:43
@pierremartins507 can you confirm that you are mapping the volumes from host to the container using `-v` so that the container has access to the certificate available on the host.

I just verified that minio is picking up the certs fine on my local setup.

**Comment by deekoder** [comment] 2017-07-21 17:23
@pierremartins507 - will go ahead and close this issue as working as intended. Please feel free to reopen if its still not working for you.

**Closed as completed by deekoder** 2017-07-21 17:23 UTC
Labels: working as intended, priority: medium, triage
