### ISSUE TITLE
minio server fails to start over CephFS storage directory

### ISSUE THREAD

**Issue by jperville** [minio/minio#2425] opened 2016-08-12 12:54 UTC
## Expected behaviour

Minio server should start when run over a CephFS directory.
## Actual behaviour

Minio server does not start and fails with the following error message:

```
FATA[0000] Unable to intialize object layer.             cause=Storage reached its minimum free disk threshold. sysInfo=map[host.cpus:2 mem.used:3.0MB mem.heap.total:5.8MB host.os:linux host.arch:amd64 host.name:compute-1-vm host.lang:go1.6 mem.total:8.8MB mem.heap.used:3.0MB] type=main.StorageFull
```
## Steps to reproduce the behaviour
1. deploy ceph latest release (currently "jewel"), mount CephFS into `/ceph`
2. download minio latest release into `/root/minio` and chmod +x it
3. run `/root/minio server /ceph/minio` and observe error message

Note: this seems to be CephFS-specific since I ran the same scenario over an NFS mountpoint and minio server booted successfully.

Real-world transcript:

```
root@compute-1-vm:~# wget https://dl.minio.io/server/minio/release/linux-amd64/minio
--2016-08-12 12:43:15--  https://dl.minio.io/server/minio/release/linux-amd64/minio
Connecting to 10.0.3.84:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 15673488 (15M) [application/octet-stream]
Saving to: ‘minio’

 0% [                                       ] 40,960       120KB/s             c 1% [                                       ] 188,416      275KB/s             m100%[======================================>] 15,673,488  2.50MB/s   in 7.0s   

2016-08-12 12:43:23 (2.13 MB/s) - ‘minio’ saved [15673488/15673488]

root@compute-1-vm:~# chmod +x minio 
root@compute-1-vm:~# mkdir /ceph/minio
root@compute-1-vm:~# ./minio server /ceph/minio
FATA[0000] Unable to intialize object layer.             cause=Storage reached its minimum free disk threshold. sysInfo=map[host.cpus:2 mem.used:3.0MB mem.heap.total:5.8MB host.os:linux host.arch:amd64 host.name:compute-1-vm host.lang:go1.6 mem.total:8.8MB mem.heap.used:3.0MB] type=main.StorageFull
root@compute-1-vm:~# df -h /ceph/minio/
Filesystem      Size  Used Avail Use% Mounted on
ceph-fuse       115G   58G   58G  50% /ceph
root@compute-1-vm:~# 
```
## Minio version

```
Version: 2016-07-13T21:46:05Z
Release-Tag: RELEASE.2016-07-13T21-46-05Z
Commit-ID: 3f27734c22212f224037a223439a425e6d2b653a
```
## System information

``` sh
root@compute-1-vm:~# uname -a
Linux compute-1-vm 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by krishnasrinivas** [comment] 2016-08-12 13:21
@jperville can you check if enough inodes are available `df -i`

**Comment by jperville** [comment] 2016-08-12 13:23
Hi @krishnasrinivas , I think you are on something!

``` sh
vagrant@compute-1-vm:~$ df -i /ceph
Filesystem     Inodes IUsed IFree IUse% Mounted on
ceph-fuse         274     -     -     - /ceph
vagrant@compute-1-vm:~$ df /ceph
Filesystem     1K-blocks     Used Available Use% Mounted on
ceph-fuse      120385536 60092416  60293120  50% /ceph
vagrant@compute-1-vm:~$ 
```

**Comment by krishnasrinivas** [comment] 2016-08-12 13:49
weird, can you check with ceph team why it does not show user/free inodes?

**Comment by krishnasrinivas** [comment] 2016-08-12 14:23
Not much info on the internet http://www.spinics.net/lists/ceph-users/msg16882.html

**Comment by jperville** [comment] 2016-08-12 14:38
The link you show is not about CephFS not reporting inode statistics, I will look up on Ceph issue tracker and submit issue there is needed. For moment I run minio on non-cephfs to workaround this issue. Thank you for the help @krishnasrinivas

**Comment by krishnasrinivas** [comment] 2016-08-12 15:09
@jperville you are right, let us know what they say.

**Comment by gjonespf** [comment] 2016-08-12 23:42
Just a FYI - Having a similar issue with this using [azurefile docker driver](https://github.com/Azure/azurefile-dockervolumedriver) mounted in docker, with very similar symptoms:

> df -i /mnt/host
> Inodes IUsed IFree IUse% Mounted on
>       0     0     0     - /mnt/host
> df /mnt/host
> 1K-blocks  Used Available Use% Mounted on
> 10485760    64  10485696   1% /mnt/host

So it's reporting free space, but not inodes correctly.  I'll follow up with azurefile, but any way to "ignore" this in minio via options?

**Comment by harshavardhana** [comment] 2016-08-13 08:59
Closing as duplicate of #2364

**Closed as completed by harshavardhana** 2016-08-13 08:59 UTC

**Comment by jperville** [comment] 2016-08-13 10:37
Thank you everyone for the quick fix on this issue. Cheers!
