### ISSUE TITLE
High availability is broken when one node is down for maintenance purpose

### ISSUE THREAD

**Issue by loicveyssiere** [minio/minio#7964] opened 2019-07-23 14:30 UTC
Hello,

I have a setup of 12 nodes with one disk per node. The cluster is running well
in distributed mode and is able to continue correctly when one Minio process of
a machine is killed. However during an update of one of my machines (the machine
is still on but the OS is not loaded on it), the cluster is so slow that it 
becomes impossible to use it.

## Expected Behavior

During the update of my machines (rolling strategy), I expect minio to continue
to work correctly in cluster mode.

## Current Behavior

When 1 machine over 12 is updating, the cluster of 11 machines is to slow that 
it is impossible to use it. When I open Minio UI, I am able to access to the
website but it needs a few minutes to list a single document on the main page. 

## Possible Solution

Seems like Minio didn't manage to exclude the failing node from the grid.

## Steps to Reproduce (for bugs)

1. Start a cluster Minio on multiple machines (12 in my case), single disk on each
2. Restart one node and block the restart at the boot to simulate a machine
switched on but with the OS not loaded yet
3. try to use the cluster in this configuration

## Context

High availability scenario is broken this way.

Info of the cluster during the failure

```log
●  10.0.0.7:9000
   Status : online
   Uptime : 3 hours 
  Version : 2019-07-17T22:54:12Z
  Storage : Used 2.3 PiB
   Drives : 1/1 OK

●  10.0.0.8:9000
   Status : offline
    Error : Post http://10.0.0.8:9000/minio/peer/v2/serverinfo?: dial tcp 10.0.0.8:9000: connect: connection timed out
●  10.0.0.9:9000
   Status : online
   Uptime : 3 hours 
  Version : 2019-07-17T22:54:12Z
  Storage : Used 2.3 PiB
   Drives : 1/1 OK
```

Intercepted log during the failure

```log
API: SYSTEM()
Time: 13:50:46 CEST 07/23/2019
DeploymentID: a69eb2a5-9d10-42b5-b598-94cd5ec4596b
Error: Post http://10.0.0.8:9000/minio/peer/v2/serverinfo?: dial tcp 10.0.0.8:9000: connect: connection timed out
    peerAddress=10.0.0.8:9000
    1: cmd/notification.go:406:cmd.(*NotificationSys).ServerInfo.func1()
```

## Regression

Is this issue a regression? No
But seems related to[#7618](https://github.com/minio/minio/issues/7618)

## Your Environment

* Version used (`minio version`):
  Version: 2019-07-17T22:54:12Z
  Release-Tag: RELEASE.2019-07-17T22-54-12Z
  Commit-ID: ea66a52ed165e1dfd45c5ce7eba23d3f273f2974

* Operating System and version (`uname -a`): Linux 'machine name' 3.10.0-862.3.3.el7.x86_64 #1 SMP Wed Jun 13 05:44:23 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitisht** [comment] 2019-07-23 14:33
Thanks for reporting @loicveyssiere we'll take a look

**Comment by harshavardhana** [comment] 2019-07-23 14:36
The issue referenced is not related here, the issue is perhaps the timeouts we have internally which is almost 1minute

**Comment by loicveyssiere** [comment] 2019-07-23 14:45
For information, my machine was down for many hours and minio wasn't able to recover correctly even after 6 hours.

**Comment by harshavardhana** [comment] 2019-07-23 14:56
Are you saying you had I/o failures? Was it just slow for any I/o?

**Comment by loicveyssiere** [comment] 2019-07-23 15:18
Well, there is no failure in general but a single operation like read can take a few minutes, so for any usage it is like a failure. for example I was able to get the info of the cluster using `mc admin info <target>`, the command terminates correctly after a few minutes (normally it is like instantaneous). The same for the website, I wait many seconds or perhaps minutes to only open a folder in the UI.

**Comment by harshavardhana** [comment] 2019-07-23 15:38
Correct the slowness here is currently expected because of the internal retries to the downed server and the amount of timeout we might have for such dial timeouts.

Fundamentally to know if the server is down or not is a hard problem. Since variations in many ways a system can go down are different and each code path behaves differently in different scenarios. 

Here is how I saw in a simple 4 node setup 

```
~ time mc admin info myminio-local1
●  127.0.0.1:9001
   Uptime: 1 minute 
  Version: 2019-07-23T15:24:17Z
  Storage: Used 87 KiB
   Drives: 1/1 OK

●  127.0.0.1:9002
   Uptime: offline
    Error: Post http://127.0.0.1:9002/minio/peer/v2/serverinfo?: dial tcp 127.0.0.1:9002: connect: connection refused
●  127.0.0.1:9003
   Uptime: 1 minute 
  Version: 2019-07-23T15:24:17Z
  Storage: Used 78 KiB
   Drives: 1/1 OK

●  127.0.0.1:9004
   Uptime: 1 minute 
  Version: 2019-07-23T15:24:17Z
  Storage: Used 85 KiB
   Drives: 1/1 OK


real	0m2.132s
user	0m0.128s
sys	0m0.019s
```

```
~ mc cp /etc/hosts myminio-local1/testbucket/
mc: <ERROR> Failed to copy `/etc/hosts`. Bucket `testbucket` does not exist.
```
```
~ mc mb myminio-local1/testbucket/
Bucket created successfully `myminio-local1/testbucket/`.
~ mc cp /etc/hosts myminio-local1/testbucket/
/etc/hosts:            836 B / 836 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 37.11 KiB/s 0s
```

There seems to be no visible difference in behavior when the node is completely down. The problem in your case is the node is partially up.  Such as the IP itself is not assigned or the OS is halfway there in such a scenario our dial doesn't get a response fast enough to know if the node is offline. Now if the response is not forthcoming we timeout in 1minute - which is what you see on your end as `"timed out"` 

We also periodically check if the disk is down almost every 10 secs in a separate routine and bring it online automatically if its a correct disk. 

But I can see why the network timeout is not ignoring the disk - because sometime in the last 3 months our error types have changed and the code looking at this is not honoring the error types anymore. So timeout is not ignored for the second call. 

There will be a visible delay in the first attempt but there shouldn't be any delay subsequently since we turned the disk off.

**Comment by harshavardhana** [comment] 2019-08-12 18:30
Duplicate of #8016

**Closed as completed by harshavardhana** 2019-08-12 18:30 UTC
Labels: duplicate, community, priority: medium
