### ISSUE TITLE
Can not list buckets using hadoop fs -ls ....

### ISSUE THREAD

**Issue by ravindraSB** [minio/minio#7919] opened 2019-07-12 08:04 UTC
**Expected Behavior**
Should list buckets with hadoop fs -ls

**Current Behavior**
[root@quickstart downloads]# hadoop fs -ls s3a://myminio/mybucket/
ls: Bucket myminio does not exist

**Possible Solution**

**Steps to Reproduce (for bugs)**

1. download docker image of quickstart-cloudera from docker hub or from cloudera. 
2. docker exec into the container.
3. Have followed this "https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls#generate-use-self-signed-keys-certificates" and this "https://github.com/minio/minio/issues/5232" to generate certs -
4. AND rest is from within the container. downloaded minio and mc and then - 

[root@quickstart downloads]# ./minio server --address quickstart.cloudera:9009 /data

[root@quickstart downloads]# ./mc mb /myminio/mybucket
Bucket created successfully `/myminio/mybucket`.

[root@quickstart downloads]# ./mc ls /myminio
[2019-07-12 07:36:38 UTC]  4.0KiB mybucket/
[root@quickstart downloads]#

[root@quickstart downloads]# hadoop fs -ls s3a://myminio/mybucket/
ls: Bucket myminio does not exist

**Context**
My core-site.xml in hadoop/conf -
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

<configuration>
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://quickstart.cloudera:8020</value>
  </property>

  
  <property>
    <name>hadoop.proxyuser.oozie.hosts</name>
    <value>*</value>
  </property>
  <property>
    <name>hadoop.proxyuser.oozie.groups</name>
    <value>*</value>
  </property>

  
  <property>
    <name>hadoop.proxyuser.httpfs.hosts</name>
    <value>*</value>
  </property>
  <property>
    <name>hadoop.proxyuser.httpfs.groups</name>
    <value>*</value>
  </property>

  
  <property>
    <name>hadoop.proxyuser.llama.hosts</name>
    <value>*</value>
  </property>
  <property>
    <name>hadoop.proxyuser.llama.groups</name>
    <value>*</value>
  </property>

  
  <property>
    <name>hadoop.proxyuser.hue.hosts</name>
    <value>*</value>
  </property>
  <property>
    <name>hadoop.proxyuser.hue.groups</name>
    <value>*</value>
  </property>

    <property>
        <name>fs.default.name</name>
        <value>hdfs://quickstart.cloudera:9000</value>
    </property>

    
    <property>
        <name>fs.s3a.connection.ssl.enabled</name>
        <value>true</value>
    </property>

    <property>
        <name>fs.s3a.endpoint</name>
        <value>http://myminio:9009</value>
    </property>

    <property>
        <name>fs.s3a.awsAccessKeyId</name>
        <value>XXXXX</value>
    </property>

    <property>
        <name>fs.s3a.awsSecretAccessKey</name>
        <value>XXXXX</value>
    </property>

    <property>
        <name>fs.s3a.path.style.access</name>
        <value>true</value>
    </property>

    <property>
        <name>fs.s3a.impl</name>
        <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
    </property>
</configuration>

**Your Environment**
using cloudera-quickstart docker.

**Version used (minio version):**
[root@quickstart downloads]# ./minio version
Version: 2019-07-10T00:34:56Z
Release-Tag: RELEASE.2019-07-10T00-34-56Z
Commit-ID: 9d49688c87e9c7c3f769833c3a8697d16349f6c0

Environment name and version (e.g. nginx 1.9.1):
N/A

Operating System and version (uname -a):
Linux quickstart.cloudera 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2019-07-12 08:05
> [root@quickstart downloads]# ./mc mb /myminio/mybucket

you don't create the bucket @ravindraSB - you need to create like this`./mc mb myminio/mybucket`

**Comment by harshavardhana** [comment] 2019-07-12 08:06
Now before this, you have to first configure the `mc` command @ravindraSB using `mc config host add`

**Comment by harshavardhana** [comment] 2019-07-12 08:07
> [root@quickstart downloads]# hadoop fs -ls s3a://myminio/mybucket/

There is no such thing as `myminio` on hadoop in this scenario, `myminio` is an alias for `mc` - all you need to after you created the bucket is `hadoop fs -ls s3a://mybucket`

**Comment by harshavardhana** [comment] 2019-07-12 08:07
> [root@quickstart downloads]# ./mc ls /myminio
> [2019-07-12 07:36:38 UTC] 4.0KiB mybucket/
> [root@quickstart downloads]#

This actually is a local directory because `myminio` is not configured yet to talk to an object storage instance.

**Comment by ravindraSB** [comment] 2019-07-12 08:15
> Now before this, you have to first configure the `mc` command @ravindraSB using `mc config host add`

_> This I had done already using mc config host, as shown in the output of ./minio server --address quickstart.cloudera:9009 /data ---
>      $ mc config host add myminio http://quickstart.cloudera:9009 XXX    XXXX_

also this -

_> [root@quickstart downloads]# hadoop fs -ls s3a://mybucket/
> ls: Bucket mybucket does not exist_

**Comment by ravindraSB** [comment] 2019-07-12 08:17
> > [root@quickstart downloads]# ./mc ls /myminio
> > [2019-07-12 07:36:38 UTC] 4.0KiB mybucket/
> > [root@quickstart downloads]#
> 
> This actually is a local directory because `myminio` is not configured yet to talk to an object storage instance.

yup, I understand, I am not sure what is wrong wrt communication b/w hadoop and minio.

**Comment by harshavardhana** [comment] 2019-07-12 08:20
> yup, I understand, I am not sure what is wrong wrt communication b/w hadoop and minio.

The whole bunch of things the entire configuration is wrong 

- `mc` shouldn't be talking to quickstart.cloudera:9000 there is no service on this hostname
- This hostname is meant for docker container for cloudera services
- minio is running locally - you said you configured certs but you are using http:// endpoint in core-site.xml 

So there is a lot of things that needs to be fixed @ravindraSB it is better for you to join https://slack.min.io so that we can help you out real time.

**Comment by harshavardhana** [comment] 2019-07-12 09:17
Closing this issue as working as intended.

**Closed as completed by harshavardhana** 2019-07-12 09:17 UTC
Labels: working as intended, community, triage
