### ISSUE TITLE
Remove an incomplete upload doesn't work?

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#1664] opened 2016-05-17 19:45 UTC
Removing incomplete upload seems to be not working as expected :

```
$ mc rm --incomplete --recursive --force myminio/bucket/
Removed ‘myminio/bucket/128mb.bin’.
$ mc rm --incomplete --recursive --force myminio/bucket/
Removed ‘myminio/bucket/128mb.bin’.
```

**Comment by krishnasrinivas** [comment] 2016-05-17 20:09
might be related to https://github.com/minio/minio/issues/1663

**Comment by harshavardhana** [comment] 2016-05-18 02:01
Closing as duplicate of #1663

**Closed as completed by harshavardhana** 2016-05-18 02:01 UTC
