### ISSUE TITLE
Operation PUT Object - Copy, incorrect respone

### ISSUE THREAD

**Issue by stepanovdmitrii** [minio/minio#6194] opened 2018-07-24 06:37 UTC
In accordance with the S3 API, PUT Object - Copy should return response without xml namespace, but minio's implementation returns response with xml namespace.

## Expected Behavior

Method PUT Object - Copy should return a response like this:

```
<CopyObjectResult>
        <LastModified>...</LastModified>
        <ETag>...</ETag>
</CopyObjectResult>
```

## Current Behavior

Method PUT Object - Copy should return a response like this:

```
<CopyObjectResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
               <LastModified>...</LastModified> 
              <ETag>...</ETag>
</CopyObjectResult>
```

**Comment by harshavardhana** [comment] 2018-07-24 06:41
I think our behavior is correct here is the aws cli output for copy-object API 

```
aws s3api copy-object --debug --copy-source vadmeste/hound.yml --bucket vadmeste --key hound-1.yml
```

```
2018-07-23 23:41:15,647 - MainThread - botocore.hooks - DEBUG - Event before-call.s3.CopyObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f372af3be10>>
2018-07-23 23:41:15,648 - MainThread - botocore.endpoint - DEBUG - Making request for OperationModel(name=CopyObject) (verify_ssl=True) with params: {'body': '', 'url': u'https://s3.amazonaws.com/vadmeste/hound-1.yml', 'headers': {u'x-amz-copy-source': 'vadmeste/hound.yml', 'User-Agent': 'aws-cli/1.11.0 Python/2.7.15rc1 Linux/4.15.0-23-generic botocore/1.8.2'}, 'context': {'auth_type': None, 'client_region': 'us-east-1', 'signing': {'bucket': u'vadmeste'}, 'has_streaming_input': False, 'client_config': <botocore.config.Config object at 0x7f372b4efd90>}, 'query_string': {}, 'url_path': u'/vadmeste/hound-1.yml', 'method': u'PUT'}
2018-07-23 23:41:15,648 - MainThread - botocore.hooks - DEBUG - Event request-created.s3.CopyObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f372b7342d0>>
2018-07-23 23:41:15,648 - MainThread - botocore.hooks - DEBUG - Event choose-signer.s3.CopyObject: calling handler <function set_operation_specific_signer at 0x7f372c3d1c08>
2018-07-23 23:41:15,648 - MainThread - botocore.hooks - DEBUG - Event before-sign.s3.CopyObject: calling handler <function fix_s3_host at 0x7f372c52f9b0>
2018-07-23 23:41:15,649 - MainThread - botocore.auth - DEBUG - Calculating signature using v4 auth.
2018-07-23 23:41:15,649 - MainThread - botocore.auth - DEBUG - CanonicalRequest:
PUT
/vadmeste/hound-1.yml

host:s3.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-copy-source:vadmeste/hound.yml
x-amz-date:20180724T064115Z

host;x-amz-content-sha256;x-amz-copy-source;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2018-07-23 23:41:15,649 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20180724T064115Z
20180724/us-east-1/s3/aws4_request
1ad12933cd0b3d14cc550c6877c96cce480a7e3e6fda13ca8df29867335341d7
2018-07-23 23:41:15,650 - MainThread - botocore.auth - DEBUG - Signature:
7a4080d9c749fe7b416483860e11b44287fc335d9fd3bc81a0c0b9813169eee0
2018-07-23 23:41:15,654 - MainThread - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2018-07-23 23:41:15,656 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): s3.amazonaws.com
2018-07-23 23:41:16,111 - MainThread - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT /vadmeste/hound-1.yml HTTP/1.1" 200 234
2018-07-23 23:41:16,113 - MainThread - botocore.parsers - DEBUG - Response headers: {'content-length': '234', 'x-amz-id-2': 'XeRbLtRjwm+dL4c8y2ex/XSKCnSMj3/x6bnV4385xCH3lSbtJHqy3SxtjK8+D1JKiWitH2nWMOs=', 'server': 'AmazonS3', 'x-amz-request-id': 'B03899B555D8DDB8', 'date': 'Tue, 24 Jul 2018 06:41:17 GMT', 'x-amz-version-id': '5V5eAKq5sV1Sgds8KneIFgKhUXCTS2gJ', 'content-type': 'application/xml'}
2018-07-23 23:41:16,113 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<CopyObjectResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LastModified>2018-07-24T06:41:17.000Z</LastModified><ETag>&quot;26e76a88686441df8de8492984cf8a30&quot;</ETag></CopyObjectResult>
2018-07-23 23:41:16,115 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CopyObject: calling handler <function check_for_200_error at 0x7f372c3d1b18>
2018-07-23 23:41:16,115 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CopyObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7f372b0e4110>
2018-07-23 23:41:16,116 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2018-07-23 23:41:16,116 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.CopyObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f372af3be10>>
2018-07-23 23:41:16,117 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.CopyObject: calling handler <function enhance_error_msg at 0x7f372b76e9b0>
2018-07-23 23:41:16,117 - MainThread - botocore.session - DEBUG - Loading variable profile from defaults.
2018-07-23 23:41:16,117 - MainThread - botocore.session - DEBUG - Loading variable output from defaults.
2018-07-23 23:41:16,118 - MainThread - awscli.formatter - DEBUG - RequestId: B03899B555D8DDB8
{
    "CopyObjectResult": {
        "LastModified": "2018-07-24T06:41:17.000Z", 
        "ETag": "\"26e76a88686441df8de8492984cf8a30\""
    }, 
    "VersionId": "5V5eAKq5sV1Sgds8KneIFgKhUXCTS2gJ"
}
```

Look at the XML output
```xml
<?xml version="1.0" encoding="UTF-8"?>
<CopyObjectResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LastModified>2018-07-24T06:41:17.000Z</LastModified><ETag>&quot;26e76a88686441df8de8492984cf8a30&quot;</ETag></CopyObjectResult>
```

**Comment by harshavardhana** [comment] 2018-07-24 06:47
@stepanovdmitrii do not go by the documents mentioned here https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html - they are usually incomplete regarding some important details.

The actual behavior of API sometimes varies.

**Comment by stepanovdmitrii** [comment] 2018-07-24 06:49
@harshavardhana but what is it "actual behavior of API" in this case?:)

**Comment by harshavardhana** [comment] 2018-07-24 06:50
> @harshavardhana but what is it "actual behavior of API" in this case?:)

Just run `aws` CLI against AWS S3 and observe the HTTP traffic :-)

**Comment by harshavardhana** [comment] 2018-07-24 06:51
Going to close this issue as working as intended... @stepanovdmitrii  we are behaving same as AWS S3

**Comment by stepanovdmitrii** [comment] 2018-07-24 06:52
@harshavardhana the best API I've seen:)

**Closed as completed by harshavardhana** 2018-07-24 06:51 UTC
Labels: working as intended, community
