### ISSUE TITLE
LDAP auth. Group search doesn't work correct if user dn contains cyrillic symbols

### ISSUE THREAD

**Issue by SteeveRan** [minio/minio#12720] opened 2021-07-15 10:19 UTC
## Expected Behavior

We are using AD for LDAP authorization. Our Minio configs:

```
MINIO_IDENTITY_LDAP_SERVER_ADDR="DC=example,DC=ru:636"
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="CN=ldap,OU=ServiceAccount,OU=org,DC=example,DC=ru"
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="pass"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="OU=Users,OU=org,DC=example,DC=ru"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(sAMAccountName=%s)"
MINIO_IDENTITY_LDAP_USERNAME_FORMAT="cn=%s,OU=Users,OU=org,DC=example,DC=ru"
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="OU=Group,OU=org,DC=example,DC=ru"
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(&(objectclass=group)(member=%d))"
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
MINIO_IDENTITY_LDAP_SERVER_INSECURE=off
```

We expect minio to correctly handle user membership

## Current Behavior

If user dn contains Cyrillic characters, minio cannot find the groups the user belongs to.

## Steps to Reproduce

1. Create user with dn - "cn=Пользователь,OU=Users,OU=org,DC=example,DC=ru"
1. Ldapsearch output for user:

```
dn:: Q0490J/QvtC70YzQt9C+0LLQsNGC0LXQu9GMLE9VPVVzZXJzLE9VPW9yZyxEQz1leGFtcGxlLERDPXJ1
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn:: BASE64STRING
sn:: BASE64STRING
title:: BASE64STRING
physicalDeliveryOfficeName: 108
telephoneNumber: 1111
givenName:: BASE64STRING
distinguishedName:: BASE64STRING
instanceType: 4
displayName:: BASE64STRING
uSNCreated: 39895
memberOf: CN=minio_admin,OU=org,DC=example,DC=ru
name:: BASE64STRING
objectGUID:: BASE64STRING
sAMAccountName: testuser
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=example,DC=ru
```

1. Ldapsearch output for group:

```
dn: CN=vpn-ovpn-croc,OU=Group,OU=org,DC=example,DC=ru
objectClass: top
objectClass: group
cn: vpn-ovpn-croc
member:: Q0490J/QvtC70YzQt9C+0LLQsNGC0LXQu9GMLE9VPVVzZXJzLE9VPW9yZyxEQz1leGFtcGxlLERDPXJ1
name: minio_admin
sAMAccountName: minio_admin
objectCategory: CN=Group,CN=Schema,CN=Configuration,DC=example,DC=ru
```

1. `mc admin user info` output:

```
AccessKey: CN=Пользователь,OU=Users,OU=org,DC=example,DC=ru
Status: 
PolicyName: consoleAdmin
MemberOf: 

```
## Context

Group policies are not assigned to users. Policy assigned to users at the same time work

## Regression

No

## Your Environment:

Minio host:
- Ubuntu 20.04
- minio - RELEASE.2021-07-12T02-44-53Z
- 
Active directory host:
- Windows server 2016

**Comment by vadmeste** [comment] 2021-07-15 14:10
@SteeveRan thanks. I will try to reproduce and update you.

**Comment by donatello** [comment] 2021-07-15 22:21
@SteeveRan There is something wrong with your configuration - you cannot use both lookup bind mode and username format mode simultaneously. You will get an error when the minio server starts up like:

```
API: SYSTEM()
Time: 14:52:02 PDT 07/15/2021
DeploymentID: 3a00fea7-4198-4cbe-a3b8-05145370b5d3
Error: Unable to parse LDAP configuration: Lookup Bind mode and Username Format mode are not supported at the same time (*fmt.wrapError)
       7: cmd/config-current.go:478:cmd.lookupConfigs()
       6: cmd/config-current.go:709:cmd.loadConfig()
       5: cmd/config.go:237:cmd.initConfig()
       4: cmd/config.go:197:cmd.(*ConfigSys).Init()
       3: cmd/server-main.go:389:cmd.initAllSubsystems()
       2: cmd/server-main.go:325:cmd.initServer()
       1: cmd/server-main.go:545:cmd.serverMain()
```

I tried a similar setup to yours (using openldap rather than AD though) with lookup bind mode - https://github.com/donatello/minio-ldap-testing

I added the following lines to the `bootstrap.ldif` file in that test repo:

```
# Add a user with special chars. The password = example here.
dn: uid=Пользователь,OU=people,OU=swengg,DC=min,DC=io
objectClass: inetOrgPerson
cn: Special Charsman
sn: Charsman
uid: Пользователь
userPassword: {SSHA}XQSZqLPvYgm30wR7pk67a1GW+q+DDvSj
```

To make this user a member of a group, I added the last line in the block below:

```
dn: cn=projectb,ou=groups,ou=swengg,dc=min,dc=io
objectclass: groupofnames
cn: projectb
description: Project B group members
member: uid=dillon,ou=people,ou=swengg,dc=min,dc=io
member: uid=liza,ou=people,ou=swengg,dc=min,dc=io
member: uid=fahim,ou=people,ou=swengg,dc=min,dc=io
member: uid=Пользователь,OU=people,OU=swengg,DC=min,DC=io
```

So now, this user is a member of the group `dn: cn=projectb,ou=groups,ou=swengg,dc=min,dc=io`. Now, after assiging policies like:

```
$ mc admin policy set myminio readonly user=uid=Пользователь,ou=people,ou=swengg,dc=min,dc=io
Policy `readonly` is set on user `uid=Пользователь,ou=people,ou=swengg,dc=min,dc=io`
$ mc admin policy set myminio consoleAdmin group=cn=projectb,ou=groups,ou=swengg,dc=min,dc=io
Policy `consoleAdmin` is set on group `cn=projectb,ou=groups,ou=swengg,dc=min,dc=io`
```
I requested credentials with the STS API (with the script at `docs/sts/ldap.go` in this repo). Then:

```
$ mc admin user info myminio "uid=Пользователь,ou=people,ou=swengg,dc=min,dc=io"
AccessKey: uid=Пользователь,ou=people,ou=swengg,dc=min,dc=io
Status: 
PolicyName: readonly
MemberOf: cn=projectb,ou=groups,ou=swengg,dc=min,dc=io
$ mc admin group info myminio "cn=projectb,ou=groups,ou=swengg,dc=min,dc=io"
Group: cn=projectb,ou=groups,ou=swengg,dc=min,dc=io
Status: 
Policy: consoleAdmin
Members: 
``` 

This shows that the user has an asigned policy of `readonly` and is a member of the group `cn=projectb,ou=groups,ou=swengg,dc=min,dc=io`. This group has as assigned policy of `consoleAdmin`. The user does get both these privileges - e.g. the `ldap.go` program is able to print the content of buckets - this permission comes from `consoleAdmin` and is not present in `readonly`.

I am not able to reproduce your bug. Could you check and let me know if the user is not getting permissions from the group? The right way to check is by first requesting credentials via the STS API. Only then will minio know about the groups and the `mc admin user info` will display the membership. If you run this before requesting any credentials, you will only see the policy assigned to the user and no group memberships.

**Comment by harshavardhana** [comment] 2021-07-15 23:03
> MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN="CN=ldap,OU=ServiceAccount,OU=org,DC=example,DC=ru"
> MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="pass"

or 

> MINIO_IDENTITY_LDAP_USERNAME_FORMAT="cn=%s,OU=Users,OU=org,DC=example,DC=ru"

Issue is right here ..

**Comment by SteeveRan** [comment] 2021-07-16 09:08
@donatello

>There is something wrong with your configuration - you cannot use both lookup bind mode and username format mode simultaneously. 

Sorry, I did not read the documentation carefully. Thank you for your help

I also found a minibug (maybe feature): `cn=Group != CN=Group`

**Closed as completed** 2021-07-16 15:11 UTC
Labels: working as intended, community
