### ISSUE TITLE
Memory leak when upload file frequnecy (using minio docker image)

### ISSUE THREAD

**Issue by HjlSr** [minio/minio#5656] opened 2018-03-15 07:52 UTC
we start minio with 4 node in 1 tenant ,and then start upload file to minio . after a while we see memory leak ("docker stats" show memory usage of docker instances  )
## docker-compose 
<pre>
version: '2'
services:
  minio1:
    image: minio/bash:RELEASE.2018-03-14T20-33-21Z
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: cFV^+7/85KFr-ws]
      _MINIO_CACHE: "off"
    volumes:
      - /home/config1:/root/.minio
      - /home/miniodisk1:/myexport
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
    mem_limit: 5000000000
  minio2:
    image: minio/bash:RELEASE.2018-03-14T20-33-21Z
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: cFV^+7/85KFr-ws]
     _MINIO_CACHE: "off"
    volumes:
      - /home/config2:/root/.minio
      - /home/miniodisk2:/myexport
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
    mem_limit: 5000000000
  minio3:
    image: minio/bash:RELEASE.2018-03-14T20-33-21Z
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: cFV^+7/85KFr-ws]
      _MINIO_CACHE: "off"
    volumes:
      - /home/config3:/root/.minio
      - /home/miniodisk3:/myexport
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
    mem_limit: 5000000000
  minio4:
    image: minio/bash:RELEASE.2018-03-14T20-33-21Z
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: cFV^+7/85KFr-ws]
      _MINIO_CACHE: "off"
    volumes:
      - /home/config4:/root/.minio
      - /home/miniodisk4:/myexport
    command: server http://minio1/myexport http://minio2/myexport http://minio3/myexport http://minio4/myexport
    mem_limit: 5000000000

</pre>

##docker stats result  in 4 steps:  

| CONTAINER ID      |  NAME   |             CPU %      |         MEM USAGE / LIMIT  |   MEM %  |
|  ------------------------ | ----------- | ------------------------| ----------------------------------- |   ---------------  | 
| 0bc59b4d33e5 | docker_minio1_1  |   6.40%    |           650.3MiB / 4.657GiB  | 13.64%   |             
| 1f8dc6a1e502 |docker_minio4_1    | 8.09%     |          677MiB / 4.657GiB   |  14.20%      |        
| 0797bb6563fb | docker_minio2_1    | 3.87%    |           620.7MiB / 4.657GiB  | 13.02%     |         
| 1dd76b16d62c | docker_minio3_1   |  6.05%  |             678.2MiB / 4.657GiB  | 14.22%    |          

| CONTAINER ID      |  NAME   |             CPU %      |         MEM USAGE / LIMIT  |   MEM %  |
|  ------------------------ | ----------- | ------------------------| ----------------------------------- |   ------------------  |           
| 0bc59b4d33e5   |     docker_minio1_1 |    2.11%      |         651MiB / 4.657GiB     | 13.65%              |
| 1f8dc6a1e502    |    docker_minio4_1  |   2.53%       |        677.7MiB / 4.657GiB   | 14.21%             | 
| 0797bb6563fb    |    docker_minio2_1  |   5.98%        |       621.4MiB / 4.657GiB   |  13.03%             | 
| 1dd76b16d62c   |     docker_minio3_1 |    5.46%       |        678.7MiB / 4.657GiB  | 14.23%            |  

| CONTAINER ID      |  NAME   |             CPU %      |         MEM USAGE / LIMIT  |   MEM %  |
|  ------------------------ | ----------- | ------------------------| ----------------------------------- |   ---------------   |
| 0bc59b4d33e5   |     docker_minio1_1 |    0.07%        |       651.1MiB / 4.657GiB |  13.66%              |
| 1f8dc6a1e502     |   docker_minio4_1   |  0.00%           |    677.7MiB / 4.657GiB  | 14.21%              |
| 0797bb6563fb     |   docker_minio2_1   |  0.98%           |    621.4MiB / 4.657GiB  | 13.03%             | 
| 1dd76b16d62c    |    docker_minio3_1  |   0.00%          |     678.9MiB / 4.657GiB |  14.24%            |  

| CONTAINER ID      |  NAME   |             CPU %      |         MEM USAGE / LIMIT  |   MEM %  |
|  ------------------------ | ----------- | ------------------------| ----------------------------------- |   -----------------  |
| 0bc59b4d33e5  |      docker_minio1_1  |   2.09%       |        650.7MiB / 4.657GiB |  13.65%   |           
| 1f8dc6a1e502   |     docker_minio4_1   |  7.07%        |       677.8MiB / 4.657GiB  | 14.21%             | 
| 0797bb6563fb     |   docker_minio2_1    | 10.22%        |      620.7MiB / 4.657GiB  | 13.02%             | 
| 1dd76b16d62c    |    docker_minio3_1   |  1.83%         |      680.6MiB / 4.657GiB  | 14.27%    |

## Steps to Reproduce (for bugs)

1. run  minio image docker 1 tenant with 4 node that are in one machine 
2. turn off  minio memory cache 
3.use minio python wrapper for upload file .
4.upload file rate is about 30 files per second and each file is about 1M.
5. check memory usage "docker stats"

## Your Environment

* Version used (`minio version`): minio/minio:latest docker image
* Server type and version: linux 
* Operating System and version (`uname -a`): 
Linux server 3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2018-03-15 19:00
@HjlSr are you saying that Minio eventually runs out of memory and gets killed by docker?

**Comment by harshavardhana** [comment] 2018-03-16 23:09
> @HjlSr are you saying that Minio eventually runs out of memory and gets killed by docker?

do you have more details @HjlSr ? would it be possible for you to capture profile output by setting then environment value  `_MINIO_PROFILER=mem`?

**Comment by HjlSr** [comment] 2018-03-17 07:15
@harshavardhana  yes when minio reached to memory limitation that i set this to 5G , docker kills minio instance and force me to re run docker-compose.
i set  _MINIO_PROFILER=mem but i don't know how profile minio memory usage with this profile.please explain more about minio memory profiler.

**Comment by harshavardhana** [comment] 2018-03-17 07:16
> @harshavardhana yes when minio reached to memory limitation that i set this to 5G , docker kills minio instance and force me to re run docker-compose.
> i set _MINIO_PROFILER=mem but i don't know how profile minio memory usage with this profile.please explain more about minio memory profiler.

the profiler will be generated inside the container at `/tmp/profile<random>/mem.pprof` @HjlSr

**Comment by harshavardhana** [comment] 2018-03-17 07:17
please attach those files here once you have reproduced the problem and copy this file out from the container. @HjlSr

**Comment by HjlSr** [comment] 2018-03-17 09:06
@harshavardhana i see this file but it is empty . so how can i fix it?

**Comment by harshavardhana** [comment] 2018-03-17 11:50
The file will be empty you have to stop server once it reaches a certain level of memory usage, while stopping the profile is written to this location.

**Comment by HjlSr** [comment] 2018-03-17 13:43
[profile952310808.tar.gz](https://github.com/minio/minio/files/1821662/profile952310808.tar.gz)
@harshavardhana this is for one node ,if it isn't enough i will send u other nodes memprofiler info

**Comment by harshavardhana** [comment] 2018-03-17 18:19
Thanks it should be enough @HjlSr

**Comment by harshavardhana** [comment] 2018-04-06 23:38
> Thanks it should be enough @HjlSr

@HjlSr sorry have been busy, getting back to this now.

**Comment by harshavardhana** [comment] 2018-04-06 23:53
this profile output looks weird, the output is indicating that you are using `fs` mode i.e single disk

```
(pprof) text
Showing nodes accounting for 90865.80kB, 97.79% of 92918.24kB total
Dropped 265 nodes (cum <= 464.59kB)
Showing top 10 nodes out of 63
      flat  flat%   sum%        cum   cum%
   61440kB 66.12% 66.12%    61440kB 66.12%  runtime/pprof.writeMutex /opt/go/src/runtime/pprof/pprof.go
   15408kB 16.58% 82.70% 15545.62kB 16.73%  encoding/gob.decStringSlice /opt/go/src/encoding/gob/dec_helpers.go
13113.31kB 14.11% 96.82% 13113.31kB 14.11%  encoding/gob.(*Decoder).decOpFor /opt/go/src/encoding/gob/decode.go
  556.27kB   0.6% 97.42%   556.27kB   0.6%  regexp.(*bitState).reset /opt/go/src/regexp/backtrack.go
  251.91kB  0.27% 97.69%   501.71kB  0.54%  crypto/x509.parseCertificate /opt/go/src/crypto/x509/x509.go
   75.93kB 0.082% 97.77%  7918.88kB  8.52%  html/template.(*Template).Delims /opt/go/src/text/template/template.go
    8.07kB 0.0087% 97.78% 13112.07kB 14.11%  encoding/gob.encBoolSlice /opt/go/src/encoding/gob/encode.go
    4.22kB 0.0045% 97.78% 15541.59kB 16.73%  encoding/gob.decInt8Slice /opt/go/src/encoding/gob/dec_helpers.go
    4.05kB 0.0044% 97.79% 13255.74kB 14.27%  github.com/minio/minio/cmd.registerAdminRouter /q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-router.go
    4.03kB 0.0043% 97.79% 70068.54kB 75.41%  github.com/minio/minio/cmd.(*FSObjects).getObjectInfo /q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1.go
```

are you sure the profile you captured is from the right server? 

Also, we don't have any release for Minio on the following date.
>     image: minio/bash:RELEASE.2018-03-14T20-33-21Z

Is this image custom? if yes then please use the official image to test otherwise we may not know what is going wrong.

**Comment by HjlSr** [comment] 2018-04-10 06:11
i have 3 disks in my system. and i disparate one of them to 2 logically separate disk 
by using lvm . so i have now 4 disks. and start minio server on my system .
i used my custom minio image . and now i again change my image to minio official image (minio/minio:latest) . and again i encounter memory leak .
this is my  new memprofile that i captured with new docker image .

[profile982646693.tar.gz](https://github.com/minio/minio/files/1893077/profile982646693.tar.gz)

**Comment by harshavardhana** [comment] 2018-04-10 06:39
Thanks will take a look

**Comment by harshavardhana** [comment] 2018-04-14 04:52
> i have 3 disks in my system. and i disparate one of them to 2 logically separate disk
> by using lvm . so i have now 4 disks. and start minio server on my system .
> i used my custom minio image . and now i again change my image to minio official image (minio/minio:latest) . and again i encounter memory leak .
> this is my new memprofile that i captured with new docker image .

From what I can see in the profile output the active memory used by the process is only 20MiB, just to test the theory of GC overhead can you set the env `GOGC=20`  and see if the memory usage improves?

**Comment by HjlSr** [comment] 2018-04-16 12:26
@harshavardhana  
i set GOGC=20 in docker-compose envirenmet ,as below :    
 environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: cFV^+7/85KFr-ws]
      _MINIO_CACHE: "off"
      _MINIO_PROFILER: "mem"
      GOGC: 20

and again i see memory leak .
new profileinfo : 
[profile471871809.tar.gz](https://github.com/minio/minio/files/1915205/profile471871809.tar.gz)

**Comment by harshavardhana** [comment] 2018-04-21 21:48
> and again i see memory leak .
> new profileinfo :
> profile471871809.tar.gz

The attached file seems to be empty @HjlSr are you sure you attached the right file? 

```
ls profile471871809/
[2018-04-16 05:22:16 PDT]     0B mem.pprof
```

**Comment by harshavardhana** [comment] 2018-04-28 22:15
@HjlSr would it be possible for you to gather the memory profiles again? - also perhaps share the script or code to reproduce this problem?

**Comment by harshavardhana** [comment] 2018-05-04 08:25
@HjlSr - reaching out again would it be possible for you to gather the memory profiles again? - also perhaps share the script or code to reproduce this problem?

**Comment by harshavardhana** [comment] 2018-05-16 00:58
@HjlSr going to close this issue for now, please reply back when you have more details.

**Closed as completed by harshavardhana** 2018-05-16 00:58 UTC
Labels: community, fixed, priority: medium
