### ISSUE TITLE
Minio container is showing the status unhealthy(Previous ticket :- #7482)

### ISSUE THREAD

**Issue by snandy-git** [minio/minio#7572] opened 2019-04-23 09:09 UTC
Minio container is showing the status unhealthy(Previous ticket:- #7482)

## Expected Behavior
Minio container is sometimes not working and we are restarting the container and it becomes ok. I checked that the status of minio container is always unhealthy .

## Current Behavior
Minio container is showing the status unhealthy. When I am running "docker restart ", then it is again ok. But after sometimes it again becomes unhealthy.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
As suggested previously, I have updated the minio (2019-03-27T22:35:21Z) . But The same issue happens again . It is showing unhealthy . 

## Your Environment

* Version used (`minio version`): 2019-03-27T22:35:21Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):Linux innolx4055 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

Screenshot :- 

CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                      PORTS                                        NAMES
ce9b1ca25c2d        minio/minio:latest          "/usr/bin/docker-ent…"   38 minutes ago      Up 38 minutes (unhealthy)   0.0.0.0:9000->9000/tcp                       minio_new

minio/minio                                            latest              2aef0c7c6a81        3 weeks ago         57.6MB

**Comment by nitisht** [comment] 2019-04-23 10:17
Sorry for the confusion @snandy-git but we did find out the root cause for this and fixed in https://github.com/minio/minio/pull/7537

This is available in release `RELEASE.2019-04-18T01-15-57Z` and later. Can you please update this and try one more time.

**Comment by harshavardhana** [comment] 2019-04-25 03:04
Closing as fixed

**Closed as completed by harshavardhana** 2019-04-25 03:04 UTC
Labels: priority: low, community, fixed
