### ISSUE TITLE
Detected configuration inconsistencies in the cluster. 

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3415] opened 2016-12-07 13:33 UTC
Version ( on ALL members) :

```
Version: 2016-12-07T11:26:45Z
Release-Tag: DEVELOPMENT.2016-12-07T11-26-45Z
Commit-ID: 71f0b35d1e15f3fc41dd07620ec205a1bb486739
```

Restarting at the same time the 4 members of the cluster (just to add an environment variable) :

```
Created minio configuration file at /root/.minio

Detected configuration inconsistencies in the cluster. Please fix following servers.
[02/04] node1.st2.xxxxx:9000:/minio : disk not found
[03/04] node2.st2.xxxxx:9000:/minio : Server versions do not match
[04/04] node3.st2.xxxxx:9000:/minio : Server versions do not match

Detected configuration inconsistencies in the cluster. Please fix following servers.
[03/04] node2.st2.xxxxx:9000:/minio : Server versions do not match
[04/04] node3.st2.xxxxx:9000:/minio : Server versions do not match

Detected configuration inconsistencies in the cluster. Please fix following servers.
[03/04] node2.st2.xxxxx:9000:/minio : Server versions do not match
[04/04] node3.st2.xxxxx:9000:/minio : Server versions do not match
Initializing data volume. Waiting for minimum 3 servers to come online.
```

**Comment by dcharbonnier** [comment] 2016-12-07 13:34
restarting again fixed the problem

**Comment by harshavardhana** [comment] 2016-12-07 20:25
> Created minio configuration file at /root/.minio
> 
> Detected configuration inconsistencies in the cluster. Please fix following servers.
> [02/04] node1.st2.xxxxx:9000:/minio : disk not found
> [03/04] node2.st2.xxxxx:9000:/minio : Server versions do not match
> [04/04] node3.st2.xxxxx:9000:/minio : Server versions do not match
> 
> Detected configuration inconsistencies in the cluster. Please fix following servers.
> [03/04] node2.st2.xxxxx:9000:/minio : Server versions do not match
> [04/04] node3.st2.xxxxx:9000:/minio : Server versions do not match
> 
> Detected configuration inconsistencies in the cluster. Please fix following servers.
> [03/04] node2.st2.xxxxx:9000:/minio : Server versions do not match
> [04/04] node3.st2.xxxxx:9000:/minio : Server versions do not match
> Initializing data volume. Waiting for minimum 3 servers to come online.

@dcharbonnier this can only happen if the 'minio' binaries themselves were switched somehow.  Since the version is built into the binary itself these values shouldn't change at all unless the something else happened. 

Will try to reproduce it.

**Comment by dcharbonnier** [comment] 2016-12-07 21:26
I run `minio version` on all hosts and they reported the same value, weird

**Comment by harshavardhana** [comment] 2016-12-09 08:56
@dcharbonnier tried to reproduce this on both scaleway, packet.net and hyper.sh not able to. would it be possible to purge the docker images locally downloaded and refresh them? - to retest and reproduce this behavior.

**Comment by harshavardhana** [comment] 2016-12-18 21:42
@dcharbonnier have you seen this issue again?

**Comment by harshavardhana** [comment] 2016-12-20 10:09
Closing this issue. @dcharbonnier  please re-open if seen again.

**Closed as completed by harshavardhana** 2016-12-20 10:09 UTC

**Comment by dcharbonnier** [comment] 2016-12-20 10:21
well I don't restart the minio right now so I don't see it anymore but there is not reason for the bug to disappear if you didn't do anything...

**Comment by harshavardhana** [comment] 2016-12-20 11:00
> well I don't restart the minio right now so I don't see it anymore but there is not reason for the bug to disappear if you didn't do anything...

Thanks @dcharbonnier .
