### ISSUE TITLE
Add Access-Control-Allow-Origin when origin is null

### ISSUE THREAD

**Issue by tomaswarynyca** [minio/minio#17517] opened 2023-06-26 13:44 UTC
## Expected Behavior

> Access-Control-Allow-Origin: *

## Current Behavior

> Access-Control-Allow-Methods: GET,OPTIONS,PUT
Access-Control-Max-Age: 100
Content-Length: 0

## Possible Solution

Modify API to send that header when origin is null

## Steps to Reproduce (for bugs)

Use fetch from javascript to make a request to one server who returns 302 status with a redirect to a presigned URL of Minio.
## Context

fetch redirect in browser sends in request Origin: null and minio doesn't send cors headers

## Your Environment

* Version used (`minio --version`): RELEASE.2023-06-23T20-26-00Z
* Server setup and configuration: docker
* Operating System and version (`uname -a`): linux

**Comment by harshavardhana** [comment] 2023-06-26 16:17
Closing as duplicate of #17409

**Closed as completed by harshavardhana** 2023-06-26 16:17 UTC
Labels: duplicate, community

**Comment by tomaswarynyca** [comment] 2023-06-26 17:41
@harshavardhana I'm not sure if it's duplicated, the redirect's fetch OPTIONS sends the headers.
> Access-Control-Request-Method: GET
Origin: null

In the response Minio does not return cors headers. 
> Access-Control-Allow-Methods: GET,OPTIONS,PUT
Access-Control-Max-Age: 100
Content-Length: 0

**Comment by harshavardhana** [comment] 2023-06-26 17:43
if its fixed it will be a comprehensive fix, so just GC'ing the issues.
