### ISSUE TITLE
Windows 10 + MinIO Azure Gateway HTTP error

### ISSUE THREAD

**Issue by MatinF** [minio/minio#7744] opened 2019-06-04 18:12 UTC
The below seems to be a general bug/issue in MinIO Azure Gateway + Windows. As requested by Anis Elleuch on Slack, I'm hereby opening an issue regarding this.

## Expected Behavior
I'm trying to run a basic MinIO Azure Gateway setup with HTTP on Windows 10. After following the MinIO quickstart guide, I expected to be able to see my files on my Azure storage account via the MinIO browser.

## Current Behavior
However, I get an error message in the command prompt when starting MinIO:

```
API: SYSTEM()
Time: 16:58:12 CEST 06/04/2019
Error: [31m[1mGet https://cssazuregatewaytestnew.blob.core.windows.net/?comp=list: x509: certificate signed by unknown authority[0m[0m
       2: cmd\policy.go:101:cmd.(*PolicySys).refresh()
       1: cmd\policy.go:163:cmd.(*PolicySys).Init()
```
Further, when I try to use MinIO browser to login, I do not see the content of my Azure account - i.e. I created a Container, which does not show up. In the command prompt I get the following:

```
API: SYSTEM()
Time: 16:51:50 CEST 06/04/2019
Error: [31m[1mGet https://cssazuregatewaytest.blob.core.windows.net/?comp=list: x509: certificate signed by unknown authority[0m[0m
       3: cmd\web-handlers.go:1956:cmd.toWebAPIError()
       2: cmd\web-handlers.go:1836:cmd.toJSONError()
       1: cmd\web-handlers.go:346:cmd.(*webAPIHandlers).ListBuckets()
```

I've previously managed to run an Azure Gateway via MinIO on Windows on the same PC without fail. But that was several months ago on a different MinIO version and the Azure interface was also different.
 
## Steps to Reproduce (for bugs)
1. Create a new free user on Azure
2. Under Storage accounts, add a new account (settings: US East, StorageV2, Read-access geo-redundant storage (RA-GRS))
3. Under the account's Access keys tab, fetch the Storage account name and the Key1 key
4. Download the latest MinIO server for Windows
5. Note: No certificates are in the .minio/certs folder
6. Open command prompt and enter the following:
```
set MINIO_ACCESS_KEY=[storage account name from Azure]
set MINIO_SECRET_KEY=[Key 1 key from Azure]
minio gateway azure
```
This starts MinIO server as expected, but produces the error codes mentioned above.

## Your Environment
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134
MinIO RELEASE.2019-06-04T01-15-58Z

**Comment by deekoder** [comment] 2019-06-05 00:17
@MatinF I am reproing this issue to see if it occurs on my end. Please stay tuned.

**Comment by MatinF** [comment] 2019-06-05 04:48
> @MatinF I am reproing this issue to see if it occurs on my end. Please stay tuned.

Ok thanks - I believe Anis Elleuch confirmed on Slack to have the same issue on Windows, while it's not an issue on Linux it seems.

**Comment by deekoder** [comment] 2019-06-06 23:51
Ok i tried it on windows 8 and it works for me.

**Comment by deekoder** [comment] 2019-06-06 23:52
We will look at it @MatinF right now we have some other issues of higher priority. We will take a look when there are some cycles.

**Comment by xmichaelx** [comment] 2019-07-11 08:09
Reproduced issue.

Windows version: 10.0.17134 N/A Build 17134
Minio version:  2019-07-10T00:34:56Z

Maybe it's related to this issue: [go/issues#27175](https://github.com/golang/go/issues/27175)

**Comment by TheFiZi** [comment] 2019-08-30 00:44
Same issue here on Windows Server 2019 Standard 64-bit but I'm using BackblazeB2

Windows version: 10.0.17763 N/A Build 17763
Minio version: 2019-08-29T00:25:01Z

Temporary workaround:
**Note:** You need access to a Linux box, the Linux Subsystem for Windows to be installed or just the OpenSSL binary and you will need to run minio.exe once on your Windows system so it creates it's default certificate directories.

1. Run this command: `echo | openssl s_client -servername BackblazeB2 -connect api.backblazeb2.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > certificate.crt`
2. Copy the .crt file that is generated into `%USERPROFILE%\.minio\certs\CAs` on your Windows machine
3. Try again

You can likely follow this same procedure if you know the Azure endpoint your connecting to. Just replace "BackblazeB2" with "Azure" and "api.backblazeb2.com" with what ever the endpoint is for Azure.

I used my Pi-Hole to snoop on my servers DNS queries to find out the endpoint for Backblaze B2

This is not idea because your going to have to redownload the certificates each time the provider changes them.

I think the underlying issue is that Minio isn’t using the Windows Certificate Store to validate certificates. 

Related to this? https://github.com/minio/minio/issues/7862

**Comment by vadmeste** [comment] 2019-10-30 10:19
It works for me using a earlier version of Windows (2016)

Not able to find Windows 2019 yet..

@MatinF @xmichaelx what happens if you open the Azure endpoint using Internet Explorer ?

http://azure-blob-account-name.blob.core.windows.net

**Comment by MatinF** [comment] 2019-10-30 10:40
I'm not able to open the above link in any browser on Win10, I get "This site can’t be reached" in Chrome for example (same in IE, Edge).

Martin

**Comment by vadmeste** [comment] 2019-10-30 11:24
> I'm not able to open the above link in any browser on Win10, I get "This site can’t be reached" in Chrome for example (same in IE, Edge).

You need to put your blob account name in the url

https://[your-blob-account-name].blob.core.windows.net

**Comment by harshavardhana** [comment] 2019-11-29 01:52
Closing this as a gateway issue, to be handled in future milestone

**Closed as completed by harshavardhana** 2019-11-29 01:52 UTC
Labels: priority: low, community
