### ISSUE TITLE
Error: Unexpected error on any write activity

### ISSUE THREAD

**Issue by HardwareHarry** [minio/minio#6224] opened 2018-08-01 16:14 UTC
## Expected Behavior
Using web UI, mc command line utility or python API, it is possible to retrieve an object and store an object.

- **web UI** -> provide authentication, select bucket (page-images), + button, upload button, select small .zip file (2kb), click open - file should be uploaded.

- **mc** -> mc cp --debug local/page-images/abc2 local/page-images/abc3 - file should be copied (from abc2 to abc3)

## Current Behavior
**web UI** - on clicking the "Open" button after choosing a file to upload, a red box appears ("Unexpected error, please report this issue at https://github.com/minio/minio/issues").
syslog output:
Aug  1 16:40:09 server5 minio[14797]: API: SYSTEM()
Aug  1 16:40:09 server5 minio[14797]: Time: 16:40:09 BST 08/01/2018
Aug  1 16:40:09 server5 minio[14797]: Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
Aug  1 16:40:09 server5 minio[14797]:        1: cmd/fs-v1-helpers.go:337:cmd.fsCreateFile()
Aug  1 16:40:09 server5 minio[14797]:        2: cmd/fs-v1.go:870:cmd.(*FSObjects).putObject()
Aug  1 16:40:09 server5 minio[14797]:        3: cmd/fs-v1.go:780:cmd.(*FSObjects).PutObject()
Aug  1 16:40:09 server5 minio[14797]:        4: cmd/object-handlers.go:732:cmd.(ObjectLayer).PutObject-fm()
Aug  1 16:40:09 server5 minio[14797]:        5: cmd/web-handlers.go:651:cmd.(*webAPIHandlers).Upload()
Aug  1 16:40:09 server5 minio[14797]: API: SYSTEM()
Aug  1 16:40:09 server5 minio[14797]: Time: 16:40:09 BST 08/01/2018
Aug  1 16:40:09 server5 minio[14797]: Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
Aug  1 16:40:09 server5 minio[14797]:        1: cmd/web-handlers.go:1196:cmd.toWebAPIError()
Aug  1 16:40:09 server5 minio[14797]:        2: cmd/web-handlers.go:1206:cmd.writeWebErrorResponse()
Aug  1 16:40:09 server5 minio[14797]:        3: cmd/web-handlers.go:653:cmd.(*webAPIHandlers).Upload()

**mc** > mc cp local/page-images/abc2 local/page-images/abc3
Command hangs for a long time then:
"mc: <ERROR> Failed to copy `http://localhost:9000/page-images/abc2`. We encountered an internal error, please try again.
mc: <ERROR> Session safely terminated. To resume session `mc session resume PNeqMfWx`"

**syslog output** (many recurrences during command run):
Aug  1 16:47:03 server5 minio[14797]: API: CopyObject(bucket=page-images, object=abc3)
Aug  1 16:47:03 server5 minio[14797]: Time: 16:47:03 BST 08/01/2018
Aug  1 16:47:03 server5 minio[14797]: RequestID: 1546CD45E1220AB9
Aug  1 16:47:03 server5 minio[14797]: RemoteHost: 127.0.0.1
Aug  1 16:47:03 server5 minio[14797]: UserAgent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-07-31T02:28:53Z
Aug  1 16:47:03 server5 minio[14797]: Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
Aug  1 16:47:03 server5 minio[14797]:        1: cmd/fs-v1-helpers.go:337:cmd.fsCreateFile()
Aug  1 16:47:03 server5 minio[14797]:        2: cmd/fs-v1.go:870:cmd.(*FSObjects).putObject()
Aug  1 16:47:03 server5 minio[14797]:        3: cmd/fs-v1.go:505:cmd.(*FSObjects).CopyObject()
Aug  1 16:47:03 server5 minio[14797]:        4: cmd/object-handlers.go:603:cmd.objectAPIHandlers.CopyObjectHandler()
Aug  1 16:47:03 server5 minio[14797]:        5: cmd/api-router.go:77:cmd.(objectAPIHandlers).CopyObjectHandler-fm()
Aug  1 16:47:03 server5 minio[14797]:        6: pkg/handlers/http-tracer.go:149:handlers.TraceReqHandlerFunc.func1()
Aug  1 16:47:03 server5 minio[14797]:        7: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
Aug  1 16:47:03 server5 minio[14797]: API: CopyObject(bucket=page-images, object=abc3)
Aug  1 16:47:03 server5 minio[14797]: Time: 16:47:03 BST 08/01/2018
Aug  1 16:47:03 server5 minio[14797]: RequestID: 1546CD45E1220AB9
Aug  1 16:47:03 server5 minio[14797]: RemoteHost: 127.0.0.1
Aug  1 16:47:03 server5 minio[14797]: UserAgent: Minio (linux; amd64) minio-go/v6.0.6 mc/2018-07-31T02:28:53Z
Aug  1 16:47:03 server5 minio[14797]: Error: io: read/write on closed pipe
Aug  1 16:47:03 server5 minio[14797]:        1: cmd/fs-v1.go:611:cmd.(*FSObjects).getObject()
Aug  1 16:47:03 server5 minio[14797]:        2: cmd/fs-v1.go:492:cmd.(*FSObjects).CopyObject.func1()

However read-only commands work:
> mc ls local/page-images/abc2
[2018-08-01 15:35:46 BST]   105B abc2

> mc cat local/page-images/abc2
eaerugokefeijearugnuwajjef9pkWFNU34HG8W ENCJI2  W3RH89W EFNIJ   W2N3WF89QNWJINWQ JUI2   3N4TGUINQWIU3NF9        W3NF

Can't even set a policy however: 
**mc** mc policy public local/page-images
mc: <ERROR> Unable to set policy `public` for `local/page-images`. We encountered an internal error, please try again.

However I can use both the web UI and the mc command to both create and delete buckets (just not place anything in them).

## Steps to Reproduce (for bugs)
1. Install minio using [instructions](https://docs.minio.io/docs/minio-quickstart-guide.html) (GNU/Linux / Binary Download)
2. mv minio to /usr/local/bin (and chmod 755)
3. create user/group minio:minio
4. install [minio-service](https://github.com/minio/minio-service/blob/master/linux-systemd/README.md) (linux/systemd), configure for user/group minio
4a. Setup /etc/defaults/minio:
```
root@server5:~# cat /etc/default/minio
# Local export path.
MINIO_VOLUMES="/data/minio"
MINIO_HTTP_TRACE="/home/minio/minio.trace"
```
5. create new directory and set ownership:
  > sudo mkdir /data/minio
  > sudo chown minio:minio /data/minio
6. start minio service via systemctl
7. attempt tests above.

## Context
Unable to create or store any object using Minio.  Using OS I can navigate to the data directory (as the minio:minio user) and touch/vim within the page-images bucket directory and it appears in the and can be downloaded/accessed correctly, but nothing that requires any sort of write is working.
To rule out a permissions problem, I have changed the minio daemon to run as root:root, however the identical problems occur so I have reverted back to running as minio:minio.

## Your Environment

* Version used:
root@server5:/data/minio# minio version
Version: 2018-07-31T02:11:47Z
Release-Tag: RELEASE.2018-07-31T02-11-47Z
Commit-ID: dbd89bbae33c70175e1f7ca1b7897e8a2fe84f90

* Environment name and version (e.g. nginx 1.9.1):
root@server5:/etc# cat os-release
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

* Server type and version:
VMWare ESXI 6.5 virtual machine on HP Microserver Gen8

* Operating System and version (`uname -a`): 
root@server5:/data/minio# uname -a
Linux server5 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Environment:

> root@server5:~# ls -ald /data/minio
drwxr-xr-x 7 minio minio 4096 Aug  1 16:30 /data/minio

> root@server5:/data/minio# ls -lart /data/minio
total 16
drwxr-xr-x 5 root  root  4096 Aug  1 12:23 ..
drwxr-xr-x 2 minio minio 4096 Aug  1 15:37 page-images
drwxr-xr-x 5 minio minio 4096 Aug  1 15:47 .minio.sys
drwxr-xr-x 4 minio minio 4096 Aug  1 17:07 .

> root@server5:~# cat /etc/default/minio
\# Local export path.
MINIO_VOLUMES="/data/minio"
MINIO_HTTP_TRACE="/home/minio/minio.trace"

strace output during attempted copy operation:

(apologies, I realised somewhat later that I forgot to add child processes to the trace so have re-done it and attached it)
[minio_strace.txt](https://github.com/minio/minio/files/2251085/minio_strace.txt)

**Comment by HardwareHarry** [comment] 2018-08-01 21:04
On a whim I downloaded a prior version of minio (I chose 2018-04-04T05-20-54Z).  I simply moved it into place, I had to downgrade the version in the config.json from 27 to 23 and then started it.  It then started functioning perfectly - the test cases I mentioned above (command line, web UI and python code) all started working.

To make sure I wasn't going mad, I re-installed the current (2018-07-31T02:11:47Z) version and (after it auto-upgraded the config.json file), the problem immediately reasserted itself and all attempted tests failed.  If you want me to try another specific version please let me know.

**Comment by kannappanr** [comment] 2018-08-01 23:19
@HardwareHarry Thanks for filing this issue. We tried to reproduce this issue internally and were unable to do so. As an initial step, can you please run the `mc` command with the `--debug` option turned on and post your output. 
I can have a debug `minio` binary for you to test. That might just give me a starting point to look at.

**Comment by kannappanr** [comment] 2018-08-02 05:15
Duplicate of #6223 . Fix has already been merged into master. Will make a release hopefully tomorrow. In the meantime, can you please try out minio, by building from the master and verifying the fix.

**Closed as completed** 2018-08-02 06:44 UTC
Labels: duplicate, community, priority: medium

**Comment by HardwareHarry** [comment] 2018-08-02 10:24
Built from master, and confirm fix to all my test cases.  Thank you!
