### ISSUE TITLE
Error : mc rm --versions option throws ...The specified method is not allowed against this resource

### ISSUE THREAD

**Issue by simha03** [minio/minio#12632] opened 2021-07-07 11:31 UTC
We are trying to remove objects with mc rm --versions objects, but we are getting the error "The specified method is not allowed against this resource". when to do mc ls without versions we dont get any object. But if we do mc ls --versions we get the object with version info present.

```
[xxxx@yyyy ~]$ ./mc rm --versions --force --json minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
{
 "status": "success",
 "key": "minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml",
 "versionID": "a2089b5c-00c3-4a7b-b7d7-e944737d9ae5",
 "modTime": "2021-07-07T11:06:11.205Z",
 "size": 0
}
{
 "status": "success",
 "key": "minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml",
 "versionID": "6671adaa-1265-4eac-a4a2-e8a301527e48",
 "modTime": "2021-07-02T12:15:07.109Z",
 "size": 293648
}
{
 "status": "error",
 "error": {
  "message": "Failed to remove `minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml` recursively.",
  "cause": {
   "message": "The specified method is not allowed against this resource.",
   "error": {}
  },
  "type": "error",
  "sysinfo": {
   "host.arch": "amd64",
   "host.cpus": "2",
   "host.lang": "go1.16.3",
   "host.name": "cb0969-edge-001",
   "host.os": "linux",
   "mem.heap.total": "67 MB",
   "mem.heap.used": "2.0 MB",
   "mem.total": "74 MB",
   "mem.used": "2.0 MB"
  }
 }
}
[xxxx@yyyy ~]$


[xxxx@yyyy ~]$ ./mc ls --json --versions minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
{
 "status": "success",
 "type": "file",
 "lastModified": "2021-07-07T14:10:42.602+03:00",
 "size": 0,
 "key": "A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml",
 "etag": "",
 "url": "http://10.254.89.0:9000/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml",
 "versionId": "98626803-a418-4022-9b69-2ce37fc10315",
 "versionOrdinal": 2,
 "isDeleteMarker": true
}
{
 "status": "success",
 "type": "file",
 "lastModified": "2021-07-02T15:15:07.109+03:00",
 "size": 293648,
 "key": "A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml",
 "etag": "acb51a4f2f9c773589eaa6c93ffcd684",
 "url": "http://10.254.89.0:9000/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml",
 "versionId": "6671adaa-1265-4eac-a4a2-e8a301527e48",
 "versionOrdinal": 1
}
[xxxx@yyyy ~]$

[cloud-user@cb0969-edge-001 ~]$ ./mc stat minio/pm-file-transfer
Name      : pm-file-transfer/
Size      : 0 B
Type      : folder
Metadata  :
  Versioning: Enabled
  Location: us-east-1
  Policy: none
  ILM: Set

[xxxx@yyyy ~]$
```

## Expected Behavior
The objects are deleted succesfully with all versions also deleted.

## Current Behavior
The objects are not deleted with even --versions option . instead an error is thrown saying -
"message": "The specified method is not allowed against this resource.",

## Possible Solution
the object should be deleted succesful or else atleast the error message should have some more details indicting cause of failure.
Present error is too generic to even debug.

## Steps to Reproduce (for bugs)
Not sure how to reproduce the issue exactly.. we have this error returning for many object which we are trying to delete. many are successful also.

## Context
We are trying to clean up files from the buckets after specifc no of days which we need to store. after that we are trying to remove files older that that. So that the storage is under check. 
Because if this issue we see there are lot of files that are still there and we are not able to delete them in any possible way causing the storage getting filled.

## Regression
NO

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration:  Kubernetes cluster with 16 minio pods 
* Operating System and version (`uname -a`): Linux neo-minio-zone-1-0 3.10.0-1160.31.1.el7.x86_64 #1 SMP Wed May 26 20:18:08 UTC 2021 x86_64 Linux

**Comment by klauspost** [comment] 2021-07-07 11:53
You appear to have object locking enabled on your bucket.

**Comment by simha03** [comment] 2021-07-07 12:13
yes object locking is enabled . But we do not have any retention or leagal holds set.We do  have replication enabled.
is there any scenario that minio will not allow to delete objects in above ?

**Comment by harshavardhana** [comment] 2021-07-07 15:29
@simha03 looks like you have default retention set - please provide output for `mc stat --versions` on the object.

**Comment by simha03** [comment] 2021-07-07 16:19
@harshavardhana  stat returns object doesnt exist. 
Also retention we dont set .. we though have ilm rule of 3 days.

```
[xxxx@yyyy ~]$ ./mc stat --versions minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
mc: <ERROR> Unable to stat `minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml`. Object does not exist.
[xxxx@yyyy ~]$
```

But if i pass version in stat command i get "405 Method Not Allowed"

```
[xxxx@yyyy ~]$ ./mc ls --versions minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
[2021-07-07 14:10:42 EEST]     0B 98626803-a418-4022-9b69-2ce37fc10315 v2 DEL A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
[2021-07-02 15:15:07 EEST] 287KiB 6671adaa-1265-4eac-a4a2-e8a301527e48 v1 PUT A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
[xxxx@yyyy ~]$
[xxxx@yyyy ~]$ ./mc stat --json --vid 6671adaa-1265-4eac-a4a2-e8a301527e48  minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
{
 "status": "error",
 "error": {
  "message": "Unable to stat `minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml`.",
  "cause": {
   "message": "405 Method Not Allowed",
   "error": {
    "Code": "405 Method Not Allowed",
    "Message": "405 Method Not Allowed",
    "BucketName": "pm-file-transfer",
    "Key": "",
    "RequestID": "168F8E7C4E4479BD",
    "HostID": "",
    "Region": "",
    "Server": ""
   }
  },
  "type": "fatal",
  "sysinfo": {
   "host.arch": "amd64",
   "host.cpus": "2",
   "host.lang": "go1.16.3",
   "host.name": "cb0969-edge-001",
   "host.os": "linux",
   "mem.heap.total": "67 MB",
   "mem.heap.used": "4.4 MB",
   "mem.total": "74 MB",
   "mem.used": "4.4 MB"
  }
 }
}
[xxxx@yyyy ~]$
```

```
[xxxx@yyyy~]$ ./mc retention info  minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
Unable to get object retention on `minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml`: The specified key does not exist.
[xxxx@yyyy ~]$
```

Just output of another file in same bucket which is put today ..

```
[xxxx@yyyy1 ~]$ ./mc retention info  minio/pm-file-transfer/MRBTS/20210707/500165/A20210707.1845+0300-1900+0300_MRBTS-500165_-_1.xml
Name    : minio/pm-file-transfer/MRBTS/20210707/500165/A20210707.1845+0300-1900+0300_MRBTS-500165_-_1.xml
Mode    : NO RETENTION

[xxxx@yyyy ~]$
```

**Comment by harshavardhana** [comment] 2021-07-07 19:44
> [xxxx@yyyy ~]$ ./mc ls --versions minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
> [2021-07-07 14:10:42 EEST]     0B 98626803-a418-4022-9b69-2ce37fc10315 v2 DEL A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
> [2021-07-02 15:15:07 EEST] 287KiB 6671adaa-1265-4eac-a4a2-e8a301527e48 v1 PUT A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
> [xxxx@yyyy ~]$

can you do `mc rm --vid 98626803-a418-4022-9b69-2ce37fc10315 minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml`  ?

**Comment by simha03** [comment] 2021-07-07 22:20
It deleted the delete marker file but got recreated again automatically again in no time.

```
[xxxx@yyyy ~]$ ./mc rm --vid 98626803-a418-4022-9b69-2ce37fc10315 minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
Removing `minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml` (versionId=98626803-a418-4022-9b69-2ce37fc10315).
[xxxx@yyyy ~]$ ./mc ls --versions minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
[2021-07-02 15:15:07 EEST] 287KiB 6671adaa-1265-4eac-a4a2-e8a301527e48 v1 PUT A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
[xxxx@yyyy ~]$

[xxxx@yyyy ~]$ ./mc ls --versions minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
[2021-07-08 01:19:18 EEST] 0B bc4c8775-d76f-4ae9-85f0-2012c5686187 v2 DEL A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
[2021-07-02 15:15:07 EEST] 287KiB 6671adaa-1265-4eac-a4a2-e8a301527e48 v1 PUT A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
[xxxx@yyyy ~]$
```

**Comment by harshavardhana** [comment] 2021-07-08 00:25
> [xxxx@yyyy ~]$ ./mc ls --versions minio/pm-file-transfer/MRBTS/20210702/500165/A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
> [2021-07-08 01:19:18 EEST] 0B bc4c8775-d76f-4ae9-85f0-2012c5686187 v2 DEL A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
> [2021-07-02 15:15:07 EEST] 287KiB 6671adaa-1265-4eac-a4a2-e8a301527e48 v1 PUT A20210702.1500+0300-1515+0300_MRBTS-500165_-_1.xml
> [xxxx@yyyy ~]$

But this is not automatic, someone else is creating these delete markers out of band here the versionId is completely different and also there is a newer timestamp on it. Are you sure your application is not again and again sending DELETEs without versionId - this will create new delete markers.

**Comment by simha03** [comment] 2021-07-08 04:59
Yes our application is not deleting the file even without vesrionID.
We do have ilm of 3 days and if you see the object is already past 3 days and ideally should have got cleaned by ilm policy.
We have replication enabled also. As stat command is not working cant find the replication state of the object.
is it possible some scenario in that replication state not allowing to delete ?

**Comment by harshavardhana** [comment] 2021-07-08 05:06
> Yes our application is not deleting the file even without vesrionID.
> We do have ilm of 3 days and if you see the object is already past 3 days and ideally should have got cleaned by ilm policy.
> We have replication enabled also. As stat command is not working cant find the replication state of the object.
> is it possible some scenario in that replication state not allowing to delete ?

I don't see anything enabled properly on the cluster. Your ILM policy is also incorrect which is creating these delete markers.

I would suggest you buy our subscription if this is a production cluster. We will help you configure this properly and can provide architecture reviews.

This is expected with replication if you have a delete marker that has pending replication it won't be allowed to delete until it's replicated otherwise explicitly deleted after replication is finished.

We have reached the level of debugging at this point.

**Comment by simha03** [comment] 2021-07-08 09:42
@harshavardhana thanks for the information.  i will pass this info to our procurement team to get in touch.
Meanwhile , this are our developer envs and not production yet.
As we are not able to delete with mc with any option is there any other options to delete files if there is replication loss also ?

**Comment by harshavardhana** [comment] 2021-07-08 17:08
> As we are not able to delete with mc with any option is there any other options to delete files if there is replication loss also ?

If this is not a prod setup just wipe the drives and restart the servers @simha03

**Comment by simha03** [comment] 2021-07-09 03:32
@harshavardhana  if i just delete the files that has issues from all drives and restart that should be ok right ?

**Comment by harshavardhana** [comment] 2021-07-09 04:35
> @harshavardhana if i just delete the files that has issues from all drives and restart that should be ok right ?

Sure that is fine @simha03

**Comment by harshavardhana** [comment] 2021-07-10 08:25
Since we have no way to currently reproduce this closing this issue, perhaps we will have next release 

```
commit d6a2fe02d395a59d952d74bcf77da02bc53ca32c
Author: Klaus Post <klauspost@gmail.com>
Date:   Fri Jul 9 11:29:16 2021 -0700

    Add admin file inspector (#12635)
    
    Download files from *any* bucket/path as an encrypted zip file.
    
    The key is included in the response but can be separated so zip
    and the key doesn't have to be sent on the same channel.
    
    Requires https://github.com/minio/pkg/pull/6
```

Will have a for us to look at the objects to inspect them - closing until then.

**Closed as completed by harshavardhana** 2021-07-10 08:25 UTC
Labels: community
