### ISSUE TITLE
docker: Minio version output should be similar to binary released versions

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2677] opened 2016-09-12 17:03 UTC
For minio compiled by source:

```
# minio version
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
```

Here it will be good to have a valid Commit-ID instead of `DEVELOPMENT.GOGET` so that it is easy to see know what is in the binary.

**Comment by harshavardhana** [comment] 2016-09-12 18:34
> For minio compiled by source:
> 
> # minio version
> 
> Version: DEVELOPMENT.GOGET
> Release-Tag: DEVELOPMENT.GOGET
> Commit-ID: DEVELOPMENT.GOGET
> Here it will be good to have a valid Commit-ID instead of DEVELOPMENT.GOGET so that it is easy to see know what is in the binary.

The problem is we can't add commit-id with 'go install' otherwise will will have to update build-constants.go upon each commit.  You have to pass these values using `--ldflags`. 

The best way is always use 'make' to install the binary.

**Comment by harshavardhana** [comment] 2016-09-12 18:37
In-case you are wondering this about docker showing then its a bug and should be fixed. We know how to  pass these values and we should properly.

**Comment by krishnasrinivas** [comment] 2016-09-12 21:06
> The problem is we can't add commit-id with 'go install' otherwise will will have to update build-constants.go upon each commit. You have to pass these values using --ldflags.
> 
> The best way is always use 'make' to install the binary.

It's ok then, because `go get` will be preferable way to install than make.

> In-case you are wondering this about docker showing then its a bug and should be fixed. We know how to pass these values and we should properly.

I see.

**Closed as completed** 2016-09-13 10:26 UTC
