### ISSUE TITLE
unexpected "minio docker image " behavior

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#1220] opened 2016-03-11 18:24 UTC
I am trying to run minio using its docker repo image. This is the error i am getting when i am using `docker run`

```
$ sudo docker run minio/minio
time="2016-03-11T10:35:33Z" level=fatal msg="Unable to listen on IP fe80::42:acff:fe11:2, port 9000" error="listen tcp6 [fe80::42:acff:fe11:2%eth0]:9000: bind: cannot assign requested address" probe="{\"cause\":{\"Op\":\"listen\",\"Net\":\"tcp6\",\"Source\":null,\"Addr\":{\"IP\":\"fe80::42:acff:fe11:2\",\"Port\":9000,\"Zone\":\"eth0\"},\"Err\":{\"Syscall\":\"bind\",\"Err\":99}},\"trace\":[{\"line\":302,\"file\":\"server-main.go\",\"func\":\"main.checkPortAvailability\"}],\"sysinfo\":{\"host.arch\":\"amd64\",\"host.cpus\":\"4\",\"host.lang\":\"go1.6\",\"host.name\":\"ed41224c4c33\",\"host.os\":\"linux\",\"mem.heap.total\":\"1.7MB\",\"mem.heap.used\":\"902kB\",\"mem.total\":\"2.8MB\",\"mem.used\":\"902kB\"}}"
```

**Comment by harshavardhana** [comment] 2016-03-11 18:28
Closing duplicate of #1219

**Closed as completed by harshavardhana** 2016-03-11 18:28 UTC
