### ISSUE TITLE
How to change the bucket length 

### ISSUE THREAD

**Issue by sbala69gmail** [minio/minio#5297] opened 2017-12-15 14:57 UTC
Hi, 
I want to change the bucket name in 2 digit.  Is it any possible?

**Comment by nitisht** [comment] 2017-12-15 15:49
@sbala69gmail Minio is S3 compatible and S3 Bucket names should be at least 3 characters long. Ref: http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by nitisht** [comment] 2017-12-15 15:50
Closing this as working as intended, for further questions please join us on Slack: https://slack.minio.io

**Closed as completed by nitisht** 2017-12-15 15:50 UTC
Labels: working as intended
