### ISSUE TITLE
[resolved] Unable to delete empty bucket (SlowDown - Please reduce your request)

### ISSUE THREAD

**Issue by salacr** [minio/minio#10288] opened 2020-08-18 20:03 UTC
Hi I have this issue with minio we run in distributed mode (details are belove) and run stress test before moving to production (https://github.com/wasabi-tech/s3-benchmark)
during the stress test I write enough data to fill my disks. I was able to clear it up. System is running  accepting new content everything seams OK, but right now I'm unable to delete the bucket used for testing.

GET: https://minio1-develop.*********:9000/wasabi-benchmark-bucket/?versions
```
<?xml version="1.0" encoding="UTF-8"?>
<ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Name>wasabi-benchmark-bucket</Name>
    <Prefix></Prefix>
    <KeyMarker></KeyMarker>
    <NextVersionIdMarker></NextVersionIdMarker>
    <VersionIdMarker></VersionIdMarker>
    <MaxKeys>10000</MaxKeys>
    <Delimiter></Delimiter>
    <IsTruncated>false</IsTruncated>
</ListVersionsResult>
```

## Expected Behavior
Possibility to delete empty bucket

## Current Behavior
Unable to delete empty bucket even after restart (mc admin service restart)
DELETE: https://minio1-develop.*******:9000/wasabi-benchmark-bucket
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>SlowDown</Code>
    <Message>Please reduce your request</Message>
    <BucketName>wasabi-benchmark-bucket</BucketName>
    <Resource>/wasabi-benchmark-bucket</Resource>
    <RequestId>162C0819DAF02B86</RequestId>
    <HostId>4ed69e58-8cdb-4e3d-944a-41aac3ea9c91</HostId>
</Error>
```

## Steps to Reproduce (for bugs)

1. run https://github.com/wasabi-tech/s3-benchmark benchmark for several hours during this benchmark fill up the disk
2. delete all content from wasabi-benchmark-bucket
3. try to delete the bucket

## Regression
Don't know

## Your Environment

* Version used  MinIO/RELEASE.2020-08-08T04-50-06Z
* Server setup and configuration:
```
{
    "status": "success",
    "info": {
        "mode": "online",
        "deploymentID": "4ed69e58-8cdb-4e3d-944a-41aac3ea9c91",
        "buckets": {
            "count": 2
        },
        "objects": {
            "count": 9
        },
        "usage": {
            "size": 821223
        },
        "services": {
            "vault": {
                "status": "disabled"
            },
            "ldap": {}
        },
        "backend": {
            "backendType": "Erasure",
            "onlineDisks": 4,
            "rrSCData": 2,
            "rrSCParity": 2,
            "standardSCData": 2,
            "standardSCParity": 2
        },
        "servers": [
            {
                "state": "ok",
                "endpoint": "minio2-develop.************:9000",
                "uptime": 456749,
                "version": "2020-08-08T04:50:06Z",
                "commitID": "2a9819aff876b2c92e3428ee6e315ec9ff523d4e",
                "network": {
                    "minio1-develop.************:9000": "online",
                    "minio2-develop.************:9000": "online",
                    "minio3-develop.************:9000": "online",
                    "minio4-develop.************:9000": "online"
                },
                "disks": [
                    {
                        "endpoint": "https://minio2-develop.************:9000/mnt/minstor1/data1",
                        "path": "/mnt/minstor1/data1",
                        "state": "ok",
                        "uuid": "f37624af-0d53-4d27-8541-fb8eab26d81f",
                        "totalspace": 14963175424,
                        "usedspace": 48308224,
                        "availspace": 14914867200
                    }
                ]
            },
            {
                "state": "ok",
                "endpoint": "minio3-develop.************:9000",
                "uptime": 456738,
                "version": "2020-08-08T04:50:06Z",
                "commitID": "2a9819aff876b2c92e3428ee6e315ec9ff523d4e",
                "network": {
                    "minio1-develop.************:9000": "online",
                    "minio2-develop.************:9000": "online",
                    "minio3-develop.************:9000": "online",
                    "minio4-develop.************:9000": "online"
                },
                "disks": [
                    {
                        "endpoint": "https://minio3-develop.************:9000/mnt/minstor1/data1",
                        "path": "/mnt/minstor1/data1",
                        "state": "ok",
                        "uuid": "c1149415-8209-4a93-b5e2-679e44ce3492",
                        "totalspace": 14963175424,
                        "usedspace": 54624256,
                        "availspace": 14908551168
                    }
                ]
            },
            {
                "state": "ok",
                "endpoint": "minio4-develop.************:9000",
                "uptime": 456734,
                "version": "2020-08-08T04:50:06Z",
                "commitID": "2a9819aff876b2c92e3428ee6e315ec9ff523d4e",
                "network": {
                    "minio1-develop.************:9000": "online",
                    "minio2-develop.************:9000": "online",
                    "minio3-develop.************:9000": "online",
                    "minio4-develop.************:9000": "online"
                },
                "disks": [
                    {
                        "endpoint": "https://minio4-develop.************:9000/mnt/minstor1/data1",
                        "path": "/mnt/minstor1/data1",
                        "state": "ok",
                        "uuid": "5d0a054a-919c-4043-8896-33800a9b496f",
                        "totalspace": 14963175424,
                        "usedspace": 54816768,
                        "availspace": 14908358656
                    }
                ]
            },
            {
                "state": "ok",
                "endpoint": "minio1-develop.************:9000",
                "uptime": 456480,
                "version": "2020-08-08T04:50:06Z",
                "commitID": "2a9819aff876b2c92e3428ee6e315ec9ff523d4e",
                "network": {
                    "minio1-develop.************:9000": "online",
                    "minio2-develop.************:9000": "online",
                    "minio3-develop.************:9000": "online",
                    "minio4-develop.************:9000": "online"
                },
                "disks": [
                    {
                        "endpoint": "/mnt/minstor1/data1",
                        "path": "/mnt/minstor1/data1",
                        "state": "ok",
                        "uuid": "0a021d0c-b024-4fac-9926-878605afcc52",
                        "totalspace": 14963175424,
                        "usedspace": 42942464,
                        "availspace": 14920232960
                    }
                ]
            }
        ]
    }
}
```
in syslog I can't see anything related to this

* Operating System and version (`uname -a`):
```
Linux minio1-develop 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
FS: ext4
```

**Comment by harshavardhana** [comment] 2020-08-18 20:06
> * run https://github.com/wasabi-tech/s3-benchmark benchmark for several hours during this benchmark fill up the disk
> * delete all content from wasabi-benchmark-bucket
> * try to delete the bucket

I have tried this doesn't look like I can reproduce this - from what I can tell your nodes are disconnected here. Do you have any logs from the server that you can share?

**Comment by harshavardhana** [comment] 2020-08-18 20:06
Also please use warp https://github.com/minio/warp instead of `s3-benchmark` - we implemented a better tool that supports distributed benchmarking, etc.

**Comment by salacr** [comment] 2020-08-18 21:05
I don't think that my nodes are disconnected as other buckets work just fine I'm able to put / get / delete content without problem also as you can see all nodes print out
`                "state": "ok",` 

In which logs are you interested? I try to obtain it for you.

I can try warp but I'm ok with s3-benchmark as well I guess that the current state of minio server when I can't delete a bucket shouldn't be caused neither by warp nor by s3-benchmark (maybe the benchmark / full disk has no link with the problem at all I'm just describing the process how we get minio into that state)

**Comment by harshavardhana** [comment] 2020-08-19 22:26
> I can try warp but I'm ok with s3-benchmark as well I guess that the current state of minio server when I can't delete a bucket shouldn't be caused neither by warp nor by s3-benchmark (maybe the benchmark / full disk has no link with the problem at all I'm just describing the process how we get minio into that state)

"Slowdown" is only sent when quorum is missing @salacr either your `ulimit -Hn` is small that your concurrency is causing it to overload the server.

**Comment by salacr** [comment] 2020-08-20 08:50
I run on all nodes and it's set to:
`1048576`

In syslog I can see only this lines periodacaly:

```
Aug 20 10:45:56 minio4-develop xe-daemon: Running CollectOS ...
Aug 20 10:45:56 minio4-develop xe-daemon: Running CollectMisc ...
Aug 20 10:45:56 minio4-develop xe-daemon: Running CollectNetworkAddr ...
Aug 20 10:45:56 minio4-develop xe-daemon: Running CollectDisk ...
```

But strange think which I have found and which might help you that even that the bucket should be empty 

```
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Name>wasabi-benchmark-bucket</Name>
    <Prefix></Prefix>
    <Marker></Marker>
    <MaxKeys>10000</MaxKeys>
    <Delimiter></Delimiter>
    <IsTruncated>false</IsTruncated>
</ListBucketResult>
```
I can see that there is one object on the FS

```
/mnt/minstor1/data1/wasabi-benchmark-bucket$ ls
Object-19712
```

I guess that this can be a reason why we are unable to delete that bucket

**Comment by harshavardhana** [comment] 2020-08-20 09:03
> /mnt/minstor1/data1/wasabi-benchmark-bucket$ ls
> Object-19712

Probably can you provide the output of `tree` command for the same path from all the drives? 
also please try to reproduce this with another bucket? perhaps also worth trying with the latest version?

**Comment by salacr** [comment] 2020-08-20 09:36
Unfortunately I'm unable to reproduce it. I have no tree installed and don't have right to do that I hope that this will help:
minio1: no result
```
minio1-develop:/mnt/minstor1/data1/wasabi-benchmark-bucket$ ls
```
minio2: no result
```
minio2-develop:/mnt/minstor1/data1/wasabi-benchmark-bucket$ ls
```
minio3: 
```
minio3-develop:/mnt/minstor1/data1/wasabi-benchmark-bucket$ ls
Object-19712
minio3-develop:/mnt/minstor1/data1/wasabi-benchmark-bucket$ cd Object-19712/
minio3-develop:/mnt/minstor1/data1/wasabi-benchmark-bucket/Object-19712$ ls
xl.meta
```
minio4:
```
minio4-develop:/mnt/minstor1/data1/wasabi-benchmark-bucket$ ls
Object-19712
minio4-develop:/mnt/minstor1/data1/wasabi-benchmark-bucket$ cd Object-19712/
minio4-develop:/mnt/minstor1/data1/wasabi-benchmark-bucket/Object-19712$ ls
xl.meta

```

**Comment by harshavardhana** [comment] 2020-08-20 17:20
> <?xml version="1.0" encoding="UTF-8"?>
> <ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
>     <Name>wasabi-benchmark-bucket</Name>
>     <Prefix></Prefix>
>     <Marker></Marker>
>     <MaxKeys>10000</MaxKeys>
>     <Delimiter></Delimiter>
>     <IsTruncated>false</IsTruncated>
> </ListBucketResult>

@salacr I tried reproducing this list objects is able to list the content so it should have been able to delete it as well 

```
~ aws s3api --profile minio --endpoint-url http://localhost:9002 list-object-versions --bucket testbucket
{
    "Versions": [
        {
            "ETag": "\"20000f00ae467da5b5b18d74f316fa0e1091cfe76e4d18bac677b64962b4028579d44e9b3b5f9738f86a2d0c795008f9\"",
            "Size": 376,
            "StorageClass": "STANDARD",
            "Key": "hosts",
            "VersionId": "null",
            "IsLatest": true,
            "LastModified": "2020-08-20T17:14:42.186Z",
            "Owner": {
                "DisplayName": "",
                "ID": "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
            }
        }
    ]
}
```

```
~ tree /tmp/fs{1..4}/testbucket/hosts
/tmp/fs1/testbucket/hosts [error opening dir]
/tmp/fs2/testbucket/hosts [error opening dir]
/tmp/fs3/testbucket/hosts
└── xl.meta
/tmp/fs4/testbucket/hosts
└── xl.meta

0 directories, 2 files
```

```
~ mc rm -r --force myminio-local2/testbucket/
Removing `myminio-local2/testbucket/hosts`.
```

```
~ tree /tmp/fs{1..4}/testbucket/hosts
/tmp/fs1/testbucket/hosts [error opening dir]
/tmp/fs2/testbucket/hosts [error opening dir]
/tmp/fs3/testbucket/hosts [error opening dir]
/tmp/fs4/testbucket/hosts [error opening dir]

0 directories, 0 files
```

> * Version used  MinIO/RELEASE.2020-08-08T04-50-06Z

I am suspecting that we have fixed something recently and this is fixed already.

**Comment by harshavardhana** [comment] 2020-08-20 17:21
> Unfortunately I'm unable to reproduce it.

Going to close this since I can't reproduce this as well, let's revisit if you can consistently reproduce this.

**Closed as completed by harshavardhana** 2020-08-20 17:21 UTC
Labels: community, fixed

**Comment by salacr** [comment] 2020-08-20 21:06
Ok is it a way how to fix this state? Is it for example safe to delete the objects from FS manualy ?
Can I run some healing proces or something like that?

**Comment by harshavardhana** [comment] 2020-08-20 21:21
> Ok is it a way how to fix this state? Is it for example safe to delete the objects from FS manualy ?
> Can I run some healing proces or something like that?

You can just purge the bucket on the backend..

**Comment by salacr** [comment] 2021-01-25 14:06
Related to #11152
