### ISSUE TITLE
 Keep empty directories after deleting all items from directory

### ISSUE THREAD

**Issue by plenczyk** [minio/minio#5102] opened 2017-10-23 07:33 UTC
To crete an empty directory, i used minio:edge image. Creating an empty directory works fine, but i found one problem. If I create an empty directory and next I upload a file there. Deleting a file will also remove the parent directory. I would like to keep empty parent directories.

## Expected Behavior
I would like to keep empty directories after deleting all items.

## Current Behavior
Delete all items from directory also remove parent directory.

## Steps to Reproduce (for bugs)

1. Create empty directory ( /testDirectory ) 
2. Upload file to directory /testDirectory/testFile.txt
3. Remove file testFile.txt from directory testDirectory.

## Your Environment

* Version used (`minio edge`):

**Comment by wszydlak** [comment] 2017-11-20 06:21
@harshavardhana We need to know if You are going to fix this and when? Cause we rely on this and need to know if we had to do some workaround?

Thank You !

**Comment by harshavardhana** [comment] 2017-11-20 06:27
Sorry for the delay we haven't finalized on the behavior yet.

**Comment by wszydlak** [comment] 2017-11-20 06:29
@harshavardhana But are You planning to do it? And when? :)

**Comment by harshavardhana** [comment] 2017-11-20 07:43
No we are not planning yet, we think the current behavior is fine since creating directories by itself is unusual on object storags. We supported it for limited use case for legacy applications relying on such a behavior. If you control the code for your application it is better to avoid making mkdir like calls on object storage it avoids multiple round trips on simply just creating a directory.

Prefix is created automatically if you choose the right object heirarchy, so it is better for your app to avoid legacy behavior if possible.

**Comment by krishnasrinivas** [comment] 2017-11-20 08:06
@wszydlak it is tricky for us to implement this behaviour. Since we use directories and files to store objects, when an object `a/b/c` is created, we create the directory `a/` and `a/b/`. When `a/b/c` is removed, we automatically remove the directories `a/b` and then `a/` if they are empty. If we do not remove the empty directories then we will leave behind a lot of empty directories. i.e we will not know if `a/` directory was created by a client PutObject request with object name `a/` or if it was created because of PutObject with objectname as `a/b/c`. Hence you see the current behaviour.

**Comment by harshavardhana** [comment] 2017-11-30 20:49
While we can implement this specially can you explain to us the real requirement here 

- Why do you need to keep empty directories? 
- What is the real requirement from the application point of view to preserve directories?
- Is it not possible to upload files with the required prefix? and objects are created automatically? 

@plenczyk ^^

**Comment by harshavardhana** [comment] 2018-01-02 19:13
@plenczyk closing this as "working as intended" for now, feel free to re-open the issue with answers to my previous questions https://github.com/minio/minio/issues/5102#issuecomment-348316434

**Closed as completed by harshavardhana** 2018-01-02 19:13 UTC
Labels: working as intended, priority: medium
