### ISSUE TITLE
Redis notification removes the previously recorded record when a user deletes an object

### ISSUE THREAD

**Issue by maxim-rstor** [minio/minio#3869] opened 2017-03-08 00:29 UTC
## Expected Behavior
Minio notifies Redis and all the events are getting stored in Redis.

## Current Behavior
If you create an object, Minio creates a new key in Redis. When you deletes that object then, Minio removes that key from Redis. The expectation is that notifications and the records created for them are basically a log of operations on data. While currently it's not, the current behavior is essentially just as a database replica.

## Possible Solution
Create separate records for "create", "delete" and any other operation on the same object in Redis (or any other notification target supported by Minio). Otherwise, there are no "events"/"notifications" actually, as the event data is getting lost.

## Steps to Reproduce (for bugs)
1. Enable notification to Redis
2. Upload a file. It will create a new key in Redis.
3. Delete an object. It will remove the previously created key in Redis (unexpected).

**Comment by harshavardhana** [comment] 2017-03-08 00:32
This is a perfectly expected behavior - What you need is change in notification config on your end such that you are only interested in "ObjectCreates" and not "ObjectDeletes" .

```
mc events add s3/mybucket arn:aws:sqs:us-west-2:444455556666:your-queue --events put --prefix photos/ --suffix .jpg
```

**Comment by maxim-rstor** [comment] 2017-03-08 00:36
I haven't specified anything (just mc events add s3/mybucket arn:aws:sqs:us-west-2:444455556666:your-queue), so I would expect all the log records to be stored in Redis.

This is not expected behavior to have the previously logged events deleted. If you got one, it is supposed to persist forever. Otherwise, it is getting inconsistent, and technically useless.

**Comment by maxim-rstor** [comment] 2017-03-08 00:37
PS We need to have both "put" and "delete" stored in the event log (Redis or any other storage) if it was not clear. That's the whole point of event notifications – to keep track of every event happened.

**Comment by harshavardhana** [comment] 2017-03-08 00:55
> This is not expected behavior to have the previously logged events deleted. If you got one, it is supposed to persist forever. Otherwise, it is getting inconsistent, and technically useless.

This is an expected behavior for all database notification targets like 

- postgres
- redis
- elasticsearch

> I haven't specified anything (just mc events add s3/mybucket arn:aws:sqs:us-west-2:444455556666:your-queue), so I would expect all the log records to be stored in Redis.

If you haven't specified to filter anything out by default Minio generates events for all  i.e for both ObjectCreate and ObjectDelete. 

```
mc events add --help |grep '\--events' | head -1
  --events value                   Filter specific type of events. Defaults to all events. (default: "put,delete")
``` 

> PS We need to have both "put" and "delete" stored in the event log (Redis or any other storage) if it was not clear. That's the whole point of event notifications – to keep track of every event happened.

For an audit log you should not use redis target.  Use logging services like 

 - kafka
 - amqp 
 - nats
 - webhook

If you still want to use redis then you can write a simple webhook which can store to redis all the generated events as well - here is an example https://gist.github.com/harshavardhana/b28cbb291b4091242746c07217c86185

**Comment by maxim-rstor** [comment] 2017-03-08 01:02
I guess you are missing the point that people treat events the same way regardless of where the storage is being. In your scenario you provide the same functionality but it works completely different depending on if the user uses Kafka or Postgres. This doesn't seem right. Generate different keys or something to store all the events and not delete them – that's totally up to you, but the functionality is not expected to be different.

PS That's kind of funny. Technically, I am your "customer", and I provide you with my expectations, and you say that "it's not what expected". If you don't want it to be expected, it doesn't make it unexpected. I am just giving you the feedback as the actual person who is trying to be your product's user.

**Comment by harshavardhana** [comment] 2017-03-08 01:11
> PS That's kind of funny. Technically, I am your "customer", and I provide you with my expectations, and you say that "it's not what expected". If you don't want it to be expected, it doesn't make it unexpected. I am just giving you the feedback as the actual person who is trying to be your product's user.

Providing feedback is welcome not denying that, but the database targets are not implemented  for this purpose. So it is working as expected because a database update for notification target is implemented to capture the state of the object storage not to behave like an audit log.  So think of it like a namespace replica which is quite useful for applications which like to query database instead of object storage. In a specific use case where redis is needed to store all events distinctively you can achieve it differently which i explained above. 

> guess you are missing the point that people treat events the same way regardless of where the storage is being. In your scenario you provide the same functionality but it works completely different depending on if the user uses Kafka or Postgres. This doesn't seem right. Generate different keys or something to store all the events and not delete them – that's totally up to you, but the functionality is not expected to be different.

To make notification target flexible i.e to address other varied use cases like yours we added webhook as well which allows you to be flexible i.e you have access to all events and you can store it the way you like it, process it etc.

**Comment by maxim-rstor** [comment] 2017-03-08 01:32
`the database targets are not implemented`

This doesn't make sense to me, sorry. It only depends on how you design your database schema. No one forbids you to store the operation in a separate column in a table to have (e.g., id, ip_address, operation, timestamp). Same with Redis, you could generate keys differently, or use some other data structure there.

I mean, it's not the limitations of some particular database / data storage, but how you design and store the data yourself.

`we added webhook as well which allows you to be flexible`

The thing is that we are currently investigation different object stores to potentially integrate into our product. And one of the requirements is to have as many features out of the box as possible. We  would want avoiding any customization as much as we could. And we actually are not going to use Redis, but it was the easiest way to try for us. But, again, anyway the event log for us is supposed to work for us the same way through all the data storages you support.

**Comment by harshavardhana** [comment] 2017-03-08 01:50
> This doesn't make sense to me, sorry. It only depends on how you design your database schema. No one forbids you to store the operation in a separate column in a table to have (e.g., id, ip_address, operation, timestamp). Same with Redis, you could generate keys differently, or use some other data structure there.
> 
> I mean, it's not the limitations of some particular database / data storage, but how you design and store the data yourself.

Its not a limitation just geared towards addressing a different use case. Database from our point of view is a namespace target rather than a auditing endpoint. 

> The thing is that we are currently investigation different object stores to potentially integrate into our product. And one of the requirements is to have as many features out of the box as possible. We would want avoiding any customization as much as we could. And we actually are not going to use Redis, but it was the easiest way to try for us. But, again, anyway the event log for us is supposed to work for us the same way through all the data storages you support.

Let me discuss this internally about providing a different behavior for database targets more in line with notification queues like NATS and AMQP by flipping a simple config option. For now this is the current behavior.

**Comment by harshavardhana** [comment] 2017-03-18 07:14
> Let me discuss this internally about providing a different behavior for database targets more in line with notification queues like NATS and AMQP by flipping a simple config option. For now this is the current behavior.

Architecture review has been approved we will be implementing a special option which differentiates the behavior. Closing this bug for now.. https://github.com/minio/minio/issues/3928

**Closed as completed by harshavardhana** 2017-03-18 07:14 UTC
Labels: community
