### ISSUE TITLE
object heal errors after updating minio to release 2017-09-29T19:16:56Z

### ISSUE THREAD

**Issue by sebschlue** [minio/minio#5018] opened 2017-10-04 20:52 UTC
`mc admin heal --fake minio`  reports "quorum not available for healing" for many files after update to release 2017-09-29T19:16:56Z from release 2017-08-05T00-00-53Z

## Expected Behavior
`mc admin heal --fake minio` did not report any files before the update and since no data has changed, it should not report any files after the update. Also, this is not a distributed setup but a local 4-disk setup.

## Current Behavior
`mc admin heal --fake minio`  reports "quorum not available for healing" for many files after update.

## Your Environment
Running as docker container on latest Fedora Atomic. 
Started as `docker run -p 9000:9000 --name minio   -v /mnt/disk1:/disk1   -v /mnt/disk2:/disk2   -v /mnt/disk3:/disk3   -v /mnt/disk4:/disk4   minio/minio server /disk1 /disk2 /disk3 /disk4` 

Here is an example of a file for which the error is reported:

xl.json per disk:

disk1:

```
{"version":"1.0.1","format":"xl","stat":{"size":32246,"modTime":"2017-09-28T19:45:57.245684487Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":1,"distribution":[1,2,3,4],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c"}]},"minio":{"release":"RELEASE.2017-08-05T00-00-53Z"},"meta":{"X-Amz-Meta-Mtime":"1367060913","content-type":"image/png"},"parts":[{"number":1,"name":"part.1","etag":"","size":32246}]}
```

disk2:

```
{"version":"1.0.1","format":"xl","stat":{"size":32246,"modTime":"2017-09-28T19:45:57.245684487Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":2,"distribution":[1,2,3,4],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c"}]},"minio":{"release":"RELEASE.2017-08-05T00-00-53Z"},"meta":{"X-Amz-Meta-Mtime":"1367060913","content-type":"image/png"},"parts":[{"number":1,"name":"part.1","etag":"","size":32246}]}
```

disk3:

```
{"version":"1.0.1","format":"xl","stat":{"size":32246,"modTime":"2017-09-28T19:45:57.245684487Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":3,"distribution":[1,2,3,4],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c"}]},"minio":{"release":"RELEASE.2017-08-05T00-00-53Z"},"meta":{"X-Amz-Meta-Mtime":"1367060913","content-type":"image/png"},"parts":[{"number":1,"name":"part.1","etag":"","size":32246}]}
```

disk4:

```
{"version":"1.0.1","format":"xl","stat":{"size":32246,"modTime":"2017-09-28T19:45:57.245684487Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":4,"distribution":[1,2,3,4],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c"}]},"minio":{"release":"RELEASE.2017-08-05T00-00-53Z"},"meta":{"X-Amz-Meta-Mtime":"1367060913","content-type":"image/png"},"parts":[{"number":1,"name":"part.1","etag":"","size":32246}]}
```

**Comment by sebschlue** [comment] 2017-10-05 21:17
[5018-example.zip](https://github.com/minio/minio/files/1360893/5018-example.zip)

**Comment by sebschlue** [comment] 2017-10-05 21:18
I have now attached the full example including data.

**Comment by deekoder** [comment] 2017-10-05 22:01
ok thanks!

**Comment by sebschlue** [comment] 2017-10-05 22:46
It seems that X-Amz-Meta-Mtime meta data causes the problem.

broken:

```
{"version":"1.0.1","format":"xl","stat":{"size":32246,"modTime":"2017-10-05T22:37:28.768775574Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":1,"distribution":[1,2,3,4],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c"}]},"minio":{"release":"RELEASE.2017-09-29T19-16-56Z"},"meta":{"X-Amz-Meta-Mtime":"1367060913","content-type":"image/png"},"parts":[{"number":1,"name":"part.1","etag":"","size":32246}]}
```


good:

```
{"version":"1.0.1","format":"xl","stat":{"size":32246,"modTime":"2017-10-05T22:44:00.940845518Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":1,"distribution":[1,2,3,4],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c"}]},"minio":{"release":"RELEASE.2017-09-29T19-16-56Z"},"meta":{"content-type":"image/png","etag":"3b3d0140bcc0827ffb9d2e5cbba804d2"},"parts":[{"number":1,"name":"part.1","etag":"","size":32246}]}
```

**Comment by donatello** [comment] 2017-10-06 11:21
@sebschlue It appears that your xl.json files have been corrupted.

The zip file you provided helped find the problem - its content is:

```
$ tree .
.
├── disk1
│   └── photos
│       └── Bewerbungen
│           └── Foto.png
│               ├── part.1
│               └── xl.json
├── disk2
│   └── photos
│       └── Bewerbungen
│           └── Foto.png
│               ├── part.1
│               └── xl.json
├── disk3
│   └── photos
│       └── Bewerbungen
│           └── Foto.png
│               ├── part.1
│               └── xl.json
└── disk4
    └── photos
        └── Bewerbungen
            └── Foto.png
                ├── part.1
                └── xl.json

```

Now, if I extract the checksums recorded in the xl.json files for the 1st part (i.e. `part.1`) of Foto.png, I see:

```
$ jq -r .erasure.checksum[0].hash ./disk{1..4}/photos/Bewerbungen/Foto.png/xl.json
9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c
9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c
9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c
9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c
```

They are all identical.

However, when I compute the [Blake2b](https://blake2.net/#su) checksums of the files, they are all different:

```
$ b2sum ./disk{1..4}/photos/Bewerbungen/Foto.png/part.1
9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c  ./disk1/photos/Bewerbungen/Foto.png/part.1
6d8513d20c8e1bceea845b0b12ec7c694111f8bc8a110811b7bf461fcaf6f2f427104bcde743073c772f8d2382aef63b515a0db1d42c6f9587946e2010b8d3c1  ./disk2/photos/Bewerbungen/Foto.png/part.1
ad66749a52363d82e9fb4294a59f4c4a9060eda65af7f0588b1dbcf49fed84423b008b5b16b1ed390ae2bf083d564a0f17f587c25a6038733be00e49af6f0672  ./disk3/photos/Bewerbungen/Foto.png/part.1
6aec02113ee819b8cf65b7b6cd474b4a09893a95c84771b9516e74297674a9c33c90375326c4b0cf1b2d8fa459e29b75ab0c24d46fc78521273dcb01dcb23283  ./disk4/photos/Bewerbungen/Foto.png/part.1
```

Only the first disk's file checksum matches!

When minio heals objects, these checksums are verified to identify valid on-disk parts. In this case, minio finds that the part files on disk{2..4} are having checksum mismatches. Thus, 3 of 4 parts of the file Foto.png are corrupt, and since at least 2 parts are needed for recovery, healing fails.

I am not sure how this could have happened, unless some of the xl.json files were edited by hand (which is NOT recommended at all), but it is highly unlikely that upgrading to the latest release is the cause.

**Comment by sebschlue** [comment] 2017-10-06 13:04
As discussed at the slack channel, it seems that I can deliberately trigger the error by using rclone:

Example 1:

```
$ ./mc admin heal --fake minio/photos/Bewerbungen/Foto.png
mc: <ERROR> Bewerbungen/Foto.png cannot be healed until quorum is available. 

$ ./mc cp Dokumente/Bewerbungen/Foto.png minio/photos/Bewerbungen 
...ente/Bewerbungen/Foto.png:  31.49 KB / 31.49 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 447.59 KB/s 

$ ./mc admin heal --fake minio/photos/Bewerbungen/Foto.png
$ 

$ ./rclone copy Dokumente/Bewerbungen/Foto.png minio:photos/Bewerbungen

$ ./mc admin heal --fake minio/photos/Bewerbungen/Foto.png
mc: <ERROR> Bewerbungen/Foto.png cannot be healed until quorum is available
```

Example 2:

```
$  ./mc admin heal --fake minio/photos/Bewerbungen/Unterschrift.png
$ 

$ ./rclone copy Dokumente/Bewerbungen/Unterschrift.png minio:photos/Bewerbungen

$ ./mc admin heal --fake minio/photos/Bewerbungen/Unterschrift.png
mc: <ERROR> Bewerbungen/Unterschrift.png cannot be healed until quorum is available. 

$ ./mc cp Dokumente/Bewerbungen/Unterschrift.png  minio/photos/Bewerbungen 
...erbungen/Unterschrift.png:  23.66 KB / 23.66 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 468.53 KB/s 0s

 
$ ./mc admin heal --fake minio/photos/Bewerbungen/Unterschrift.png
$ 

```

**Comment by sebschlue** [comment] 2017-10-06 13:05
Can you try to reproduce the error by using rclone copy?

**Comment by sebschlue** [comment] 2017-10-06 13:13
I did not edit xl.json by hand. Please see my examples that show that while using mc copy is fine, using rclone copy triggers the error.

**Comment by donatello** [comment] 2017-10-06 13:42
Removed label after more getting more info.

**Comment by sebschlue** [comment] 2017-10-06 14:35
I am using rclone version  v1.37

**Comment by sebschlue** [comment] 2017-10-06 17:05
I have now re-created everything from scratch, including whole fedora-atomic VM and all virtual disks and can no longer reproduce the issue. I think it's best to close the ticket now. I apologize for the effort and amount of time that was spent on this.

**Comment by krishnasrinivas** [comment] 2017-10-06 18:39
@sebschlue do you know if there is any misconfiguration in the previous setup? just want to make sure that minio does not have any bugs.

**Comment by sebschlue** [comment] 2017-10-06 20:10
I was not aware of any misconfiguration.

When I started from scratch I used the current version immediately and did not do the version update. So this may in theory be a difference (the version number is part of xl.json for instance). But there is no indication that the version update has caused the errors that I experienced. On the other hand, there is no other indication either, there were no i/o errors (disk, bus, filesystem) or crashes of the service. Also, a simple crash would maybe affect a single file that was currently being written. But I could deliberately trigger the error by using rclone copy und could heal the error by using mc copy. This is very strange and I have no idea why it happened.

I have also already repeated the disk failure test  (delete a whole disk and let the self healing heal all files) with the new setup without any issues.

**Comment by harshavardhana** [comment] 2017-10-07 02:42
> $ jq -r .erasure.checksum[0].hash ./disk{1..4}/photos/Bewerbungen/Foto.png/xl.json
> 9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c
> 9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c
> 9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c
> 9ce4970d3550e1dd38fcc8267570fc472c26048f916791608abf634e709df0b1c7a403c98505f3dacf69848fa668b390a9974871561e02ea80a2fcc89db7fb0c

@sebschlue  i have a few questions. 

- Were you ever in the past used our master branch or source compiled Minio and attempted a heal operation in the past on these files? 
- What was the first version that minio was used on this data set? 
- Did you create the above files recently or the file referenced by @donatello is an older file?

**Comment by sebschlue** [comment] 2017-10-07 08:39
There were only two versions involved:

RELEASE.2017-08-05T00-00-53Z
RELEASE.2017-09-29T19-16-56Z

The files were originally created by the older release version.

At the same day, I updated to the current release version and started playing with rclone. At that day, Ire recognized the heal errors.

Is is somehow possible to get/pull the old release version? I could then try to reproduce the error by re-doing the steps including the update.

**Comment by harshavardhana** [comment] 2017-10-07 08:44
Yes you can get the old versions from archive https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2017-08-05T00-00-53Z @sebschlue

**Comment by harshavardhana** [comment] 2017-10-11 09:07
> Yes you can get the old versions from archive https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2017-08-05T00-00-53Z @sebschlue

@sebschlue were you able to look at perhaps reproducing this again?

**Comment by harshavardhana** [comment] 2017-10-23 22:18
We can close this bug @deekoder @nitisht

**Comment by nitisht** [comment] 2017-10-27 06:25
Closing as no response.

**Closed as completed by nitisht** 2017-10-27 06:25 UTC
Labels: priority: medium, triage
