### ISSUE TITLE
mc mirror loses content types

### ISSUE THREAD

**Issue by gavinmcnair** [minio/minio#5324] opened 2017-12-23 23:54 UTC
Due to other issues (Issue #5237) I built a new minio based on the latest version which i cannot use with the old data and used mc mirror to copy it all across. However all the content types have been reset on the destination to binary/octet.

Command line was essentially
```
mc mirror minio/bucket minio2/bucket
```

## Expected Behavior

I would expect attributes like content type (maybe modification date, etc as well) to be preserved.

## Expected Resolution

Mirror should also mirror attributes like content type.

## But
On the positive side it all worked 👍 apart from that.

**Comment by harshavardhana** [comment] 2017-12-25 05:25
Can you provide the mc version that you are using ?

**Comment by gavinmcnair** [comment] 2017-12-25 23:03
I upgraded fairly recently but i am pretty sure that i ran the mirror after the upgrade.

The version is

```
Version: 2017-12-12T01:08:02Z
Release-tag: RELEASE.2017-12-12T01-08-02Z
Commit-id: 4cb6e3534286819d3e11db7c3659164655020bd3
```

**Comment by nitisht** [comment] 2018-02-05 18:07
Reported by user qlb on Slack, looks like the issue is still reproducible on latest `mc` release, @poornas could you please confirm

**Comment by poornas** [comment] 2018-02-05 19:09
@nitisht, have not been able to reproduce issue yet. Did user give additional details?

**Comment by nitisht** [comment] 2018-02-05 19:12
no additional details @poornas he just said mirror dropped content-types. I will ping again to get some more info, will update here

**Comment by poornas** [comment] 2018-02-21 00:37
@qlb said on slack that application/json content-type was dropped - however in my testing, haven't been able to repro the issue.

**Comment by deekoder** [comment] 2018-02-28 22:59
@qLb we have patched this and fixed it. It was already reported here by @gavinmcnair. So we are closing this as fixed.

**Closed as completed by deekoder** 2018-02-28 22:59 UTC
Labels: fixed, priority: medium
