### ISSUE TITLE
Is there a way to see bucket permission in the web app? 

### ISSUE THREAD

**Issue by danyaljj** [minio/minio#2347] opened 2016-08-02 23:20 UTC
Is there a way to see the bucket permissions online?  (e.g accessible to public, private, etc)? 
If so, how about modifying them online? 

<img width="734" alt="screen shot 2016-08-02 at 4 17 20 pm" src="https://cloud.githubusercontent.com/assets/2441454/17348704/f9ea52c0-58cc-11e6-9aab-bbf3087f76a2.png">

**Comment by harshavardhana** [comment] 2016-08-02 23:46
> Is there a way to see the bucket permissions online? (e.g accessible to public, private, etc)? 
> If so, how about modifying them online?

You have to use 'mc policy' to set new policies,  by default all buckets are private. Browser doesn't have a way right now, we are working on it. 

Closing this as duplicate of #1858

**Comment by harshavardhana** [comment] 2016-08-02 23:47
For more information - https://docs.minio.io/docs/minio-client-complete-guide#policy

**Closed as completed by harshavardhana** 2016-08-02 23:46 UTC
