### ISSUE TITLE
Minio should respond with 100 Continue when Expect: 100-continue is provided (chunked uploads)

### ISSUE THREAD

**Issue by ChrisPenner** [minio/minio#7266] opened 2019-02-21 15:22 UTC
Issue: Minio hangs on chunked upload request when s3 doesn't.

Best guess: Minio doesn't appear to respond with the appropriate `100 Continue` after receiving the head of a chunked file upload. (with `Expect: 100-continue` set).

## Expected Behavior

Minio should send the `HTTP/1.1 100 Continue` response after receiving the headers for a file PUT request with `Expect: 100-continue` set

## Current Behavior

We use Minio to mock out s3 for our local tests. We use the [`amazonka`](http://hackage.haskell.org/package/amazonka-1.6.1/) client library for all our s3 interactions and use it to upload large files. It's sends requests of the following form (I listened in by calling to a netcat process instead):

```
PUT /my-bucket/my-file HTTP/1.1
Accept-Encoding: gzip
Transfer-Encoding: chunked
Host: localhost
X-Amz-Date: 20190221T145253Z
X-Amz-Content-SHA256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
Expect: 100-continue
Content-MD5: 1dD7l/e1ORpJRgcO1UCaqQ==
x-amz-meta-token: aQ_pb-CB-Qt0CbFQWm1mig==
x-amz-meta-user: 15e5c1b4-6562-41a0-bf1c-6286d79869c6
Content-Type: application/text
Content-Encoding: aws-chunked
X-Amz-Decoded-Content-Length: 100000
Content-Length: 100176
Authorization: <redacted>
```

As seen above the following headers are set:

- `Transfer-Encoding: chunked`
- `Expect: 100-continue`
- `Content-Encoding: aws-chunked`

The data points behind my assumption that Minio is missing the header are the following experiments:

- When I intercept my app's request using netcat I notice the app sends the headers and then waits for a `HTTP/1.1 100 Continue` before it continues the upload
- When I connect to a minio instance and send the headers myself I don't receive any response after the headers are finished (as indicated by a trailing newline) even though I'd expected the 100 continue response

## Possible Solution

- Minio should recognize the `Expect: 100-continue` header on chunked PUT requests and should respond with `HTTP/1.1 100 Continue` after the headers are received (if well formed).

## Steps to Reproduce (for bugs)

It's difficult to reproduce using available cli clients (I couldn't find a way to do chunked uploads using `aws` or `mc`; please let me know if there's a way :D), I ended up intercepting application traffic to get a valid request, saving it to a file and sending it manually using netcat. I hope this behaviour is relatively simple to understand, but if a minimal app using the `amazonka` client would be very helpful then I can try to boil it down. If there's any other way to help with this I'll do my best :D

Please reference the request headers included above.

## Context

- This represents a difference in behaviour between s3 and minio

## Your Environment

We run minio using docker-compose,

This issue exists on the most recent tag at the moment:  `minio/minio:RELEASE.2019-02-20T22-44-29Z`

### Link to your project:
You can find our docker-compose.yaml and setup [here](https://github.com/wireapp/wire-server/blob/develop/deploy/docker-ephemeral/docker-compose.yaml)

**Comment by harshavardhana** [comment] 2019-02-21 15:24
Do you have a sample code ?

**Comment by ChrisPenner** [comment] 2019-02-21 15:28
@harshavardhana I can attempt to boil down a simple usage of the client lib; but it would still be haskell code; do you have a recommended easier way to represent these sorts of requests? I would say it's easiest to just send these requests via netcat; but it's tricky because the headers expire, etc.

If I provide haskell code/a haskell binary or perhaps a docker image which makes the request would that be helpful to you?

**Comment by harshavardhana** [comment] 2019-02-21 15:40
You can provide is the code. Perhaps a Haskell project with the reproducer will be good too.

We have our own Haskell implementation https://github.com/minio/minio-hs which works perfectly fine both with S3 and Minio so curious to know why it is not working.

We have in past reproduced a similar issue in boto3 python library - can you check it this the case here https://github.com/boto/botocore/pull/1328 ?

At Minio we don't have control over 100-Continue - Go http already handles this before we get the request, so whatever the issue maybe is the issue with Go http here.

**Comment by ChrisPenner** [comment] 2019-02-21 15:47
@harshavardhana Thanks for the quick responses; I'll whip up a minimal example using `amazonka` and verify that it fails on minio and works with s3; It's also possible that `amazonka` itself is the bad agent here; but regardless there seems to be *something* different between minio and s3 because the only thing I'm changing is the s3 endpoint and it succeeds on s3 😄 

I'll be back with some code soon.

**Comment by harshavardhana** [comment] 2019-02-21 15:55
Yeah this is something other than boto3 we have never seen with other AWS SDKs. Even in boto3 the issue is for an object with content-length of zero bytes. Which is clearly from the linked PR states why they are violating HTTP 1.1 spec. 

NOTE: boto3 works fine with AWS S3 too without the fix, but that would mean that AWS S3 is allowing non compliant behavior or not being stricter with HTTP 1.1 spec. This came as a surprise to us but nevertheless we fixed it in boto3.

Curious to see on what amazonka may reveal.

**Comment by ChrisPenner** [comment] 2019-02-22 14:03
@harshavardhana 

I've got a small haskell app which reproduces the issue; please follow the readme here: https://github.com/ChrisPenner/amazonka-minio-failure-case

You can run it in docker if you prefer; it has options to either run against a local minio instance or to upload to aws so you can see the difference in behaviour.\

Hope this helps to demonstrate the problem, thanks! Let me know if there's anything else I can do to help.

**Comment by harshavardhana** [comment] 2019-02-22 17:11
Thanks this is helpful.

**Comment by harshavardhana** [comment] 2019-02-28 18:17
So I got around testing this @ChrisPenner looks like Minio server is able to read the body properly but it's returning an error due to signature mismatch 

```
{SignatureDoesNotMatch The request signature we calculated does not match the signature you provided. Check your key and signing method. 403}
```

Which client is perhaps not able to read for some reason and it hangs perpetually, perhaps this is in your app? 

A signature mismatch can happen for a few reasons here and which we fixed in AWS libraries in the past 

- https://github.com/aws-amplify/aws-sdk-ios/pull/638
- https://github.com/aws-amplify/aws-sdk-ios/issues/716

This is because most probably `Transfer-Encoding` is part of the signature calculation in amazonka library and it shouldn't in accordance with the Streaming Signature V4 spec published by AWS

So two things need to happen - 

- amazonka should ready the response body and return an error to the client correctly, server is able to write the error anyways.
- avoid sending `Transfer-Encoding: chunked` or using that as part of signature v4.

**Comment by ChrisPenner** [comment] 2019-03-01 12:07
@harshavardhana I think I must be misunderstanding something; but if what you say is correct then why do I get a signature mismatch when sending to minio but NOT when sending to s3? There's still some sort of behaviour difference between s3 and minio here because the upload succeeds when sending to s3 but fails with signature mismatch on minio.

My previous thought on this was that perhaps the signature check was failing because the body was actually not being read (because the client was waiting for the signal to continue); so of course the signature wouldn't match since the body was missing haha. If you have other evidence to suggest that minio is actually receiving the full body though then perhaps that's incorrect.

There's still some sort of behaviour difference here; so I'm just trying to figure out why that is 😄; have any ideas?

Thanks for your time 😃

**Comment by harshavardhana** [comment] 2019-03-01 16:27
As I said two fixes are needed here, server has validated the request and sent signature mismatch. Which is correct because Transfer-Encoding cannot be set and used as part of signature calculation. I referenced fixes which we did upstream for iOS SDK. Similar fixes need to happen in amazonka SDK.

Note: you can see iOS SDK was working fine with S3 too.

**Comment by harshavardhana** [comment] 2019-03-04 22:04
Going to close this issue as amazonka bug to not read the http response properly, also to be putting Transfer-Encoding as part of signature V4 where it is clearly isn't necessary or expected.

**Closed as completed by harshavardhana** 2019-03-04 22:04 UTC
Labels: working as intended, community, priority: medium
