### ISSUE TITLE
listObjecs: Listing performance

### ISSUE THREAD

**Issue by fwessels** [minio/minio#1064] opened 2016-01-29 10:06 UTC
I have created a test minio server that stores 100K objects and noticed that the (prefix) listing performance started to decrease as more objects were added.

Are there any guidelines for max number of objects and/or performance for the minio server? Or is this more a case for the "XL" server? (haven't investigated)

Here are the results when listing all objects that start with prefix '0000000' of which there are 1000 (out of the 100K objects):

```
$ time ./listperf -p "0000000" -b "frank" -r "us-east-1" -e "http://localhost:9000" -a "U09DX0NB71K0HBYRQGVD" -s "PsqdAhZD9tYkZ4+eQL0lOywKMoWnGTDpQNeoF47K"
Number of replies: 1000

real    0m14.255s
user    0m0.055s
sys 0m0.022s
```

When doing a similar query on an S3 bucket with 10 times the number of objects (so 1 million in total) I get a pretty linear response time for the 10,000 replies:

```
$ time ./listperf -p "0000000" -b "lifedrive" -r "eu-central-1" -e "https://s3-eu-central-1.amazonaws.com" 
Number of replies: 10000

real    0m0.454s
user    0m0.695s
sys 0m0.065s
```

The list itself is actually done as 16 parallel calls with modified prefixes (so in this case like `fmt.Sprintf("0000000%x", index)` with index ranging from 0x0 to 0xf) for enhanced performance but I guess that that shouldn't make any real difference. (I can provide the source if needed.)

**Comment by harshavardhana** [comment] 2016-01-29 10:16
> Here are the results when listing all objects that start with prefix '0000000' of which there are 1000 (out of the 100K objects):

@fwessels - This is a great test,  is this test run against current minio server code base on master or the released version? 

Released version had some limitations and it slows down a bit, the current master has been optimized. But the optimization is still not finished yet. 

> Are there any guidelines for max number of objects and/or performance for the minio server? Or is this more a case for the "XL" server? (haven't investigated)

We haven't really done any benchmarks and currently there are no known limitations as such. For simple filesystem backend the limitations are generally the same limitations of your backend filesystem.

**Comment by harshavardhana** [comment] 2016-01-29 10:18
> $ time ./listperf -p "0000000" -b "frank" -r "us-east-1" -e "http://localhost:9000" -a "U09DX0NB71K0HBYRQGVD" -s "PsqdAhZD9tYkZ4+eQL0lOywKMoWnGTDpQNeoF47K"
> Number of replies: 1000
> 
> real    0m14.255s
> user    0m0.055s
> sys 0m0.022s

Is it possible to share the source code for this tool? - Thanks.

**Comment by fwessels** [comment] 2016-01-29 10:26
I am running the master version (commit 68a25aa).

Below is the source code -- you should be able to run it against the S3 bucket (public read access), may be a bit slower for you as it is in eu-central-1.

```
package main

import (
    "fmt"
    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/aws/credentials"
    "github.com/aws/aws-sdk-go/service/s3"
    "runtime"
    "sync"
    "flag"
)

var (
    prefixFlag = flag.String("p", "", "prefix for search")
    bucketFlag = flag.String("b", "", "bucket for search")
    regionFlag = flag.String("r", "", "region for search")
    endpointFlag = flag.String("e", "", "endpoint for bucket")
    accessFlag = flag.String("a", "", "access key")
    secretFlag = flag.String("s", "", "secret key")
    cpu      = flag.Int("cpus", runtime.NumCPU(), "Number of CPUs to use. Defaults to number of processors.")
)

func listS3(wg *sync.WaitGroup, index int, results chan<- []string) {

    var creds *credentials.Credentials
    if *accessFlag != "" && *secretFlag != "" {
        creds = credentials.NewStaticCredentials(*accessFlag, *secretFlag, "")
    } else {
        creds = credentials.AnonymousCredentials
    }
    sess := session.New(aws.NewConfig().WithCredentials(creds).WithRegion(*regionFlag).WithEndpoint(*endpointFlag).WithS3ForcePathStyle(true))

    prefix := fmt.Sprintf("%s%x", *prefixFlag, index)

    svc := s3.New(sess)
    inputparams := &s3.ListObjectsInput{
        Bucket: aws.String(*bucketFlag),
        Prefix: aws.String(prefix),
    }

    result := make([]string, 0, 1000)

    svc.ListObjectsPages(inputparams, func(page *s3.ListObjectsOutput, lastPage bool) bool {

        for _, value := range page.Contents {
            result = append(result, *value.Key)
        }

        if lastPage {
            results <- result
            wg.Done()
            return false
        } else {
            return true
        }
    })
}

func listPrefixes() (map[string]bool, error) {

    var wg sync.WaitGroup
    var results = make(chan []string)

    for i := 0x0; i <= 0xf; i++ {
        wg.Add(1)

        go func(index int) {
            listS3(&wg, index, results)
        }(i)
    }

    go func() {
        wg.Wait()
        close(results)
    }()

    prefixHash := make(map[string]bool)
    for result := range results {
        for _, r := range result {
            prefixHash[r] = true
        }
    }

    return prefixHash, nil
}

func main() {
    flag.Parse()
    runtime.GOMAXPROCS(*cpu)
    if *prefixFlag == "" || *bucketFlag == "" || *regionFlag == "" || *endpointFlag == "" {
        fmt.Println("Bad arguments")
        return
    }

    list, _ := listPrefixes()

    fmt.Println("Number of replies:", len(list))
}
```

**Comment by fwessels** [comment] 2016-01-29 10:43
If you would like to have a copy of the minio bucket, I can zip it up for you and send it separately (it is about 414 MB uncompressed).

**Comment by harshavardhana** [comment] 2016-01-29 11:16
> If you would like to have a copy of the minio bucket, I can zip it up for you and send it separately (it is about 414 MB uncompressed).

Sure you can upload it to https://play.minio.io:9000/ using 'mc'

**Comment by harshavardhana** [comment] 2016-01-29 11:16
> I am running the master version (commit 68a25aa).
> 
> Below is the source code -- you should be able to run it against the S3 bucket (public read access), may be a bit slower for you as it is in eu-central-1.

Thanks this is good to know. I will take a look.

**Comment by fwessels** [comment] 2016-01-29 12:08
You can also run it against one of the AWS Public Datasets, for instance the [multimedia-commons](http://aws.amazon.com/public-data-sets/multimedia-commons/) which is located in us-west-2 (and hence a bit slower for me).

```
$ time ./listperf -p "data/images/08" -b "multimedia-commons" -r "us-west-2" -e "https://s3-us-west-2.amazonaws.com"
Number of replies: 25743

real    0m3.015s
user    0m1.299s
sys 0m0.150s
```

**Comment by fwessels** [comment] 2016-01-29 12:30
I have sent you an email with a download link for the minio test bucket.

**Comment by harshavardhana** [comment] 2016-01-29 17:22
> I have sent you an email with a download link for the minio test bucket.

Thanks i have download the data sets.

**Comment by harshavardhana** [comment] 2016-01-30 23:47
Looks like the problem is between recursive and non recursive i see that we recursive there is a memory leak. 

Memory is up for the same data sets in recursive is up by 10x and the listing has slowed down. Where as  listing with 'non-recursive' is acceptable. 

Will work on getting this fixed.

**Comment by harshavardhana** [comment] 2016-01-31 00:03
> $ time ./listperf -p "0000000" -b "frank" -r "us-east-1" -e "http://localhost:9000" -a "U09DX0NB71K0HBYRQGVD" -s "PsqdAhZD9tYkZ4+eQL0lOywKMoWnGTDpQNeoF47K"
> Number of replies: 1000
> 
> real    0m14.255s
> user    0m0.055s
> sys 0m0.022s

For the time being this is an expected value for a filesystem, since it is not using a database to pre-sort the keys. Keys are sorted and then replied back - even for prefix based match. 

Another think to see is the files being dumped entirely in a single bucket at top level, for a filesystem it is a wrong prefix/key combination but a perfect use case for databases. Dumping all files in a single directory slows it down since all the files have to be fetched in a single Readdir() call for it to be sorted and replied back.

We will go through our internal discussion again on how to address this problem.

**Comment by harshavardhana** [comment] 2016-02-09 06:17
Closed - Duplicate of #1076

**Closed as completed by harshavardhana** 2016-02-09 06:17 UTC

**Comment by fwessels** [comment] 2016-02-09 08:43
Great, I'll give it a test run.

**Comment by balamurugana** [comment] 2016-03-04 06:01
@fwessels you could try https://github.com/minio/minio/pull/1186.  This could help in performance :-)
