### ISSUE TITLE
upgrading minio?

### ISSUE THREAD

**Issue by bearmoo-cloud-net** [minio/minio#4534] opened 2017-06-13 14:13 UTC
When upgrading, I notice that I get this error:

6/13/2017 7:00:58 AMDetected configuration inconsistencies in the cluster. Please fix following servers.
6/13/2017 7:00:58 AM[01/04] http://head-node01:9000/export1 : Server versions do not match
6/13/2017 7:00:58 AM[02/04] http://head-node01:9000/export2 : Server versions do not match

## Expected Behavior

Maybe have a backwards compatibility option to allow minio to still serve data while the nodes are going though the upgrade process?

## Current Behavior

I notice that when I upgraded to the lastest release on one node I get an error.

6/13/2017 7:00:58 AMDetected configuration inconsistencies in the cluster. Please fix following servers.
6/13/2017 7:00:58 AM[01/04] http://head-node01:9000/export1 : Server versions do not match
6/13/2017 7:00:58 AM[02/04] http://head-node01:9000/export2 : Server versions do not match

## Possible Solution

Not sure. Maybe have minio detect the version? Or even maybe pass on option ether in mc or minio itself to let know that an upgrade is in progress?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

This upgrade can be potential disruptive. Trying to upgrade with minimal disruption as possible.

## Your Environment

* Version used (`minio version`):
VERSION:
  2017-06-13T08:38:09Z
* Environment name and version (e.g. nginx 1.9.1):
Apache 2.4
* Server type and version: 
Storage, Centos 7.2
* Operating System and version (`uname -a`):
Linux example.com 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment] 2017-06-13 15:34
There are no rolling upgrades @bearmoo-repo . In a given set you upgrade all servers at once. So this error message is by design.

**Comment by deekoder** [comment] 2017-06-14 20:20
@bearmoo-repo  did we address your query? Will go ahead and close this. Please reopen if you think we should still clarify this further.

**Closed as completed by deekoder** 2017-06-14 20:20 UTC
Labels: working as intended, priority: medium
