### ISSUE TITLE
Unable to replace a lost node without downtime

### ISSUE THREAD

**Issue by sblaisot** [minio/minio#5700] opened 2018-03-23 13:38 UTC
I'm trying, on a testing minio cluster with 4 nodes (1 disk each) to drop a node, replace it, and recover to nominal state without downtime.
I can't achieve this, either due to a bug or a lack of documentation.

## Expected Behavior
node fails and gets replaced.
Run Heal on new node which replaces the failed node
Whole cluster (each node) becomes stable in nominal state

## Current Behavior
node fails ang gets replaced.
Run Heal on new node which replaces the failed node
Replaced node health is ok but all other nodes can't connect to replaced node anymore and cluster stay unhealthy.
Stopping and restarting all nodes (inducing a downtime) let the cluster come back to a stable state

## Possible Solution
no re-connect after disk failure ?

## Steps to Reproduce (for bugs)
See details below
1. Build a 4-nodes cluster (with 1 disk each)
2. simulate node replacement: Stop minio on a node and delete all data on the disk (including `.minio.sys`), then sart minio again
3. mc admin heal on replaced server => `.minio.sys` gets rebuilded
4. mc admin heal -r on replaced server => data on this node gets rebuilded
5. all 3 other nodes can't connect to newly replaced disk with traceback in minio logs

```
[ERROR] Unable to fetch disk info for &cmd.networkStorage{rpcClient:(*cmd.AuthRPCClient)(0xc420542480), connected:false} (disk not found)
```

## Context
I know minio is primarily designed to be installed and forgottent and failed disks never replaced, but I need it as a transition for legacy applications and I want to be able to recover on failed disks

## Your Environment
* Version used (`minio version`): 
```
# minio version
Version: 2018-03-19T19:22:06Z
Release-Tag: RELEASE.2018-03-19T19-22-06Z
Commit-ID: a4d2e2b4283b228c34ca2fe0aa007d792a726c3a
```
* Server type and version: 9 (stretch) x64

## Details

Having a 4 node cluster with 1 disk each. We call each node minio-0{1...4}

```
minio-03# mc admin service status local
Uptime: 1 minutes 35 seconds.
minio-03# mc admin info local
●  localhost:9000
   Uptime : online since 1 minute ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 170KiB, Outgoing 64KiB
  Storage : Total 11GiB, Free 11GiB
    Disks : 4, 0


●  10.230.0.21:9000
   Uptime : online since 1 minute ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 157KiB, Outgoing 67KiB
  Storage : Total 11GiB, Free 11GiB
    Disks : 4, 0


●  10.230.0.22:9000
   Uptime : online since 1 minute ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 160KiB, Outgoing 65KiB
  Storage : Total 11GiB, Free 11GiB
    Disks : 4, 0


●  10.230.0.24:9000
   Uptime : online since 1 minute ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 170KiB, Outgoing 66KiB
  Storage : Total 11GiB, Free 11GiB
    Disks : 4, 0


minio-03# mc admin heal -n -r minio-01/
 ◑  test2
    0/3 objects; 402 KiB in 2s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 7 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
minio-03# mc admin heal -n -r minio-02/
 ◓  test/fic2
    0/3 objects; 402 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 7 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
minio-03# mc admin heal -n -r minio-03/
 ◓  mybucket/hosts
    0/3 objects; 402 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 7 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
minio-03# mc admin heal -n -r minio-04/
 ◓  test/fic2
    0/3 objects; 402 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 7 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```

### STOP minio on minio-03 and delete everything (including .minio.sys) on minio disk (same as node rebuild)

```
minio-03# mc admin info minio-01
●  localhost:9000
   Uptime : online since 18 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 258KiB, Outgoing 110KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1


●  10.230.0.22:9000
   Uptime : online since 18 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 264KiB, Outgoing 109KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1


●  10.230.0.23:9000
   Uptime : Server is offline
    Error : dial-http 10.230.0.23:9000/minio/admin: dial tcp 10.230.0.23:9000: getsockopt: connection refused

●  10.230.0.24:9000
   Uptime : online since 18 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 271KiB, Outgoing 111KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1
```

### START minio again on minio-03 (i.e. rebuild a fresh replacement node)

```
minio-03# mc admin info local
●  localhost:9000
   Uptime : online since 28 seconds ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 20KiB, Outgoing 13KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1


●  10.230.0.21:9000
   Uptime : online since 29 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 284KiB, Outgoing 129KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1


●  10.230.0.22:9000
   Uptime : online since 29 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 290KiB, Outgoing 120KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1


●  10.230.0.24:9000
   Uptime : online since 29 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 298KiB, Outgoing 122KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1

minio-03# mc admin heal minio-03
 ◓  mybucket
    0/0 objects; 0 B in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 1 │  25.0% ███          │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 3 │  75.0% █████████    │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```
=> .minio.sys gets rebuilt but no data rebuilt

```
minio-03# mc admin heal -r minio-03/
 ◓  mybucket/hosts
    0/3 objects; 402 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 4 │  57.1% ███████      │
    │ Yellow │ 3 │  42.9% ██████       │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```
Every data gets back ok on minio-03:
```
# mc admin heal -r -n minio-03/
 ◓  test/fic2
    0/3 objects; 402 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 7 │ 100.0% ████████████ │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```

BUT minio-01, 02 and 04 can't see minio-03 anymore and can't get back to an "healthy" state :
```
# mc admin info minio-03
●  localhost:9000
   Uptime : online since 4 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 118KiB, Outgoing 84KiB
  Storage : Total 11GiB, Free 11GiB
    Disks : 4, 0


●  10.230.0.21:9000
   Uptime : online since 33 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 485KiB, Outgoing 270KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1


●  10.230.0.22:9000
   Uptime : online since 33 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 488KiB, Outgoing 255KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1


●  10.230.0.24:9000
   Uptime : online since 33 minutes ago
  Version : 2018-03-19T19:22:06Z
   Region : 
 SQS ARNs : <none>
    Stats : Incoming 596KiB, Outgoing 357KiB
  Storage : Total 5.6GiB, Free 5.5GiB
    Disks : 3, 1

# mc admin heal -r -n minio-01
 ◓  test/fic2
    0/3 objects; 402 KiB in 1s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 1 │  14.3% ██           │
    │ Yellow │ 3 │  42.9% ██████       │
    │ Red    │ 3 │  42.9% ██████       │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
```
and I find in the logs of minio-01 :
```
2018-03-23T14:24:33.067445+01:00 minio-01 minio[25320]: Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:150:cmd.getDisksInfo()
2018-03-23T14:24:33.068655+01:00 minio-01 minio[25320]:        2: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:181:cmd.getStorageInfo()
2018-03-23T14:24:33.069838+01:00 minio-01 minio[25320]:        3: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:220:cmd.xlObjects.StorageInfo()
2018-03-23T14:24:33.070764+01:00 minio-01 minio[25320]:        4: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-sets.go:249:cmd.(*xlSets).StorageInfo()
2018-03-23T14:24:33.071834+01:00 minio-01 minio[25320]:        5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-handlers.go:522:cmd.adminAPIHandlers.HealHandler()
2018-03-23T14:24:33.073099+01:00 minio-01 minio[25320]:        6: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-router.go:66:cmd.(adminAPIHandlers).HealHandler-fm()
2018-03-23T14:24:33.074087+01:00 minio-01 minio[25320]:        7: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
2018-03-23T14:24:33.075402+01:00 minio-01 minio[25320]:        8: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
2018-03-23T14:24:33.076553+01:00 minio-01 minio[25320]:        9: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:617:cmd.rateLimit.ServeHTTP()
2018-03-23T14:24:33.077791+01:00 minio-01 minio[25320]:       10: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:575:cmd.pathValidityHandler.ServeHTTP()
2018-03-23T14:24:33.079006+01:00 minio-01 minio[25320]:       11: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:514:cmd.httpStatsHandler.ServeHTTP()
2018-03-23T14:24:33.081396+01:00 minio-01 minio[25320]:       12: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
2018-03-23T14:24:33.083241+01:00 minio-01 minio[25320]:       13: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:90:cmd.requestHeaderSizeLimitHandler.ServeHTTP()
2018-03-23T14:24:33.084160+01:00 minio-01 minio[25320]:       14: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
2018-03-23T14:24:33.085054+01:00 minio-01 minio[25320]:       15: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:231:cmd.redirectHandler.ServeHTTP()
2018-03-23T14:24:33.086165+01:00 minio-01 minio[25320]:       16: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:289:cmd.minioReservedBucketHandler.ServeHTTP()
2018-03-23T14:24:33.087103+01:00 minio-01 minio[25320]:       17: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:258:cmd.cacheControlHandler.ServeHTTP()
2018-03-23T14:24:33.088167+01:00 minio-01 minio[25320]:       18: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:359:cmd.timeValidityHandler.ServeHTTP()
2018-03-23T14:24:33.088971+01:00 minio-01 minio[25320]:       19: /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
2018-03-23T14:24:33.089440+01:00 minio-01 minio[25320]:       20: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
2018-03-23T14:24:33.089932+01:00 minio-01 minio[25320]:       21: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:465:cmd.resourceHandler.ServeHTTP()
2018-03-23T14:24:33.090404+01:00 minio-01 minio[25320]:       22: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:257:cmd.authHandler.ServeHTTP()
2018-03-23T14:24:33.090872+01:00 minio-01 minio[25320]:       23: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:133:cmd.reservedMetadataHandler.ServeHTTP()
2018-03-23T14:24:33.091361+01:00 minio-01 minio[25320]:       24: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/http/server.go:111:http.(*Server).Start.func1()
2018-03-23T14:24:33.091831+01:00 minio-01 minio[25320]:       25: /opt/go/src/net/http/server.go:1918:http.HandlerFunc.ServeHTTP()
2018-03-23T14:24:33.092299+01:00 minio-01 minio[25320]:       26: /opt/go/src/net/http/server.go:2619:http.serverHandler.ServeHTTP()
2018-03-23T14:24:33.092765+01:00 minio-01 minio[25320]:       27: /opt/go/src/net/http/server.go:1801:http.(*conn).serve()
2018-03-23T14:24:33.093259+01:00 minio-01 minio[25320]: [2018-03-23T13:24:33.067030844Z] [ERROR] Unable to fetch disk info for &cmd.networkStorage{rpcClient:(*cmd.AuthRPCClient)(0xc420542480), connected:false} (disk not found)
```

**Comment by sblaisot** [comment] 2018-03-23 14:43
I also see this log entries on node minio-01 when issuing `mc admin info minio-01`:
```
2018-03-23T15:42:23.690175+01:00 minio-01 minio[25320]: Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:150:cmd.getDisksInfo()
2018-03-23T15:42:23.691898+01:00 minio-01 minio[25320]:        2: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:181:cmd.getStorageInfo()
2018-03-23T15:42:23.693494+01:00 minio-01 minio[25320]:        3: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:220:cmd.xlObjects.StorageInfo()
2018-03-23T15:42:23.694543+01:00 minio-01 minio[25320]:        4: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-sets.go:249:cmd.(*xlSets).StorageInfo()
2018-03-23T15:42:23.695027+01:00 minio-01 minio[25320]:        5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-rpc-client.go:141:cmd.localAdminClient.ServerInfoData()
2018-03-23T15:42:23.695530+01:00 minio-01 minio[25320]:        6: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-handlers.go:244:cmd.adminAPIHandlers.ServerInfoHandler.func1()
2018-03-23T15:42:23.696168+01:00 minio-01 minio[25320]: [2018-03-23T14:42:23.689814013Z] [ERROR] Unable to fetch disk info for &cmd.networkStorage{rpcClient:(*cmd.AuthRPCClient)(0xc420542480), connected:false} (disk not found)
```

**Comment by harshavardhana** [comment] 2018-03-27 04:52
This issue is not fixed correctly yet, re-opening.

**Comment by nitisht** [comment] 2018-03-28 01:12
@sblaisot the fix is now merged onto the master, could you give it a try and let us know how it goes

**Comment by sblaisot** [comment] 2018-04-04 15:58
I tried with version `2018-04-04T05:20:54Z` downloaded from https://dl.minio.io/server/minio/release/linux-amd64/minio and I still have the same problem: I'm unable to recover to a healthy cluster state after stopping minio, clearing disk and restarting minio on one node.

can you provide information on how we are supposed to recover from a lost node ?

**Comment by sblaisot** [comment] 2018-04-04 16:25
I still have the same errors:
```
2018-04-04T18:24:00.822447+02:00 minio-01 minio[1759]: Trace: 1: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:150:cmd.getDisksInfo()
2018-04-04T18:24:00.824160+02:00 minio-01 minio[1759]:        2: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:181:cmd.getStorageInfo()
2018-04-04T18:24:00.825567+02:00 minio-01 minio[1759]:        3: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-v1.go:220:cmd.xlObjects.StorageInfo()
2018-04-04T18:24:00.826802+02:00 minio-01 minio[1759]:        4: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/xl-sets.go:249:cmd.(*xlSets).StorageInfo()
2018-04-04T18:24:00.828265+02:00 minio-01 minio[1759]:        5: /q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-rpc-server.go:126:cmd.(*adminCmd).ServerInfoData()
2018-04-04T18:24:00.829446+02:00 minio-01 minio[1759]:        6: /opt/go/src/reflect/value.go:434:reflect.Value.call()
2018-04-04T18:24:00.830419+02:00 minio-01 minio[1759]:        7: /opt/go/src/reflect/value.go:302:reflect.Value.Call()
2018-04-04T18:24:00.831591+02:00 minio-01 minio[1759]:        8: /opt/go/src/net/rpc/server.go:381:rpc.(*service).call()
2018-04-04T18:24:00.832527+02:00 minio-01 minio[1759]: [2018-04-04T16:24:00.8221358Z] [ERROR] Unable to fetch disk info for &cmd.networkStorage{rpcClient:(*cmd.AuthRPCClient)(0xc4200723c0), connected:false} (disk not found)
```

**Comment by harshavardhana** [comment] 2018-04-04 20:55
> 2018-04-04T18:24:00.832527+02:00 minio-01 minio[1759]: [2018-04-04T16:24:00.8221358Z] [ERROR] Unable to fetch disk info for &cmd.networkStorage{rpcClient:(*cmd.AuthRPCClient)(0xc4200723c0), connected:false} (disk not found)

From this it looks like servers have not started and are disconnected, have you verified your network issues if any?

**Comment by sblaisot** [comment] 2018-04-04 22:43
there is no network issue, the whole cluster is working well until I stop a node, clear all data including `.minio.sys` and restart minio on that node. starting from this point I'm unable to recover an healthy cluster.

I also see this in the log of other nodes:
```
2018-04-05T00:38:43.935352+02:00 minio-01 minio[6383]: Trace: 1: cmd/prepare-storage.go:37:cmd.glob..func4.1()
2018-04-05T00:38:43.936843+02:00 minio-01 minio[6383]:        2: cmd/xl-sets.go:152:cmd.(*xlSets).connectDisks()
2018-04-05T00:38:43.937915+02:00 minio-01 minio[6383]:        3: cmd/xl-sets.go:173:cmd.(*xlSets).monitorAndConnectEndpoints()
2018-04-05T00:38:43.939034+02:00 minio-01 minio[6383]: [2018-04-04T22:38:43.935025799Z] [ERROR] http://10.230.0.23:9000/data/data1: UUID on positions 0:3 do not match with, expected 7a9cd180-4bb4-4f5a-a682-d77ed73c3e68 got e5f67f4f-8878-4fdc-9727-a1e7b30fec78 (UUID on positions 0:3 do not match with, expected 7a9cd180-4bb4-4f5a-a682-d77ed73c3e68 got e5f67f4f-8878-4fdc-9727-a1e7b30fec78)
```

Can you please explain what steps are recommended to recover from a lost node in a cluster ? what command are we supposed to use on what node ?

**Comment by sblaisot** [comment] 2018-04-04 22:50
please also note that after a recursive heal on the lost node, restarting all nodes permits to recover the whole cluster in an healthy state but leads to an outage, which is something I try to avoid in a production environment.

**Comment by harshavardhana** [comment] 2018-04-04 23:13
> there is no network issue, the whole cluster is working well until I stop a node, clear all data including .minio.sys and restart minio on that node. starting from this point I'm unable to recover an healthy cluster.
> 
> I also see this in the log of other nodes:
> 
> 2018-04-05T00:38:43.935352+02:00 minio-01 minio[6383]: Trace: 1: cmd/prepare-storage.go:37:cmd.glob..func4.1()
> 2018-04-05T00:38:43.936843+02:00 minio-01 minio[6383]:        2: cmd/xl-sets.go:152:cmd.(*xlSets).connectDisks()
> 2018-04-05T00:38:43.937915+02:00 minio-01 minio[6383]:        3: cmd/xl-sets.go:173:cmd.(*xlSets).monitorAndConnectEndpoints()
> 2018-04-05T00:38:43.939034+02:00 minio-01 minio[6383]: [2018-04-04T22:38:43.935025799Z] [ERROR] http://10.230.0.23:9000/data/data1: UUID on positions 0:3 do not match with, expected 7a9cd180-4bb4-4f5a-a682-d77ed73c3e68 got e5f67f4f-8878-4fdc-9727-a1e7b30fec78 (UUID on positions 0:3 do not match with, expected 7a9cd180-4bb4-4f5a-a682-d77ed73c3e68 got e5f67f4f-8878-4fdc-9727-a1e7b30fec78)
> Can you please explain what steps are recommended to recover from a lost node in a cluster ? what command are we supposed to use on what node ?

@sblaisot from our local testing I do not see this problem, let me test it again and get back to you. For now will re-open this issue.

**Comment by harshavardhana** [comment] 2018-04-05 00:26
So I tested a local setup with 4 servers here are my results i am using the latest `minio` and `mc`, then deleting all the data on the backend directory restart the server. 

Server shows
```
Trace: 1: cmd/prepare-storage.go:37:cmd.glob..func4.1()
       2: cmd/xl-sets.go:143:cmd.(*xlSets).connectDisks()
       3: cmd/xl-sets.go:225:cmd.newXLSets()
       4: cmd/server-main.go:302:cmd.newObjectLayer()
       5: cmd/server-main.go:265:cmd.serverMain()
       6: vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       7: vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       8: vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       9: cmd/main.go:155:cmd.Main()
      10: main.go:71:main.main()
[2018-04-05T00:21:51.180245287Z] [ERROR] http://localhost:9002/tmp/export2: unformatted disk found (unformatted disk found)
Drive Capacity: 13 GiB Free, 52 GiB Total
Status:         3 Online, 1 Offline. 

Endpoint:  http://localhost:9002
AccessKey: minio 
SecretKey: minio123 
SQS ARNs:  arn:minio:sqs::test1:redis arn:minio:sqs::test2:redis arn:minio:sqs::1:webhook

Browser Access:
   http://localhost:9002

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://localhost:9002 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Trace: 1: cmd/prepare-storage.go:44:cmd.glob..func4.1()
       2: cmd/xl-sets.go:152:cmd.(*xlSets).connectDisks()
       3: cmd/xl-sets.go:177:cmd.(*xlSets).monitorAndConnectEndpoints()
[2018-04-05T00:22:11.221942522Z] [ERROR] http://localhost:9002/tmp/export2: UUID on positions 0:1 do not match with, expected 8a8c9303-9cf2-4246-932d-596aa8b93b6e got d2bd2567-1068-4a2f-938c-1c0fd171f620 (UUID on positions 0:1 do not match with, expected 8a8c9303-9cf2-4246-932d-596aa8b93b6e got d2bd2567-1068-4a2f-938c-1c0fd171f620)
```

As expected that disk is found to be unformatted.  Now starting `mc admin heal` i see that all disks and all objects have healed.

```
$ mc admin heal -r myminio-local1
 ◑  testbucket/sbin/zic
    303/303 objects; 29 MiB in 6s
    ┌────────┬─────┬─────────────────────┐
    │ Green  │ 305 │ 100.0% ████████████ │
    │ Yellow │   0 │   0.0%              │
    │ Red    │   0 │   0.0%              │
    │ Grey   │   0 │   0.0%              │
    └────────┴─────┴─────────────────────┘
```

I see from `mc admin info` that other nodes still see one of the disk as offline. 

```
mc admin info myminio-local1
●  localhost:9001
   Uptime : online since 5 minutes ago
  Version : 2018-04-05T00:19:24Z
   Region : 
 SQS ARNs : arn:minio:sqs::test1:redis arn:minio:sqs::test2:redis arn:minio:sqs::1:webhook 
    Stats : Incoming 29MiB, Outgoing 518KiB
  Storage : Total 104GiB, Free 25GiB
    Disks : 4, 0


●  192.168.1.3:9002
   Uptime : online since 3 minutes ago
  Version : 2018-04-05T00:19:24Z
   Region : 
 SQS ARNs : arn:minio:sqs::test1:redis arn:minio:sqs::test2:redis arn:minio:sqs::1:webhook 
    Stats : Incoming 16MiB, Outgoing 132KiB
  Storage : Total 52GiB, Free 13GiB
    Disks : 3, 1


●  192.168.1.4:9003
   Uptime : online since 5 minutes ago
  Version : 2018-04-05T00:19:24Z
   Region : 
 SQS ARNs : arn:minio:sqs::test1:redis arn:minio:sqs::test2:redis arn:minio:sqs::1:webhook 
    Stats : Incoming 27MiB, Outgoing 12MiB
  Storage : Total 52GiB, Free 13GiB
    Disks : 3, 1


●  192.168.1.5:9004
   Uptime : online since 5 minutes ago
  Version : 2018-04-05T00:19:24Z
   Region : 
 SQS ARNs : arn:minio:sqs::1:webhook arn:minio:sqs::test1:redis arn:minio:sqs::test2:redis 
    Stats : Incoming 28MiB, Outgoing 12MiB
  Storage : Total 52GiB, Free 13GiB
    Disks : 3, 1
```

so looks like I have reproduced it we will fix fit.

**Closed as completed** 2018-04-09 17:25 UTC
Labels: community, fixed, priority: medium

**Comment by harshavardhana** [comment] 2018-04-09 17:27
> please also note that after a recursive heal on the lost node, restarting all nodes permits to recover the whole cluster in an healthy state but leads to an outage, which is something I try to avoid in a production environment.

@sblaisot would you be able to test `docker pull minio/minio:edge`  and let us know how it goes?

**Comment by sblaisot** [comment] 2018-04-10 07:59
I tested and it works. Nice, thank you !

**Comment by zerkms** [comment] 2018-04-13 03:42
Is this problem relevant to

```
Apr 13 03:40:56 minio-2-dev minio[6350]: Error: volume not found
Apr 13 03:40:56 minio-2-dev minio[6350]:        1: cmd/xl-v1-utils.go:298:cmd.readXLMeta()
Apr 13 03:40:56 minio-2-dev minio[6350]:        2: cmd/xl-v1-utils.go:327:cmd.readAllXLMetadata.func1()
```
?

(it's from `RELEASE.2018-04-12T23-41-09Z`)

It happens on demo install: create a cluster of 4 machines, run it, shut down one machine, create a bucket, upload a file and boot up the machine back.

**Comment by harshavardhana** [comment] 2018-04-13 04:10
No @zerkms the new logging is a bit verbose we are working on reducing it.

**Comment by zerkms** [comment] 2018-04-13 04:14
I mostly addressed the `Error: volume not found`: in the scenario I described the 4th machine (which I shut down) cannot re-join the cluster.

**Comment by harshavardhana** [comment] 2018-04-13 04:31
How did you test that it cannot rejoin the cluster ?
