### ISSUE TITLE
Propose a multipart upload backend without fcntl(3)-based coordination.

### ISSUE THREAD

**Issue by krisis** [minio/minio#4704] opened 2017-07-20 11:54 UTC
Requirements
- Crash-consistent, concurrency-safe multipart upload
- Support user meta-data _iff_ EA support is present

**Comment by krisis** [comment] 2017-08-08 18:06
The proposal and discussions surrounding it can be followed here - https://gist.github.com/krisis/761ff87ee0a7368681351239dca5733a

**Comment by GarimaKapoor** [comment] 2017-08-28 04:24
@krisis did we reach any conclusion on this?

**Comment by krisis** [comment] 2017-08-28 04:38
@garima, we decided that we will work on this after we finish ongoing projects.

**Comment by deekoder** [comment] 2017-08-29 20:07
Moving this to future.

**Comment by deekoder** [comment] 2017-11-16 02:47
Duplicate of #5063

**Closed as completed by deekoder** 2017-11-16 02:47 UTC
Labels: duplicate, priority: medium
