### ISSUE TITLE
Minio gateway s3 - Key object encoded

### ISSUE THREAD

**Issue by NMD49** [minio/minio#8325] opened 2019-09-27 14:28 UTC
When minio act as a gateway for s3, a call to GET Bucket (List Objects) Version 2 returns a list with object key encoded.
## Expected Behavior

object key must not be encoded. For example "test/sample.txt"

## Current Behavior

In version 2019-09-26T19:42:35Z object key are encoded for example "test%2Fsample.txt"
It was not the case with version 2019-09-05T23:24:38Z

**Comment by kannappanr** [comment] 2019-09-27 14:35
@NMD49 Thanks for reporting this issue. We will take a look and fix it right away.

**Comment by vadmeste** [comment] 2019-09-27 14:44
@NMD49 what's your S3 client in this case ?

**Comment by NMD49** [comment] 2019-09-27 15:04
mc client RELEASE.2019-09-24T01-36-20Z

**Comment by vadmeste** [comment] 2019-09-27 15:10
> mc client RELEASE.2019-09-24T01-36-20Z

What about your Minio version ?

**Comment by vadmeste** [comment] 2019-09-27 15:20
I am not able to see any issue.

mc listing doesn't show encoded chars while testing against a MinIO gateway s3.
MinIO server version: 2019-09-05T23-24-38Z
mc version: 2019-09-24T01-36-20Z

Did I miss something ?

**Comment by NMD49** [comment] 2019-09-27 16:23
I use this minio server version :
`> minio version`
`Version: 2019-09-26T19:42:35Z`
`Release-Tag: RELEASE.2019-09-26T19-42-35Z`
`Commit-ID: 2a2ff96ee1cb263058e7bfcc553e99054a1e9000`

Put Minio server in gateway mode :
`> set MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F`
`> set MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG`
`> minio gateway s3 https://play.minio.io:9000`

Test #1 with mc on https://play.minio.io:9000
`> set MC_HOST_play=https://Q3AM3UQ867SPQQA43P2F:zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG@play.minio.io:9000`
`> mc ls play/abc`
`[2019-09-27 14:57:11 CEST]   28KiB candle light.jpg`
Result is OK

Test #2 with mc via gateway
`> set MC_HOST_play=http://Q3AM3UQ867SPQQA43P2F:zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG@127.0.0.1:9000`
`> mc ls play/abc`
`[2019-09-27 14:57:11 CEST]   28KiB candle+light.jpg`
Result is not OK (see the "+").

For me this issue is in version 2019-09-26T19:42:35Z

**Comment by vadmeste** [comment] 2019-09-27 16:33
@NMD49 yes, I was able to reproduce this issue, we will fix it quickly

**Comment by vadmeste** [comment] 2019-09-27 16:58
The reason for this issue is that Gateway S3 is using minio-go Core, but changes for url encoding that were made recently process encoding in a more higher level.

**Comment by NMD49** [comment] 2019-09-27 17:31
@vadmeste Thank you very much for your investigation

**Comment by harshavardhana** [comment] 2019-10-06 14:54
This issue is fixed and released..closing

**Closed as completed by harshavardhana** 2019-10-06 14:54 UTC
Labels: community, fixed, triage
