### ISSUE TITLE
minio.exe does not start on windows 8 platform if it failed before

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4234] opened 2017-05-03 23:05 UTC
Downloaded minio.exe  and tried to start it.  Received error message. Minio was already a service. And tried to start it and had failed. New minio downloaded also does not start anymore.

## Expected Behavior
Minio starts normally

## Current Behavior
Unable to load format.json. Unexpected end of JSON input. Source - server-main.go276:serverMain()

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Unclear. 

## Your Environment

* Version used (`minio version`): does not print
* Environment name and version (e.g. nginx 1.9.1): Windows 8
* Server type and version: FS
* Operating System and version (`uname -a`): Windows 8 i386
* Link to your project:

**Comment by harshavardhana** [comment] 2017-05-04 07:29
Fixed by #4195

**Comment by harshavardhana** [comment] 2017-05-05 15:50
Since we merged #4195 we need to test this again on windows, with a new build.

**Comment by harshavardhana** [comment] 2017-05-06 18:03
Followed the steps to reproduce it.  Not able to reproduce the problem anymore `minio.exe` makes sure to not corrupt `format.json`.

**Closed as completed by harshavardhana** 2017-05-06 18:03 UTC
Labels: fixed, priority: medium
