### ISSUE TITLE
[distributed]: mc ls hangs and then fails.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2504] opened 2016-08-20 03:48 UTC
## Expected behaviour

`mc ls` to list . 
## Actual behaviour

Hangs and then fails with `mc: <ERROR> Unable to list folder. 503 Service Unavailable`
## Steps to reproduce the behaviour
- First pulled the latest from distributed branch and build the binary.
- On Minio1: `./minio server --address ":9999" minio1:/tmp/d1 minio2:/tmp/d2 minio1:/tmp/d3 minio2:/tmp/d4`
- On Mino2: `./minio server --address ":9999" minio1:/tmp/d1 minio2:/tmp/d2 minio1:/tmp/d3 minio2:/tmp/d4`
- on Minio1: `mc config host add rdis1 http://65.19.167.91:9999 <AK> <SK>`  (From the output of the server start on the console)
## Minio version
- 38386510a41eca468e0bb05af8f092f94a6c97ad on distributed (latest at this point)
## System information

Minio Servers.

**Comment by harshavardhana** [comment] 2016-08-20 03:50
> Steps to reproduce the behaviour
> 
> First pulled the latest from distributed branch and build the binary.
> 
> On Minio1: ./minio server --address ":9999" minio1:/tmp/d1 minio2:/tmp/d2 minio1:/tmp/d3 minio2:/tmp/d4
> 
> On Mino2: ./minio server --address ":9999" minio1:/tmp/d1 minio2:/tmp/d2 minio1:/tmp/d3 minio2:/tmp/d4
> 
> on Minio1: mc config host add rdis1 http://65.19.167.91:9999 <AK> <SK> (From the output of the server start on the console)

Have you checked "/tmp/d1" permissions?  @krisis is already running another instance on this directory.

**Comment by hackintoshrao** [comment] 2016-08-20 03:51
Let me change the directory and test.

**Comment by harshavardhana** [comment] 2016-08-20 03:52
Closing as duplicate of https://github.com/minio/minio/issues/2502

**Closed as completed by harshavardhana** 2016-08-20 03:52 UTC
