### ISSUE TITLE
Openshift: Insufficient permissions to access path, `/.minio`

### ISSUE THREAD

**Issue by FedericoPonzi** [minio/minio#6524] opened 2018-09-26 09:55 UTC
## Expected Behavior

Tryied to deploy minio on Openshift,  using the generated kubernetes deployment file and have a minio succesfully deployed.

## Current Behavior

The config is succesfully submitted, but it goes in crash loop:
```
ERROR Unable to initialize configuration files: 
Insufficient permissions to access path, `/.minio`.
 > Please ensure the specified path can be accessed.
```
## Context
I've tried to debug the problem, by accessing the pod/container:
```
 $ whoami
whoami: unknown uid 1000130000 #For some reason, the terminal is not run by a root user - dunno why
/ $ ls -a
.           data        lib         root        storage     var
..          dev         media       run         sys
.dockerenv  etc         mnt         sbin        tmp
bin         home        proc        srv         usr
```
There is no .minio file.
In the pod page, these are the info about the container:
```
Containers
minio
Image: minio/minio
Command: <image-entrypoint> server /storage
Ports: 9000/TCP
Mount: storage → /storage read-write
Mount: default-token-7dc89 → /var/run/secrets/kubernetes.io/serviceaccount read-only
```

## Steps to Reproduce (for bugs)

1. Generate a kubernetes config
2. Use `oc create -f deployment.yml`

## Your Environment

OpenShift:  Running (openshift v3.10.0+e3465d0-44)
minishift v1.24.0+8a904d0

As an addition, here is the deployment.yml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. Will be used in deployment below.
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
spec:
  # Read more about access modes here: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: 50Gi
  # Uncomment and add storageClass specific to your requirements below. Read more https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  #storageClassName:
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio-deployment
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: minio
    spec:
      # Refer to the PVC created earlier
      volumes:
      - name: storage
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: minio-pv-claim
      containers:
      - name: minio
        # Pulls the default Minio image from Docker Hub
        image: minio/minio
        args:
        - server
        - /storage
        env:
        # Minio access key and secret key
        - name: MINIO_ACCESS_KEY
          value: "RC2O1H9T9QW2ZY7Z4UR5"
        - name: MINIO_SECRET_KEY
          value: "dFbDCSRFL4OmFepfG4dSGF1fHcuV5ht3Z3Y8IW6U"
        ports:
        - containerPort: 9000
        # Mount the volume into the pod
        volumeMounts:
        - name: storage # must match the volume name, above
          mountPath: "/storage"
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
```

**Comment by nitisht** [comment] 2018-09-26 12:37
@FedericoPonzi we are addressing this issue with #6160 , meanwhile you can try something like this under the `image` section of yaml file?

```yaml
image: minio/minio:RELEASE.2018-09-25T21-34-43Z
args:
- -C
- /data
- server
- /data
```

Here, we're using the `-C` flag to use a custom config directory that is `/data`. Note that you'll need to change the mount paths based on your setup.

**Comment by FedericoPonzi** [comment] 2018-09-26 13:54
Hello and thanks for the prompt response!
I've tried it, and now It gives the following error:

```
ERROR Unable to initialize configuration files: Insufficient permissions to access path, `/data/certs`.
 > Please ensure the specified path can be accessed.
```

**Comment by nitisht** [comment] 2018-09-27 13:51
@FedericoPonzi the problem here that user running Minio doesn't have the permission to write to `/data/certs`. Can you please try `-C` flag with a path where a non root user can write data?

**Comment by harshavardhana** [comment] 2018-10-01 08:00
@FedericoPonzi do you have SELinux enabled by any chance?

**Comment by FedericoPonzi** [comment] 2018-10-04 14:03
Sorry for the latency in the answer!

@nitisht  I've done an ls -lR and seems like it's all root's property :confused: I've run:
```
ls -lR | grep -v -e "root" | grep -v -e "total" | grep -v -e ":" | grep -v -
e "open" | tr -d '\n'
```
And results in a couple of errors accessing some directories and that's all.

@nitisht I'm running on minishift and it's on a VM, so I'm not sure about it
edit: Searching in the repo of minishift, I've found this: https://github.com/minishift/minishift/blob/781349690090db8711a30d0f5fd3d84accc27732/pkg/minishift/provisioner/utils.go#L36

**Comment by harshavardhana** [comment] 2018-10-19 01:58
> @FedericoPonzi do you have SELinux enabled by any chance?

@FedericoPonzi did you check if you have SELinux enabled? you can turn it off and by setting `setenforce Permissive` ?

**Comment by mhworth** [comment] 2019-01-05 03:37
I'm having this same problem, using the [minio operator ](https://github.com/rook/rook/blob/master/Documentation/minio-object-store.md) on a single node OpenShift instances (started with `oc cluster up`). Is there a workaround for this?

**Comment by harshavardhana** [comment] 2019-01-05 05:10
@mhworth which version of Minio are you using ?

**Comment by mhworth** [comment] 2019-01-05 20:51
@harshavardhana Thanks for responding! I figured it out--it was an OpenShift configuration problem. This command will fix it:
`oc adm policy add-scc-to-group anyuid system:authenticated`

The problem is that OpenShift autogenerates a user id, and that messes with all kinds of things. Explanations here:
https://docs.openshift.com/container-platform/3.6/admin_guide/manage_scc.html#enable-images-to-run-with-user-in-the-dockerfile 

and here: 
https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines

**Comment by harshavardhana** [comment] 2019-01-05 22:31
Thanks @mhworth perhaps this issue can be closed

**Comment by mhworth** [comment] 2019-01-06 01:49
Forgot to mention, I saw the same thing error @FedericoPonzi saw (whoami: unknown uid 1000221000 ), so I'm pretty sure this is the same thing @FedericoPonzi ran into. So yes, I suspect this can be closed.

**Comment by kannappanr** [comment] 2019-01-06 03:53
@mhworth Closing this issue based on the previous comments.

**Closed as completed by kannappanr** 2019-01-06 03:53 UTC
Labels: working as intended, priority: medium
