### ISSUE TITLE
Bucket level distribution in standalone erasure minio server

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4047] opened 2017-04-05 01:58 UTC
- Explore this in a separate branch.
- Bucket scheduling:  look up max free space 
- ListBuckets
- Bucket look up cache (in memory)
- Explore routing mechanism for all the calls

**Comment by harshavardhana** [comment] 2017-11-16 03:35
Closing as duplicate of #4153

**Closed as completed by harshavardhana** 2017-11-16 03:35 UTC
Labels: duplicate, priority: medium
