### ISSUE TITLE
Feature: lock XL disks to forbid reading/writing

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2252] opened 2016-07-20 23:46 UTC
That will be necessar for fsck.

**Comment by harshavardhana** [comment] 2016-07-21 01:25
Can you add more gist here @vadmeste ?

**Comment by vadmeste** [comment] 2016-07-21 09:35
fsck will be an independant tool that will check the consistency of the XL data. For that, Minio server should be stopped. However we need to protect data from all malicious and mistaken actions, for example, running a new minio while fsck is checking etc..

Also probably fsck will change data in the XL disks themselves, and there is no safe way to do that only by stopping Minio.

**Comment by vadmeste** [comment] 2016-08-02 16:47
We need a proper shutdown mechanism for this.. could we discuss to see if we will really need that shutdown mechanism for other purposes? (cleaning stale files, etc..)

**Comment by vadmeste** [comment] 2016-08-04 17:07
Timeline: 5 August

**Comment by harshavardhana** [comment] 2016-08-23 07:27
> That will be necessar for fsck.

Locking disks and fsck is out of scope for Minio.  Since most of the time we are non-root we will never be able to disallow access to disks. 

Closing this as not a bug.

**Closed as completed by harshavardhana** 2016-08-23 07:27 UTC
Labels: working as intended
