### ISSUE TITLE
Minio cannot update metadata of an existing object

### ISSUE THREAD

**Issue by dustpuppyNGTI** [minio/minio#3416] opened 2016-12-08 15:05 UTC
The following code works in setting new metadata to an existing object in AmazonS3, but fails with an error in Minio:
```
final AmazonS3Client client = s3.getClient();
final ObjectMetadata md = client.getObjectMetadata(s3.getFilesBucket(), fileId);
final CopyObjectRequest request = new CopyObjectRequest(s3.getFilesBucket(), fileId, s3.getFilesBucket(), fileId)
  .withSourceBucketName(s3.getFilesBucket())
  .withSourceKey(fileId)
  .withNewObjectMetadata(md);

client.copyObject(request);
```

The error in minio is this:
```
storage_1 | com.amazonaws.services.s3.model.AmazonS3Exception: This copy request is illegal because it is trying to copy an object to itself. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 3L137), S3 Extended Request ID: 3L137
storage_1 | 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1343)
storage_1 | 	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:961)
storage_1 | 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:738)
storage_1 | 	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:489)
storage_1 | 	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:448)
storage_1 | 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:397)
storage_1 | 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:378)
storage_1 | 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
storage_1 | 	at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1714)
```

**Comment by harshavardhana** [comment] 2016-12-08 16:42
Closing as duplicate of #3316

**Closed as completed by harshavardhana** 2016-12-08 16:42 UTC
