### ISSUE TITLE
Existing access key not available after changing root user and password

### ISSUE THREAD

**Issue by weeee9** [minio/minio#20574] opened 2024-10-22 02:08 UTC
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I used Docker Compose to start the MinIO service. After testing for a while, I realized I needed to update the root user credential, so I updated the `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` environment variables to replace the default values.

However, after restarting the container and logging into the MinIO web interface, I found that the previously created access keys had disappeared. I tried to recreate them using the existing records, but encountered the error: `Specified service account action is not allowed: the service account access key is taken by another user.` 

Currently, I can only revert the changes to the `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` environment variables back to the default root username and password in order to use the original access keys again.

## Expected Behavior
Everything works as before changing the root user credential.

## Current Behavior
After changing, all the created access keys are not available anymore.

## Steps to Reproduce (for bugs)
1. Start MinIO server with default root credential.
2. Logging into web and create some access keys.
3. Changing root credentials by setting `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` environment variables.
4. Logging into web again and head to access keys page, access keys created at step 2 are missing.

## Your Environment

* Version used (`minio --version`): minio/minio:RELEASE.2024-08-29T01-40-52Z-cpuv1
* Server setup and configuration: I used docker-compose to start a server
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment] 2024-10-22 02:15
yes this is expected @weeee9 duplicate of #17565

**Closed as completed by harshavardhana** 2024-10-22 02:15 UTC
Labels: community, triage

**Comment by weeee9** [comment] 2024-10-22 02:21
@harshavardhana 
In this [comment](https://github.com/minio/minio/issues/17565#issuecomment-1619294676) you mentions `Just recreate the same credentials that you did again once the new parent exists`, but how to achieve if the `Specified service account action is not allowed: the service account access key is taken by another user.` occurred?

Update: Have to remove it manually then re-created them. `mc admin user svcacct remove ALIAS SERVICE-ACCOUNT`

**Comment by harshavardhana** [comment] 2024-10-22 02:38
> @harshavardhana In this [comment](https://github.com/minio/minio/issues/17565#issuecomment-1619294676) you mentions `Just recreate the same credentials that you did again once the new parent exists`, but how to achieve if the `Specified service account action is not allowed: the service account access key is taken by another user.` occurred?
> 
> Update: Have to remove it manually then re-created them. `mc admin user svcacct remove ALIAS SERVICE-ACCOUNT`

Yes remove it and recreate
