### ISSUE TITLE
[distributed] 503 Service Unavailable during concurrent PUT

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3183] opened 2016-11-05 13:44 UTC
Setup:
6 minio processes on localhost (process per disk setup)
i.e 6 X  `minio server --address localhost:9001 http://localhost:9001/export/sk1 http://localhost:9002/export/disk2 http://localhost:9003/export/disk3 http://localhost:9004/export/disk4 http://localhost:9005/export/disk5 http://localhost:9006/export/disk6`

Had a client script running:
```
package main

import (
	"fmt"
	"log"
	"os"
	"strings"
	"sync"

	minio "github.com/minio/minio-go"
)

func main() {
	accessKey := os.Getenv("MINIO_ACCESS_KEY")
	secretKey := os.Getenv("MINIO_SECRET_KEY")

	testCases := []struct {
		host string
		data string
	}{
		{"localhost:9001", "one"},
		{"localhost:9002", "two"},
		{"localhost:9003", "three"},
		{"localhost:9004", "four"},
		{"localhost:9005", "five"},
		{"localhost:9006", "six"},
	}

	i := 0
	for {
		i++
		fmt.Println(i)
		wg := &sync.WaitGroup{}
		for _, test := range testCases {
			wg.Add(1)
			go func(host string, data string) {
				defer wg.Done()
				client, err := minio.New(host, accessKey, secretKey, false)
				if err != nil {
					log.Fatalln(err)
				}
				_, err = client.PutObject("test", "testobject", strings.NewReader(data), "")
				if err != nil {
					log.Println(err)
				}
			}(test.host, test.data)
		}
		wg.Wait()
	}
}
```

I was Ctrl-C'ing servers randomly and bringing it back up, at some point, when 4 servers were up, client got:
```
2016/11/05 19:07:10 503 Service Unavailable
2016/11/05 19:07:14 503 Service Unavailable
453
2016/11/05 19:07:14 Get http://localhost:9003/test/?location=: dial tcp 127.0.0.1:9003: getsockopt: connection refused
2016/11/05 19:07:14 Get http://localhost:9002/test/?location=: dial tcp 127.0.0.1:9002: getsockopt: connection refused
2016/11/05 19:07:28 503 Service Unavailable
2016/11/05 19:07:36 503 Service Unavailable
454
2016/11/05 19:07:36 Get http://localhost:9002/test/?location=: dial tcp 127.0.0.1:9002: getsockopt: connection refused
2016/11/05 19:07:36 Get http://localhost:9003/test/?location=: dial tcp 127.0.0.1:9003: getsockopt: connection refused
2016/11/05 19:07:44 503 Service Unavailable
2016/11/05 19:07:54 503 Service Unavailable
```

Server logs had lot of:
```
ERRO[0622] Unable to create an object.                   cause=Storage resources are insufficient for the write operation. location=[object-handlers.go:509:objectAPIHandlers.PutObjectHandler()] stack=xl-v1-object.go:336:rename xl-v1-object.go:361:renameObject xl-v1-object.go:535:xlObjects.PutObject <autogenerated>:858:(*xlObjects).PutObject object-handlers.go:506:objectAPIHandlers.PutObjectHandler api-router.go:61:(objectAPIHandlers).PutObjectHandler-fm
```

**Comment by vadmeste** [comment] 2016-11-05 13:49
@krishnasrinivas, this is most likely similar to https://github.com/minio/minio/issues/3149, you can check that by noticing that a multipart upload id exists in disks < write quorum

**Comment by krishnasrinivas** [comment] 2016-11-05 13:58
@vadmeste this is single-put operation, also the uploads started working fine when the 2 servers that were down were brought back up. In https://github.com/minio/minio/issues/3149 I see that you observe `Cannot upload by that name anymore, even if I restart all nodes or restart upload.`

**Comment by hackintoshrao** [comment] 2016-11-05 14:07
> Cannot upload by that name anymore, even if I restart all nodes or restart upload.

@krishnasrinivas , I've witnessed this too.

**Comment by krishnasrinivas** [comment] 2016-11-05 14:09
> Cannot upload by that name anymore, even if I restart all nodes or restart upload.
> 
> @krishnasrinivas , I've witnessed this too.

@hackintoshrao `Cannot upload by that name anymore, even if I restart all nodes or restart upload.` is observed by @vadmeste  in https://github.com/minio/minio/issues/3149, I did not observe it in this issue.

**Comment by donatello** [comment] 2016-11-07 00:34
This issue is different from #3149 as here, it is not a multipart upload.

**Comment by krishnasrinivas** [comment] 2016-11-09 15:00
timeline: 10-11

**Comment by harshavardhana** [comment] 2016-11-10 16:41
@krishnasrinivas can you reproduce this with latest master?

**Comment by harshavardhana** [comment] 2016-11-17 20:12
Taking this

**Comment by harshavardhana** [comment] 2016-11-17 23:53
Tested this with latest master not able to reproduce. 

Start minio servers like this 

```
for i in $(seq 1 6);do minio server --address localhost:900${i} http://localhost:9001/tmp/disk1 http://localhost:9002/tmp/disk2 http://localhost:9003/tmp/disk3 http://localhost:9004/tmp/disk4 http://localhost:9005/tmp/disk5 http://localhost:9006/tmp/disk6 & done
```

Run the following program.

``` go
// Start the minio servers in another terminal.
// --------------------
// #!/bin/bash
//
// for i in $(seq 1 6); do
//      minio server --address localhost:900${i} http://localhost:9001/tmp/disk1 http://localhost:9002/tmp/disk2 \
//            http://localhost:9003/tmp/disk3 http://localhost:9004/tmp/disk4 http://localhost:9005/tmp/disk5 \
//            http://localhost:9006/tmp/disk6 &
// done
// ---------------------
//
// This starts 6 disk distributed XL setup locally.
//
// On another terminal compile the code.
//
//   go build parallel-put.go
//
// Grab accessKey and secretKey from minio servers and set them as env
// MINIO_ACCESS_KEY and MINIO_SECRET_KEY respectively.
//
// Proceed to run the test on all the 6 nodes.
//
//  ./parallel-put localhost:900{1..6}
//
package main

import (
    "fmt"
    "log"
    "os"
    "strings"
    "sync"

    minio "github.com/minio/minio-go"
)

func getMinioClients(minioNodes []string) ([]*minio.Client, error) {
    accessKey := os.Getenv("MINIO_ACCESS_KEY")
    secretKey := os.Getenv("MINIO_SECRET_KEY")

    clnts := make([]*minio.Client, len(minioNodes))
    for i, minioNode := range minioNodes {
        client, err := minio.New(minioNode, accessKey, secretKey, false)
        if err != nil {
            return nil, err
        }
        clnts[i] = client
    }
    return clnts, nil
}

func main() {
    clnts, err := getMinioClients(os.Args[1:])
    if err != nil {
        log.Fatalln(err)
    }

    // Data to be uploaded.
    data := make([]string, len(clnts))
    for i := range data {
        data[i] = strings.Repeat(fmt.Sprintf("Hello, World - %d", i), 10)
    }

    // Continously write to all nodes.
    j := 0
    for {
        j++
        fmt.Println("Running: ", j)
        wg := &sync.WaitGroup{}
        for i, d := range data {
            wg.Add(1)
            go func(i int, d string) {
                defer wg.Done()
                _, perr := clnts[i].PutObject("test", "testobject", strings.NewReader(d), "")
                if perr != nil {
                    log.Println(perr)
                }
            }(i, d)
        }
        wg.Wait()
    }
}
```

Randomly take down nodes one by one and start them after a delay of 10-15secs, don't see any symptoms anymore. Repeated the same tests with taking 2 at a time as well no unexpected errors were observed. 

Closing this bug as fixed in master.

**Closed as completed by harshavardhana** 2016-11-17 23:53 UTC
