### ISSUE TITLE
Size of the object uploaded to minio is ZERO

### ISSUE THREAD

**Issue by mayurjain0312** [minio/minio#3436] opened 2016-12-13 00:41 UTC
Hi Minio Team,

I am using minio on my linux box since last few days.
Everything seems to have been running fine.

But, since today morning, I am facing issues uploading/downloading files.
On uploading the file, I see that the file is uploaded in the min io UI, but the size of the file is ZERO.
I am using boto3 to call minio apis.

In the minio logs I am constantly seeing the following:

ERRO[0851] Unable to peek into the protocol              cause=EOF source=[server-mux.go:78:(*ConnMux).PeekProtocol()]

Following is the code snippet:

args = parse_args(sys.argv[1:])

setup_logging(logging.INFO)
upload_local_file_path = args.path

s3 = boto3.resource('s3',
                    endpoint_url='http://129.46.71.250:9000',
                    aws_access_key_id='8LZG1GMCMARYRJRMN0MD',
                    aws_secret_access_key='euwFSUIYlmqrFSlmfJI4HPCegA3lL/zDgQUEeQuH',
                    config=Config(signature_version='s3v4'),
                    region_name='us-east-1')

file_name = os.path.basename(upload_local_file_path)

logging.info("Creating bucket: ")
bucket_name = "test"
try:
    s3.create_bucket(Bucket=bucket_name)
    logging.info("Bucket created: " + bucket_name)
except botocore.exceptions.ClientError:
    logging.info("Bucket already exists: " + bucket_name)

test_bucket = s3.Bucket(bucket_name)

logging.info("Start upload: ")
test_bucket.upload_file(upload_local_file_path, file_name)
logging.info("End upload: ")
logging.info(
    "uploaded " + upload_local_file_path + " with name: " + file_name + " in bucket: " + bucket_name)

**Comment by harshavardhana** [comment] 2016-12-13 00:42
@mayurjain0312  can you paste your 'minio version' ?

**Comment by harshavardhana** [comment] 2016-12-13 00:43
> ERRO[0851] Unable to peek into the protocol cause=EOF source=[server-mux.go:78:(*ConnMux).PeekProtocol()]

This is not a bug we have fixed the log in a recent release. Can you update to latest release?

**Comment by mayurjain0312** [comment] 2016-12-13 00:43
2016-11-26T02:23:47Z

**Comment by mayurjain0312** [comment] 2016-12-13 01:48
https://gist.github.com/mayurjain0312/8697757004e9bb74ba60dcc07ae75154

**Comment by mayurjain0312** [comment] 2016-12-13 01:51
I just uploaded a file and the size is still 0

**Comment by mayurjain0312** [comment] 2016-12-13 01:51
Although I don't see any errors in the logs on minio

**Comment by mayurjain0312** [comment] 2016-12-13 01:52
I uploaded a short video file minion.mp4, but the size is zero

**Comment by harshavardhana** [comment] 2016-12-13 02:20
Closing this as not a bug in minio.

**Closed as completed by harshavardhana** 2016-12-13 02:20 UTC
