### ISSUE TITLE
[resolved] After replacing a broker server with a new one the cluster is inconsistent

### ISSUE THREAD

**Issue by rudolpho1** [minio/minio#9275] opened 2020-04-06 18:27 UTC
We have two servers and I am running one minio instance (with two disks) on each server. This is working fine. To simulate a system failure I shut down one server. After that, I am still able to read files but cannot write, as expected. Now, I replace the (potentially broken) server with a new one. After that I am able to create new files again, but the data is inconsistent. It seems that files present before the shutdown of the original server were not added to the new server. When I hit refresh in the UI, the files randomly appear and disappear. Nevertheless `mc admin info` lists all drives as `ok` and `mc admin heal` does not fix the issue.

## Expected Behavior
After replacing a broken server with a new one the cluster data should still be consistent. At least after running `mc admin heal`.

## Current Behavior
The data is inconsistent. Data created before shutting down the original server is not present on the new server.

## Steps to Reproduce (for bugs)
1. Prepare three servers (e.g. A: 192.168.0.2, B: 192.168.0.3, C: 192.168.0.4)
2. start minio on A and B with `./minio server http://192.168.0.{2...3}/mnt/minio{1...2}`
3. add a bucket X and a file F1 inside X
4. stop minio on server A
5. start minio on C with `./minio server http://192.168.0.{3...4}/mnt/minio{1...2}`
6. stop minio on server B and restart it with `./minio server http://192.168.0.{3...4}/mnt/minio{1...2}`
7. now you are able to create files again. Create a file F2 inside bucket X
8. in the UI navigate to bucket X and refresh the page a few times
Sometimes you will see only F2 and sometimes you see both, F1 and F2, presumingly depending if the request was served from server B or C.

## Context
We would like to use minio in our system and I am investigating it now. I would like to simulate the case where one server breaks down and it takes some time
to get a replacement. During this time period I would like to add another server to the cluster to allow write operations again. 

## Environment
- 3 Openstack servers with 16GB RAM, 4 CPUs each
- Fedora 31
- Minio version 2020-04-04T05:39:31Z

**Comment by i0x71** [comment] 2020-04-10 17:35
Not to hijack this thread, but i just did a test with 4 servers 1 disk each, and everything was rebuild successfully, however there is an error which gets thrown the first time heal is ran
any ideas what it means 

Procedure
Setup 4 hosts with 1 disk each
minio server http://NODE_A:9000/disk http://NODE_B:9000/disk http://NODE_C:9000/disk http://NODE_D:9000/disk

Client running on laptop configured as follows:
mc config host add cluster http://NODE_A:9000

On NODE_A and NODE_B run rm -rf /disk/*
Right after that run
mc admin heal -r cluster
mc: <ERROR> Unable to display heal status. Heal had an error - Storage resources are insufficient for the write operation.


The second time i run it, everything shows properly as healing and cluster is back to normal.

Is this expected behavior ?

Just an fyi, when rm -rf /disk/* was ran only on NODE_A
and heal was ran afterwards, everything healed without any issues
I have not done any data verification tests.

**Comment by vadmeste** [comment] 2020-04-10 18:29
@rudolpho1 how are you running the heal command ? you need -r flag

**Comment by vadmeste** [comment] 2020-04-10 18:30
@i0x71 if you are running the latest version, could you open a new issue ?

**Comment by i0x71** [comment] 2020-04-10 18:39
@vadmeste 
Sure

**Comment by harshavardhana** [comment] 2020-04-14 20:16
> @rudolpho1 how are you running the heal command ? you need -r flag

As per @vadmeste this looks like you didn't run `mc admin heal -r` closing this issue. Please re-open if you have further queries.

**Closed as completed by harshavardhana** 2020-04-14 20:16 UTC
Labels: working as intended, community

**Comment by rudolpho1** [comment] 2020-04-16 13:39
@vadmeste @harshavardhana , yes the -r option in mc admin heal fixes the issue. Thanks a lot!!
