### ISSUE TITLE
ListObjectsV2 gets unexpected CommonPrefixes

### ISSUE THREAD

**Issue by amiryi365** [minio/minio#10157] opened 2020-07-29 08:06 UTC
I use **minio** to store files in file system style keys (indirectly by **mlflow** package).
Upload files seems OK, and I can display and download files by minio browser.
Download files also works well.
But calling **ListObjectsV2** by python3.7 **boto3** paginator for a "leaf" object (a file), gets results with a "child",
i.e. I get **"CommonPrefixes"** in the results with key of format: **/path/to/leaf_file/\<auto-generated-name>**
I cannot see this \<auto-generated-name> "dir"  in the browser.
Additionally, it seems **inconsistent**, as for some "files" I got this bug at start, and later it worked fine...

## Expected Behavior
I expect ListObjectsV2 to return **no CommonPrefixes or Contents objects**!

## Steps to Reproduce (for bugs)
I'm using the **mlflow 1.9.0** python package.
The bug is expressed in the following function from file **mlflow/store/artifact/s3_artifact_repo.py** class  **S3ArtifactRepository**:
```
    def list_artifacts(self, path=None):
        (bucket, artifact_path) = data.parse_s3_uri(self.artifact_uri)
        dest_path = artifact_path
        if path:
            dest_path = posixpath.join(dest_path, path)
        infos = []
        prefix = dest_path + "/" if dest_path else ""
        s3_client = self._get_s3_client()
        paginator = s3_client.get_paginator("list_objects_v2")
        results = paginator.paginate(Bucket=bucket, Prefix=prefix, Delimiter='/')
        for result in results:
            # Subdirectories will be listed as "common prefixes" due to the way we made the request
            for obj in result.get("CommonPrefixes", []):
                ####  BUG IS HERE: in case of "file" object, it enters here with this auto-generated postfix
                subdir_path = obj.get("Prefix")
                self._verify_listed_object_contains_artifact_path_prefix(
                    listed_object_path=subdir_path, artifact_path=artifact_path)
                subdir_rel_path = posixpath.relpath(
                    path=subdir_path, start=artifact_path)
                if subdir_rel_path.endswith("/"):
                    subdir_rel_path = subdir_rel_path[:-1]
                infos.append(FileInfo(subdir_rel_path, True, None))
            # Objects listed directly will be files
            for obj in result.get('Contents', []):
                file_path = obj.get("Key")
                self._verify_listed_object_contains_artifact_path_prefix(
                    listed_object_path=file_path, artifact_path=artifact_path)
                file_rel_path = posixpath.relpath(path=file_path, start=artifact_path)
                file_size = int(obj.get('Size'))
                infos.append(FileInfo(file_rel_path, False, file_size))
        return sorted(infos, key=lambda f: f.path)

```

## Context
This bug causes an mlflow bug: when the user selects an artifact file in the mlflow UI, Ui requests the file contents from mlflow server, which first checks if its a "file" or "dir" using the above **list_artifacts()**. This bug causes mlflow believe it's a dir, and apparently raise **IsADirectoryError** (user gets error in mlflow UI).

## Your Environment
* **minio version:** 2020-07-18T18:48:16Z
* **Server setup and configuration:** runs on **docker**. config:
volums: has 2 volumns
ports:  9001-9000
environment: MINIO_ACCESS_KEY, MINIO_SECRET_KEY
command:  server http://minio{1...2}/data{1...2}
healthcheck: 
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
* **Operating System:** Centos linux release 7.4
* **python packages:** mlflow 1.9.0, boto3 1.11.14, botocore 1.14.14
* **browsers:** chrome, firefox

**Comment by harshavardhana** [comment] 2020-07-29 23:50
> I expect ListObjectsV2 to return **no CommonPrefixes or Contents objects**!

CommonPrefixes will be present if there is an empty directory and lexically it part of the batch that is being sent. 
CommonPrefixes will be empty if no such empty directories are present your delimiter is not "/" 

Since in your case delimiter is present this will report CommonPrefixes as per the AWS S3 spec @amiryi365 

> I cannot see this <auto-generated-name> "dir" in the browser.

I suspect this is a stale directory issue should should be gone in the latest releases. can you upgrade to latest and test again?

**Comment by amiryi365** [comment] 2020-07-30 06:07
@harshavardhana Thanks for replying :-)
First of all, this code is **mlflow** code, a common ML logging framework with 7k starts and 1.6k forks in github.
I made a deep search and found no similar bugs or complains.
I also posted a bug issue in mlflow github [here](https://github.com/mlflow/mlflow/issues/3154) but got no real answers.
I also found a very similar code in [Airflow](https://airflow.readthedocs.io/en/stable/_modules/airflow/hooks/S3_hook.html), so I believe it should work.

> CommonPrefixes will be present if there is an empty directory and lexically it part of the batch that is being sent.
> CommonPrefixes will be empty if no such empty directories are present your delimiter is not "/"

In my case it returns an empty subdirectory with a long auto-generated name. I cannot find any evidence in the mlflow code for creating such a dummy empty dir in S3.
Additionally, it's **inconsistent**, as for some "files" keys I got this CommonPrefix at start, and later I didn't (I can't tell what caused the change...)

> I suspect this is a stale directory issue should should be gone in the latest releases. can you upgrade to latest and test again?

I'm currently using the **2020-07-18T18:48:16Z** version which is pretty new, **less than 2 weeks**!
Do you think there's a fix to that in newer releases? (there are only minor changes)

**Comment by harshavardhana** [comment] 2020-07-30 06:09
> I'm currently using the **2020-07-18T18:48:16Z** version which is pretty new, **less than 2 weeks**!

That is quite old in MinIO's world @amiryi365 feel free to test with latest release.

**Comment by harshavardhana** [comment] 2020-07-30 06:10
> In my case it returns an empty subdirectory with a long auto-generated name. I cannot find any evidence in the mlflow code for creating such a dummy empty dir in S3.
> Additionally, it's **inconsistent**, as for some "files" keys I got this CommonPrefix at start, and later I didn't (I can't tell what caused the change...)

If it's inconsistent then it's a different problem - I am suspecting that it would be fixed in the latest release.

**Comment by amiryi365** [comment] 2020-07-30 11:55
@harshavardhana I just compared that **list_artifacts()** function in 2 ways:

1. As usual: select the file in the mlflow UI, then I can debug it in the mlflow worker process.

1. Run the same function (copied to a test project) directly with same params.

**For the same path, I get one dummy subdir in test 1 (buggy), and no children in test 2 (OK) !!!**
I carefully checked that s3 credentials and file path are identical in both.
I even compared the **s3_client** object to make sure they've got the same config.
Any suggestion?

**Comment by amiryi365** [comment] 2020-08-02 10:54
@harshavardhana I just **downgraded** to minio **2020-04-28T23:56:56Z** and it solved the bug!
Please check your last release/s for such a bug... (I don't know if it's a read bug or write bug).

**Comment by harshavardhana** [comment] 2020-08-02 15:54
> @harshavardhana I just **downgraded** to minio **2020-04-28T23:56:56Z** and it solved the bug!
> Please check your last release/s for such a bug... (I don't know if it's a read bug or write bug).

I asked you to test the latest release @amiryi365 would it be possible to validate latest release?

**Comment by amiryi365** [comment] 2020-08-03 05:18
> I asked you to test the latest release @amiryi365 would it be possible to validate latest release?

@harshavardhana I'm sorry, I already spent 2 weeks around this bug (before I posted here I had a long session with mlflow too)

**Comment by harshavardhana** [comment] 2020-08-03 05:19
> > I asked you to test the latest release @amiryi365 would it be possible to validate latest release?
> 
> @harshavardhana I'm sorry, I already spent 2 weeks around this bug (before I posted here I had a long session with mlflow too)

Ah okay, feel free to close the issue we have no way to reproduce this issue on our end unfortunately.

**Closed as completed** 2020-08-04 05:48 UTC
Labels: community, triage
