### ISSUE TITLE
Running with --address in distributed mode prints an error

### ISSUE THREAD

**Issue by beniwtv** [minio/minio#4205] opened 2017-04-29 18:13 UTC
I tested a small distributed server setup (3 servers, 6 disks), with the following command:

/usr/local/bin/minio server http://192.168.0.1/mnt/pool/d1 http://192.168.0.1/mnt/pool/d2 http://192.168.2.1/mnt/pool/d1 http://192.168.2.1/mnt/pool/d2 http://192.168.4.1/mnt/pool/d1 http://192.168.4.1/mnt/pool/d2

Which works absolutely fine.

However, I'd like to restrict the nodes to only listen on the internal VPN interface, as right now they listen on all interfaces.

So I executed:

/usr/local/bin/minio server **--address 192.168.0.1:9000** http://192.168.0.1/mnt/pool/d1 http://192.168.0.1/mnt/pool/d2 http://192.168.2.1/mnt/pool/d1 http://192.168.2.1/mnt/pool/d2 http://192.168.4.1/mnt/pool/d1 http://192.168.4.1/mnt/pool/d2

Which gives my a validation error:

```
FATA[0000] Unable to parse storage endpoints http://192.168.0.1/mnt/pool/d1 http://192.168.0.1/mnt/pool/d2 http://192.168.2.1/mnt/pool/d1 http://192.168.2.1/mnt/pool/d2 http://192.168.4.1/mnt/pool/d1 http://192.168.4.1/mnt/pool/d2  cause=Invalid Argument 192.168.0.1, port mandatory when --address <host>:<port> is used source=[server-main.go:352:checkServerSyntax()]
```

So then I tried:

/usr/local/bin/minio server --address 192.168.0.1:9000 http://192.168.0.1:9000/mnt/pool/d1 http://192.168.0.1:9000/mnt/pool/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2

But that gives another validation error:

```
FATA[0000] 192.168.0.1:9000 matches %!e(int= 2)ntries in http://192.168.0.1:9000/mnt/pool/d1 http://192.168.0.1:9000/mnt/pool/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2  cause=Invalid arguments specified source=[server-main.go:397:checkServerSyntax()]
```

So now I am confused on how to start this, as it won't take any arguments I try.

## Expected Behavior
Minio should start up as normal.

## Current Behavior
Minio gives a validation error.

## Steps to Reproduce (for bugs)
See description above.

## Your Environment
* Version used (`minio version`):
Version: 2017-04-29T00:40:27Z
Release-Tag: RELEASE.2017-04-29T00-40-27Z
Commit-ID: eb50175ad911d496bf583a599de89547f0c9be89

* Server type and version:
Linux xxx.xxx.com 4.9.20-std-1 #1 SMP Tue Apr 4 12:56:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2017-04-29 18:32
@beniwtv this is how you can start a distributed setup bound to specific IP. NOTE that you need to specify different IPs to listen on for each servers to match the ones which are on the command line. 

```
#!/bin/bash

$(minio server --address localhost:9001 http://localhost:9001/tmp/1 http://localhost:9002/tmp/2 http://localhost:9003/tmp/3 http://localhost:9004/tmp/4)&
$(minio server --address localhost:9002 http://localhost:9001/tmp/1 http://localhost:9002/tmp/2 http://localhost:9003/tmp/3 http://localhost:9004/tmp/4)&
$(minio server --address localhost:9003 http://localhost:9001/tmp/1 http://localhost:9002/tmp/2 http://localhost:9003/tmp/3 http://localhost:9004/tmp/4)&
minio server --address localhost:9004 http://localhost:9001/tmp/1 http://localhost:9002/tmp/2 http://localhost:9003/tmp/3 http://localhost:9004/tmp/4
```

And a sample docker compose file.

```yml
version: '2'
services:
  minio1:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9001:9000"
    volumes:
      - /tmp/1:/export
    command: server --address minio1:9000 http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export
      
  minio2:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9002:9000"
    volumes:
      - /tmp/2:/export      
    command: server --address minio2:9000 http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export
    
  minio3:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9003:9000"
    volumes:
      - /tmp/3:/export      
    command: server --address minio3:9000 http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export

  minio4:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9004:9000"
    volumes:
      - /tmp/4:/export      
    command: server --address minio4:9000 http://minio1:9000/export http://minio2:9000/export http://minio3:9000/export http://minio4:9000/export    
```

**Comment by beniwtv** [comment] 2017-04-29 18:44
@harshavardhana 

So as I understand it, I basically would need two instances on two different ports per server? One for each disk?

If so, why did the first command work?

/usr/local/bin/minio server http://192.168.0.1/mnt/pool/d1 http://192.168.0.1/mnt/pool/d2 http://192.168.2.1/mnt/pool/d1 http://192.168.2.1/mnt/pool/d2 http://192.168.4.1/mnt/pool/d1 http://192.168.4.1/mnt/pool/d2

That one works, shows the right amount of disks:

```
Initializing data volume.
[01/06] http://192.168.0.1:9000/mnt/pool/d1 - 46 GiB online
[02/06] http://192.168.0.1:9000/mnt/pool/d2 - 46 GiB online
[03/06] http://192.168.2.1:9000/mnt/pool/d1 - 46 GiB online
[04/06] http://192.168.2.1:9000/mnt/pool/d2 - 46 GiB online
[05/06] http://192.168.4.1:9000/mnt/pool/d1 - 46 GiB online
[06/06] http://192.168.4.1:9000/mnt/pool/d2 - 46 GiB online

<snip>

Drive Capacity: 129 GiB Free, 137 GiB Total
Status:         6 Online, 0 Offline. We can withstand [3] more drive failure(s).
```

The only difference is the --address part, but I don't understand why specifying a bind address should change the behaviour described in the documentation.

https://docs.minio.io/docs/distributed-minio-quickstart-guide -> Example #2.

**Comment by harshavardhana** [comment] 2017-04-29 22:23
> So as I understand it, I basically would need two instances on two different ports per server? One for each disk?
> 
> If so, why did the first command work?

This is only when you want to serve multiple disks on different ports which is also possible but a given server can just listen on one port and serve multiple disks as well even with --address as shown below using the latest release. 

```yml
version: '2'
services:
  minio1:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9001:9000"
    volumes:
      - /tmp/1:/export1
      - /tmp/2:/export2
    command: server --address minio1:9000 http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2
      
  minio2:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9002:9000"
    volumes:
      - /tmp/3:/export1
      - /tmp/4:/export2
    command: server --address minio2:9000 http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2
```

Other variations also work like 

```yml
version: '2'
services:
  minio1:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9001:9000"
    volumes:
      - /tmp/1:/export1
      - /tmp/2:/export2
    command: server --address minio1:9000 http://minio1:9000/export1 http://minio1:9000/export2 http://minio2:9000/export1 http://minio2:9000/export2
      
  minio2:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=abcd123
      - MINIO_SECRET_KEY=abcd12345
    ports:
      - "9002:9000"
    volumes:
      - /tmp/3:/export1
      - /tmp/4:/export2
    command: server --address minio2:9000 http://minio1:9000/export1 http://minio1:9000/export2 http://minio2:9000/export1 http://minio2:9000/export2
```

**Comment by harshavardhana** [comment] 2017-04-29 22:24
Can you paste all the command line arguments that you are passing on all the servers in line by line? - Would love to reproduce this, i am not able to reproduce it.

**Comment by beniwtv** [comment] 2017-04-29 23:41
Sure.

Your first variation doesn't work for me, it complains with:

`cause=Invalid Argument 192.168.0.1, port mandatory when --address <host>:<port> is used 
`

So here are the 3 commands (your second variation):

**Server 1:**

$ /usr/local/bin/minio server --address 192.168.0.1:9000 http://192.168.0.1:9000/mnt/pool/d1 http://192.168.0.1:9000/mnt/pool/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2

```
FATA[0000] 192.168.0.1:9000 matches %!e(int= 2)ntries in http://192.168.0.1:9000/mnt/pool/d1 http://192.168.0.1:9000/mnt/pool/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2  cause=Invalid arguments specified source=[server-main.go:397:checkServerSyntax()]
```

**Server 2:**

$ /usr/local/bin/minio server --address 192.168.2.1:9000 http://192.168.0.1:9000/mnt/pool/d1 http://192.168.0.1:9000/mnt/pool/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2
```

FATA[0000] 192.168.2.1:9000 matches %!e(int= 2)ntries in http://192.168.0.1:9000/mnt/pool/d1 http://192.168.0.1:9000/mnt/pool/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2  cause=Invalid arguments specified source=[server-main.go:397:checkServerSyntax()]
```

**Server 3:**

$ /usr/local/bin/minio server --address 192.168.4.1:9000 http://192.168.0.1:9000/mnt/pool/d1 http://192.168.0.1:9000/mnt/pool/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2

```
FATA[0000] 192.168.4.1:9000 matches %!e(int= 2)ntries in http://192.168.0.1:9000/mnt/pool/d1 http://192.168.0.1:9000/mnt/pool/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2  cause=Invalid arguments specified source=[server-main.go:397:checkServerSyntax()]
```

**Comment by balamurugana** [comment] 2017-04-30 00:47
@beniwtv I am unable to reproduce the error for below command ie the command line is working fine.
```bash
$ minio server --address 192.168.122.1:9000 http://192.168.122.1:9000/home/bala/tmp/d1 http://192.168.122.1:9000/home/bala/tmp/d2 http://192.168.2.1:9000/mnt/pool/d1 http://192.168.2.1:9000/mnt/pool/d2 http://192.168.4.1:9000/mnt/pool/d1 http://192.168.4.1:9000/mnt/pool/d2
Initializing data volume. Waiting for minimum 4 servers to come online. (elapsed 23s)
Initializing data volume. Waiting for minimum 4 servers to come online. (elapsed 55s)
```

In fact I am not able to see the error message `FATA[0000] 192.168.0.1:9000 matches %!e(int= 2)ntries in ` in latest master HEAD.

I am trying with the version you mentioned.

**Comment by balamurugana** [comment] 2017-04-30 01:35
@beniwtv the issue is there in the release.  Is it possible you to try master HEAD?

**Comment by beniwtv** [comment] 2017-04-30 01:55
@balamurugana That worked. Thank you!

**Comment by balamurugana** [comment] 2017-04-30 02:30
@beniwtv you could close this issue as fixed upstream

**Comment by harshavardhana** [comment] 2017-04-30 04:44
Fixed by https://github.com/minio/minio/pull/4019

**Closed as completed by harshavardhana** 2017-04-30 04:44 UTC
Labels: community, fixed, priority: high
