### ISSUE TITLE
Minio behind reverse proxy breaks presigned URLs

### ISSUE THREAD

**Issue by andrewtmendoza** [minio/minio#7857] opened 2019-07-01 10:10 UTC
If you are following the cookbook, example 1 ([Proxy all requests](https://docs.min.io/docs/setup-nginx-proxy-with-minio.html)) will break the presigned URL functionality. You will still be able to generate a presigned URL from the UI, but you will get an error when you try to use it:

![image](https://user-images.githubusercontent.com/4677802/60428188-2b52b980-9bad-11e9-8f89-0e20e18c4799.png)

Can you please confirm whether this is the expected behavior, and it not, would it be possible to fix the documentation?

**Comment by nitisht** [comment] 2019-07-01 11:04
> Can you please confirm whether this is the expected behavior, and it not, would it be possible to fix the documentation?

This is expected behaviour @andrewtmendoza since it is not possible to change the hostname in a presigned URL. We'll fix the docs

**Comment by eco-minio** [comment] 2019-07-01 19:06
@nitisht  what is the issue here?  How did you determine the hostname changed?

**Comment by andrewtmendoza** [comment] 2019-07-01 22:00
@eco-minio if you follow the nginx cookbook and try to generate a presigned URL (even via the Minio UI) it will result in the signature does not match error I previously shared.

![image](https://user-images.githubusercontent.com/4677802/60469243-e1032400-9c10-11e9-9290-076945bd2c68.png)

![image](https://user-images.githubusercontent.com/4677802/60469208-c761dc80-9c10-11e9-84d8-911aec205c0b.png)

**Comment by harshavardhana** [comment] 2019-07-02 09:42
UI is not generating the Presigned URLs correctly, the args.Hostname populated is wrong when behind the proxy @kanagarajkm most probably because `location.host` carries port 80 as part of the signature calculation which should be removed for standard ports such as 80 and 443.

**Comment by kanagarajkm** [comment] 2019-07-02 11:13
@harshavardhana `location.host` will not have `80` for default ports(80).

@andrewtmendoza can you give the nginx conf file? i could not reproduce this in my setup.

**Comment by andrewtmendoza** [comment] 2019-07-02 22:15
@kanagarajkm here is what I put in `/etc/nginx/conf.d/default.conf`

```
server {
    listen 80;
    # listen 443 ssl;

    # server_name ~.;

    # ssl_certificate /sslcerts/localhost.pem;
    # ssl_certificate_key /sslcerts/localhost-key.pem;

    # To allow special characters in headers
     ignore_invalid_headers off;
     # Allow any size file to be uploaded.  
     # Set to a value such as 1000m; to restrict file size to a specific value
     client_max_body_size 0;
     # To disable buffering
     proxy_buffering off;

    ## If the static server was another docker service,
    ## It is possible to forward requests to its port:
    location / {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://minio:9000/;
    }

}
```

**Comment by kanagarajkm** [comment] 2019-07-03 05:56
@andrewtmendoza you are missing `proxy_set_header Host $http_host;` in the `location /` section. Can you add it and try?

**Comment by harshavardhana** [comment] 2019-07-05 20:16
> @andrewtmendoza you are missing `proxy_set_header Host $http_host;` in the `location /` section. Can you add it and try?

This is needed and we have documented this in our reverse proxy docs. Closing this as working as intended for now.

**Closed as completed by harshavardhana** 2019-07-05 20:16 UTC
Labels: working as intended, community, triage

**Comment by ngrigoriev** [comment] 2020-03-17 17:26
I think the proxy docs may need to explain a bit more about how the signature is calculated. Basically, the important part is that the value of the "Host" request field is used to calculate the hash. And given that Minion is often used with is default port 9000, the host value becomes "host:9000". And often the ingress proxies (Ambassador, NGINX...) put just the target host name there without the port number, even when forwarding the request to "host:9000". 

For Kubernetes, I would have the following recommendations:

- if using the endpoint like "minio-service:9000", then the "host" value used for signing the request will be exactly "minio-service:9000". This is about the requests to generate the pre-signed URL usually made from inside of the cluster.
- when configuring your ingress proxy, make sure that the "host" field on the request is rewritten to exactly that value
- should you have any other signature validation issues, test them from inside of the cluster and then from the outside, capture both requests in minio pod with tcpdump and compare. You will see what does not match.
