### ISSUE TITLE
Intermittent behaviour under strace

### ISSUE THREAD

**Issue by candlerb** [minio/minio#8751] opened 2020-01-05 21:56 UTC
(Aside: I was trying to find out why minio could take a minute or more to start in erasure coding mode.  But I ended up with something weirder)

## Expected Behavior
minio to start successfully under strace, every time.

## Current Behavior
It's intermittent. Sometimes it works:

```
root@minio1:~# rm -rf /ec/*/* /ec/*/.minio.sys
root@minio1:~# strace -t -E MINIO_SECRET_KEY=minioadmin -E MINIO_ACCESS_KEY=minioadmin -f ./minio server /ec/1 /ec/2 /ec/3 /ec/4 /ec/5 /ec/6 /ec/7 /ec/8 2>/tmp/ert
Attempting encryption of all config, IAM users and policies on MinIO backend
Status:         8 Online, 0 Offline.
Endpoint:  http://10.12.255.61:9000  http://127.0.0.1:9000
AccessKey: minioadmin
SecretKey: minioadmin

Browser Access:
   http://10.12.255.61:9000  http://127.0.0.1:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.12.255.61:9000 minioadmin minioadmin

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
^CExiting on signal: INTERRUPT
```

And sometimes it doesn't:

```
root@minio1:~# rm -rf /ec/*/* /ec/*/.minio.sys
root@minio1:~# strace -t -E MINIO_SECRET_KEY=minioadmin -E MINIO_ACCESS_KEY=minioadmin -f ./minio server /ec/1 /ec/2 /ec/3 /ec/4 /ec/5 /ec/6 /ec/7 /ec/8 2>/tmp/ert
Attempting encryption of all config, IAM users and policies on MinIO backend
ERROR Unable to initialize server switching into safe-mode: Unable to initialize config system: Unable to load config file. Invalid credentials
root@minio1:~#
```

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
See above

## Context
I am testing on a very low power server (Intel NUC DN2820FYK, Celeron N2820 dual core) and inside an lxd container.  This means that possible race conditions might be brought to the fore.

It also *could* be a bad interaction with lxd or cgroups.

The directory `/ec` inside the container, is actually an ext4 filesystem bind-mounted into the container from outside.

Seen from inside container:

```
root@minio1:~# df /ec
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda2       14287344 10076344   3462200  75% /ec
```

Seen from the host:

```
root@nuc1:~# mount | grep minio1-ec
/dev/sda2 on /var/lib/lxd/devices/minio1/disk.minio1-ec.ec type ext4 (rw,relatime,errors=remount-ro,data=ordered)

root@nuc1:~# lxc config show minio1
...
devices:
  minio1-ec:
    path: /ec
    pool: plain
    source: minio1-ec
    type: disk
```

## Regression
N/A

## Your Environment
* Version used (`minio --version`): `minio version RELEASE.2020-01-03T19-12-21Z
`
* Server type and version: Intel DN2820FYK, host Ubuntu 18.04; lxd container Ubuntu 18.04
* Operating System and version (`uname -a`): `Linux minio1 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by harshavardhana** [comment] 2020-01-06 04:02
@candlerb have tried many times already cannot reproduce this

```
~ strace -t -E MINIO_SECRET_KEY=minioadmin -E MINIO_ACCESS_KEY=minioadmin -f ./minio server /tmp/1 /tmp/2 /tmp/3 /tmp/4 /tmp/5 /tmp/6 /tmp/7 /tmp/8 2>/tmp/ert
Attempting encryption of all config, IAM users and policies on MinIO backend
Configuration file config/config.json migrated from version '28' to '29' successfully.
Configuration file config/config.json migrated from version '29' to '30' successfully.
Configuration file config/config.json migrated from version '30' to '31' successfully.
Configuration file config/config.json migrated from version '31' to '32' successfully.
Configuration file config/config.json migrated from version '32' to '33' successfully.
Configuration file config/config.json migrated from version '33' to new KV format successfully.
Status:         8 Online, 0 Offline. 
```

**Comment by harshavardhana** [comment] 2020-01-06 04:04
> ERROR Unable to initialize server switching into safe-mode: Unable to initialize config system: Unable to load config file. Invalid credentials

This means that ENV is not visible for some reason @candlerb because backend config is encrypted with ENV creds.

**Comment by harshavardhana** [comment] 2020-01-07 07:45
I can't seem to reproduce this, as far as I can see it's env related issue.

Going to close this for now unless we find a proper reproducer.

**Closed as completed by harshavardhana** 2020-01-07 07:45 UTC
Labels: working as intended, community, incomplete info
