### ISSUE TITLE
The upload speed is much slower than download speed

### ISSUE THREAD

**Issue by sokui** [minio/minio#12011] opened 2021-04-07 21:32 UTC
## Expected Behavior

The upload speed should be faster, or the parallel degree should be configurable for upload/download
## Current Behavior

I am testing the performance for uploading and downloading a big file (50+ GB). The download speed is around 280 MBps, but the upload speed is only 30-50 MBps.

My testing is done within Kube. The MinIO is in server mode, with 16 nodes, 2 PVCs for each, so totally 32 PVCs. My client is using minIO JDK, which is also within the same Kube cluster. When uploading, it seems it only has two internet connections (netstat -pan), and there are totally 14 processes from the client (check by htop). The Kube node has 25 GbE NIC, and the volume is using nvme ssds.
## Possible Solution

I saw some issue reported in minio/mc, saying that the client will auto open new connections to adapt to the bandwidth. But it seems not so at least for JDK client. 

Is it possible to config the thread? For example, we can choose between Auto, or Manual (with thread number fixed)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): RELEASE.2021-03-04T00-53-13Z
* Server setup and configuration: server mode, 16 nodes, 32 PVCs
* Operating System and version (`uname -a`): Linux test-minio-statefulset-0 5.4.77-7.el7pie #1 SMP Sat Nov 21 01:16:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* JDK version: io.minio:minio:8.1.0

**Comment by harshavardhana** [comment] 2021-04-07 21:41
@sokui there is nothing you are sharing here about your environment or testing that you did with the code that reproduced this.  

Our published benchmarks tell you that this not going to be an issue to meet performance requirements for MinIO. So it is always environment-specific and incorrect deployment leads to suboptimal deployment. 

Closing this issue please share more information.

**Closed as completed by harshavardhana** 2021-04-07 21:41 UTC
Labels: community, triage

**Comment by sokui** [comment] 2021-04-07 21:49
Hi @harshavardhana ,

Here is the Java code I used to upload the file. For the environment setting, I posted all the infos about the deployment setup and the software versions. What kind of other information you need? Please let me know. Thanks


```
            final String endpoint = args[1];
            MinioClient minioClient =
                    MinioClient.builder()
                            .endpoint(endpoint)
                            .credentials(ACCESS_KEY, SECRET_KEY)
                            .build();

            final String bucket = args[2];
            final String src = args[3];
            final String dst = args[4];
            minioClient.downloadObject(DownloadObjectArgs.builder()
                        .bucket(bucket)
                        .object(src)
                        .filename(dst)
                        .build());
```

**Comment by harshavardhana** [comment] 2021-04-07 21:53
> Here is the Java code I used to upload the file. For the environment setting, I posted all the infos about the deployment setup and the software versions. What kind of other information you need? Please let me know. Thanks
> 
> ```
>             final String endpoint = args[1];
>             MinioClient minioClient =
>                     MinioClient.builder()
>                             .endpoint(endpoint)
>                             .credentials(ACCESS_KEY, SECRET_KEY)
>                             .build();
> 
>             final String bucket = args[2];
>             final String src = args[3];
>             final String dst = args[4];
>             minioClient.downloadObject(DownloadObjectArgs.builder()
>                         .bucket(bucket)
>                         .object(src)
>                         .filename(dst)
>                         .build());
> ```

This is not a realistic benchmarking you should do a distributed upload test using https://github.com/minio/warp to see the real throughput possible. 

Of course uploads will be slower than downloads since uploads use server bandwidth than downloads the way erasure coding works, you need to optimize your parity ratio to get upload and download to have similar throughput profiles. 

Everything depends on how your architecture and design the environment.  For this you need to get a subscription https://min.io/pricing

**Comment by sokui** [comment] 2021-04-07 23:41
Thanks for replying. Yeah, my purpose was not to benchmarks the throughput of the server, instead, I want to tune a single client to see what the maximum upload speed it can get. Currently it seems the number of internet connection is not adaptable or configurable. Not sure how to increase the performance by only tuning the client side.

For server side, thanks for pointing out the parity ratio. Will adjust that and do further testing.
