### ISSUE TITLE
Ability to create, upload, share and delete folder in ui

### ISSUE THREAD

**Issue by gurvindersingh** [minio/minio#5956] opened 2018-05-18 11:41 UTC
Currently in the minio UI it is not possible to create a folder or upload folder from client side using UI. Neither if you already have folder in the underlying storage ability to share or delete it. UI allows sharing only a file via link.
## Expected Behavior

It should provide an option in addition to "Upload file, Create bucket" as "Create folder" and a user should be able to upload folder using drag and drop to create a folder in the current bucket. Also folder should have a the same shared link and delete option similar to files.
## Current Behavior

It is not possible to perform above mentioned tasks from UI. I can upload file using drag and drop but folder is not possible to upload using drag and drop.

## Context

I am trying to use minio to share my data with colleagues and having ability to share subfolders will be really useful. Currently I have to create the tar file of folder to share the content.
## Your Environment

* Version used (`minio version`): minio/minio:RELEASE.2018-05-16T23-35-33Z
* Environment name and version (e.g. nginx 1.9.1): Docker
* Operating System and version (`uname -a`):  Linux test 4.4.0-119-generic #143-Ubuntu SMP

**Comment by harshavardhana** [comment] 2018-05-18 17:27
Duplicate of #5915 and #3933

**Comment by deekoder** [comment] 2018-05-18 18:26
@gurvindersingh  some of these, we plan to do as part of a new ux release which will happen later. But I wanted to clarify something about object storage that I myself had to learn as I worked with object storage - the concept of folders that we know of as consumers do not really exist in object storage. The UX doesn't help us understand this since we are used to explorer, dropbox, etc. Some UX tools for object storage do have the concept of naming a file/objects using dir/filename just to help users out.  In S3 compatible object storage such as ours, have prefixes which are like keys and they have corresponding values (the object content itself). We allow '/ ' in prefixes so you can directly use the URL bar to create it if you prefer. See #3933 and #5915 for how to. @gurvindersingh we will have a discussion about how much we should support these in the UX for the user's convenience and consider it for upcoming releases.

**Comment by gurvindersingh** [comment] 2018-05-18 18:44
@deekoder thanks for the detailed info. I am aware of the directory being mimicked as file with suffix "/". Given minio supports the folders being present in the filesystem when started. As a user I would expect the same user experience after interacting with minio and thus asked for this in the issue. #5915 was mainly for the file which does work for mac and as noted there you have to drop in upper part of the page. But dropping directory currently does not work even in the upper region of the page.

Do you have any guesstimate as when the next UX upgrade will happen. I saw quite some issues are tagged with [New UX Milestone](https://github.com/minio/minio/milestone/18) and due date marked as 31st May, so wondering how realistic is that.

**Comment by deekoder** [comment] 2018-05-22 18:53
@gurvindersingh  you are right we are not on track for May 31. After we wrap up our current commitments we do plan to address the new UX release. I don't have an exact date for you at this time. I will update the date as soon as I have clarity on it.

**Comment by deekoder** [comment] 2018-05-31 23:56
Closing now as won't fix and moving it to new ux milestone for activation after we clear our current backlog.

**Closed as completed by deekoder** 2018-05-31 23:56 UTC
Labels: out of scope, priority: medium, triage

**Comment by fkromer** [comment] 2020-04-21 09:18
@deekoder When was/will the new UX milestone be released? BTW: I'm running a potentially outdated Docker Image for ARM server.

**Comment by fkromer** [comment] 2020-04-21 12:18
On Windows and MAC the client https://cyberduck.io/ is a free choice.

**Comment by blairdrummond** [comment] 2020-05-20 19:04
Still, it would be nice if this worked without need for an external client :-/ It complicates things for us too. I'd be very happy to see this reopened.

**Comment by darkdragon-001** [comment] 2020-05-21 07:58
- Drag&Drop folder uploads are added in #9627 for supporting browsers
- "+" menu to upload folders with file chooser is postponed until a HTML5 `<input>` element (property) exists which allows both file and folder upload at the same time.
- "..." menu is added for folders in #9631 to allow downloading as zip and deletion directly. Feel free to send a PR for more options.

The UI code is not too complex, it took me about a day get comfortable within the code in order to be able to fix such small things where the functionality already exists but is just not intuitively exposed in the UI. Check the README in https://github.com/minio/minio/tree/master/browser for instructions.

**Comment by harshavardhana** [comment] 2020-05-21 16:22
> * Drag&Drop folder uploads are added in #9627 for supporting browsers
> * "+" menu to upload folders with file chooser is postponed until a HTML5 `<input>` element (property) exists which allows both file and folder upload at the same time.
> * "..." menu is added for folders in #9631 to allow downloading a folder as zip directly. Feel free to send a PR for more options.
> 
> The UI code is not too complex, it took me about a day get comfortable within the code in order to be able to fix such small things where the functionality already exists but is just not intuitively exposed in the UI. Check the README in https://github.com/minio/minio/tree/master/browser for instructions.

Thanks @darkdragon-001 we really appreciate the work here.

**Comment by fkromer** [comment] 2020-08-28 16:51
What provides minio w.r.t. UI control and visualization capabilities in contrast to [minio console](https://github.com/minio/console)?

**Comment by harshavardhana** [comment] 2020-08-28 17:00
> What provides minio w.r.t. UI control and visualization capabilities in contrast to [minio console](https://github.com/minio/console)?

MinIO WebUI is kind of in feature freeze all work is going to `minio console` at this moment @fkromer

**Comment by fkromer** [comment] 2020-08-29 10:46
@harshavardhana Thanks a lot for the notification!
