### ISSUE TITLE
GetObjectAsync Timeout issue

### ISSUE THREAD

**Issue by Rajeshrg55** [minio/minio#10456] opened 2020-09-10 04:23 UTC
## Expected Behavior
I'm using the below code to download the object from minio.

               MemoryStream memStream = new MemoryStream();
                string[] filename = URL.Split('/');
                var _containerName = filename[filename.Length - 2];
                System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls |
               System.Net.SecurityProtocolType.Tls11 | System.Net.SecurityProtocolType.Tls12;
                var minioClient = new MinioClient(minioEndpoint, minioAccessKey, minioSecretKey).WithSSL();

                minioClient.StatObjectAsync(_containerName, filename[4]);
                await minioClient.GetObjectAsync(_containerName, filename[4], s => s.CopyTo(memStream));
                return memStream;

Which is working fine in my BO project but not in DAL project.

## Current Behavior
The issue is : GetObjectAsync request getting timeout while downloading the object

## Possible Solution
GetObjectAsync  should get not timeout.

## Context
The issue is : GetObjectAsync request getting timeout while downloading the object

## Regression
 No

## Your Environment
The SDKs I'm using in the both projects are :
Minio Version 3.1.10
RestSharp Version 106.3.1

Operating System: Windows 10 Pro

**Comment by poornas** [comment] 2020-09-10 05:36
this is a duplicate of https://github.com/minio/minio-dotnet/issues/456, closing this one

**Closed as completed by poornas** 2020-09-10 05:36 UTC
Labels: community, triage
