### ISSUE TITLE
Any plan to build real-time dashboard for resource files monitoring ?

### ISSUE THREAD

**Issue by nvcken** [minio/minio#7827] opened 2019-06-25 04:57 UTC
We want to monitor resource files usage, is it built-in or could you please tell any thid-party can be integrated to Minio for this purpose

Thanks

**Comment by harshavardhana** [comment] 2019-06-25 04:59
How about this “Monitor Minio server with Prometheus” by Nitish Tiwari https://link.medium.com/tAZrXQGBNX - also please we request that use the issue template in future it really helps triage the issues @nvcken 

For general questions please feel free to join our https://slack.min.io

**Comment by nitisht** [comment] 2019-06-27 07:26
closing as working as intended

**Closed as completed by nitisht** 2019-06-27 07:26 UTC
Labels: working as intended, community
