### ISSUE TITLE
faq: Running Minio Erasure Code Mode in a Docker Swarm Mode (1.13) 

### ISSUE THREAD

**Issue by pascalandy** [minio/minio#3713] opened 2017-02-07 21:36 UTC
Hey folks,

I’m running a 4 nodes cluster in Docker Swarm Mode 1.13.
I want to setup a ECM (Erasure Code Mode). Following [this doc](https://docs.minio.io/docs/minio-erasure-code-quickstart-guide) and this [docker-compose.yml ](https://raw.githubusercontent.com/minio/minio/master/docs/docker/docker-compose.yml), I’m still not sure to understand this syntax: 

- `command: server http://minio1/myexport http://minio2/myexport …n`
- `minio server /mnt/export1/backend /mnt/export2/backend …n`

Would you help me define the best way to deploy a Minio ECM cluster in a Docker Swarm Cluster?

**Comment by pascalandy** [comment] 2017-02-07 22:18
After looking at this docker-compose V3 file, here is my routine.

I understand that a docker stack is a great way to start this project for most folk but I prefer to launch containers via `docker service create`.

### Take 2

```
# Node 1
CTN_NAME=minio1
SVR_NAME=node1
SOURCE="/mnt/minio/dev-d"
\
docker service create \
--name "$CTN_NAME" \
--network "minio-net" \
--replicas "1" \
-p 9000:9000 \
--constraint node.labels.nodename="$SVR_NAME" \
-e "MINIO_ACCESS_KEY=A18d29a3acc40256b1e6069c2" \
-e "MINIO_SECRET_KEY=Sdf128a527d40490fd6811df3f0a72136b9e92014db080" \
--mount	type=bind,src="$SOURCE",target=/export \
--mount	type=bind,src="$SOURCE/minio_config",target="/root/.minio" \
minio/minio:latest \
server \
http://minio1/export \
http://minio2/export \
http://minio3/export \
http://minio4/export


# Node 2
CTN_NAME=minio2
SVR_NAME=node2
SOURCE="/mnt/minio/dev-d"
\
docker service create \
--name "$CTN_NAME" \
--network "minio-net" \
--replicas "1" \
-p 9000:9000 \
--constraint node.labels.nodename="$SVR_NAME" \
-e "MINIO_ACCESS_KEY=A18d29a3acc40256b1e6069c2" \
-e "MINIO_SECRET_KEY=Sdf128a527d40490fd6811df3f0a72136b9e92014db080" \
--mount	type=bind,src="$SOURCE",target=/export \
--mount	type=bind,src="$SOURCE/minio_config",target="/root/.minio" \
minio/minio:latest \
server \
http://minio1/export \
http://minio2/export \
http://minio3/export \
http://minio4/export


# Node 3
CTN_NAME=minio3
SVR_NAME=node3
SOURCE="/mnt/minio/dev-d"
\
docker service create \
--name "$CTN_NAME" \
--network "minio-net" \
--replicas "1" \
-p 9000:9000 \
--constraint node.labels.nodename="$SVR_NAME" \
-e "MINIO_ACCESS_KEY=A18d29a3acc40256b1e6069c2" \
-e "MINIO_SECRET_KEY=Sdf128a527d40490fd6811df3f0a72136b9e92014db080" \
--mount	type=bind,src="$SOURCE",target=/export \
--mount	type=bind,src="$SOURCE/minio_config",target="/root/.minio" \
minio/minio:latest \
server \
http://minio1/export \
http://minio2/export \
http://minio3/export \
http://minio4/export



# Node 4
CTN_NAME=minio4
SVR_NAME=node4
SOURCE="/mnt/minio/dev-d"
\
docker service create \
--name "$CTN_NAME" \
--network "minio-net" \
--replicas "1" \
-p 9000:9000 \
--constraint node.labels.nodename="$SVR_NAME" \
-e "MINIO_ACCESS_KEY=A18d29a3acc40256b1e6069c2" \
-e "MINIO_SECRET_KEY=Sdf128a527d40490fd6811df3f0a72136b9e92014db080" \
--mount	type=bind,src="$SOURCE",target=/export \
--mount	type=bind,src="$SOURCE/minio_config",target="/root/.minio" \
minio/minio:latest \
server \
http://minio1/export \
http://minio2/export \
http://minio3/export \
http://minio4/export

```

**Comment by pascalandy** [comment] 2017-02-07 23:35
From the docker-compose v3, I realize that this argument is not present:
`--mount type=bind,src=/mnt/minio/dev-d/minio_config",dst="/root/.minio" \`

At this point it looks we don't need to specify need anymore.

**Comment by pascalandy** [comment] 2017-02-13 22:00
I just tested this [docker-compose.yaml](https://github.com/NitishT/minio/blob/master/docs/orchestration/docker-swarm/docker-compose.yaml) and as expected, all 4 instances are all on my node #2. 

This setup does not allow me to ensure there is only one instance per node.

**Comment by pascalandy** [comment] 2017-02-14 00:56
my updated journey below ...

**Comment by harshavardhana** [comment] 2017-02-14 01:11
> Let's see if Minio ECM (Erasure Code Mode) can help.

Let's not use abbreviations here it is just simply "erasure code" - now simple question @pascalandy are you creating files directly on the backend? 

If yes then it is not supported on erasure coded mode, we need certain types of metadata on the backend to be able to make sense of the object uploaded which is only created when the object is uploaded through our S3 API. 

> I want to share/sync a common folder between 4 nodes.

If you want to share and sync a common folder between 4 nodes just run Minio server on the shared folder and it will be accessible over 4 nodes. 

Or you can mount the same shared folder across all 4 nodes and then run 4 independent minio servers on the mounted share. 

Minio servers can work independently on the same shared backend as well for concurrent access - Minio uses filesystem locks.  - https://github.com/minio/minio/tree/master/docs/shared-backend

**Comment by pascalandy** [comment] 2017-02-14 14:27
@harshavardhana since our chat on Slack, everything is working as expected. I'm bouncing all over the place at the moment!!

**Comment by pascalandy** [comment] 2017-02-14 14:32
@harshavardhana since our chat on Slack, everything is working as expected. I'm bouncing all over the place at the moment! I decided to make a post out of my finding.

Check this out! [The complete guide to attach a Docker volume with Minio on your Docker Swarm Cluster](https://pascalandy.com/blog/the-complete-guide-to-attach-a-docker-volume-with-minio-on-your-docker-swarm-cluster/)

**Comment by harshavardhana** [comment] 2017-03-06 00:16
Closing as duplicate of #3489

**Closed as completed by harshavardhana** 2017-03-06 00:16 UTC
Labels: community, question
