### ISSUE TITLE
changing server config 

### ISSUE THREAD

**Issue by abipaul** [minio/minio#4109] opened 2017-04-13 07:39 UTC
./minio server --address x.x.x.x:7071 /home /home1 /home2 /home3

The server works fine..

But when i change the config to 6 discs i get this error

./minio server --address x.x.x.x:7071 /home /home1 /home2 /home3 /home4 /home5

FATA[0000] Initializing object layer failed   cause=Number of disks 6 did not match the backend format 4 source=[server-main.go:587:serverMain()]

If i am experimenting with different disk configs..I  run into problems..

**Comment by harshavardhana** [comment] 2017-04-13 07:42
You can't run 6 disk setup on a previously configured 4 disk one - you should setup a new minio cluster and migrate the data over -

This is expected and working as intended @abipaul

**Comment by abipaul** [comment] 2017-04-13 07:47
how do get rid of previous config then?

./minio server --address x.x.x.x:7071 /home /home1 /home2 /home3 

let's say i don't want this now and i want to switch to new configuration

**Comment by harshavardhana** [comment] 2017-04-13 07:49
> ./minio server --address x.x.x.x:7071 /home /home1 /home2 /home3

Just delete `rm -rf /home*/.minio.sys`  @abipaul

**Comment by deekoder** [comment] 2017-04-13 18:05
@abipaul - let us know if this resolved your issue.

**Comment by abipaul** [comment] 2017-04-13 18:43
yes. this fixed the issue. thanks!

**Comment by harshavardhana** [comment] 2017-04-13 19:07
Closing this as answered.

**Closed as completed by harshavardhana** 2017-04-13 19:07 UTC
Labels: working as intended, priority: low, community
