### ISSUE TITLE
GCS Gateway - GetObject return incorrect metadata from disk cache

### ISSUE THREAD

**Issue by retinio** [minio/minio#8934] opened 2020-02-04 14:57 UTC
With minio running as GCS gateway in docker (disk caching is enabled). After updated metadata  "get_object" method returned old data if the object is already in disk cache.

I'm using AWS SDK for .NET with MinIO Server.
```
const string bucketName = "test-container-1";
const string objectName = "586191.webp";

var request = new CopyObjectRequest
                {
                    SourceBucket = bucketName,
                    SourceKey = objectName,
                    DestinationBucket = bucketName,
                    DestinationKey = objectName,
                    MetadataDirective = S3MetadataDirective.REPLACE,
                };
request.Metadata.Add("watermark", "true");
var result = await s3Client.CopyObjectAsync(request );

var requestMeta = new GetObjectMetadataRequest { BucketName = bucketName, Key = objectName,  };
//The response contains incorrect metadata (old data from disk cache)
var responseMetaBefore = await s3Client.GetObjectMetadataAsync(requestMeta);

 var requestGetObject = new GetObjectRequest {BucketName = bucketName, Key = objectName};
//The response contains incorrect metadata (old data from disk cache)
var responseGetObject = await s3Client.GetObjectAsync(requestGetObject);

//The response contains correct metadata (new data from disk cache)
var responseMetaAfter = await s3Client.GetObjectMetadataAsync(requestMeta);
```
I think this is because  **cacheReader** contains not updated data.

https://github.com/minio/minio/blob/881e983ed97ae2101835f307f09fda93eb3428ad/cmd/disk-cache.go#L262-L268

## Current Behavior

Metadata in GCS is updated successfully. Metadata in disk cache is updated after running method get_object but returned old data.

## Steps to Reproduce (for bugs)

With minio running as gcs gateway with disk caching enabled, using the copy_object method with "x-amz-metadata-directive: REPLACE" to update metadata. Using the get_object method for get old metadata.

## Your Environment

* Version used (`minio version`): RELEASE.2020-01-25T02-50-51Z
* Server type and version: Docker version 19.03.5

**Comment by harshavardhana** [comment] 2020-02-05 17:04
Closing as duplicate of #8942

**Closed as completed by harshavardhana** 2020-02-05 17:04 UTC
Labels: community, triage
