### ISSUE TITLE
Storage backend has reached its minimum free disk threshold

### ISSUE THREAD

**Issue by bupy7** [minio/minio#6795] opened 2018-11-10 00:12 UTC
## Expected Behavior

I want to put object up to end of my free space.

## Current Behavior

I try to put object with size about 10 Mib at the first time. But I cannot put the same object again. Minio throw an exception:

```
Error executing "PutObject" on "http://core.example.local:4567/prv0.example.local/mobile-app/packages/app_1.0.2.apk";
AWS HTTP error: Server error:
`PUT http://core.example.local:4567/prv0.example.local/mobile-app/packages/app_1.0.2.apk` resulted in a `507 Insufficient Storage` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioStorageFull</Code><Message>Storage backend has reached its min (truncated...)
 XMinioStorageFull (server): Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioStorageFull</Code><Message>Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed.</Message><Key></Key><BucketName></BucketName><Resource>/prv0.example.local/mobile-app/packages/app_1.0.2.apk</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error> (File: /vagrant/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php, Line: 191):
```

It's only one file in only one bucket. I have only one bucket at all. Total size of all files is 10 Mib.

## Possible Solution
 
I don't know. How to change threshold size of Minio?

I have enough free space:

```
vagrant@example:/var/www/html$ df
Filesystem                            1K-blocks    Used Available Use% Mounted on
/dev/sda1                               9620408 8127212    981452  90% /
udev                                      10240       0     10240   0% /dev
tmpfs                                    204876    4452    200424   3% /run
tmpfs                                    512184       0    512184   0% /dev/shm
tmpfs                                      5120       0      5120   0% /run/lock
tmpfs                                    512184       0    512184   0% /sys/fs/cgroup
192.168.20.1:/Volumes/Project/example  28945984 7908088  21037896  28% /vagrant
```

![image](https://user-images.githubusercontent.com/5145037/48294676-9416e580-e4a7-11e8-9b95-47cb4b7a2353.png)

## Steps to Reproduce (for bugs)

```
/** @var \Aws\S3\S3Client $s3 **/
$s3->putObject([
    'Key' => 'destination/file.apk',
    'Bucket' => 'prv0.example.local',
    'SourceFile' => '/path/to/file.apk',
    'ContentType' => 'application/vnd.android.package-archive'
]);
```

## Context

Everything is general, nothing special.

## Regression

I don't know, may be it was before.

## Your Environment
* Version used (`minio version`): 
```
Version: 2018-07-13T00:09:07Z
Release-Tag: RELEASE.2018-07-13T00-09-07Z
Commit-ID: 2aa18cafc674faf97201a973504cb4caa3a3e67c
```
* Environment name and version (e.g. nginx 1.9.1):
```
Vagrant 2.1.2

Nginx 1.6.2

PHP 7.1.10-1+0~20170929170631.9+jessie~1.gbp501135 (cli) (built: Sep 29 2017 17:33:58) ( NTS )
```
* Server type and version:
```
Linux example 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
Debian Jessie x64
```
* Operating System and version (`uname -a`):
```
Darwin macbook.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
```
* Link to your project:
It's private project.

**Comment by harshavardhana** [comment] 2018-11-10 00:16
You should delete the object first @bupy7 , we stage the object before we rename so we need 2x space at any given point in time.

**Comment by bupy7** [comment] 2018-11-10 00:18
@harshavardhana 

I used only 10 Mib my free space. I don't understand why I cannot upload more.
I successfull uploaded another files through Minio Browser. What is wrong?
Multipart upload will solve this problem?

**Comment by bupy7** [comment] 2018-11-10 00:41
@harshavardhana I successfull uploaded another files through Minio Browser. What is wrong?

**Comment by bupy7** [comment] 2018-11-10 00:53
@harshavardhana Multipart upload will solve this problem?

**Comment by bupy7** [comment] 2018-11-10 00:56
No, throught Minio Browser its don't work too. 507 Insufficient Storage. =(

**Comment by harshavardhana** [comment] 2018-11-10 00:57
@bupy7 as I said it's not a problem it's by design, you should delete the objects first. Not expect PutObject to work since PutObject requires staging and then rename() so at one point in time, we need additional space to stage the data. 

So please delete data and upload.

**Comment by bupy7** [comment] 2018-11-10 01:04
@harshavardhana Yes, of course. But I have **21Gb free space**. I said it at the my first message. Why Minio think that I don't have enough free space?

```
vagrant@example:/mnt$ df -h
Filesystem                             Size  Used Avail Use% Mounted on
/dev/sda1                              9.2G  7.8G  967M  90% /
udev                                    10M     0   10M   0% /dev
tmpfs                                  201M  4.4M  196M   3% /run
tmpfs                                  501M     0  501M   0% /dev/shm
tmpfs                                  5.0M     0  5.0M   0% /run/lock
tmpfs                                  501M     0  501M   0% /sys/fs/cgroup
192.168.20.1:/Volumes/Project/locale   28G  7.7G   21G  28% /vagrant
```

**Comment by harshavardhana** [comment] 2018-11-10 01:08
> @harshavardhana Yes, of course. But I have **21Gb free space**. I said it at the my first message. Why Minio think that I don't have enough free space?
> 
> ```
> vagrant@example:/mnt$ df -h
> Filesystem                             Size  Used Avail Use% Mounted on
> /dev/sda1                              9.2G  7.8G  967M  90% /
> udev                                    10M     0   10M   0% /dev
> tmpfs                                  201M  4.4M  196M   3% /run
> tmpfs                                  501M     0  501M   0% /dev/shm
> tmpfs                                  5.0M     0  5.0M   0% /run/lock
> tmpfs                                  501M     0  501M   0% /sys/fs/cgroup
> 192.168.20.1:/Volumes/Project/locale   28G  7.7G   21G  28% /vagrant
> ```

Most probably because minio is running on root disk @bupy7, not in /vagrant check your minio startup.

**Comment by bupy7** [comment] 2018-11-10 01:15
Root Minio is `/mnt/minio`, but under `/` has 967Mb free more.

**Comment by harshavardhana** [comment] 2018-11-10 01:17
> Root Minio is `/mnt/minio`, but under `/` has 967Mb free more.

Minimum required in Minio is 1 gig free disk space.

**Comment by bupy7** [comment] 2018-11-10 01:18
@harshavardhana Ok, thanks a lot! I just will change mount directory and write here again after.

**Comment by harshavardhana** [comment] 2018-11-10 08:52
Feel free to close this issue.

**Comment by kannappanr** [comment] 2018-11-13 00:30
@bupy7 Closing this issue as answered. Please feel free to contact us if you have further questions.

**Closed as completed by kannappanr** 2018-11-13 00:30 UTC
Labels: working as intended, community, priority: medium

**Comment by bupy7** [comment] 2018-12-12 07:47
@harshavardhana everything is working. Thanks a lot!

**Comment by Paxa** [comment] 2019-01-16 05:04
How to configure this value?

**Comment by harshavardhana** [comment] 2019-01-16 05:15
You cannot minimum required is 1gig.

**Comment by Paxa** [comment] 2019-01-16 05:16
Would you like if I make it configurable and submit PR?

**Comment by harshavardhana** [comment] 2019-01-16 08:02
No we don't want it to be configurable, it is on purpose. It really doesn't make sense to start an object storage service without having 1gig of disk space.

**Comment by Paxa** [comment] 2019-01-16 08:43
Yes, unless we wanna do some testing or have small storage like 1-2gb. Also in some cases could be nice to increase minimum value
(I'm planing to use minio as example app for https://kuber.host/ but don't wanna give more storage for free plan)

**Comment by harshavardhana** [comment] 2019-01-16 08:46
We would like to limit the number of options we give our users and not confuse them. So 1g is a practical value. Feel free to fork Minio and make your own changes, but it is not something Minio upstream is interested in.

**Comment by recipedude** [comment] 2019-01-16 10:25
> You should delete the object first, we stage the object before we rename so we need 2x space at any given point in time.

Where is the file stored during staging? How to configure the location of the "staging" area?

Am also running into 

`An error occurred (XMinioStorageFull) when calling the UploadPart operation: Storage backend has reached its minimum free disk threshold.`

yet there is plenty (well over 2x) of free space in the storage volume.

**Comment by harshavardhana** [comment] 2019-01-16 11:02
You can simply look at `df -h` output it is definitely not possible that we are complaining before we run out of required space.  Staging is using the same backend disk as your actual data.

**Comment by jsmilani** [comment] 2020-02-25 17:30
I would like this reopened because the minimum threshold not being configurable makes dangerously incompatible with some automation tooling. Specifically when using it as an Elasticsearch Snapshot Repository, if your disk fills up then Elasticsearch cannot even delete old snapshots to clear up space. The Elasticsearch team states you should never delete snapshots manually (https://discuss.elastic.co/t/delete-some-snapshots-on-s3/151482/6) so the only choice is to increase disk space or delete the whole repository. Neither of these choices are good. Increasing disk to free disk is a contradiction and level of effort to decrease a disk size after increasing it is extremely high (usually requires replacing the disk). Deleting the repo is extremely bad option that we cannot even consider. The simplest fix would be to temporarily reconfigure the Minio min disk space to allow deletes so Elasticsearch can safely do the cleanup.

**Comment by harshavardhana** [comment] 2020-02-25 17:43
Are you saying that you don't even have 900MiB free space? @jsmilani

**Comment by harshavardhana** [comment] 2020-02-25 18:18
```go
        diskMinFreeSpace  = 900 * humanize.MiByte // Min 900MiB free space.
        diskMinTotalSpace = diskMinFreeSpace      // Min 900MiB total space.
```

This is the minimum, I don't see the point of making this configurable. If you don't even have 900MiB of disk space we are really trying to squeeze things here for no good reason, you should be buying more storage.

**Comment by Paxa** [comment] 2020-02-25 18:30
Agree with @jsmilani, there are several use cases when we may need to run it on small volumes, e.g. testing pipelines.
And most of cloud system provide only volume increase feature and no downsize feature

**Comment by harshavardhana** [comment] 2020-02-25 18:39
IMO it doesn't make sense. Best option fork, modify and use it the way you want. 

Let's close this topic for now.
