### ISSUE TITLE
[shared-fs] Concurrent multipart uploads intermittently fail with Invalid UploadId

### ISSUE THREAD

**Issue by krisis** [minio/minio#3527] opened 2017-01-04 09:10 UTC
Concurrent multipart uploads intermittently fail with Invalid UploadId.
## Expected Behavior

Concurrent multipart uploads must complete successfully.
## Current Behavior

Errors seen on servers:
```
time="2017-01-04T14:16:56+05:30" level=error msg="Unable to create object part."
 cause="rename \\\\?\\c:\\Users\\Atul\\sb-kp\\.minio.sys\\tmp\\1538fb7e-b548-420
6-9365-55b573e7b30a\\7f4e6e31-39b3-4932-ba2e-72a313414935.91ae6e2b-095e-4aca-87d
1-393e9b1a15cf.object2 \\\\?\\c:\\Users\\Atul\\sb-kp\\.minio.sys\\multipart\\tes
t\\minio.exe\\7f4e6e31-39b3-4932-ba2e-72a313414935\\object2: Access is denied."
source="[object-handlers.go:641:objectAPIHandlers.PutObjectPartHandler()]" stack
="/home/harsha/mygo/src/github.com/minio/minio/cmd/fs-v1-helpers.go:317:fsRename
File /home/harsha/mygo/src/github.com/minio/minio/cmd/fs-v1-multipart.go:469:fsO
bjects.PutObjectPart <autogenerated>:228:(*fsObjects).PutObjectPart /home/harsha
/mygo/src/github.com/minio/minio/cmd/object-handlers.go:638:objectAPIHandlers.Pu
tObjectPartHandler /home/harsha/mygo/src/github.com/minio/minio/cmd/api-router.g
o:44:(objectAPIHandlers).PutObjectPartHandler-fm"
```
```
time="2017-01-04T14:17:21+05:30" level=error msg="Unable to complete multipart u
pload." cause="Prefix access is denied: test/minio.exe" source="[object-handlers
.go:774:objectAPIHandlers.CompleteMultipartUploadHandler()]" stack="/home/harsha
/mygo/src/github.com/minio/minio/cmd/fs-v1-multipart.go:640:fsObjects.CompleteMu
ltipartUpload <autogenerated>:231:(*fsObjects).CompleteMultipartUpload /home/har
sha/mygo/src/github.com/minio/minio/cmd/object-handlers.go:772:objectAPIHandlers
.CompleteMultipartUploadHandler /home/harsha/mygo/src/github.com/minio/minio/cmd
/api-router.go:48:(objectAPIHandlers).CompleteMultipartUploadHandler-fm"
time="2017-01-04T14:17:21+05:30" level=error msg="Unable to complete multipart u
pload." cause="Prefix access is denied: test/minio.exe" source="[object-handlers
.go:774:objectAPIHandlers.CompleteMultipartUploadHandler()]" stack="/home/harsha
/mygo/src/github.com/minio/minio/cmd/fs-v1-multipart.go:640:fsObjects.CompleteMu
ltipartUpload <autogenerated>:231:(*fsObjects).CompleteMultipartUpload /home/har
sha/mygo/src/github.com/minio/minio/cmd/object-handlers.go:772:objectAPIHandlers
.CompleteMultipartUploadHandler /home/harsha/mygo/src/github.com/minio/minio/cmd
/api-router.go:48:(objectAPIHandlers).CompleteMultipartUploadHandler-fm"
time="2017-01-04T14:17:21+05:30" level=error msg="Unable to complete multipart u
pload." cause="Prefix access is denied: test/minio.exe" source="[object-handlers
.go:774:objectAPIHandlers.CompleteMultipartUploadHandler()]" stack="/home/harsha
/mygo/src/github.com/minio/minio/cmd/fs-v1-multipart.go:640:fsObjects.CompleteMu
ltipartUpload <autogenerated>:231:(*fsObjects).CompleteMultipartUpload /home/har
sha/mygo/src/github.com/minio/minio/cmd/object-handlers.go:772:objectAPIHandlers
.CompleteMultipartUploadHandler /home/harsha/mygo/src/github.com/minio/minio/cmd
/api-router.go:48:(objectAPIHandlers).CompleteMultipartUploadHandler-fm"
time="2017-01-04T14:17:21+05:30" level=error msg="Unable to complete multipart u
pload." cause="Prefix access is denied: test/minio.exe" source="[object-handlers
.go:774:objectAPIHandlers.CompleteMultipartUploadHandler()]" stack="/home/harsha
/mygo/src/github.com/minio/minio/cmd/fs-v1-multipart.go:640:fsObjects.CompleteMu
ltipartUpload <autogenerated>:231:(*fsObjects).CompleteMultipartUpload /home/har
```
## Possible Solution

Not known
## Steps to Reproduce (for bugs)

1. Set up two minio servers on port 9001, 9002  respectively.
2. Download https://gist.github.com/krisis/46fabb7c7fb178f9712cc1890938b17f to uploads-test.go (say).
3. ``go run uploads-test.go``
N B The program assumes certain files to be present, modify suitable to your needs. It is meant to demonstrate the issue and _doesn't_ work everywhere without modification.

## Your Environment

* Version used:
```
Version: 2017-01-04T07:22:10Z
Release-Tag: RELEASE.2017-01-04T07-22-10Z
Commit-ID: cefb3d4952c34dc78d1423e386469fcb06045ce7
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version: MS Windows 8.1
* Link to your project: -

**Comment by harshavardhana** [comment] 2017-01-04 16:12
If some uploads received the same upload id and one of them completed before the second will see NoSuchUpload.  minio-go doesn't do re-upload if it sees NoSuchUpload on completemultipart.

**Comment by harshavardhana** [comment] 2017-01-04 16:55
The issue is expected as i explained, the messages in the logs are suspicious one is related to background-append and another is related to accessing a file which is locked.

Will check what is going on.

**Comment by harshavardhana** [comment] 2017-01-04 17:48
Should be fixed on the recent push to PR.

**Closed as completed by harshavardhana** 2017-01-04 17:48 UTC
