### ISSUE TITLE
minio server fails to start if an object by name `policy.json` is present

### ISSUE THREAD

**Issue by krisis** [minio/minio#4484] opened 2017-06-06 13:19 UTC
## Expected Behavior

minio server should start successfully, migrating the object (`policy.json`) correctly.

## Current Behavior

```
➜  minio git:(master) ✗ minio server /tmp/fs 
Please do not stop the server.
Migrating bucket metadata format from "1" to newer format "2"... completed successfully.FATA[0002] Initializing object layer failed              cause=corrupted backend format, please join https://slack.minio.io for assistance source=[server-main.go:276:serverMain()]
```
The backend after migration (and failure to start) looks like this.
```
/tmp/fs
├── .minio.sys
│   ├── buckets
│   │   └── test
│   │       ├── objects
│   │       └── policy.json
│   │           └── fs.json
│   ├── format.json
│   ├── multipart
│   └── tmp
│       └── 7420720b-1653-42c7-8a75-b99644e1aaef
└── test
    └── policy.json

```
## Possible Solution

Not known yet
## Steps to Reproduce (for bugs)

[use minio with version `99ddd35`]
1. `mc mb s1/test`
2. `mc cp /etc/lsb-release s1/test/policy.json`

[use minio master `a4d1ef1`]
3. Minio server fails to start.
4.

## Context

Testing recent fs mode format change.
## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment] 2017-06-06 14:23
Closing as duplicate of #4478

**Closed as completed by harshavardhana** 2017-06-06 14:23 UTC
Labels: duplicate

**Comment by krisis** [comment] 2017-06-07 14:21
This issue is fixed by https://github.com/minio/minio/pull/4482 too.
