### ISSUE TITLE
Share URL

### ISSUE THREAD

**Issue by dR3b** [minio/minio#3463] opened 2016-12-16 12:44 UTC
## Expected Behavior
Expire URL should remove automatically when the file was deleted.

## Current Behavior
URL still is alive even the file doesn't exist anymore.

## Steps to Reproduce (for bugs)
Share a file:
```bash
~ % mc share download minio/tmp/freebsd11.txt
```
```bash
~ % mc share list download
URL: http://127.0.0.1:9000/tmp/freebsd11.txt
Expire: 6 days 23 hours 32 minutes 41 seconds
Share: http://127.0.0.1:9000/tmp/freebsd11.txt?X-Amz-Algorithm.....
```
Remove the file or remove the bucket.
```bash
~ % mc rm --recursive --force minio/tmp
```

## Your Environment

* Version used: **mc** 2016-12-09T18:23:19Z 
* Server type and version: **minio** 2016-12-13T17:19:42Z
* Operating System and version: Arch Linux | FreeBSD R11.0

**Comment by harshavardhana** [comment] 2016-12-16 16:17
This is not possible it is a client side functionality and these URLs if they exist are harmless.

It is also expensive for a client to reach server for every possible object delete and make unnecessary calls. 

Closing this with working as intended.

**Closed as completed by harshavardhana** 2016-12-16 16:17 UTC
