### ISSUE TITLE
mc export users and policies

### ISSUE THREAD

**Issue by fabio-longarai** [minio/minio#8338] opened 2019-09-30 21:10 UTC
**Is your feature request related to a problem? Please describe.**
"mc mirror" does a great job cloning data between different minio services. Yet... there's no way to replicate users credentials and policies from one installation to another.

**Describe the solution you'd like**
Maybe a "mc export" would provide a great tool to export users and policies. An "mc import" should not be needed if current admin commands provide enough resources to recreate an  user from a provided export output.

**Describe alternatives you've considered**
Another alternative is to add some flag to the current 'mirror' function to allow mirroring users and policies.

**Additional context**
Since minio now supports groups, maybe it would be nice to have a groups support on an export command.

**Comment by donatello** [comment] 2019-10-04 20:58
The problem is in exporting of credentials. Currently none of the admin APIs export user secret keys, but it would be needed the feature described here. Exporting secret keys is problematic because the feature could be abused. By design even AWS never returns secret keys after the first time they are created.

We will discuss internally about adding such a feature and update here.

**Comment by harshavardhana** [comment] 2019-12-18 23:08
This is unsafe for us to do and don't see a cleaner way that doesn't compromise security aspects here. Closing this issue as not going to be fixed.

**Closed as completed by harshavardhana** 2019-12-18 23:08 UTC
Labels: community, out of scope
