### ISSUE TITLE
Create a sub-directory from the Web UI

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#6518] opened 2018-09-24 23:07 UTC
One of the guys at the conference asked us how to create sub-directories from the UI, since we can support it now from the S3 API, we should provide a way to do it from the UI. This is a very useful feature for the web-UI consumers.

**Comment by harshavardhana** [comment] 2018-09-24 23:32
Duplicate of #3933

**Closed as completed** 2018-09-25 02:09 UTC
Labels: duplicate, community
