### ISSUE TITLE
Can't upload more than 1 MB with Minio distribuited Docker stack 

### ISSUE THREAD

**Issue by lettore** [minio/minio#8538] opened 2019-11-19 21:46 UTC
## Expected Behavior

It should be possible to upload files bigger than 1MB to a distribuited Minio setup

## Current Behavior

When I upload a file bigger than 1MB I receive
 "We encountered an internal error, please try again." in Minio frontpage and this error in the container log
`
Status:         4 Online, 0 Offline. 
Endpoint:  http://10.0.19.176:9000  http://10.0.32.160:9000  http://172.18.0.17:9000  http://127.0.0.1:9000
Browser Access:
   http://10.0.19.176:9000  http://10.0.32.160:9000  http://172.18.0.17:9000  http://127.0.0.1:9000
Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
API: SYSTEM()
Time: 21:28:41 UTC 11/19/2019
DeploymentID: 8df3fa99-3c51-4a4a-9441-923006c3d800
Error: Write failed. Insufficient number of disks online
       5: cmd/erasure-encode.go:100:cmd.(*Erasure).Encode()
       4: cmd/xl-v1-object.go:630:cmd.xlObjects.putObject()
       3: cmd/xl-v1-object.go:514:cmd.xlObjects.PutObject()
       2: cmd/xl-sets.go:653:cmd.(*xlSets).PutObject()
       1: cmd/web-handlers.go:1060:cmd.(*webAPIHandlers).Upload()`

## Steps to Reproduce (for bugs)

Deploy the official Docker Swarm stack [https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/docker-swarm/docker-compose-secrets.yaml](url)
Instead of using a named volume
`volumes:
      - minio1-data:/export`
 mount the directory as bind mount
` volumes:
     - /minio1:/export`

The issue won't happen if I run the standalone server with this command
`docker run -p 9000:9000 --name minio1 \
  -v /minio:/data \
  minio/minio server /data`

I'm using Traefik as proxy but it should not be the problem because I can upload 1 GB file with the same setup but with named volumes or running the standalone server with bind mount
## Your Environment

* Version used (`latest`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): Linux Home-Server 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment] 2019-11-21 22:36
This doesn't look like MinIO limit @lettore some configuration issue on your end perhaps traefik is the culprit here. 

We have tests running proper for all kinds of file sizes so I don't think its a problem.

**Comment by lettore** [comment] 2019-11-22 06:13
> This doesn't look like MinIO limit @lettore some configuration issue on your end perhaps traefik is the culprit here.
> 
> We have tests running proper for all kinds of file sizes so I don't think its a problem.


Thank you for the reply, it can't be a Traefik problem because I connect directly to http://local-ip:9000 and I made no changes to the official stack, so it can't be a configuration problem. 
As I said running the container only with the command "server /export" works.
The issue happens when I run "server http://minio{1...4}/export".
This happened only with bond mounts not with named volumes.
Did you tried to make it works with bind mount enabled?

**Comment by harshavardhana** [comment] 2019-11-29 01:40
> Did you tried to make it works with bind mount enabled?

We have the same tests running on Docker, Kubernetes, and bare-metal we can't seem to reproduce this problem. Try to remove Traefik and uploading again.

**Comment by harshavardhana** [comment] 2019-12-04 17:42
Closing this issue as not reproducible.

**Closed as completed by harshavardhana** 2019-12-04 17:42 UTC
Labels: working as intended, community

**Comment by cloutier** [comment] 2020-02-14 19:44
If anyone comes here with a Google search like me because they had the same problem:

Mine was caused by using the NGINX ingress with kubernetes, which defaults to limiting upload to 1mb. I solve the problem by putting an annotation in my ingress: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

**Comment by Samuel-Schober-USU** [comment] 2021-08-24 09:09
Thanks @cloutier , saved me a lot of trouble
