### ISSUE TITLE
Minio cluster becomes unresponsively if a minority of disks are down

### ISSUE THREAD

**Issue by davidgeorgealex** [minio/minio#5190] opened 2017-11-15 09:35 UTC
I have a custom Docker image where I bundle Minio and MC [docker.tar.gz](https://github.com/minio/minio/files/1474050/docker.tar.gz). Beside this, this Docker image contains a startupHeal script that will do the healing when the nodes joins the cluster, if it was down due to different reasons (since I will use Kubernetes for orchestration, the nodes can be re-started automatically). This scripts waits for a 30 seconds before starting looking if the cluster is up (all the nodes don't have errors) and then proceed with a basic heal operation. 

I start a Minio cluster using [docker-compose.txt](https://github.com/minio/minio/files/1474051/docker-compose.txt) and upload some files with [MinioClientUploader.txt](https://github.com/minio/minio/files/1474054/MinioClientUploader.txt). Everything works as expected, but when I kill a node (for example minio3), the cluster becomes unresponsively and cannot upload files using the Java client. More, the UI and `mc ls` sometimes display `disk error` and sometimes responds very slow. This ticket is very similar with https://github.com/minio/minio/issues/5189, but the difference is that we are using a custom image (with Minio, MC and a startupHeal script bundled) and the result of uploads during un-complete cluster is an error sometimes. 

## Your Environment
* Version used (`minio version`): Minio - latest, MC - latest
* Operating System and version (`uname -a`): 42~16.04.1-Ubuntu

**Comment by krisis** [comment] 2017-11-17 11:23
@davidgeorgealex In your setup, minio3 has 2 disks out of 4 in all. So, when minio3 is offline the setup has only 2 disks online. In a 4 disk setup, you need 3 of them to be online for uploads to be successful. So, what you observe is expected.

**Comment by davidgeorgealex** [comment] 2017-11-17 12:17
Hi @krisis, thanks for looking into this. Indeed, I miss-configured the `server` command that is used to start the cluster. I forgot to add one disk for minio1 and one for minio2. I've updated the command, so I use `    command: server http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2 http://minio3/export1 http://minio3/export2` to all 3 nodes in docker-compose file. I'm still having issues:
1. If I kill one container (minio3 for example), I get sometimes `disk not found from net error` in the UI
2. From the command line, if I exec into one of two remaining containers (minio2) for example and do `mc ls local/photos` (where photos bucket was created previously), I got `mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.` most of the times. 
3. Using the MinioClientUploader.java, if I start it when minio3 is down, I get the following stacktrace:
`    command: server http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2 http://minio3/export1 http://minio3/export2
`
Please do the same steps (update the command and run the 1-3 scenarios).
Running `mc admin info local` I get:
`  localhost:9000
   Uptime : online since 10 minutes ago
  Version : 2017-11-02T07:27:31Z
   Region : 
 SQS ARNs : <none>
  Network : Incoming 391KiB, Outgoing 1.3MiB
  Storage : Total 156GiB, Free 99GiB, Online Disks: 6, Offline Disks: 0

●  minio1:9000
   Uptime : online since 10 minutes ago
  Version : 2017-11-02T07:27:31Z
   Region : 
 SQS ARNs : <none>
  Network : Incoming 274KiB, Outgoing 207KiB
  Storage : Total 156GiB, Free 99GiB, Online Disks: 6, Offline Disks: 0

●  minio3:9000
   Uptime : Server is offline
    Error : dial-http minio3:9000/minio/admin: dial tcp: lookup minio3 on 127.0.0.11:53: server misbehaving
`
Thanks for the help !

**Comment by krisis** [comment] 2017-11-20 08:23
> If I kill one container (minio3 for example), I get sometimes disk not found from net error in the UI

This is expected. Minio server tries to reconnect periodically with offline disks. Every time such a connection attempt fails we will see those error messages on the console.

> From the command line, if I exec into one of two remaining containers (minio2) for example and do mc ls local/photos (where photos bucket was created previously), I got mc: <ERROR> Unable to list folder. We encountered an internal error, please try again. most of the times.

I wasn't able to recreate this locally. Let me browse the code to see why this may happen.

> Using the MinioClientUploader.java, if I start it when minio3 is down, I get the following stacktrace:

Could you paste the java stack trace?

**Comment by davidgeorgealex** [comment] 2017-11-24 11:49
HI @krisis, I performed more tests and come back with a piece of code that throws the exception: 
[MinioClientUploaderV2.txt](https://github.com/minio/minio/files/1501525/MinioClientUploaderV2.txt). This is a Java code, so please change the extension from `.txt` to `.java`. 
So, using the initial docker image (the one from the initial post, with Minio and MC), While running the attached Java code which will upload a file multiple times and does also a `listObjects`, I'm killing one of the three nodes from the cluster (from the initial docker-compose file - for example minio3). As a result, the file is still uploaded, but I get the following stacktrace while getting the bucket objects:
`java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:227)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at io.minio.MinioClient.execute(MinioClient.java:998)
	at io.minio.MinioClient.executeGet(MinioClient.java:1192)
	at io.minio.MinioClient.listObjectsV2(MinioClient.java:2609)
	at io.minio.MinioClient.access$100(MinioClient.java:158)
	at io.minio.MinioClient$5$1.populate(MinioClient.java:2483)
	at io.minio.MinioClient$5$1.hasNext(MinioClient.java:2506)
	at com.example.MinioClientUploader.main(MinioClientUploader.java:35)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	... 26 more`

Also the upload performs quite slow, so this might be the reason why I get that timeout exception. 
If I try to perform an "mc ls local/photos` I got `mc: <ERROR> Unable to list folder. We encountered an internal error, please try again.`

Please let me know if you are able to reproduce the issue with the provided Java code.

Thanks for the help and hopefully we can pinpoint the issue,
George

**Comment by davidgeorgealex** [comment] 2017-11-24 12:13
Upgrading my image to the latest Minio image (https://github.com/minio/minio/tree/RELEASE.2017-11-22T19-55-46Z), I got from the Java code:
`error occured
ErrorResponse(code=InternalError, message=We encountered an internal error, please try again., bucketName=null, objectName=null, resource=/photos/test0.json, requestId=3L137, hostId=3L137)
request={method=PUT, url=http://127.0.0.1:9001/photos/test0.json, headers=Content-Type: application/json
Host: 127.0.0.1:9001
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: 267ad975e5d6ab2b8abfeaad68b217fd24e76a4047e94f43141563797be074b5
x-amz-date: 20171124T121253Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20171124/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=500, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-11-24T12-05-44Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14FA04803E7613B5
Date: Fri, 24 Nov 2017 12:12:53 GMT
Transfer-Encoding: chunked
}	at io.minio.MinioClient.execute(MinioClient.java:1099)
	at io.minio.MinioClient.executePut(MinioClient.java:1266)
	at io.minio.MinioClient.executePut(MinioClient.java:1288)
	at io.minio.MinioClient.putObject(MinioClient.java:3480)
	at io.minio.MinioClient.putObject(MinioClient.java:3520)
	at io.minio.MinioClient.putObject(MinioClient.java:3001)
	at io.minio.MinioClient.putObject(MinioClient.java:3038)
	at com.example.MinioClientUploader.main(MinioClientUploader.java:33)`

**Comment by davidgeorgealex** [comment] 2017-11-27 10:25
Exceptions in the node logs:
`minio2_1  | time="2017-11-27T10:23:54Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:04 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:54Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:07 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:55Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:07 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:55Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:11 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:55Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:11 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:55Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:12 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:55Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:12 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:55Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:24 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:55Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:16:24 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:55Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:18:02 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:56Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:18:02 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:56Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:18:07 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:56Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:18:07 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:56Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:18:52 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:56Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:18:52 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:56Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:21:40 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:56Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:21:40 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:56Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:23:08 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:23:08 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:23:34 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/aatestMon Nov 27 12:23:34 EET 2017.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/test0.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/test0.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/test1.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/test1.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/test16.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:57Z" level=error msg="Unable to stat a file photos/test16.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:58Z" level=error msg="Unable to stat a file photos/test19.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:58Z" level=error msg="Unable to stat a file photos/test19.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:58Z" level=error msg="Unable to stat a file photos/test21.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:58Z" level=error msg="Unable to stat a file photos/test21.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:58Z" level=error msg="Unable to stat a file photos/test23.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:58Z" level=error msg="Unable to stat a file photos/test23.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:58Z" level=error msg="Unable to stat a file photos/test9.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio2_1  | time="2017-11-27T10:23:58Z" level=error msg="Unable to stat a file photos/test9.json//xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
`

**Comment by davidgeorgealex** [comment] 2017-12-04 14:55
Hi @krisis, do you have any updates on this?
Thanks,
George

**Comment by krisis** [comment] 2017-12-08 10:50
@davidgeorgealex the logs seen in https://github.com/minio/minio/issues/5190#issuecomment-347139708
are expected. During the listing operation, minio server checks if a given path is a prefix or an object. This check is performed on the disks, one after another, until it returns successfully. Since one disk is down, it returns "disk not found from net error" which is printed on the console.

Further, the exception observed in https://github.com/minio/minio/issues/5190#issuecomment-346815528
is not due to a timeout, as seen with an older minio release. Could you provide the size of the file (test0.json) that is being uploaded?

**Comment by krisis** [comment] 2017-12-08 10:59
@davidgeorgealex, could you run `docker-compose -f docker-compose.txt run minio1 version` on your setup? I am unable to recreate this issue with the latest minio server and minio-3.0.10-all.jar. Could you check if you continue to see this issue after moving to latest minio-server and minio-java releases?

**Comment by davidgeorgealex** [comment] 2017-12-11 11:55
@krisis Even with the latest libraries, I'm still facing an issue. Sometimes it works, but sometimes I got:
`minio1_1  | time="2017-12-11T11:52:58Z" level=error msg="Unable to stat a file photos/testaavMon Dec 11 13:52:50 EET 2017.json/xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio1_1  | time="2017-12-11T11:52:58Z" level=error msg="Unable to stat a file photos/testaavMon Dec 11 13:52:50 EET 2017.json/xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" 
minio1_1  | time="2017-12-11T11:53:00Z" level=error msg="Unable to create an object. /photos/testaavMon Dec 11 13:52:59 EET 2017.json" cause="disk not found from net error" source="[object-handlers.go:612:objectAPIHandlers.PutObjectHandler()]" stack="object-api-input-checks.go:139:checkPutObjectArgs xl-v1-object.go:448:xlObjects.PutObject <autogenerated>:1:(*xlObjects).PutObject object-handlers.go:610:objectAPIHandlers.PutObjectHandler api-router.go:63:(objectAPIHandlers).PutObjectHandler-fm" 
`
I'm still investigate if something is missing. Does these new logs raise any bell?

**Comment by davidgeorgealex** [comment] 2017-12-11 11:56
The file that I try to upload is very small (it just contains `{
    "data" : "testing file for Minio java client uploader"
}
` as string

**Comment by davidgeorgealex** [comment] 2017-12-12 07:23
@krisis Please find new reproducer files:
[docker.tar.gz](https://github.com/minio/minio/files/1550571/docker.tar.gz)
[docker-compose.yml.tar.gz](https://github.com/minio/minio/files/1550577/docker-compose.yml.tar.gz)
[java.tar.gz](https://github.com/minio/minio/files/1550572/java.tar.gz)

The docker.tar.gz contains the files for creating Docker image (custom image with Minio&MC and some healing scripts at startup. The Dockerfile and entrypoint are based on https://github.com/minio/minio/tree/RELEASE.2017-11-22T19-55-46Z). 
The docker-compose.yml.tar.gz contains the docker-compose.yml used to start the cluster
The java.tar.gz contains the Java code for the uploader, the json file to be uploaded and the latest version of the Minio jar file.

Steps:
1. Extract the docker.tar.gz archive
2. Run ` docker build -t storage .` from the extracted folder to create the Docker image
3. Extract docker-compose.yml.tar.gz and run `docker-compose up` from the folder where it was extracted. This will create the Minio cluster with 3 instances, each with 2 nodes. Check in browser if everything is ok (http://localhost:9001/minio, http://localhost:9002/minio, http://localhost:9003/minio)
4. Run MinioClientUploader.java. The upload should start and you can see this in the console.
5. Kill node 3 for example (run `docker ps -a`, get the `Container Id` for node 3, and run `docker kill ***`)
6. The MinioClientUploader.java should continue to run without a problem
7. Run `docker start ***` for the same `Container Id` that was killed on step #5
8. Check in the docker console if the node started successfully - the MinioClinetUploader.java should continue to run without a problem
9. Kill node 2, in the same way as 3 was killed on step #5
10. Start node node 2
11. Repeat this sequence of killing/starting nodes 2 and 3 till exception is raised in the MinioClientUploader. Usually this happens after killing the nodes two times.

In Java logs I see:
`error occured
ErrorResponse(code=InternalError, message=We encountered an internal error, please try again., bucketName=null, objectName=null, resource=/photos/testTue Dec 12 09:01:07 EET 2017.json, requestId=3L137, hostId=3L137)
request={method=PUT, url=http://127.0.0.1:9001/photos/testTue%20Dec%2012%2009%3A01%3A07%20EET%202017.json, headers=Content-Type: application/json
Host: 127.0.0.1:9001
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: 267ad975e5d6ab2b8abfeaad68b217fd24e76a4047e94f43141563797be074b5
x-amz-date: 20171212T070108Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20171212/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=500, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-12-12T06-53-36Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14FF79EFB8450953
Date: Tue, 12 Dec 2017 07:01:10 GMT
Transfer-Encoding: chunked
}	at io.minio.MinioClient.execute(MinioClient.java:1201)
	at io.minio.MinioClient.executePut(MinioClient.java:1368)
	at io.minio.MinioClient.executePut(MinioClient.java:1390)
	at io.minio.MinioClient.putObject(MinioClient.java:3688)
	at io.minio.MinioClient.putObject(MinioClient.java:3728)
	at io.minio.MinioClient.putObject(MinioClient.java:3138)
	at io.minio.MinioClient.putObject(MinioClient.java:3175)
	at com.example.MinioClientUploader.main(MinioClientUploader.java:31)`

and in the container logs, I see 
`minio1_1 | time="2017-12-11T11:52:58Z" level=error msg="Unable to stat a file photos/testaavMon Dec 11 13:52:50 EET 2017.json/xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" minio1_1 | time="2017-12-11T11:52:58Z" level=error msg="Unable to stat a file photos/testaavMon Dec 11 13:52:50 EET 2017.json/xl.json" cause="disk not found from net error" source="[xl-v1-common.go:67:xlObjects.isObject()]" minio1_1 | time="2017-12-11T11:53:00Z" level=error msg="Unable to create an object. /photos/testaavMon Dec 11 13:52:59 EET 2017.json" cause="disk not found from net error" source="[object-handlers.go:612:objectAPIHandlers.PutObjectHandler()]" stack="object-api-input-checks.go:139:checkPutObjectArgs xl-v1-object.go:448:xlObjects.PutObject <autogenerated>:1:(*xlObjects).PutObject object-handlers.go:610:objectAPIHandlers.PutObjectHandler api-router.go:63:(objectAPIHandlers).PutObjectHandler-fm"` before the exception is raised. 

As a note, also the UI becomes un-operable after the exception is raised in Java uploader.

**Comment by davidgeorgealex** [comment] 2017-12-19 12:43
@krisis Do you have any updates on this?

Thanks!

**Comment by krisis** [comment] 2017-12-20 07:17
@davidgeorgealex thank you for your patience. I finally managed to find the root cause of this issue. I have sent a [fix](https://github.com/minio/minio/pull/5310) for this and expect it to be merged soon.

**Closed as completed** 2017-12-21 06:58 UTC
Labels: fixed, priority: medium
