### ISSUE TITLE
docs: terminology usage for different setups : fs singlenode-XL distributed-XL

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3239] opened 2016-11-10 16:22 UTC
For internal discussion and at code level, we use the terms fs, singlnode-XL, distributed-XL for different minio setups.

However in the documentation we don't use these terms at all. Because of this communication with users on minio channel and github issues becomes harder. For ex. 
* we can't just ask "is your setup minio-fs or xl?" we'll have ask how they start the minio server and figure out if it's minio fs/xl.
* we can't say ETag is not supported on FS and supported only on XL, we'll have to put it in a different verbose way.

**Comment by harshavardhana** [comment] 2016-11-10 16:26
> we can't say ETag is not supported on FS and supported only on XL, we'll have to put it in a different verbose way.

This will go away since we are going to make it a default behavior so FS setups are no different.

**Comment by koolhead17** [comment] 2016-11-29 08:56
@harshavardhana Can this be closed after adding  ``ETag is supported with Distributed & works with FS`` as well to FAQ?

**Comment by harshavardhana** [comment] 2016-11-29 09:04
Oh yes this is no longer valid.

**Comment by harshavardhana** [comment] 2016-11-29 09:05
Wait re-opening we still need to discuss about the other points @krishnasrinivas has mentioned. So keeping it open for discussion.

**Comment by koolhead17** [comment] 2017-01-31 09:48
@harshavardhana @krishnasrinivas Is it still in discussion?

**Comment by harshavardhana** [comment] 2017-02-06 03:18
Two modes of operations:
- Standalone 
- Distributed 

Two types of backends:
- FS
- Erasure Code

**Comment by krishnasrinivas** [comment] 2017-02-09 17:27
I think this issue should not be closed yet. Here is the reason why:

![minioslack1](https://cloud.githubusercontent.com/assets/634494/22794657/cd08902e-eea8-11e6-9629-d8860a2a693f.png)

We should come up with consistent terminologies that we will use in our documentation and we should use the same terminologies when communicating with our users.

For example, we can call the three different setups as:
1) FS mode
2) Singlenode Erasure mode (abbrv. SE mode)
3) Distributed Erasure mode (abbrv. DE mode)

**Comment by harshavardhana** [comment] 2017-02-09 17:32
The issue is closed as I mentioned what are the agreed terminologies and our documentation is using these terminologies already. It is how we usually use it needs to be changed. We confused the community with XL etc our docs don't talk about it.

Also there are no abbrev .. list of type of setups possible with Minio

- Standalone FS
- Standalone Erasure
- Distributed FS (shared)
- Distributed Erasure

**Closed as completed by harshavardhana** 2017-02-09 17:32 UTC

**Comment by harshavardhana** [comment] 2017-02-09 17:45
|    Minio    | FS | Erasure | Stability |
|:-----------:|:----:|:----:|:---:|
| Standalone  | x  | x  | Stable |
| Distributed | x  | x  | Stable |

And here is the matrix.
