### ISSUE TITLE
MC mirror with --watch fails after some hours

### ISSUE THREAD

**Issue by philipkozeny** [minio/minio#8324] opened 2019-09-27 11:20 UTC
I am running 2 Minio instances (one distributed with 3 hosts 2 disks each with the binary, one running with docker and 4 disks).

On another server I am running 

`/usr/local/bin/mc mirror --remove --overwrite --quiet --watch storage/live storage-failover/live`

This works fine for some time, but after ~24 hours (not always the same), there are no changes synced to the storage-failover node. The mc command is still running and doesn't show any error. I also don't see anything concerning in the trace or logs.

## Expected Behavior
I expect MC --watch to run indefinitely and don't stop syncing files after some time.

## Current Behavior
Changes in storage/ are no longer reflected on storage-failover/ after some time

## Your Environment
* Version used (`minio version`): Version: 2019-09-26T19:42:35Z (on both hosts)
* Environment name and version (e.g. nginx 1.9.1): Server 1 with distributed mode (3 nodes), connected to node-1, -2,-3 directly for --watch, doesn't matter
* Server type and version: Dedicated & Virtual Servers
* Operating System and version (`uname -a`):  Linux storage-3 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
* MC Version: Version: 2019-09-24T01:36:20Z

**Comment by kannappanr** [comment] 2019-09-27 14:25
@philipkozeny Are you overwriting existing objects or is it new objects that you are talking about? Does it start working once you restart `storage` How many objects are we talking about here? Do you have lots of prefixes etc? Is the distributed one named `storage`?

**Comment by philipkozeny** [comment] 2019-09-27 20:33
@kannappanr 

> Are you overwriting existing objects or is it new objects that you are talking about? 

I've seen it mainly with new / removed files, but will try.

> Does it start working once you restart storage

Can't confirm that 100%, will try it in the next few hours when it fails again

> How many objects are we talking about here?

Currently about ~500.000 objects in the bucket (all smaller size, around 100 GB in total)

> Do you have lots of prefixes etc?

All files have a prefix "id/" and then a generate UUID as a file name, `storage/live/113/7b4332e5-6c65-4f18-be9c-d27ff080ae9d` is a typical file name

> Is the distributed one named storage?

Yes, in that specific case it is nginx proxy in front of the 3 nodes, but I can also produce it when i connect directly to the 3 nodes

**Comment by philipkozeny** [comment] 2019-09-30 06:44
@kannappanr 

> Are you overwriting existing objects or is it new objects that you are talking about?

So I've done some more tests.

It happens with all kinds of operations, doesn't matter if its a new file, or overwrite or delete operation.

> Does it start working once you restart storage

Yes, after restarting all 3 nodes in the cluster the operations are mirrored again

**Comment by maitredede** [comment] 2019-10-10 23:43
Hi,
I have same problem in a kubernetes environment, running minio docker server `minio/minio:RELEASE.2019-10-02T21-19-38Z`, client mirror `minio/mc:RELEASE.2019-08-29T00-40-57Z`.
I replicate data from one namespace to an other one (same physical server). I have less objets, low activity (about 30 operations per week).
The problem is arrived sonner : I had mirror files just before evening, and next morning files were no longer synchronized.

**Comment by sinhaashish** [comment] 2019-10-14 06:46
@philipkozeny  i tried to replicate this , but was unsuccessful in about 6 hours of watch. Can you confirm by any means the connection was lost or the ip got changed with which `mc` was configured. Just wanted to double check before trying for 24 hour.

**Comment by philipkozeny** [comment] 2019-10-14 06:48
@sinhaashish IP did not get changed, those are dedicated servers hosted by Hetzner. Can't see any suspicious that the connection was lost. Any clue where I could verify / see that in the logs? Happy to provide more information.

**Comment by sinhaashish** [comment] 2019-10-15 03:18
Can you provide the `mc` and `minio server` log in this scenario.
`mc` log you can get by running the command with --debug option,  and enabling the Audit log on server using the `MINIO_AUDIT_LOGGER_HTTP_ENDPOINT` environment variable.

**Comment by sinhaashish** [comment] 2019-10-17 09:34
`mc` watch uses listen bucket notification. There is an issue with listen bucket notification so referring it here as well https://github.com/minio/minio/issues/8403

**Comment by gcmsch** [comment] 2019-11-06 13:46
I do have the same issue as well. I'm currently evaluating minio and it's live mirroring feature, so right now this is a test setup.
mc version RELEASE.2019-10-09T22-54-57Z
minio version 2019-10-12T01:39:57Z

I have two physical servers running minio, 56 hard drives each, one minio instance per server. No docker containers involved, just the binaries running on the physical servers. Static IP address. 2x 10 GbE ethernet interfaces (LACP). So in short: Everything you would expect from a production server :-)

`mc mirror` invocation: `./mc mirror --watch --overwrite --remove --quiet ams1/orig ams3/orig`
`ams1` and `ams3` are the two minio instances running on two physical servers. `mc mirror` runs on `ams1`, so there's not even any sort of network infrastructure in between those two processes, just local loopback communication.

I started `mc mirror` two days ago, worked just fine for a few hours. Did something else yesterday and started testing again today and `mc mirror` has stopped working.
I did a bit of debugging:
- The TCP connection between `mc mirror` and `minio` was established
- Twice per second I saw packet exchange on said TCP connection (looks like a heartbeat), so `mc mirror` and `minio` had an established and working TCP connection.
- When uploading a file to the `ams1` minio instance (or deleting a file) I saw a larger JSON document sent to `mc mirror` on that TCP connection
- I saw a constant flow of TCP ACKs going back to `minio`, so `mc mirror` must have processed those heartbeats and JSON status updates, but somehow failed to do anything further.

Do you need any further information? Should I run `mc mirror` with the `--debug` option set?

**Comment by gcmsch** [comment] 2019-11-12 15:16
Just a quick update from my side: Running `mc mirror` with the `--debug` option set does not really produce any more information. Debug output simply stops after a few hours of operation. Nothing more than that.

**Comment by gcmsch** [comment] 2019-12-09 09:16
Any update on this issue? Do you need more information? A better test case?

**Comment by harshavardhana** [comment] 2019-12-09 09:34
This issue most probably gets fixed with all the recent updates that are going into mc

#2993
#2991
#2988

**Comment by harshavardhana** [comment] 2019-12-18 22:55
Closing this issue we have released server and mc - please upgrade and let us know if this is reproducible. Closing this as fixed for now.

**Closed as completed by harshavardhana** 2019-12-18 22:55 UTC
Labels: community, fixed, priority: medium
