### ISSUE TITLE
[web/rpc] Support Decentralized Browser Authentication

### ISSUE THREAD

**Issue by hernandev** [minio/minio#2748] opened 2016-09-20 22:34 UTC
## Expected behaviour

When having multiple minio instances load balanced not sharing the configuration directory across instances (on different servers/containers), minio browser JWT Token, once issued, should be valid against any server using the same api credentials (not sure what is being used as secret key at HS512). 
## Actual behaviour

The Browser JWT Token is not accepted on another server
## Steps to reproduce the behaviour

Create two isolated minio instances, using the same api credentials, load balance them and try to access minio browser

P.S. I need to do more testing and put some additional info here, don't mind this issue that much yet, since I'll validate it a little bit more soon.

**Comment by krishnasrinivas** [comment] 2016-09-21 07:20
@hernandev does the browser see same proxy IP:PORT for the backend minio servers? If so it should have worked, because the JWT is encrypted using S3  secret key which is shared by the backend minio servers and hence should be valid.
can you post the relevant portion of the reverse proxy config?

**Comment by harshavardhana** [comment] 2016-09-28 08:22
> @hernandev does the browser see same proxy IP:PORT for the backend minio servers? If so it should have worked, because the JWT is encrypted using S3 secret key which is shared by the backend minio servers and hence should be valid.
> can you post the relevant portion of the reverse proxy config?

Were you able to validate this @krishnasrinivas ?

**Comment by hernandev** [comment] 2016-09-28 18:59
Hey guys,  gonna take a few minutes later today to test it all again, and provide more details.

**Comment by harshavardhana** [comment] 2016-10-18 06:53
> Hey guys, gonna take a few minutes later today to test it all again, and provide more details.

@hernandev were you able to validate this on your end?

**Comment by harshavardhana** [comment] 2016-10-29 09:52
This issue seems to be reproducible.  Will verify what is going on.

**Comment by harshavardhana** [comment] 2016-11-03 00:48
So finally got a nginx configuration tested , seems to be working fine . Here is the load balanced nginx configuration.

Was able to take down nodes but the browser was properly authenticated all the time and worked transparently. 

```
user       www-data www-data;  ## Default: nobody                                                                                                 
worker_processes  5;  ## Default: 1                                                                                                               
error_log  /var/log/error.log;
worker_rlimit_nofile 8192;

events {
  worker_connections  4096;  ## Default: 1024                                                                                                     
}

http {
  upstream myproject {
    server 127.0.0.1:9001 weight=3;
    server 127.0.0.1:9002;
  }

  server {
    listen 80;
    server_name localhost;
    location / {
      proxy_set_header Host $http_host;
      proxy_pass http://myproject;
    }
  }
}
```

Going to close this bug @hernandev - if you happen to reproduce this issue again please re-open this issue.

**Closed as completed by harshavardhana** 2016-11-03 00:48 UTC
Labels: community
