### ISSUE TITLE
[resolved] Versioning support

### ISSUE THREAD

**Issue by 31z4** [minio/minio#2111] opened 2016-07-06 09:46 UTC
Would be great to have [versioning](http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html) support.

**Comment by GarimaKapoor** [comment] 2016-07-06 19:22
Its by design that we have kept versioning out of the server. You can look at [s3git project](https://github.com/s3git/s3git) for versioning, it works seamlessly with Minio and S3. You can follow  #1309 for more detailed discussion on why it's a better design to keep versioning out of server.

**Comment by harshavardhana** [comment] 2016-07-10 22:03
> Its by design that we have kept versioning out of the server. You can look at s3git project for versioning, it works seamlessly with Minio and S3. You can follow #1309 for more detailed discussion on why it's a better design to keep versioning out of server.

Closing..

**Comment by harshavardhana** [comment] 2020-01-22 22:00
We will be implementing versioning.

**Comment by dinobagio** [comment] 2020-02-14 14:15
Hi, do you have an ETA for this feature (i.e. versionning support)

**Comment by harshavardhana** [comment] 2020-02-14 14:21
> Hi, do you have an ETA for this feature (i.e. versionning support)

No ETA @dinobagio but soon!

**Comment by ghoeffner** [comment] 2020-02-16 23:32
As far as I understand, as soon as versioning is supported, owncloud should start working with minio as external storage as well.

**Comment by i0x71** [comment] 2020-04-16 23:42
Will there be an option to delete old version of data ?

**Comment by harshavardhana** [comment] 2020-04-16 23:43
> Will there be an option to delete old version of data ?

It will exactly similar to AWS S3 Versioning API @i0x71

**Comment by Skywrath-Mage** [comment] 2020-04-29 21:50
it would be very nice if we could easily set up versioning rules. like how long a version of a file should be kept.

**Comment by harshavardhana** [comment] 2020-04-29 22:03
> it would be very nice if we could easily set up versioning rules. like how long a version of a file should be kept.

As explained it is as per AWS S3 specs, if those specs have it it shall be implemented. Such as lifecycle deletes following versionid or object tags

**Comment by mohandass-pat** [comment] 2020-05-29 07:53
Hi. I'm trying versioning in Minio. Is it finished?

**Comment by darkdragon-001** [comment] 2020-06-12 07:52
@harshavardhana `xl` format is the distributed backend (in contrast to `fs` backend)? So this is a requirement for versioning support? (Makes sense IMHO, but I just want to verify).

How are different versions stored? Is the complete file replicated for each version or is some sort of diff format used? If so which one?

**Comment by vlcinsky** [comment] 2020-06-12 09:02
@darkdragon-001 If Minio is supposed to reflect S3 functionality, then the content of stored version shall be functional on its own without adding any extra burden with diffing or so. The S3 API allows to delete particular version and this would make the implementation too complex.

We are using versioning in AWS S3 buckets for years in huge scales (10 years of feeds storing 1440 versions of the same file a day).

Anyway, I am not member of minio team, so my comment is just an opinion.

**Comment by klauspost** [comment] 2020-06-12 09:24
@vlcinsky Correct. And this is also how it is implemented.

We looked at block based de-duplication (large scale diffs) but decided not to go for it mainly from a complexity standpoint.

**Closed as completed** 2020-06-13 03:04 UTC
Labels: community, fixed, priority: medium

**Comment by Cal30** [comment] 2020-06-16 11:25
Hi,
using 'master' branch where the PR is merged throws always 'Missing Content-MD5 header' error if using 'aws-sdk-java' dependency as they don't include that header when enabling/disabling versioning.

I've been checking your addings and I can see that for Minio is required. Usingin minio-client dependency works but I want to know if this feature could be reviewed or not.

Thanks in advance

**Comment by harshavardhana** [comment] 2020-06-16 14:59
> Hi,
> using 'master' branch where the PR is merged throws always 'Missing Content-MD5 header' error if using 'aws-sdk-java' dependency as they don't include that header when enabling/disabling versioning.
> 
> I've been checking your addings and I can see that for Minio is required. Usingin minio-client dependency works but I want to know if this feature could be reviewed or not.
> 
> Thanks in advance

Use it and report issues if you must . We would like community to use it.

NOTE: things may break, so don't put your real content just yet for testing.

**Comment by vlcinsky** [comment] 2020-07-12 18:49
Great. Today major release was announced and it includes versioning.

https://github.com/minio/minio/releases/tag/RELEASE.2020-07-11T06-07-16Z

Thanks a lot for this feature.
