### ISSUE TITLE
Reconsider disallowing use of mixed hardware platforms in cluster setup

### ISSUE THREAD

**Issue by noahwilliamsson** [minio/minio#12202] opened 2021-05-02 13:24 UTC
**Is your feature request related to a problem? Please describe.**

Since Nov, 2019, MinIO has a code-level check which blocks use of mixed hardware platforms (e.g. ARM64 and AMD64) in distributed setups.  In this case, MinIO would fail with the following error message:

> Expected platform 'OS: linux | Arch: arm64', found to be running 'OS: linux | Arch: amd64'

(see https://github.com/minio/minio/blob/RELEASE.2021-04-22T15-44-28Z/cmd/bootstrap-peer-server.go#L60-L63)

A question about this behavior was raised in #10089 (Can arm64 and amd64 hosts be used in the same cluster?), which was closed with "working as intended":

> it is not allowed - it is due to mainly performance differences in a distributed setup. amd64 >> arm64 unless you are using like graviton2 like ARM CPUs.
> Homogenous environments are more predictable to debug and fix issues.

This was just weeks after https://blog.min.io/intel_vs_gravitron/ had been posted (June, 2020), which noted that:

> [...] what is clear is that the ARM architecture, with the introduction of the Graviton2 processor by AWS, has closed the performance gap to Intel and even surpassed it for multi-core performance.

**Describe the solution you'd like**

Now I can totally understand your position that the use of mixed hardware platforms is neither recommended nor supported, but I'd like to ask you to reconsider actively _blocking_ such attempts in code.

Thus, I'd like to propose that the platform check is either dropped or relaxed (e.g. by merely issuing a warning about how it's not supported).

This would allow system administrators to make decisions on what hardware to use purely based on currently available hardware from a performance/cost perspective, independent of views held by developers' at some point in time.  For example, gradually replacing existing AMD64 cluster nodes with cheaper ARM64 equivalents.  Furthermore, it would allow hobbyists to experiment with distributed MinIO setups on mixed hardware platforms, with the Raspberry Pi being one of the most popular ARM64 platforms out there.

I'm going to open a PR shortly which drops this check but I'd be happy to change it (and relevant docs) to e.g. raise a warning about how it's not a supported configuration.

Thanks!

**Comment by harshavardhana** [comment] 2021-05-02 15:13
> This would allow system administrators to make decisions on what hardware to use purely based on currently available hardware from a performance/cost perspective, independent of views held by developers' at some point in time. For example, gradually replacing existing AMD64 cluster nodes with cheaper ARM64 equivalents. Furthermore, it would allow hobbyists to experiment with distributed MinIO setups on mixed hardware platforms, with the Raspberry Pi being one of the most popular ARM64 platforms out there.

No it is not expected @noahwilliamsson - for our production deployments this is unexpected. Serious deployments do not deploy in mixed hardware - there may be some niche cases where you lack homogenous hardware. But we didn't build MinIO for such usecases - we require that 

- CPU 
- Disk
- Network

To be of same vendor, same firmware and same performance metrics. MinIO's design is symmetric in nature i.e the slowest component in the system governs the overall performance on the system. 

This is why a homogeneous architecture is more predictable and keeps your mind at ease at scale. Going to close this as wont fix because this is a stretch for MinIO's design goals.

**Closed as completed by harshavardhana** 2021-05-02 15:13 UTC
Labels: community, out of scope

**Comment by klauspost** [comment] 2021-05-03 08:24
@noahwilliamsson  I propose you fork the project if this is something you want. We cannot guarantee that there isn't a subtle incompatibility between platforms, caused by either our or third party code. 

So it is not worth the additional risk for a feature that is suboptimal anyway. The support matrix will explode by the combination of platforms and we cannot allow a subtle bug in production code.

**Comment by furkanmustafa** [comment] 2021-11-21 04:33
I would say it's totally acceptable that minio doesn't support it. But actively blocking is different. If some setup is unsupported but a user is using it anyway, whatever problem happens there, can easily be considered "not a bug" / "won't fix". I guess minio wouldn't actively check network card firmware versions and deny operation depending on that.

**Comment by harshavardhana** [comment] 2021-11-21 09:46
> I would say it's totally acceptable that minio doesn't support it. But actively blocking is different. If some setup is unsupported but a user is using it anyway, whatever problem happens there, can easily be considered "not a bug" / "won't fix". I guess minio wouldn't actively check network card firmware versions and deny operation depending on that.

MinIO advocates best practices, if you do not wish to follow best practices you are allowed to fork the project and build it yourself for your needs. 

We will not change the enforcement of best practices. This issue is resolved.
