### ISSUE TITLE
[distributed] document distributed minio server in k8s

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3098] opened 2016-10-26 09:28 UTC
Running 4 servers (scaleway), those servers have 2 interface, one public, one private.
The public IP of the server is not directly assigned to to server but routed, anyway I'm using the private network so it should not have an influence.

I start a minio container on each server and expose **publicly** the port 9000, **no swarm, no docker network**.
From inside each container I can curl all the other ones on the port 9000 successfully.

The servers don't start and wait for 3 servers to be available.
On the same machines, running minio without docker works, the cluster get initialized.

**Comment by dcharbonnier** [comment] 2016-10-26 09:50
It's working if you add the option --net=host but it's still a problem

**Comment by harshavardhana** [comment] 2016-10-30 17:36
// cc @vadmeste

**Comment by dcharbonnier** [comment] 2016-10-31 10:33
the solution of putting the --net-host is not applicable for a swarm so it's still an issue and the net=host a 'temporary' solution

**Comment by vadmeste** [comment] 2016-10-31 10:37
> the solution of putting the --net-host is not applicable for a swarm so it's still an issue and the net=host a 'temporary' solution

Can you show us how you are running your docker instances? like are you running manually one docker instance in each of your server ?

**Comment by dcharbonnier** [comment] 2016-10-31 13:04
@vadmeste https://github.com/dcharbonnier/minio/tree/master/terraform/scaleway-distributed

**Comment by harshavardhana** [comment] 2016-11-09 20:51
This will be fixed by Kubernetes documentation - assigned to @NitishT

**Comment by dcharbonnier** [comment] 2016-11-15 10:40
I think there is a similar question on elastic and they addressed it using environment variables ,
check **Auto transport/http discovery with Swarm Mode** on https://hub.docker.com/r/itzg/elasticsearch/

**Comment by harshavardhana** [comment] 2016-11-21 05:02
Closing as duplicate of #2825

**Closed as completed by harshavardhana** 2016-11-21 05:02 UTC
Labels: community
