### ISSUE TITLE
Healing after node crash does not clean deleted objects

### ISSUE THREAD

**Issue by cracknel** [minio/minio#7428] opened 2019-03-26 12:59 UTC
## Expected Behavior
If a crashed node rejoins the cluster, healing should clean objects that have been deleted during downtime.

## Current Behavior
Parts of deleted objects are still on the node that went down during delete operations even after recursively healing.

## Possible Solution
Garbage collector?

## Steps to Reproduce (for bugs)
4 node cluster
create 10k objects in a bucket
stop one node
delete objects
start node
do recursive healing
check data on node that was put down

## Context
Testing the behavior of minio in different scenarios for a PoC.

## Your Environment

4 nodes started with:
export MINIO_ACCESS_KEY=admin
export MINIO_SECRET_KEY=adminadmin
./minio server http://minio{1...4}/home/alex.cucu/data

Version: 2019-03-20T22:38:47Z
Release-Tag: RELEASE.2019-03-20T22-38-47Z
Commit-ID: a9032b52b86d9d8a2b89ebbf47a50bc233565f3f

**Comment by nitisht** [comment] 2019-03-26 14:19
I think this is duplicate of https://github.com/minio/mc/issues/2713 . We can close this and follow updates there.

**Comment by kannappanr** [comment] 2019-03-26 16:38
@cracknel We have a PR #7407 that handles this scenario. As mentioned above, closing this issue now.

**Closed as completed by kannappanr** 2019-03-26 16:38 UTC
Labels: duplicate
