### ISSUE TITLE
Error from IDP: Key is of invalid type

### ISSUE THREAD

**Issue by AliMirlou** [minio/minio#15981] opened 2022-10-31 20:25 UTC
I have configured an IDP in a new MinIO SNSD linux instance.

## Expected Behavior
It is expected that the OAuth login would be successful and redirect me to the dashboard.

## Current Behavior
The login is unsuccessful with the following error:

![image](https://user-images.githubusercontent.com/19661419/199064339-d3005ce4-6b38-4426-bbff-8b0155b7274d.png)

## Steps to Reproduce
1. Installed the instance using [this link](https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-single-node-single-drive.html) for DEB distros.
2. Configured the authentication to use OpenID using [this link](https://min.io/docs/minio/linux/operations/external-iam/configure-openid-external-identity-management.html) by setting `MINIO_IDENTITY_OPENID_CONFIG_URL`, `MINIO_IDENTITY_OPENID_CLIENT_ID`, `MINIO_IDENTITY_OPENID_CLIENT_SECRET` and `MINIO_IDENTITY_OPENID_REDIRECT_URI` variables in the `/etc/default/minio` file.
3. The SSO login page shows in the console's login page and it correctly redirects me to the OAuth page and after that, it correctly redirects back to `/oauth_callback` route of the console with successful parameters (e.g. `userState=Authenticated`).

The IDP is an on-premise instance of [FusionAuth](https://fusionauth.io/) service. This is [the OpenID configuration link](https://fusion.roboepics.com/.well-known/openid-configuration) which is set in the MinIO config file.

## Context
We have a few integrated services and websites on different servers, so we installed FusionAuth to store and handle the authentication of our users across these services. 
Recently we needed a dedicated S3-compatible storage service in the system. So we installed a MinIO instance on a newly provisioned server.
Since we wanted our users to be able to access it, we needed MinIO to be accessed through FusionAuth too.

## Your Environment
* Version used (`minio --version`): `minio version RELEASE.2022-10-29T06-21-33Z (commit-id=d765b89a63c225ca271ef6d031a7bcc8fe9137df)`
* Server setup and configuration: Just an Nginx 1.18.0
* Operating System and version: Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-52-generic x86_64)

**Comment by harshavardhana** [comment] 2022-11-01 06:06
> The login is unsuccessful with the following error:
> 
> ![image](https://user-images.githubusercontent.com/19661419/199064339-d3005ce4-6b38-4426-bbff-8b0155b7274d.png)
> 
> ## Steps to Reproduce

This error indicates that the JWT sent by fusionauth is malformed.

**Comment by AliMirlou** [comment] 2022-11-01 09:06
I extracted the token from the MinIO trace logs when `AssumeRoleWithWebIdentity` request is being sent to the server and decoded and verified it.

![image](https://user-images.githubusercontent.com/19661419/199195828-aa8a050a-c11b-4965-a87f-8c3560c7d2c8.png)

![image](https://user-images.githubusercontent.com/19661419/199195605-c6d73a7a-36b6-4bb7-9547-a05c7e1357e1.png)

Everything seems to be correct!

Is there a specific requirement on the signing method or the key that I don't know about?
Right now, I'm using a default OpenID Connect compliant HMAC using SHA-256 key which uses the client secret to sign and verify the token.

**Comment by harshavardhana** [comment] 2022-11-01 15:08
Can you provide the output of openid configuration URL?

**Comment by AliMirlou** [comment] 2022-11-01 17:12
@harshavardhana Yeah.
```json
{
  "authorization_endpoint" : "https://fusion.roboepics.com/oauth2/authorize",
  "backchannel_logout_supported" : false,
  "claims_supported" : [
    "applicationId",
    "at_hash",
    "aud",
    "authenticationType",
    "birthdate",
    "c_hash",
    "email",
    "email_verified",
    "exp",
    "family_name",
    "given_name",
    "iat",
    "iss",
    "jti",
    "middle_name",
    "name",
    "nbf",
    "nonce",
    "phone_number",
    "picture",
    "preferred_username",
    "roles",
    "sub"
  ],
  "device_authorization_endpoint" : "https://fusion.roboepics.com/oauth2/device_authorize",
  "end_session_endpoint" : "https://fusion.roboepics.com/oauth2/logout",
  "frontchannel_logout_supported" : true,
  "grant_types_supported" : [
    "authorization_code",
    "password",
    "implicit",
    "refresh_token",
    "urn:ietf:params:oauth:grant-type:device_code"
  ],
  "id_token_signing_alg_values_supported" : [
    "ES256",
    "ES384",
    "ES512",
    "HS256",
    "HS384",
    "HS512",
    "RS256",
    "RS384",
    "RS512"
  ],
  "issuer" : "roboepics.com",
  "jwks_uri" : "https://fusion.roboepics.com/.well-known/jwks.json",
  "response_modes_supported" : [
    "form_post",
    "fragment",
    "query"
  ],
  "response_types_supported" : [
    "code",
    "id_token",
    "token id_token"
  ],
  "scopes_supported" : [
    "openid",
    "offline_access"
  ],
  "subject_types_supported" : [
    "public"
  ],
  "token_endpoint" : "https://fusion.roboepics.com/oauth2/token",
  "token_endpoint_auth_methods_supported" : [
    "client_secret_basic",
    "client_secret_post",
    "none"
  ],
  "userinfo_endpoint" : "https://fusion.roboepics.com/oauth2/userinfo",
  "userinfo_signing_alg_values_supported" : [
    "ES256",
    "ES384",
    "ES512",
    "RS256",
    "RS384",
    "RS512",
    "HS256",
    "HS384",
    "HS512"
  ]
}
```

**Comment by harshavardhana** [comment] 2022-11-02 19:41
Reproduced this via FusionAuth local deployment, verifying what this might be.

**Comment by harshavardhana** [comment] 2022-11-02 21:54
Okay the issue is your alg we expect that you use RS256, ES256 i.e assymetric keys for authentication - however you are using (default) to HS256 which is a hmac style.

This is a feature request for MinIO to support OpenID with HS algos.

**Comment by harshavardhana** [comment] 2022-11-02 22:12
So if you end up enabling the JWT to use RS keys then it will work fine with MinIO. Closing this as we are not planning to support HMAC based keys at the moment please enable RS/EC keys.

**Closed as completed by harshavardhana** 2022-11-02 22:12 UTC
Labels: working as intended, community

**Comment by AliMirlou** [comment] 2022-11-03 01:11
@harshavardhana Well it's fine to not support it but can you mention this in the documentation, so future people with a similar problem don't get confused?

**Comment by harshavardhana** [comment] 2022-11-03 03:44
> @harshavardhana Well it's fine to not support it but can you mention this in the documentation, so future people with a similar problem don't get confused?

we won't mention it, instead, we can support it #15993

**Comment by AliMirlou** [comment] 2022-11-03 08:27
The only reference to HMAC that I could find in the documentation was [here](https://min.io/docs/minio/linux/developers/java/API.html#common-exceptions).

**Comment by AliMirlou** [comment] 2022-11-04 10:10
@harshavardhana Oh, cool 👍!
