### ISSUE TITLE
update is not a minio sub-command. See minio --help

### ISSUE THREAD

**Issue by RooyeKhat** [minio/minio#8350] opened 2019-10-02 12:03 UTC
Hi
in new version when i try to update minio show this error 

can any one help me why this command is not working ?

Thanks

**Comment by nitisht** [comment] 2019-10-02 12:10
This command is deprecated, you can use `mc` to update MinIO cluster now, https://docs.min.io/docs/minio-admin-complete-guide.html#update

**Comment by kannappanr** [comment] 2019-10-02 13:11
@RooyeKhat Closing this issue as working as intended. Please use `mc` to update `MinIO` cluster

**Closed as completed by kannappanr** 2019-10-02 13:11 UTC
Labels: working as intended
