### ISSUE TITLE
[feature] Azure Gateway: Implement ListObjectParts

### ISSUE THREAD

**Issue by pauln** [minio/minio#5169] opened 2017-11-10 23:24 UTC
## Expected Behavior

`ListObjectParts` returns a list of parts which can be used to generate a subsequent `CompleteMultipartUpload` request

## Current Behavior

`ListObjectParts` always returns an empty list, as per Known Limitations list in Azure Gateway docs.

## Possible Solution

The `ListObjectParts` stub method in Azure Gateway has the comment `ListObjectParts - Use Azure equivalent GetBlockList`, suggesting that it may be possible to implement `ListObjectParts` using existing Azure API methods. 

## Context

While attempting to set up a `tusd` server which stores uploaded files on Azure, I came across Minio Azure Gateway and thought it seemed like a neat way to achieve this as `tusd` supports S3 (but doesn't currently support Azure).  However, `tusd` currently fails to complete the multipart upload as it relies on S3 to provide the list of parts.  I [raised an issue](https://github.com/tus/tusd/issues/156) with `tusd` to see if it was possible to track the parts there, but its architecture makes it infeasible to do so - especially if `tusd` is scaled horizontally (i.e. there are multiple instances of `tusd` potentially handling different chunks of the same upload).

## Your Environment

* Version used (`minio version`): RELEASE.2017-10-27T18-59-02Z
* Environment name and version (e.g. nginx 1.9.1): `minio/minio` Docker image

**Comment by krishnasrinivas** [comment] 2017-11-10 23:56
We will discuss this internally and get back to you @pauln

**Comment by krishnasrinivas** [comment] 2017-11-13 21:16
@pauln it is tricky to implement ListObjectParts on Azure:

Here is a sample response:
```
  <Part>
    <PartNumber>2</PartNumber>
    <LastModified>2010-11-10T20:48:34.000Z</LastModified>
    <ETag>"7778aef83f66abc1fa1e8477f296d394"</ETag>
    <Size>10485760</Size>
  </Part>
  <Part>
    <PartNumber>3</PartNumber>
    <LastModified>2010-11-10T20:48:33.000Z</LastModified>
    <ETag>"aaaa18db4cc2f85cedef654fccc4a4x8"</ETag>
    <Size>10485760</Size>
  </Part>
```

We won't be able to derive `LastModified` from Azure as it does not provide this info.

Also if there are two PutObjectPart with same part number, ListObjectParts will not be able to differentiate which is the latest part.

Also https://github.com/aws/aws-sdk-go/issues/1518 ListObjectParts should not be relied upon on Amazon S3.

**Comment by pauln** [comment] 2017-11-14 01:12
Thanks for looking into this, @krishnasrinivas.  Even if full parity with the S3 API method isn't possible, I think that a (properly documented) partial (but compatible) implementation would be helpful / better than no implementation.  I'll pass the note about ListObjectParts on to the `tusd` folks - but removing the reliance on ListObjectParts is not likely to be a simple or quick undertaking.

> Also if there are two PutObjectPart with same part number, ListObjectParts will not be able to differentiate which is the latest part.

Per the [remarks in the Azure API docs](https://docs.microsoft.com/en-us/rest/api/storageservices/get-block-list#remarks) (emphasis added):
> The list of uncommitted blocks is returned in alphabetical order. If a block ID has been uploaded more than once, **only the most recently uploaded block appears in the list**.

Since it'll only return the latest version of any uncommitted block/part, there shouldn't be any need to differentiate between versions of a block.  If/since this differs from S3, this should then be listed as a known limitation.


> We won't be able to derive LastModified from Azure as it does not provide this info.

Since (as above) Azure only returns the latest version of any given block/part, LastModified probably isn't especially useful.  I'd certainly be happy with it returning a fixed date/time for all parts, so long as it's also documented as a known limitation.

**Comment by krishnasrinivas** [comment] 2017-11-14 01:20
> Since it'll only return the latest version of any uncommitted block/part, there shouldn't be any need to differentiate between versions of a block. If/since this differs from S3, this should then be listed as a known limitation.

The problem is blockIDs will differ (because even though partNumber is same the ETag will be different)

> Since (as above) Azure only returns the latest version of any given block/part, LastModified probably isn't especially useful. I'd certainly be happy with it returning a fixed date/time for all parts, so long as it's also documented as a known limitation.

true.

What we can do is return error in ListObjectParts if different parts were uploaded for the same partNumber. Let me see if we hit any roadblock if we implement this.

**Comment by pauln** [comment] 2017-11-14 03:13
> The problem is blockIDs will differ (because even though partNumber is same the ETag will be different)

Ah, I hadn't realised that more than just the part number was being put into the `blockID`.  For the record, it's currently `fmt.Sprintf("%05d.%02d.%s.%s", partID, subPartNumber, uploadID, md5Hex)`.  Now that I'm aware of that, I have a follow up question: how much of the 64-byte maximum length is that using?  If there's enough space left, perhaps a timestamp of some sort could be fitted in to the `blockID` in order to be able to return the actual `LastModified` date/time - and thus which version of a block is the latest?

> Let me see if we hit any roadblock if we implement this.

Thanks for working on it!  If there's anything I can do to help (such as continuing to discuss potential issues and workarounds here, or pre-release testing), please let me know.

**Comment by krishnasrinivas** [comment] 2017-11-14 04:43
> If there's anything I can do to help (such as continuing to discuss potential issues and workarounds here, or pre-release testing), please let me know.

That would be great, can you test https://github.com/krishnasrinivas/minio/tree/azure-listparts and see if it works as expected?

**Comment by pauln** [comment] 2017-11-15 01:33
The implementation seems to work, @krishnasrinivas - though in testing it, I found that `tusd` fires off a `ListObjectParts` request before the first chunk is uploaded, which resulted in a 404 because `NewMultipartUpload` doesn't create a `BlockBlob` for the data (although it does create one for the metadata).

I've submitted a pull request to your `azure-listparts` branch which creates the empty `BlockBlob` in `NewMultipartUpload`; this change prevents the 404 and therefore allows `tusd` to get on with uploading the blocks.  The `ListObjectParts` request(s) which are made after blocks have been uploaded appear to then be sufficient for `tusd` to do its thing - uploads now complete.

**Comment by krishnasrinivas** [comment] 2017-11-15 01:44
OK great, I have merged it. Will wait for more tests from you.

**Comment by pauln** [comment] 2017-11-15 05:10
I've done a few tests via `tusd`, and haven't had any further issues after fixing the 404.  I don't really have the capacity to test for how it handles multiple versions of the same block - or other edge cases - at the moment, sorry.

**Comment by krishnasrinivas** [comment] 2017-11-16 19:42
Thanks @pauln for testing.

**Closed as completed** 2017-11-20 22:03 UTC
Labels: priority: medium

**Comment by nitisht** [comment] 2018-06-01 08:08
@pauln will it be possible to get in touch with you regarding couple of questions on your `tusd` deployment
