### ISSUE TITLE
Access Denied to Public Bucket

### ISSUE THREAD

**Issue by ryjo44** [minio/minio#8533] opened 2019-11-18 20:27 UTC
I am running minio through a docker container. There are a couple different buckets within and most are working fine, however, I'm getting errors when I try to look into one of them. I have confirmed that within the container the permissions on these files are identical to all of the others, and have made sure that the bucket's policy is "public."

## Expected Behavior

Expected behavior would be being able to access this bucket through minio. 

## Current Behavior

Currently unable to access this bucket through either the browser or command line client even after confirming that permissions within my docker container are consistent and that the bucket has a "public" policy.

## Steps to Reproduce (for bugs)

1. Minio container was started by mounting in a volume containing all data
2. Each bucket was chown-d to the user running minio within container (minio:minio)

This seems to be working fine for 4/5 buckets currently in my volume, but for some reason this one bucket isn't.

## Context

It seems like the data is still accessible through the web application. The problem is being able to interact with it outside of that. My team is attempting to restructure our backend which requires a new naming convention for our files in minio and I am unable to edit the files in this bucket.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

Version used: minio/minio:RELEASE.2019-08-21T19-40-07Z Docker image

**Comment by harshavardhana** [comment] 2019-11-18 23:01
Please upgrade to latest release and let us know if its reproducible @ryjo44

**Comment by ryjo44** [comment] 2019-11-19 16:33
I am getting the same issue using the latest stable release on docker hub @harshavardhana

**Comment by ryjo44** [comment] 2019-11-21 15:05
Bumping on this again

**Comment by harshavardhana** [comment] 2019-11-21 22:38
@ryjo44 are you sure your bucket has public read access? can you provide output of `mc policy list` ?

**Comment by ryjo44** [comment] 2019-11-22 12:36
`mc policy list` on the bucket returned empty. Through the browser, I can see that there is a policy where prefix "*" has read/write access.

I tried setting `mc policy public` on the bucket, but am still getting the `prefix access denied` error through the browser. @harshavardhana

**Comment by ryjo44** [comment] 2019-11-25 15:22
@harshavardhana confirmed that access to the bucket is set to "public" and that all prefixes should have r/w permissions, but I am still unable to access the files within the bucket from neither the web browser nor minio-client.

`(base) C02YN0KQJGH7:RMS ryancapps$ mc policy get minio/rms-dev-doc-files
Access permission for minio/rms-dev-doc-files is public
(base) C02YN0KQJGH7:RMS ryancapps$ mc policy list minio/rms-dev-doc-files
rms-dev-doc-files/* => readwrite`

**Comment by ryjo44** [comment] 2019-11-27 13:52
@harshavardhana

**Comment by harshavardhana** [comment] 2019-11-29 01:38
I tried reproducing this with the latest release @ryjo44 - I am not able to.

**Comment by kannappanr** [comment] 2019-12-01 14:13
Even with the version that you have initially suggested, here is what I see locally
```
$ mc mb myminio/test1
Bucket created successfully `myminio/test1`.
$ mc cp /etc/issue myminio/test1/prefix/issue
/etc/issue:                          26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 5.69 KiB/s 0s
$ mc policy set public myminio/test1
Access permission for `myminio/test1` is set to `public`
$ curl http://localhost:9000/test1/prefix/issue
Ubuntu 18.04.2 LTS \n \l
```

Here is the test done with `play`

```
$ mc policy get play/test1
Access permission for `play/test1` is `public`
$ mc policy list play/test1
test1/* => readwrite
$ mc cp /etc/issue play/test1
/etc/issue:    26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 311 B/s 0s
$ curl https://play.min.io:9000/test1/issue
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>issue</Key><BucketName>test1</BucketName><Resource>/test1/issue</Resource><Region>us-east-1</Region><RequestId>15DC440560530FED</$ mc policy get play/test1
Access permission for `play/test1` is `none`
$ mc policy set public play/test1
Access permission for `play/test1` is set to `public`
$ mc policy list play/test1
test1/* => readwrite
$ mc policy get play/test1
Access permission for `play/test1` is `public`
$ curl https://play.min.io:9000/test1/issue
Ubuntu 18.04.2 LTS \n \l
```

**Comment by ryjo44** [comment] 2019-12-02 14:19
Do either of you have any other ideas on what I might try? The permissions on my bucket look exactly the same as yours, but I am still unable to access the files within it from minio.

**Comment by ryjo44** [comment] 2019-12-02 18:42
@kannappanr getting the following when I tried to curl one of my files:
`error:1408F10B:SSL routines:ssl3_get_record:wrong version number`

Have you seen this before/do you think this may be causing the issue?

**Comment by harshavardhana** [comment] 2019-12-02 18:43
This is because your curl is trying to use TLS1.1 @ryjo44

**Comment by harshavardhana** [comment] 2019-12-11 04:08
Closing this as not a MinIO issue.

**Closed as completed by harshavardhana** 2019-12-11 04:08 UTC
Labels: working as intended, community, triage
