### ISSUE TITLE
duplicate directories

### ISSUE THREAD

**Issue by i0x71** [minio/minio#10888] opened 2020-11-12 19:32 UTC
Hi,
Not sure how this happened, but somehow i ended up with multiple duplicate directories
This is most likely a result of creating directories with mc mb and moving directories with mc mv

root@sandbox:~# mc ls dot9/sys
[2020-11-11 20:07:22 UTC]     0B configs/
[2020-11-12 19:21:34 UTC]     0B notes/
[2020-11-12 18:56:22 UTC]     0B scripts/
[2020-11-12 19:29:51 UTC]     0B configs/
[2020-11-12 19:29:51 UTC]     0B notes/
[2020-11-12 19:29:51 UTC]     0B scripts/

mc version RELEASE.2020-10-03T02-54-56Z
minio    Version: 2020-11-10T21:02:24Z

**Comment by harshavardhana** [comment] 2020-11-12 19:33
Closing as duplicate of #10881

**Closed as completed by harshavardhana** 2020-11-12 19:33 UTC
Labels: duplicate, community
