### ISSUE TITLE
Object name invalid

### ISSUE THREAD

**Issue by alpswjc** [minio/minio#3858] opened 2017-03-06 16:08 UTC
H there 

Key length is less than 1024, but still getting this error. 

time="2017-03-04T13:47:04-06:00" level=error msg="Unable to create an object." cause="Object name invalid: virginia#20170304/35-35/%e0%b8%a3%e0%b8%b2%e0%b8%84%e0%b8%b2+%e0%b8%95%e0%b8%b1%e0%b9%8b%e0%b8%a7%e0%b9%80%e0%b8%84%e0%b8%a3%e0%b8%b7%e0%b9%88%e0%b8%ad%e0%b8%87%e0%b8%9a%e0%b8%b4%e0%b8%99+%e0%b9%84%e0%b8%9b+%e0%b8%9f%e0%b8%b4%e0%b8%a5%e0%b8%b4%e0%b8%9b%e0%b8%9b%e0%b8%b4%e0%b8%99%e0%b8%aa%e0%b9%8c" source="[object-handlers.go:479:objectAPIHandlers.PutObjectHandler()]" stack="fs-v1.go:577:fsObjects.PutObject <autogenerated>:275:(*fsObjects).PutObject object-handlers.go:476:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm"

Please take a look 

Thanks

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
 2017-02-16T01:47:30Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
Ubuntu 16.04.2 LTS
* Link to your project:

**Comment by harshavardhana** [comment] 2017-03-06 18:39
> Key length is less than 1024, but still getting this error.

A key length in all operating systems is limited to by 255 characters per path component in a given path.  Here your path is 

```
echo "%e0%b8%a3%e0%b8%b2%e0%b8%84%e0%b8%b2+%e0%b8%95%e0%b8%b1%e0%b9%8b%e0%b8%a7%e0%b9%80%e0%b8%84%e0%b8%a3%e0%b8%b7%e0%b9%88%e0%b8%ad%e0%b8%87%e0%b8%9a%e0%b8%b4%e0%b8%99+%e0%b9%84%e0%b8%9b+%e0%b8%9f%e0%b8%b4%e0%b8%a5%e0%b8%b4%e0%b8%9b%e0%b8%9b%e0%b8%b4%e0%b8%99%e0%b8%aa%e0%b9%8c" | wc -c
274
```

Which is clearly longer than > 255 characters.   While Minio adheres to S3 behavior of 1024 it is the full flat key length inclusive of the backend nature on Linux and other operating systems. 

So if you really need long keys you need to split them like (each component is 255 in length)

```
255/255/255/255
```

**Comment by harshavardhana** [comment] 2017-03-06 19:50
Closing this as not a bug but an expected behavior.

**Closed as completed by harshavardhana** 2017-03-06 19:50 UTC
Labels: working as intended, community
