### ISSUE TITLE
MinIO gateway is crashing when deployed in Kubernetes with Azure backend

### ISSUE THREAD

**Issue by fmuyassarov** [minio/minio#13145] opened 2021-09-03 20:39 UTC
## Expected Behavior
Not crash

## Current Behavior
I'm running MinIO gateway as Kubernetes deployment with Azure being backend storage. However, MinIO pod is crashing immediately after writing some data to it. Or I expect it happens when it writes the data to Azure. If there is no data to write, MinIO pod keeps running fine. However, it crashes right after finishing writing data to Azure.  I can see that data has reached Azure storage but as said MinIO is crashing and gets restarted (pod is being recreated).

```
2021/09/03 20:08:23 http: panic serving 10.244.0.3:36298: Can't make a deep copy of the http.Request because at least one of the following is not nil:TransferEncoding, Form, PostForm, MultipartForm, or Trailer.
goroutine 232 [running]:
net/http.(*conn).serve.func1(0xc000659ae0)
	net/http/server.go:1804 +0x153
panic(0x2e36e60, 0x450e280)
	runtime/panic.go:971 +0x499
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0xc000f5b000, 0x45a0020, 0xc000bf7ea0)
	github.com/minio/minio/cmd/generic-handlers.go:532 +0x1ac
panic(0x2e36e60, 0x450e280)
	runtime/panic.go:965 +0x1b9
github.com/Azure/azure-pipeline-go/pipeline.Request.Copy(0xc000f5b700, 0x33d1987)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/request.go:79 +0x415
github.com/Azure/azure-storage-blob-go/azblob.(*storageError).Error(0xc000629400, 0xc000e01980, 0xc00140ce08)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:74 +0x505
github.com/Azure/azure-pipeline-go/pipeline.WriteRequestWithResponse(0xc000e01980, 0xc000f5b600, 0xc0009cbe60, 0x4548140, 0xc000629400)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/response.go:50 +0x1e2
github.com/Azure/azure-storage-blob-go/azblob.NewRequestLogPolicyFactory.func1.1(0x45ac948, 0xc000f113e0, 0xc000f5b600, 0x10, 0x2e51620, 0x1, 0xc000f75340)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_request_log.go:94 +0x508
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000629270, 0x45ac948, 0xc000f113e0, 0xc000f5b600, 0xc000f75428, 0xc0005cb770, 0x4d, 0xc000dd89c0)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.(*SharedKeyCredential).New.func1(0x45ac948, 0xc000f113e0, 0xc000f5b600, 0x5c596a0, 0x45ac948, 0xc000f113e0, 0xc0010f4a90)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_credential_shared_key.go:66 +0x2f4
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000e016e0, 0x45ac948, 0xc000f113e0, 0xc000f5b600, 0xc000f113e0, 0xc0010f4a90, 0x1, 0x0)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewRetryPolicyFactory.func1.1(0x45ac980, 0xc000e01410, 0xc000f5b500, 0x10, 0x2e51620, 0x64492d747301, 0xc000f751e0)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_retry.go:204 +0x69d
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0006292c0, 0x45ac980, 0xc000e01410, 0xc000f5b500, 0xc000f75298, 0x40db9b, 0xc0010f49c0, 0x10)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x45ac980, 0xc000e01410, 0xc000f5b500, 0x10, 0x2e51620, 0x40e201, 0xc000f751e0)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_unique_request_id.go:19 +0xae
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000f0adb0, 0x45ac980, 0xc000e01410, 0xc000f5b500, 0xc000f75280, 0x24, 0xc000e22060, 0xc00140d5b0)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0x45ac980, 0xc000e01410, 0xc000f5b500, 0x1, 0x0, 0x1, 0xc000f16298)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_telemetry.go:34 +0x162
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000e01710, 0x45ac980, 0xc000e01410, 0xc000f5b500, 0xc000e01710, 0x0, 0xc00140d680, 0x40e2f8)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc0002ee840, 0x45ac980, 0xc000e01410, 0x45504c0, 0xc000675ad0, 0xc000f5b500, 0x2c, 0xc001099180, 0x3b, 0x0)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:129 +0x82
github.com/Azure/azure-storage-blob-go/azblob.blobClient.GetProperties(0xc000e16280, 0x5, 0x0, 0x0, 0x0, 0xc000e16288, 0x2c, 0xc001099180, 0x3b, 0x0, ...)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zz_generated_blob.go:888 +0x3c5
github.com/Azure/azure-storage-blob-go/azblob.BlobURL.GetProperties(0xc000e16280, 0x5, 0x0, 0x0, 0x0, 0xc000e16288, 0x2c, 0xc001099180, 0x3b, 0x0, ...)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/url_blob.go:118 +0x132
github.com/minio/minio/cmd/gateway/azure.(*azureObjects).GetObjectInfo(0xc000e24000, 0x45ac980, 0xc000e01410, 0xc0005cb5e5, 0x9, 0xc0005cb5ef, 0x30, 0x0, 0x0, 0x0, ...)
	github.com/minio/minio/cmd/gateway/azure/gateway-azure.go:838 +0x1c5
github.com/minio/minio/cmd/gateway/azure.(*azureObjects).GetObjectNInfo(0xc000e24000, 0x45ac980, 0xc000e01410, 0xc0005cb5e5, 0x9, 0xc0005cb5ef, 0x30, 0x0, 0xc000e01230, 0x1, ...)
	github.com/minio/minio/cmd/gateway/azure/gateway-azure.go:778 +0x19f
github.com/minio/minio/cmd.objectAPIHandlers.getObjectHandler(0x418fda0, 0x418fd78, 0x45ac980, 0xc000e01410, 0x45f6730, 0xc00097e168, 0xc0005cb5e5, 0x9, 0xc0005cb5ef, 0x30, ...)
	github.com/minio/minio/cmd/object-handlers.go:409 +0xa55
github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler(0x418fda0, 0x418fd78, 0x45946b0, 0xc000659c20, 0xc000f5b200)
	github.com/minio/minio/cmd/object-handlers.go:573 +0x34d
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2049
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x45946b0, 0xc000659c20, 0xc000f5b200)
	github.com/minio/minio/cmd/handler-utils.go:372 +0x70
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2049
github.com/minio/minio/cmd.maxClients.func1(0x45946b0, 0xc000659c20, 0xc000f5b200)
	github.com/minio/minio/cmd/handler-api.go:165 +0x3a2
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2049
github.com/minio/minio/cmd.collectAPIStats.func1(0x45946b0, 0xc000659b80, 0xc000f5b200)
	github.com/minio/minio/cmd/handler-utils.go:387 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc000c32040, 0x45946b0, 0xc000659b80, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setRedirectHandler.func1(0x45946b0, 0xc000659b80, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:141 +0x91
net/http.HandlerFunc.ServeHTTP(0xc000f0ab88, 0x45946b0, 0xc000659b80, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.addCustomHeaders.func1(0x4594650, 0xc000f0acf0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:503 +0x174
net/http.HandlerFunc.ServeHTTP(0xc000f0aba0, 0x4594650, 0xc000f0acf0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.addSecurityHeaders.func1(0x4594650, 0xc000f0acf0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:516 +0x366
net/http.HandlerFunc.ServeHTTP(0xc000f0abb8, 0x4594650, 0xc000f0acf0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setBucketForwardingHandler.func1(0x4594650, 0xc000f0acf0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:435 +0xad
net/http.HandlerFunc.ServeHTTP(0xc000f0abd0, 0x4594650, 0xc000f0acf0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setRequestValidityHandler.func1(0x4594650, 0xc000f0acf0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:423 +0x459
net/http.HandlerFunc.ServeHTTP(0xc000f0abe8, 0x4594650, 0xc000f0acf0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setHTTPStatsHandler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:354 +0x104
net/http.HandlerFunc.ServeHTTP(0xc000f0ac00, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:54 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc000f0ac18, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:74 +0x1da
net/http.HandlerFunc.ServeHTTP(0xc000f0ac30, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x45537c0, 0xc000f0ac30, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/crossdomain-xml-handler.go:52 +0x82
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:173 +0xe8
net/http.HandlerFunc.ServeHTTP(0xc000f0ac48, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setReservedBucketHandler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:275 +0x258
net/http.HandlerFunc.ServeHTTP(0xc000f0ac60, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setTimeValidityHandler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:341 +0x3ef
net/http.HandlerFunc.ServeHTTP(0xc000f0ac78, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setAuthHandler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/auth-handler.go:491 +0xbf
net/http.HandlerFunc.ServeHTTP(0xc000f0ac90, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.setSSETLSHandler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:550 +0x74
net/http.HandlerFunc.ServeHTTP(0xc000f0aca8, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.filterReservedMetadata.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	github.com/minio/minio/cmd/generic-handlers.go:114 +0x1c8
net/http.HandlerFunc.ServeHTTP(0xc000f0acc0, 0x45a0020, 0xc000bf7ea0, 0xc000f5b200)
	net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000ad8000, 0x45a0020, 0xc000bf7ea0, 0xc000f5b000)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rs/cors.(*Cors).Handler.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b000)
	github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc000e144c0, 0x45a0020, 0xc000bf7ea0, 0xc000f5b000)
	net/http/server.go:2049 +0x44
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x45537c0, 0xc000e144c0, 0x45a0020, 0xc000bf7ea0, 0xc000f5b000)
	github.com/minio/minio/cmd/generic-handlers.go:535 +0x85
github.com/minio/minio/internal/http.(*Server).Start.func1(0x45a0020, 0xc000bf7ea0, 0xc000f5b000)
	github.com/minio/minio/internal/http/server.go:103 +0x258
net/http.HandlerFunc.ServeHTTP(0xc000e145a0, 0x45a0020, 0xc000bf7ea0, 0xc000f5b000)
	net/http/server.go:2049 +0x44
net/http.serverHandler.ServeHTTP(0xc0000d6b40, 0x45a0020, 0xc000bf7ea0, 0xc000f5b000)
	net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc000659ae0, 0x45ac980, 0xc000541c40)
	net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:2993 +0x39b
```
## Steps to Reproduce (for bugs)
Apply MinIO Deployment and its Service in Kubernetes with the following manifests
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: prow
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - gateway
        - azure
        - --console-address=:33333
        env:
        - name: MINIO_ROOT_USER
          value: "foo"
        - name: MINIO_ROOT_PASSWORD
          value: "abc"
        - name: MINIO_REGION_NAME
          value: minio
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: prow
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: minio

```
## Context
I'm running Kubernetes Prow CICD system on Kubernetes. And as for storage backend for MinIO I'm using Azure storage. In short, Prow system generates some logs which should eventually end up in Azure storage via MinIO. The reason for having MinIO is that Prow doesn't support Azure storage by default.  As such, we mimic S3 storage (which is supported by Prow) via MinIO. 

## Regression
No

## Your Environment

* Version used (`minio --version`): latest container image minio/minio:latest
* Kubernetes version: 1.21
* Operating System and version (`uname -a`): Linux est 5.10.0-1044-oem 46-Ubuntu SMP Wed Aug 11 09:50:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Manifest is shown above

**Comment by harshavardhana** [comment] 2021-09-03 20:44
Duplicate of https://github.com/minio/minio/issues/13101 - upstream azure SDK bug

**Closed as completed by harshavardhana** 2021-09-03 20:44 UTC
Labels: duplicate, community
