### ISSUE TITLE
[resolved] minio docker container can't run on aarch64 (ARM64) server

### ISSUE THREAD

**Issue by eugene-xie** [minio/minio#5345] opened 2018-01-03 05:27 UTC
## Expected Behavior
I would expect that the Minio Docker container can run on aarch64 server. 

## Current Behavior
I could pull minio/minio docker image from an aarch64 server, but it failed when I tried to ran the container from the aarch64 server. 

The error message is as following:
**$ docker run -p 9000:9000 minio/minio server /data**
panic: standard_init_linux.go:178: exec user process caused "no such file or directory" [recovered]
        panic: standard_init_linux.go:178: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x715400, 0x44201c0fc0)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x390
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0x442016f2d0)
        /home/buildslave/workspace/build-package/label/docker-jessie-arm64/work/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x2a0
panic(0x715400, 0x44201c0fc0)
        /usr/lib/go-1.7/src/runtime/panic.go:458 +0x4c0
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x442016ebf0, 0x4420076018, 0x442016ecf0)
        /home/buildslave/workspace/build-package/label/docker-jessie-arm64/work/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x150
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x44200df590, 0x8de9c0, 0x44201c0fc0)
        /home/buildslave/workspace/build-package/label/docker-jessie-arm64/work/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x458
main.glob..func8(0x44200eea00, 0x0, 0x0)
        /home/buildslave/workspace/build-package/label/docker-jessie-arm64/work/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x50
reflect.Value.call(0x6ffc60, 0x794c00, 0x13, 0x75f13b, 0x4, 0x442016f250, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/lib/go-1.7/src/reflect/value.go:434 +0xdac
reflect.Value.Call(0x6ffc60, 0x794c00, 0x13, 0x442016f250, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go-1.7/src/reflect/value.go:302 +0x88
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x6ffc60, 0x794c00, 0x44200eea00, 0x0, 0x0)
        /home/buildslave/workspace/build-package/label/docker-jessie-arm64/work/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x1d4
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x75f30b, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7707ec, 0x51, 0x0, ...)
        /home/buildslave/workspace/build-package/label/docker-jessie-arm64/work/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xd0c
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0x4420130000, 0x44200c6060, 0x2, 0x2, 0x0, 0x0)
        /home/buildslave/workspace/build-package/label/docker-jessie-arm64/work/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x830
main.main()
        /home/buildslave/workspace/build-package/label/docker-jessie-arm64/work/_build/src/github.com/opencontainers/runc/main.go:132 +0xbb8

## Possible Solution
The possible solution, and the one that I suggest, is to make the docker image multi-arch.  

## Steps to Reproduce (for bugs)
precondition, you have got a aarch64 server/VM. (if you don't have one, you may request one from packet.net by filing a new issue at: https://github.com/WorksOnArm/cluster/issues/new) and from that machine, run the following:
1. docker pull minio/minio
2. docker run -p 9000:9000 minio/minio server /data

## Your Environment

* the stable Mino docker image. 
* aarch64 sever
* Linux wls-arm 4.12.0-222-arm64 #1 SMP Debian 4.12.0.linaro.222-1 (2017-08-01) aarch64 GNU/Linux

**Comment by harshavardhana** [comment] 2018-01-03 05:33
Docker image is not multi-arch since we never really test on aarch64 or arm platforms.  Our current tested platforms are 

- x86_64 Linux
- x86_64 Windows
- x86_64 MacOS

For the rest of the OS and Architectures you will have to compile from source.  Currently we do not have any plans on officially building images for other architectures.

**Comment by eugene-xie** [comment] 2018-01-03 05:53
Thanks for your prompt reply!
I did a bit more search and found that Ed has reported the same issue: https://github.com/minio/minio/issues/3864, and there is already **edge-aarch64** tag for aarch64. [minio tags](https://hub.docker.com/r/minio/minio/tags/), which is very good. Just need one more step to make it multi-arch. 

I understand there is no plan to build images for other arch at the moment. It's OK to close this issue and I will watch [#3864](https://github.com/minio/minio/issues/3864)

**Comment by harshavardhana** [comment] 2018-01-03 05:59
> Thanks for your prompt reply!
> I did a bit more search and found that Ed has reported the same issue: #3864, and there is already edge-aarch64 tag for aarch64.
> minio tags/, which is very good. Just need one more step to make it multi-arch.
> 
> I understand there is no plan to build images for other arch at the moment. It's OK to close this issue and I will watch #3864

We used to build but we couldn't test / vet on these platforms, so just building a binary which is not well tested didn't make sense for us to be part of a release.  master branch is always release ready and kept atleast compile on multiple platforms so that users can self build.

**Comment by eugene-xie** [comment] 2018-01-03 06:10
Could you help me understand what difficulties you have to test on AArch64 platform? We will see how we can get help from community.

**Comment by harshavardhana** [comment] 2018-01-03 06:25
> Could you help me understand what difficulties you have to test on AArch64 platform?

Difficulty is not many requirements from the community, In-fact that was the reason we did initially the build to see how popular the aarch64 platforms are.  From what we have seen most of Minio users use Intel platforms.  With new processors with AVX512 instructions on Intel we are seeing very high raw performance for erasure coding, checksum [sha256](https://github.com/minio/sha256-simd#performance).

If there is a good need i.e comparable to Intel platforms we would definitely add it as part of our testing cycle. But for now there doesn't seem to be much interest.

**Comment by kannappanr** [comment] 2018-01-03 20:23
Closing this issue now. Please re--open the issue if you have further questions.

**Closed as completed by kannappanr** 2018-01-03 20:23 UTC
Labels: fixed

**Comment by amiga23** [comment] 2020-03-28 14:52
2 years have passed, more aarch64 SBCs are on the market and are more powerful. Please reevaluate community interest.

**Comment by harshavardhana** [comment] 2020-03-28 16:51
Binaries are available now, for now build your own containers.

**Comment by amiga23** [comment] 2020-03-29 08:00
Okay, the binaries are a bit hidden but I found them. Have it running in k3s on odroid-n2 + -c2 and created some backups with restic, works like a charm.

**Comment by kellyhair** [comment] 2020-04-14 16:23
> 2 years have passed, more aarch64 SBCs are on the market and are more powerful. Please reevaluate community interest.

AWS is about to launch [Gravitron2 instances](https://aws.amazon.com/ec2/instance-types/m6/). 
+1 on putting back onto the radar.

**Comment by kellyhair** [comment] 2020-04-15 14:56
If anyone needs the container, it will be available @ registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest within next hour/whenever build completes.

I built an empty container & it worked fine:

> docker run -it registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest
> Unable to find image 'registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest' locally
> latest: Pulling from gitlab-com/alliances/aws/sandbox-projects/minio-arm64
> f07e4bcf42b8: Pull complete 
> Digest: sha256:3544a3ca80e4c4e3a55f905310b279a03fccd42b30c1ec26f79f6fda9797dfb0
> Status: Downloaded newer image for registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest
> 
> / # uname -a
> Linux fc49b5204b76 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:18:09 UTC 2020 aarch64 Linux

**Comment by kellyhair** [comment] 2020-04-15 15:29
and.. ready for testing

>  docker run -it registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest
> Unable to find image 'registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest' locally
> latest: Pulling from gitlab-com/alliances/aws/sandbox-projects/minio-arm64
> f07e4bcf42b8: Pull complete 
> 7350706f2210: Pull complete 
> b4312a5de97c: Pull complete 
> 1ec2e1057914: Pull complete 
> 8d73007448d8: Pull complete 
> Digest: sha256:437a20fa0fabdf75f2cab93a8cdf0387261f648f34fa1b886b7ce63c73e2b229
> Status: Downloaded newer image for registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest
> NAME:
>   minio - High Performance Object Storage
> 
> DESCRIPTION:
>   Build high performance data infrastructure for machine learning, analytics and application data workloads with MinIO
> 
> USAGE:
>   minio [FLAGS] COMMAND [ARGS...]
> 
> COMMANDS:
>   server   start object storage server
>   gateway  start object storage gateway
>   
> FLAGS:
>   --certs-dir value, -S value  path to certs directory (default: "/root/.minio/certs")
>   --quiet                      disable startup information
>   --anonymous                  hide sensitive information from logging
>   --json                       output server logs and startup information in json format
>   --help, -h                   show help
>   --version, -v                print the version
>   
> VERSION:
>   DEVELOPMENT.2020-04-15T14-58-37Z

**Comment by rjelbert** [comment] 2020-09-13 19:55
> and.. ready for testing
> 
> > docker run -it registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest
> > Unable to find image 'registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest' locally
> > latest: Pulling from gitlab-com/alliances/aws/sandbox-projects/minio-arm64
> > f07e4bcf42b8: Pull complete
> > 7350706f2210: Pull complete
> > b4312a5de97c: Pull complete
> > 1ec2e1057914: Pull complete
> > 8d73007448d8: Pull complete
> > Digest: sha256:437a20fa0fabdf75f2cab93a8cdf0387261f648f34fa1b886b7ce63c73e2b229
> > Status: Downloaded newer image for registry.gitlab.com/gitlab-com/alliances/aws/sandbox-projects/minio-arm64:latest
> > NAME:
> > minio - High Performance Object Storage
> > DESCRIPTION:
> > Build high performance data infrastructure for machine learning, analytics and application data workloads with MinIO
> > USAGE:
> > minio [FLAGS] COMMAND [ARGS...]
> > COMMANDS:
> > server   start object storage server
> > gateway  start object storage gateway
> > FLAGS:
> > --certs-dir value, -S value  path to certs directory (default: "/root/.minio/certs")
> > --quiet                      disable startup information
> > --anonymous                  hide sensitive information from logging
> > --json                       output server logs and startup information in json format
> > --help, -h                   show help
> > --version, -v                print the version
> > VERSION:
> > DEVELOPMENT.2020-04-15T14-58-37Z

Looking good on a Raspberry Pi 4 8GB running the 64bit beta Raspberry Pi OS. When it runs it reports it is a week out of date so just checking how often it will be updated. I can go back to building from source if this was a one off test. 
I'm keen to get it working in distributed mode across our RPi cluster hence these tests. Thanks.

**Comment by kellyhair** [comment] 2020-09-14 17:54
Hey @rjelbert -

I had added the pipeline for some work I was doing for supporting GitLab on the AWS Graviton2 CPUs. 

As I'm leaving GitLab, and is on the work account, this image may fall out of date after my departure. That said, I noticed there was an issue in the Dockerfile. I fetched the new Dockerfile from Dockerhub and have confirmed it is working until the Dockerfile is updated again. In the meanwhile. I set up a scheduled/cron job to build weekly.

**Comment by harshavardhana** [comment] 2020-09-14 18:02
https://hub.docker.com/layers/minio/minio/RELEASE.2020-09-10T22-02-45Z-arm64/images/sha256-0f0d434834dec348c39bb83c3e29b4312cd89ceb1b6cd300dd88d8b0e7520fb2?context=explore ARM64 containers are officially available here.

**Comment by kellyhair** [comment] 2020-09-15 14:39
Thanks for the heads up @harshavardhana. Glad to see there's official Arm support now!

**Comment by alexellis** [comment] 2020-11-18 10:02
@harshavardhana are there any plans to use multi-arch manifests? I checked and the latest tag seems to point directly to AMD64. Pushing a manifest tag would be really helpful to our OpenFaaS community.

**Comment by harshavardhana** [comment] 2020-11-20 00:34
> @harshavardhana are there any plans to use multi-arch manifests? I checked and the latest tag seems to point directly to AMD64. Pushing a manifest tag would be really helpful to our OpenFaaS community.

The latest release now has support for multiarch manifests @alexellis  - please let your community know and start testing it.

**Comment by alexellis** [comment] 2020-11-20 07:57
Thank you 👍
