### ISSUE TITLE
How to permit s3/ListMultipartUploads to a readonly user

### ISSUE THREAD

**Issue by funkypenguin** [minio/minio#7182] opened 2019-01-31 18:39 UTC
Hi folks,
I'm trying to expose a bucket to a read-only user, with enough permissions to list and download objects. I created the user as "readonly", and applied the "download" policy to my bucket:

```
root@node1:/docker/minio# mc policy list minio/media --recursive
media/* => readonly
root@node1:/docker/minio# mc admin user list minio
enabled   spiderman             readonly
root@node1:/docker/minio#
```

## Expected Behavior
User uses goofys to mount bucket, using ```./goofys-latest --f -debug_s3 --debug_fuse --endpoint=https://MYMINIOURL media /tmp/banana``` 

## Current Behavior
Bucket mounts, but the following error is displayed:
```
2019/02/01 07:05:11.393324 s3.DEBUG DEBUG: Request s3/ListMultipartUploads Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /media?uploads= HTTP/1.1
Host: MIMINIOURL
User-Agent: aws-sdk-go/1.8.25 (go1.9.2; linux; amd64)
Accept-Encoding: identity


-----------------------------------------------------
2019/02/01 07:05:11.394513 fuse.DEBUG Op 0x00000001        connection.go:396] <- init
2019/02/01 07:05:11.394534 fuse.DEBUG Op 0x00000001        connection.go:479] -> OK ()
2019/02/01 07:05:11.394549 main.INFO File system has been successfully mounted.
2019/02/01 07:05:11.613239 s3.DEBUG DEBUG: Response s3/ListMultipartUploads Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 403 Forbidden
<snip>
2019/02/01 07:05:11.613274 s3.DEBUG DEBUG: Validate Response s3/ListMultipartUploads failed, not retrying, error AccessDenied: Access Denied.
	status code: 403, request id: 157F0103874262B8, host id:
```

Further, while this technically works on goofys, other S3-mounting tools fail altogether because of the 403.

## Possible Solution

I create to create this policy and assign to the user, but the result is unchanged:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::media/*"
      ],
      "Sid": ""
    },
    {
      "Action": [
	"s3:ListBucket",
	"s3:ListMultipartUploadParts",
	"s3:ListBucketMultipartUploads"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::media"
      ],
      "Sid": ""
    }
  ]
}
```

## Context

My goal here is to provide a way to share read-only data with authenticated users. I encourage them to use an S3-mounting library to mount the bucket locally on either Linux (goofys) or Windows (something else)

## Your Environment

* Version used (`minio version`):
```
/ # minio version
Version: 2019-01-23T23:18:58Z
Release-Tag: RELEASE.2019-01-23T23-18-58Z
Commit-ID: bd25f31100f44646cffae99dfec23179366593e2
/ #
```
* Environment name and version (e.g. nginx 1.9.1): Docker version 18.09.0, build 4d60db4 on Ubuntu Xenial 1604

Any ideas?
Thanks!
D

**Comment by kannappanr** [comment] 2019-01-31 20:44
@funkypenguin Will try to reproduce the issue described here and get back to you with further questions.

**Comment by eco-minio** [comment] 2019-02-05 21:02
@funkypenguin It looks like there is no authorization header for the requests by goofys.  Compare the request below to the one you shared:

```
---[ REQUEST POST-SIGN ]-----------------------------
HEAD /media/421q6khf3e3e4zrcl2usv6m0fko2bu26 HTTP/1.1
Host: localhost:9000
User-Agent: aws-sdk-go/1.8.25 (go1.10.4; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=minio/20190205/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=abd24e839cc6c31cf735f5d6b3e28b696bcc055cc7957abf2173b27c55a80abe
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20190205T205443Z
```
For some reason it looks like goofys is not picking up the credentials from `~/.aws/credentials`.  Try adding `--profile default` to the goofys mount command and let us know if it works after.

**Comment by kannappanr** [comment] 2019-02-06 23:15
@funkypenguin Did you get a chance to try out the suggestion from @eco-minio ?

**Comment by funkypenguin** [comment] 2019-02-06 23:24
Hey @kannappanr, goofys _must_ be adding the authorization header, since if I specify invalid credentials in ~/.aws/credentials, the entire mount request fails. As it stands, the R/O mount works perfectly in goofys, aside from the 403 in debug mode.

The issue seems to be more that the 403 is breaking _other_ S3-based mounting tools, and goofys is somehow immune. (I guess, goofys doesn't _care_ that it can't list ListMultipartUploads).

My question is more re how I can permit the ListMultipartUploads to my read-only using using a canned policy. The examples I gave above don't seem to alter the behaviour.

Thanks!
D

**Comment by kannappanr** [comment] 2019-02-07 22:17
@funkypenguin With your policy, the user created has access to `ListMultipartUploadParts` I was able to verify it using `aws-sdk-go` sdk. 

Also, as suggested by @eco-minio, adding the flag, `--profile default` adds the authorization header. Without that, it is not adding the authorization header.

Please try `./goofys --f --profile default -debug_s3 --debug_fuse --endpoint=http://localhost:9000 media /tmp/goofys/mount_folder`

**Comment by kannappanr** [comment] 2019-02-11 23:13
@funkypenguin Closing this as answered. Please feel to re-open if the suggestion does not work for you.

**Closed as completed by kannappanr** 2019-02-11 23:13 UTC
Labels: working as intended, community, priority: medium
