### ISSUE TITLE
XL: complete-multipart-upload of large file timesout (20th)

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1558] opened 2016-05-09 12:00 UTC
```
azureuser@minio-test:/mnt$ mc --debug session resume CPUYxaFa                                                                                                                                               200gfile:                           200.00 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00 % 61.88 MB0 mc: <ERROR> Failed to copy ‘200gfile’. Post http://127.0.0.1:9000/test1/200gfile?uploadId=9300be63-7064-49b2-b057-f5be367245ca: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

It timesout because of the renames.

**Comment by krishnasrinivas** [comment] 2016-05-09 12:19
Observing backend indicates that rename has all completed, just that the client timedout.

**Comment by harshavardhana** [comment] 2016-05-09 18:44
> Observing backend indicates that rename has all completed, just that the client timedout.

That is because of the go-routine and waitgroup.

**Comment by harshavardhana** [comment] 2016-05-18 01:06
Is this still reproducible?

**Comment by GarimaKapoor** [comment] 2016-05-18 01:28
Krishna please update the timeline.

**Comment by krishnasrinivas** [comment] 2016-05-18 04:28
@harshavardhana yes, @GarimaKapoor done

**Comment by krishnasrinivas** [comment] 2016-05-27 22:45
@harshavardhana this can be closed now, you fix of merging xl and object-layer also fixed this.

**Comment by harshavardhana** [comment] 2016-05-27 23:25
> @harshavardhana this can be closed now, you fix of merging xl and object-layer also fixed this.

Closing..

**Closed as completed by harshavardhana** 2016-05-27 23:25 UTC
