### ISSUE TITLE
Is there any possible to set policy to only to particular user?Or If i want to set the policy is that possible to set from minio client installed in other than the server host machine ??

### ISSUE THREAD

**Issue by akb2017** [minio/minio#4069] opened 2017-04-07 16:42 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by krishnasrinivas** [comment] 2017-04-07 17:31
@akb2017 can you format the issue properly? You have put everything in the subject line.

> Is there any possible to set policy to only to particular user?

The policy is at `bucket/prefix` level. One minio instance is tied to one access/secret key.

> If i want to set the policy is that possible to set from minio client installed in other than the server host machine ?

Yes.

**Comment by akb2017** [comment] 2017-04-07 17:36
Actually my issue is if the minio server is used by many clients,then  how to make it private ?
Is there any way to set policy to that particular minio client?

**Comment by akb2017** [comment] 2017-04-07 17:38
If possible how to do that ?

**Comment by krishnasrinivas** [comment] 2017-04-07 19:34
You will have to launch separate minio instances for each tenant.

If minio is used by an application, the application will itself have multiple users and application controls access to minio objects using [presigned-url](http://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURL.html)

**Comment by harshavardhana** [comment] 2017-04-08 08:25
Can you fix the title of the issue @akb2017 ? and also fill in the details of the issue template - it is always a good practice to follow issue template for us to help you better.

**Comment by harshavardhana** [comment] 2017-04-08 08:27
Moving the issue as working as intended.

**Comment by harshavardhana** [comment] 2017-04-10 18:47
Closing this issue as well as answered.

**Closed as completed by harshavardhana** 2017-04-10 18:47 UTC
Labels: working as intended, priority: low, community
