### ISSUE TITLE
Can't delete an object anonymously via MinIO Browser when Bucket Policy is set to Read and Write on MinIO Browser

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#9410] opened 2020-04-22 00:05 UTC
When a user tries to delete an object anonymously via MinIO Browser from a bucket whose policy has been set to Read/Write on MinIO Browser, they are not able to do so.

## Expected Behavior

As Read/Write implies, the user should be able to delete an object anonymously on MinIO Browser when the bucket policy has been set to Read and Write.

## Current Behavior

A user can't delete an object anonymously on MinIO Browser when the bucket policy has been set to Read and Write from MinIO Browser.

## Possible Solution

We might want to check how the Delete Object request is being sent and processed on the MinIO Browser when a user tries to delete the object anonymously for buckets with Read and Write policy

## Steps to Reproduce (for bugs)

1. Create a bucket via MinIO Browser
2. Upload an object to the bucket
3. Set the bucket policy to be Read/Write for all prefixes as follows:
<img width="624" alt="Screen Shot 2020-04-21 at 5 02 35 PM" src="https://user-images.githubusercontent.com/27314853/79926519-f9d40480-83f1-11ea-816e-561c82b95506.png">
4. Access the bucket from a private tab and try deleting the object
5. Verify that the `We encountered an internal error, please try again.` error message is shown on the browser and the following error is printed on the terminal window where `minio` runs:
```
API: WebRemoveObject(bucket=tet)
Time: 16:43:18 PDT 04/21/2020
DeploymentID: 3a62d2d7-96c5-4f3d-b54d-412d281b90be
RemoteHost: ::1
Host: localhost:9000
UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
Error: Do not have enough permissions to access this resource
       5: github.com/minio/minio@/cmd/api-errors.go:1825:cmd.toAPIErrorCode()
       4: github.com/minio/minio@/cmd/api-errors.go:1850:cmd.toAPIError()
       3: github.com/minio/minio@/cmd/web-handlers.go:2267:cmd.toWebAPIError()
       2: github.com/minio/minio@/cmd/web-handlers.go:2137:cmd.toJSONError()
       1: github.com/minio/minio@/cmd/web-handlers.go:744:cmd.(*webAPIHandlers).RemoveObject()
```

## Context

This might be unintuitive for users who are trying to delete an object anonymously when the policy has been set to Read and Write

## Regression

Yes, the issue seems to have started with the 04-10-2020 release.

## Your Environment

* Version used (`minio version`): latest
* Environment name and version (e.g. nginx 1.9.1): play.min.io
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by ebozduman** [comment] 2020-04-22 16:36
This is a regression due to retention change PR #9259 (fix: support object-remaining-retention-days policy condition).
I'll talk to @harshavardhana  and @kannappanr about what we would like to do it at this point.

**Comment by ebozduman** [comment] 2020-04-23 12:29
The issue was introduced with the `fix for #9259: support object-remaining-retention-days policy condition` almost 2 weeks ago.
I talked to @harshavardhana about the regression and decided to address the problem for both anonymous and authenticated users.

**Comment by ebozduman** [comment] 2020-05-21 16:23
Fixed. Closing...

**Closed as completed by ebozduman** 2020-05-21 16:23 UTC
Labels: community, fixed, regression (fixed)
