### ISSUE TITLE
ARM64 : Minio server crashes randomly 

### ISSUE THREAD

**Issue by kattakarthik** [minio/minio#8005] opened 2019-07-31 13:51 UTC
Minio server is terminating randomly on ARM64 platform. Built the latest code on ARM64 platform and used for testing.The deployment type is "distributed mode". 
In a week testing on 6 nodes, 3 servers crashed. 
The load was moderate when these crashes happened.

Log messages ::
-------------------------------------------------------------------------------------------
goroutine 338370336 [IO wait]:
runtime.gopark(0x1821768, 0xfffe25850a98, 0x4001841b02, 0x5)
       /usr/local/go/src/runtime/proc.go:301 +0xf0 fp=0x40042fc9c0 sp=0x40042fc9a0 pc=0x43cf50
runtime.netpollblock(0xfffe25850a70, 0x72, 0x409266a000)
       /usr/local/go/src/runtime/netpoll.go:389 +0xa4 fp=0x40042fca00 sp=0x40042fc9c0 pc=0x4385f4
internal/poll.runtime_pollWait(0xfffe25850a70, 0x72, 0xffffffffffffffff)
       /usr/local/go/src/runtime/netpoll.go:182 +0x48 fp=0x40042fca30 sp=0x40042fca00 pc=0x437b48
internal/poll.(*pollDesc).wait(0x408b030818, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
       /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xa0 fp=0x40042fca60 sp=0x40042fca30 pc=0x493fc0
internal/poll.(*pollDesc).waitRead(...)
       /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x408b030800, 0x409266a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
       /usr/local/go/src/internal/poll/fd_unix.go:169 +0x170 fp=0x40042fcac0 sp=0x40042fca60 pc=0x494e40
net.(*netFD).Read(0x408b030800, 0x409266a000, 0x1000, 0x1000, 0x40042fcb78, 0x413008, 0x40042fcb60)
       /usr/local/go/src/net/fd_unix.go:202 +0x44 fp=0x40042fcb20 sp=0x40042fcac0 pc=0x598c14
net.(*conn).Read(0x4031f50158, 0x409266a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
       /usr/local/go/src/net/net.go:177 +0x5c fp=0x40042fcb80 sp=0x40042fcb20 pc=0x5ab42c
net/http.(*persistConn).Read(0x408dc807e0, 0x409266a000, 0x1000, 0x1000, 0x40042fcc68, 0x6c2f30, 0x405fa8c840)
       /usr/local/go/src/net/http/transport.go:1524 +0x60 fp=0x40042fcc00 sp=0x40042fcb80 pc=0x6c1da0
bufio.(*Reader).fill(0x4004105a40)
       /usr/local/go/src/bufio/bufio.go:100 +0x100 fp=0x40042fcc50 sp=0x40042fcc00 pc=0x4b0000
bufio.(*Reader).Peek(0x4004105a40, 0x1, 0x0, 0x0, 0x1, 0x400d6c5600, 0x0)
       /usr/local/go/src/bufio/bufio.go:138 +0x40 fp=0x40042fcc70 sp=0x40042fcc50 pc=0x4b0180
net/http.(*persistConn).readLoop(0x408dc807e0)
       /usr/local/go/src/net/http/transport.go:1677 +0x16c fp=0x40042fcfd0 sp=0x40042fcc70 pc=0x6c282c
runtime.goexit()
       /usr/local/go/src/runtime/asm_arm64.s:1128 +0x4 fp=0x40042fcfd0 sp=0x40042fcfd0 pc=0x46aa74
created by net/http.(*Transport).dialConn
       /usr/local/go/src/net/http/transport

## Expected Behavior
Minio server shouldn't terminate.

## Current Behavior
Minio server terminates.

## Your Environment

* Version used (`minio version`):
Minio (built from source on ARM64 platform)
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET

* Operating System and version (`uname -a`):
aarch64 aarch64 aarch64 GNU/Linux

**Comment by vadmeste** [comment] 2019-07-31 15:25
@kattakarthik, the stack trace that you pasted is not the one which caused the crash, can you paste all the logs that you can find ?

**Comment by kattakarthik** [comment] 2019-08-01 06:19
[minio_log.txt](https://github.com/minio/minio/files/3455168/minio_log.txt)

Here is the complete log.. Hope it helps to root cause the issue @kannappanr

**Comment by vadmeste** [comment] 2019-08-01 10:42
Most likely, a C dependency is causing the issue in ARM64

**Comment by kattakarthik** [comment] 2019-08-01 10:49
Do you have any suggestions for us to try ?

**Comment by vadmeste** [comment] 2019-08-01 11:29
@kattakarthik did you enable compression or encryption in your Minio setup ?

**Comment by kattakarthik** [comment] 2019-08-01 11:47
@vadmeste  We just built the binary from source and ran it on arm64. Didn't change any default config.

**Comment by kattakarthik** [comment] 2019-08-01 11:59
The binary was built on one machine and same is used across all machiens. The other machines don't have Go installed on them.  Is it required to have Go installed on all machienes ??

In a week testing 3 out of 6 server instances terminated with this error..

**Comment by harshavardhana** [comment] 2019-08-01 13:00
@kattakarthik can you build MinIO binary with CGO_ENABLED=0 ?

**Comment by kattakarthik** [comment] 2019-08-01 13:20
GOPROXY=https://proxy.golang.org GO111MODULE=on 
CGO_ENABLED=0
go get github.com/minio/minio

You mean add the above flag in this command ?? 

Will there be any impact to the already synced data if we restart minio after building the way you suggested ??

**Comment by harshavardhana** [comment] 2019-08-01 13:28
> You mean add the above flag in this command ??

yes it should be one line
```
GOPROXY=https://proxy.golang.org GO111MODULE=on CGO_ENABLED=0 go get github.com/minio/minio
```

**Comment by kattakarthik** [comment] 2019-08-01 13:32
Got it.
Will there be any impact to the already synced data if we restart minio after building the way you suggested ??

**Comment by harshavardhana** [comment] 2019-08-01 13:34
> Got it.
> Will there be any impact to the already synced data if we restart minio after building the way you suggested ??

@kattakarthik there shouldn't be any.

**Comment by kattakarthik** [comment] 2019-08-02 19:13
[minio_log.txt](https://github.com/minio/minio/files/3462613/minio_log.txt)

@harshavardhana Rebuilt minio like the way you suggested. After ~10 hrs of run, the issue is still reproducible. Attaching the log file. Please have a look.

**Comment by harshavardhana** [comment] 2019-08-02 21:01
This looks like a Go bug 

```
runtime: pointer 0x401a000000 to unallocated span span.base()=0x4009fae000 span.limit=0x4009fb0000 span.state=0
runtime: found in object at *(0x401a6a3030+0xb0)
object=0x401a6a3030 s.base()=0x401a69e000 s.limit=0x401a6a6000 s.spanclass=0 s.elemsize=8192 s.state=mSpanManual
```

A bug happened in garbage scanning which version of Go are you using?

**Comment by harshavardhana** [comment] 2019-08-02 21:04
Apparently fixed in go 1.12 https://github.com/golang/go/issues/26243

**Comment by kattakarthik** [comment] 2019-08-03 01:07
I used go1.12.7.linux-arm64 @harshavardhana

**Comment by kattakarthik** [comment] 2019-08-03 01:25
This is the latest version available. 
These two threads have the same issue reported earlier :: 
https://github.com/thanos-io/thanos/issues/654
https://github.com/json-iterator/go/issues/140

This one particularly on arm :: https://github.com/golang/go/issues/21568 
But the fix should be been there on latest release.. 
Not sure if I need to open a new ticket for this on Go ?

@harshavardhana

**Comment by harshavardhana** [comment] 2019-08-03 03:30
Okay this may require some deeper debugging.. @kattakarthik

**Comment by kattakarthik** [comment] 2019-08-03 06:55
Ok. I just posted the same error on Go and here is the reply ::

"This error indicates some sort of memory corruption. By far the most common causes are incorrect uses of unsafe.Pointer, incorrect uses of cgo when calling C code, and incorrect C code."

I will be able to provide any debug logs you need to root casue it.

**Comment by harshavardhana** [comment] 2019-08-03 06:58
> "This error indicates some sort of memory corruption. By far the most common causes are incorrect uses of unsafe.Pointer, incorrect uses of cgo when calling C code, and incorrect C code."

We don't depend on Cgo code most probably one of our libraries is using unsafe.Pointer which may lead to this bug in some manner.  @kattakarthik

**Comment by kattakarthik** [comment] 2019-08-05 03:20
Thanks @harshavardhana ...  Wonder how can we root cause this ? This is blocker for our POC on ARM.. Can I enable any debug flags and run this which may give you more info than present stack trace ?

**Comment by harshavardhana** [comment] 2019-08-05 03:55
We should talk on this more @kattakarthik can you please join us as https://slack.min.io and ping me there `y4m4`

**Comment by harshavardhana** [comment] 2019-08-06 19:28
@kattakarthik how are things going?

**Comment by kattakarthik** [comment] 2019-08-07 03:52
The issue didn't occur in last 24 hrs testing.. I will have to monitor it for 2 more days and see.
I will keep you posted.

**Comment by kattakarthik** [comment] 2019-08-07 11:22
[minio_log.txt](https://github.com/minio/minio/files/3476703/minio_log.txt)
Oops.. it crashed again.. Here is the log.. @harshavardhana

**Comment by kattakarthik** [comment] 2019-08-07 11:28
[minio_log_7Aug.txt](https://github.com/minio/minio/files/3476739/minio_log_7Aug.txt)
One more instance of crash... You can see stack trace at the end of this log.. 
@harshavardhana

**Comment by harshavardhana** [comment] 2019-08-07 16:06
When you said testing, is there any I/O activity in progress for the entirety of the server run ?

**Comment by harshavardhana** [comment] 2019-08-07 16:13
Also this time can you redeploy the binary compiled with `-race` flag on ?

**Comment by harshavardhana** [comment] 2019-08-09 02:53
How are things going ??

**Comment by kattakarthik** [comment] 2019-08-09 11:33
Deployed minio with -race flag... Didn't hit issue yet. I will get back to you as soon as the issue is reproduced.

**Comment by harshavardhana** [comment] 2019-08-09 15:54
Thanks @kattakarthik

**Comment by kattakarthik** [comment] 2019-08-10 07:35
[minio_log.txt](https://github.com/minio/minio/files/3488628/minio_log.txt)
[minio_lo2.txt](https://github.com/minio/minio/files/3488630/minio_lo2.txt)

@harshavardhana Please check these two logs..

**Comment by harshavardhana** [comment] 2019-08-10 15:18
Thank you will do @kattakarthik

**Comment by harshavardhana** [comment] 2019-08-11 20:27
I am working on another build will attach it here once done @kattakarthik

**Comment by harshavardhana** [comment] 2019-08-11 23:31
~[minio.tar.gz](https://github.com/minio/minio/files/3490544/minio.tar.gz)~

@kattakarthik new binary with new changes based on #8063 can you check?

**Comment by harshavardhana** [comment] 2019-08-11 23:54
Hold-off the deployment, checking there is something wrong with the binary. Will report back if there are no issues.

**Comment by harshavardhana** [comment] 2019-08-12 00:27
[minio.tar.gz](https://github.com/minio/minio/files/3490600/minio.tar.gz)

Updated the binary this works and is properly fixed.

**Comment by kattakarthik** [comment] 2019-08-12 00:28
Sure. I will wait. Thanks. @harshavardhana

**Comment by kattakarthik** [comment] 2019-08-12 00:29
Thanks. We will test and let you know.

**Comment by harshavardhana** [comment] 2019-08-14 00:11
@kattakarthik how are things going?

**Comment by kattakarthik** [comment] 2019-08-16 03:12
Its been running successfully since 2.5 days. We have been running load tests. We will do the same over the weekend and confirm you by Monday. Thanks @harshavardhana

**Comment by kattakarthik** [comment] 2019-08-18 16:36
[server_2019_08_18_11_50_AM.log](https://github.com/minio/minio/files/3513293/server_2019_08_18_11_50_AM.log)
[server_2019_08_18_04_15_PM.log](https://github.com/minio/minio/files/3513294/server_2019_08_18_04_15_PM.log)
Crashed twice today @harshavardhana Please find the attached logs.

**Comment by harshavardhana** [comment] 2019-08-18 17:10
Now the stack is different, looks like some other dependency is using unsafe in a wrong way

**Comment by kattakarthik** [comment] 2019-08-18 17:12
Ok. But the crash occurances have reduced after the fix.

**Comment by kattakarthik** [comment] 2019-08-21 15:04
@harshavardhana Finally we have a found for this crash or corruption issue. 

This is happening only if we sync to particular type of files..  1. LAZ 2. HRC 
Both these are binary files. 

I tried the same scenario on an x86 (single node) server and it could sync the data without any issues.

So only ARM servers are running into issue (I haven't tested X86-Minio on distributed mode though..where as our ARM cluster is a distributed mode setup)

This is another error we are observing with the same files :: 

_An error occurred (InvalidPart) when calling the CompleteMultipartUpload operation: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part\'s entity tag.\nupload failed: ../../persistent/task_ed8c94c9-4114-4db3-827c-c7e2b5a59b06/tiles/out_21_-18.laz to_ 

I have seen this similar error while uploading "debug.so" files... 

So looks like an issue in reading binary files on ARM ?

**Comment by vadmeste** [comment] 2019-08-21 15:24
@kattakarthik by the way, it is possible that tweaking GOGC environment variable can trigger the crash more often. GOGC needs be set before running Minio server. Its default value is 100, lowering it to 20 should make GC work more often.

**Comment by harshavardhana** [comment] 2019-08-21 16:17
@kattakarthik the error that you are seeing is reproducible on x86 as well, we are working on a fix for that. But are you saying a crash happens right after this error is seen on the client side ?

**Comment by kattakarthik** [comment] 2019-08-21 19:24
> @kattakarthik the error that you are seeing is reproducible on x86 as well, we are working on a fix for that. But are you saying a crash happens right after this error is seen on the client side ?

No. I meant that the crash & the error are the two issues I've come across while working with binary files. The server doesn't crash after this error.

**Comment by kattakarthik** [comment] 2019-08-23 13:25
Here is another observation from our side. This is doesn't happen in ARM standalone mode (not standalone erasure code... just standalone server with data folder on a drive). 

Next I am trying to test ARM server standalone erasure code with multiple drives on a single server.

@harshavardhana

**Comment by harshavardhana** [comment] 2019-09-08 23:45
We have moved to Go 1.13 - can you test again to see if we reproduce any issues @kattakarthik ?

**Comment by harshavardhana** [comment] 2019-09-09 19:39
Looks like the issue is reproduced by using a simple main.go program https://github.com/golang/go/issues/33446

**Comment by FU100** [comment] 2019-09-17 11:21
I tried to simplify the code and found that it was a high probability while calling a third-party upload function on the arm64 platform, so it might not be of much help to you.

**Comment by harshavardhana** [comment] 2019-09-18 00:28
Going to close this issue, for now, please re-open @kattakarthik if you think we should look at this again.

**Closed as completed by harshavardhana** 2019-09-18 00:28 UTC
Labels: working as intended, community, priority: medium

**Comment by kattakarthik** [comment] 2019-09-18 03:30
> Going to close this issue, for now, please re-open @kattakarthik if you think we should look at this again.

Sure, Thanks for the help.
