### ISSUE TITLE
IAM Policies do not keep Sid

### ISSUE THREAD

**Issue by bluemmb** [minio/minio#13905] opened 2021-12-14 12:09 UTC
According to the documentation "MinIO policy documents use the same schema as AWS IAM Policy documents."

But **IAM Policies** and **Service Account Policies** remove Sid field from the given json and don't store it. **(Note that Bucket policies keep Sid field)**

Sid is really useful when it comes to controlling policies programmatically. otherwise, you have to loop through all statements and have some special checks to find your desired statement to update.

## Expected Behavior
Keep Sid field in **IAM Policies** and **Service Account policies**

## Current Behavior
Sid field gets removed.

## Steps to Reproduce (for bugs)
- Suppose you have this policy.json
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AddSomeRestrictions",
            "Effect": "Deny",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::public-bucket/private.txt*",
                "arn:aws:s3:::public-bucket/private2.txt*"
            ]
        }
    ]
}
```
- Run `mc admin policy add local newpolicy policy.json`
- Run `mc admin policy info local newpolicy`
- You should see that Sid is removed
- The same thing happens for Service Account policies

## Your Environment
* Version used (`minio --version`): RELEASE.2021-12-10T23-03-39Z

**Comment by vadmeste** [comment] 2021-12-14 15:34
@bluemmb Thanks for reporting this. I am able to reproduce this. We will fix this soon.

**Comment by vadmeste** [comment] 2021-12-14 15:55
@bluemmb this looks like already fixed by this commit, 44fefe5b9

The fix will be in the next release @bluemmb .

**Comment by bluemmb** [comment] 2021-12-26 08:18
@vadmeste Thanks. I tested the latest version `2021-12-20T22-07-16Z` which includes #13796

It now accepts Sid for **IAM Policies** but still **Service Account Policies** do not keep Sid

Steps to reproduce:
- Suppose you have this policy.json
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AddSomeRestrictions",
            "Effect": "Deny",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::public-bucket/private.txt*",
                "arn:aws:s3:::public-bucket/private2.txt*"
            ]
        }
    ]
}
```
- Run `mc admin user svcacct add local admin --access-key abc --secret-key 12345678 --policy policy.json`
- Run `mc admin user svcacct info local abc --policy`
- You should see that Sid is removed

**Comment by harshavardhana** [comment] 2021-12-26 08:56
> * Run `mc admin user svcacct add local admin --access-key abc --secret-key 12345678 --policy policy.json`
> * Run `mc admin user svcacct info local abc --policy`
> * You should see that Sid is removed

This a server bug, that needs to be fixed // cc @vadmeste - I am able to reproduce it.

**Comment by bluemmb** [comment] 2021-12-27 08:32
@harshavardhana Thanks. Would you reopen this issue so it wouldn't be missed out?

**Closed as completed** 2022-01-10 22:26 UTC
Labels: community, fixed, priority: medium
