### ISSUE TITLE
 Directory index full

### ISSUE THREAD

**Issue by alpswjc** [minio/minio#3857] opened 2017-03-06 16:05 UTC
i am seeing the following error in the log file 

time="2017-03-05T19:09:27-06:00" level=error msg="Unable to create an object." cause="mkdir /opt/buckets/.minio.sys/buckets/abc/201703/1-1/home+in+a:479:objectAPIHandlers.PutObjectHandler()]" stack="fs-v1.go:577:fsObjects.PutObject <autogenerated>:275:(*fsObjects).PutObject object-handlers.go:476:objectAPIHandlers.r-fm"

this is in syslog 

Mar  6 09:19:49 mno-001 kernel: [496466.463940] EXT4-fs warning (device sda4): ext4_dx_add_entry:2199: inode #21901881: comm minio: Directory index full!
Mar  6 09:19:49 mno-001 kernel: [496466.464527] EXT4-fs warning (device sda4): ext4_dx_add_entry:2199: inode #21901881: comm minio: Directory index full!
Mar  6 09:19:49 mno-001 kernel: [496466.465115] EXT4-fs warning (device sda4): ext4_dx_add_entry:2199: inode #21901881: comm minio: Directory index full!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
 2017-02-16T01:47:30Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=32963184k,nr_inodes=8240796,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=6596640k,mode=755 0 0
/dev/sda4 / ext4 rw,relatime,data=ordered 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,nosuid,nodev,noexec,relatime 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
systemd-1 /proc/sys/fs/binfmt_misc autofs rw,relatime,fd=22,pgrp=1,timeout=0,minproto=5,maxproto=5,direct 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
mqueue /dev/mqueue mqueue rw,relatime 0 0
hugetlbfs /dev/hugepages hugetlbfs rw,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,relatime 0 0
fusectl /sys/fs/fuse/connections fusectl rw,relatime 0 0
/dev/sda2 /boot ext2 rw,relatime,block_validity,barrier,user_xattr,acl,stripe=4 0 0
lxcfs /var/lib/lxcfs fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0
tmpfs /run/user/999 tmpfs rw,nosuid,nodev,relatime,size=6596640k,mode=700,uid=999,gid=999 0 0
tmpfs /run/user/2002 tmpfs rw,nosuid,nodev,relatime,size=6596640k,mode=700,uid=2002,gid=2002 0 0
tmpfs /run/user/2005 tmpfs rw,nosuid,nodev,relatime,size=6596640k,mode=700,uid=2005,gid=2005 0 0
tmpfs /run/user/2044 tmpfs rw,nosuid,nodev,relatime,size=6596640k,mode=700,uid=2044,gid=2044 0 0

* Link to your project:

**Comment by harshavardhana** [comment] 2017-03-06 19:54
```
kernel: EXT4-fs warning (device dm-2): ext4_dx_add_entry: Directory index full!
```

There are a number of possible resolutions:

- Determine if a process is creating unexpected or unwanted files or directories.
- Remove unnecessary or unwanted files or directories.
- Reorganize files and directories within the filesystem to reduce the number of entries in each individual directory.
- Use shorter filenames.
- Change the block size of the filesystem. This option requires a re-format of the filesystem, since the block size cannot be changed once it is set.
**CAUTION**: Before re-formatting the filesystem backup any important files to another device as reformatting will recreate the filesystem metadata and not retain information about existing files. By default the ext3 block size for small volumes is 1024. If possible format the disk with 4096 bytes (4k) block size as follows:

```
# mkfs -t ext4 -b 4096 /dev/device
```

- Disable dir_index option of the filesystem. Note: There is no need to unmount the file system.
**CAUTION**: Disabling this option may impact performance on lookups in large directories.

```
# tune2fs -O ^dir_index /dev/device
```

- To recreate the dir_index:

```
# umount /dev/device
# tune2fs -O dir_index /dev/device
# e2fsck -D /dev/device
```

### Root Cause

- The 'directory index full' error will be seen if there are lots of files/directories in the filesystem so that the tree reaches its indexing limits and cannot keep track further.
- The directory index is an additional tree structure which helps directory lookups, improving performance for huge directories.
- There is a limit in ext3 and ext4 of the directory structure.
    - A directory on ext3 can have at most 31998 sub directories, because an inode can have at most 32000 links. This is one cause of the warning.
    - A directory on ext4 can have at most 64000 sub directories.
- The size of each section of a directory index is limited by the filesystem's block size. If very long filenames are used, fewer entries will fit in the block, leading to 'directory index full' errors earlier than they would occur with shorter filenames. This can become a bigger problem when the filesystem's block size is small (1024-byte or 2048-byte blocks), but will occur with 4096-byte blocks as well.
- For further information about directory indexing, you may refer to the following page : http://ext2.sourceforge.net/2005-ols/paper-html/node3.html

**Comment by harshavardhana** [comment] 2017-03-06 19:55
Closing this as a `ext4` issue above solution sufficiently provides enough information on how to address this problem.

**Closed as completed by harshavardhana** 2017-03-06 19:55 UTC
Labels: working as intended, community

**Comment by rumpelstiltzkin** [comment] 2018-12-27 04:51
Hi @harshavardhana ,

Thanks for the detailed resolutions and explanations above. Our usage of Minio involves storing millions of objects that don't have a "/" delimiter in their names. So using it on top of a filesystem like ext4 seems to be giving us the same or similar problems as above. The latest one is "No space for directory leaf checksum. Please run e2fsck -D". I suspect that's also due to the block filling up. 

There's no directory hierarchy created by us - we simply PUT and GET object names & their values. We cannot use shorter object names as our object names are hash values. We can try reformatting the filesystem (ext4) but I suspect it simply kicks the can down the road, isn't it? The underlying problem is that all these issues arise from using Minio on top of a POSIX filesystem like ext4, which wasn't designed for a flat structure of a key-value store, such that we end up with _all_ our objects under the same "directory".

That brings me to my question - does Minio provide its own backing-storage format that does not suffer from the above problems of a filesystem? I looked here https://www.minio.io/drive.html under 'Architecture' and it seems that all of them require a pre-formatted filesystem below the Minio server. Thanks.
