### ISSUE TITLE
Mounting a minio bucket with s3fs return an error on list_buckets

### ISSUE THREAD

**Issue by legolas49** [minio/minio#3895] opened 2017-03-13 17:14 UTC
## Expected Behavior

hi, 
i would like help if possible, when i try to mount a minio bucket with s3fs i have this error : 

[ERR] s3fs.cpp:list_bucket(2516): xmlReadMemory returns with error.
[ERR] s3fs.cpp:s3fs_readdir(2437): list_bucket returns error(-1).

## Steps to Reproduce (for bugs)

1. i mount using the command :
 s3fs -f -d -o use_path_request_style -o url=http://xxxx.xxxxx.xxx:9000/minio -o allow_other -o endpoint=eu-central-1 -o passwd_file=/etc/passwd-s3fs mybucket /mnt/mybucket
2.
3.
4.

## Context

i try to mount a minio bucket in a folder on an other server  (2 servers when it will works),
that works with a s3 bucket on amazon but i would like to change with my own server

## Your Environment

* Version used:
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: scaleway VC1S with minio in docker
* Operating System and version: Ubuntu 14.04
* Link to your project:

**Comment by vadmeste** [comment] 2017-03-13 17:36
@legolas49, there is a lot of projects called s3fs :) Can you just point us to which one are you talking about ?

**Comment by legolas49** [comment] 2017-03-13 17:48
Sorry

# s3fs --version
Amazon Simple Storage Service File System V1.80(commit:d40da2c) with OpenSSL
Copyright (C) 2010 Randy Rizun <rrizun@gmail.com>
License GPL2: GNU GPL version 2 <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

https://github.com/s3fs-fuse/s3fs-fuse

**Comment by vadmeste** [comment] 2017-03-15 23:38
@legolas49, 

*) The endpoint url is http://xx.xx.xx.xx:9000/ without 'minio'. So you need to pass `-o url=http://xxxx.xxxxx.xxx:9000/`
*) I noticed that you passed `eu-central-1` region, did you also set `eu-central-1` in Minio config ?
*) I added one fix that enhances s3fs support with Minio. However, it still can't support mkdir.

Currently, to test, you need to download the source and compile the project.

**Comment by legolas49** [comment] 2017-03-16 09:34
@vadmeste 
Hi,
First thanks for your response.

1/ Ok i will change the endpoint like explained.
2/ Yes i have this region in Minio config.
3/ i use minio in docker, where i can download your fix? I compile with Make? I have to reinstall minio server?

Regards

**Comment by vadmeste** [comment] 2017-03-16 10:44
> 3/ i use minio in docker, where i can download your fix? I compile with Make? I have to reinstall minio server?

If you are using docker, you can download this image `minio/minio:edge` which contains the fix.

**Comment by legolas49** [comment] 2017-03-16 10:49
great, thanks

**Comment by harshavardhana** [comment] 2017-03-23 05:31
> great, thanks

@legolas49 were you able to validate the fix?

**Comment by harshavardhana** [comment] 2017-03-30 06:33
Closing this as fixed as per #3897 - please re-open if the issue is not fixed yet.

**Closed as completed by harshavardhana** 2017-03-30 06:33 UTC
Labels: community
