### ISSUE TITLE
CopyObjectPart does not copy checksums (difference w/ observed AWS S3 behavior)

### ISSUE THREAD

**Issue by jimrobinson** [minio/minio#20649] opened 2024-11-14 16:22 UTC
## NOTE

The MinIO page [S3 API Compatibility](https://min.io/docs/minio/linux/reference/s3-api-compatibility.html#multipart-uploads) points users to the AWS S3 documentation for [UploadPartCopy](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html).

On that AWS page it lists the following [Request Syntax](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html#API_UploadPartCopy_RequestSyntax):

	PUT /Key+?partNumber=PartNumber&uploadId=UploadId HTTP/1.1
	Host: Bucket.s3.amazonaws.com
	x-amz-copy-source: CopySource
	x-amz-copy-source-if-match: CopySourceIfMatch
	x-amz-copy-source-if-modified-since: CopySourceIfModifiedSince
	x-amz-copy-source-if-none-match: CopySourceIfNoneMatch
	x-amz-copy-source-if-unmodified-since: CopySourceIfUnmodifiedSince
	x-amz-copy-source-range: CopySourceRange
	x-amz-server-side-encryption-customer-algorithm: SSECustomerAlgorithm
	x-amz-server-side-encryption-customer-key: SSECustomerKey
	x-amz-server-side-encryption-customer-key-MD5: SSECustomerKeyMD5
	x-amz-copy-source-server-side-encryption-customer-algorithm: CopySourceSSECustomerAlgorithm
	x-amz-copy-source-server-side-encryption-customer-key: CopySourceSSECustomerKey
	x-amz-copy-source-server-side-encryption-customer-key-MD5: CopySourceSSECustomerKeyMD5
	x-amz-request-payer: RequestPayer
	x-amz-expected-bucket-owner: ExpectedBucketOwner
	x-amz-source-expected-bucket-owner: ExpectedSourceBucketOwner

And the following [Response Syntax](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html#API_UploadPartCopy_ResponseSyntax):

	<CopyPartResult>
	   <ETag>string</ETag>
	   <LastModified>timestamp</LastModified>
	   <ChecksumCRC32>string</ChecksumCRC32>
	   <ChecksumCRC32C>string</ChecksumCRC32C>
	   <ChecksumSHA1>string</ChecksumSHA1>
	   <ChecksumSHA256>string</ChecksumSHA256>
	</CopyPartResult>

The documentation for the checksum elements indicate they will be populated if object was uploaded with the data, e.g., for CRC32 it specifies:

	 ChecksumCRC32
	
	    The base64-encoded, 32-bit CRC-32 checksum of the object. This will only be present if it was uploaded with the object. When you use an API operation on an object that was uploaded using multipart uploads, this value may not be a direct checksum value of the full object. Instead, it's a calculation based on the checksum values of each individual part. For more information about how checksums are calculated with multipart uploads, see Checking object integrity in the Amazon S3 User Guide.
	
	    Type: String

There is some ambiguity in the response documentation.  Because it specifies "object" and not "original object" it's not immediately clear whether or not the checksum might be provided with the UploadPartCopy call. Examining the Request Syntax makes it clear the checksum must be coming from the original, as there is no facility for specifying a checksum with the UploadPartCopy call.

Some testing has shown that on AWS S3 if the following sequence of calls are made:

1. create-multipart-upload w/ --checksum-algorithm specified
2. upload-part w/ --checksum-algorithm specified
3. complete-multipart-upload w/ ETag, Checksum, and PartNumber listed per part
4. create-multipart-upload w/ --checksum-algorithm specified
5. upload-part-copy of the original part (from step 2)
6. complete-multipart-upload w/ ETag, Checksum (from step 2), and PartNumber listed per part

Then the copy that was created in steps 4 through 6 will have the Checksum set, copying the original checksum from step 2.

Attempting the same sequence on MinIO fails at step 5, where MinIO complains

	An error occurred (InvalidArgument) when calling the UploadPartCopy operation: Invalid arguments provided for test-jrobinso/ffc760738e5b213014b88e7e0445f54b8a1c543c80e6a41955e3fe506bda06f8/0c1a3b6b-94ab-474e-ae03-ab5127546518x1731597547036225467: (checksum missing, want "SHA256", got "")

## Expected Behavior

I expect UploadPartCopy in MinIO to behave the same way as it does in AWS S3, where you can copy the Checksum of an object when you are performing a server side copy.

## Current Behavior

MinIO fails with an error message from `cmd/erasure-multipart.go`'s implementation of  [PutObjectPart]https://github.com/minio/minio/blob/0e9854372ef81402fd3e81e0f7bbe852896f2ef7/cmd/erasure-multipart.go#L593-L600

## Possible Solution

Since I don't have access to the AWS S3 server side implementation of the equivalent of MinIO's PutObjectPart I'm not positive, but I am suspecting that the AWS implementation ensures it copies over the Checksum metadata from the original when the create-multipart-upload has provided a `--checksum-algorithm` argument.

## Steps to Reproduce (for bugs)

I've created a bash script that can be run against both AWS and MinIO to show the difference in behavior.  It requires a Unix setup with access to bash, tee, jq, and the aws cli.

1. Setup aws cli credentials and configuration for profiles for AWS and MinIO, e.g,. `test-aws` and `test-minio`, and create buckets in each that you have read/write access to
2. git clone https://github.com/jimrobinson/test-upload-part-copy and change to it
3. Run `./test-upload-part-copy --profile <aws_profile> --bucket <bucket> --key <key> --source zero.dat --algorithm <algorithm>`
4. Run `./test-upload-part-copy --profile <minio_profile> --bucket <bucket> --key <key> --source zero.dat --algorithm <algorithm>`

The shell script will perform three iterations of `create-multipart-upload` / `upload-part` or `upload-part-copy` / `complete-multipart-upload`, naming the objects `<key>`, `<key>.1`, or `<key>.2`.

The script's first `upload-part-copy` does not specify a byte range, the second one does specify a full byte range.  AWS S3 behaves the same way in both cases, copying the original Checksum.

Examples of the output are in `test.aws.out` and `test.minio.out`

## Context

When a client has uploaded an object w/ Checksum metadata it is important to us that we are able to perform a server side copy of the object while preserving the original checksum metadata.

It'd be nice if we could optionally provide the expected checksum with the upload-part-copy call, but it doesn't appear to me that there is an facility to do that with the current API definition laid out by AWS.  If there was the option to provide the checksums as part of the UploadPartCopy operation then it'd introduce the ability to resize the parts of a multi-part object while still preserving the ability for a client to validate the remote copy against a local version (by examining the remote part offets and their checksums, and comparing those against their local version).

## Regression

I'm not sure.  It doesn't seem likely that this is a regression.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2024-11-07T00-52-20Z (commit-id=cefc43e4daa4cbb490ef6726ea374e26a93eb85e)
* Server setup and configuration: minio server --console-address :9001 http://test-minio-n{0...3}/mnt/disk0
* Operating System and version (`uname -a`): Linux 6.11.5-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 19:13:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment] 2024-11-15 11:57
Yes. Part copy operations aren't super reliable with checksums. This is on our list, but not a high priority item at the moment.

**Comment by harshavardhana** [comment] 2024-11-17 03:35
https://github.com/minio/minio/issues/17013 closing as duplicate of an existing issue

**Closed as completed by harshavardhana** 2024-11-17 03:35 UTC
Labels: duplicate, community
