### ISSUE TITLE
browser: use BEM CSS naming convention 

### ISSUE THREAD

**Issue by rushenn** [minio/minio#3731] opened 2017-02-10 11:18 UTC
With BEM(Block, Element, Modifier) methodology,  classes in HTML and CSS are named with a unique approach in order to help code maintainers better understand the relationship between HTML and CSS.

http://getbem.com/naming/

**Comment by deekoder** [comment] 2017-04-01 01:32
Needs further discussion.

**Comment by deekoder** [comment] 2017-04-03 16:41
dependent on new UI. Track new UX as an issue.

**Comment by nitisht** [comment] 2018-01-15 17:47
closing as duplicate of https://github.com/minio/minio/issues/5397

**Closed as completed by nitisht** 2018-01-15 17:47 UTC
Labels: duplicate, priority: medium
