### ISSUE TITLE
Free disk space totally wrong - reset possible?

### ISSUE THREAD

**Issue by peterbe** [minio/minio#5003] opened 2017-10-02 21:16 UTC
I used to have not much free space on my docker host (osx). Eventually I ran into XMinioStorageFull and wasn't able to add more files to minio. 
I poked around my laptop and freed up many gigabytes of old junk and started the minio docker image again. Now it said I had even less space! 73MB. 
I don't remember what I did next but I deleted all docker images and rebuilt with docker-compose and now it's down to 0MB. 

## Expected Behavior
The disk space reporting to match my laptops remaining disk space capacity.

## Current Behavior
```
▶ docker-compose run minio
Created minio configuration file successfully at /root/.minio
Endpoint:  http://172.18.0.4:9000  http://127.0.0.1:9000
AccessKey: minio
SecretKey: miniostorage

Browser Access:
   http://172.18.0.4:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://172.18.0.4:9000 minio miniostorage

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 0 B Free, 63 GiB Total
```

I'm confident my host has more than 0B free. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
I'm running minio/minio as part of docker-compose so I can use it to simulate S3 uploads.
My docker-compose looks like this:
https://github.com/mozilla-services/tecken/blob/517f8a32955bcb5dd1b9d650cecf2f529757603a/docker-compose.yml#L123-L132

## Your Environment
* Version used (`minio version`): Don't know where to look that up. 
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment] 2017-10-02 21:32
From what it looks like the docker is not reporting the disk sizes properly here.. can you see the `df -h` output of the docker container and do you see the same issue?

**Comment by peterbe** [comment] 2017-10-02 23:38
> can you see the df -h output of the docker container and do you see the same issue?

I admit that I'm still learning docker. I don't know how to get into a shell (bash) of the minio container. With my other containers I can do things like `docker-compose run webapp bash`.

**Comment by harshavardhana** [comment] 2017-10-02 23:49
> I admit that I'm still learning docker. I don't know how to get into a shell (bash) of the minio container. With my other containers I can do things like docker-compose run webapp bash.

You can `docker ps` and look at the container name and then do the following on another terminal 

```
docker exec -it <container_id> /bin/sh
```

Once you are in just type 
```
df -h /export
```

Also i see a problem in your container configuration.

```yml
 minio:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniostorage
    ports:
      - "9000:9000"
    volumes:
      - $PWD/miniodata:/export
    command: server /myexport
```

you want `/export` but you have used `/myexport` is that expected?

**Comment by peterbe** [comment] 2017-10-03 00:03
```
▶ docker exec -it e903e054f0df /bin/sh
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  62.7G     59.6G         0 100% /
tmpfs                   999.4M         0    999.4M   0% /dev
tmpfs                   999.4M         0    999.4M   0% /sys/fs/cgroup
osxfs                   930.7G    465.6G    464.9G  50% /export
/dev/vda1                62.7G     59.6G         0 100% /etc/resolv.conf
/dev/vda1                62.7G     59.6G         0 100% /etc/hostname
/dev/vda1                62.7G     59.6G         0 100% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                   999.4M         0    999.4M   0% /proc/kcore
tmpfs                   999.4M         0    999.4M   0% /proc/timer_list
tmpfs                   999.4M         0    999.4M   0% /proc/sched_debug
tmpfs                   999.4M         0    999.4M   0% /sys/firmware
```

**Comment by peterbe** [comment] 2017-10-03 00:08
Also, 
```
/ # ls -l myexport/
total 4
drwxr-xr-x    2 root     root          4096 Oct  2 21:09 testbucket
/ # ls -l myexport/testbucket/
total 0
```
And,
```
/ # ls | xargs du -sh
808.0K	bin
0	dev
1.2M	etc
0	export
4.0K	home
2.7M	lib
16.0K	media
4.0K	mnt
28.0K	myexport
0	proc
24.0K	root
4.0K	run
216.0K	sbin
4.0K	srv
0	sys
4.0K	tmp
21.5M	usr
72.0K	var
```

I actually didn't understand how the volumes mount worked. There is no `./miniodata` directory mounted on the host. 

Oh, for what it's worth, I used `mc` to delete all the content I previously put into the `testbucket`. 

By the way, the difference between 62.7G and 59.6G is what I actually had on my "Macintosh HD" today before I started deleting a bunch of old junk. 

I just don't get why minio can't see that I've taken care of freeing up disk space here on my host.

**Comment by harshavardhana** [comment] 2017-10-03 00:14
> overlay                  62.7G     59.6G         0 100% /

Minio is reporting correctly you have a wrong configuration on your docker-compose.yml don't use myexport since that would end up using your `/` which is reported to have 0% available space.

You need to provide `server /export` in your docker-compose.yml which would report the following. 

> osxfs                   930.7G    465.6G    464.9G  50% /export

**Comment by peterbe** [comment] 2017-10-03 00:35
Yay! That totally solved the problem. 
<img width="763" alt="screen shot 2017-10-02 at 8 34 21 pm" src="https://user-images.githubusercontent.com/26739/31105321-3b7f2272-a7b1-11e7-86fd-9cb40f01770c.png">

But it's curious, what the 116TB comes from :)
My HD only has a 1TB of space.
<img width="391" alt="screen shot 2017-10-02 at 8 35 12 pm" src="https://user-images.githubusercontent.com/26739/31105325-4115a56c-a7b1-11e7-941f-d1b983dac121.png">

**Comment by harshavardhana** [comment] 2017-10-03 00:44
Do not this is what is being reported by the local FS.

**Comment by harshavardhana** [comment] 2017-10-03 07:39
Do not know what happened here, perhaps you should use Linux machine for running docker. Docker on macOS is not really native and can have weird interaction issues. 

It is also possible since your disk is encrypted this type erroneous volume sizes are being reported.

**Comment by harshavardhana** [comment] 2017-10-05 19:12
@peterbe is there anything we can help further with this issue? , if not feel free to close it.

**Comment by peterbe** [comment] 2017-10-05 20:17
Well, I feel bad for filing an issue when ultimately it was a user error. And I admit that I rushed my own debugging and abused the issue filing because things didn't work. 

However, what we can learn from this is that if you make my same mistake it's hard to understand what's going wrong. What did happen was that I deleted all the files I could see with `mc` and `localhost:9000` and yet the file size didn't go down. 

Is there something we can do with that? Or is the user error too prominent?

**Comment by der-onkel** [comment] 2017-10-06 21:01
It's a strange Docker on Mac OS X behavior.

## Example
```golang
package main

import (
	"fmt"
	"syscall"
)

func main() {
	// Path inside docker container
	//path := "/mnt"
	// Path on Mac OS X
	path := "/Users/dukat/Desktop/minio"
	s := syscall.Statfs_t{}
	err := syscall.Statfs(path, &s)
	if err != nil {
		return
	}
	fsReservedBlocks := uint64(s.Bfree) - uint64(s.Bavail)
	fmt.Println("Total:", uint64(s.Bsize)*(uint64(s.Blocks)-fsReservedBlocks))
	fmt.Println("Free: ", uint64(s.Bsize)*uint64(s.Bavail))
}
```

### Docker Command:
```bash
docker run --rm -it -v /Users/dukat/Desktop/minio:/mnt  golang
```

### Results:
Native on Mac OS X 10.13
```
Max OS X Total:    244093681664
Max OS X Free:      82487795712
```
Inside Docker on Mac OS X 10.13
```
Docker Total:   249951930023936
Docker Free:     84383058886656
```

:confused:

**Comment by harshavardhana** [comment] 2017-10-06 21:12
Perhaps you can open a bug with docker on this macOS issue @der-onkel ?

**Comment by der-onkel** [comment] 2017-10-06 21:39
@harshavardhana  Bug is open: https://github.com/docker/for-mac/issues/2136

**Comment by harshavardhana** [comment] 2017-10-06 21:45
Thanks

**Comment by harshavardhana** [comment] 2017-10-09 05:22
> @harshavardhana Bug is open: docker/for-mac#2136

Closing this bug "Working as Intended" , upstream bug.

**Closed as completed by harshavardhana** 2017-10-09 05:22 UTC
Labels: working as intended, priority: medium, triage
