### ISSUE TITLE
[resolved] Panic after upgrading to RELEASE.2020-06-12T00-06-19Z

### ISSUE THREAD

**Issue by zieg8301** [minio/minio#10507] opened 2020-09-17 14:18 UTC
## Expected Behavior

After upgrade of cluster, a single container in a distributed install should be able to be restarted and rejoin the cluster.

## Current Behavior

After upgrading from RELEASE.2019-06-15T23-07-18Z to RELEASE.2020-06-12T00-06-19Z when a single container is restarted, intermittently that container will get stuck in a panic loop, and never come online. The below log will loop continuously. If all containers in the distributed install are restarted, all participants will usually start just fine, but after that healthy state, we can still experience the below panic loop if a single container is restarted.

The panic behavior is intermittent, and does not affect every pod. If two pods share the same physical k8s node, typically only one of the two will exhibit the behavior. Please see context section for more information regarding our particular setup.

```
Error: http: panic serving 10.244.2.127:55400: runtime error: invalid memory address or nil pointer dereference
Error: goroutine 105895 [running]:
Error: net/http.(*conn).serve.func1(0xc000bfc3c0)
Error: 	net/http/server.go:1767 +0x139
Error: panic(0x19315e0, 0x327c920)
Error: 	runtime/panic.go:679 +0x1b2
Error: github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0xc0006a1500, 0x1f8e9a0, 0xc0007cc7e0)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:800 +0x1a2
Error: panic(0x19315e0, 0x327c920)
Error: 	runtime/panic.go:679 +0x1b2
Error: github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x0, 0x0, 0x1f8c560, 0xc0049f5f00, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:770 +0x13a
Error: github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1f60de0, 0xc000bdd760, 0x1f8c560, 0xc0049f5f00, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:785 +0x1d6
Error: github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc001a6e0f0, 0x1f60f40, 0xc000bdd770, 0x1f8c560, 0xc0049f5f00, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:643 +0xcc
Error: github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x1f60d40, 0xc0049f5de0, 0x1f8c560, 0xc0049f5f00, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:627 +0x421
Error: github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1f60ee0, 0xc000bdd7a0, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:555 +0xe4
Error: github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1f60e00, 0xc000bdd7b0, 0x50004000000, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:69 +0xcf
Error: github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1f60ec0, 0xc0049f5e00, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:94 +0x1b3
Error: github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1f60ea0, 0xc000bdd7c0, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/crossdomain-xml-handler.go:51 +0x81
Error: github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1f60dc0, 0xc000bdd7d0, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:251 +0x68
Error: github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1f60e80, 0xc000bdd7e0, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:319 +0xac
Error: github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1f60e40, 0xc000bdd7f0, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:278 +0x1c2
Error: github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1f60d60, 0xc000bdd800, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:389 +0x3b5
Error: github.com/rs/cors.(*Cors).Handler.func1(0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8
Error: net/http.HandlerFunc.ServeHTTP(0xc0049f5e80, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	net/http/server.go:2007 +0x44
Error: github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1f61b60, 0xc0049f5e80, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:535 +0xa5
Error: github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1f60f20, 0xc000bdd880, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/auth-handler.go:470 +0x290
Error: github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x1f60d20, 0xc000bdd890, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:821 +0x2a3
Error: github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1f60f60, 0xc000bdd8a0, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1900)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:140 +0x1b3
Error: github.com/gorilla/mux.(*Router).ServeHTTP(0xc000ad80c0, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1500)
Error: 	github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe2
Error: github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1f5d660, 0xc000ad80c0, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1500)
Error: 	github.com/minio/minio@/cmd/generic-handlers.go:803 +0xac
Error: github.com/minio/minio/cmd/http.(*Server).Start.func1(0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1500)
Error: 	github.com/minio/minio@/cmd/http/server.go:104 +0x2ab
Error: net/http.HandlerFunc.ServeHTTP(0xc00077aa60, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1500)
Error: 	net/http/server.go:2007 +0x44
Error: net/http.serverHandler.ServeHTTP(0xc00054e480, 0x1f8e9a0, 0xc0007cc7e0, 0xc0006a1500)
Error: 	net/http/server.go:2802 +0xa4
Error: net/http.(*conn).serve(0xc000bfc3c0, 0x1f964e0, 0xc0000e8b40)
Error: 	net/http/server.go:1890 +0x875
Error: created by net/http.(*Server).Serve
Error: 	net/http/server.go:2928 +0x384
```

## Possible Solution

Investigate bug behavior given the context below?

## Steps to Reproduce (for bugs)

1. Have existing distributed cluster, running RELEASE.2019-06-15T23-07-18Z
2. Perform "rolling" upgrade to version RELEASE.2020-06-12T00-06-19Z ( I understand rolling upgrade is not supported between these versions, however this is the only actual 'deployment' tool available to us in this environment.
3. After upgrade completes and cluster is healthy, restart one container. 
4. Container may come up correctly, but it also may experience the panic loop shown above. If the panic behavior shown above is experienced, the only way I've found to recover the cluster is to restart all participating containers. At that point the cluster will come up healthy, until a single pod is again restarted and gets stuck in the panic loop at startup.

## Context

Minio install is running in kubernetes. It is a 6 pod distributed install running on 3 physical nodes. Two pods per physical node. We pin the pods to their respective nodes to ensure persistent disk gets mounted back to same pod (pods 1 and 2 always live on node 1...etc)

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by klauspost** [comment] 2020-09-17 15:10
Please upgrade to latest version.

**Comment by zieg8301** [comment] 2020-09-17 15:23
We don't typically like running the latest version, as we are using this in a production environment. If we encounter any other bugs, we are stuck until a fix is released. Is there any indication of a fix to address this issue in a more recent release?

I've been poring over release notes, and I'll plan on testing the latest version in a lab, however we would like to try to find a definitive version that fixes this if it is a bug, as there is an aversion to running the 'latest' code in any production environments in our organization.

**Comment by klauspost** [comment] 2020-09-17 15:48
Sure, your choice. If you would like support for older versions you can look into our [subscription offer](https://min.io/pricing).

But unless you can reproduce it with our latest release I cannot help you here. I will close the issue.

You are of course welcome to reopen the issue or file a new if you see the same problem on the latest version.

**Closed as completed by klauspost** 2020-09-17 15:48 UTC
Labels: community, fixed

**Comment by zieg8301** [comment] 2020-09-21 13:57
I upgraded to the latest release (RELEASE.2020-09-17T04-49-20Z) over the weekend and am now facing a different issue. During the deployment of the new pods in kubernetes, they come up fine. If any of the pods get restarted, they go and stay offline with the error: 

```
Unable to read 'format.json' from http://minio-1:9000/data: Expected 'storage' API version 'v20', instead found 'v20', please upgrade the servers
```

Please reopen the issue as I am unable to.

**Comment by harshavardhana** [comment] 2020-09-21 17:46
> I upgraded to the latest release (RELEASE.2020-09-17T04-49-20Z) over the weekend and am now facing a different issue. During the deployment of the new pods in kubernetes, they come up fine. If any of the pods get restarted, they go and stay offline with the error:

Can you describe a proper reproducer here? @zieg8301 please open a new issue.

**Comment by zieg8301** [comment] 2020-09-21 17:53
Seems there is already a duplicate. https://github.com/minio/minio/issues/10529

**Comment by harshavardhana** [comment] 2020-09-21 17:54
> Seems there is already a duplicate. #10529

There is no reproducer in that issue still, I would like to see a step by step guide on how to reproduce this. As I can't reproduce it on my end or in any of our deployments.

Share your kubernetes yaml etc.

**Comment by harshavardhana** [comment] 2020-09-21 18:08
```yaml
## Create headless service to StatefulSet to work.
apiVersion: v1
kind: Service
metadata:
  name: minio-dist-erasure-headless-test
  labels:
    app: minio-dist-erasure-headless-test
spec:
  ports:
  - port: 9000
  clusterIP: None
  selector:
    app: minio-dist-erasure-app-test
---
## Run minio dist erasure StatefulSet.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-dist-erasure-test
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: "Parallel"
  serviceName: "minio-dist-erasure-headless-test"
  replicas: 4
  selector:
    matchLabels:
      app: minio-dist-erasure-app-test
  template:
    metadata:
      labels:
        app: minio-dist-erasure-app-test
    spec:
      containers:
      - name: minio-dist-erasure-test
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        - name: MINIO_KMS_MASTER_KEY
          value: "my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574"
        image: minio/minio:edge
        imagePullPolicy: Always
        args:
        - server
        - http://minio-dist-erasure-test-{0...3}.minio-dist-erasure-headless-test.default.svc.cluster.local/data
        ports:
        - containerPort: 9000
```

```
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Attempting encryption of all config, IAM users and policies on MinIO backend
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         4 Online, 0 Offline. 
Endpoint:  http://10.42.2.34:9000  http://127.0.0.1:9000

Browser Access:
   http://10.42.2.34:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

Now restarting the pod by deleting it

```
~ kubectl delete pod minio-dist-erasure-test-3
pod "minio-dist-erasure-test-3" deleted
```

```
~ kubectl logs minio-dist-erasure-test-3
Found drives to heal 1, waiting until 10s to heal the content...
Waiting for all MinIO sub-systems to be initialized.. lock acquired
All MinIO sub-systems initialized successfully
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
Status:         4 Online, 0 Offline. 
Endpoint:  http://10.42.3.249:9000  http://127.0.0.1:9000

Browser Access:
   http://10.42.3.249:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

Comes back online fine? @zieg8301  - 

I suspect that you have some incorrect headless services running and incorrectly routed.  Use my example yaml it should work fine all the time.

**Comment by zieg8301** [comment] 2020-09-21 19:27
I've provided reproducer steps in #10529 as the issue seems larger than kubernetes (I was able to reproduce using docker in centos VMs)
