### ISSUE TITLE
All Service Accounts have insufficient permissions

### ISSUE THREAD

**Issue by pschichtel** [minio/minio#19206] opened 2024-03-05 20:22 UTC
All service accounts on my root user seem to not have any privileges, even newly created ones. This includes the site-replicator-0 service account used by my second site, which is currently unable to sync. The root user itself works perfectly fine, both for bucket access as well as the console.

No errors logged, KES seems to work (login wouldn't be possible without it, right?)

## Your Environment

* Version used (`minio --version`): RELEASE.2024-03-05T04-48-44Z
* Server setup and configuration: deployed by operator (5.0.12), replicating to a single-node setup on the same version deployed with docker-compose.
* Operating System and version (`uname -a`): `Linux  6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux`

**Comment by harshavardhana** [comment] 2024-03-05 20:24
> All service accounts on my root user seem to not have any privileges, even newly created ones. This includes the site-replicator-0 service account used by my second site, which is currently unable to sync. The root user itself works perfectly fine, both for bucket access as well as the console.

Yes root based accounts will never have any permissions by default. However the site replicator account is special and it must have permissions.

// cc @poornas @donatello please investigate.

**Comment by pschichtel** [comment] 2024-03-05 20:27
Has that always been the case? I remember having "unrestricted" root access keys in the past. All of the access keys I have except site-replicator-0, have policies configured with access to specific buckets. Those should work, right? I tested newly created access keys with and without a policy and neither are able to access anything.

**Comment by harshavardhana** [comment] 2024-03-05 21:13
Okay looks like this is your setup issue

```
~ mc admin user svcacct add myminio/ minioadmin
Access Key: NDRTXD6FUGY3NPCUP77Q
Secret Key: tjBXFWeiiXLKaMU5YPamkCcNfPhynZAmVZCAatML
Expiration: no-expiry
```

```
~ MC_HOST_root=http://NDRTXD6FUGY3NPCUP77Q:tjBXFWeiiXLKaMU5YPamkCcNfPhynZAmVZCAatML@localhost:9000 mc ls root/
[2024-03-01 01:24:49 PST]     0B testbucket/

```

Now a site replicated setup

```
~ minio server ~/site1 --address ":9001" &
```

```
~ minio server ~/site2 --address ":9002" &
```

```
~ mc admin replicate add site1 site2                           
Requested sites were configured for replication successfully.             
```

```
~ mc mb site1/bucket/
Bucket created successfully `site1/bucket/`.
```

```
~ mc ls site2/                                                                                                                               
[2024-03-05 13:04:04 PST]     0B bucket/                                  
```

Buckets are replicated as well as objects as well

```mc cp /etc/hosts site2/bucket/
/etc/hosts:                           228 B / 228 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 14.79 KiB/s 0s
```

```
~ mc ls site1/bucket/
[2024-03-05 13:12:37 PST]   228B STANDARD hosts
```

```
~ mc admin user add site1/ user123 user12345
Added user `user123` successfully.
```

```
~ mc admin user ls site2/
enabled    user123                                   
```

I think you have some other setup issue @pschichtel - closing this issue since its not really reproducible. 
~

**Closed as completed by harshavardhana** 2024-03-05 21:13 UTC
Labels: community, fixed

**Comment by pschichtel** [comment] 2024-03-05 21:26
@harshavardhana and what "setup issue" could that be? I'm pretty sure this worked in an older version up until a few days ago. how far can I safely downgrade?

**Comment by poornas** [comment] 2024-03-05 21:30
@harshavardhana , looks like issue happens after site replication is enabled 

~ MC_HOST_root=http://NDRTXD6FUGY3NPCUP77Q:tjBXFWeiiXLKaMU5YPamkCcNfPhynZAmVZCAatML@localhost:9000 mc ls root/

will fail because site replicator creds are used to get token claims instead of root

**Comment by pschichtel** [comment] 2024-03-05 21:52
@harshavardhana on second look, I don't think your test actually tested this issue, or did it? It seems you neither accessed S3 with that user nor did you use a service account on root. @poornas seems to be able to reproduce it. Can we reopen this?

**Comment by pschichtel** [comment] 2024-03-05 21:55
it seems that non-root users with matching policies work, so it seems only service accounts on the root user are affected by this.

**Comment by harshavardhana** [comment] 2024-03-06 08:23
> @harshavardhana , looks like issue happens after site replication is enabled
> 
> ~ MC_HOST_root=http://NDRTXD6FUGY3NPCUP77Q:tjBXFWeiiXLKaMU5YPamkCcNfPhynZAmVZCAatML@localhost:9000 mc ls root/
> 
> will fail because site replicator creds are used to get token claims instead of root

I did enable site replication @poornas - all my operations are after enabling site replication as you can see. 

What is the difference in your tests?
