### ISSUE TITLE
Minio-Server Scale UP and Down documentation

### ISSUE THREAD

**Issue by abhilash07** [minio/minio#5901] opened 2018-05-08 08:58 UTC
is there any related documents for scaling existing deployed minio-server

https://github.com/minio/minio-boshrelease/issues/66

why because i deployed 1 minio-server and sometime i want to extend to 4 or 8 is it possible.

Some times i don't need 8 disks, at that time i want to scale down to 4 is it possible. Please refer any use full documentaion or related article blog.

Thanks in advance

**Comment by harshavardhana** [comment] 2018-05-08 09:45
@abhilash07 you cannot add or remove disks from an existing Minio setup.  This is by design.

**Comment by abhilash07** [comment] 2018-05-08 11:16
@harshavardhana thanks for your response, it means upto date minio doesn't support scaling up and down functionality???

**Comment by nitisht** [comment] 2018-05-08 12:04
@abhilash07 yes, you can't add new nodes/disks to an existing deployment. To add more storage you just create new Minio deployment. This is by design.

Closing this as working as intended, feel free to get back if there are further questions.

**Closed as completed by nitisht** 2018-05-08 12:04 UTC
Labels: working as intended

**Comment by abhilash07** [comment] 2018-05-09 00:04
@nitisht thanks for your consideration i think scaling up and down for existing deployment is a good feature for Minio.
I have small question after researching i find  https://www.nginx.com/blog/enterprise-grade-cloud-storage-nginx-plus-minio/, is it possible to configure multiple deployment minio servers to LB and data synchronization ???
https://medium.com/@jmarhee/building-an-object-storage-service-ecd771d91483
Why because in production environment data synchronisation  multiple deployment minio servers  is imported, is there any recommended documentation ???

**Comment by beviah** [comment] 2019-03-22 07:23
What exactly is this doing?

mc config host add ...

from this page: https://jpmens.net/2017/09/06/my-restic-backend-of-choice-minio/

**Comment by kannappanr** [comment] 2019-03-22 17:00
@beviah Please look at https://docs.minio.io/docs/minio-client-complete-guide.html#config

**Comment by beviah** [comment] 2019-03-22 18:18
@kannappanr my point was that it does seem to scale up / down.. so this issue seems to be solved, not only closed,

**Comment by aremmes** [comment] 2019-05-14 14:09
Could this issue be reopened as a feature request? Having the ability to add extra servers/disks would be a great time saver. Requirements change over time, and having to mirror terabytes of data between deployments is an arduous process.
