### ISSUE TITLE
[fs] bucket policy does not work on windows

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3138] opened 2016-10-31 15:27 UTC
## Steps to Reproduce (for bugs)
1. mc policy both myminio/testbucket
2. `curl http://localhost:9000/testbucket/obj` gives Access denied.

## Your Environment
Windows 10

**Comment by vadmeste** [comment] 2016-11-01 18:55
@krishnasrinivas, I wasn't able to reproduce this with master mc and master windows.

> curl http://localhost:9000/testbucket/obj gives Access denied.

How do you use curl and localhost here? do you have curl under Windows?

**Comment by krishnasrinivas** [comment] 2016-11-01 19:00
> How do you use curl and localhost here? do you have curl under Windows?

yes, curl was available on the windows VM we have on aws. did the access to `http://localhost:9000/testbucket/obj` from browser work fine? i.e without any auth?

**Comment by vadmeste** [comment] 2016-11-01 19:02
> yes, curl was available on the windows VM we have on aws. did the access to http://localhost:9000/testbucket/obj from browser work fine? i.e without any auth?

yes, with a browser and without authentication.

**Comment by harshavardhana** [comment] 2016-11-01 19:07
I guess we can close this issue, the curl present on PowerShell is different than the regular `curl` available on Linux.

**Comment by harshavardhana** [comment] 2016-11-01 19:08
The issue i saw related to bucket policy not being able to send messages to its peers and not updating the policy.json - https://github.com/minio/minio/issues/3022

**Comment by vadmeste** [comment] 2016-11-01 19:11
oh, I've only tested with FS as the issue title suggested.

**Comment by krishnasrinivas** [comment] 2016-11-01 19:12
this is a minio-fs setup, it's on windows EC2 instance, just checked from browser too, it was getting access denied when the policy is `both` on the bucket.

**Comment by vadmeste** [comment] 2016-11-01 19:24
Can you check your version of minio and mc ? I tested again in my side and it looks fine

![capture-bucket-policy](https://cloud.githubusercontent.com/assets/283197/19903980/fd7fd70c-a070-11e6-942e-ef46eb2b7e13.PNG)

**Comment by krishnasrinivas** [comment] 2016-11-01 19:33
@vadmeste tried with latest minio/mc, still does not work, i might be doing some silly mistake, don't know, will message you the access details on gitter.

**Comment by harshavardhana** [comment] 2016-11-01 19:47
> this is a minio-fs setup, it's on windows EC2 instance, just checked from browser too, it was getting access denied when the policy is both on the bucket.

This is the same problem @krishnasrinivas it is related to bucket policies but it is related to how the "dial" is rejected by the RPC peer when updating policy.

**Comment by harshavardhana** [comment] 2016-11-01 19:48
> oh, I've only tested with FS as the issue title suggested.

It is with FS even with FS bucket policy updates send an RPC to itself, this is currently being fixed by @donatello

**Comment by vadmeste** [comment] 2016-11-01 20:04
> It is with FS even with FS bucket policy updates send an RPC to itself, this is currently being fixed by @donatello

:+1: , we need to test then with distributed because it seems there is another problem.

**Comment by harshavardhana** [comment] 2016-11-08 02:22
> , we need to test then with distributed because it seems there is another problem.

The bucket policy updates to localhost are fixed. This issue is closed by #3152 . Please re-open if seen again.

**Closed as completed by harshavardhana** 2016-11-08 02:22 UTC
