### ISSUE TITLE
[distributed] Stopping and restarting a node in the middle of a upload *always* returns XMinioWriteQuorum error

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3149] opened 2016-11-01 17:51 UTC
## Expected Behavior
If we have 4 running nodes, stopping and restarting a node during a *multipart* file upload shouldn't prevent that file to be uploaded again  

## Current Behavior
Cannot upload by that name anymore, even if I restart all nodes or restart upload.

## Steps to Reproduce (for bugs)
1. Start 4 nodes from fresh disks
2. Upload a 70mb file
3. Stop any container and start it again
4. Try to upload the same file again without changing the dest name.

## Your Environment
Docker edge

**Comment by donatello** [comment] 2016-11-02 06:21
@vadmeste Need more help with reproducing this one. I've tried the steps given above many times (though with a 480MB file, as i could not restart a container quickly with 70mb, for a local docker setup), but have been unable to reproduce this problem.

**Comment by vadmeste** [comment] 2016-11-02 09:09
> @vadmeste Need more help with reproducing this one. I've tried the steps given above many times (though with a 480MB file, as i could not restart a container quickly with 70mb, for a local docker setup), but have been unable to reproduce this problem.

The bug is systematic for me using docker-compose and docker stop/start. Ping me in chat for further investigation

**Comment by donatello** [comment] 2016-11-07 00:19
This appears to be an issue related to the need for healing. Here's what's happening:

During a multipart PUT, when a node is brought down, the `uploads.json` on it does not get deleted. In my testing, I was uploading to `stop.mp4` in the `mineo` bucket; during the upload I terminated and restarted node `minio2` (in 4 node setup `minio{1..4}`), and ended up with the following on-disk state:

```
# find . | grep mineo | grep '\.minio\.sys'
./minio2/.minio.sys/multipart/mineo
./minio2/.minio.sys/multipart/mineo/stop.mp4
./minio2/.minio.sys/multipart/mineo/stop.mp4/b0d08208-1da2-4bae-a494-054bf132b884
./minio2/.minio.sys/multipart/mineo/stop.mp4/b0d08208-1da2-4bae-a494-054bf132b884/xl.json
./minio2/.minio.sys/multipart/mineo/stop.mp4/uploads.json
./minio4/.minio.sys/multipart/mineo
./minio4/.minio.sys/multipart/mineo/stop.mp4
./minio3/.minio.sys/multipart/mineo
./minio3/.minio.sys/multipart/mineo/stop.mp4
./minio1/.minio.sys/multipart/mineo
./minio1/.minio.sys/multipart/mineo/stop.mp4
```

Now, when we ask mc to upload a large file back into the same location, it first checks for any incomplete uploads, and gets the upload id `b0d08208-1da2-4bae-a494-054bf132b884` (present on `minio2` above).

But when it tries to list the parts in this upload-id, it fails because `isUploadIDExists()` in ListObjectParts (in xl-v1-multipart.go) fails. Then it gives up. This is why it seems to be impossible to upload to the same object. But in fact this is possible with mc with a small (non-multipart) object and any sized object with awscli (as this tool does not try to resume any pending uploads). So either mc needs to handle the failing `list-parts` request, and start a new upload or the server needs healing (or both?).

As as aside, mc's implementation does not display the above mentioned uploadid during a list incomplete uploads request. awscli's implementation does work:

```
$ aws --endpoint-url http://localhost:9001/ s3api list-multipart-uploads --bucket mineo
{
    "Uploads": [
        {
            "Initiated": "2016-11-06T23:23:43.661Z",
            "StorageClass": "",
            "Key": "stop.mp4",
            "UploadId": "b0d08208-1da2-4bae-a494-054bf132b884",
            "Owner": {
                "ID": "",
                "DisplayName": ""
            },
            "Initiator": {
                "DisplayName": "",
                "ID": ""
            }
        }
    ]
}
```

This is probably ok, as the uploadid is not actually valid for continuing/completing/aborting.

If we want to avoid this situation, we need to use quorum for listing incomplete multipart uploads too.

**Comment by harshavardhana** [comment] 2016-11-07 18:26
'mc' should in-fact re-upload in this scenario when a given uploadID returns NoSuchUpload{}, its a bug in 'mc' .

**Comment by harshavardhana** [comment] 2016-11-07 18:26
But why would you get XMinioWriteQuorum ?

**Comment by donatello** [comment] 2016-11-07 18:31
I don't get XMinioWriteQuorum actually - maybe it is because of difference in mc version? @vadmeste could you update mc and retry, so we can be sure that we are seeing same problem? (I will too!).

**Comment by donatello** [comment] 2016-11-07 18:42
Just updated and tried now - https://github.com/minio/mc/issues/1874#issuecomment-258923271 - I just get

```
mc: <ERROR> Failed to copy ‘stop.mp4’. Object key is missing, object key cannot be empty
```

Complete debug log in the linked comment.

**Comment by vadmeste** [comment] 2016-11-07 18:45
I am still getting XMinioWriteQuorum with last minio/mc.

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioWriteQuorum</Code><Message>Multiple disks failures, unable to write data.</Message><Key></Key><BucketName></BucketName><Resource>/testbucket/1gb.bin</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error> 
```

**Comment by vadmeste** [comment] 2016-11-07 18:52
```
time="2016-11-07T18:50:57Z" level=error msg="Unable to create object part." cause="Storage resources are insufficient for the write operation." location="[object-handlers.go:691:objectAPIHandlers.PutObjectPartHandler()]" stack="xl-v1-object.go:337:rename xl-v1-object.go:353:renamePart xl-v1-multipart.go:485:xlObjects.PutObjectPart <autogenerated>:849:(*xlObjects).PutObjectPart object-handlers.go:688:objectAPIHandlers.PutObjectPartHandler api-router.go:47:(objectAPIHandlers).PutObjectPartHandler-fm" 
```

**Comment by vadmeste** [comment] 2016-11-07 18:56
`time="2016-11-07T18:55:17Z" level=error msg="Unable to create object part." cause="Storage resources are insufficient for the write operation." location="[object-handler
s.go:691:objectAPIHandlers.PutObjectPartHandler()]" stack="xl-v1-object.go:336:rename xl-v1-object.go:352:renamePart xl-v1-multipart.go:485:xlObjects.PutObjectPart <auto
generated>:849:(*xlObjects).PutObjectPart object-handlers.go:688:objectAPIHandlers.PutObjectPartHandler api-router.go:47:(objectAPIHandlers).PutObjectPartHandler-fm"`

Commit: 286a8924fd3780509590c82f17d2f874cc0846ea

(I've updated the stacktrace)

**Comment by vadmeste** [comment] 2016-11-07 19:21
In my case, here is what happens:
1. https://github.com/minio/minio/blob/master/cmd/xl-v1-multipart.go#L373, `errs` contains some 'file not found' since upload id doesn't exist in some disks. 
2. https://github.com/minio/minio/blob/master/cmd/xl-v1-multipart.go#L375,  `isDiskQuorum` won't consider `errs` (because file not found is not considered too)
3. https://github.com/minio/minio/blob/master/cmd/xl-v1-multipart.go#L382,  listOnlineDisks will return some nil disks since partsMetadata has some nil elements too
4. https://github.com/minio/minio/blob/master/cmd/xl-v1-multipart.go#L485 renamePart() returns XMinioWriteQuroum because some disks are nil

**Comment by donatello** [comment] 2016-11-07 19:42
@vadmeste During your test, can you confirm that you bring down one server during the upload and bring it back up **before** the upload completes?

**Comment by vadmeste** [comment] 2016-11-07 19:45
> @vadmeste During your test, can you confirm that you bring down one server during the upload and bring it back up before the upload completes?

oh sorry, I missed that detail.. Actually, I stop a container, wait until the upload completes, start the container again and then restart the upload with that same name.

**Comment by donatello** [comment] 2016-11-07 20:30
After some debugging with @vadmeste found that this is happening because mc is trying to resume the upload that was completed when one of the servers was down.

**Comment by harshavardhana** [comment] 2016-11-07 20:32
> After some debugging with @vadmeste found that this is happening because mc is trying to resume the upload that was completed when one of the servers was down.

This seems like can be fixed in `mc` will circle this with @abperiasamy and see what the best course of action.

**Comment by harshavardhana** [comment] 2016-11-10 02:20
Closing this as duplicate of #3169

**Closed as completed by harshavardhana** 2016-11-10 02:20 UTC
