### ISSUE TITLE
Using Https for minio server

### ISSUE THREAD

**Issue by Coder-212** [minio/minio#7329] opened 2019-03-05 16:16 UTC
I am trying to get a minio server to run on https but every time I try to run it I get the following error:

D:\APP\Minio>minio.exe server D:\APP\Storage
←7←[41m←[37m←[1mERROR←[0m←[0m←[0m ←8←[6C←[31mUnable to load the TLS configuratio
n: ←[1mThe parameter is incorrect.
←7←[41m     ←[0m ←8←[6C.←[0m←[0m

I have followed the following guide: https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls

And tried to generate my own self-signed Keys and Certificates but nothing seems to work... 
I placed the certificates inside the .minio/certs folder and named them public.crt and private.key. 
I have tried to re-generate the certs using generate_cert.go and GnuTLS methods over and over again but I am still getting that error message.

## Your Environment

* Version used (`minio version`):
Version: 2018-06-09T03:43:35Z
Release-Tag: RELEASE.2018-06-09T03-43-35Z
Commit-ID: 371349787f0e324f072b03ed5a7842229d6b3174
* Operating System and version (`uname -a`):
Windows Server 2012 R2 Standard x64

**Comment by kannappanr** [comment] 2019-03-05 20:44
@Coder-212 Maybe the algorithm in the keys generated are not supported by `Minio`. Will try to reproduce it and get back to you.

**Comment by Coder-212** [comment] 2019-03-06 15:09
@kannappanr thank you for your responsiveness, waiting for your feedback

**Comment by eco-minio** [comment] 2019-03-06 19:37
@Coder-212 You are using an older build, with your version I see the failure, with latest build it works.  Please upgrade and test again.

**Comment by ebozduman** [comment] 2019-03-07 01:12
@Coder-212,
I also could not reproduce the issue.
Could you tell us when you test it again with the latest build?

**Comment by Coder-212** [comment] 2019-03-07 10:58
Thank you @eco-minio 
It works very well with the last version.

**Comment by kannappanr** [comment] 2019-03-07 14:58
@Coder-212 Closing this issue. Please feel free to reach out to us on https://slack.min.io or open new issues here for future questions.

**Closed as completed by kannappanr** 2019-03-07 14:58 UTC
Labels: working as intended, community, priority: medium
