### ISSUE TITLE
Cannot store reserved characters on NTSF volumes

### ISSUE THREAD

**Issue by butonic** [minio/minio#2954] opened 2016-10-17 08:33 UTC
## Expected behaviour

Running minio on windows I should be able to store objects containing `:`, eg `urn:oid:1234`
## Actual behaviour

```
time="2016-10-15T00:08:38+02:00" level=error msg="Unable to create an object." cause="rename \\\\?\\C:\\Users\\jfd\\Programme\\minio\\data\\.minio.sys\\tmp\\eed894ca-a984-4f33-a34b-9bfafcbfc36c \\\\?\\C:\\Users\\jfd\\Programme\\minio\\data\\owncloud\\urn:oid:2055: The filename, directory name, or volume label syntax is incorrect."
```
## Steps to reproduce the behaviour

just create an object with `:` in the name.
## Minio version

```
Version: 2016-10-14T04:00:39Z
Release-Tag: RELEASE.2016-10-14T04-00-39Z
Commit-ID: 8c59a4166865e65192e91986e8bee329851bbf7c
```
## System information

Windows 10, minio on an NTFS volume which has these reserved characters:

```
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

**Comment by krishnasrinivas** [comment] 2016-10-17 08:50
> Windows 10, minio on an NTFS volume which has these reserved characters:
> : (colon)

Since minio uses backend FS to store objects it will not be able to create files with file name that has reserved characters.

**Comment by harshavardhana** [comment] 2016-10-18 06:46
Closing this as not a bug.

**Closed as completed by harshavardhana** 2016-10-18 06:46 UTC
Labels: working as intended, priority: low
