### ISSUE TITLE
Possible to increase number of disk on distributed minio cluster?

### ISSUE THREAD

**Issue by tomcsi** [minio/minio#5205] opened 2017-11-20 13:46 UTC
I have a distributed minio cluster from two nodes, and I would like to add more disks to cluster. Is this possible scenario?

**Comment by harshavardhana** [comment] 2018-02-23 23:24
Minio server now supports more than 16 number of disks.  You cannot still add more disks to the cluster, but you can start with more than 16 disks. 

Since we have decided not to implement dynamic expansion we can close this issue @deekoder

**Comment by deekoder** [comment] 2018-03-21 17:41
Since this is by design, I will close this issue as working as intended.  @tomcsi please see our guide on scaling https://docs.minio.io/docs/minio-deployment-quickstart-guide

**Closed as completed by deekoder** 2018-03-21 17:41 UTC
Labels: working as intended, priority: medium
