### ISSUE TITLE
[shared backend] Running two minio instances at the same time leads to failed initialization

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#3450] opened 2016-12-14 15:49 UTC
It is fine when I run one minio instance above NFS, but two instances can show the following errors:

Minio 1 output:
```
FATA[0001] intializing object layer failed               cause=Unable to recognize backend format, invalid character '{' after top-level value source=[server-main.go:491:serverMain()]
```

Minio 2 output:
```
FATA[0001] intializing object layer failed               cause=Unable to recognize backend format, invalid character '{' after top-level value source=[server-main.go:491:serverMain()]
```

**Comment by harshavardhana** [comment] 2016-12-14 16:07
This one did you run minio simultaneously ?

**Comment by vadmeste** [comment] 2016-12-14 16:08
> This one did you run minio simultaneously ?

yes

**Comment by vadmeste** [comment] 2016-12-14 16:10
> This one did you run minio simultaneously ?

Running two minio instances using a fresh backend (not initialized)

**Comment by harshavardhana** [comment] 2016-12-14 17:21
@vadmeste should be fixed in the latest push. Concurrent writes won't happen on format.json.

**Comment by vadmeste** [comment] 2016-12-14 21:58
I can't have the error above anymore (looks like I've done something wrong) let's forget it.. but I have a similar issue which is quite rare, I am running 100 Minio instances at the same moment still with NFS:

The error message is:
`FATA[0000] Initializing object layer failed              cause=Unable to load 'format.json', unexpected end of JSON input source=[server-main.go:490:serverMain()]`

I am using the following script:

```
#!/bin/bash
 
sudo rm -rf ./mount/.minio.sys
 
sudo killall minio
 
for i in {1..100}; do
   sudo -u nobody $(which minio) server --address ":$((9000+$i))" -C ./minioconfig mount/ &
done
```

**Comment by harshavardhana** [comment] 2016-12-14 23:41
Will test it.. @vadmeste  - thanks.

**Comment by harshavardhana** [comment] 2016-12-15 00:07
Not able to reproduce this with latest push to the PR @vadmeste .. was your NFS mount not mounted with "sync" ?

**Comment by harshavardhana** [comment] 2016-12-15 00:27
also share the commit id from 'git log' ?

**Comment by harshavardhana** [comment] 2016-12-15 01:38
I am able to reproduce this @vadmeste - looks like it takes a while..

**Comment by harshavardhana** [comment] 2016-12-15 01:50
Should be fixed now.. @vadmeste

**Closed as completed by harshavardhana** 2016-12-15 01:50 UTC
