### ISSUE TITLE
disconnecting a single node makes the cluster inoperable

### ISSUE THREAD

**Issue by chernykhse** [minio/minio#7273] opened 2019-02-22 07:47 UTC
we have a minio cluster on 7 nodes in 3 DC.
DC1: node 1, node 2, node 3
DC2: node 4, node 5, node 6
DC3: node 7
If we lose connection with any one of the nodes, we get many write errors from the applications.

test copying 1 file through mc, it takes about 3 minutes before the copying is completed. The next attempt at a test copy can happen immediately and maybe again be delayed by three minutes.
mc admin info shows a lot of errors
```
 172.21.8.252:9000
   Uptime: Server is offline
    Error: Post http://172.21.8.252:9000/minio/admin: read tcp 172.21.9.137Cl3228->172.21.8.252:9000: i / o timeout

? 172.21.8.253:9000
   Uptime: Server is offline
    Error: Post http://172.21.8.253:9000/minio/admin: read tcp 172.21.9.137:58190->172.21.8.253:9000: i / o timeout

? 172.21.9.132:9000
   Uptime: Server is offline
    Error: Post http://172.21.9.132:9000/minio/admin: read tcp 172.21.9.137:47766->172.21.9.132:9000: i / o timeout

? 172.21.9.133:9000
   Uptime: Server is offline
    Error: Post http://172.21.9.133:9000/minio/admin: read tcp 172.21.9.137:44458->172.21.9.133:9000: i / o timeout

? 172.21.9.138:9000
   Uptime: Server is offline
    Error: Post http://172.21.9.138:9000/minio/admin: read tcp 172.21.9.137:50602->172.21.9.138:9000: i / o timeout
```

## Expected Behavior

We expect that the ability to write and read will remain as long as more than (n / 2 + 1) discs are available.
## Current Behavior

At loss of communication with 1 node, (2 disks from 14 become inaccessible) the cluster becomes inoperative
## Steps to Reproduce (for bugs)

1. copy to 7 servers /usr/local/bin/minio
2. Create a minio user and group, set rights to the data folder
3. Copy /etc/default/minio, copy /etc/systemd/system/minio.service and replace with your IP and path to the data folder minio, systemctl daemon-reload; systemctl enable minio
4. Cut down the network at one of the nodes, or activate the blocking rules in the firewall.

## Your Environment

* Version used (`minio version`): 2018-12-06T01:27:43Z
* Server type and version: VM vmware
* Operating System and version (`uname -a`): Linux minio-node1 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2 (2017-06-12) x86_64 GNU/Linux
Runs through systemd
/etc/default/minio
/etc/systemd/system/minio.service

[minio.service.txt](https://github.com/minio/minio/files/2892882/minio.service.txt)

[minio_env.jinja.txt](https://github.com/minio/minio/files/2892883/minio_env.jinja.txt)

**Comment by nitisht** [comment] 2019-02-22 07:54
are these DCs geographically distributed @chernykhse ?
Also can you provide the configuration/command line used to deploy Minio?

**Comment by harshavardhana** [comment] 2019-02-22 07:56
Also @chersnky it would be helpful if you upgrade and do these testings against latest release.

**Comment by chernykhse** [comment] 2019-02-22 08:21
> are these DCs geographically distributed @chernykhse ?

> Also can you provide the configuration/command line used to deploy Minio?


all DCs are in the same city, network delays are 5 ms
command line
```
ExecStart=/usr/local/bin/minio server http://172.21.8.252:9000/mnt/minio/data1 http://172.21.8.252:9000/mnt/minio/data2 http://172.21.8.253:9000/mnt/minio/data1 http://172.21.8.253:9000/mnt/minio/data2 http://172.21.9.137:9000/mnt/minio/data1 http://172.21.9.137:9000/mnt/minio/data2 http://172.21.9.132:9000/mnt/minio/data1 http://172.21.9.132:9000/mnt/minio/data2 http://172.21.9.133:9000/mnt/minio/data1 http://172.21.9.133:9000/mnt/minio/data2 http://172.21.9.138:9000/mnt/minio/data1 http://172.21.9.138:9000/mnt/minio/data2 http://10.99.0.12:9000/mnt/minio/data1 http://10.99.0.12:9000/mnt/minio/data2
```
configuration:
Are there any other configurations besides what is contained in the attached files?
[minio.service.txt] = / etc / default / minio
[minio_env.jinja.txt] = /etc/systemd/system/minio.service

**Comment by chernykhse** [comment] 2019-02-22 08:34
> Also @chersnky it would be helpful if you upgrade and do these testings against latest release.

It is not possible to make an update quickly, there is already a lot of data in the cluster, and we need to make a full backup before the update and schedule downtime

**Comment by harshavardhana** [comment] 2019-02-22 08:34
> It is not possible to make an update quickly, there is already a lot of data in the cluster, and we need to make a full backup before the update and schedule downtime

an update is simply `minio update --quiet` and restart all servers in a rolling fashion? is that a problem?

**Comment by harshavardhana** [comment] 2019-02-22 08:38
> ```
> ExecStart=/usr/local/bin/minio server http://172.21.8.252:9000/mnt/minio/data1 http://172.21.8.252:9000/mnt/minio/data2 http://172.21.8.253:9000/mnt/minio/data1 http://172.21.8.253:9000/mnt/minio/data2 http://172.21.9.137:9000/mnt/minio/data1 http://172.21.9.137:9000/mnt/minio/data2 http://172.21.9.132:9000/mnt/minio/data1 http://172.21.9.132:9000/mnt/minio/data2 http://172.21.9.133:9000/mnt/minio/data1 http://172.21.9.133:9000/mnt/minio/data2 http://172.21.9.138:9000/mnt/minio/data1 http://172.21.9.138:9000/mnt/minio/data2 http://10.99.0.12:9000/mnt/minio/data1 http://10.99.0.12:9000/mnt/minio/data2
> ```

How is the routing working here with different subnets? - NOTE: we do not support multi-datacenter deployments for distributed setup.  Our latency requirements are single rack or even across racks within a DC.  It would better to measure how much of network bandwidth you have between these servers using `iperf`.  If you want DR like capabilities you should set up two clusters in different DCs and use `mc mirror` between them.

**Comment by chernykhse** [comment] 2019-02-22 08:47
> > It is not possible to make an update quickly, there is already a lot of data in the cluster, and we need to make a full backup before the update and schedule downtime
> 
> an update is simply `minio update --quiet` and restart all servers in a rolling fashion? is that a problem?

This is not a problem, but our corporate rules do not allow us to upgrade servers in production, without prior backup and an approved maintenance window. We will do it, not in the next hours.

**Comment by chernykhse** [comment] 2019-02-22 09:08
> How is the routing working here with different subnets?

Routing was configured by network administrators. What exactly do you need to ask?

**Comment by harshavardhana** [comment] 2019-02-22 09:19
> Routing was configured by network administrators. What exactly do you need to ask?

To start with `iperf` output between servers would be better preferably node 1 to node 2 and then across DC's between node1 to node7.

**Comment by chernykhse** [comment] 2019-02-22 13:09
> > Routing was configured by network administrators. What exactly do you need to ask?
> 
> To start with `iperf` output between servers would be better preferably node 1 to node 2 and then across DC's between node1 to node7.

node1 - > node2
```
iperf3 -c 172.21.8.253
Connecting to host 172.21.8.253, port 5201
[  4] local 172.21.8.252 port 33102 connected to 172.21.8.253 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  1.06 GBytes  9.12 Gbits/sec  121    888 KBytes
[  4]   1.00-2.00   sec   950 MBytes  7.97 Gbits/sec   61    691 KBytes
[  4]   2.00-3.00   sec  1020 MBytes  8.56 Gbits/sec    0    759 KBytes
[  4]   3.00-4.00   sec   956 MBytes  8.02 Gbits/sec    0    776 KBytes
[  4]   4.00-5.00   sec  1.00 GBytes  8.61 Gbits/sec   24    560 KBytes
[  4]   5.00-6.00   sec   979 MBytes  8.22 Gbits/sec    0    856 KBytes
[  4]   6.00-7.00   sec   982 MBytes  8.24 Gbits/sec    0   1.36 MBytes
[  4]   7.00-8.00   sec   981 MBytes  8.23 Gbits/sec    0   1.39 MBytes
[  4]   8.00-9.00   sec  1004 MBytes  8.42 Gbits/sec   10   1.15 MBytes
[  4]   9.00-10.00  sec   982 MBytes  8.24 Gbits/sec    0   1.24 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  9.73 GBytes  8.36 Gbits/sec  216             sender
[  4]   0.00-10.00  sec  9.73 GBytes  8.36 Gbits/sec                  receiver

iperf Done.
```

node1 -> node7
```
iperf3 -c 10.99.0.12
Connecting to host 10.99.0.12, port 5201
[  4] local 172.21.8.252 port 35056 connected to 10.99.0.12 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  19.4 MBytes   163 Mbits/sec   13    494 KBytes
[  4]   1.00-2.00   sec  19.2 MBytes   161 Mbits/sec    0    552 KBytes
[  4]   2.00-3.00   sec  19.6 MBytes   164 Mbits/sec    0    594 KBytes
[  4]   3.00-4.00   sec  19.9 MBytes   167 Mbits/sec    0    620 KBytes
[  4]   4.00-5.00   sec  20.1 MBytes   168 Mbits/sec    0    635 KBytes
[  4]   5.00-6.00   sec  20.1 MBytes   168 Mbits/sec    0    642 KBytes
[  4]   6.00-7.00   sec  19.7 MBytes   165 Mbits/sec    0    644 KBytes
[  4]   7.00-8.00   sec  19.7 MBytes   166 Mbits/sec    0    644 KBytes
[  4]   8.00-9.00   sec  20.0 MBytes   168 Mbits/sec    0    649 KBytes
[  4]   9.00-10.00  sec  20.0 MBytes   168 Mbits/sec    0    671 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec   198 MBytes   166 Mbits/sec   13             sender
[  4]   0.00-10.00  sec   196 MBytes   164 Mbits/sec                  receiver

iperf Done.
```
node1 -> node6 (DC1 -> DC2)
```
iperf3 -c 172.21.9.138
Connecting to host 172.21.9.138, port 5201
[  4] local 172.21.8.252 port 36032 connected to 172.21.9.138 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  1.01 GBytes  8.64 Gbits/sec   10   1.33 MBytes
[  4]   1.00-2.00   sec  1015 MBytes  8.52 Gbits/sec    0   1.46 MBytes
[  4]   2.00-3.00   sec  1007 MBytes  8.45 Gbits/sec    7   1.13 MBytes
[  4]   3.00-4.00   sec  1.01 GBytes  8.64 Gbits/sec    0   1.27 MBytes
[  4]   4.00-5.00   sec  1008 MBytes  8.46 Gbits/sec    5   1.00 MBytes
[  4]   5.00-6.00   sec   995 MBytes  8.35 Gbits/sec    0   1.19 MBytes
[  4]   6.00-7.00   sec  1018 MBytes  8.54 Gbits/sec    3   1.07 MBytes
[  4]   7.00-8.00   sec  1.00 GBytes  8.60 Gbits/sec    0   1.18 MBytes
[  4]   8.00-9.00   sec  1008 MBytes  8.45 Gbits/sec  196    979 KBytes
[  4]   9.00-10.00  sec   971 MBytes  8.15 Gbits/sec    0   1.18 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  9.87 GBytes  8.48 Gbits/sec  221             sender
[  4]   0.00-10.00  sec  9.87 GBytes  8.48 Gbits/sec                  receiver

iperf Done.
```

**Comment by harshavardhana** [comment] 2019-02-22 17:18
If you can see the non homogeneous nature here with network speeds is going to cause significant issues for us, we need consistent backend bandwidth. One is 8Gbits and another is 160Mbits is truly something is completely misconfigured on these systems.

We should fix these - especially the non consistent subnet i.e few nodes on 172.x and some on 10.x is not correct. Once all servers use the same network speed we can continue to test further.

**Comment by chernykhse** [comment] 2019-02-25 05:16
> If you can see the non homogeneous nature here with network speeds is going to cause significant issues for us, we need consistent backend bandwidth. One is 8Gbits and another is 160Mbits is truly something is completely misconfigured on these systems.

do you mean to work properly, we need to equalize the speed to 160Mbits between all nodes?

> We should fix these - especially the non consistent subnet i.e few nodes on 172.x and some on 10.x is not correct. Once all servers use the same network speed we can continue to test further.

to change the network you will need to re-create the cluster completely. Need time.

**Comment by chernykhse** [comment] 2019-02-25 05:28
We raised another test cluster on 4 nodes.
Network: 172.21.22.0/24
minio Version: 2019-02-20T22: 44: 29Z
with the same configs except command line:
ExecStart = /usr/local/bin/minio server http://172.21.22.{33...36}:9000/mnt/minio/data

We observe similar behavior:
Before shutting down the node
copy
```time mcc cp ../DockerImage.tar mid/test
...DockerImage.tar:  477.67 MB / 477.67 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 70.37 MB/s 6s
real    0m6.832s
user    0m2.125s
sys     0m0.485s
```
mc admin info 
```time mcc admin info mid
●  172.21.22.34:9000
   Uptime : online since 5 minutes ago
  Version : 2019-02-20T22:44:29Z
   Region : us-east-1
 SQS ARNs : <none>
    Stats : Incoming 751MiB, Outgoing 473KiB
  Storage : Used 38KiB
    Disks : 4, 0


●  172.21.22.35:9000
   Uptime : online since 6 minutes ago
  Version : 2019-02-20T22:44:29Z
   Region : us-east-1
 SQS ARNs : <none>
    Stats : Incoming 751MiB, Outgoing 480KiB
  Storage : Used 38KiB
    Disks : 4, 0


●  172.21.22.36:9000
   Uptime : online since 5 minutes ago
  Version : 2019-02-20T22:44:29Z
   Region : us-east-1
 SQS ARNs : <none>
    Stats : Incoming 751MiB, Outgoing 477KiB
  Storage : Used 38KiB
    Disks : 4, 0


●  172.21.22.33:9000
   Uptime : online since 6 minutes ago
  Version : 2019-02-20T22:44:29Z
   Region : us-east-1
 SQS ARNs : <none>
    Stats : Incoming 1.5GiB, Outgoing 97KiB
  Storage : Used 28KiB
    Disks : 4, 0



real    0m0.035s
user    0m0.012s
sys     0m0.000s
```

After `iptables -A INPUT -p tcp --dport 9000 -j DROP ; iptables -A OUTPUT -p tcp --dport 9000 -j DROP` on 172.21.22.35
copy
```time mcc cp ../DockerImage.tar mid/test
...DockerImage.tar:  477.67 MB / 477.67 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 65.38 MB/s 7s
real    9m17.751s
user    0m2.170s
sys     0m0.418s
```
mc admin info
```time mcc admin info mid
●  172.21.22.34:9000
   Uptime : Server is offline
    Error : rpc: retry error

●  172.21.22.35:9000
   Uptime : Server is offline
    Error : rpc: retry error

●  172.21.22.36:9000
   Uptime : Server is offline
    Error : rpc: retry error

●  172.21.22.33:9000
   Uptime : online since 15 minutes ago
  Version : 2019-02-20T22:44:29Z
   Region : us-east-1
 SQS ARNs : <none>
    Stats : Incoming 1.9GiB, Outgoing 127KiB
  Storage : Used 24KiB
    Disks : 3, 1



real    9m0.001s
user    0m0.032s
sys     0m0.032s
```
next try to same node:
```time mcc cp ../DockerImage.tar mid/test
...DockerImage.tar:  477.67 MB / 477.67 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 69.42 MB/s 6s
real    0m6.925s
user    0m2.108s
sys     0m0.438s
```
change mc node `config host add `

```time mcc cp ../DockerImage.tar mid/test
...DockerImage.tar:  477.67 MB / 477.67 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 1.86 MB/s 4m16s
real    4m16.896s
user    0m2.391s
sys     0m0.529s
```
usually the second attempt works fine, if I don’t change the node. When change node, the delay it appears again.

**Comment by chernykhse** [comment] 2019-03-11 11:28
up

**Comment by harshavardhana** [comment] 2019-03-11 13:42
@chernykhse we cannot reproduce this - I don't know what is going on in your environment.

**Comment by nitisht** [comment] 2019-03-27 16:54
@chernykhse closing this as not reproducible, feel free to reach out on Slack with more info if possible..

**Closed as completed by nitisht** 2019-03-27 16:54 UTC
Labels: working as intended, community, priority: medium
