### ISSUE TITLE
Support high number of users in IAM

### ISSUE THREAD

**Issue by christophemorio** [minio/minio#11305] opened 2021-01-19 15:51 UTC
## Expected Behavior
MinIO installed in gateway mode, is provisioned **with >500 users + policies**.
After a restart of the MinIO server, the users and policies should be available for usage. (thanks to etcd backend)

## Current Behavior
After a restart of the MinIO server, the users and policies are not available.
- user could not login
- `mc admin user info [...]` could not respond

## Steps to Reproduce
https://gist.github.com/christophemorio/eb67efd9819e89f778617ef5c6c8d705

1. start an etcd server
2. start a MinIO server in s3 gateway mode
3. run this script to provision many users
4. restart MinIO
5. query any user or policy => it returns a timeout, or item not found, with error logs on MinIO server

### Console logs
```
2021-01-19T14:51:14.600580431Z 
2021-01-19T14:51:14.600615626Z  You are running an older version of MinIO released 1 week ago 
2021-01-19T14:51:14.600620578Z  Update: Run `mc admin update` 
2021-01-19T14:51:14.600624063Z 
2021-01-19T14:51:14.600627338Z 
2021-01-19T14:51:14.601016356Z Endpoint:  http://172.17.0.5:9000  http://127.0.0.1:9000
2021-01-19T14:51:14.601030536Z 
2021-01-19T14:51:14.601034637Z Browser Access:
2021-01-19T14:51:14.601038867Z    http://172.17.0.5:9000  http://127.0.0.1:9000
2021-01-19T14:51:14.601042281Z 
2021-01-19T14:51:14.601079931Z Object API (Amazon S3 compatible):
2021-01-19T14:51:14.601089242Z    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
2021-01-19T14:51:14.601125754Z    Java:       https://docs.min.io/docs/java-client-quickstart-guide
2021-01-19T14:51:14.601375066Z    Python:     https://docs.min.io/docs/python-client-quickstart-guide
2021-01-19T14:51:14.601386686Z    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
2021-01-19T14:51:14.601391063Z    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
2021-01-19T14:51:43.830119487Z {"level":"warn","ts":"2021-01-19T14:51:43.829Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-ebbd6fcb-7268-4953-a1c7-135919bb5ec3/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
2021-01-19T14:51:43.83025429Z 
2021-01-19T14:51:43.830267145Z API: SYSTEM()
2021-01-19T14:51:43.830273081Z Time: 14:51:43 UTC 01/19/2021
2021-01-19T14:51:43.830290925Z DeploymentID: db2a4cf3-14bd-4e01-b26a-065aae081049
2021-01-19T14:51:43.830296712Z Error: Unable to initialize IAM sub-system, some users may not be available etcd is unreachable, please check your endpoints [http://etcd:2379] (*fmt.wrapError)
2021-01-19T14:51:43.830302529Z        1: cmd/iam.go:530:cmd.(*IAMSys).Init()
```

## Context
Server `RELEASE.2019-10-02T21-19-38Z` in gateway mode used to works fine with high number of users and policies (one per user).
The same users and policies fails to apply on `RELEASE.2021-01-05T05-22-38Z` after a restart of the server.

## Regression
This was not an issue for old server prior to ~RELEASE.2021-01-05T05-22-38Z~ RELEASE.2019-10-12T01-39-57Z.

## Your Environment
(test environment)
* Version used (`minio --version`):  `docker.io/minio/minio:RELEASE.2021-01-05T05-22-38Z`
* Server setup and configuration: minikube
* Operating System and version (`uname -a`): `Linux minikube 4.19.114 #1 SMP Mon Aug 3 12:35:22 PDT 2020 x86_64 GNU/Linux`
* one etcd v3.4.14 (cluster of a single member)
* one replicas of MinIO pod

**Comment by christophemorio** [comment] 2021-01-20 08:50
The problem still persist with a build from master.
Apparently #11151 does not solve the issue.

**Comment by christophemorio** [comment] 2021-01-20 08:53
Issue fixed by #11306 when encryption is disabled.

**Comment by harshavardhana** [comment] 2021-01-20 09:30
> Issue fixed by #11306 when encryption is disabled.

Unfortunately we cannot take that PR @christophemorio that is an incorrect way to do things.

**Comment by harshavardhana** [comment] 2021-01-20 09:31
> This was not an issue for old server prior to RELEASE.2021-01-05T05-22-38Z .

can you elaborate?

**Comment by christophemorio** [comment] 2021-01-20 09:33
My bad, I mean was not an issue before `RELEASE.2019-10-12T01-39-57Z` (edit description)

**Comment by mathieuherbert** [comment] 2021-01-20 09:51
@harshavardhana I can explain a bit more:
- we have X000 users and policy in our Minio setup
 We were with the release RELEASE.2019-10-12T01-39-57Z (without encryption) and we want to update to a new version. 
We did the update but we are facing the issue that minio cannot get the users and policy after the update (with the encrypted data in etcd). With the proposal we did (removing encryption) it is working well.

**Comment by harshavardhana** [comment] 2021-01-20 09:54
> * We did the update but we are facing the issue that minio cannot get the users and policy after the update (with the encrypted data in etcd). With the proposal we did (removing encryption) it is working well.

That proposal is not going to work we cannot have multiple ways to do the same thing, either we encrypt or we don't.  The issue looks like a problem when encryption migration is failing which needs to be fixed instead of leaving them unencrypted.

I will try to see why this is happening as it is expected to migrate unecrypted users safely.

**Comment by christophemorio** [comment] 2021-01-20 10:19
Not specifically a migration related issue.

We also start from a brand new setup with latest release, then recreate the users and policies through mc admin (link in issue description), that gives the same error.

**Comment by mathieuherbert** [comment] 2021-01-20 10:50
@harshavardhana  if you want to reproduce we changed the `Steps to Reproduce` in PR description

**Comment by harshavardhana** [comment] 2021-01-20 19:43
> 2021-01-19T14:51:43.830119487Z {"level":"warn","ts":"2021-01-19T14:51:43.829Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-ebbd6fcb-7268-4953-a1c7-135919bb5ec3/etcd:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

The main issue here is @mathieuherbert @christophemorio our context deadline is not enough, etcd is slow in your environment with lots of users. In my local setup I am able to start the service perfectly fine without any issues just using a local etcd. 

I am adding additional refactoring to make `GetUser, GetUserInfo` like calls directly served from etcd while MinIO tries to build its users in the background.

Unencrypting is not an option unfortunately @mathieuherbert @christophemorio

**Comment by mathieuherbert** [comment] 2021-01-21 18:09
Hi, 
We have now ETCD with 16GB of ram and 4VCPU. 
we created with mc admin 4 000 users and policies in Minio. We restarted the service and it is crashing. Is it possible to test this usecase on your side please ?

**Comment by harshavardhana** [comment] 2021-01-24 10:06
Here is the potential refactor to test out locally @mathieuherbert @christophemorio https://github.com/harshavardhana/minio/commit/8ebabdda9e99381bc01a5c3bc8971ce27765d4cd

**Comment by mathieuherbert** [comment] 2021-01-24 17:25
thanks @harshavardhana  ! I tested your branch with 2K users. I still have the issue. When I get a specific user it is working fine but when I list it is still failing. I will try to do more tests tomorrow.

**Comment by harshavardhana** [comment] 2021-01-24 18:49
> thanks @harshavardhana ! I tested your branch with 2K users. I still have the issue. When I get a specific user it is working fine but when I list it is still failing. I will try to do more tests tomorrow.

Of course I mentioned that listing is not that useful - authentication will always work and some basic GetUser, GetUserInfo will always work.

You let the server do the work in the background while you can authenticate the users normally and applications will work fine.

Main thing is server won't return "Invalid Access Key Id"  - all other management commands would block until the reload is finished in background.

**Comment by ToLToL** [comment] 2021-01-26 14:26
Hi,

I have the same problem. Everything worked perfectly with `RELEASE.2020-10-18T21-54-12Z` but when I try to upgrade MinIO version to `RELEASE.2020-10-27T04-03-55Z` or + I have:


```
{"level":"warn","ts":"2021-01-26T14:21:09.248Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"{etcd-endpoint}","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}

Error: Unable to initialize IAM sub-system, some users may not be available etcd is unreachable, please check your endpoints [{etcd-endpoint}]
```

**Comment by ToLToL** [comment] 2021-01-26 14:58
We have + 7k entries

**Comment by ToLToL** [comment] 2021-01-27 11:21
@harshavardhana @mathieuherbert @christophemorio do you have some news?

**Comment by ToLToL** [comment] 2021-01-27 12:03
@harshavardhana @mathieuherbert @christophemorio, maybe https://github.com/minio/minio/pull/10700 or https://github.com/minio/minio/pull/10719 from `RELEASE.2020-10-27T04-03-55Z` changed something?

I have this error with all releases after `RELEASE.2020-10-27T04-03-55Z`, and these are the 2 PRs related to IAM.

**Comment by harshavardhana** [comment] 2021-01-27 19:38
Closing this issue as it's sufficiently addressed to support large encrypted users - when the server is loading them background requests

- API calls fetch the user directly from etcd as a fallback
- UserInfo like calls also fetch directly from etcd as a fallback
- ListUsers `mc admin user list` might not finish quickly as the server loading them
  - clients are advised not to do it and let load them properly in background

**Closed as completed by harshavardhana** 2021-01-27 19:38 UTC
Labels: priority: low, community, fixed

**Comment by mathieuherbert** [comment] 2021-01-28 15:43
Hi, 
we tested the fix, but even after waiting a while we can't list users. we see this in the logs. 

```
API: SYSTEM()
Time: 12:47:18 UTC 01/28/2021
DeploymentID: f8cf1e9a-5c46-4b33-a789-2a27564291c1
Error: Unable to initialize IAM sub-system, some users may not be available etcd is unreachable, please check your endpoints [http://etcd.int.internal.lan:2379] (*fmt.wrapError)
       1: /go/minio/cmd/iam.go:649:cmd.(*IAMSys).Init()
```

**Comment by harshavardhana** [comment] 2021-01-28 19:17
> Hi,
> we tested the fix, but even after waiting a while we can't list users. we see this in the logs.
> 
> ```
> API: SYSTEM()
> Time: 12:47:18 UTC 01/28/2021
> DeploymentID: f8cf1e9a-5c46-4b33-a789-2a27564291c1
> Error: Unable to initialize IAM sub-system, some users may not be available etcd is unreachable, please check your endpoints [http://etcd.int.internal.lan:2379] (*fmt.wrapError)
>        1: /go/minio/cmd/iam.go:649:cmd.(*IAMSys).Init()
> ```

You have wait really long if you have such large users, as each of them are individually loaded.

What is the purpose of listing users?  If all the access credentials work for API calls?

**Comment by sgandon** [comment] 2021-02-26 10:49
Hello @harshavardhana , 
Correct me if I am wrong but it means that some APIs (like fetching all users) cannot be used at any given time when minio is active.
I have a question on this initial phase where all policies and users are loaded from etcd.
In a previous comment you said

> Main thing is server won't return "Invalid Access Key Id" - all other management commands would block until the reload is finished in background.

Does this mean that the creation of users will also block during this inital phase ?

**Comment by harshavardhana** [comment] 2021-02-26 18:16
> Does this mean that the creation of users will also block during this inital phase ?

It may I haven't thought about that usecase @sgandon are you experiencing problems with it?

**Comment by sgandon** [comment] 2021-03-01 13:58
Hi @harshavardhana , I am doing some checks on this issue and I have found that 3 APIs will not only wait for the initialization phase to finish but will also re-trigger the initialisation phase.
I have tested those admin calls during a long running initialization phase (2000 users).

| command | sucess | what it does |
|---|---|---|
admin user info|               :heavy_check_mark: | get user info.
admin user add|               :heavy_check_mark: | add a user
admin policy info|            :x:| get policy info (this will trigger a new reload of users, policies and mapping)
admin policy add|            :heavy_check_mark:| add a policy
admin policy set|             :heavy_check_mark:| set a policy to a user
admin policy list|             :x:| list all policies  (this will trigger a new reload of users, policies and mapping)
admin user list|                :x:| list all user  (this will trigger a new reload of users, policies and mapping)

So everytime one of these 3 apis (with the red cross) are called, there is a call to [this method](https://github.com/minio/minio/blob/0b9c17443eb809be94bba93b1be98e587a1951a0/cmd/iam.go#L446) that loads all the users, policies and mappings, and it is called again and again for each call hence defering the chance to have this call succeeding.

**Comment by klauspost** [comment] 2021-03-01 15:13
@sgandon Thanks for the investigation. Correct, it will start *another* load operation if the first on startup hasn't finished. Not that productive, agreed.

It will not currently block. I will make a PR that *does* block and not retrigger another load since that is counterproductive.

Blocking calls will be `ListPolicies`, `ListUsers`, `ListServiceAccounts`, `ListGroups` - and the calls that eventually trigger these. Sending a PR. These will wait for the initial load to complete.

Making user loading concurrent is generally a bigger task, and not currently something requested by our subscribers.

**Comment by sgandon** [comment] 2021-03-01 16:06
@klauspost this is fantastic, thanks a lot for the PR.
There are other issues that I have found that I' like to talk to someone about.

1/ during the initialization phase the etcd api are called for each user, each policy and each mapping... this sometimes create the following error `Error: Unable to initialize IAM sub-system, some users may not be available etcd is unreachable`. I have implmented a fix (locally) that does get all keys and values in one request and not one by one. This fixes the etcd issue. 
I can submit a PR if you think it is interesting ? (I was hoping it improves the performances of the ini phase but read the part 2 to see how this fix does not help on perfs)

2/ I have done some profiling during the loading of users, policies and mappings, and it turns out that the Argon library used for decryption is perfoming poorly.  
Here is an example for 400 policies.  
```
go tool pprof cpuprofile.prof
Type: cpu
Time: Feb 25, 2021 at 7:13pm (CET)
Duration: 7.72s, Total samples = 19.28s (249.62%)
(pprof) top10
Showing nodes accounting for 18.82s, 97.61% of 19.28s total
Dropped 55 nodes (cum <= 0.10s)
Showing top 10 nodes out of 50
      flat  flat%   sum%        cum   cum%
     7.19s 37.29% 37.29%      7.19s 37.29%  runtime.pthread_cond_wait
     5.67s 29.41% 66.70%      5.67s 29.41%  github.com/minio/minio/pkg/argon2.blamkaSSE4
     1.93s 10.01% 76.71%      1.93s 10.01%  github.com/minio/minio/pkg/argon2.mixBlocksSSE2
     1.74s  9.02% 85.74%      1.74s  9.02%  runtime.pthread_cond_signal
     1.08s  5.60% 91.34%      1.08s  5.60%  github.com/minio/minio/pkg/argon2.xorBlocksSSE2
```
it takes 7.72 seconds to load all policies and more 7 seconds are taken by the decryption !!!  
This explains why the initialization of Minio can be very slow ( I have more figures if required).

**Comment by klauspost** [comment] 2021-03-01 17:09
Argon2 is slow by design so remote data is secure. I don't know the details for this, but I am not sure much can be done about that.

At least #11671 will make sure that there isn't competition for the CPU.

**Comment by sgandon** [comment] 2021-03-01 17:54
thanks for your answer, 
well about securing remote data, I am not sure that policies require that level of security, this of course a different story for the credentials (user/password/sts tokens).

**Comment by harshavardhana** [comment] 2021-03-01 18:01
> thanks for your answer,
> well about securing remote data, I am not sure that policies require that level of security, this of course a different story for the credentials (user/password/sts tokens).

The approach was simple @sgandon all the config sub-system gets encrypted.

**Comment by ToLToL** [comment] 2021-03-01 18:13
I have the same issue as @sgandon for `Error: Unable to initialize IAM sub-system, some users may not be available etcd is unreachable` (5k users) even after 1 day.

**Comment by sgandon** [comment] 2021-03-01 18:17
@ToLToL I believe I  have managed to fix this issue on my machine but I'd like to know if the guys managing this project are ok with my way of solving this issue. 
Basically during the initlializing phase instead of doing one query to get the etcd values one by one for each policies then for each users, I do a single query to get them all at once. All policies at once to avoid to many calls on the etcd backend, then all users at onces, etc...

**Comment by sgandon** [comment] 2021-03-01 18:21
> > thanks for your answer,
> > well about securing remote data, I am not sure that policies require that level of security, this of course a different story for the credentials (user/password/sts tokens).
> 
> The approach was simple @sgandon all the config sub-system gets encrypted.

I understand this but this has a big costs.
here is the initialization timing for 10 000 policies, 10 000 users (and of course the same number for the mappings)
```
[2021-03-01 17:39:11]    extracting policies                <- 3:13 mn
[2021-03-01 17:42:24] Setting default canned policies        
[2021-03-01 17:42:24] Loading all MinIOUsersSys  users      <- 3:12 mn
[2021-03-01 17:45:36] Loading mapped policies               <- 3:45 mn
[2021-03-01 17:49:21] Loading all users
                                                           ----------
                                                             = 10:10 mn
```
As mentionned above the etcd calls are negligable, only the Argon decryption is accounting for those figures.  (in fact the mapped policies is bigger because I did not yet implement the single etcd call for both keys and values)

**Comment by harshavardhana** [comment] 2021-03-01 18:27
> As mentionned above the etcd calls are negligable, only the Argon decryption is accounting for those figures. (in fact the mapped policies is bigger because I did not yet implement the single etcd call for both keys and values)

None of that can be changed right now, unfortunately, it requires a complete migration and it's a very tricky road.

**Comment by justinclift** [comment] 2021-07-18 08:21
It kind of sounds like a more optimal solution would be to make the encryption scheme configurable, so less cpu-intensive alternatives to Aargon can be used.  That'd allow for Minio to better work with the use cases where the configuration data doesn't need that level of security.

**Comment by harshavardhana** [comment] 2021-07-18 16:32
> It kind of sounds like a more optimal solution would be to make the encryption scheme configurable, so less cpu-intensive alternatives to Aargon can be used. That'd allow for Minio to better work with the use cases where the configuration data doesn't need that level of security.

This has been fixed already @justinclift
