### ISSUE TITLE
service not accessible and no logs after deployed with kubernetes

### ISSUE THREAD

**Issue by neo-feng** [minio/minio#8523] opened 2019-11-14 11:16 UTC
I deployed distributed minio servers in kubernetes using yaml file option as stated here - https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/k8s-yaml.md 
I followed guide above strictly, except that I added secret-volume to make ssl work
## Expected Behavior

all pods lauched and service accessible from browser

## Current Behavior

all pods lauched with no issues, however, service is not accessible from browser
and no logs at all from any pod (kubectl logs -n xxx minio-0) -- this is the most strange part

And standalone deployment is working and verified, only distributed one failed.

## Steps to Reproduce (for bugs)

1. deploy local storage in kubernetes
2. create secret for secret-volume
3. deploy minio via yaml files
4. try to access https://nodeip:port/minio/login

## Your Environment

* Version used (`minio version`): image: minio/minio:RELEASE.2019-10-12T01-39-57Z
* Environment name and version (e.g. nginx 1.9.1): kubernetes 1.15.2
* Server type and version: kubernetes 1.15.2
* Operating System and version (`uname -a`): centos 7.3

my yaml file: 
```
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: minio
  selector:
    app: minio
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: timezone-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: secret-volume
        secret:
          secretName: tls-ssl-minio
          items:
          - key: public.crt
            path: public.crt
          - key: private.key
            path: private.key
          - key: public.crt
            path: CAs/public.crt       
      containers:
      - name: minio
        env:
        - name: MINIO_ACCESS_KEY
          value: "xxxxxx"
        - name: MINIO_SECRET_KEY
          value: "xxxxx"
        image: minio/minio:RELEASE.2019-10-12T01-39-57Z
        args:
        - server
        - http://minio-{0...3}.minio.default.svc.cluster.local/data
        ports:
        - containerPort: 9000
        # These volume mounts are persistent. Each pod in the PetSet
        # gets a volume mounted based on this field.
        volumeMounts:
        - name: data
          mountPath: /data
        - name: timezone-config
          mountPath: /etc/localtime  
        - name: secret-volume
          mountPath: /root/.minio/certs           
          
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      # Uncomment and add storageClass specific to your requirements below. Read more https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
      storageClassName: {{storageClassName}}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 35009
      protocol: TCP
  selector:
    app: minio
```

any suggestion is appreciated.

**Comment by kannappanr** [comment] 2019-11-14 14:11
@neo-feng We will take a look at this issue and get back to you.

**Comment by nitisht** [comment] 2019-12-03 11:36
@neo-feng are you able to access the distributed cluster from other clients e.g. `mc` ?

**Comment by neo-feng** [comment] 2019-12-03 15:19
@nitisht No, I cannot,  there was no logs from the pods, it seems minio inside container didn't launch at all. 
Good news is that I reinstall distributed minio cluster via Helm and everything works fine, so it should be a problem of the YAML WAY.

**Comment by nitisht** [comment] 2019-12-03 15:51
YAML setup works, and has been tested numerous times. If you'd like investigate this further, we can take a look at `kubectl describe pods <pod-name>` output

**Comment by neo-feng** [comment] 2019-12-03 16:04
So it should be a minor issue inside my yaml template. I checked kubectl describe pods <pod-name> output and everything seems fine, all 4 pods' status are running, and kubectl logs <pod-name> is empty for all pods. Are there any other logs I can check? 
Another thing I can do is to locate the yaml files generated by Helm and compare with my template above.

**Comment by nitisht** [comment] 2019-12-03 17:31
>  all 4 pods' status are running, and kubectl logs is empty for all pods. Are there any other logs I can check?

Logs should atleast have MinIO startup banner, which means server started up successfully. Comparing with helm yaml should give you an idea

**Comment by tomsherrod** [comment] 2019-12-03 18:40
I had this same problem...
 - http://minio-{0...3}.minio.default.svc.cluster.local/data   looks fine...except minio was deployed into a namespace NOT default. Once the url/name was changed, logs began coming out.

**Comment by neo-feng** [comment] 2019-12-04 02:22
@tomsherrod did you figure it out?

**Comment by nitisht** [comment] 2019-12-04 04:32
@neo-feng are you using default namespace or something else?

**Comment by neo-feng** [comment] 2019-12-04 05:38
@nitisht not default, my namespace is 'minio'.

**Comment by nitisht** [comment] 2019-12-04 06:01
then please try http://minio-{0...3}.minio.minio.svc.cluster.local/data

in the yaml

**Comment by neo-feng** [comment] 2019-12-04 06:38
good point, thanks for the insight, I'll try it soon

**Comment by nitisht** [comment] 2019-12-04 07:14
Thanks @neo-feng closing this as working as intended, please let us how it goes. For further questions please join us on Slack (https://slack.min.io)

**Closed as completed by nitisht** 2019-12-04 07:14 UTC
Labels: working as intended, community, priority: medium
