### ISSUE TITLE
aws-sdk-java-v2 cannot extract 'x-amz-meta-' metadata due case-sensitivity

### ISSUE THREAD

**Issue by rezss** [minio/minio#7280] opened 2019-02-23 19:53 UTC
Hi,
i played a bit more with the software.amazon.awssdk:s3:2.4.14 and figured out that it cannot receive object metadata from minio due case-sensitivity-mismatch.

The [amazon sdk is looking explicitly](https://github.com/aws/aws-sdk-java-v2/blob/985ec92c0dfac868b33791fe4623296c68e2feab/core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/unmarshall/HeaderUnmarshaller.java#L42) for the 'x-amz-meta-' header, but minio sends - unfortuantely - a 'X-Amz-Meta-' header.

An excerpt from the `software.amazon.awssdk.services.s3.model.HeadObjectResponse`

```java
private static final SdkField<Map<String, String>> METADATA_FIELD = SdkField
        .<Map<String, String>> builder(MarshallingType.MAP)
        .getter(getter(HeadObjectResponse::metadata))
        .setter(setter(Builder::metadata))
        .traits(LocationTrait.builder().location(MarshallLocation.HEADER).locationName("x-amz-meta-")
                .unmarshallLocationName("x-amz-meta-").build(),
                MapTrait.builder()
                        .keyLocationName("key")
                        .valueLocationName("value")
                        .valueFieldInfo(
                                SdkField.<String> builder(MarshallingType.STRING)
                                        .traits(LocationTrait.builder().location(MarshallLocation.PAYLOAD)
                                                .locationName("value").unmarshallLocationName("value").build()).build())
                        .build()).build();
```

## Expected Behavior
aws sdk v2 is able to receive the x-amz-meta data provided by minio

## Current Behavior
aws sdk v2 is unable to receive the x-amz-meta data provided by minio

## Steps to Reproduce (for bugs)
1. Download the docker minio image with id af49f6661d6a
2. Use the java software.amazon.awssdk:s3:2.4.14 sdk
3. Upload a file with meta-data and provide the following code:

```java
var s3 = S3Client
    .builder()
    .region(region)
    .endpointOverride(URI.create(endpointUrl))
    .overrideConfiguration(c -> c.putAdvancedOption(SdkAdvancedClientOption.SIGNER, AwsS3V4Signer.create()))
    .credentialsProvider(StaticCredentialsProvider.create(credentials))
    .build();

var headResponse = s3.headObject(b -> b.bucket(bucketName).key(key));
headResponse.metadata().forEach((k, v) -> System.out.println(k + ": " + v));
```

The metadata map is empty.

## Workaround
```java
var headResponse = s3.headObject(b -> b.bucket(bucketName).key(key));
var metaData = headResponse
    .sdkHttpResponse()
    .headers()
    .entrySet()
    .stream()
    .filter(x -> x.getKey().toLowerCase().startsWith("x-amz-meta-"))
    .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));

metaData.forEach((k, v) -> System.out.println(k + ": " + v));
```

## Your Environment

* Version used (`minio version`): 2019-02-20T22:44:29Z

**Comment by harshavardhana** [comment] 2019-02-23 19:53
HTTP headers are case insensitive it is aws-sdk-java bug

**Comment by harshavardhana** [comment] 2019-02-23 19:58
This was fixed in https://github.com/aws/aws-sdk-java/issues/704 looks like this is a regression again introduced in aws-sdk-java-v2 version

**Closed as completed** 2019-02-23 19:58 UTC
Labels: priority: low, community, out of scope

**Comment by rezss** [comment] 2019-02-23 20:25
I opened an issue: https://github.com/aws/aws-sdk-java-v2/issues/1091
