### ISSUE TITLE
GCS Gateway - CopyObject: io: read/write on closed pipe

### ISSUE THREAD

**Issue by jared-hess** [minio/minio#8918] opened 2020-01-31 03:00 UTC
With minio running as GCS gateway in docker, When trying to copy a file from one bucket to another using the "copy_object" method, the minio server throws an io error:
```
minio_1           | 
minio_1           | API: CopyObject(bucket=<redacted>, object=<redacted>)
minio_1           | Time: 02:45:47 UTC 01/29/2020
minio_1           | RequestID: <redacted>
minio_1           | RemoteHost: 192.168.16.11
minio_1           | UserAgent: MinIO (Linux; x86_64) minio-py/5.0.6
minio_1           | Error: io: read/write on closed pipe
minio_1           |        2: cmd/gateway/gcs/gateway-gcs.go:788:gcs.(*gcsGateway).GetObject()
minio_1           |        1: cmd/gateway/gcs/gateway-gcs.go:750:gcs.(*gcsGateway).GetObjectNInfo.func1()
```

The file does appear to be copied successfully, however.
I've also tried this on a couple different versions including :latest with same behavior.

## Current Behavior
Object is copied successfully, but throws an IO error.

## Steps to Reproduce (for bugs)
With minio running as gcs gateway, simply using the copy_object method should reproduce. Using the mc command line client does not reproduce the issue, however.

## Your Environment

* Version used (`minio version`): 2019-05-14T23:57:45Z
* Environment name and version (e.g. nginx 1.9.1): python:3.7.3
* Server type and version: Docker version 19.03.5, build 633a0ea

**Comment by harshavardhana** [comment] 2020-02-01 01:52
Please upgrade to latest and let us know.

**Comment by ebozduman** [comment] 2020-02-25 00:35
Hi @jared-hess ,

I've tried to reproduce the issue with the latest MinIO code from the top of tree (master), using Golang Client API (minio-go) `CopyObject` command and I did not see/hit any problem. The file is copied over onto the destination side correctly.

As @harshavardhana suggested, we would like you to upgrade and go through your reproduction steps one more time to see if the issue is still happening in your setup. If it is, please send us your script for us to try it out here in our setup.

**Comment by kannappanr** [comment] 2020-05-20 21:33
@jared-hess I tried with the latest docker image and did not see any issue with the copy object. Closing this issue right now. Please feel free to reach out to us if you still see the issue

**Closed as completed by kannappanr** 2020-05-20 21:33 UTC
Labels: working as intended, priority: low
