### ISSUE TITLE
Bucket Lifecycle Policy does not deleted objects on disk in single mode (RELEASE.2020-06-03)

### ISSUE THREAD

**Issue by markush81** [minio/minio#9805] opened 2020-06-11 07:57 UTC
Bucket Lifecycle Policy does not deleted objects

While in https://github.com/minio/minio/issues/9804 with old version RELEASE.2020-02-27T00-23-05Z i had this wrong behaviour only in **cluster** mode, with new version RELEASE.2020-06-03T22-13-49Z it does not even work in **single** mode. 

## Expected Behavior
Objects get deleted.

## Current Behavior
Objects are not getting deleted

## Steps to Reproduce (for bugs)
1. Create Single minio node
```
version: '3.7'
services:
  minio:
    image: minio/minio:RELEASE.2020-02-27T00-23-05Z
    volumes:
      - data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
```
2. Add Bucket Lifecycle policy
```
markus@lucky ➜  ~  date; AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 aws s3api get-bucket-lifecycle-configuration --bucket nexus-single --endpoint-url http://localhost:9000
Thu Jun 11 09:33:01 CEST 2020
{
    "Rules": [
        {
            "Filter": {
                "Tag": {
                    "Value": "true",
                    "Key": "deleted"
                }
            },
            "Status": "Enabled",
            "Expiration": {
                "Days": 1
            },
            "ID": "Expire soft-deleted objects in blobstore minio-single"
        }
    ]
}
```
3. Upload Content, Check Filesystem and Tags
```
markus@lucky ➜  ~ date; docker container exec docker_minio_1 ls -alh /data/nexus-single/content/vol-02/chap-04/16337bc5-3c08-4b02-a648-a213b4de9b21.bytes
Thu Jun 11 09:34:48 CEST 2020
-rw-r--r--    1 root     root       41.3K Jun 11 07:34 /data/nexus-single/content/vol-02/chap-04/16337bc5-3c08-4b02-a648-a213b4de9b21.bytes


markus@lucky ➜  ~ date; AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 aws s3api get-object-tagging --bucket nexus-single --key content/vol-02/chap-04/16337bc5-3c08-4b02-a648-a213b4de9b21.bytes --endpoint-url http://localhost:9000
Thu Jun 11 09:35:46 CEST 2020
{
    "TagSet": []
}
```
4. Set deleted=true
```
markus@lucky ➜  ~ date; AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 aws s3api get-object-tagging --bucket nexus-single --key content/vol-02/chap-04/16337bc5-3c08-4b02-a648-a213b4de9b21.bytes --endpoint-url http://localhost:9000
Thu Jun 11 09:38:28 CEST 2020
{
    "TagSet": [
        {
            "Value": "true",
            "Key": "deleted"
        }
    ]
}
```
5. Forward System Clock and wait
```
markus@lucky ➜  ~ date; docker container exec docker_minio_1 ls -alh /data/nexus-single/content/vol-02/chap-04/16337bc5-3c08-4b02-a648-a213b4de9b21.bytes
Sun Jun 14 09:44:32 CEST 2020
-rw-r--r--    1 root     root       41.3K Jun 11 07:34 /data/nexus-single/content/vol-02/chap-04/16337bc5-3c08-4b02-a648-a213b4de9b21.bytes
```

Using **old version RELEASE.2020-02-27T00-23-05Z in single** setup, file was deleted nearly **immediately**.

## Regression
i guess so, since it worked out with RELEASE.2020-02-27T00-23-05Z.

## Your Environment
* Version used (`minio version`): RELEASE.2020-06-03T22-13-49Z

**Comment by harshavardhana** [comment] 2020-06-11 09:03
Closing this as duplicate of #9804

**Comment by markush81** [comment] 2020-06-11 09:16
@harshavardhana actually i do not think it is a real duplicate, one is about single node and one about cluster, there is different behaviour in different versions. so in case then #9804 has to be enhance with single and cluster mode.

**Comment by vadmeste** [comment] 2020-06-11 10:31
@markush81 forwarding the system clock is not enough, you still need to wait for 24 hours (or less) until you see the lifecycle triggered.

**Comment by markush81** [comment] 2020-06-11 10:41
> @markush81 forwarding the system clock is not enough, you still need to wait for 24 hours (or less) until you see the lifecycle triggered.

did this change in some version? did same test with RELEASE.2020-02-27T00-23-05Z and it took not even 5min. and the file got deleted, after forwarding system clock.

**Comment by markush81** [comment] 2020-06-11 10:41
Btw. is there any logging which i can activate to see the lifecycle events? So far i only know how to see http trace.

**Comment by vadmeste** [comment] 2020-06-11 10:44
> did this change in some version? did same test with RELEASE.2020-02-27T00-23-05Z and it took not even 5min. and the file got deleted.

yes, before lifecycle is triggered when you start MinIO server, but then we decided to report it for 24 hours.

> Btw. is there any logging which i can activate to see the lifecycle events? So far i only know how to see http trace.

What you can do is issue this call: `aws s3api head-object --endpoint http://localhost:9000 --bucket your-bucket --key your-object`, it should show `expiry_time` which predicts when the object will be removed.

**Comment by markush81** [comment] 2020-06-11 10:46
> yes, before lifecycle is triggered when you start MinIO server, but then we decided to report it for 24 hours.

i am not sure if i get the part "when you start MinIO server", lifecycle should be executed always right? not just at startup.
 
> What you can do is issue this call: `aws s3api head-object --endpoint http://localhost:9000 --bucket your-bucket --key your-object`, it should show `expiry=time` which predicts when the object will be removed.

ok i'll give it another try with latest version.

**Comment by vadmeste** [comment] 2020-06-11 10:50
> i am not sure if i get the "when you start MinIO server", lifecycle should executed always right? not just at startup.

Yes, lifecycle is always executed but once each 24 hours. But, it is not executed immediately after you start your server. You will have to wait 24 hours first.

**Comment by markush81** [comment] 2020-06-11 10:54
> > i am not sure if i get the "when you start MinIO server", lifecycle should executed always right? not just at startup.
> 
> Yes, lifecycle is always executed but once each 24 hours. But, it is not executed immediately after you start your server. You will have to wait 24 hours first.

So this is expected behaviour with latest version.

But so far to me it seems old version RELEASE.2020-02-27 behave different in single and cluster mode. But ok maybe we forget old version if new one works.

**Comment by markush81** [comment] 2020-06-11 11:04
Ok so i did now suggested call in #9805 and wait until expire-time has gone by

```
markus@lucky ➜  docker date; AWS_ACCESS_KEY_ID=minio AWS_SECRET_ACCESS_KEY=minio123 aws s3api head-object --endpoint http://localhost:9000 --bucket nexus --key content/vol-03/chap-30/d2d5eae4-4d76-4417-923f-f4538e1cd6c4.bytes
Thu Jun 11 13:02:59 CEST 2020
{
    "AcceptRanges": "bytes",
    "ContentType": "application/octet-stream",
    "LastModified": "Thu, 11 Jun 2020 10:57:40 GMT",
    "ContentLength": 42296,
    "ETag": "\"1cd78190492e366d0707e0a8976f0632\"",
    "Expiration": "expiry-date=\"Sat, 13 Jun 2020 00:00:00 GMT\", rule-id=\"Expire soft-deleted objects in blobstore minio\"",
    "Metadata": {}
}
```

in case it get's deleted by then we can close this ticket.

**Comment by harshavardhana** [comment] 2020-06-12 03:20
> in case it get's deleted by then we can close this ticket.

Closing this please re-open if it doesn't delete.

**Closed as completed by harshavardhana** 2020-06-12 03:20 UTC
Labels: community
