### ISSUE TITLE
ecosystem: Support SSL for  cloudberry MBS

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4184] opened 2017-04-26 23:05 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment] 2017-04-26 23:26
Duplicate of #4017

**Closed as completed** 2017-04-27 00:32 UTC
Labels: duplicate, priority: high
