### ISSUE TITLE
Minio JS client copyObject broken on Google Cloud Storage

### ISSUE THREAD

**Issue by ericvicenti** [minio/minio#6036] opened 2018-06-12 18:34 UTC
## Expected Behavior

copyObject should work on Google Cloud Storage

## Current Behavior

Google cloud throws a permission error "does not have storage.objects.get access" about a user who does have read access!

## Possible Solution

I don't have time to debug minio right now, instead I just switched to `@glcoud/storage`

```
  const storage = require('@google-cloud/storage')();
  const gBucket = storage.bucket(bucket);
...
      const { resource } = await gBucket.file(from).copy(to);
      return resource.etag;
```

## Steps to Reproduce (for bugs)

1. Set up minio with GCS storage
2. Upload a doc to a bucket, read it back just fine
3. use copyObject to copy file to a different location in the same bucket

## Context

Minio is supposed to work equally well on GCS!

## Your Environment

Experienced on my local mac as well as nodejs production

NPM version of minio: 5.0.2

**Comment by donatello** [comment] 2018-06-15 00:04
If you are using the minio server as a gateway, could you specify the version of minio you are using? From the above description it is not clear if the issue is in the JS client library or in the minio server itself.

**Comment by harshavardhana** [comment] 2018-09-27 02:16
> If you are using the minio server as a gateway, could you specify the version of minio you are using? From the above description it is not clear if the issue is in the JS client library or in the minio server itself.

@ericvicenti do you have more information that was requested? feel free to close it if its not an issue anymore.

**Comment by harshavardhana** [comment] 2019-02-07 01:47
Closing this as an unresponsive/stale issue..

**Closed as completed by harshavardhana** 2019-02-07 01:47 UTC
Labels: working as intended, priority: medium
