### ISSUE TITLE
Multipart upload regression from RELEASE.2021-02-24T18-44-45Z to RELEASE.2021-04-06T23-11-00Z (latest)

### ISSUE THREAD

**Issue by kevinlul** [minio/minio#12043] opened 2021-04-12 16:17 UTC
## Expected Behavior
`mc cp LARGE_FILE minioserver/BUCKET_NAME` should just work.

## Current Behavior
For sufficiently large files (tested with a 35 MB file and reproduced with even larger ones), `mc` uses multipart uploads, and they fail with the following message:

mc: <ERROR> Failed to copy `LARGE_FILE`. We encountered an internal error, please try again.: cause(open /data/.minio.sys/multipart/c55717a43c1e7e1021cfe395b49b0eb70efd3b1952ea5c8849854468a2a0a789/97f41ebd-c82f-47d0-934c-e5107053a744/fs.json: operation not permitted)

The long UUIDs change with every transfer. This does not occur with regular files that transmit the entire file in a single PUT request.

`mc admin console` trimmed output:
```
 API: PutObjectPart(bucket=BUCKET_NAME, object=LARGE_FILE)
 Time: 13:27:35 UTC 04/12/2021
 DeploymentID: 5868a74e-86b5-4747-9963-59649a92f91d
 RequestID: 16751F4CD0F0B8FB
 RemoteHost: IPv4_ADDRESS
 UserAgent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-03-23T05-46-11Z
 Error: open /data/.minio.sys/multipart/c55717a43c1e7e1021cfe395b49b0eb70efd3b1952ea5c8849854468a2a0a789/e9157b7f-ae34-43ab-ad95-627066855980/fs.json: operation not permitted (*fs.PathError)
        3: cmd/fs-v1-multipart.go:395:cmd.(*FSObjects).GetMultipartInfo()
        2: cmd/object-handlers.go:2270:cmd.objectAPIHandlers.PutObjectPartHandler()
        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

 API: PutObjectPart(bucket=BUCKET_NAME, object=LARGE_FILE)
 Time: 13:27:35 UTC 04/12/2021
 DeploymentID: 5868a74e-86b5-4747-9963-59649a92f91d
 RequestID: 16751F4CD0F0B8FB
 RemoteHost: IPv4_ADDRESS
 UserAgent: MinIO (linux; amd64) minio-go/v7.0.11 mc/RELEASE.2021-03-23T05-46-11Z
 Error: open /data/.minio.sys/multipart/c55717a43c1e7e1021cfe395b49b0eb70efd3b1952ea5c8849854468a2a0a789/e9157b7f-ae34-43ab-ad95-627066855980/fs.json: operation not permitted (*fs.PathError)
        4: cmd/api-errors.go:2009:cmd.toAPIErrorCode()
        3: cmd/api-errors.go:2034:cmd.toAPIError()
        2: cmd/object-handlers.go:2272:cmd.objectAPIHandlers.PutObjectPartHandler()
        1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```

Of note is that when I SSH into the server during the transfer, I can access the temporary multipart directory that is created, write new files, `cat` the `fs.json` in question, and even overwrite it with `echo "foo" > fs.json`. This is true when `exec`ing into the container as well.
 

## Possible Solution

After some detailed investigation, I suspect the issue is some interplay between filesystem permissions and the NFS4 mount, as the issue does not occur with a different directory on the host filesystem. The backing filesystem volume for MinIO is an NFS4 mount on the host. While the filesystem owners are potentially users that don't exist on this host, all accesses are squashed to a particular uid and gid, so any location within the mount can be read and written regardless of apparent ownership. This mount is then bind-mounted into the Docker container, and the ownership ids are preserved, but processes in the container may continue to read and write to any location within the mount.

The regression may be because the MinIO process is checking its own uid:gid instead of relying on the kernel. I noticed that the error is only occurring with the NFS mount, not a host directory, and only when the MinIO container is downgraded from root. Regardless of these changes, a shell running as root or a downgraded user in the container is able to read and write any location in the bind mount.

## Steps to Reproduce (for bugs)

1. Spin up a MinIO instance with Docker Compose. The data volume is an NFS mount or a subdirectory in an NFS mount on the host side. Downgrade the running instance from `root` to some other UID/GID.
   ```yaml
    version: "3.8"
    services:
      minio:
        image: minio/minio
        user: "10000:10000"
        environment:
          MINIO_ROOT_USER: something
          MINIO_ROOT_PASSWORD: something
        volumes:
          - /path/to/nfs4/mount:/data
        command: server /data
2. Create a bucket with `mc` and try to `mc cp` a sufficiently large file to the MinIO instance such that multipart uploads are triggered.

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->
No longer able to transfer large files to our object storage, a key use of MinIO.

I found another individual who may have been affected by the same error. https://forum.cloudron.io/topic/4786/minio-backup-not-working

## Regression
<!-- Is this issue a regression? (Yes / No) -->
<!-- If Yes, optionally please include minio version or commit id or PR# that caused this regression, if you have these details. -->
Yes. Last working version is RELEASE.2021-02-23T20-05-01Z. 

## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used (`minio --version`): all versions from RELEASE.2021-02-24T18-44-45Z through 
RELEASE.2021-04-06T23-11-00Z
* Server setup and configuration: single instance deployed via Docker Compose, behind an nginx reverse proxy for TLS, NFS4 mount bind-mounted into the MinIO container
* Operating System and version (`uname -a`): Linux minio 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 18.04.5 LTS)

**Comment by harshavardhana** [comment] 2021-04-12 16:20
>  Error: open /data/.minio.sys/multipart/c55717a43c1e7e1021cfe395b49b0eb70efd3b1952ea5c8849854468a2a0a789/e9157b7f-ae34-43ab-ad95-627066855980/fs.json: operation not permitted (*fs.PathError)

what is the backend filesystem here? @kevinlul

**Comment by kevinlul** [comment] 2021-04-12 16:21
NFS4 mount bind-mounted into the Docker container.

**Comment by harshavardhana** [comment] 2021-04-12 16:22
> The regression may be because the MinIO process is checking its own uid:gid instead of relying on the kernel. I noticed that the error is only occurring with the NFS mount, not a host directory, and only when the MinIO container is downgraded from root. Regardless of these changes, a shell running as root or a downgraded user in the container is able to read and write any location in the bind mount.

This is the behavior of Go stdlib not sure if we can change it @kevinlul

**Comment by kevinlul** [comment] 2021-04-12 16:24
What was the change between February 23 and 24? I am seeing an IO library change b517c791e9f164e7b2c27d7bb0c31de4ae23c3c9

**Comment by harshavardhana** [comment] 2021-04-12 16:27
@kevinlul    `readMode = os.O_RDONLY | 0x40000 // O_NOATIME`  most probably O_NOATIME is not supported on NFS

**Comment by kevinlul** [comment] 2021-04-12 16:43
I see, none of my tests in the shell would use [`NOATIME`](https://man7.org/linux/man-pages/man2/open.2.html) then. I'm not seeing a flag for this with `cat` and `less`.
```
       O_NOATIME (since Linux 2.6.8)
              Do not update the file last access time (st_atime in the
              inode) when the file is read(2).

              This flag can be employed only if one of the following
              conditions is true:

              *  The effective UID of the process matches the owner UID
                 of the file.

              *  The calling process has the CAP_FOWNER capability in
                 its user namespace and the owner UID of the file has a
                 mapping in the namespace.

              This flag is intended for use by indexing or backup
              programs, where its use can significantly reduce the
              amount of disk activity.  This flag may not be effective
              on all filesystems.  One example is NFS, where the server
              maintains the access time.
```
The kernel might actually be checking the UIDs for this then. I altered the downgraded UID to match that of the NFS mount and it worked.

**Comment by harshavardhana** [comment] 2021-04-12 16:46
> The kernel might actually be checking the UIDs for this then. I altered the downgraded UID to match that of the NFS mount and it worked.

Yes that is the permission needed for perhaps this os.Open flag to succeed since it needs to CAP_FOWNER or UID matches.

**Comment by harshavardhana** [comment] 2021-04-14 05:45
> I see, none of my tests in the shell would use [`NOATIME`](https://man7.org/linux/man-pages/man2/open.2.html) then. I'm not seeing a flag for this with `cat` and `less`.

Yes, they would not it's our feature to avoid doing **atime** updates on objects @kevinlul

**Comment by harshavardhana** [comment] 2021-04-16 16:03
Closing this as not our bug and expected behavior.

**Closed as completed by harshavardhana** 2021-04-16 16:03 UTC
Labels: working as intended, community

**Comment by michaelyork** [comment] 2021-06-22 18:42
I'm also experiencing this issue with a CIFS mount (so not limited to NFS). What's the best workaround here?
