### ISSUE TITLE
minio cannot find file starting with certain characters on network drive

### ISSUE THREAD

**Issue by Druckles** [minio/minio#7850] opened 2019-06-28 14:36 UTC
If I link min.io to a filestore on a network drive I cannot access files starting with ASCII characters 33 (`!`) - 45 (`-`). Characters after this (`.` and above) work fine (including Unicode).

If several files like this are added, it is just the first one that is not displayed.

* The files are visible in Windows Explorer.
* The problem doesn't occur when the filestore is on a local drive.
* Happens whether min.io is run on the network drive or locally and linked to the drive.
* e.g. filename `-abc.jpg`

Characters that don't work at start of filename: `!#$%&'()+,-`
Characters that do work: `.0-9;=@A-Z[]^_a-zA-Z{}~ §`

### One file
The filename `-abc.jpg` should be visible in the MinIO Browser and should be accessible through the S3 API.

### Multiple files
If multiple files are in one folder (`!abc.jpg`, `~abc.jpg`, `#abc.jpg`) all should be visible in the MinIO Browser and accessible through the S3 API.

### One file
The file `-abc.jpg` is not visible in the MinIO Browser and cannot be found through the S3 API.

### Multiple files
The file `!abc.jpg` is not visible in the MinIO Browser. The later files (`~abc.jpg` and `#abc.jpg`) are visible. The same behaviour is observed using the S3 API.

## Steps to Reproduce (for bugs)

1. The filestore is a Docker image on a virtual machine (e.g. `\\192.168.59.101\public`) and set up as a network drive in Windows 10 (e.g. `Z:\`)  
The docker-compose:  
```
smbd:
  image: 529985782713.dkr.ecr.eu-central-1.amazonaws.com/ttsdev/repo:latest
  ports:
    - "445:445"
  networks:
    default:
      aliases:
        - datastore
```
2. Start min.io: `./minio.exe server Z:/filestore`
3. Add file through MinIO Browser (or copy directly using Windows Explorer) called `!abc.jpg`
4. File is not visible in Browser. Should be visible in Explorer.

## Your Environment
* Version used (`minio version`): 2019-06-27T21:13:50Z
* MinIO running on: Windows 10
* Filestore running from: Linux dev 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kannappanr** [comment] 2019-06-28 18:42
@Druckles We will take a look and get back to you.

**Comment by ebozduman** [comment] 2019-10-02 00:48
@Druckles ,

I tried to reproduce the issue on a slightly different, but much simpler setup, however, I could not reproduce the issue.

In my setup, I had a filesystem/dir (let's call it `".../shared_data/"`) defined on an Ubuntu box (18.04, not virtual), and some files/objects with offensive file names (!abc.jpg, $abc.jpeg, #abc.txt etc.) created in the same location, `".../shared_data/"`. 

On a separate Windows box (8.1 Pro, not virtual), I had the latest MinIO started with `".../shared_data/"` as the data store, after the shared data point is made available on the Windows side.
```
    C:\ minio.exe server .../shared_data/
```

When checked with the IE, and `"mc ls myminio"` command, all files appeared correctly and without any problem.

So, we would like to ask you to try one more time, if you could, with the latest release available at the time of your trial, while we continue trying the reproduction steps with the details assumed to be unrelated in our first attempt.

Please let us know if there is any new/existing details, any additional information about the reproduction steps, you want to bring to our attention.

**Comment by kannappanr** [comment] 2019-10-10 20:32
@Druckles closing this issue now. Will take a look if we have more information to reproduce this issue

**Closed as completed by kannappanr** 2019-10-10 20:32 UTC
Labels: community

**Comment by boerderspeck** [comment] 2019-10-17 11:44
@kannappanr The issue is still reproducable with min.io version 2019-10-12T01:39:57Z. The version of Samba used in the docker image @Druckles mentioned is 4.3.9-Ubuntu. Does this help?

On local filesystem (Windows 7, 10) we had no problems with these characters, seems to be related with Samba somehow.

**Comment by ebozduman** [comment] 2019-10-17 17:22
@boerderspeck 
Yes, the culprit could be Samba.
Thanks for the information. We'll try it again.
