### ISSUE TITLE
[resolved] Server does not format blank disks

### ISSUE THREAD

**Issue by igomura** [minio/minio#9456] opened 2020-04-26 20:43 UTC
This is a continuation of #9449 which has been partially fixed to make server not to crash.
In the same scenario, server shows new disks as an offline ones but there is no attempt to bring them online. There is a little evidence what minio is looking into new disks. Every 10sec atime and mtime on mountpoints get updated. But after 15min of work there is no .minio.sys created.

## Expected Behavior
Expected new disks to be formatted (.minio.sys created) and data healing process started.

## Current Behavior
Blank disks stay offline.

## Steps to Reproduce (for bugs)
Described in #9449

**Comment by harshavardhana** [comment] 2020-04-26 21:14
@igomura `mc admin heal -r <alias>`  should work

**Comment by kannappanr** [comment] 2020-04-27 04:56
@igomura Closing this as answered, please feel free to reach out to us at https://slack.min.io for further such questions

**Comment by harshavardhana** [comment] 2020-04-27 05:32
@kannappanr need to keep this open to see why auto heal didn't work on newly replaced drives.

**Comment by kannappanr** [comment] 2020-04-27 05:38
ok

**Comment by vadmeste** [comment] 2020-04-27 10:51
@igomura I am not able to reproduce this, could you tell us what is your MinIO version and the arguments that you pass to the server ?

**Comment by igomura** [comment] 2020-04-27 16:08
I did build at commit 6ecc98fddbfb6ffa6e31dc79b0acac407154f9ac
This is my configuration:
```
MINIO_VOLUMES="https://node{01...16}.local.net/data/disk{001...200}"
MINIO_OPTS="--anonymous --certs-dir /etc/minio/certs"
MINIO_BROWSER="off"
MINIO_ERASURE_SET_DRIVE_COUNT="16"
MINIO_STORAGE_CLASS_STANDARD="EC:6"
MINIO_API_REQUESTS_MAX="9600"
MINIO_DISK_USAGE_CRAWL_ENABLE="off"
```
Please see attached file with output of
mc trace -a -v

[trace.gz](https://github.com/minio/minio/files/4540743/trace.gz)

**Comment by igomura** [comment] 2020-04-27 16:37
I intentionally did not start healing manually in order to keep state for troubleshooting. I can try to start it

**Comment by igomura** [comment] 2020-04-27 17:36
Here is my attempt to start healing manually:
```
$ mc admin heal -r bs02/
 ◓  ** waiting for status from server **
    0/0 objects; 0 B in 19m54s
    ┌────────┬───┬─────────────────────┐
    │ Green  │ 0 │   0.0%              │
    │ Yellow │ 0 │   0.0%              │
    │ Red    │ 0 │   0.0%              │
    │ Grey   │ 0 │   0.0%              │
    └────────┴───┴─────────────────────┘
^Cmc: <ERROR> Unable to display heal status. Healing is backgrounded, to resume watching use `mc admin heal --recursive  bs02/`.
```

mc admin info:
```
●  node01.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 196/200 OK

●  node02.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 196/200 OK

●  node03.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 197/200 OK

●  node04.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 196/200 OK

●  node05.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node06.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node07.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node08.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node09.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node10.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node11.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node12.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node13.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node14.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node15.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

●  node16.local.net:9000
   Uptime: 21 hours
   Version: <development>
   Network: 16/16 OK
   Drives: 200/200 OK

308 TiB Used, 2 Buckets, 1,325,669 Objects
3,185 drives online, 15 drives offline

**Comment by igomura** [comment] 2020-04-27 17:45
mc admin heal bs/
```
$ mc admin heal bs02
Background healing status:
 ●  431 item(s) scanned in total
 ●  Completed 5 minutes ago
 ●  Next scheduled in 29 days
```

**Comment by vadmeste** [comment] 2020-04-27 20:29
@igomura thanks. If possible, could also attach the output of your servers ? Maybe there are some clues there..

Also what's the output of `mc admin top locks your-alias` ? (the alias can point to any server)

**Comment by vadmeste** [comment] 2020-04-27 20:45
Also @igomura, could you attach `mc --json admin info your-alias` ? this will give us better information of the status of nodes/disks.

**Comment by vadmeste** [comment] 2020-04-27 22:19
It is also possible that there is something wrong while mounting new disks. Could you check MinIO is able to read/write in the new disk ? could you also check that MinIO is not mistakenly writing in the root filesystem (`/`) instead of the external disk ?

**Comment by igomura** [comment] 2020-04-28 00:02
I did not save state if the cluster. I have to reproduce it again.

**Comment by igomura** [comment] 2020-04-28 20:46
I was not able to reproduce the issue second time. The only difference was amount of data in cluster and I think this is the key. Original cluster had 1.3P of data while second time it had less than 100Tb.

You can close this ticket for now and I will try to reproduce the issue once again when I will have right conditions.

**Comment by harshavardhana** [comment] 2020-04-28 20:59
> I was not able to reproduce the issue second time. The only difference was amount of data in cluster and I think this is the key. Original cluster had 1.3P of data while second time it had less than 100Tb.
> 
> You can close this ticket for now and I will try to reproduce the issue once again when I will have right conditions.

The size has nothing to do with healing @igomura as it runs slowly - I think the issue is some form of disk mounting error where the disk is deemed root disk which is the reason MinIO refused to heal it.

**Comment by harshavardhana** [comment] 2020-04-28 20:59
Will close this for now.

**Closed as completed by harshavardhana** 2020-04-28 20:59 UTC
Labels: working as intended, community, priority: medium
