### ISSUE TITLE
CPU continues to grow

### ISSUE THREAD

**Issue by Gerrylinux** [minio/minio#14960] opened 2022-05-23 10:23 UTC
3-node server. Node a is exposed to receiving API requests. The CPU of node a will continue to grow to 97% utilization. Every time the Minio service is restarted, the CPU will be released. For this problem, no positioning method is found
Binary files are deployed on CentOS 7 server
And / or shared SDA partitions
Version: mini version release 2022-05-19T18-20-59Z
How to locate the problem
![image](https://user-images.githubusercontent.com/31839722/169798709-037b2b5a-9244-4700-bac4-dd294bcc250f.png)
![image](https://user-images.githubusercontent.com/31839722/169799072-b945c169-5abe-45ff-9f3a-977c04c7e0fa.png)

**Comment by Gerrylinux** [comment] 2022-05-23 10:44
This is the imported pprof file
mc admin profile
[profile (1).zip](https://github.com/minio/minio/files/8753871/profile.1.zip)

**Comment by Gerrylinux** [comment] 2022-05-23 11:01
This is the imported pprof file
mc admin profile
[profile.zip](https://github.com/minio/minio/files/8753966/profile.zip)

**Comment by klauspost** [comment] 2022-05-23 11:22
Seems like there are a bunch of directory listings going on. The caller isn't revealed though.

@Gerrylinux Could you do a profile with `--type=goroutines` as well on a running server with high CPU usage?

**Comment by klauspost** [comment] 2022-05-23 11:24
Looks like a hot loop is trying to do listings that fails and then instantly retries. May be an internal problem, but I need to see the cause.

**Comment by Gerrylinux** [comment] 2022-05-23 11:44
Goroutines added
[profile.zip](https://github.com/minio/minio/files/8754189/profile.zip)

**Comment by klauspost** [comment] 2022-05-23 12:27
@Gerrylinux Fix added in #14961 - My guess is you have a problematic disk or something else causing disk/network errors. Unmounting will avoid the problem.  Otherwise the fix will be in the next release.

**Closed as completed** 2022-05-23 13:28 UTC
Labels: community, fixed
