### ISSUE TITLE
Updating object metadata (copy object into self) cause loosing ETag in response

### ISSUE THREAD

**Issue by ddzialak** [minio/minio#6512] opened 2018-09-21 17:29 UTC
After updating metadata on object (copying into self with REPLACE directive) next GET OBJECT operations doesn't return ETag in the response.

## Expected Behavior

GET OBJECT operation should always return ETag header

## Current Behavior

GET OBJECT doesn't return ETag header

## Steps to Reproduce (for bugs)

1. Upload object
2. Copy object to itself
3. Get object and check ETag

Please see attached script that for Amazon S3 returns:
```
put_object etag="328c30fae61cd119cd177c061d1ac11f" 
get_object etag="328c30fae61cd119cd177c061d1ac11f" 
copy_object etag=None 
get_object etag="328c30fae61cd119cd177c061d1ac11f" 
```
but for S3 minio print out:
```
put_object etag="328c30fae61cd119cd177c061d1ac11f" 
get_object etag="328c30fae61cd119cd177c061d1ac11f" 
copy_object etag=None 
get_object etag=None 
```

## Context

Without ETag it's not possible to download object with retries and from last finished position because ETag verification doesn't work. In result I'm not able to use `Content-MD5` / ETag header to verify if it's the same object so have to download again whole object.

## Regression

Don't know

## Your Environment

* Version used (`minio version`):
```
root@beta92:~# docker exec minio minio version
Version: 2017-10-27T18:59:02Z
Release-Tag: RELEASE.2017-10-27T18-59-02Z
Commit-ID: 03df692ae2f911943d5ef98b0ee2f9461605fb8c
```
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
That's what s3minio service says:
```
    Version
    2017-10-27T18:59:02Z
    Memory
    Used: 8.2 MB | Allocated: 24 GB | Used-Heap: 8.2 MB | Allocated-Heap: 15 MB
    Platform
    Host: 59a49de45434 | OS: linux | Arch: amd64
    Runtime
    Version: go1.9.2 | CPUs: 8
```

* Operating System and version (`uname -a`):
`Linux beta92 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* Link to your project:

**Comment by ddzialak** [comment] 2018-09-21 17:31
Script to reproduce that bug:
```
import boto3

common = {'Bucket': 'dd-test', 'Key': 'simple-object'}

client = boto3.client('s3',
 aws_access_key_id='AKIAIOSFODNN7EXAMPLE',
 aws_secret_access_key='wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
 endpoint_url='http://beta92:9000')


def action(op, **kwargs):
    kwargs.update(common)
    resp = getattr(client, op)(**kwargs)
    print("%s etag=%s " % (op, resp.get('ETag', None)))

action('put_object', Body=b'some body', Metadata={'a': 'b'})

action('get_object')

action('copy_object', CopySource=common, MetadataDirective='REPLACE', Metadata={'b': 'c'})

action('get_object')
```

**Comment by harshavardhana** [comment] 2018-09-21 17:35
This is an very old release, you would have to upgrade this problem is already fixed.

**Comment by kannappanr** [comment] 2018-09-21 18:03
@ddzialak https://github.com/minio/minio/pull/5626 has the fix. Any release from RELEASE.2018-03-12T21-25-28Z onwards should have this fix. Closing this as working as intended.

**Closed as completed by kannappanr** 2018-09-21 18:03 UTC
Labels: working as intended, community
