### ISSUE TITLE
Cannot delete an object throught the browser when the user has specific permissions

### ISSUE THREAD

**Issue by JosephLucas** [minio/minio#10039] opened 2020-07-13 21:30 UTC
Hi, I really enjoy using Minio ! I used Syncthing so far, but i had many issues with case sensitivity. Even if Minio is less easy to setup than Syncthing, Minio seems the right tool for me. Synchronizations are fast and I like the bucket browser. Thanks.

There is a very annoying problem though. When using the browser, and I log as a user with specific access rights, I cannot delete an object. An error pops up. The admin can do everything well through the browser. Using `mc` with the user credentials works too. So it might be an issue with the browser. If the user policy is wrong, I do not expect the error popup but an exception due to wrong permission.

## Expected behavior
Being able to remove an object from the Minio browser

## Actual behavior
A toast notification shows up on the top with "We encountered an internal error, please try again." 

journalctl shows
```
mbda-start[1378]: API: WebRemoveObject(bucket=input)
mbda-start[1378]: Time: 21:01:56 UTC 07/13/2020
mbda-start[1378]: DeploymentID: 74300fd6-c33d-471a-bffd-5e9669c2efd1
mbda-start[1378]: RemoteHost: 37.120.204.164
mbda-start[1378]: Host: THISISMYDOMAIN.com
mbda-start[1378]: UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
mbda-start[1378]: Error: Do not have enough permissions to access this resource
mbda-start[1378]:        5: /build/source/cmd/api-errors.go:1847:cmd.toAPIErrorCode()
mbda-start[1378]:        4: /build/source/cmd/api-errors.go:1872:cmd.toAPIError()
mbda-start[1378]:        3: /build/source/cmd/web-handlers.go:2251:cmd.toWebAPIError()
mbda-start[1378]:        2: /build/source/cmd/web-handlers.go:2121:cmd.toJSONError()
mbda-start[1378]:        1: /build/source/cmd/web-handlers.go:744:cmd.(*webAPIHandlers).RemoveObject()

```
## Steps to reproduce the behavior
In the browser, selecting the object, deleting, and clicking OK, while using this policy
```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:ListAllMyBuckets"
   ],
   "Resource": [
    "arn:aws:s3:::*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetBucketLocation",
    "s3:ListBucket",
    "s3:ListBucketMultipartUploads"
   ],
   "Resource": [
    "arn:aws:s3:::input", "arn:aws:s3:::help"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:AbortMultipartUpload",
    "s3:DeleteObject",
    "s3:GetObject",
    "s3:ListMultipartUploadParts",
    "s3:PutObject"
   ],
   "Resource": [
    "arn:aws:s3:::input/*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::help/*"
   ]
  }
 ]
}
```
## System information
My version of Minio is minio-2020-05-01T22-19-14Z
from https://github.com/NixOS/nixpkgs-channels/blob/nixos-unstable/pkgs/servers/minio/default.nix

**Comment by harshavardhana** [comment] 2020-07-13 21:46
@JosephLucas please upgrade we fixed a whole bunch of issues regarding policy handling in browser UI - would be better if you can test that and let us know..

**Comment by kannappanr** [comment] 2020-07-13 22:31
@JosephLucas Please test with the latest version of minio. I verified the policy that you provided with the latest version and was unable to reproduce the issue. Please upgrade to the latest and let us know if you still see the issue. Closing this issue as fixed.

**Comment by JosephLucas** [comment] 2020-07-14 08:47
I confirm that the last binary release at https://docs.min.io/docs/minio-quickstart-guide.html does fix the issue. Thanks

**Closed as completed** 2020-07-14 08:51 UTC
Labels: community, fixed
