### ISSUE TITLE
[distributed] upload 1gb file twice stuck at 100%

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2500] opened 2016-08-19 21:19 UTC
minio@minio1:~/vadmeste$ mc cp work/bigfiles/1024mb.bin myvadmeste/testbucket/
work/bigfiles/1024mb.bin:      1024.00 MB / 1024.00 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 12.88 MB/s 0

where mc and minio are idle

**Comment by vadmeste** [comment] 2016-08-19 21:35
Actually, this is systematic if we upload a file twice

**Comment by vadmeste** [comment] 2016-08-19 21:36
in this case, `mc rm myvadmeste/testbucket/1024mb.bin` doesn't work too.. it seems it is some locking issue

**Comment by harshavardhana** [comment] 2016-08-19 21:43
> in this case, mc rm myvadmeste/testbucket/1024mb.bin doesn't work too.. it seems it is some locking issue

Yes over-write of a file has a locking issue during GetObject() initiated to populate the cache.

**Comment by harshavardhana** [comment] 2016-08-23 02:37
Closing this as duplicate of - https://github.com/minio/minio/issues/2518

**Closed as completed by harshavardhana** 2016-08-23 02:37 UTC
