### ISSUE TITLE
Docker & Traefik - "There are no buckets yet"

### ISSUE THREAD

**Issue by gino** [minio/minio#12676] opened 2021-07-10 09:11 UTC
Hey everyone,

I am trying to setup MinIO through Traefik, with Docker. And I have setup two endpoints:
- `minio.mydomain.tld`, where the MinIO Console is accessible.
- `cdn.mydomain.tld`, where the actual MinIO API lives.

Both endpoints are working fine and are able to reach through the browser. However, whenever I create a bucket through the Console, my bucket does not show up in the actual overview: `There are no Buckets yet.`. I do see the created bucket in the filesystem, but it doesn't show up in the actual browser. Even though other list overviews, like listing all created users, works fine. I am not sure why this is happening, both endpoints are working, I do not see any errors in the logs either. Just `null` when it is trying to fetch all the buckets. 

I assume this bucket issue has something to do with the combination of Traefik. Since I have tried to just run a MinIO container without Traefik, and that works fine, as expected. However, I think my `docker-compose.yml` should work fine, since both endpoints are reachable and both provided with a valid SSL certificate:

```yml
services:
  minio:
    image: minio/minio:latest
    env_file: ".env"
    volumes:
      - "./data:/data"
    networks:
      - web_proxy
    command: server /data --console-address ":9001"
    labels:
      # Minio Console
      - "traefik.http.routers.minio.rule=Host(`minio.mydomain.tld`)"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.tls.certresolver=resolver"
      - "traefik.http.routers.minio.service=minioService"
      - "traefik.http.services.minioService.loadbalancer.server.port=9001"
      - "traefik.http.services.minioService.loadbalancer.passhostheader=true"
      # Minio itself
      - "traefik.http.routers.cdn.rule=Host(`cdn.mydomain.tld`)"
      - "traefik.http.routers.cdn.tls=true"
      - "traefik.http.routers.cdn.tls.certresolver=resolver"
      - "traefik.http.routers.cdn.service=cdnService"
      - "traefik.http.services.cdnService.loadbalancer.server.port=9000"
      - "traefik.http.services.cdnService.loadbalancer.passhostheader=true"

networks:
  web_proxy:
    external:
      name: web_proxy
```

I hope someone is able to help me out, I have no idea why this issue is happening and it makes MinIO unable to use, unfortunately.

Thanks in advance.

**Edit:** If I try to reach my just created bucket in the URL (`https://minio.mydomain.tld/buckets/<bucket>/summary`), I receive an error in the console on the `/api/v1/buckets/test/encryption/info` call: `{ code: 404, message: "The server side encryption configuration was not found" }`. Could this error, cause the issue I am having? Even though I am not sure how to solve it..

**Comment by kiennd** [comment] 2021-07-10 12:13
I've got the same issue. 
After inspected i got some information:
- Api create bucket is successfull and return 201 
- Api get all bucket (/api/v1/buckets) return null: {"buckets":null}
- Folder with bucket name is created.

So i think this issuce cause by /api/v1/buckets api return null.
Hope it will be fixed.

**Comment by harshavardhana** [comment] 2021-07-10 15:28
We will investigate and let you know..

**Comment by edmondburnett** [comment] 2021-07-10 22:11
Same issue here, running the Docker container on top of Ubuntu:

```
sudo docker run -d -p 9000:9000 -p 9001:9001 --name minio -v /mnt/data1:/data1 -v /mnt/data2:/data2 -v /mnt/data3:/data3 -v /mnt/data4:/data4 minio/minio server  --console-address ":9001" /data{1...4}
```

Buckets get created on the filesystem, but don't show up in the console.

**Comment by memochou1993** [comment] 2021-07-11 10:09
Same issue here

**Comment by Enrico204** [comment] 2021-07-11 10:41
Same issue here, however using the `mc` client I can see all buckets. So apparently the bug is in the console part.

I'm using Caddy as reverse proxy

**Comment by Enrico204** [comment] 2021-07-11 11:19
Ok some clues: the last working version was `RELEASE.2021-07-08T01-15-01Z`. I've done these tests:

| Server version | Console version | Outcome |
| ----- | ----- | ----- |
| pre-`RELEASE.2021-07-08T01-15-01Z` | any (external) | OK |
| `RELEASE.2021-07-08T01-15-01Z` | any (external/integrated) | OK |
| `RELEASE.2021-07-08T19-43-25Z` | any (external/integrated) | Fail |
| `master` (`e4c395394`) | integrated | Fail |

(every version was built from this repo using `make build`)

**Comment by gino** [comment] 2021-07-11 12:17
I can indeed confirm that using version `RELEASE.2021-07-08T01-15-01Z` solves my issue, as @Enrico204 said. Might help @harshavardhana investigate what's causing this issue.

**Comment by Enrico204** [comment] 2021-07-11 13:52
I was looking at code changes between versions, apparently the bug was added in commit 84a64a7e479e2165ef897f4f87aabffbe11dd2a5 . This commit is from this pull request https://github.com/minio/minio/pull/12652 .

I think that the idea behind [lines 987-991 in that commit](https://github.com/minio/minio/commit/84a64a7e479e2165ef897f4f87aabffbe11dd2a5#diff-ef268fe29d8a37a689fc4720dcb9feb441bb3076def2ed405c717ab586d6baa2R987) was that a standard user doesn't have a `parentUser`. However, in my case, my user do have a string inside that field (20 character length wide, apparently alphanumeric), so that string is used in place of my username. I suppose that this disrupts the username matching in policies.

I use OIDC to authenticate my users. Maybe this can help

**Comment by Enrico204** [comment] 2021-07-11 14:06
ok I think that the origin of (at least, mine) `parentUser` value is here:

https://github.com/minio/minio/blob/28adb29db335d451c186088543667f9c4ed40171/cmd/sts-handlers.go#L244-L246

Here the `parentUser` is set to the `user.AccessKey` when using an external account (STS), if I'm reading correctly. This, together with the commit mentioned above is causing issues when on STS (LDAP, OIDC, etc), I think.

@gino @memochou1993 @edmondburnett are you using STS?

**Comment by harshavardhana** [comment] 2021-07-11 15:56
> ok I think that the origin of (at least, mine) `parentUser` value is here:
> 
> https://github.com/minio/minio/blob/28adb29db335d451c186088543667f9c4ed40171/cmd/sts-handlers.go#L244-L246
> 
> Here the `parentUser` is set to the `user.AccessKey` when using an external account (STS), if I'm reading correctly. This, together with the commit mentioned above is causing issues when on STS (LDAP, OIDC, etc), I think.
> 
> @gino @memochou1993 @edmondburnett are you using STS?

@Enrico204 that part has been present this 15 months and it's also not the codepath that is used for OIDC/LDAP they have their own functions.

**Comment by Enrico204** [comment] 2021-07-11 16:26
There is a similar line of code in the LDAP function, actually:

https://github.com/minio/minio/blob/28adb29db335d451c186088543667f9c4ed40171/cmd/sts-handlers.go#L562-L564

And in the SSO:

https://github.com/minio/minio/blob/28adb29db335d451c186088543667f9c4ed40171/cmd/sts-handlers.go#L409-L411

These line of codes are not an issue *per-se* (I mean, they are not causing issues by themself). The problem is when you add a code like this:

https://github.com/minio/minio/blob/84a64a7e479e2165ef897f4f87aabffbe11dd2a5/cmd/admin-handlers-users.go#L189-L192

If you're logged in via OIDC, now you have that `cred.AccessKey` is something like `XXXXXXXXXXXXXXXXXXXX` (masked, it was an alphanumeric string) and `cred.ParentUser` is `jwt:00000000-0000-0000-0000-000000000000:https://myidp/path`. Given that the `cred.ParentUser` is not empty (it contains the JWT ID and the IDP path), it's used in place of the `cred.AccessKey`.

I've removed those lines (189-192) from `admin-handlers-users.go` in a local copy, and the bug disappears.

Hope this helps

**Comment by harshavardhana** [comment] 2021-07-11 16:32
> I've removed those lines (189-192) from `admin-handlers-users.go` in a local copy, and the bug disappears.

This line of code is specifically added on purpose to evaluate dynamic policies can you share your policies @Enrico204 ?

**Comment by Enrico204** [comment] 2021-07-11 16:37
> This line of code is specifically added on purpose to evaluate dynamic policies can you share your policies @Enrico204 ?

Apparently those line broke everything else. Also, it doesn't seems to work, see the comment of @fixr here: https://github.com/minio/minio/issues/12651#issuecomment-877028310

Here an example of a policy that I use:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:ListBucket"],
      "Resource": ["arn:aws:s3:::tweets"]
    },
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject"
      ],
      "Resource": ["arn:aws:s3:::tweets/*"]
    }
  ]
}
```

I'm applying the policy via the OIDC attribute `policy`. The same configuration is working properly when using version `RELEASE.2021-07-08T01-15-01Z` of the server, but it doesn't work starting from the commit 84a64a7e479e2165ef897f4f87aabffbe11dd2a5 (i verified by compiling each commit between versions)

**Comment by harshavardhana** [comment] 2021-07-11 16:44
> Apparently those line broke everything else. Also, it doesn't seems to work, see the comment of @fixr here: [#12651 (comment)](https://github.com/minio/minio/issues/12651#issuecomment-877028310)

It works fine @Enrico204 I have tested it locally - that problem is not the same as this. In this situation however the ParentUser should work fine regardless since you are using a specific policy not a dynamic one.

**Comment by gino** [comment] 2021-07-11 16:47
To mention, I haven't changed any policies or STS stuff. I only created a bucket through the Console and the issue immediately happened..

**Comment by harshavardhana** [comment] 2021-07-11 16:49
> To mention, I haven't changed any policies or STS stuff. I only created a bucket through the Console and the issue immediately happened..

Yeah I am able to test it locally, I can see the buckets getting listed even with restricted dynamic policies.

**Comment by harshavardhana** [comment] 2021-07-11 18:28
> Apparently those line broke everything else. Also, it doesn't seems to work, see the comment of @fixr here: [#12651 (comment)](https://github.com/minio/minio/issues/12651#issuecomment-877028310)

It wasn't enough because console has other bugs those were fixed on  master @Enrico204

**Comment by harshavardhana** [comment] 2021-07-11 19:31
Okay so I found few issues 

- Dynamic policies were not working with STS credentials due to `aws:username` usage this will break console usage since console uses STS APIs to list buckets etc, it works fine with explicit bucket names but not with `{aws:username}` - it required a collection of 3-4 different fixes.
- While the fix for `aws:username` broke the issue with AccountInfoHandler() since the policy
  evaluator with specific buckets was not working anymore - this is because OIDC adds `jwt:` and policy evaluator was converting the `jwt:` into something meaningful internally and there is a clash on the prefixes for some variable translation. Changing this to `openid:` instead of `jwt:` works.
- Another issue was passing parentUser for IsAllowed() function for policy evaluation that is not correct, instead only change needed as condition value to be dynamic.

**Comment by harshavardhana** [comment] 2021-07-11 19:35
This PR fixes the bugs reported here https://github.com/minio/minio/pull/12681 - thanks for all the help in tracking it down saved me a bunch of time.

🍰 @Enrico204 @gino

**Closed as completed** 2021-07-12 00:39 UTC
Labels: community, fixed, priority: high
