### ISSUE TITLE
server: Minio crashed due to thread exhaustion under high load.

### ISSUE THREAD

**Issue by alpswjc** [minio/minio#3883] opened 2017-03-10 16:41 UTC
here is the log 

```
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw(0xca2800, 0x11)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:566 +0x95
runtime.checkmcount()
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:486 +0xa4
runtime.mcommoninit(0xc42b94b000)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:506 +0xd5
runtime.allocm(0xc42002ca00, 0xd11508, 0x7efe00000001)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:1286 +0x9b
runtime.newm(0xd11508, 0xc42002ca00)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:1555 +0x39
runtime.startm(0xc42002ca00, 0x100000001)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:1642 +0x181
runtime.wakep()
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:1723 +0x57
runtime.newproc1(0xd100b8, 0xc4202bae40, 0x10, 0x56d0d5, 0x7f1487ac8d78)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:2810 +0x334
runtime.newproc.func1()
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:2712 +0x51
runtime.systemstack(0xc420027500)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:1079

goroutine 26 [running]:
runtime.systemstack_switch()
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/asm_amd64.s:252 fp=0xc4202bade8 sp=0xc4202bade0
runtime.newproc(0x10, 0xd100b8)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/proc.go:2713 +0x8b fp=0xc4202bae30 sp=0xc4202bade8
github.com/minio/minio/cmd.newListenerMux.func1(0xc4203c6090)
        /home/builder/mygo/src/github.com/minio/minio/cmd/server-mux.go:263 +0x2c5 fp=0xc4202bafa8 sp=0xc4202bae30
runtime.goexit()
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
VERSION:
  2017-02-16T01:47:30Z

* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by harshavardhana** [comment] 2017-03-10 17:01
Can you provide us reproducing steps here? Can you explain further what were you trying to do etc.? 

Thanks

**Comment by alpswjc** [comment] 2017-03-10 17:39
Yes. we have about 4000-5000 concurrent uploads going on at the same time, and about 4-5 mts.  Minio service crashed. could you please let  me know how to increase the thread ?

**Comment by harshavardhana** [comment] 2017-03-10 21:14
@alpswjc can you provide us output of `ss -t` when the server is about to reach 4000 connections? and after the crash?

**Comment by harshavardhana** [comment] 2017-03-23 05:32
> @alpswjc can you provide us output of ss -t when the server is about to reach 4000 connections? and after the crash?

@alpswjc were you able to gather the previously requested info? ..

**Comment by vadmeste** [comment] 2017-03-23 21:44
For peeking connection stuff, we create a goroutine here, https://github.com/minio/minio/blob/master/cmd/server-mux.go#L238, this is creating more threads than we expect, nearly double in some cases when I run some benchmarks in my local machine.

However, this go-routine is really needed especially in case of TLS connections, I can see that the number of processed requests falls down from 350/sec to 140/sec when I disable that go-routine.

Why does Go have this goroutine number limit? The documentation says that leaked goroutines have bad effect on the operating system that's why there is an intentional crash.

I think it is safe to increase this one to maximum file descriptor as you suggested @harshavardhana.

(For the record, the command I used to benchmark `httperf --ssl --server=127.0.0.1 --port=9000 --hog --timeout 300.0 --num-conns 5000 --rate=5000 --uri=/testbucket/public/file`)

**Comment by krishnasrinivas** [comment] 2017-03-25 01:34
If the thread count goes more than max limit and it crashes then it will always be easy for someone to crash the server. 

Right fix is to figure out max threads the machine can handle and set the limit to that. Because if we set it to something the machine can not handle then minio can make the machine unresponsive. Once the ideal max-threads is configured then we should not allow more than n/2 number of concurrent connections so that we dont spawn too many threads and crash the server.

**Comment by harshavardhana** [comment] 2017-03-25 01:37
> Right fix is to figure out max threads the machine can handle and set the limit to that. Because if we set it to something the machine can not handle then minio can make the machine unresponsive. Once the ideal max-threads is configured then we should not allow more than n/2 number of concurrent connections so that we dont spawn too many threads and crash the server.

Agree we should have a pool and block the connection upon the listen itself - we actually do have a counter for this i think already in the `ListenerMux` we should just use that.

**Comment by krishnasrinivas** [comment] 2017-03-25 01:57
> Agree we should have a pool and block the connection upon the listen itself - we actually do have a counter for this i think already in the ListenerMux we should just use that.

Or instead of implementing pool we can return
```
503 - Service Unavailable
A 503 status code is most often seen on extremely busy servers, and it indicates that the server was unable to complete the request due to a server overload.
```

**Comment by harshavardhana** [comment] 2017-03-25 02:04
There is an S3 error response just for this..  - http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

```
SlowDown	Reduce your request rate.	503 Slow Down
```

**Comment by deekoder** [comment] 2017-04-01 01:19
blocked on @abperiasamy

**Comment by deekoder** [comment] 2017-04-03 16:36
Handle gracefully. @abperiasamy , @vadmeste and @harshavardhana  to discuss optimal solution.

**Comment by vadmeste** [comment] 2017-04-03 21:06
@alpswjc, I did a simple test where Minio processed ~ 5000 requests per second and around 1022 concurrents requests, but Minio created only 230 threads << 10000 threads.

Can you tell us what your clients did exactly ? (in case if there is a thread leak)

**Comment by deekoder** [comment] 2017-04-11 16:33
Could not reproduce. Please reopen if you still see this issue @alpswjc

**Comment by harshavardhana** [comment] 2017-04-21 23:20
We were able to reproduce this issue, finding a fix.

**Comment by harshavardhana** [comment] 2017-04-22 02:01
In all the situations that i have observed this behavior i see that the threads are waiting on disk i/o 

```
 grep "^goroutine " error.log  |  perl -npe 's/\d+/n/' | sort | uniq  -c
      1 goroutine n [chan receive]:
      4 goroutine n [chan receive, 14 minutes]:
      1 goroutine n [IO wait]:
   9214 goroutine n [runnable]:
      1 goroutine n [select, 14 minutes, locked to thread]:
     76 goroutine n [semacquire]:
      1 goroutine n [semacquire, 14 minutes]:
     89 goroutine n [semacquire, 1 minutes]:
    648 goroutine n [syscall]:
      1 goroutine n [syscall, 14 minutes]:
      1 goroutine n [syscall, 14 minutes, locked to thread]:
    175 goroutine n [syscall, 1 minutes]:
``` 

```
grep "^goroutine " error.log  |  perl -npe 's/\d+/n/' | sort | uniq  -c
      1 goroutine n [chan receive]:
      4 goroutine n [chan receive, 1 minutes]:
      1 goroutine n [IO wait]:
   9428 goroutine n [runnable]:
      1 goroutine n [select, 1 minutes, locked to thread]:
    211 goroutine n [semacquire]:
      1 goroutine n [semacquire, 1 minutes]:
    695 goroutine n [syscall]:
      1 goroutine n [syscall, 1 minutes]:
      1 goroutine n [syscall, 1 minutes, locked to thread]:
``` 

Only reproduced it on a 64 directory erasure coded setup, but in all cases it is waiting on disks and writing to disks.  This setup is rather not a normal setup but a fake 64 disk setup but it increased wait times enough to crash the server by reaching the aforementioned thread state.

But digging down deeper after adding many other sorts of limit at the Conn level even it can be observed that the problem exists not because of the network connections but the amount of active go-routines there are in the program. 

We have around 10,000 active go-routines , each go-routine gets a thread and we try to do more which is when the program crashes. But this is not trivial and not easy to control through. 

https://golang.org/pkg/runtime/debug/#SetMaxThreads
```The limit controls the number of operating system threads, not the number of goroutines. A Go program creates a new thread only when a goroutine is ready to run but all the existing threads are blocked in system calls, cgo calls, or are locked to other goroutines due to use of runtime.LockOSThread.```

**Comment by harshavardhana** [comment] 2017-04-22 02:04
After performing a scheduler trace we can also see more details 

```SCHED 20008ms: gomaxprocs=64 idleprocs=0 threads=9742 spinningthreads=0 idlethreads=5834 runqueue=25 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0```

Now this is right before the program crashed.

**Comment by harshavardhana** [comment] 2017-04-22 02:11
Increasing the SetMaxThreads() increases the overall behavior here did set the value to 50k here.  This is the only work-around right now. 

```
$ grep threads error.log 
SCHED 0ms: gomaxprocs=64 idleprocs=62 threads=4 spinningthreads=1 idlethreads=0 runqueue=0 gcwaiting=0 nmidlelocked=0 stopwait=0 sysmonwait=0
SCHED 10008ms: gomaxprocs=64 idleprocs=0 threads=9275 spinningthreads=0 idlethreads=2858 runqueue=564 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 20014ms: gomaxprocs=64 idleprocs=64 threads=10486 spinningthreads=0 idlethreads=4325 runqueue=0 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 30014ms: gomaxprocs=64 idleprocs=0 threads=10486 spinningthreads=0 idlethreads=5389 runqueue=75 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 40015ms: gomaxprocs=64 idleprocs=64 threads=10486 spinningthreads=0 idlethreads=2321 runqueue=0 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 50018ms: gomaxprocs=64 idleprocs=64 threads=10486 spinningthreads=0 idlethreads=3030 runqueue=0 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 60026ms: gomaxprocs=64 idleprocs=0 threads=10486 spinningthreads=0 idlethreads=7910 runqueue=104 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 70026ms: gomaxprocs=64 idleprocs=0 threads=10486 spinningthreads=0 idlethreads=5181 runqueue=23 gcwaiting=1 nmidlelocked=1 stopwait=4 sysmonwait=0
SCHED 80033ms: gomaxprocs=64 idleprocs=64 threads=10486 spinningthreads=0 idlethreads=5712 runqueue=0 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 90034ms: gomaxprocs=64 idleprocs=64 threads=10643 spinningthreads=0 idlethreads=1649 runqueue=0 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 119511ms: gomaxprocs=64 idleprocs=51 threads=10643 spinningthreads=0 idlethreads=2026 runqueue=0 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 133955ms: gomaxprocs=64 idleprocs=0 threads=10643 spinningthreads=16 idlethreads=2860 runqueue=24 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 146872ms: gomaxprocs=64 idleprocs=0 threads=10643 spinningthreads=16 idlethreads=3075 runqueue=239 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 159514ms: gomaxprocs=64 idleprocs=0 threads=10643 spinningthreads=16 idlethreads=3305 runqueue=469 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
SCHED 169516ms: gomaxprocs=64 idleprocs=0 threads=10643 spinningthreads=0 idlethreads=3854 runqueue=179 gcwaiting=0 nmidlelocked=1 stopwait=0 sysmonwait=0
```

**Comment by vadmeste** [comment] 2017-04-22 10:30
> We have around 10,000 active go-routines , each go-routine gets a thread and we try to do more which is when the program crashes.

Actually, a go-routine doesn't necessarily take a thread.

Creating threads is costly. Golang created go routines to minimize creating threads as much as possible. 

SetMaxThreads() means threads and not goroutines.

By the way @harshavardhana, can we know the number of concurrent clients ? can you print the number of concurrent clients each second until the server crashes? is there a limit of number of concurrent clients ?

I feel that there is an "unusual"  bottleneck in the server and responding becomes too slow when there is too many clients.

**Comment by harshavardhana** [comment] 2017-04-22 18:26
A running either blocking or ready to run go routine is always on a thread.  It is not about concurrent number of clients. I tried multiple variations of limiting the number of incoming requests such as 

-  Blocking listeners using a global limit 
-  Blocking in ServeHTTP 

We never even reach closer to top limit. The problem of the thread buildup is due to how many go-routines we create underneath. It is essential to read this line 

`A Go program creates a new thread only when a goroutine is ready to run but all the existing threads are blocked in system calls, cgo calls, or are locked to other goroutines due to use of runtime.LockOSThread.`

So for any blocking operations in our case when we have 64 directories erasure coded on the same disk. We reach a situation where we have enough blocking go-routines which leads to the thread build up. It is also easy to read this using scheduler trace as well.

So the math is quite simple each I/O becomes ridiculously slow operation so total number of blocking go-routines we create are 1 file is splitted into 64 in parallel. So now the benchmark creates 200×64 of them,  each of them blocking on a operation which is visible in the backtrace each go routine is waiting on AppendFile(). 

Variations tested are here this is a standalone `minio server`  running erasure code on local directories (NOTE not on disks). 

- 12, 16, 24, 32 directories never fail for 200 concurrent requests (lack of blocking operations build up in the runtime)
- 12 disks we never fail even till 10,000 concurrent requests (lack of blocking operations)
- 64 and above fails for 200+ but not for 100+ 
- 32 and above fail for 400+ 

So the math should be clear from this view that it is easy to reach this situation because a syscall blocking on the disk i/o is considered to be a call worthy to be on a thread by Go runtime regardless of go-routine being thinner theory.  

One such link validating this theory - http://article.gmane.org/gmane.comp.lang.go.general/148263 
`Can you upload the entire crash message? Does your program do a lot of file (not network) io in response to network requests? Each of those goroutines will consume a native thread under the current runtime. `

**Comment by harshavardhana** [comment] 2017-04-22 18:36
NOTE: Let me make this even more clear this testing and reproducer uses a patch - https://github.com/minio/minio/pull/4157 - Which basically breaks away the limit of erasure disks limit we can have. 

So my testing used 64 directories not a usual scenario.

**Comment by donatello** [comment] 2017-04-23 19:30
Root cause appears to be that disk IO calls are blocking in the go-runtime, and the go-runtime spawns a new OS thread whenever a go-routine is ready to run but existing OS threads are blocked. This program demonstrates this - https://gist.github.com/donatello/08eec9a1847d0f9f2a73510460bae421 - with more parallelism, the number of OS threads used by the process increases and eventually the process crashes when it reaches 10K.

So in the case of 64 disks, with 200 concurrent requests, the current design requires 64*200 = 12800 OS threads and this crashes.

**Comment by deekoder** [comment] 2017-04-26 01:30
Lowering priority to high since it is an edge case crash. We will  address this issue so that we don't crash in cases like these.

**Comment by deekoder** [comment] 2017-04-28 01:52
We are closing this issue and address this along with https://github.com/minio/minio/issues/4191

**Closed as completed by deekoder** 2017-04-28 01:52 UTC
Labels: working as intended, community, priority: high

**Comment by hainesc** [comment] 2019-12-27 07:37
Sorry to talk at a closed issue, but I encounter the same error, minio/minio:RELEASE.2019-09-11T19-53-16Z, and search google which takes me here.

Agree with @harshavardhana, the writer goroutine got blocked due to poor disk performance or too many too many write requests, whatever, it got blocked and didn't release the thread, and eventually, threads got exhausted.

@deekoder A question please, Does this bug get resolved?  If not, should we reopen this issue?

**Comment by harshavardhana** [comment] 2019-12-27 15:27
We will not open historical issues, please open a new one @hainesc
