### ISSUE TITLE
_mc admin info_ and _mc watch_ abort with error, minio spams error log

### ISSUE THREAD

**Issue by steschuser** [minio/minio#10457] opened 2020-09-10 08:45 UTC
When doing a _mc admin info myminio_ that command will hang and abort with an error

`mc: <ERROR> Unable to get service status. Get "http://172.16.252.101:9000/minio/admin/v3/info": Connection closed by foreign host http://172.16.252.101:9000/minio/admin/v3/info. Retry again.
`
the output of _mc admin console_ will show the same error over and over again
` API: SYSTEM()
 Time: 08:18:32 UTC 09/10/2020
 DeploymentID: 55db4586-cec5-410c-a221-b7b2f6b4edb0
 Error: 	net/http/server.go:2962 +0x35c
        1: cmd/server-main.go:473:cmd.serverMain.func2()
`

## Steps to Reproduce (for bugs)
Follow the tutorial with unix binary
1. wget https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio
MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin ./minio server /mnt/data

2. wget https://dl.min.io/client/mc/release/linux-amd64/mc
chmod +x mc

3. mc alias set myminio http://192.168.42.151:9000 minioadmin minioadmin

4. mc admin info myminio -> Fail

## Regression
This worked two or three days ago, its a recent regression 

## Environment
minio version RELEASE.2020-09-08T23-05-18Z
mc version RELEASE.2020-09-03T00-08-28Z

Linux docker01  4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2020-09-10 08:49
Duplicate of #10454 and fixed by #10455

**Closed as completed by harshavardhana** 2020-09-10 08:49 UTC
Labels: duplicate, community
