### ISSUE TITLE
[distributed] uploading same file repeatedly causes `mc cp` hangs

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#2518] opened 2016-08-22 12:08 UTC
minio version:

```
Version: 2016-08-22T08:13:15Z
Release-Tag: DEVELOPMENT.2016-08-22T08-13-15Z
Commit-ID: 81da694efccd02231d50991146f64d553ad1fc31
```

Reproducer:

``` bash
for i in $(seq 1 10); do mc cp ~/golang/go1.7.linux-amd64.tar.gz myminio/mybucket/go.tar.gz; done
```

**Comment by krishnasrinivas** [comment] 2016-08-22 12:15
Happens to me too, I can see that, there is no response for complete multipart:

```
REQUEST : POST path:/testbucket/go1.6.2.linux-amd64.tar.gz?uploadId=2938e2fb-45d6-4962-bf54-692264bc40c6
Host: 127.0.0.1:9000
X-Amz-Date: 20160822T121140Z
Accept-Encoding: gzip
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/DEVELOPMENT.GOGET
Content-Length: 2351
Authorization: AWS4-HMAC-SHA256 Credential=SXO8VW2OFKKP2OG7AC85/20160822/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=c1c5a0e237bf09ee7cf5953498581422b8ea19e4762a7d1e9c113bec15519448
Expect: 100-continue
X-Amz-Content-Sha256: 602bdea04a9922c761d2987f073bdfe6b931474573d27d73f9489983af53b4f2

```

this request hangs.

**Comment by vadmeste** [comment] 2016-08-22 12:17
Normally, this is the same as #2500

**Comment by krishnasrinivas** [comment] 2016-08-22 12:19
@vadmeste i have disabled cache MINIO_CACHE_SIZE=0

**Comment by harshavardhana** [comment] 2016-08-22 17:57
Can you paste server logs as well here?

**Comment by harshavardhana** [comment] 2016-08-23 01:48
```
minio@minio1:~$ for i in $(seq 1 10); do mc cp ~/go1.7.linux-amd64.tar.gz dist-harsha/testbucket/go.tar.gz; done
....7.linux-amd64.tar.gz:  77.79 MB / 77.79 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 13.48 MB/s 0
```

Hangs with latest distributed HEAD.  

> @vadmeste i have disabled cache MINIO_CACHE_SIZE=0

Issue exists without cache :+1:

**Comment by fwessels** [comment] 2016-08-23 14:08
Having the same here:

```
[ec2-user@ip-10-193-15-145 ~]$ mc cp large2.bin myminio/frank/aap
large2.bin:    808.71 MB / 808.71 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 29.22 MB/s 0
```

**Comment by harshavardhana** [comment] 2016-08-27 10:18
This has been fixed @balamurugana can you validate and close this?

**Comment by harshavardhana** [comment] 2016-08-28 06:32
> This has been fixed @balamurugana can you validate and close this?

Validated this multiple times and seems like the issue is fixed,  @balamurugana please re-open as a separate bug if seen again.

**Closed as completed by harshavardhana** 2016-08-28 06:32 UTC
