### ISSUE TITLE
Documentation: Object naming guidelines 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1194] opened 2016-03-04 12:37 UTC
Need Object naming guidelines which defines the effect of delimiters like forward slash and backward slash and many more being part of the object name and define safe practices around object naming.

**Comment by harshavardhana** [comment] 2016-03-04 17:01
All files that are safe to be created in a said OS under said Filesystem. The limits of object naming is based on the limits of your backend filesystem.

**Comment by hackintoshrao** [comment] 2016-03-05 01:09
Wanted to whether know forward slash in the object name will be interpreted as a folder by the SDK. Is backward slash is discouraged to be used in the file name? something like described here http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#storage-class-intro

**Comment by harshavardhana** [comment] 2016-03-05 01:36
> Wanted to whether know forward slash in the object name will be interpreted as a folder by the SDK. Is backward slash is discouraged to be used in the file name? something like described here http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#storage-class-intro

It is not interpreted by SDK , SDK behaves regardless what you are providing. A keyName can be any UTF-8 character with 1024 length. 

There is no special handling of '/' or without '/' .

**Comment by harshavardhana** [comment] 2016-03-05 02:12
> Wanted to whether know forward slash in the object name will be interpreted as a folder by the SDK. Is backward slash is discouraged to be used in the file name? something like described here http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#storage-class-intro

The interpretation of '/' happens on the server side at backend layer.

**Comment by hackintoshrao** [comment] 2016-03-05 18:23
This behavior seems to be different from how S3 behaves, and users coming form strong S3 background should be made aware of this.

**Comment by harshavardhana** [comment] 2016-03-05 20:48
> This behavior seems to be different from how S3 behaves, and users coming form strong S3 background should be made aware of this.

It is usually the other way round, what minio does is what S3 users expect.  Strong S3 background meaning they have applications which depend on certain API calls like versioning, lifecycle management etc which we don't support.

**Comment by hackintoshrao** [comment] 2016-03-06 02:57
> The interpretation of '/' happens on the server side at backend layer. 

But this is what S3 documentation claims 
`### Amazon S3 supports buckets and objects, there is no hierarchy in Amazon S3. However, the prefixes and delimiters in an object key name, enables the Amazon S3 console and the AWS SDKs to infer hierarchy and introduce concept of folders.`

**Comment by harshavardhana** [comment] 2016-03-06 03:16
`> ### Amazon S3 supports buckets and objects, there is no hierarchy in Amazon S3. However, the prefixes and delimiters in an object key name, enables the Amazon S3 console and the AWS SDKs to infer hierarchy and introduce concept of folders.`

Yeah it's a loosely coupled concept and on s3 anything is possible. But taking this into as an example imagine 

`/a/b/c` as the key name and also `/a/b/c/` as another keyname can exist on S3. But any tool for example cannot really make a real copy of this onto a local FS, the problem is that you cannot possibly have /a/b/c as directory and also as a file.

"Anything is possible" leads to common cases not being handled properly, since it is not a requirement 95% of the time.

**Comment by hackintoshrao** [comment] 2016-03-06 04:19
Hmm, yes ..I agree... That adds more strength to the reason for which this issue was opened. Even i don't feel the need for those extreme cases 99.99% of the times, but I do feel the need for documenting these above mentioned differences in behavior since it is necessary to convey this to someone who is migrating from S3 to Minio. It is important to tell them that "Hey, you know what. We know you've been using S3 from 5 years now and you always got away with creating objects with names like /a/b/c and also /a/b/c/, but this particular thing doesn't work in Minio because of the following reasons!".

**Comment by harshavardhana** [comment] 2016-05-08 10:37
This should move to documentation closing it here - Open this bug on https://github.com/minio/docs.minio.io

**Closed as completed by harshavardhana** 2016-05-08 10:37 UTC
Labels: priority: low
