### ISSUE TITLE
package: Package minio as a (virtual) storage appliance using bosh / Cloud Foundry. 

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#3718] opened 2017-02-08 08:41 UTC
We got request from our community on Slack for:
Package and maintain minio as a (virtual) storage appliance using bosh / Cloud Foundry.

**Comment by beddari** [comment] 2017-02-08 08:47
There are already several bosh releases, both for a single CF tenant and a distributed one, random google search:

https://github.com/dpb587/minio-bosh-release
https://github.com/shinji62/minio-dist-boshrelease
https://libraries.io/github/cloudfoundry-community/minio-boshrelease

It might be interesting to adopt/help maintain something like this as part of the minio project effort

**Comment by shinji62** [comment] 2017-02-09 00:16
Already list in awesome minio.

I think @shinji62 is the only one supporting distributed version.

**Comment by harshavardhana** [comment] 2017-03-04 11:45
Closing as duplicate of #3850

**Closed as completed by harshavardhana** 2017-03-04 11:45 UTC
Labels: community
