### ISSUE TITLE
Can't create a subfolder in a bucket using the web interface.

### ISSUE THREAD

**Issue by SaimonL** [minio/minio#4423] opened 2017-05-24 22:27 UTC
Can't create a subfolder in a bucket using the web interface.

**Comment by harshavardhana** [comment] 2017-05-24 22:28
Please follow the issue template @SaimonL - we cannot understand what is needed and what is not working if you don't provide us basic information.

It helps us triage internally.

**Comment by deekoder** [comment] 2017-05-24 23:16
I think this is by design @SaimonL

**Comment by deekoder** [comment] 2017-06-01 22:23
Closing this as this behavior is Minio compatible. Please reopen if you think this needs to be addressed.

**Closed as completed by deekoder** 2017-06-01 22:23 UTC
Labels: priority: low, out of scope
