### ISSUE TITLE
PutObjectPart does not override the file with same part number

### ISSUE THREAD

**Issue by TestMsr** [minio/minio#12609] opened 2021-07-01 01:35 UTC
## Expected Behavior

while CompleteMultipartUpload,the oldest upload part info is invalid,and get err response

## Current Behavior

CompleteMultipartUpload with the oldest upload part info ,it returns 200

## Possible Solution

1.CompleteMultipartUpload  checking the newest upload part may works
2.PutObjectPart remove the oldest part avoid racing is the best

## Steps to Reproduce (for bugs)

1.PutObjectPart part number 1
2.PutObjectPart with same part number 
3.CompleteMultipartUpload  with part info in step 1
4.return 200

## Your Environment

* Version used (`minio --version`):
abount 2021-04-18
* Server setup and configuration:
minio server ./data1
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment] 2021-07-01 02:33
@TestMsr I have no idea what you are talking about here.

How to finish CompleMultipart is a client responsibility, you neet to choose which part to save.

Please provide a full reproducer, going to close this issue until then.

**Comment by harshavardhana** [comment] 2021-07-01 02:34
You are also free to upgrade to latest release and test as well..

**Closed as completed by harshavardhana** 2021-07-01 02:33 UTC
Labels: community, triage

**Comment by TestMsr** [comment] 2021-07-01 03:16
sorry for my description @harshavardhana 

step to produce:
1.NewMultipartUpload and client get upload id
2.PutObjectPart,partNumber=1,get etag c4ca4238a0b923820dcc509a6f75849b
3.PutObjectPart again ,partNumber=1,get etag c81e728d9d4c2f636f067f89cc14862c
4.CompleteMultipartUpload,partinfo(partNumber=1,etag=c4ca4238a0b923820dcc509a6f75849b),it works!

https://play.golang.org/p/hT-57og8Vxs

as mentioned in s3 doc, _If you upload a new part using the same part number that was used with a previous part, the previously uploaded part is overwritten._,it shouldn't works

it returns _One or more of the specified parts could not be found._ in play.min.io but success while single drive mode or gateway nas(the latest release)

**Comment by harshavardhana** [comment] 2021-07-01 04:06
> sorry for my description @harshavardhana 
> 
> step to produce:
> 1.NewMultipartUpload and client get upload id
> 2.PutObjectPart,partNumber=1,get etag c4ca4238a0b923820dcc509a6f75849b
> 3.PutObjectPart again ,partNumber=1,get etag c81e728d9d4c2f636f067f89cc14862c
> 4.CompleteMultipartUpload,partinfo(partNumber=1,etag=c4ca4238a0b923820dcc509a6f75849b),it works!
> 
> https://play.golang.org/p/hT-57og8Vxs
> 
> as mentioned in s3 doc, _If you upload a new part using the same part number that was used with a previous part, the previously uploaded part is overwritten._,it shouldn't works
> 
> it returns _One or more of the specified parts could not be found._ in play.min.io but success while single drive mode or gateway nas(the latest release)
> 
> 

Single drive mode cannot support this behavior unfortunately @TestMsr because all parts are kept on server in single drive mode for appending the object at the end.

It is client responsibility to choose which part you are interested in. If you are willfully choosing an older part we can't do much.

We kept this behavior simple for single drive modes.. if you want S3 behavior use erasure coding.

**Comment by TestMsr** [comment] 2021-07-01 04:15
> > sorry for my description @harshavardhana
> > step to produce:
> > 1.NewMultipartUpload and client get upload id
> > 2.PutObjectPart,partNumber=1,get etag c4ca4238a0b923820dcc509a6f75849b
> > 3.PutObjectPart again ,partNumber=1,get etag c81e728d9d4c2f636f067f89cc14862c
> > 4.CompleteMultipartUpload,partinfo(partNumber=1,etag=c4ca4238a0b923820dcc509a6f75849b),it works!
> > https://play.golang.org/p/hT-57og8Vxs
> > as mentioned in s3 doc, _If you upload a new part using the same part number that was used with a previous part, the previously uploaded part is overwritten._,it shouldn't works
> > it returns _One or more of the specified parts could not be found._ in play.min.io but success while single drive mode or gateway nas(the latest release)
> 
> Single drive mode cannot support this behavior unfortunately @TestMsr because all parts are kept on server in single drive mode for appending the object at the end.
> 
> It is client responsibility to choose which part you are interested in. If you are willfully choosing an older part we can't do much.
> 
> We kept this behavior simple for single drive modes.. if you want S3 behavior use erasure coding.

thanks for your reply
