### ISSUE TITLE
Issue with PresignedGetObjectAsync

### ISSUE THREAD

**Issue by Rajeshrg55** [minio/minio#10495] opened 2020-09-16 14:27 UTC
Expected Behavior
A valid url should come based on the parameters served for PresignedGetObjectAsync

Current Behavior
public static string Get(string DocURL)
{
string[] filename = DocURL.Split('/');
var _containerName = filename[filename.Length - 2];
Task url = minioClient.PresignedGetObjectAsync(_containerName, filename[4], 2000);
return url.Result;
}

The above code is working fine but, file is getting downloaded instead of displaying when I'm parsing the url(which I'm getting in the result) into an I frame. Where as it is displaying with the other storage(Azure) urls.

The below code is the sample:

<iframe type="application/pdf" src="" allowfullscreen width="100%" height="100%"></iframe> When I'm trying to put a url from play.mini.io server it is getting displayed but file is getting downloaded when I'm trying with the url from server which I have hosted.
Context
while getting the presigned url from minio server

Regression
Yes
Your Environment
The SDKs I'm using in the project are :

Minio Version 3.1.10
RestSharp Version 106.3.1

**Comment by poornas** [comment] 2020-09-16 16:00
duplicate of https://github.com/minio/minio-dotnet/issues/461. Closing this

**Closed as completed by poornas** 2020-09-16 16:00 UTC
Labels: community, triage
