### ISSUE TITLE
tests: Need better coverage for control-heal-main.go

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2840] opened 2016-10-04 07:25 UTC

**Comment by GarimaKapoor** [comment] 2016-10-07 18:27
@krisis pease update the timeline for the fix.

**Comment by hackintoshrao** [comment] 2016-10-08 06:29
Timeline - 10th october.

**Comment by harshavardhana** [comment] 2016-10-08 06:40
> Timeline - 10th october.

are you working on this issue? ping @krisis

**Comment by hackintoshrao** [comment] 2016-10-08 06:43
I've put timeline on the wrong issue, sorry.

**Comment by krisis** [comment] 2016-10-08 08:48
I expect to fix this issue by the 10th Oct.

**Comment by GarimaKapoor** [comment] 2016-10-10 23:50
@krisis please update the status of this issue.

**Comment by krisis** [comment] 2016-10-11 04:58
I have not looked into this issue. I am investigating the root cause for sporadic failure of streaming signature putobject API request.

**Comment by harshavardhana** [comment] 2016-10-11 08:15
> I have not looked into this issue. I am investigating the root cause for sporadic failure of streaming signature putobject API request.

Will be fixed in the control-heal refactor, taking this issue and closing #2491

**Closed as completed by harshavardhana** 2016-10-11 08:15 UTC
