### ISSUE TITLE
[resolved] New release infinity loading screen on ARM

### ISSUE THREAD

**Issue by CX32** [minio/minio#10019] opened 2020-07-11 09:44 UTC
## Expected Behavior
1. Accessing minio through my web browser
2. minio listing the files I have

## Current Behavior
1. Infinity loading screen

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Update from the previous version to the latest version released 3 hours ago.

## Context
I am using a Raspberry Pi 3, Debian Buster on ARM. It previously worked but since the latest update, minio is stuck on a infinity loading screen. It works fine on version minio.RELEASE.2020-07-02T00-15-09Z. 

## Regression
Yes. I only know that it didn't happen with the previous version.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-07-11T06-07-16Z
* Server setup and configuration: Raspberry Pi 3, arm32 OS
* Operating System and version (`uname -a`): Linux host 5.4.50-v7+ #1324 SMP Wed Jul 1 17:00:22 BST 2020 armv7l GNU/Linux

**Comment by kannappanr** [comment] 2020-07-11 13:56
@CX32 Can you please let us know the command line parameters used to start `minio`?

**Comment by CX32** [comment] 2020-07-11 14:31
@kannappanr `./minio server MINIO_ACCESS_KEY MINIO_SECRET_KEY /mnt/data/`

**Comment by harshavardhana** [comment] 2020-07-11 20:12
Close your browser and restart again? There is nothing changed for single disk mode which can lead to this.

Did you build the binary yourself? If yes can you try our released binaries 

https://dl.minio.io/server/minio/release/linux-arm/minio

**Comment by CX32** [comment] 2020-07-11 21:32
@harshavardhana I tried different browsers, devices etc. I'm always using the release binaries officially provided by minio.

**Comment by minio-trusted** [comment] 2020-07-11 21:36
> @harshavardhana I tried different browsers, devices etc. I'm always using the release binaries officially provided by minio.

Just released try new release @CX32

**Comment by minio-trusted** [comment] 2020-07-11 21:37
> @kannappanr `./minio server MINIO_ACCESS_KEY MINIO_SECRET_KEY /mnt/data/`

BTW FWIW this command line looks incorrect `MINIO_ACCESS_KEY` `MINIO_SECRET_KEY` are environment variables not command line options.

**Comment by CX32** [comment] 2020-07-11 21:47
> > @harshavardhana I tried different browsers, devices etc. I'm always using the release binaries officially provided by minio.
> 
> Just released try new release @CX32

Same thing with minio version RELEASE.2020-07-11T21-14-23Z :(



> > @kannappanr `./minio server MINIO_ACCESS_KEY MINIO_SECRET_KEY /mnt/data/`
> 
> BTW FWIW this command line looks incorrect `MINIO_ACCESS_KEY` `MINIO_SECRET_KEY` are environment variables not command line options.

Yeah I just noticed that too. Apologies, I wasn't at home that time and just wrote down the way I remembered it. I am using minio as described in the systemd guide linked here: https://github.com/minio/minio-service/tree/master/linux-systemd
Anyway here are some more details: I'm starting minio with systemd, it's running behind an nginx reverse proxy, but other than that I'm using minio without anything special. No clue if I'm doing something wrong. :/

The only thing I notice that could be wrong is one error in the console: 
![image](https://user-images.githubusercontent.com/67905257/87234409-d311e280-c3d0-11ea-8ac5-8db05bef11aa.png)

**Comment by harshavardhana** [comment] 2020-07-11 21:48
Yeah, that looks like the browser bug @CX32 - can you provide more extended output from the console.

**Comment by CX32** [comment] 2020-07-11 21:53
@hackintoshrao I tried to pretty print the code but it still looks slightly messy. Unfortunately I don't think it's too helpful but this is what I see. Line 17 is very long so if you want any more details let me know.
![image](https://user-images.githubusercontent.com/67905257/87234479-a1e5e200-c3d1-11ea-9023-e825b5a2b1df.png)

**Comment by CX32** [comment] 2020-07-11 21:54
Also this is Firefox's output:
![image](https://user-images.githubusercontent.com/67905257/87234501-d194ea00-c3d1-11ea-90bc-74430a8df549.png)

**Comment by harshavardhana** [comment] 2020-07-11 21:57
> @hackintoshrao I tried to pretty print the code but it still looks slightly messy. Unfortunately I don't think it's too helpful but this is what I see. Line 17 is very long so if you want any more details let me know.

@CX32 just the console error is fine. It looks like something specific to ARM we will have to reproduce this on our own. Can't reproduce this on Linux or https://play.minio.io

**Comment by harshavardhana** [comment] 2020-07-13 05:51
> > @hackintoshrao I tried to pretty print the code but it still looks slightly messy. Unfortunately I don't think it's too helpful but this is what I see. Line 17 is very long so if you want any more details let me know.
> 
> @CX32 just the console error is fine. It looks like something specific to ARM we will have to reproduce this on our own. Can't reproduce this on Linux or https://play.minio.io 

Please use latest release and let us know?

**Comment by CX32** [comment] 2020-07-13 09:36
@harshavardhana same thing with minio version RELEASE.2020-07-12T19-14-17Z.

**Comment by harshavardhana** [comment] 2020-07-13 19:21
how about https://github.com/minio/minio/releases/tag/RELEASE.2020-07-13T18-09-56Z/  - can you check also if https://play.minio.io loads on your system?

**Comment by harshavardhana** [comment] 2020-07-13 19:21
Please share the console error if any @CX32

**Comment by CX32** [comment] 2020-07-13 19:40
> Please share the console error if any @CX32

@harshavardhana same thing on minio version RELEASE.2020-07-13T18-09-56Z. This is the error I get in the console: `Uncaught SyntaxError: "" literal not terminated before end of script index_bundle-2020-07-11T18-42-21Z.js:17:2744079`

Also yes, play.minio.io loads fine on my devices.

**Comment by harshavardhana** [comment] 2020-07-13 23:05
![arm32](https://user-images.githubusercontent.com/622699/87362123-9bb34b00-c522-11ea-842e-a6bc4722ab24.gif)

So I tested the binary on Raspberry PI ARM32 can't reproduce it. @CX32

**Comment by CX32** [comment] 2020-07-14 00:07
@harshavardhana Okay so apparently this is an nginx issue as direct access over IP works for me. I am using the nginx config provided here: https://docs.min.io/docs/setup-nginx-proxy-with-minio.html. Not sure what's wrong though. I don't see any relevant errors in the nginx error log. Version RELEASE.2020-07-02T00-15-09Z works fine with the nginx config provided but any version higher than that breaks it for some reason.

**Comment by harshavardhana** [comment] 2020-07-20 00:18
> @harshavardhana Okay so apparently this is an nginx issue as direct access over IP works for me. I am using the nginx config provided here: https://docs.min.io/docs/setup-nginx-proxy-with-minio.html. Not sure what's wrong though. I don't see any relevant errors in the nginx error log. Version RELEASE.2020-07-02T00-15-09Z works fine with the nginx config provided but any version higher than that breaks it for some reason.

This may be related to another reverse proxy issues we fixed in #10090

**Closed as completed by harshavardhana** 2020-07-20 00:18 UTC
Labels: community, fixed

**Comment by CX32** [comment] 2020-07-20 09:25
@harshavardhana Thanks! This fixed my issue. :)
