### ISSUE TITLE
Explore go cover tools for code coverage

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4658] opened 2017-07-10 18:43 UTC
Our code coverage plugin is showing conflicting numbers. It also shows failures in unrelated files not part of the PR. Having this be unreliable makes it really hard for the PR merger to merge with confidence.

**Comment by brendanashworth** [comment] 2017-07-21 00:03
The issue here doesn't lie with codecov (= switching to go cover will not help), it lies with our own tests. A few of our tests (file system related especially) won't always cover the exact same code path when they execute. There may be a race condition here or there that will trigger a different code path while still having the same end result, which gives different code coverage between equal runs while still passing the tests.

A good example of this is in `posix.go`. There is a single [`return nil` statement](https://codecov.io/gh/minio/minio/src/ecc7113b0257f37e026f65aaa20df05066904fef/cmd/posix.go#L95) which is only called under [a race condition](https://github.com/minio/minio/issues/3011). The race condition handling code was [added](https://github.com/minio/minio/commit/95567c68bfdc1c198125480bcb1e13d9d280c77f), but it wasn't added with a specific test that always triggered that code path. This means that, out of the [20,000 times `isDirEmpty` will be called](https://codecov.io/gh/minio/minio/src/ecc7113b0257f37e026f65aaa20df05066904fef/cmd/posix.go#L76) throughout the whole test suite, the race condition may only appear once, and it will do so at random. If it happened on master but not on a pull request, the coverage will decrease minutely; if it didn't happen on master but did on a pull request, it will increase minutely.

Because of these tests that have somewhat flaky code paths, the test coverage should have an error margin. Roughly within `~0.05%`, the test coverage is valid and should be taken into consideration, especially if the files are related to the change. If the code coverage is something like `+0.01%`, it is probably unrelated.

**Comment by deekoder** [comment] 2017-07-21 00:43
Thanks brendan! This explains the rootcause really well.

**Comment by brendanashworth** [comment] 2017-07-27 21:46
Here's a list of common culprit files:

- [x] ~~[`cmd/posix.go`](https://github.com/minio/minio/blob/ec5293ce29ef03726c7174d9e3304bc156259c4e/cmd/posix.go#L95) ([example](https://codecov.io/gh/minio/minio/pull/4695/src/cmd/posix.go#L95))~~ https://github.com/minio/minio/commit/28bc5899fdea9dd433c10ae480320c58ea48f093
- [x] ~~[`cmd/fs-v1-helpers.go`](https://github.com/minio/minio/blob/ec5293ce29ef03726c7174d9e3304bc156259c4e/cmd/fs-v1-helpers.go#L398-L412) ([example](https://codecov.io/gh/minio/minio/pull/4695/src/cmd/fs-v1-helpers.go#L398))~~ https://github.com/minio/minio/commit/bccc3869944f375c8b9f6a0c1f174feac1c5a7bd
- [ ] [`cmd/fs-v1-background-append.go`](https://github.com/minio/minio/blob/ec5293ce29ef03726c7174d9e3304bc156259c4e/cmd/fs-v1-background-append.go#L85-L88) ([example](https://codecov.io/gh/minio/minio/pull/4695/src/cmd/fs-v1-background-append.go#L85))
- [x] [`cmd/fs-v1-rwpool.go`](https://github.com/minio/minio/blob/ec5293ce29ef03726c7174d9e3304bc156259c4e/cmd/fs-v1-rwpool.go#L98-L115) ([example](https://codecov.io/gh/minio/minio/pull/4671/src/cmd/fs-v1-rwpool.go#L99))
- [x] [`cmd/xl-v1-common.go`](https://github.com/minio/minio/blob/ec5293ce29ef03726c7174d9e3304bc156259c4e/cmd/xl-v1-common.go#L53) ([example](https://codecov.io/gh/minio/minio/pull/4741/changes#L53))
- [ ] [`cmd/fs-v1-multipart.go`](https://github.com/minio/minio/blob/748b1d6495a24dd1d6432a5b34e04c58acd1c031/cmd/fs-v1-multipart.go) ([example](https://codecov.io/gh/minio/minio/compare/b4dc6df35c69210dde2c8355fcd137b240985a5b...188dd510efdfa6b7de29cd4b6f89585789cffb7c/src/cmd/fs-v1-multipart.go))
- [x] ~~[`cmd/fs-v1.go`](https://github.com/minio/minio/blob/748b1d6495a24dd1d6432a5b34e04c58acd1c031/cmd/fs-v1.go#L262) ([example](https://codecov.io/gh/minio/minio/compare/748b1d6495a24dd1d6432a5b34e04c58acd1c031...0a48f283056dfb57cca41fade45f8884ed4a31b7/src/cmd/fs-v1.go#L262))~~ https://github.com/minio/minio/commit/e7cdd8f02ce71399efcf69ac3b39ba290c3462e3
- [x] ~~[`cmd/posix-list-dir-nix.go`](https://github.com/minio/minio/blob/b3b42c72a94be698062c44d7cd2206e4bac5f8b5/cmd/posix-list-dir-nix.go#L141) ([example](https://codecov.io/gh/minio/minio/compare/b3b42c72a94be698062c44d7cd2206e4bac5f8b5...0a4a9f5a1a221fdbbcd5d04dfd0a133096ee53d8/src/cmd/posix-list-dir-nix.go#L141))~~

This list can be updated when coverage changes due to a racy condition in a file not listed. When it's fixed, a file can be crossed out. This is a good reference for checking code coverage to see if it's real or not, before the tests are fixed. I'm working on some of these right now.

**Comment by harshavardhana** [comment] 2017-08-07 07:38
Is this bug ready to be closed? @brendanashworth

**Comment by brendanashworth** [comment] 2017-08-07 16:55
@harshavardhana I'd suggest it stays open until all the tests have reliable code coverage, imo. According to my above ^ comment, when everything is checked.

**Comment by harshavardhana** [comment] 2017-08-07 18:53
> @harshavardhana I'd suggest it stays open until all the tests have reliable code coverage, imo. According to my above ^ comment, when everything is checked.

:+1:

**Comment by GarimaKapoor** [comment] 2017-08-28 04:29
@deekoder Is this resolved? are we seeing improvement in the code coverage?

**Comment by harshavardhana** [comment] 2017-08-28 06:47
> @deekoder Is this resolved? are we seeing improvement in the code coverage?

- [x] [`cmd/fs-v1-background-append.go`](https://github.com/minio/minio/blob/ec5293ce29ef03726c7174d9e3304bc156259c4e/cmd/fs-v1-background-append.go#L85-L88) ([example](https://codecov.io/gh/minio/minio/pull/4695/src/cmd/fs-v1-background-append.go#L85))
- [x] [`cmd/fs-v1-rwpool.go`](https://github.com/minio/minio/blob/ec5293ce29ef03726c7174d9e3304bc156259c4e/cmd/fs-v1-rwpool.go#L98-L115) ([example](https://codecov.io/gh/minio/minio/pull/4671/src/cmd/fs-v1-rwpool.go#L99))
- [x] [`cmd/fs-v1-multipart.go`](https://github.com/minio/minio/blob/748b1d6495a24dd1d6432a5b34e04c58acd1c031/cmd/fs-v1-multipart.go) ([example](https://codecov.io/gh/minio/minio/compare/b4dc6df35c69210dde2c8355fcd137b240985a5b...188dd510efdfa6b7de29cd4b6f89585789cffb7c/src/cmd/fs-v1-multipart.go))

There are three pending issues still which occur sporadically, for example in the following PR 
 [api: Fix the conditional to check for reserved buckets](https://github.com/minio/minio/pull/4856#issuecomment-324815828) - The above two files `fs-v1-rwpool.go` and `fs-v1-background-append.go` show up as loosing coverage but the PR doesn't do anything related to this part of the code at all.

**Comment by harshavardhana** [comment] 2018-01-18 22:56
Adding to this we also have one more file now which exhibits this behavior

- [ ] [`pkg/http/listener.go`](https://github.com/minio/minio/blob/dd5a3289dd66d9734a584d08835fd600f97963bd/pkg/http/listener.go#L254-L255)[example](https://codecov.io/gh/minio/minio/compare/e2d5a87b2676e3e01f0f4fa7ebd01205364cfb16...dcb9d1758691d3000d1bc41253f64dd8e1f1c40a/src/pkg/http/listener.go)

**Comment by harshavardhana** [comment] 2018-01-18 22:58
> cmd/fs-v1-background-append.go (example)

This is being addressed by PR https://github.com/minio/minio/pull/5401

**Comment by harshavardhana** [comment] 2018-02-02 12:14
With lockfree FS backend implemented the spuriously changing files seems to be fixed in fs-v1* , will monitor further to see if there are more files which needs to be fixed in the same manner.

**Comment by kannappanr** [comment] 2018-03-22 01:34
Closing this issue. Will reopen it if we see that the issue is still not fixed.

**Closed as completed by kannappanr** 2018-03-22 01:34 UTC
Labels: fixed, priority: medium
