### ISSUE TITLE
files corrupted after rolling upgrade

### ISSUE THREAD

**Issue by sungwoooo** [minio/minio#12453] opened 2021-06-07 05:51 UTC
lots of files have been corrupted after rolling upgrade from RELEASE.2020-03-25T07-03-04Z to RELEASE.2021-05-11T23-27-41Z. 
is there any way to recover corrupted files?

## Expected Behavior

able to copy existing files normally after minio upgraded

## Current Behavior

got error messages below when trying to copy files.
`
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.: cause(file is corrupted)</Message><Key>raw-data/asdfile-newest/data/part-00016-78d800ec-1d32-4f85-b1cc-6460cb7dccc2-c000.snappy.parquet</Key><BucketName>adl-data</BucketName><Resource>/adl-data/raw-data/asdfile-newest/data/part-00016-78d800ec-1d32-4f85-b1cc-6460cb7dccc2-c000.snappy.parquet</Resource><RequestId>1680BB059DCB9379</RequestId><HostId>97b6620c-62a2-4b19-bc62-84c5fa89aa2c</HostId></Error>
`

`
API: SYSTEM() 5/21/2021 9:04:26 AM Time: 00:04:26 UTC 05/21/2021 5/21/2021 9:04:26 AM DeploymentID: 97b6620c-62a2-4b19-bc62-84c5fa89aa2c 5/21/2021 9:04:26 AM Error: Disk: http://minio-3.minio-svc.minio.svc.cluster.local:9000/data2/local-minio-pv -> adl-data/raw-data/asdfile-newest/data/part-00016-78d800ec-1d32-4f85-b1cc-6460cb7dccc2-c000.snappy.parquet/b36a116e-1375-4f3a-bb21-039f7252bf1e/part.1 - content hash does not match - expected 03dd56429a50f0390d530aaa1c40a039d3a3ec0fefb2748f942a7ec7a3682daa, got 29a523c418db7b977bfeaa361d7b6b48a5b98a7654d2e9327170e2ec2be46c3f (*errors.errorString) 5/21/2021 9:04:26 AM 2: cmd/bitrot-streaming.go:173:cmd.(*streamingBitrotReader).ReadAt() 5/21/2021 9:04:26 AM 1: cmd/erasure-decode.go:165:cmd.(*parallelReader).Read.func1()
`

on web browser
`
This site can’t be reached
The webpage at https:/xxx/adl-data/raw-data/asdfile-test/data/part-00486-31823839-1f00-42fc-9f30-6b35f19e71e5-c000.snappy.parquet?token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJhaWxhYiIsImV4cCI6MTYyMzA0NDA5OCwic3ViIjoiYWlsYWIifQ.BXNMW6cyMziO8JZLnto7oPUa3LsKyRD7gNRlnEYC9kJsWi6OkdCeeBk8tkSN0kMwxuQFTt_e0qTnUcbhJDW_Vw might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE
`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
RELEASE.2021-05-11T23-27-41Z
* Server setup and configuration: 
distributed mode with 6 nodes in k8s, helm chart version 5.0.23
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment] 2021-06-07 05:53
What is your deployment configuration can you share it here ?

**Comment by sungwoooo** [comment] 2021-06-07 06:21
please see the values below
(some values are removed because of company policy)

nameOverride: ""
fullnameOverride: ""
clusterDomain: cluster.local

image:
  repository: 
  tag: RELEASE.2021-05-11T23-27-41Z
  pullPolicy: IfNotPresent

mcImage:
  repository: 
  tag: RELEASE.2021-05-12T03-10-11Z
  pullPolicy: IfNotPresent

helmKubectlJqImage:
  repository: bskim45/helm-kubectl-jq
  tag: 3.1.0
  pullPolicy: IfNotPresent

mode: distributed

extraArgs: []

DeploymentUpdate:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 100%

StatefulSetUpdate:
  updateStrategy: RollingUpdate

priorityClassName: ""


existingSecret: ""
accessKey: 
secretKey: 
certsPath: "/etc/minio/certs/"
configPathmc: "/etc/minio/mc/"
mountPath: "/data2/local-minio-pv"

bucketRoot: ""
drivesPerNode: 1
replicas: 6
zones: 1

tls:
  enabled: false
  certSecret: ""
  publicCrt: public.crt
  privateKey: private.key

persistence:
  enabled: true
  existingClaim: ""
  storageClass: "local-minio-storage"
  VolumeName: ""
  accessMode: ReadWriteOnce
  size: 100Ti
  subPath: ""

service:
  type: ClusterIP
  clusterIP: ~
  port: 9000
  nodePort: 32000
  externalIPs: []
  annotations: {}

imagePullSecrets: []

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  path: /
  hosts:
    - 
  tls:
    - secretName: 
      hosts:
        - 

nodeSelector:
  node-role/minio: "true"
tolerations: []
affinity: {}

securityContext:
  enabled: false
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

podAnnotations: {}

podLabels: {}

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 1
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 6
  successThreshold: 1
  failureThreshold: 3

resources:
  requests:
    memory: 4Gi

defaultBucket:
  enabled: false
  name: bucket
  policy: none
  purge: false

buckets: []

makeBucketJob:
  annotations:

updatePrometheusJob:
  annotations:
s3gateway:
  enabled: false
  replicas: 4
  serviceEndpoint: ""
  accessKey: ""
  secretKey: ""

azuregateway:
  enabled: false
  replicas: 4

gcsgateway:
  enabled: false
  replicas: 4
  gcsKeyJson: ""
  projectId: ""

ossgateway:
  enabled: false
  replicas: 4
  endpointURL: ""

nasgateway:
  enabled: false
  replicas: 4
  pv: ~

b2gateway:
  enabled: false
  replicas: 4

environment:
  MINIO_API_READY_DEADLINE: "5s"

networkPolicy:
  enabled: false
  allowExternal: true

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1

serviceAccount:
  create: true
  name:

metrics:
  serviceMonitor:
    enabled: false
    additionalLabels: {}

etcd:
  endpoints: []
  pathPrefix: ""
  corednsPathPrefix: ""
  clientCert: ""
  clientCertKey: ""

**Comment by harshavardhana** [comment] 2021-06-07 06:34
What is the operating system under use ?

**Comment by sungwoooo** [comment] 2021-06-07 06:59
It's CentOS 7.

**Comment by harshavardhana** [comment] 2021-06-07 14:28
> It's CentOS 7.

what is the backend filesystem? @sungwoooo are you on x86_64 or arm64?

**Comment by harshavardhana** [comment] 2021-06-07 14:31
Closing as duplicate of #12451

**Closed as completed by harshavardhana** 2021-06-07 14:31 UTC
Labels: duplicate, community
