### ISSUE TITLE
connection refused when deployed on a specific namespace 

### ISSUE THREAD

**Issue by ddib** [minio/minio#6210] opened 2018-07-31 03:38 UTC
I deploy minio within a specific namespace 

## Expected Behavior
 Access minio as when deployed within the default name space 

## Current Behavior

The deployment is fine. However port-forward fails as follows 

```
kubectl port-forward minio-1 9000:9000
Forwarding from 127.0.0.1:9000 -> 9000
Forwarding from [::1]:9000 -> 9000
Handling connection for 9000
Handling connection for 9000
E0730 18:26:02.615524    8299 portforward.go:331] an error occurred forwarding 9000 -> 9000: error forwarding port 9000 to pod 38f207fc4d48fe330ddad027dea1daa21febf34ba3e13b811ea29a7a24513a24, uid : exit status 1: 2018/07/31 01:26:02 socat[28360] E connect(5, AF=2 127.0.0.1:9000, 16): Connection refused
E0730 18:26:02.618393    8299 portforward.go:331] an error occurred forwarding 9000 -> 9000: error forwarding port 9000 to pod 38f207fc4d48fe330ddad027dea1daa21febf34ba3e13b811ea29a7a24513a24, uid : exit status 1: 2018/07/31 01:26:02 socat[28361] E connect(5, AF=2 127.0.0.1:9000, 16): Connection refused
Handling connection for 9000
E0730 18:26:02.624532    8299 portforward.go:331] an error occurred forwarding 9000 -> 9000: error forwarding port 9000 to pod 38f207fc4d48fe330ddad027dea1daa21febf34ba3e13b811ea29a7a24513a24, uid : exit status 1: 2018/07/31 01:26:02 socat[28362] E connect(5, AF=2 127.0.0.1:9000, 16): Connection refused
Handling connection for 9000
Handling connection for 9000
E0730 18:26:06.171745    8299 portforward.go:331] an error occurred forwarding 9000 -> 9000: error forwarding port 9000 to pod 38f207fc4d48fe330ddad027dea1daa21febf34ba3e13b811ea29a7a24513a24, uid : exit status 1: 2018/07/31 01:26:06 socat[28381] E connect(5, AF=2 127.0.0.1:9000, 16): Connection refused
E0730 18:26:06.174777    8299 portforward.go:331] an error occurred forwarding 9000 -> 9000: error forwarding port 9000 to pod 38f207fc4d48fe330ddad027dea1daa21febf34ba3e13b811ea29a7a24513a24, uid : exit status 1: 2018/07/31 01:26:06 socat[28382] E connect(5, AF=2 127.0.0.1:9000, 16): Connection refused

```

## Steps to Reproduce (for bugs)

1. create namespace 'my_namespace'
2. set the right namespace in kubectl:
`kubectl config set-context $(kubectl config current-context) --namespace=my_namespace`
3. launch the script "minio_distributed.sh" 
4. check the deployment (everything was fine for me)
5. port-forward 
`kubectl port-forward minio-1 9000:9000`
6. go localhost:9000

## Context

II
I want to deploy minio and kafka in the kubeless namespace 

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1): minikube v0.28.2
* Server type and version:
* Operating System and version (`uname -a`): Linux  4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:  https://github.com/kubeless/functions/tree/master/incubator/minio-resize

**Comment by nitisht** [comment] 2018-07-31 04:47
@ddib can you share how did you start Minio? I mean yaml files etc, also `kubectl logs` for Minio pods

**Comment by ddib** [comment] 2018-07-31 06:33
I followed the steps of this [tutorial](https://github.com/minio/minio/blob/master/docs/orchestration/minikube/README.md). same yaml file.

The `kubectl logs <minio-pods>` doesn't return anything.

**Comment by nitisht** [comment] 2018-07-31 08:50
> The kubectl logs <minio-pods> doesn't return anything.

This generally means Minio is not up. Can you try `kubectl describe pods/<minio-pods>`

**Comment by ddib** [comment] 2018-07-31 16:48
```
$ kubectl describe pods/minio-0
Name:           minio-0
Namespace:      kubeless
Node:           minikube/10.0.2.15
Start Time:     Tue, 31 Jul 2018 09:43:30 -0700
Labels:         app=minio
                controller-revision-hash=minio-56f68fbbbf
                statefulset.kubernetes.io/pod-name=minio-0
Annotations:    <none>
Status:         Running
IP:             172.17.0.6
Controlled By:  StatefulSet/minio
Containers:
  minio:
    Container ID:  docker://a2be8199a48b0990f08821d12dddc2d2e45773d170f212d5130ade4a5c9f703a
    Image:         minio/minio:RELEASE.2018-07-23T18-34-49Z
    Image ID:      docker-pullable://minio/minio@sha256:5941d9726df97f9dfbddc8039db4063dc543a67f801f26fcac55747cef4fe78c
    Port:          9000/TCP
    Host Port:     0/TCP
    Args:
      server
      http://minio-0.minio.default.svc.cluster.local/data
      http://minio-1.minio.default.svc.cluster.local/data
      http://minio-2.minio.default.svc.cluster.local/data
      http://minio-3.minio.default.svc.cluster.local/data
    State:          Running
      Started:      Tue, 31 Jul 2018 09:43:44 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      MINIO_ACCESS_KEY:  minio
      MINIO_SECRET_KEY:  minio123
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8hxzr (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          True 
  PodScheduled   True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-minio-0
    ReadOnly:   false
  default-token-8hxzr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8hxzr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From               Message
  ----    ------                 ----  ----               -------
  Normal  Scheduled              2m    default-scheduler  Successfully assigned minio-0 to minikube
  Normal  SuccessfulMountVolume  2m    kubelet, minikube  MountVolume.SetUp succeeded for volume "pvc-d731953b-94e0-11e8-a4c7-080027f5c0b7"
  Normal  SuccessfulMountVolume  2m    kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-8hxzr"
  Normal  Pulled                 2m    kubelet, minikube  Container image "minio/minio:RELEASE.2018-07-23T18-34-49Z" already present on machine
  Normal  Created                2m    kubelet, minikube  Created container
  Normal  Started                2m    kubelet, minikube  Started container

```

**Comment by nitisht** [comment] 2018-08-01 03:31
@ddib looks like the URL `http://minio-0.minio.default.svc.cluster.local/data` is incorrect, as it indicates default namespace. 

It should be changed to `http://minio-0.minio.kubeless.svc.cluster.local/data`

(Ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-identity)

**Comment by ddib** [comment] 2018-08-01 05:00
Thank you so much @nitisht, it is working now. This should be passed as a variable, to be able to deploy minio on any namespace without modifying the yaml file.

**Comment by nitisht** [comment] 2018-08-01 05:14
> This should be passed as a variable, to be able to deploy minio on any namespace without modifying the yaml file.

Feel free to send a PR @ddib . Thanks for bringing this up. Closing the issue as working as intended.

**Closed as completed** 2018-08-01 05:14 UTC
Labels: working as intended, priority: medium
