### ISSUE TITLE
Minio still fails with IPv6.

### ISSUE THREAD

**Issue by zajdee** [minio/minio#15918] opened 2022-10-21 12:49 UTC
The issue was reported in https://github.com/minio/minio/issues/6946 but the issue was closed without proper resolution.

It's 2022 and the issue is still there. IPv6 is no longer an optional feature, as many datacenters go IPv6-only.

Please consider fixing of the issue.
Please do not autoclose bug/issue reports, as that's a really bad habit.

Thank you.

**Comment by ravindk89** [comment] 2022-10-21 14:00
The issue was addressed by https://github.com/minio/minio/pull/6947

The OP of that issue confirmed the issue was fixed here: https://github.com/minio/minio/issues/6946#issuecomment-446529730

We still have a test suite that runs IPv6 validation in our regular build tests here: https://github.com/minio/minio/blob/master/buildscripts/verify-build.sh#L67-L76

We have made other fixes related to IPv6 since theren: https://github.com/minio/minio/issues/11833

Declaring that the issue was closed without proper resolution is willfully misleading.

If you are seeing an issue now, then provide logs and data for us to look at. Maybe there has been a regression, maybe it's an edge case, maybe it's something that your specific network infra requires. You have provided no information and are demanding a solution.

Start with the basics. Logs, versions, repro scripts or steps. Then lets see how we can help.

**Comment by harshavardhana** [comment] 2022-10-21 16:08
> The issue was reported in #6946 but the issue was closed without proper resolution.
> 
> It's 2022 and the issue is still there. IPv6 is no longer an optional feature, as many datacenters go IPv6-only.
> 
> Please consider fixing of the issue. Please do not autoclose bug/issue reports, as that's a really bad habit.
> 
> Thank you.

There is nothing reported here. Closing.

**Closed as completed by harshavardhana** 2022-10-21 16:08 UTC
Labels: community, triage
