### ISSUE TITLE
When user logs in and out using Open ID login, credentials are not asked on subsequent logins

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#8597] opened 2019-12-03 19:26 UTC
## Expected Behavior

Once a user has already logged in and logged out via Open ID Login, it should ask for user credentials again on subsequent logins.

## Current Behavior

When a user has already logged in and logged out via Open ID Login, on subsequent logins, user credentials are not asked and users are logged in as the previously logged out user.

## Possible Solution

This might be caused by the duration of the Access Token Lifespan on Keycloak settings, but even after setting it to 1 minute, this still seems to be happening as the users aren't being redirected to the login prompt.

We might also want to check if there is any JWT token caching happening on the Open ID side which is not triggering the user credentials to be displayed.

## Steps to Reproduce (for bugs)

1. Follow the steps listed on https://github.com/minio/minio/blob/master/docs/sts/keycloak.md, which includes logging in as the created user
2. Log out of the MinIO Browser
3. Log in once again and verify that the user credentials are not being asked and the user is logged in as the user created on Step 1

## Context

There might be a case where someone creates two users (say `user1` and `user2`), logs in as `user1`, logs out, and then tries to log in as `user2`. Currently this doesn't seem possible as when we log in as `user1` initially and log out, on the subsequent logins we seem to be logged in as the user that logged in earlier.

## Regression

Issue seems to be introduced when the Open ID login feature was merged on #8392

## Your Environment

* Version used (`minio version`): master with latest commit hash `2ab8d5e`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment] 2019-12-03 20:05
This I figured is a feature of Keycloack @kaankabalak because keycloack is setting some cookies on the browser which allows for auto-login until the login expires on keycloack

**Comment by kaankabalak** [comment] 2019-12-03 21:02
Thanks for the clarification @harshavardhana, I think we can close this issue then, because it is working as intended.

**Comment by harshavardhana** [comment] 2019-12-03 23:57
Closing this as working as intended

**Closed as completed by harshavardhana** 2019-12-03 23:57 UTC
Labels: working as intended, community, triage
