### ISSUE TITLE
support SFTP upload to trigger S3 put notification

### ISSUE THREAD

**Issue by cawfeecoder** [minio/minio#19317] opened 2024-03-21 19:35 UTC
**Is your feature request related to a problem? Please describe.**
I expected to receive a S3 put notification when uploading a file via SFTP

**Describe the solution you'd like**
Either fire an S3 put notification event (or some equivalent event) when a file is uploaded via SFTP

**Describe alternatives you've considered**
This is feeding a workflow. I could always switch the workflow to a cron timer to check the bucket vs listening for the put event.

**Additional context**
None

**Comment by harshavardhana** [comment] 2024-03-21 19:43
sftp PUT is expected to invoke PutObject() call notification, its by design.

**Comment by cawfeecoder** [comment] 2024-03-21 22:22
> sftp PUT is expected to invoke PutObject() call notification, its by design.

I’m not seeing that behavior running Minio 2024-03-15T01:07:19Z

**Comment by zveinn** [comment] 2024-03-22 14:53
I tested SFTP with 'mc admin trace --call s3 [alias]' enabled, audit logs enabled and webhook notifications enabled and they all seems to be generating results. 

![image](https://github.com/minio/minio/assets/20964930/b820deca-9a0e-485e-8552-cfe206d7bdd3)
![image](https://github.com/minio/minio/assets/20964930/3f88fbdd-3210-44ed-a227-e03a24ad2f35)
![image](https://github.com/minio/minio/assets/20964930/989a70a0-7872-4c45-8a7b-b346568596c1)

Could you describe the steps you took to enable notifications ? also if you open the console and inspect the bucket, do you see the ARN assigned to that bucket with the appropriate events ? 
@cawfeecoder

**Closed as completed** 2024-03-27 08:37 UTC
Labels: working as intended, community, waiting for info
