### ISSUE TITLE
Run Minio as another user - 500 error on cp

### ISSUE THREAD

**Issue by bitva77** [minio/minio#5862] opened 2018-04-26 21:06 UTC
## Expected Behavior
mc cp hello.txt minio-test/mnt/shared_content/  would succeed.

## Current Behavior
It loops and eventually errors out.

## Steps to Reproduce (for bugs)

1.  Build minio like:

FROM minio/minio
RUN adduser -u 55556 -G root default
USER default

2.  Run it like:

docker run -d --restart unless-stopped -p 9000:9000 --name minio -v /minio:/minio -v /mnt:/mnt -v /etc/minio:/etc/minio myregistryserver/minio/minio server --config-dir /etc/minio /minio

3.  Try to put a file:

./mc cp hello.txt minio-4d/mnt/shared_content/

## Context
/mnt/shared_content is an NFS file share.  /minio/mnt is a symlink to /mnt which actually contains various NFS mounts.

## Your Environment

* Version used (`minio version`):  minio/minio:latest
* Server type and version:  RHEL 7.4

Here's the debug from the server:

```
API: PutObject(bucket=mnt, object=shared_content/hello.txt)
Time: 21:00:40 UTC 04/26/2018
RemoteHost: 172.17.0.1:58082
UserAgent: Minio (linux; amd64) minio-go/4.0.7 mc/2018-01-18T21:18:56Z
Error: file access denied
       1: cmd/fs-v1-helpers.go:235:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).parentDirIsObject.func1()
       3: cmd/fs-v1.go:612:cmd.(*FSObjects).parentDirIsObject()
       4: cmd/fs-v1.go:675:cmd.(*FSObjects).putObject()
       5: cmd/fs-v1.go:630:cmd.(*FSObjects).PutObject()
       6: cmd/object-handlers.go:660:cmd.(ObjectLayer).PutObject-fm()
       7: cmd/object-handlers.go:733:cmd.objectAPIHandlers.PutObjectHandler()
       8: cmd/api-router.go:77:cmd.(objectAPIHandlers).PutObjectHandler-fm()
       9: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: PutObject(bucket=mnt, object=shared_content/hello.txt)
Time: 21:00:40 UTC 04/26/2018
RemoteHost: 172.17.0.1:58082
UserAgent: Minio (linux; amd64) minio-go/4.0.7 mc/2018-01-18T21:18:56Z
Error: Rename across devices not allowed, please fix your backend configuration (/minio/.minio.sys/tmp/2372b0c9-b758-4783-8d23-a2df9c1ff0dc/a10a8bd3-58ac-45f4-a3f8-9acd5614a381)->(/minio/mnt/shared_content/hello.txt)
       1: cmd/fs-v1-helpers.go:378:cmd.fsRenameFile()
       2: cmd/fs-v1.go:748:cmd.(*FSObjects).putObject()
       3: cmd/fs-v1.go:630:cmd.(*FSObjects).PutObject()
       4: cmd/object-handlers.go:660:cmd.(ObjectLayer).PutObject-fm()
       5: cmd/object-handlers.go:733:cmd.objectAPIHandlers.PutObjectHandler()
       6: cmd/api-router.go:77:cmd.(objectAPIHandlers).PutObjectHandler-fm()
       7: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

I can verify that within the container, I can access and write to that path:

cd /mnt/shared_content
echo hello >hello.txt
/mnt/shared_content $ id
uid=55556 gid=0(root)
/mnt/shared_content $ ls -la hello.txt
-rw-r--r--    1 55556    root             6 Apr 26 21:06 hello.txt

**Comment by harshavardhana** [comment] 2018-04-26 21:11
> Error: Rename across devices not allowed, please fix your backend configuration (/minio/.minio.sys/tmp/2372b0c9-b758-4783-8d23-a2df9c1ff0dc/a10a8bd3-58ac-45f4-a3f8-9acd5614a381)->(/minio/mnt/shared_content/hello.txt)

This is expected @bitva77 you cannot use different backends for /minio/mnt and /minio

**Comment by harshavardhana** [comment] 2018-04-27 09:16
@deekoder this is not a bug relevant other bugs 

- https://github.com/minio/minio/issues/5080
- https://github.com/minio/minio/issues/4655

**Comment by nitisht** [comment] 2018-04-28 13:40
@bitva77 since this is expected behaviour, closing this issue as working as intended. Feel free to get back if you have further questions.

**Closed as completed by nitisht** 2018-04-28 13:40 UTC
Labels: working as intended, priority: medium
