### ISSUE TITLE
A timeout occurred while trying to lock a resource, please reduce your request rate

### ISSUE THREAD

**Issue by catiz** [minio/minio#15442] opened 2022-07-31 02:07 UTC
## NOTE
This problem is encountered after I open HTTPS, when I try to delete files with .exe and .apk extensions, they will not be deleted and the message "Timeout occurred while trying to lock the resource, please reduce your request rate" content
Currently this problem I found only in the .exe and .apk suffix files, when I delete the zip format or image format is all normal, upload any suffix file is also all normal, only in the deletion of these two suffixes encountered (there may be other suffix files)
 

## Expected Behavior
Under normal circumstances, the file will be deleted

## Current Behavior
Prompt "A timeout occurred while trying to lock a resource, please reduce your request rate"
HTTPS URL /api/v1/buckets/test/delete-objects?all_versions=false
The returned json is
```json
{"code":500,"detailedMessage":"A timeout occurred while trying to lock a resource, please reduce your request rate","message":"an error occurred, please try again"}
```

## Steps to Reproduce (for bugs)

1. Upload the crt certificate and key file of the domain to the /root/.minio/certs directory of the server
2. My startup command is
/minio/minio server /mnt/sda1 --console-address ":2083" --address "domain.com:2053"
3. Modify the hosts file and add the following content
192.168.31.2 domain.com
If not added, my minio can not start, this is the way I found in Google
4. Upload xx.exe and xx.apk files to the storage bucket
5. Error deleting xx.exe and xx.apk

## Context

The server is Linux arm64
I started minio using the binary
The version of minio is the latest version as of July 30, 2022

## Regression

I did not try to roll back the version, but the problem persists in versions after at least July 26, 2022

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2022-07-30T05-21-40Z
```
* Operating System and version (`uname -a`):
```
Linux OpenWrt 5.4.203 #0 SMP PREEMPT Tue Jul 12 10:40:55 2022 aarch64 GNU/Linux
```

**Comment by harshavardhana** [comment] 2022-07-31 05:09
> ```json
> ```json
> {"code":500,"detailedMessage":"A timeout occurred while trying to lock a resource, please reduce your request rate","message":"an error occurred, please try again"}
> ```


This means that you already have a lock and we couldn't lock your resource. This is not a MinIO version-related problem you have conflicting locks on the object i.e 

Either you are trying to delete while uploading - please provide a reproducer @catiz

**Comment by harshavardhana** [comment] 2022-07-31 15:58
Closing as duplicate of https://github.com/minio/minio/issues/15405

**Closed as completed by harshavardhana** 2022-07-31 15:58 UTC
Labels: community, fixed

**Comment by Rush** [comment] 2022-09-07 20:18
> This is not a MinIO version-related problem you have conflicting locks on the object i.e

I have the same issue. I am uploading a 300MB or so file to minio via our CI based on the app version. Every few weeks we encounter an issue that we cannot overwrite the same file, say "release-2.1.15.tgz" with the error:

```
A timeout occurred while trying to lock a resource, please reduce your request rate
```

No requests are being done to this file other than trying to overwrite it. There is no "request rate" to reduce.

**Comment by harshavardhana** [comment] 2022-09-07 22:07
@Rush what you are talking about here is unrelated to the issue here which is fixed. Please make sure that you are running the latest version of MinIO and open separate issues.
