### ISSUE TITLE
Test: TestGetObject Go Routine leaks after tests are finished. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2230] opened 2016-07-19 03:37 UTC
## Expected behaviour

No pending/leaked go routine after tests process has ended. 
## Actual behaviour

objcache.(*Cache).startGC , minio.signalTrap , minio.registerShutdown running even after the test process finishd executing. 
## Steps to reproduce the behaviour

A defer print statements in the above functions and run `go test -run=TestGet*`
## Minio version

Latest master 27a5b61f40fc1747bf759ed7555e8d3ebb636c5f
## System information

OSX El Captain.

**Comment by GarimaKapoor** [comment] 2016-07-21 01:02
Please update the timeline for the fix.

**Comment by krisis** [comment] 2016-07-21 21:46
@hackintoshrao GetObject unit-tests are independent of the go routines such as objcache.(*cache).startGC, minio.signalTrap, etc. It is natural that unit-tests aren't aware of these go-routines and therefore don't do anything special to 'reap' them. e.g, Imagine a unit-test for a private function that sorts integer for various []int values. Would it make sense to expect it to perform cleanup of all go-routines that could have been spawned as part of importing the `main` package? Further, if we added newer go-routines to the server process, do we change this unit-test that sorts []int and other unit-tests too?

I think this is not a bug in our unit-tests.

**Comment by hackintoshrao** [comment] 2016-07-22 00:55
@krisis : The issue is after the test process finishes execution it leaves behind tens of zombie Go routines which are dangling around, that's not acceptable, a simple solution could be call the done channel of these routines by the end of the tests.

**Comment by krisis** [comment] 2016-07-22 03:38
@hackintoshrao And to which process do these Go routines belong to? Could you paste the output of `ps ax` showing the corresponding processes?

**Comment by krisis** [comment] 2016-07-22 06:05
After discussing this with @hackintoshrao, there is nothing to be fixed in the unit-tests to close the go-routines before the test completes. We could explore the impact of these go-routines beyond the scope of a single test function, when the tests are run via `go test -v` (i.e, all tests are run)

**Comment by krisis** [comment] 2016-07-22 16:15
@hackintoshrao @harshavardhana If we agree that 'reaping' go-routines listed above are outside the scope of unit-tests, we should close this issue.

**Comment by harshavardhana** [comment] 2016-07-22 18:45
> @hackintoshrao @harshavardhana If we agree that 'reaping' go-routines listed above are outside the scope of unit-tests, we should close this issue.

Yes, closing.

**Closed as completed by harshavardhana** 2016-07-22 18:45 UTC
