### ISSUE TITLE
Ability to pass sessionToken using Java client

### ISSUE THREAD

**Issue by davemsolomon** [minio/minio#8674] opened 2019-12-19 18:06 UTC
the java client doesn’t currently implement  the ability to pass a sessionToken, which means the java client can not do “assumerolewithldapidentity”. 

I would like to be able to use the java client to consume minio integrated with ldap.

**Comment by harshavardhana** [comment] 2019-12-19 18:10
Closing as duplicate of https://github.com/minio/minio-java/issues/793

**Closed as completed by harshavardhana** 2019-12-19 18:10 UTC
Labels: duplicate, community
