### ISSUE TITLE
403 Forbidden error while doing hadoop ls

### ISSUE THREAD

**Issue by lmf5103510** [minio/minio#7766] opened 2019-06-11 08:30 UTC
When trying to do haddop fs -ls to list files/folders, minio server is throwing 403; Error Code: 403 Forbidden.  Related issue #6220 
## Expected Behavior
hadoop fs -ls  s3a://spark-new/test.json

and 

hadoop fs -ls  s3a://spark-new/

should both work

## Current Behavior
Only
hadoop fs -ls  s3a://spark-new/
is working, shows:
Found 1 items
-rw-rw-rw-   1 root root          5 2019-06-09 22:48 s3a://spark-new/test.json

For 
hadoop fs -ls  s3a://spark-new/test.json

ls: s3a://spark-new/user/root: getFileStatus on s3a://spark-new/user/root: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden

## Steps to Reproduce (for bugs)
1. have hadoop conf in /hadoop/etc/hadoop/core-site.xml like:
   
    <name>fs.s3a.endpoint</name>
    <value>http://10.**.**.**:9000</value>

    <name>fs.s3a.access.key</name>
    <value>*****</value>

    <name>fs.s3a.secret.key</name>
    <value>********</value>

    <name>fs.s3a.path.style.access</name>
    <value>true</value>

    <name>fs.s3a.impl</name>
    <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>

2. run Hadoop with its start-all.sh
3. run hadoop fs -ls command

## Context
Following online minio tutorial and get this error

## Regression
Perhaps #6220 ?

## Your Environment
Version: 2019-06-04T01:15:58Z
hadoop 3.1.2

**Comment by kannappanr** [comment] 2019-06-11 14:03
@lmf5103510 Thanks for filing this issue. Will try to repro this error and get back to you.

**Comment by harshavardhana** [comment] 2019-06-11 16:34
> For
> hadoop fs -ls s3a://spark-new/test.json

> ls: s3a://spark-new/user/root: getFileStatus on s3a://spark-new/user/root: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden

This looks wrong, you are listing test.json instead Hadoop is listing /user/root ?

**Comment by lmf5103510** [comment] 2019-06-12 02:06
Sorry, I copied wrong log. I tried again:

hadoop fs -ls  s3a://spark-new/
Found 1 items
-rw-rw-rw-   1 root root          5 2019-06-09 22:48 s3a://spark-new/test.json

hadoop fs -ls  s3a://spark-new/test.json
ls: s3a://spark-new/test.json: getFileStatus on s3a://spark-new/test.json: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null:403 Forbidden

**Comment by harshavardhana** [comment] 2019-06-20 07:36
I think there is some local issue, not able to reproduce the issue with hortonworks latest distribution.

**Comment by harshavardhana** [comment] 2019-06-24 17:37
Closing this since this looks like a setup issue @lmf5103510

**Closed as completed by harshavardhana** 2019-06-24 17:37 UTC
Labels: working as intended, community, triage

**Comment by speeddragon** [comment] 2019-12-20 17:48
I'm having the same issue.

My configuration file is the same as [here](https://github.com/minio/cookbook/blob/master/docs/apache-spark-with-minio.md#3-start-spark-shell). It works great with AWS.

I've debug where it fails, and this is the behaviour of the AWS S3 Client.
* Request HEAD of bucket.
* Request HEAD of the file is going to write (ex: s3a://bucket/folder/file.ext) [In minio this is the step that fails]
* Request PUT of the file, to write it.
* Request POST to update some parameters.

But this is a bit strange, before using hadoop configuration I was using Flink configuration, and it worked great. Not sure what was the difference.

**Comment by harshavardhana** [comment] 2019-12-20 17:51
Please open a new issue @speeddragon with more details on our configuration etc.

Locking this issue to avoid any future updates on old issues.
