### ISSUE TITLE
Windows fails to execute minio in gateway mode

### ISSUE THREAD

**Issue by LukeDS-it** [minio/minio#5649] opened 2018-03-14 11:55 UTC
Trying a distributed setup between multiple dev machines, we ran into the impossibility of running minio as described here [https://github.com/minio/minio/blob/master/docs/gateway/nas.md](url).

First instance gets up and running smoothly. Subsequent instances fail to startup and just hangs.

If second+ instance is run from a linux machine, then we get a more evident error: `[2018-03-14T11:52:31.88573894Z] [FATAL] Unable to initialize gateway layer (read /mnt/minio-storage/.minio.sys/format.json: input/output error)`

I guess there is some kind of locking on the format.json file that takes place with windows machines.

Running minio with linux machines only works fine.

## Expected Behavior
Multiple instances should connect to the correct path and serve files

## Current Behavior
First instance runs fine, second+ instances fail to start

## Steps to Reproduce (for bugs)
1. Run minio.exe gateway nas on 1st windows machine
2. Run minio.exe gateway nas on 2nd windows machine
3. Try to run same command on a linux machine (still leaving 1st machine's minio running), following error occurs: [2018-03-14T11:52:31.88573894Z] [FATAL] Unable to initialize gateway layer (read /mnt/minio-storage/.minio.sys/format.json: input/output error)

## Your Environment
* Version used (`minio version`): 2018-03-12T21:25:28Z
* Environment name and version (e.g. nginx 1.9.1): NA
* Server type and version: NA
* Operating System and version (`uname -a`): Windows 7 SP1
* Link to your project: NA

**Comment by harshavardhana** [comment] 2018-03-14 16:41
Are you planning to run one nas gateway on Windows mount and another on Linux ?  This is because your NAS is rejecting locking requests across platforms. This is expected since windows implements mandatory filesystem locks and Linux doesn't. Also they are not inter operable.

So it  is expected that you run in a homogeneous environment with NAS gateway.

**Comment by LukeDS-it** [comment] 2018-03-14 16:55
Sorry, I might have explained myself poorly. The issue presents itself even with a homogeneous environment, the first thing I tried was running two nodes on two windows machines. The mixed environment was just another test I did because I supposed there was something wrong with windows.

So, if I understood correctly, there should be no issues in running two nodes in two windows machines, right? If so, how do you suggest to configure the environment to point at the NAS?

**Comment by harshavardhana** [comment] 2018-03-14 17:23
What is the backend NAS here on windows ? Does your backend NAS support NT filesystem locks ?

**Comment by harshavardhana** [comment] 2018-06-14 09:05
> What is the backend NAS here on windows ? Does your backend NAS support NT filesystem locks ?

Were you able to provide us this information @LukeDS-it? if we shall we close this issue?

**Comment by harshavardhana** [comment] 2018-08-30 01:10
This seems to be a regression @deekoder @poornas we have one more user reporting this issue.

**Comment by poornas** [comment] 2018-08-30 01:17
thanks @harshavardhana, will debug the issue

**Closed as completed** 2018-09-12 16:35 UTC
Labels: regression, fixed, priority: medium
