### ISSUE TITLE
Uploading "larger" files through the webui fails.

### ISSUE THREAD

**Issue by jtilander** [minio/minio#3852] opened 2017-03-04 23:15 UTC
Repo:

Follow the guide and bring up a docker-compose cluster e.g. this one:

https://raw.githubusercontent.com/minio/minio/master/docs/docker/docker-compose.yml

Go to the first node web interface. 

* Create a new bucket "test"
* Upload  file from your local drive that is "large", e.g. I've tried 500MB.

They will fail with the following error on the docker console:
```
minio1_1  | time="2017-03-04T23:03:18Z" level=error msg="Unexpected error, please report this issue at https://github.com/minio/minio/issues" cause="read tcp 172.20.0.2:9000->172.20.0.1:55674: i/o timeout" source="[web-handlers.go:962:toWebAPIError()]"
```

Verify that you can upload smaller files (less than 12MB) just fine:

Tested under docker with the above docker-compose file running on a mac.

**Comment by harshavardhana** [comment] 2017-03-04 23:28
Uploading files > 5 GB is not supported on browser please use command line tool. Also this looks weird we haven't seen with < 5GB this to occur for example 

Can you try uploading to https://play.minio.io:9000 and let us know if there is a same issue?.  From what it looks like browser stopped responding.

```
read tcp 172.20.0.2:9000->172.20.0.1:55674: i/o timeout
```

**Comment by harshavardhana** [comment] 2017-03-04 23:33
Also please follow the issue template so that the issue can be described better starting with versions of all the software in question to help us reproduce this issue.

 - minio version 
 - browser type (firefox, chrome etc) version name is a plus. 
 - docker version
 - macOS version

**Comment by jtilander** [comment] 2017-03-07 15:23
Uploading to play.minio.io worked fine. Is that also running in a distributed mode? 

I'm using MacOS 10.12.3, Safari 1.0.3, Docker 17.03.0-ce, build 60ccb22 and minio: don't know, I just pulled the latest from docker hub. The version tag says:

/usr/bin # /go/bin/minio --version
Minio version 0.0.0

**Comment by harshavardhana** [comment] 2017-03-07 23:47
> /usr/bin # /go/bin/minio --version
> Minio version 0.0.0

Play runs erasure coded mode with 8 local disks, IMHO i don't think so this is related to distributed minio.  We have continuous servers running everyday on 8-16 nodes. The issue from what i can think is related to macOS networking which is little flaky with docker. 

Can you do 'minio version' instead?  `--version` had a bug which is fixed in master.  Also your docker version looks strange? are you using the latest stable release? 

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by harshavardhana** [comment] 2017-03-13 04:26
Were you able to test with docker 1.13 ? @jtilander

**Comment by harshavardhana** [comment] 2017-03-30 06:38
Closing this issue as resolved for now @jtilander , please re-open if you observe the issue again.

**Closed as completed by harshavardhana** 2017-03-30 06:38 UTC
Labels: working as intended, community
