### ISSUE TITLE
Unexpected error encountered on windows startup

### ISSUE THREAD

**Issue by jiuker** [minio/minio#15397] opened 2022-07-24 13:53 UTC
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

I cloned the code from the main branch and ran it locally to start. When I visit http://127.0.0.1:9000.
The following error appears:
```
MinIO Object Storage Server
Copyright: 2015-0000 MinIO, Inc.
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Version: DEVELOPMENT.GOGET (go1.18 windows/amd64)

Status:         1 Online, 0 Offline.
API: http://192.168.1.150:9000  http://172.21.0.1:9000  http://127.0.0.1:9000               
RootUser: minioadmin 
RootPass: minioadmin 
Console: http://192.168.1.150:58829 http://172.21.0.1:58829 http://127.0.0.1:58829        
RootUser: minioadmin 
RootPass: minioadmin 

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc.exe alias set myminio http://192.168.1.150:9000 minioadmin minioadmin

Documentation: https://docs.min.io
___8server.exe: <DEBUG> dataUpdateTracker: cycle bloom filter: 69 -> 70
___8server.exe: <DEBUG> dataUpdateTracker: Saving: 2037433 bytes, Current idx: 70
looking up route for GET /api/v1/session
got a router for GET
got a router for DELETE
got a router for POST
got a router for PUT
found a route for GET /api/v1/session with 0 parameters
responding to GET /api/v1/session with produces: [application/json]
offers: [application/json]
[GET /api/v1/session] set response format "application/json" in context
[GET /api/v1/session] negotiated response format "application/json"
looking up route for GET /api/v1/login
got a router for POST
got a router for PUT
got a router for GET
got a router for DELETE
looking up route for GET /api/v1/check-version
got a router for DELETE
got a router for POST
got a router for PUT
got a router for GET
found a route for GET /api/v1/check-version with 0 parameters
found a route for GET /api/v1/login with 0 parameters
E: 2022/07/24 21:33:55 Get "": unsupported protocol scheme ""
%!(EXTRA *url.Error=Get "": unsupported protocol scheme "", *errors.errorString=unable to contact configured identity provider)
responding to GET /api/v1/login with produces: [application/json]
offers: [application/json]
[GET /api/v1/login] set response format "application/json" in context
[GET /api/v1/login] negotiated response format "application/json"
responding to GET /api/v1/check-version with produces: [application/json]
offers: [application/json]
[GET /api/v1/check-version] set response format "application/json" in context
[GET /api/v1/check-version] negotiated response format "application/json"
```

## Expected Behavior
I can access the front-end page normally

## Current Behavior
The pop-up tip reported the following error：
```
Get "": unsupported protocol scheme ""
```

## Possible Solution
`internal/config/identity/openid/openid.go:216`
```go
	openIDTargets, err := s.GetAvailableTargets(config.IdentityOpenIDSubSys)
	if err != nil {
		return c, err
	}
```
It looks like the associated data is empty.
Can it be obtained through environment variables? I don't know.
## Steps to Reproduce (for bugs)
1. clone master
2. git pull
3. set env _MINIO_SERVER_DEBUG=on;DEBUG=true
4. go run main.go server D:\minio\data
5. Access to front-end pages
## Context
I can't start the service locally, even if I follow the instructions in the README documentation.
## Your Environment

* Version used (`minio --version`):
```
[1mminio.exe version RELEASE.2022-07-24T01-54-52Z (commit-id=ce8548a1a203b247818f6913af5d885361d80c12)[0m
[34mRuntime:[0m[1m go1.18.4 windows/amd64[0m
[34mLicense:[0m[1m GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>[0m
[34mCopyright:[0m[1m 2015-2022 MinIO, Inc.[0m
```
* Server setup and configuration:
server D:\minio\data
* Operating System and version (`uname -a`):
windows

And I found a bug in the log
[console#2196](https://github.com/minio/console/pull/2196)

**Comment by harshavardhana** [comment] 2022-07-24 16:45
Duplicate of https://github.com/minio/console/issues/2197

**Closed as completed by harshavardhana** 2022-07-24 16:45 UTC
Labels: duplicate, community, fixed
