### ISSUE TITLE
mc admin info command times out on single-node instance 

### ISSUE THREAD

**Issue by bzakhar** [minio/minio#10460] opened 2020-09-10 16:11 UTC
## Expected Behavior
"mc admin info local" displays minio server status and attributes, similar to the following:

$ mc admin info local
●  localhost:9001
   Uptime: 1 month
   Version: 2020-05-06T23:23:25Z
   Network: 1/1 OK

350 KiB Used, 6 Buckets, 14 Objects

## Current Behavior
"mc admin info local" times out and returns the following error message:

$ mc admin info local
mc: <ERROR> Unable to get service status. Get "http://127.0.0.1:9001/minio/admin/v3/info": Connection closed by foreign host http://127.0.0.1:9001/minio/admin/v3/info. Retry again.

## Possible Solution
Either fix the API or immediately report it's unsupported in mode-server-fs mode similar to "mc admin top locks" if it is indeed no longer supported.

## Steps to Reproduce (for bugs)

1. start single instance of minio server with "--address :9001" command line 
2. use mc version RELEASE.2020-09-03T00-08-28Z and configure local alias for started instance.
3. try "mc admin info local". it will time out.
4. confirm that the server is operational by listing the root with "mc ls local/".

## Context
This command worked before, not being able to quickly verify server status or perform other administrative functions via mc 

## Regression
 Yes

No data, but it worked at least in version 2020-05-06T23:23:25Z

## Your Environment

* Version used (`minio --version`): RELEASE.2020-09-08T23-05-18Z
* Server setup and configuration: --address :9001 
* Operating System and version (`uname -a`): Linux a-server 4.14.35-1902.10.7.el7uek.x86_64 #2 SMP Fri Jan 31 12:23:16 PST 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2020-09-10 16:16
Duplicate of #10454

**Closed as completed by harshavardhana** 2020-09-10 16:16 UTC
Labels: duplicate, community, triage
