### ISSUE TITLE
Cluster with multiple zones fails to start

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#11421] opened 2021-02-03 09:28 UTC
I have Federation with multiple MinIO clusters. One of them has 2 zones, 3 nodes in each one.
I updated to the latest release: `RELEASE.2021-02-01T22-56-52Z` from `RELEASE.2020-10-18T21-54-12Z`.

Clusters with only 1 zone restart rapidly, in ~ 10 secondes.
However the cluster with 2 zones is blocked with this message since 14 hours:

```
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Verifying if {more than 3K} buckets are consistent across drives...
```

This cluster has:

20 GiB, 3k Buckets, 5k Objects, 24 drives

## Expected Behavior
A cluster with multiple zones should restart normally with the latest release: `RELEASE.2021-02-01T22-56-52Z`

## Current Behavior
Blocked with the following message since 14 hours:

```
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Verifying if {more than 3K} buckets are consistent across drives...
```

**Comment by ToLToL** [comment] 2021-02-03 14:11
Maybe it's related to https://github.com/minio/minio/pull/11423 ?

**Comment by zapto2600** [comment] 2021-02-03 15:32
I am seeing the same issue when we upgraded to `2021-02-01T22:56:52Z` This seems to only affect clusters that are setup as distributed.

**Comment by harshavardhana** [comment] 2021-02-03 16:39
@ToLToL can you paste your server command line?

**Comment by ToLToL** [comment] 2021-02-03 16:42
@harshavardhana

`minio server --certs-dir=/certs https://minio{0...2}.xxx.xxx.xxx/mnt/data{0...3} https://minio{3...5}.xxx.xxx.xxx/mnt/data{0...3}`
Worked fine with `RELEASE.2020-10-18T21-54-12Z`

**Comment by harshavardhana** [comment] 2021-02-03 16:45
> @harshavardhana
> 
> `minio server --certs-dir=/certs https://minio{0...2}.xxx.xxx.xxx/mnt/data{0...3} https://minio{3...5}.xxx.xxx.xxx/mnt/data{0...3}`
> Worked fine with `RELEASE.2020-10-18T21-54-12Z`

Did you upgrade all servers together? I.e all of them were upgraded?

**Comment by ToLToL** [comment] 2021-02-03 16:46
@harshavardhana yes

**Comment by zapto2600** [comment] 2021-02-03 16:49
> @harshavardhana yes

Just to add some info here. Our file looks very much like this and we upgraded all servers at the same time.

**Comment by ToLToL** [comment] 2021-02-03 16:50
I also upgraded all servers together for clusters with 1 zone and it worked perfectly.

**Comment by harshavardhana** [comment] 2021-02-03 16:52
I can't seem to reproduce the problem at all.

**Comment by harshavardhana** [comment] 2021-02-03 16:57
> Clusters with only 1 zone restart rapidly, in ~ 10 secondes.

When you say this do you have any logs to share ?

**Comment by ToLToL** [comment] 2021-02-03 17:07
It takes ~ 10 secondes to restart this cluster (1 zone):

```
●  1.xxx.xxx.xxx:9000
   Uptime: 19 hours
   Version: 2021-02-01T22:56:52Z
   Network: 3/3 OK
   Drives: 4/4 OK

●  2.xxx.xxx.xxx:9000
   Uptime: 19 hours
   Version: 2021-02-01T22:56:52Z
   Network: 3/3 OK
   Drives: 4/4 OK

●  0.xxx.xxx.xxx:9000
   Uptime: 19 hours
   Version: 2021-02-01T22:56:52Z
   Network: 3/3 OK
   Drives: 4/4 OK
```

mc admin info of the cluster with 2 zones:

```
●  1.xxx.xxx.xxx:9000
   Uptime: 3 hours
   Version: 2021-02-01T22:56:52Z
   Network: 2/6 OK
   Drives: 4/4 OK

●  2.xxx.xxx.xxx:9000
   Uptime: 3 hours
   Version: 2021-02-01T22:56:52Z
   Network: 2/6 OK
   Drives: 4/4 OK

●  3.xxx.xxx.xxx:9000
   Uptime: 3 hours
   Version: 2021-02-01T22:56:52Z
   Network: 2/6 OK
   Drives: 4/4 OK

●  4.xxx.xxx.xxx:9000
   Uptime: 3 hours
   Version: 2021-02-01T22:56:52Z
   Network: 1/6 OK
   Drives: 4/4 OK

●  5.xxx.xxx.xxx:9000
   Uptime: 3 hours
   Version: 2021-02-01T22:56:52Z
   Network: 2/6 OK
   Drives: 4/4 OK

●  0.xxx.xxx.xxx:9000
   Uptime: 3 hours
   Version: 2021-02-01T22:56:52Z
   Network: 2/6 OK
   Drives: 4/4 OK
```

**Comment by harshavardhana** [comment] 2021-02-03 17:16
yes but if it restarts there will be something on the console @ToLToL I need to be able to see that. Otherwise, it's hard for me to see how this is possible. 

There must be a reason why it's specifically restarting.

**Comment by ToLToL** [comment] 2021-02-03 17:24
Server that restarts:

```
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Verifying if {6xx} buckets are consistent across drives...
All MinIO sub-systems initialized successfully
Status:         12 Online, 0 Offline.
Endpoint: https://172.31.20.18:9000  https://172.17.0.1:9000  https://127.0.0.1:9000

Browser Access:
   https://172.31.20.18:9000  https://172.17.0.1:9000  https://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Waiting for all MinIO IAM sub-system to be initialized.. lock acquired
```

Server that doesn't restart:

```
API: SYSTEM()
Time: 17:21:19 UTC 02/03/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: Operation timed out (cmd.OperationTimedOut)
       1: cmd/data-crawler.go:135:cmd.runDataCrawler()
2021-02-03 17:21:19.662298 I | http2: server connection error from 172.31.39.208:47084: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.662557 I | http2: server connection error from 172.31.39.208:47084: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.662723 I | http2: server connection error from 172.31.39.208:47084: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.662818 I | http2: server connection error from 172.31.39.208:47084: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.662935 I | http2: server connection error from 172.31.39.208:47084: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.675022 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR

API: SYSTEM()
Time: 17:21:19 UTC 02/03/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       3: cmd/erasure-server-pool.go:1164:cmd.(*erasureServerPools).ListBuckets()
       2: cmd/erasure-server-pool.go:368:cmd.(*erasureServerPools).CrawlAndGetDataUsage()
       1: cmd/data-crawler.go:119:cmd.runDataCrawler()

API: SYSTEM()
Time: 17:21:19 UTC 02/03/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       3: cmd/erasure-server-pool.go:1164:cmd.(*erasureServerPools).ListBuckets()
       2: cmd/erasure-server-pool.go:368:cmd.(*erasureServerPools).CrawlAndGetDataUsage()
       1: cmd/data-crawler.go:119:cmd.runDataCrawler()

API: SYSTEM()
Time: 17:21:19 UTC 02/03/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: Read failed. Insufficient number of disks online (*errors.errorString)
       1: cmd/data-crawler.go:121:cmd.runDataCrawler()
2021-02-03 17:21:19.681998 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.682372 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.682598 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.682811 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.682951 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.683051 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.683607 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.683774 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.683952 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.684082 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.684306 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.684472 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.684730 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.684873 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.684994 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.686265 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.688629 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.695101 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.695341 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.695641 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.695863 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.698276 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.698480 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.698680 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.698771 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.698998 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.699176 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.699770 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.700010 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.700100 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.700175 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.712778 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
2021-02-03 17:21:19.713966 I | http2: server connection error from 172.31.39.208:52354: connection error: PROTOCOL_ERROR
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Verifying if {3k} buckets are consistent across drives...
```

**Comment by harshavardhana** [comment] 2021-02-03 17:25
@ToLToL that looks strange do you see some memory usage? and some restrictions on memory? looks like this is a containerized instance?

**Comment by ToLToL** [comment] 2021-02-03 17:25
Yes, this is a containerized instance.

**Comment by ToLToL** [comment] 2021-02-03 17:31
History of `docker stats minio`, with CPU usage at `158.93%` at its peak 😂:

```
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     79.77%    567.5MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.53GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     79.77%    567.5MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.53GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     158.93%   567.6MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.53GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     158.93%   567.6MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.53GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     115.46%   567.7MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.53GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     115.46%   567.7MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.53GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     83.99%    567.6MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.53GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     83.99%    567.6MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.53GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     82.53%    567.8MiB / 3.786GiB   14.65%    0B / 0B   25.2MB / 2.54GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     82.53%    567.8MiB / 3.786GiB   14.65%    0B / 0B   25.2MB / 2.54GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     97.60%    567.8MiB / 3.786GiB   14.65%    0B / 0B   25.2MB / 2.54GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     97.60%    567.8MiB / 3.786GiB   14.65%    0B / 0B   25.2MB / 2.54GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     97.28%    567.8MiB / 3.786GiB   14.65%    0B / 0B   25.2MB / 2.54GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     97.28%    567.8MiB / 3.786GiB   14.65%    0B / 0B   25.2MB / 2.54GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     108.80%   567.7MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.55GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     108.80%   567.7MiB / 3.786GiB   14.64%    0B / 0B   25.2MB / 2.55GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     107.86%   567.8MiB / 3.786GiB   14.65%    0B / 0B   25.2MB / 2.55GB   17
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
5a74a81c40be   minio     107.86%   567.8MiB / 3.786GiB   14.65%    0B / 0B   25.2MB / 2.55GB   17
```

**Comment by ToLToL** [comment] 2021-02-03 17:35
So I should get more CPU?

**Comment by harshavardhana** [comment] 2021-02-03 17:36
> @ToLToL that looks strange do you see some memory usage? and some restrictions on memory? looks like this is a containerized instance?

I suspect there is some other issue here @ToLToL on baremetal I don't see this problem

**Comment by ToLToL** [comment] 2021-02-03 18:56
@harshavardhana 

The CPU usage with 1 zone is very low:

```
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     31.73%    207.1MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT     MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     31.73%    207.1MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     13.26%    207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     13.26%    207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.79%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.79%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.38%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.38%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     1.91%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     1.91%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     2.30%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     2.30%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.40%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.40%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.40%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.40%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.72%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.72%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.41%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.41%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O         PIDS
787a494162f6   minio     0.74%     207MiB / 3.786GiB   5.34%     0B / 0B   27.5MB / 8.06GB   20
```

**Comment by harshavardhana** [comment] 2021-02-03 18:58
I suspect that you have some limit on the containers that makes them restart @ToLToL can you disable `container` restart policy? and let it die?  so we can see what the error might be?

**Comment by ToLToL** [comment] 2021-02-03 20:32
I changed the EC2 instance type to get more CPU and servers restart after ~ 30 secondes.
I have another problem now, the IP addresses changed and have this error for each bucket:

```
API: SYSTEM()
Time: 20:29:07 UTC 02/03/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: Unable to add bucket DNS entry for bucket {bucket_name}, an entry exists for the same bucket by a different tenant. This local bucket will be ignored. Bucket names are globally unique in federated deployments. Use path style requests on following addresses '[{new_ip_addresses}]' to access this bucket. (*errors.errorString)
       1: cmd/bucket-handlers.go:143:cmd.initFederatorBackend()
```

**Comment by harshavardhana** [comment] 2021-02-03 20:37
> API: SYSTEM()
> Time: 20:29:07 UTC 02/03/2021
> DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
> Error: Unable to add bucket DNS entry for bucket {bucket_name}, an entry exists for the same bucket by a different tenant. This local bucket will be ignored. Bucket names are globally unique in federated deployments. Use path style requests on following addresses '[{new_ip_addresses}]' to access this bucket. (*errors.errorString)
>        1: cmd/bucket-handlers.go:143:cmd.initFederatorBackend()

yes for that you need to make sure to provide MINIO_PUBLIC_IPS instead of relying on AWS EC2  https://github.com/minio/minio/tree/master/docs/federation/lookup#minio_public_ips

**Comment by harshavardhana** [comment] 2021-02-03 20:38
NOTE: you can use DNS names that point to the same ec2 instance or elastic IPs - I don't know why you are using federation support along with zones based expansion. 

If this is a production setup you should really consider getting a subscription https://min.io/pricing - looks like you have architectured this incorrectly.

**Comment by harshavardhana** [comment] 2021-02-03 20:40
So the original issue is resolved, I don't think zones expansion itself is the issue here - it is simply that you have constrained the system that docker ends up restarting them.

**Comment by harshavardhana** [comment] 2021-02-04 03:09
> I changed the EC2 instance type to get more CPU and servers restart after ~ 30 secondes.

@ToLToL the restart doesn't look correct as I ran multiple such zones locally and there are no problems. The only reason I can think of is there is something suspicious on the cluster that is prematurely restarting the service. 

As I suggested to help me get to the bottom of this you should avoid `docker's ` or pods default restart policy - instead let it fail and then we can see the reason why it failed.

**Comment by harshavardhana** [comment] 2021-02-04 03:11
Check if you have some weird health checks that are too aggressive and restarting the pods - if there are some of these checks you should remove them.

**Comment by harshavardhana** [comment] 2021-02-04 03:55
@ToLToL also please remove the federation settings, and try this again.

**Comment by ToLToL** [comment] 2021-02-04 10:05
Thanks for your reply.

Docker container's restart policy is already set to `false` and I don't have any aggressive health checks.

Please note that I restart the containers with `mc admin service restart my_cluster`, it's not containers that restart themselves due to an error.
They run on EC2 instances and I expanded a cluster with a zone for testing purposes.


> I changed the EC2 instance type to get more CPU and servers restart after ~ 30 secondes.
> I have another problem now, the IP addresses changed and have this error for each bucket:
> 
> ```
> API: SYSTEM()
> Time: 20:29:07 UTC 02/03/2021
> DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
> Error: Unable to add bucket DNS entry for bucket {bucket_name}, an entry exists for the same bucket by a different tenant. This local bucket will be ignored. Bucket names are globally unique in federated deployments. Use path style requests on following addresses '[{new_ip_addresses}]' to access this bucket. (*errors.errorString)
>        1: cmd/bucket-handlers.go:143:cmd.initFederatorBackend()
> ```

I fixed this error and now I have this new one for each bucket when I restart:

```
API: SYSTEM(bucket={bucket_name})
Time: 09:37:35 UTC 02/04/2021
DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
Error: Operation timed out (cmd.OperationTimedOut)
       1: cmd/notification.go:702:cmd.(*NotificationSys).load()

...
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
...
Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
Waiting for all MinIO sub-systems to be initialized.. lock acquired
Verifying if {3k} buckets are consistent across drives...
```

**Comment by harshavardhana** [comment] 2021-02-04 10:14
> API: SYSTEM(bucket={bucket_name})
> Time: 09:37:35 UTC 02/04/2021
> DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
> Error: Operation timed out (cmd.OperationTimedOut)
>        1: cmd/notification.go:702:cmd.(*NotificationSys).load()
> 
> ...
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> ...
> Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> Waiting for all MinIO sub-systems to be initialized.. lock acquired
> Verifying if {3k} buckets are consistent across drives...

are you zones like across DC? @ToLToL

**Comment by harshavardhana** [comment] 2021-02-04 10:16
> Please note that I restart the containers with `mc admin service restart my_cluster`, it's not containers that restart themselves due to an error.

But why are you restarting them? what is the purpose?

**Comment by ToLToL** [comment] 2021-02-04 10:20
To upgrade to `RELEASE.2021-02-01T22-56-52Z` but servers didn't start, blocked with this message:

`Verifying if {more than 3K} buckets are consistent across drives...`

BTW, there's always one server that succeeds in starting.

I waited for 14 hours the first time and I continue to restart them to see if it can change sth.

**Comment by ToLToL** [comment] 2021-02-04 10:26
> > API: SYSTEM(bucket={bucket_name})
> > Time: 09:37:35 UTC 02/04/2021
> > DeploymentID: a4d7c650-dcf6-4134-9f60-455ee6f8cf2c
> > Error: Operation timed out (cmd.OperationTimedOut)
> > 1: cmd/notification.go:702:cmd.(*NotificationSys).load()
> > ...
> > Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> > ...
> > Waiting for all MinIO sub-systems to be initialized.. trying to acquire lock
> > Waiting for all MinIO sub-systems to be initialized.. lock acquired
> > Verifying if {3k} buckets are consistent across drives...
> 
> are you zones like across DC? @ToLToL

Yes, they're within the same availability zone (EC2)

**Comment by harshavardhana** [comment] 2021-02-04 10:28
> Yes, they're within the same availability zone (EC2)

I can't fathom how this is happening though unless you can share some more information such as network trace - all my tests seem to work fine.  I hope it is not related to the number of buckets you have. 

Can you share all the environment settings that you have?

**Comment by harshavardhana** [comment] 2021-02-04 10:31
Can you try running let's say the version from 2021-01-016?

**Comment by ToLToL** [comment] 2021-02-04 10:35
> Can you try running let's say the version from 2021-01-016?

Yes, on it.

**Comment by ToLToL** [comment] 2021-02-04 11:15
@harshavardhana  Still `Verifying if {3k} buckets are consistent across drives..` with `2021-01-016`:

```
●  minio1.xxx:9000                           Zone 1
   Uptime: 22 minutes
   Version: 2021-01-16T02:19:44Z
   Network: 2/6 OK
   Drives: 4/4 OK

●  minio2.xxx:9000                           Zone 1 👈 This server is up
   Uptime: 22 minutes
   Version: 2021-01-16T02:19:44Z
   Network: 1/6 OK
   Drives: 4/4 OK

●  minio3.xxx:9000                           Zone 2
   Uptime: 22 minutes
   Version: 2021-01-16T02:19:44Z
   Network: 2/6 OK
   Drives: 4/4 OK

●  minio4.xxx:9000                           Zone 2
   Uptime: 22 minutes
   Version: 2021-01-16T02:19:44Z
   Network: 2/6 OK
   Drives: 4/4 OK

●  minio5.xxx:9000                           Zone 2
   Uptime: 22 minutes
   Version: 2021-01-16T02:19:44Z
   Network: 2/6 OK
   Drives: 4/4 OK

●  minio0.xxx:9000                           Zone 1
   Uptime: 22 minutes
   Version: 2021-01-16T02:19:44Z
   Network: 2/6 OK
   Drives: 4/4 OK

20 GiB Used, 3k Buckets, 5k Objects
24 drives online, 0 drives offline
```

**Comment by harshavardhana** [comment] 2021-02-04 11:17
what are your environment settings? @ToLToL

**Comment by ToLToL** [comment] 2021-02-04 11:20
Do you want a docker inspect?

**Comment by ToLToL** [comment] 2021-02-04 13:24
@harshavardhana 

I finally succeeded in restarting the cluster with the latest release.

When a server was logging `Verifying if {more than 3K} buckets are consistent across drives...` for more than ~ 10 minutes, I restarted it with `docker restart minio` and it was up.
Very strange though ...

**Comment by ToLToL** [comment] 2021-02-04 13:31
Maybe it's due to the large amount of buckets / objects?

Before this I downgraded to `RELEASE.2020-10-18T21-54-12Z` and didn't have this problem.

**Comment by harshavardhana** [comment] 2021-02-04 22:30
FWIW https://github.com/minio/minio/pull/11449 this might help, not sure if it will.

**Comment by ToLToL** [comment] 2021-02-04 22:32
Will test in the next release, thanks 😊

**Comment by harshavardhana** [comment] 2021-02-05 23:48
This issue is fixed with #11446, not #11449

**Comment by harshavardhana** [comment] 2021-02-05 23:49
More improvements here #11468

**Closed as completed by harshavardhana** 2021-02-05 23:48 UTC
Labels: community, fixed

**Comment by ToLToL** [comment] 2021-02-07 09:10
@harshavardhana 

Working fine with `RELEASE.2021-02-07T01-31-02Z`,  it takes less than 30 secondes.
Thanks 👍🏻.

**Comment by harshavardhana** [comment] 2021-02-07 18:58
> Working fine with `RELEASE.2021-02-07T01-31-02Z`, it takes less than 30 secondes.
> Thanks 👍🏻.

Awesome! @ToLToL
