### ISSUE TITLE
Marker-Delete replication stop working on the latest release RELEASE.2021-02-01T22-56-52Z

### ISSUE THREAD

**Issue by pavel-z1** [minio/minio#11454] opened 2021-02-05 09:45 UTC
After update minio from release RELEASE.2021-01-30T00-20-58Z to RELEASE.2021-02-01T22-56-52Z stopped working Delete-Marker replication feature.

## Expected Behaviour on the replicated bucket after file deletion
```
# mc stat local/test-bucket/file.xml
mc: <ERROR> Unable to stat `local/test-bucket/file.xml`. Object does not exist
```

## Current Behaviour on the replicated bucket after file deletion
```
# mc stat local/test-bucket/file.xml
Name      : file.xml
Date      : 2021-02-05 09:57:34 CET
Size      : 32 KiB
ETag      : 00963f092bee5c09d36fde60fb0db0d5
VersionID : 112d08bd-de33-499e-a4c1-f4feb5cb8453
Type      : file
Metadata  :
  Content-Type: text/xml
Replication Status: REPLICA
```

## Possible Solution
As current workaround I've downgraded minio back to the RELEASE.2021-01-30T00-20-58Z

## Steps to Reproduce (for bugs)
1. Configure Replication between buckets with enabled Delete-Marker replication
2. Upload file, then delete file.
3. Check file on replicated bucket

## Regression
Is this issue a regression

## Your Environment
MinIO RELEASE.2021-02-01T22-56-52Z

**Comment by Sug2077** [comment] 2021-02-05 11:23
#11440 #11451

**Comment by harshavardhana** [comment] 2021-02-05 17:50
Duplicate of #11440

**Closed as completed by harshavardhana** 2021-02-05 17:50 UTC
Labels: duplicate, community
