### ISSUE TITLE
modifying existing blobs

### ISSUE THREAD

**Issue by vtolstov** [minio/minio#150] opened 2015-02-11 06:38 UTC
Does it possible to modify exiting blob that already stored in server?

**Comment by harshavardhana** [comment] 2015-02-11 06:44
> Does it possible to modify exiting blob that already stored in server?

No it won't be possible, every object uploaded is immutable by design.  But multi part upload will be supported so that large blobs can be added in batches.  But once created object is written to stone only GET is allowed.

**Comment by domsj** [comment] 2015-02-11 08:58
Is overwriting an object possible?

**Comment by harshavardhana** [comment] 2015-02-12 06:10
> Is overwriting an object possible?

No it won't be possible, any given object is immutable once it is written to disk.   By design we choose immutability to keep data reliable and safe. 

Subsequent changes in any uploaded object can be captured as new object, but that is left to client side tooling. https://github.com/minio-io/mc (Minio client) which is currently being written will help such scenarios for capturing subsequent object deltas.

**Comment by harshavardhana** [comment] 2015-10-16 18:47
Moving to filesystem backend we have unlink support now so closing this bug - erasure coded code has moved from @minio to @minio-xl which will be immutable.

**Closed as completed by harshavardhana** 2015-10-16 18:47 UTC
Labels: working as intended
