### ISSUE TITLE
object not available after upload with asynchronous replication enabled

### ISSUE THREAD

**Issue by hkirov** [minio/minio#12573] opened 2021-06-24 11:59 UTC
## Expected Behavior

Object to be accessible from main site immediately after upload. Secondary site to return 404 until the object gets replicated there. 

## Current Behavior

Object is not accessible in main site after upload until it gets replicated. Secondary site returns 404 for the object until it gets replicated there.

## Steps to Reproduce (for bugs)

1. create buckets with asynchronous replication:
2. mc mb site1/test
3. mc mb site2/test
4. mc version enable site1/test
5. mc version enable site2/test
6. mc admin bucket remote add site1/test https://user:pass@site2.somewere.net:9000/test --service "replication"
7. mc replicate add site1/test --remote-bucket test --arn 'arn:minio:replication::xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:test' --replicate "delete,delete-marker"
8. upload large file. Size is irrelevant just big enough to have a time to test replication
9. mc cp 2Gfile.bin site1/test/
10. immediately copy back file after upload
11. mc cp site1/test/2Gfile.bin bigfile1.bin #this hangs until object gets replicated
12. mc cp site2/test/2Gfile.bin bigfile2.bin #this one returns "mc: <ERROR> Unable to validate source `site2/test/2Gfile.bin`." which is good

## Your Environment

* Version used (`minio --version`): Version: 2021-06-17T00:10:46Z
* Server setup and configuration: two baremetal clusters with 5 nodes each
* Operating System and version (`uname -a`): Linux tafl-serv1 5.4.0-74-generic 83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment] 2021-06-24 14:16
@hkirov The object is only ready when your upload call returns. So you should never rely on it being available before that.

However, @poornas it seems like `replicateObject` is grabbing a write lock while it is replicating.

I assume you use this since you eventually want to update the metadata. However, since the transfer can be lengthy grabbing a read lock, transferring, and then grab a write lock, re-reading the metadata would be nicer. At least for bigger objects.

**Comment by hkirov** [comment] 2021-06-24 14:32
@klauspost The object is not available after upload call returns. I do not expect it to be available before that. mc cp finished without error. After that for some time all attempts to access file on main site hangs (mc stat, mc cp, ..). I can see that there is WRITE lock on object during this time.

This is after 100GB file upload:
ico@anduril:/tmp/minio$ mc admin top locks nl
Time                  Type    Resource
7 hours               WRITE   .minio.sys/runDataScanner.lock
3 minutes             WRITE   storage/cont_farm2g/testFile.eu

**Comment by harshavardhana** [comment] 2021-06-25 01:27
This is expected behavior as of now @hkirov we are changing the locking semantics slightly to cater for this requirement as well.

**Closed as completed** 2021-06-29 06:58 UTC
Labels: community, fixed, priority: high

**Comment by hkirov** [comment] 2021-06-29 07:15
Thanks
