### ISSUE TITLE
[faq] minio gateway s3 with IAM role (no access/secret key) not working

### ISSUE THREAD

**Issue by tooptoop4** [minio/minio#9370] opened 2020-04-16 16:17 UTC
minio gateway s3 command does not work unless i specify access/secret key?

## Expected Behavior
The command should work based on IAM role/instance profile credentials, the ec2 can already access s3 using aws cli without having access/secret key defined anywhere (not in profile/env variables/.credentials - not present at all!)

## Current Behavior
error saying key is invalid

## Possible Solution
?

## Steps to Reproduce (for bugs)
export MINIO_REGION=eu-west-1
./minio gateway s3 --address :8787 https://s3.eu-west-1.amazonaws.com

## Context
I just got https://github.com/minio/minio/issues/7765 working. Was hoping to not have to deal with rotating keys with IAM User, as my EC2 already has IAM role to S3.

## Regression
No

## Your Environment

* Version used (`minio version`): 2020-04-15T19:42:18Z
* Server type and version: AmazonLinux1
* Operating System and version (`uname -a`): 4.14.171-105.231.amzn1.x86_64 #1 SMP Thu Feb 27 23:49:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by kannappanr** [comment] 2020-04-17 10:48
I am not entirely sure about this. Will check internally and get back to you on this

**Comment by poornas** [comment] 2020-04-17 18:07
looks like you should be setting [AWS_CONTAINER_CREDENTIALS_FULL_URI ](https://github.com/minio/minio-go/blob/master/pkg/credentials/iam_aws.go#L116) env. var since your endpoint is in eu region and may not be using the default metadata service url.

**Comment by tooptoop4** [comment] 2020-04-17 20:04
what should I set it to?

**Comment by harshavardhana** [comment] 2020-04-20 23:18
> what should I set it to?

Your endpoint region https://github.com/minio/minio-go/commit/d18cd1c3fde63effb2eb789120abdc73da4a5610 @tooptoop4

**Comment by jdheyburn** [comment] 2020-04-21 14:40
I believe I have the same issue. I have minio running in Fargate and yet I have to duplicate the policies for both IAM User Keys and the ECS task role. 

My Fargate instance is in eu-west-1, am I right in thinking we can set AWS_CONTAINER_CREDENTIALS_FULL_URI to `s3.eu-west-1.amazonaws.com` and it will work without the need for IAM keys?

Will IAM keys still be needed for when etcd backend is used?

**Comment by harshavardhana** [comment] 2020-04-21 14:52
> I believe I have the same issue. I have minio running in Fargate and yet I have to duplicate the policies for both IAM User Keys and the ECS task role.
> 
> My Fargate instance is in eu-west-1, am I right in thinking we can set AWS_CONTAINER_CREDENTIALS_FULL_URI to `s3.eu-west-1.amazonaws.com` and it will work without the need for IAM keys?
>
Not sure what you mean?

> Will IAM keys still be needed for when etcd backend is used?

This for backend communication it has nothing to do with your use of etcd on the gateway side..

**Comment by tooptoop4** [comment] 2020-04-22 21:29
@harshavardhana AWS_CONTAINER_CREDENTIALS_FULL_URI=s3.eu-west-1.amazonaws.com does not fix it. Note I am using plain EC2 not ECS

**Comment by poornas** [comment] 2020-04-23 00:50
@tooptoop4 , thanks for the clarification - have you tried starting the gateway without the endpoint? It [seems](https://github.com/minio/minio-go/blob/master/pkg/credentials/iam_aws.go#L172) that the default IAM role endpoint would be used if  you use `export MINIO_REGION=eu-west-1; ./minio gateway s3 --address :8787` 

Also, you should be able to curl your role name from this metadata endpoint  - replace s3access with your rolename 
 `$ curl http://169.254.169.254/latest/meta-data/iam/security-credentials/s3access`

**Comment by squarek** [comment] 2020-04-23 01:35
This problem appears to be similar to the one I am facing. I tried this from us-west-1 and I got “invalid credentials” when running a binary from EC2.

**Comment by tooptoop4** [comment] 2020-04-23 06:11
same error @poornas

**Comment by tkadarla** [comment] 2020-05-07 04:14
Any update on this issue?

**Comment by harshavardhana** [comment] 2020-05-07 04:40
> Any update on this issue?

Lower priority for us right now, will get to this in future. Feel free to send a PR if you must to get it fixed quickly.

**Comment by tooptoop4** [comment] 2020-06-15 01:35
@harshavardhana i would like to have a 'go' at fixing this. can you suggest any pointers like which file the changes should go into?

**Comment by harshavardhana** [comment] 2020-06-15 01:37
> @harshavardhana i would like to have a 'go' at fixing this. can you suggest any pointers like which file the changes should go into?

You may have to do the necessary digging yourself, mostly in minio-go repository.

Before one dwells into that please test the functionality in latest release..

**Comment by tooptoop4** [comment] 2020-06-15 06:13
latest release still has issue

**Comment by harshavardhana** [comment] 2020-06-15 06:28
> latest release still has issue

Feel free to send a PR

**Comment by bensodenkamp** [comment] 2020-06-19 08:12
It was an easy fix. The general 'gateway' case was demanding environment variables that the S3 implementation didn't need. @tooptoop4, it would be easy enough for you to make a custom build if you really need it..

**Comment by bensodenkamp** [comment] 2020-06-20 13:27
@tooptoop4, I'm afraid you and I have had a fundamental misunderstanding about the purpose of the MINIO_ACCESS_KEY and MINIO_SECRET_KEY environment variables. The main purpose of those variables is to set up creds for authenticating into MINIO, and for minio to use under the hood to encrypt/decrypt config values.
They are also _one_ of the places that minio looks for S3 creds when acting as an S3 gateway, however, if you have a role set up for S3 access, and have added the EC2 instance to that role, MINIO will check for S3 creds there too.
You can make up whatever you want the MINIO_ACCESS_KEY and MINIO_SECRET_KEY to be as long as they are long enough, so literally:

export MINIO_ACCESS_KEY=foobarbazqux
export MINIO_SECRET_KEY=123456789

Will get the server started, and as long as you have the roll set up, minio will be able to talk to S3.
@poornas, @harshavardhana, correct me if I'm wrong.

**Comment by harshavardhana** [comment] 2020-06-20 13:31
> @tooptoop4, I'm afraid you and I have had a fundamental misunderstanding about the purpose of the MINIO_ACCESS_KEY and MINIO_SECRET_KEY environment variables. The main purpose of those variables is to set up creds for authenticating into MINIO, and for minio to use under the hood to encrypt/decrypt config values.
> They are also _one_ of the places that minio looks for S3 creds when acting as an S3 gateway, however, if you have a role set up for S3 access, and have added the EC2 instance to that role, MINIO will check for S3 creds there too.
> You can make up whatever you want the MINIO_ACCESS_KEY and MINIO_SECRET_KEY to be as long as they are long enough, so literally:
> 
> export MINIO_ACCESS_KEY=foobarbazqux
> export MINIO_SECRET_KEY=123456789
> 
> Will get the server started, and as long as you have the roll set up, minio will be able to talk to S3.
> @poornas, @harshavardhana, correct me if I'm wrong.

Yes that is the expected behavior.

**Comment by tooptoop4** [comment] 2020-06-20 20:12
maybe docs need improvement?

**Comment by harshavardhana** [comment] 2020-06-20 20:21
> maybe docs need improvement?

Feel free to send an update to the docs..

**Comment by bensodenkamp** [comment] 2020-06-21 18:58
@tooptoop4, docs updated. Good to close?

**Comment by harshavardhana** [comment] 2020-06-21 19:39
> @tooptoop4, docs updated. Good to close?

Closing, docs are updated. Please open new issues if there are further problems

**Closed as completed by harshavardhana** 2020-06-21 19:39 UTC
Labels: working as intended, priority: low, community
