### ISSUE TITLE
mc ls listing differences

### ISSUE THREAD

**Issue by Iguana9999phil** [minio/minio#11254] opened 2021-01-09 04:23 UTC
Debugging an issue with rclone mount not showing the correct directory counts. Testing with mc gives similar results.
Directory contains 13067 directories, running mc ls on it in 2s interval gives me this:
```
:~$ mc ls minio/media/Movies | wc -l
7901
:~$ mc ls minio/media/Movies | wc -l
7926
:~$ mc ls minio/media/Movies | wc -l
13067
:~$ mc ls minio/media/Movies | wc -l
13067
:~$ mc ls minio/media/Movies | wc -l
2632
```
## Expected Behavior
Show the correct directory count.

## Current Behavior
No showing the correct directory count.
## Possible Solution
No idea
## Steps to Reproduce (for bugs)
Unknown, this is happening on 2021-01-05T05:22:38Z, got another cluster running an older release which doesn't have the issue at the moment. 

## Context
Debugging an issue with rclone related to https://github.com/minio/minio/pull/11136, updated minio to the 2021-01-05T05:22:38Z and now seeing this issue. 

To rule out rclone I testing with mc and while before it doesn't show this issue, it does now on 2021-01-05T05:22:38Z

## Regression
Possibly

## Your Environment

* Version used (`minio --version`): 2021-01-05T05:22:38Z
* Server setup and configuration: 8x SX132 hetzner
* Operating System and version (`uname -a`): Debian 10 64bit 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2021-01-09 04:26
> Unknown, this is happening on 2021-01-05T05:22:38Z, got another cluster running an older release which doesn't have the issue at the moment.

You should enable `MINIO_API_LIST_QUORUM=strict` @Iguana9999phil  - it looks like you have drives that are inconsistent with their namespace.

**Comment by Iguana9999phil** [comment] 2021-01-09 04:36
@harshavardhana Can I do that while it's running using MC or do I need to add it as an ENV variable on all nodes?

**Comment by harshavardhana** [comment] 2021-01-09 04:41
> @harshavardhana Can I do that while it's running using MC or do I need to add it as an ENV variable on all nodes?

you can use `mc admin config set alias/ api list_quorum=strict`  - can be applied without restarting the server.

**Comment by Iguana9999phil** [comment] 2021-01-09 04:58
Thanks, tried it but still the same, looking at some other threads related to list_quorum and if I understand correctly the list cache gets invalidated / updated when data is written to the bucket, while testing I had mc mirror running, could that be the reason? I've disabled the mc mirrors for now and it looks consistent (or at least better) than while mc mirror was running. Does it mean every time something gets written to the cluster I'm going to see this?

**Comment by harshavardhana** [comment] 2021-01-09 04:59
> Thanks, tried it but still the same, looking at some other threads related to list_quorum and if I understand correctly the list cache gets invalidated / updated when data is written to the bucket, while testing I had mc mirror running, could that be the reason? I've disabled the mc mirrors for now and it looks consistent (or at least better) than while mc mirror was running. Does it mean every time something gets written to the cluster I'm going to see this?

Try restarting the server after the setting has been done @Iguana9999phil

**Comment by Iguana9999phil** [comment] 2021-01-09 05:06
Restarted, verified it's on list_quorum=strict and still the same.

**Comment by harshavardhana** [comment] 2021-01-09 05:08
> Restarted, verified it's on list_quorum=strict and still the same.

Then you have verify inconsistent namespace that cannot be fixed, you should try `mc admin heal -r --remove` to heal the content first.

**Comment by Iguana9999phil** [comment] 2021-01-09 05:46
Ok will try that first.
For my info what are the differences between the different list_quorum= options?

**Comment by harshavardhana** [comment] 2021-01-09 06:30
> For my info what are the differences between the different list_quorum= options?

The number of disks used for listing @Iguana9999phil default is '3', quorum means all disks and returns list that satisfies quorum. Most probably you have some oldish cache that is interfering here. 

So the best way is set the `quorum` then purge the content at this location on all drives `rm -rf /<backend_drive>/.minio.sys/buckets/<bucketname>/.metacache` 

and then restart the server using `mc admin service restart` - once done if you do `mc ls` it should always show the correct content. 

The cache will be rebuilt anyways.

**Comment by Iguana9999phil** [comment] 2021-01-09 10:48
Does it need to rebuild the whole cache first or should it be instant working after restart? Even after doing that I still get the same issue after restart of the whole cluster. Tried both list_quorum= optimal and strict (each followed by restart)

> So the best way is set the `quorum` then purge the content at this location on all drives `rm -rf /<backend_drive>/.minio.sys/buckets/<bucketname>/.metacache`

Edit: Been checking the different options for list_quorum= and with strict I get a very broad difference, less so with list_quorum=disk.

Could the above be related to expanding the cluster / adding a zone?

**Comment by harshavardhana** [comment] 2021-01-09 15:53
> Does it need to rebuild the whole cache first or should it be instant working after restart? Even after doing that I still get the same issue after restart of the whole cluster. Tried both list_quorum= optimal and strict (each followed by restart)
> 
> > So the best way is set the `quorum` then purge the content at this location on all drives `rm -rf /<backend_drive>/.minio.sys/buckets/<bucketname>/.metacache`
> 
> Edit: Been checking the different options for list_quorum= and with strict I get a very broad difference, less so with list_quorum=disk.
> 
> Could the above be related to expanding the cluster / adding a zone?

It is possible let me reproduce it on my end, it still looks some inconsistent backend.

**Comment by harshavardhana** [comment] 2021-01-11 03:44
So I tried to reproduce this locally, I can't seem to reproduce it.  Steps taken to reproduce 

- Create the first cluster with 4 drives, create around 800 files
- Then expand the cluster with another 4 drives create another set of 800 files and observe that new files are going to the expanded drives as well. 
- Once done verify `mc ls -r` from previous un-expanded with expanded setup - do not see any variation in `mc ls` output.

**Comment by Iguana9999phil** [comment] 2021-01-11 04:20
Well there is something wrong with it, I've rolled back to 2020-10-27T04 and that works without issue. While I would like to have a recent version working for me, I honestly don't have the will anymore to keep chasing a working version.

**Comment by harshavardhana** [comment] 2021-01-11 04:41
> Well there is something wrong with it, I've rolled back to 2020-10-27T04 and that works without issue. While I would like to have a recent version working for me, I honestly don't have the will anymore to keep chasing a working version.

No problem, if we find it we may reproduce and fix it in future, will close this issue as I can't reproduce it.

**Closed as completed by harshavardhana** 2021-01-11 04:41 UTC
Labels: community
