### ISSUE TITLE
server: Restic fails to backup over Nginx reverse proxy to Minio

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4056] opened 2017-04-06 18:49 UTC
Original issue here - https://github.com/restic/restic/issues/849, https://github.com/restic/restic/issues/904

## Expected Behavior
restore my file completely without a GOAWAY result.

## Current Behavior

The minio io instance is behind a HTTPS nginx reverse proxy. After some more testing today i was able to restore my data from minio without the reverse proxy and HTTP only successfully.
I'm running in an error while restoring my snapshot on my minio storage. I try to restore a ~4.5GB file but every time at 669MB it breaks wit following error. Backing up the file went perfectly fine.

```
http2: server sent GOAWAY and closed the connection; LastStreamID=1999, ErrCode=NO_ERROR, debug=""
obj.ReadAt
restic/backend/s3.(*s3).Load
	/tmp/restic-build-559492747/src/restic/backend/s3/s3.go:179
restic.ReadAt
	/tmp/restic-build-559492747/src/restic/readerat.go:25
restic/repository.(*Repository).loadBlob
	/tmp/restic-build-559492747/src/restic/repository/repository.go:106
restic/repository.(*Repository).LoadBlob
	/tmp/restic-build-559492747/src/restic/repository/repository.go:538
restic.Node.createFileAt
	/tmp/restic-build-559492747/src/restic/node.go:214
restic.(*Node).CreateAt
	/tmp/restic-build-559492747/src/restic/node.go:109
restic.(*Restorer).restoreNodeTo
	/tmp/restic-build-559492747/src/restic/restorer.go:90
restic.(*Restorer).restoreTo
	/tmp/restic-build-559492747/src/restic/restorer.go:53
restic.(*Restorer).RestoreTo
	/tmp/restic-build-559492747/src/restic/restorer.go:122
main.runRestore
	/tmp/restic-build-559492747/src/cmds/restic/cmd_restore.go:135
main.glob..func13
	/tmp/restic-build-559492747/src/cmds/restic/cmd_restore.go:23
github.com/spf13/cobra.(*Command).execute
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:599
github.com/spf13/cobra.(*Command).ExecuteC
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:689
github.com/spf13/cobra.(*Command).Execute
	/tmp/restic-build-559492747/src/github.com/spf13/cobra/command.go:648
main.main
	/tmp/restic-build-559492747/src/cmds/restic/main.go:37
runtime.main
	/usr/lib/go/src/runtime/proc.go:185
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:2197
```

What does the GOAWAY actually mean? Does it kill my connection and restic doesn't try to reconnect to the server how can i prevent that?

## Possible Solution
Current workaround is disable HTTP2

## Steps to Reproduce (for bugs)
Nginx HTTPS reverse proxy in front from minio. Restore you're backup in a long session.

## Context
Backups need to use a workaround on restic to make it work - `GODEBUG=http2client=0`

## Your Environment
restic 0.4.0 (v0.4.0-0-ga7c2f28)
compiled with go1.8 on linux/amd64

minio server release binary.

**Comment by vadmeste** [comment] 2017-04-06 18:54
Taking this.

**Comment by vadmeste** [comment] 2017-04-06 22:01
**=>**  I wasn't able to reproduce this issue, I tested with:

* Ubuntu 16.04 64 bits
*  go 1.8
*  minio 2017-03-16T21:50:32Z
*  restic: 0.4.0
*  nginx version: nginx/1.10.0 (Ubuntu)

**=>** Minio & nginx lives in one server, restic client is invoked from another server.
**=>** the size of the test file is 5 GiB.


**=>** **nginx config:**

```
client_max_body_size 128M;

server {
 listen 8081 ssl;
 server_name localhost;
 ssl_certificate public.crt;
 ssl_certificate_key private.key;
 ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
 ssl_ciphers HIGH:!aNULL:!MD5;
 location / {
   proxy_set_header Host $http_host;
   proxy_pass http://minio3:9001;
   # proxy_buffer off
 }
}
```

**=>** **Restic commands:**

`$ ./restic-0.4.0/restic -r s3:minio3:8081/testbucket/ init`
`$ ./restic-0.4.0/restic -r s3:minio3:8081/testbucket/ backup 5gb.file`

Then restore multiple times:

`$ ./restic-0.4.0/restic -r s3:minio3:8081/testbucket/ restore 02c68aee --target out/`


**=>** We need to have more information to be able to reproduce this.

@JohnnyLeone, could you paste your nginx configuration ?

**Comment by JohnnyLeone** [comment] 2017-04-08 19:50
Thanks for opening the issue here. I had not the time to open it myself.

As additional information too you i'm running minio in and nginx in a container. The base template for generating the nginx.conf is located here [nginx-proxy](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl)

### Here is my nginx.conf block for minio

```
upstream minio.foo.bar {
			server 172.18.0.4:9000;
}
server {
	server_name minio.foo.bar;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	return 301 https://$host$request_uri;
}
server {
	server_name minio.foo.bar;
	listen 443 ssl http2 ;
	access_log /var/log/nginx/access.log vhost;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
	ssl_prefer_server_ciphers on;
	ssl_session_timeout 5m;
	ssl_session_cache shared:SSL:50m;
	ssl_session_tickets off;
	ssl_certificate /etc/nginx/certs/minio.foo.bar.crt;
	ssl_certificate_key /etc/nginx/certs/minio.foo.bar.key;
	ssl_dhparam /etc/nginx/certs/minio.foo.bar.dhparam.pem;
	add_header Strict-Transport-Security "max-age=31536000";
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://minio.foo.bar;
	}
}
```

@vadmeste I'm using the same procedure to backup/restore my files with restic.

**Comment by vadmeste** [comment] 2017-04-09 19:04
@JohnnyLeone, I wasn't able to reproduce the issue with nginx_proxy using your nginx conf. Both nginx and minio were executed in two separate containers.

Can you update your jwilder/nginx-proxy and minio/minio image ? (`docker pull jwilder/nginx-proxy` and `docker pull minio/minio`)

I put the nginx config in a separate file (minio.conf) which will be /etc/nginx/conf.d/minio.conf inside the container and run the following command:
`docker run -p443:443 -p 80:80 -v /home/minio/vadmeste/nginx/:/etc/nginx/conf.d -v /var/run/docker.sock:/tmp/docker.sock:ro  jwilder/nginx-proxy`
 
Can you test again with my way and update us ?

**Comment by deekoder** [comment] 2017-04-11 16:47
Test by forcing restic to use http2 to directly communicate to minio @vadmeste .

**Comment by vadmeste** [comment] 2017-04-12 12:12
@JohnnyLeone, I was finally able to reproduce the bug but it is quite rare.

What does './restic version' say ?

This issue looks very related to this one https://github.com/golang/go/issues/18112 which is fixed in go 1.8. Can you rebuild restic with go 1.8 and see if the problem persists ?

**Comment by harshavardhana** [comment] 2017-04-12 15:37
The original issue reported by @JohnnyLeone says go1.8 - https://github.com/restic/restic/issues/849 so it is quite strange. Is it reproducible without nginx as well @vadmeste ? i.e forcing restic to use HTTP2.

**Comment by JohnnyLeone** [comment] 2017-04-12 17:00
Thanks for testing this long @vadmeste. Did you changed something to you're first nginx config post here?
I'm testing currently more and will report when i'm finished.

**Comment by vadmeste** [comment] 2017-04-12 17:10
> Thanks for testing this long @vadmeste. Did you changed something to you're first nginx config post here?

No, I didn't.

**Comment by JohnnyLeone** [comment] 2017-04-12 20:15
If i remove the `http2` statement in my `listen 443 ssl http2;` line it seems to work without any problem. But i think restic downloads now with http1.1.

**Comment by vadmeste** [comment] 2017-04-12 20:17
> If i remove the http2 statement in my listen 443 ssl http2; line it seems to work without any problem. But i think restic downloads now with http1.1.

Yes, I also reproduced with golang 1.8, that issue is rare in my configuration, are you testing with a high load ?

**Comment by JohnnyLeone** [comment] 2017-04-12 20:24
No, i really don't. It appears every time i try to restore the file with activated http2. The restore dies exactly after 1.1 Gb or 2.4Gb, the hashes by the fragments are also every time identical.

**Comment by vadmeste** [comment] 2017-04-12 20:27
Do you mean the issue is systematic and you have only one restic instance which is restoring a file ?

**Comment by JohnnyLeone** [comment] 2017-04-12 20:35
Right

**Comment by vadmeste** [comment] 2017-04-14 21:22
@JohnnyLeone 

This looks like a golang bug which is supposed to be fixed in go 1.8, besides it looks like restic can retry when it encounters this error. 

I don't believe this is related to Minio but I am still interested to understand what's going on.

Can you join us here https://slack.minio.io ?

**Comment by deekoder** [comment] 2017-04-17 16:53
@JohnnyLeone  since this does not seem to be a minio related issue, we will go ahead and close it. The workaround is to disable http2. Please reopen if you think this issue needs any further attention from us.

**Closed as completed by deekoder** 2017-04-17 16:53 UTC
Labels: working as intended, community, do-not-close, priority: high

**Comment by leshik** [comment] 2019-02-22 02:11
@harshavardhana @deekoder I'm seeing this with latest `minio` and `nginx` stable, except I'm not even using `restic`. All I do is mirroring a lot of small files (`svg` images) with `minio` client, and `minio` server is behind `nginx` proxy. The `nginx` config is from `minio` docs, nothing fancy.

**Comment by harshavardhana** [comment] 2019-02-22 02:16
> @harshavardhana @deekoder I'm seeing this with latest `minio` and `nginx` stable, except I'm not even using `restic`. All I do is mirroring a lot of small files (`svg` images) with `minio` client, and `minio` server is behind `nginx` proxy. The `nginx` config is from `minio` docs, nothing fancy.

please open a new issue @leshik

**Comment by leshik** [comment] 2019-02-22 02:39
> please open a new issue @leshik

Done in #7271.
