### ISSUE TITLE
[doc] File is wrapped in FormData boundary when using presigned http put in browser

### ISSUE THREAD

**Issue by gregod** [minio/minio#3148] opened 2016-11-01 14:46 UTC
When uploading using a presigned using form data ajax as described in the [docs
](https://docs.minio.io/docs/upload-files-from-browser-using-pre-signed-urls) the form data metadata is retained in the stored file. Happens in the edge and stable builds.

## Expected Behavior
File is stored as given by the client

## Current Behavior
File is wrapped in the the form data
```
------WebKitFormBoundary9hhme0TSqEoakTEU
Content-Disposition: form-data; name="tmp.txt"; filename="tmp.txt"
Content-Type: text/plain

File Content

------WebKitFormBoundary9hhme0TSqEoakTEU--
```

## Steps to Reproduce
1. Generate Presigned PUT url 
2. Use FormData ajax to upload the file ( either plain xhr or jquery as used in the [docs
](https://docs.minio.io/docs/upload-files-from-browser-using-pre-signed-urls))
```
<input type="file" id="selector" multiple>
<button onclick="upload()">Upload</button>

<div id="status">No uploads</div>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script type="text/javascript">

function upload() {
    var files = $('#selector')[0].files
    var file = files[0];

    let data = new FormData()
    data.append(file.name, file)

    $.ajax({
        url: "https://play.minio.io:9000/blamoo/test.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=Q3AM3UQ867SPQQA43P2F%2F20161101%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20161101T144030Z&X-Amz-Expires=259200&X-Amz-SignedHeaders=host&X-Amz-Signature=454206c4c1ef0aaca9f0f892a46fb9e3190758469396ae38de0343ee323bad9c",
        method: 'PUT',
        success: () => {
            $('#status').text(`Uploaded ${file.name}.`)
        },
        processData: false,
        contentType: false,
        data
    })
}

</script>
```

## Your Environment
minio stable build
minio java-client  2.0.4
Chrome & Firefox

**Comment by harshavardhana** [comment] 2016-11-01 16:38
This is not related to Minio server. Data is being modified here while uploading and server doesnt know that.  

Here is a relevant stackoverflow post http://stackoverflow.com/questions/38781909/webkitformboundary-included-in-file-payload-on-direct-upload-to-s3

**Comment by harshavardhana** [comment] 2016-11-01 16:40
Also i see that the documentation is wrong to indicate usage of FormData() we will fix it .

**Comment by harshavardhana** [comment] 2016-11-01 23:34
@gregod - we fixed and updated the document with relevant way to do this can you check https://docs.minio.io/docs/upload-files-from-browser-using-pre-signed-urls ?

**Comment by harshavardhana** [comment] 2016-11-02 22:14
> @gregod - we fixed and updated the document with relevant way to do this can you check https://docs.minio.io/docs/upload-files-from-browser-using-pre-signed-urls ?

Closing as fixed. Please re-open if the issue is observed again @gregod

**Closed as completed by harshavardhana** 2016-11-02 22:14 UTC
Labels: community

**Comment by gregod** [comment] 2016-11-03 00:13
Thanks for the quick reply. Works fine! I did try some more complicated aproaches using the FileReader API but somehow missed the easiest solution.
