### ISSUE TITLE
[browser] Removing a bucket policy after an error popup doesn't have an effect

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4498] opened 2017-06-07 22:06 UTC
## Expected Behavior
Removing a bucket policy *really* removes it.

## Current Behavior
Removing a bucket policy doesn't have an effect after an error popup

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)

1. Start from fresh FS disk
2. Login into Minio Browser
3. Create a bucket
4. Show bucket policy popup
5. Add '*'  policy
6. Add 'foo' policy
7. Add '*' policy again
(an error popup is shown to say that the user is adding an incompatible policy rule which is correct)
8. Now remove all existing policies
9. Hide policy dialog 
10. Show policy dialog  again

You'll notice that you have a policy rule though you removed all existing rules.

## Context
Testing before release

## Your Environment
minio master, all environments

**Comment by krisis** [comment] 2017-07-11 09:59
This issue can be reproduced simply as below.

1. Create a bucket
2. Show bucket policy modal
3. Add '*' policy
4. Remove '*' policy
5. Close bucket policy modal
6. Open bucket policy modal

You will find the bucket policy for '*' still present.

**Comment by krishnasrinivas** [comment] 2017-07-14 19:37
@vadmeste when you `Add '*' policy` do you put `*` in the input box? or do you leave it blank and then click `Add` button?

**Comment by vadmeste** [comment] 2017-07-14 20:08
> @vadmeste when you Add '*' policy do you put * in the input box? or do you leave it blank and then click Add button?

Yes, I put '*' in the input box. By the way, I am still able to reproduce with master (and not with the opened PR)

**Comment by brendanashworth** [comment] 2017-07-14 21:15
@krishnasrinivas AFAIK both empty and `*` do the same thing because of [this line of code](https://github.com/minio/minio/blob/bc73a1a1cb1ed89c913e3d7656c223a80a61b3bf/browser/app/js/components/PolicyInput.js#L36). #4671 is similar to that, but if we want to treat empty and `*` differently than we can discuss that

**Comment by krishnasrinivas** [comment] 2017-08-05 17:21
## Steps to Reproduce (for bugs)

1. Start from fresh FS disk
2. Login into Minio Browser
3. Create a bucket
4. Show bucket policy popup
5. Add '*'  policy
6. Add 'foo' policy
7. Add '*' policy again
(an error popup is shown to say that the user is adding an incompatible policy rule which is correct)
8. Now remove all existing policies
9. Hide policy dialog 
10. Show policy dialog  again

Here Step 6 itself should have given an error saying there is conflicting setting. (Because we have already set '*' policy)

**Comment by vadmeste** [comment] 2017-08-05 18:26
> Here Step 6 itself should have given an error saying there is conflicting setting. (Because we have already set '*' policy)

Actually, AWS S3 accepts having both `*` and `foo` at the same time.

```
19:25 $ mc policy list s3/vadmeste/
vadmeste/* => readonly
vadmeste/foo* => readonly
```

**Comment by harshavardhana** [comment] 2017-08-05 21:32
> 19:25 $ mc policy list s3/vadmeste/
> vadmeste/* => readonly
> vadmeste/foo* => readonly

We don't support nested policies yet @vadmeste

**Comment by deekoder** [comment] 2017-09-12 00:28
Need to fix this after we move to Vue.js

**Comment by kannappanr** [comment] 2018-10-31 00:00
Closing this issue as fixed based on feedback from @kaankabalak . This was fixed by a bunch of PRs from @kaankabalak @balamurugana and @ebozduman. The final PR to fix this issue is https://github.com/minio/minio/pull/6396

**Closed as completed by kannappanr** 2018-10-31 00:00 UTC
Labels: fixed, priority: medium
