### ISSUE TITLE
gateway: [s3] mc cp -r fails with a warning object key missing

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4126] opened 2017-04-14 23:04 UTC
## Expected Behavior
```
mc cp -r play/testbucket /tmp/
...t/resumes/4.thumb.png:  19.71 MB / 19.71 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 9.88 MB/s 1s
```

## Current Behavior
```
mc cp -r  mys3/testbucket  /tmp/
mc: <ERROR> Failed to copy `http://127.0.0.1:9000/testbucket/`. Object key is missing, object key cannot be empty
....0.1:9000/testbucket/:  19.71 MB / 19.71 MB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 7.87 MB/s 2s
```

## Possible Solution
Possibly related to #4125 recursive output perhaps a wrong entry.

## Steps to Reproduce (for bugs)
Use latest `mc` master, recursively copy a bucket.

## Context
S3 compatibility errors

## Your Environment
Download binary: http://minio-download.s3.amazonaws.com/minio and use the latest mc master.

**Comment by nl5887** [comment] 2017-04-17 13:32
related to #4129 and #4125. Fixed in latest PR.

**Comment by koolhead17** [comment] 2017-04-17 14:28
Can confirm, works as intended. 

```
$ mc cp appveyor.yml mys3/atul1
appveyor.yml:  1.60 KB / 1.60 KB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 2.67 KB/s 0s$ mc ls  mys3/atul1
[2017-04-17 19:57:15 IST] 1.6KiB appveyor.yml
$ mc cp -r  mys3/atul1  /tmp/
...veyor.yml:  1.60 KB / 1.60 KB  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100.00% 1.39 KB/s 1s$ 

```

**Closed as completed** 2017-04-17 16:25 UTC
Labels: duplicate, priority: high
