### ISSUE TITLE
RELEASE.2021-02-14T04-01-33Z and loadBucketMetaCache: object layer not ready

### ISSUE THREAD

**Issue by sylus** [minio/minio#11552] opened 2021-02-16 23:57 UTC
Hey awesome MinIO community. 

We recently just updated our MinIO instances from `RELEASE.2021-01-05T05-22-38Z` to `RELEASE.2021-02-14T04-01-33Z` to fix a  “panic: runtime error: integer divide by zero” resolved by https://github.com/minio/minio/pull/11307 

Unfortunately now with our instances they keep saying error messages such as “Error: loadBucketMetaCache: object layer not ready. bucket: “shared” (*errors.errorString)” and it has been 3 hours since without them healing. 

Has anyone run across this and is there other steps I can perform to debug this to figure out what the problem is? Before with this image update we have been running successfully for the past 2 months.

## Expected Behavior

That all of the MinIO instances come up successfully after updating the MinIO image.

## Current Behavior

```sh
❯ mc admin info aaw-standard
●  minio-standard-tenant-1-minio-zone-0-0.minio-standard-tenant-1-minio-hl.minio-standard-tenant-1.svc.cluster.local:9000
   Uptime: 3 hours 
   Version: 2021-02-14T04:01:33Z
   Network: 1/4 OK 
   Drives: 4/4 OK 
●  minio-standard-tenant-1-minio-zone-0-2.minio-standard-tenant-1-minio-hl.minio-standard-tenant-1.svc.cluster.local:9000
   Uptime: 3 hours 
   Version: 2021-02-14T04:01:33Z
   Network: 2/4 OK 
   Drives: 4/4 OK 
●  minio-standard-tenant-1-minio-zone-0-3.minio-standard-tenant-1-minio-hl.minio-standard-tenant-1.svc.cluster.local:9000
   Uptime: 3 hours 
   Version: 2021-02-14T04:01:33Z
   Network: 2/4 OK 
   Drives: 4/4 OK 
●  minio-standard-tenant-1-minio-zone-0-1.minio-standard-tenant-1-minio-hl.minio-standard-tenant-1.svc.cluster.local:9000
   Uptime: 3 hours 
   Version: 2021-02-14T04:01:33Z
   Network: 2/4 OK 
   Drives: 4/4 OK 
```

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

N/A

## Context

N/A

## Regression

N/A

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

MinIO: RELEASE.2021-02-14T04-01-33Z
MinIO Operator: v3.0.29

**Comment by sylus** [comment] 2021-02-17 00:24
I am seeing in logs:

Error: Post "http://minio-standard-tenant-1-minio-zone-0-1.minio-standard-tenant-1-minio-hl.minio-standard-tenant-1.svc.cluster.local:9000/minio/peer/v12/getmetacache?": context deadline exceeded (*rest.NetworkError)

Which makes me wonder if is related to: https://github.com/minio/minio/issues/10942#issuecomment-740962043

**Comment by harshavardhana** [comment] 2021-02-17 00:28
> I am seeing in logs:
> 
> Error: Post "http://minio-standard-tenant-1-minio-zone-0-1.minio-standard-tenant-1-minio-hl.minio-standard-tenant-1.svc.cluster.local:9000/minio/peer/v12/getmetacache?": context deadline exceeded (*rest.NetworkError)

Looks like you have some DNS issues

**Comment by zachomedia** [comment] 2021-02-17 00:35
@harshavardhana How do you figure that? I don't have access to DNS tools within that pod, but another pod shows it resolving just fine. Also, when the instance is down and no longer in the Kubernetes DNS, it appropriately shows a name resolution error.

```
# dig +short minio-standard-tenant-1-minio-zone-0-1.minio-standard-tenant-1-minio-hl.minio-standard-tenant-1.svc.cluster.local
[redacted ip]
```

**Comment by harshavardhana** [comment] 2021-02-17 00:40
from what I can figure the update didn't go through my suggestion would be to delete the deployment - hopefully your PVCs are local and you re-deploy the statefulset.

**Comment by sylus** [comment] 2021-02-17 14:08
Hmm eventually they all came up and it is running now, it took 6 hours though, very confusing.

**Comment by harshavardhana** [comment] 2021-02-17 18:20
> Hmm eventually they all came up and it is running now, it took 6 hours though, very confusing.

How many buckets do you have ?

**Comment by zachomedia** [comment] 2021-02-17 19:10
@harshavardhana 197 buckets with a total of 1,483,907 objects

**Comment by harshavardhana** [comment] 2021-02-17 19:11
> @harshavardhana 197 buckets with a total of 1,483,907 objects

I suspect something was up with those buckets, it would be harder to know.  I suspect since it was an operator there was an issue updating the image.

**Comment by harshavardhana** [comment] 2021-02-20 08:04
Not sure if there is an easier way to reproduce this, we haven't seen any such bug reports from the community or customers  -  we will close this issue for now.

**Closed as completed by harshavardhana** 2021-02-20 08:04 UTC
Labels: community
