### ISSUE TITLE
GCS Gateway: PutObject: Error: storage: object doesn't exist

### ISSUE THREAD

**Issue by shamil** [minio/minio#8928] opened 2020-02-03 17:48 UTC
When using GCS Gateway minio logs an error when uploading objects. The object got uploaded after several tries. 

We are also using S3 Gateway and it works as expected.

The error logged:

```
API: PutObject(bucket=test-bucket, object=v2/merchant=60003/hour=2020020317/ls.s3.fc3644b4-7a00-43ca-beb5-2a5dead213eb.2020-02-03T17.40.part6.txt)
Time: 17:42:22 UTC 02/03/2020
DeploymentID: bc85f804-af0d-499a-ac05-72a9dad5e293
RequestID: 15EFF555AAAAD529
RemoteHost: 127.0.0.1
Host: test-bucket.localhost:9000
UserAgent: aws-sdk-ruby2/2.11.427 jruby/2.5.3 java resources
Error: storage: object doesn't exist
       4: cmd/gateway/gcs/gateway-gcs.go:871:gcs.(*gcsGateway).GetObjectInfo()
       3: cmd/object-lock.go:171:cmd.checkPutObjectLockAllowed()
       2: cmd/object-handlers.go:1314:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

Sometimes the exception has different stack trace:

```
Error: storage: object doesn't exist
       4: cmd/gateway/gcs/gateway-gcs.go:871:gcs.(*gcsGateway).GetObjectInfo()
       3: cmd/object-lock.go:539:cmd.checkPutObjectRetentionAllowed()
       2: cmd/object-handlers.go:1251:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

## Regression

Last working version `RELEASE.2019-10-12T01-39-57Z`, all newer have the problem.

## Your Environment

* Version used: `RELEASE.2019-12-17T23-16-33Z`, but all earlier versions up to `RELEASE.2019-10-12T01-39-57Z` have this issue
Client: `aws-sdk-ruby2/2.11.427 jruby/2.5.3 ` (`logstash`)

Mini env variables:

```
MINIO_DOMAIN=localhost
MINIO_ACCESS_KEY_FILE=access_key
MINIO_KMS_MASTER_KEY_FILE=kms_master_key
MINIO_SSE_MASTER_KEY_FILE=sse_master_key
MINIO_ACCESS_KEY=admin
MINIO_UPDATE=off
MINIO_SECRET_KEY_FILE=secret_key
MINIO_SECRET_KEY=password
MINIO_CACHE_MAXUSE=0
```

let me know if you need more info

**Comment by kannappanr** [comment] 2020-02-04 02:38
@shamil Does this work with `RELEASE.2019-10-12T01-39-57Z` version?

**Comment by shamil** [comment] 2020-02-04 05:49
Yep, this is the last working version for me

**Comment by shamil** [comment] 2020-02-04 09:03
@kannappanr  I tried all versions after `RELEASE.2019-10-12T01-39-57Z`, also the latest one (`RELEASE.2020-01-25T02-50-51Z`). All of them causing same problem, the stacktrace a bit different (see above), but result is the same

**Comment by vadmeste** [comment] 2020-02-04 10:40
@shamil is the issue intermittent ? it would be great if you describe how to reproduce this

**Comment by shamil** [comment] 2020-02-04 11:10
@vadmeste 
We use `logstash-s3-output` plugin. The issue happens each time logstash uploads files to S3, the upload succeeded after exactly 2 tries.

below is a logstash configuration of s3 output

```
        s3 {
            # destination bucket, will be uploaded by Minio GCS gateway
            bucket => "test-bucket"

            # minio server
            access_key_id => "admin"
            secret_access_key => "password"
            endpoint => "http://localhost:9000"

            # limit chunk size to 5MB (less then 5MB won't work)
            upload_multipart_threshold => 5242880

            # each payload saved as json line
            codec => "json_lines"

            # upload when file reached 3MB or 1 minute passed (the first of the two)
            size_file => 3145728
            time_file => 1
        }
```

**Comment by shamil** [comment] 2020-02-09 08:44
After upgrading to latest version, I see the error only one time and the object get uploaded.
I guess this is related to fix #8953

The error still the same:

```
Error: storage: object doesn't exist
       4: cmd/gateway/gcs/gateway-gcs.go:871:gcs.(*gcsGateway).GetObjectInfo()
       3: cmd/object-lock.go:171:cmd.checkPutObjectLockAllowed()
       2: cmd/object-handlers.go:1321:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

**Comment by vadmeste** [comment] 2020-02-10 10:52
@shamil that log is verbose, I guess it will get removed. 

Are you seeing any other error otherwise ?

**Comment by shamil** [comment] 2020-02-10 15:22
Nope, otherwise it works as expected. I'd like to mention that this error isn't appear in s3 gateway, but does appear in gcs gateway...

**Comment by harshavardhana** [comment] 2020-02-10 16:22
That is because both are different implementations.. @shamil

**Comment by shamil** [comment] 2020-02-10 16:55
@hackintoshrao I see,
so if the error is harmless, I guess this can be closed, or should we wait for PR which moves this error to different level.

**Comment by harshavardhana** [comment] 2020-02-10 17:05
We need to fix the object locking code to avoid invoking `checkPutObjectLockAllowed` functions on gateway's which do not implement them.

**Comment by kannappanr** [comment] 2020-05-20 20:06
Closing this issue as fixed. I do not see the log in the current master.

**Closed as completed by kannappanr** 2020-05-20 20:06 UTC
Labels: priority: low, community

**Comment by dperezro** [comment] 2021-01-27 12:33
I'm seeing this issue in google as well. How can it be fixed? version used is `RELEASE.2021-01-05T05-22-38Z`. Thanks!

**Comment by ebozduman** [comment] 2021-01-27 17:59
@dperezro

The issue was originally filed for GCS anyways.
> I'm seeing this issue in google as well.

Did you mean some other gw as well, or did you mean you still see it on GCS gw?

Could you give us more info and the error msg you see?
What is your setup?
Do you have a way to reproduce it?

**Comment by aarnaud** [comment] 2021-06-04 18:30
Still have the issue on minio/minio:RELEASE.2021-05-27T22-06-31Z :

```
API: PutObject(bucket=MYBUCKET, object=videos/chunk-stream2-00004.m4s)
Time: 03:32:54 UTC 06/04/2021
DeploymentID: 5ddb8c68-04a4-4ace-be3c-6ec668267571
RequestID: 1685439B3FC17F89
RemoteHost: 10.16.2.3
Host: minio-gw:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.10
Error: storage: object doesn't exist (*errors.errorString)
       3: cmd/gateway/gcs/gateway-gcs.go:888:gcs.(*gcsGateway).GetObjectInfo()
       2: cmd/object-handlers.go:1689:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

API: PutObject(bucket=MYBUCKET, object=videos/chunk-stream0-00006.m4s)
Time: 03:36:46 UTC 06/04/2021
DeploymentID: 5ddb8c68-04a4-4ace-be3c-6ec668267571
RequestID: 168543D11CFAD149
RemoteHost: 10.16.2.3
Host: minio-gw:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.10
Error: storage: object doesn't exist (*errors.errorString)
       3: cmd/gateway/gcs/gateway-gcs.go:888:gcs.(*gcsGateway).GetObjectInfo()
       2: cmd/object-handlers.go:1689:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

API: PutObject(bucket=MYBUCKET, object=videos/chunk-stream2-00006.m4s)
Time: 03:36:46 UTC 06/04/2021
DeploymentID: 5ddb8c68-04a4-4ace-be3c-6ec668267571
RequestID: 168543D1330C044B
RemoteHost: 10.16.2.3
Host: minio-gw:9000
UserAgent: MinIO (linux; amd64) minio-go/v7.0.10
Error: storage: object doesn't exist (*errors.errorString)
       3: cmd/gateway/gcs/gateway-gcs.go:888:gcs.(*gcsGateway).GetObjectInfo()
       2: cmd/object-handlers.go:1689:cmd.objectAPIHandlers.PutObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()

```

**Comment by aarnaud** [comment] 2021-06-05 05:12
In my case it not a real issue, just logs, this stacktrace happen when minio try to write object on gcs but before, it try to get object to know if it had to delete.
