### ISSUE TITLE
s3 gateway handle invalid range 416 improperly

### ISSUE THREAD

**Issue by JetChars** [minio/minio#7481] opened 2019-04-04 08:55 UTC
## Expected Behavior

status code 416

## Current Behavior

```console
$ s3cmd get s3://foobar9/empty -f
download: 's3://foobar9/empty' -> './empty'  [1 of 1]
ERROR: S3 error: 500 (Internal Server Error)
```

## Possible Solution

- update func `ErrorRespToObjectError` and func `toAPIErrorCode` to handle exception type `InvalidRange`

## Steps to Reproduce (for bugs)

1. `touch empty`
2. `s3cmd put empty s3://foobar/empty`
3. `s3cmd get s3://foobar/empty -f`

## Context

Inappropriate 500 will lead to a bad user experience

## Regression

No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by kannappanr** [comment] 2019-04-04 22:05
@JetChars Can you specify more about the gateway part. I tried two things one is that the backend in the case of `s3 gateway` is minio and in the other scenario, it is `aws s3` and in both cases I did not see this issue. 

So, can you specify more info about your `minio` version and the backend `s3` server that you are using etc.

**Comment by JetChars** [comment] 2019-04-06 04:37
I'm using ceph/s3(Jewel) as the backend, which will return 416 if object size if zero.
Maybe you can try to retrieve an object with a manually specified range in aws s3 to reproduce a similar situation.

**Comment by JetChars** [comment] 2019-04-06 04:43
In func `ErrorRespToObjectError`, forget to handle issues like invalid range, maybe some other exception types too.

![image](https://user-images.githubusercontent.com/5701082/55664944-48efdb80-5869-11e9-9da0-94a812bff3f6.png)

**Comment by kannappanr** [comment] 2019-04-06 14:33
can you specify your minio version ? It will be easy for us if you follow the issue template.

**Comment by kannappanr** [comment] 2019-04-06 15:28
Also, I have tested it against `s3`, `s3 gateway with AWS as backend` and `minio` with latest master and I am receiving `416` in all scenarios.

Here is a reproducer code, that you can run. It assumes that you have the bucket and an empty object and uses aws-sdk-go.

```
package main

import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
)

func setupClient() *s3.S3 {

	//accessKey := "Q3AM3UQ867SPQQA43P2F"
	//secretKey := "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
	//sdkEndpoint := "https://play.minio.io:9000"

	accessKey := "minio"
	secretKey := "minio123"
	sdkEndpoint := "http://127.0.0.1:9000"


	creds := credentials.NewStaticCredentials(accessKey, secretKey, "")
	newSession := session.New()
	s3Config := &aws.Config{
		Credentials:      creds,
		Endpoint:         aws.String(sdkEndpoint),
		Region:           aws.String("us-east-1"),
		S3ForcePathStyle: aws.Bool(true),
		DisableSSL:       aws.Bool(false),
		Logger: aws.LoggerFunc(func(args ...interface{}) {
			fmt.Fprintln(os.Stdout, args...)
		}),
	}

	// Create an S3 service object in the default region.
	return s3.New(newSession, s3Config)
}
func main() {

	s3Client := setupClient()

	if s3Client == nil {
		fmt.Println("s3Client is nil, connection failed")
		return
	}

	bucket := "yourbucket"
	object := "empty"

	objectoutput, err := s3Client.GetObject(&s3.GetObjectInput{
		Bucket: aws.String(bucket),
		Key:    aws.String(object),
		Range:  aws.String("bytes=100-200"),
	})

	if err != nil {
		fmt.Println("Error: ", err)
		return
	}

	b, err := ioutil.ReadAll(objectoutput.Body)
	if err != nil {
		fmt.Println("Error: ", err)
		return
	}
	fmt.Println(string(b))
}

```

**Comment by kannappanr** [comment] 2019-04-07 23:38
@JetChars Closing this issue as working as intended. Please feel free to reach out to us, if you can reproduce this issue with either `play` or `AWS S3` as backend with the code given above.

**Closed as completed by kannappanr** 2019-04-07 23:38 UTC
Labels: working as intended, community, priority: medium
