### ISSUE TITLE
App with AWS-iOS-SDK-v2.6.10 failed uploading image file to minio-v22 with "Bad Sha256 error"

### ISSUE THREAD

**Issue by mayulu** [minio/minio#5339] opened 2018-01-02 03:13 UTC
## Full iOS function body code
with awss3 iOS sdk(v2.6.10)
``` swift
func push2awss3(uid: String, data: Data?) {
        let accessKey = "xxxxxx"
        let secretKey = "yyyyyyyyy"
        let credentialsProvider = AWSStaticCredentialsProvider(accessKey: accessKey, secretKey: secretKey)
        let configuration = AWSServiceConfiguration(region: .USEast1,
                                                    endpoint: AWSEndpoint(region: .USEast1,
                                                                          service: .S3,
                                                                          url: URL(string:"http://192.168.0.4:9000")),
                                                    credentialsProvider: credentialsProvider)
        AWSServiceManager.default().defaultServiceConfiguration = configuration
        let S3BucketName = "qbme"
        let remoteName = "\(UUID().uuidString).jpg"
        let fileURL = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent(remoteName)
        do {
            try data?.write(to: fileURL)
            debugPrint("Image File: ", fileURL)
        }
        catch {}
        let uploadRequest = AWSS3TransferManagerUploadRequest()!
        uploadRequest.body = fileURL
        uploadRequest.key = "\(uid)/\(remoteName)"
        uploadRequest.bucket = S3BucketName
        uploadRequest.contentType = "image/jpeg"
        uploadRequest.acl = .publicRead
        let transferManager = AWSS3TransferManager.default()
        transferManager.upload(uploadRequest).continueWith { (task: AWSTask<AnyObject>) -> Any? in
            DispatchQueue.main.async {
                debugPrint("In async queue...")
            }
            if let error = task.error {
                print("Upload failed with error: (\(error.localizedDescription))")
            }
            if task.result != nil {
                let url = AWSS3.default().configuration.endpoint.url
                let publicURL = url?.appendingPathComponent(uploadRequest.bucket!).appendingPathComponent(uploadRequest.key!)
                print("Uploaded to:\(String(describing: publicURL!))")
            }
            return nil
        }
    }
```

## Part of minio config.json file
``` json
        "version": "22",
	"credential": {
		"accessKey": "xxxxxx",
		"secretKey": "yyyyyyyyyy"
	},
	"region": "us-east-1",
	"browser": "on",
	"domain": "",
	"storageclass": {
		"standard": "",
		"rrs": ""
	},
```
## Part of nginx.conf
``` txt
worker_processes  auto;
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 20m;
    
    server {
        listen       80;
        server_name  localhost;
        location /qbme {
            #root   html;
            proxy_buffering off;
            proxy_set_header Host $http_host;
            proxy_pass http://localhost:9000;
        }
        location / {
            proxy_set_header Host $http_host;
            proxy_pass http://localhost:8080;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
    include servers/*;
}
```

**I had tried with and without nginx proxy to my local minio server, both failed.**
##### iOS log the error:
``` txt
Upload failed with error: (The operation couldn’t be completed. (com.amazonaws.AWSS3ErrorDomain error 0.))
```
##### minio log the error:
``` txt
time="2018-01-02T09:58:00+08:00" 
level=error 
msg="Unable to create an object. /qbme/mayulu/30031DB3-499D-4A9F-888F-B64B1F20754F.jpg" cause="Bad sha256: Expected e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 is not valid with what we calculated 07bcec324d4d06473e6e631fecdeaa49e1137349a063854bc557f23aec6f1d06"
```
### 2 With nginx proxy(request to http://localhost)
In this case, I think the request stopped at nginx, and did not reach minio
##### iOS log the error(same as above):
``` txt
Upload failed with error: (The operation couldn’t be completed. (com.amazonaws.AWSS3ErrorDomain error 0.))
```
##### nginx access and error log:
``` txt
access.log:
172.30.0.107 - - [02/Jan/2018:11:02:58 +0800] "PUT /qbme/mayulu/61A44F95-B736-4882-81CE-5D854046AC59.jpg HTTP/1.1" 403 169 "-" "aws-sdk-iOS/2.6.10 iOS/11.2 en_CN transfer-manager"
......
error.log:
2018/01/02 11:02:58 [crit] 3077#0: *1 open() "/usr/local/var/run/nginx/client_body_temp/0000000001" failed (13: Permission denied), client: 172.30.0.107, server: localhost, request: "PUT /qbme/mayulu/61A44F95-B736-4882-81CE-5D854046AC59.jpg HTTP/1.1", host: "172.30.0.70"
```

## the Request http header dumped:
``` txt
Content-Type:[image/jpeg] 
Accept-Language:[zh-cn] 
Accept:[*/*] 
Content-Length:[193373] 
Authorization:[AWS4-HMAC-SHA256 
		Credential=B5V58T2CI5D0SB2V7AOX/20180101/us-east-1/s3/aws4_request, 
		SignedHeaders=content-length;
		content-type;
		host;
		user-agent;
		x-amz-acl;
		x-amz-date, Signature=5594d2940403d73b6f3ad94ca915d56a8e52f520ec8af9e7c20af15816bc331b] 
X-Amz-Acl:[public-read] 
Accept-Encoding:[gzip, deflate] 
Connection:[keep-alive] 
User-Agent:[aws-sdk-iOS/2.6.10 iOS/11.2 en_CN transfer-manager] 
X-Amz-Date:[20180101T164801Z]
```
## The Environment
* minis version(stable 20171122195546 (bottled))
* AWS SDK version: 2.6.10
* Environment name and version (e.g. nginx 1.12.2)
* Go version(1.9.2)
* Server type and version: (macOS 10.13.2)
* Operating System and version (Darwin mambphd.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64)

Yes I noticed no transfer-encoding header field set, and  I checked aws-sdk v2.6.10 code, the field is not there either. And, I read the similar closed issues #4039 and #4731, but it does not help me.

Anyone can help me out?

**Comment by harshavardhana** [comment] 2018-01-02 03:26
Looks like iOS SDK is not sending the computed sha256 request. Can you enable MINIO_HTTP_TRACE=1 env and restart minio server ? 

We need to look at the server headers to see where exactly the issue might be.

**Comment by mayulu** [comment] 2018-01-02 03:33
@harshavardhana  Is this help?
``` txt
time="2018-01-02T11:31:18+08:00" level=error msg="Unable to create an object. /qbme/mayulu/4D4C05AD-039E-4FA0-AD91-6C9BDFE758C2.jpg" cause="Bad sha256: Expected e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 is not valid with what we calculated 07bcec324d4d06473e6e631fecdeaa49e1137349a063854bc557f23aec6f1d06" source="[object-handlers.go:621:objectAPIHandlers.PutObjectHandler()]" stack="/q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1-helpers.go:305:fsCreateFile() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1.go:634:fsObjects.PutObject() <autogenerated>:1:(*fsObjects).PutObject() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:619:objectAPIHandlers.PutObjectHandler() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/api-router.go:63:(objectAPIHandlers).PutObjectHandler-fm() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107:(*Router).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:600:rateLimit.ServeHTTP() <autogenerated>:1:(*rateLimit).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:558:pathValidityHandler.ServeHTTP() <autogenerated>:1:(*pathValidityHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:497:httpStatsHandler.ServeHTTP() <autogenerated>:1:(*httpStatsHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:65:requestSizeLimitHandler.ServeHTTP() <autogenerated>:1:(*requestSizeLimitHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:90:requestHeaderSizeLimitHandler.ServeHTTP() <autogenerated>:1:(*requestHeaderSizeLimitHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51:crossDomainPolicy.ServeHTTP() <autogenerated>:1:(*crossDomainPolicy).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:219:redirectHandler.ServeHTTP() <autogenerated>:1:(*redirectHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:267:minioReservedBucketHandler.ServeHTTP() <autogenerated>:1:(*minioReservedBucketHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:246:cacheControlHandler.ServeHTTP() <autogenerated>:1:(*cacheControlHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:337:timeValidityHandler.ServeHTTP() <autogenerated>:1:(*timeValidityHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190:(*Cors).Handler.func1() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:448:resourceHandler.ServeHTTP() <autogenerated>:1:(*resourceHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:234:authHandler.ServeHTTP() <autogenerated>:1:(*authHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:133:reservedMetadataHandler.ServeHTTP() <autogenerated>:1:(*reservedMetadataHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/pkg/http/server.go:107:(*Server).Start.func1() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /opt/go/src/net/http/server.go:2619:serverHandler.ServeHTTP() /opt/go/src/net/http/server.go:1801:(*conn).serve()"
```

**Comment by mayulu** [comment] 2018-01-02 03:35
@harshavardhana ,I format the log, looks easier.

``` txt
time="2018-01-02T11:31:18+08:00" 
level=error 
msg="Unable to create an object. /qbme/mayulu/4D4C05AD-039E-4FA0-AD91-6C9BDFE758C2.jpg" 
cause="Bad sha256: Expected e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 is not valid with what we calculated 07bcec324d4d06473e6e631fecdeaa49e1137349a063854bc557f23aec6f1d06" 
source="[object-handlers.go:621:objectAPIHandlers.PutObjectHandler()]" 
stack="/q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1-helpers.go:305:fsCreateFile() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1.go:634:fsObjects.PutObject() <autogenerated>:1:(*fsObjects).PutObject() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:619:objectAPIHandlers.PutObjectHandler() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/api-router.go:63:(objectAPIHandlers).PutObjectHandler-fm() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107:(*Router).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:600:rateLimit.ServeHTTP() <autogenerated>:1:(*rateLimit).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:558:pathValidityHandler.ServeHTTP() <autogenerated>:1:(*pathValidityHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:497:httpStatsHandler.ServeHTTP() <autogenerated>:1:(*httpStatsHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:65:requestSizeLimitHandler.ServeHTTP() <autogenerated>:1:(*requestSizeLimitHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:90:requestHeaderSizeLimitHandler.ServeHTTP() <autogenerated>:1:(*requestHeaderSizeLimitHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51:crossDomainPolicy.ServeHTTP() <autogenerated>:1:(*crossDomainPolicy).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:219:redirectHandler.ServeHTTP() <autogenerated>:1:(*redirectHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:267:minioReservedBucketHandler.ServeHTTP() <autogenerated>:1:(*minioReservedBucketHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:246:cacheControlHandler.ServeHTTP() <autogenerated>:1:(*cacheControlHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:337:timeValidityHandler.ServeHTTP() <autogenerated>:1:(*timeValidityHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190:(*Cors).Handler.func1() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:448:resourceHandler.ServeHTTP() <autogenerated>:1:(*resourceHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:234:authHandler.ServeHTTP() <autogenerated>:1:(*authHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:133:reservedMetadataHandler.ServeHTTP() <autogenerated>:1:(*reservedMetadataHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/pkg/http/server.go:107:(*Server).Start.func1() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /opt/go/src/net/http/server.go:2619:serverHandler.ServeHTTP() /opt/go/src/net/http/server.go:1801:(*conn).serve()"
```

**Comment by harshavardhana** [comment] 2018-01-02 04:54
From what you shared earlier it looks like the request has no x-amz-content-sha256 set, so it would mean that payload checksum is not set.. 

Have you tested the same code with AWS S3 ? If yes can you post the request header that you see from client ?

But I think I have a clue on what is going wrong here.

**Comment by harshavardhana** [comment] 2018-01-02 06:36
Sent a PR which should address this problem @mayulu

**Comment by mayulu** [comment] 2018-01-02 06:58
wonderful job, great! Thank you. @harshavardhana

**Comment by mayulu** [comment] 2018-01-03 00:21
Hi, @hackintoshrao , this fix has merged into master, right? I update my local minio repo to "2018-01-02T11:55:26Z", I tried the same as previous procedure, still failed, log shows just the same.
And I noticed that the minio log alway shows:
``` txt
Bad sha256: Expected e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 is not valid with what we calculated ec8df795fa53dea68cd0868e6145e66487e6010b5ce26a8597f6b593975bf6b6
```
Maybe it is not empty, just competed the wrong way, right?

And, I also try the the same code to aws s3, it succeed. 

``` txt
Uploaded to:https://s3.amazonaws.com/mayuluqbme/mayulu/838990B2-C39F-42A6-856B-96C3A23EBCBC.jpg
``` 
I don't how to print the the awss3 request header in the client, I use simple go code to dump the previous header dump.

Any idea?
Thank you.

**Comment by harshavardhana** [comment] 2018-01-03 00:22
It is not merged yet.. @mayulu

**Comment by mayulu** [comment] 2018-01-03 06:09
Hi, @harshavardhana, I tried  the **3fff3dc**  fix, still fail. But the minio log is the following:

``` txt
ERRO[0531] {"method":"PUT","reqURI":"/qbme/mayulu/70006A77-5F7D-484C-94B3-96DFC59C8D7C.jpg","header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["zh-cn"],"Authorization":["AWS4-HMAC-SHA256 Credential=B5V58T2CI5D0SB2V7AOX/20180103/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;user-agent;x-amz-acl;x-amz-date, Signature=5a57c35dc70c18e43abfb2ae5ee6eeb5e9175aadf495a1a66b59395d17ad7a72"],"Connection":["keep-alive"],"Content-Length":["178772"],"Content-Type":["image/jpeg"],"Host":["172.20.10.2"],"User-Agent":["aws-sdk-iOS/2.6.10 iOS/11.2 en_CN transfer-manager"],"X-Amz-Acl":["public-read"],"X-Amz-Date":["20180103T055817Z"]}}  cause=Signature does not match source=[object-handlers.go:590:objectAPIHandlers.PutObjectHandler()]
```
Am I miss something?

**Comment by harshavardhana** [comment] 2018-01-03 06:21
> Hi, @harshavardhana, I tried the 3fff3dc fix, still fail. But the minio log is the following:
> 
> ERRO[0531] {"method":"PUT","reqURI":"/qbme/mayulu/70006A77-5F7D-484C-94B3-96DFC59C8D7C.jpg","header":{"Accept":["*/*"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["zh-cn"],"Authorization":["AWS4-HMAC-SHA256 Credential=B5V58T2CI5D0SB2V7AOX/20180103/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;user-agent;x-amz-acl;x-amz-date, Signature=5a57c35dc70c18e43abfb2ae5ee6eeb5e9175aadf495a1a66b59395d17ad7a72"],"Connection":["keep-alive"],"Content-Length":["178772"],"Content-Type":["image/jpeg"],"Host":["172.20.10.2"],"User-Agent":["aws-sdk-iOS/2.6.10 iOS/11.2 en_CN transfer-manager"],"X-Amz-Acl":["public-read"],"X-Amz-Date":["20180103T055817Z"]}}  cause=Signature does not match source=[object-handlers.go:590:objectAPIHandlers.PutObjectHandler()]
> Am I miss something?

This is perhaps how the signature is being constructed on the iOS SDK, would it be possible for you to give me your full application that i can validate?

**Comment by mayulu** [comment] 2018-01-03 06:27
@harshavardhana, sure I will mail your a minimum runnable iOS package soon.

**Comment by harshavardhana** [comment] 2018-01-03 06:29
> @harshavardhana, sure I will mail your a minimum runnable iOS package soon.

Thanks with source would be better.. @mayulu

**Comment by mayulu** [comment] 2018-01-03 07:06
@harshavardhana Here it is: https://github.com/mayulu/TestAWS
You can define you own Key string and server url in the ViewController.swift file, easy to be found.
Thank you.

**Comment by harshavardhana** [comment] 2018-01-03 07:07
> @harshavardhana Here it is: https://github.com/mayulu/TestAWS
> You can define you own Key string and server url in the ViewController.swift file, easy to be found.
> Thank you.

Thanks a lot @mayulu

**Comment by harshavardhana** [comment] 2018-01-05 01:05
Was able to successfully run your application, we had a regression introduced recently @mayulu - the PR should fix the issue now.

**Closed** 2018-01-09 07:19 UTC
Labels: priority: medium

**Comment by mayulu** [comment] 2018-01-09 07:26
Thanks @harshavardhana @nitisht , it works.  :)
