### ISSUE TITLE
reload certificate chain & key on SIGHUP

### ISSUE THREAD

**Issue by harridu** [minio/minio#13669] opened 2021-11-16 12:01 UTC
**Is your feature request related to a problem? Please describe.**
Using letsencrypt I get a new certificate chain and key file every other month. How can I tell bare-metal minio to recognize these new files (pointed to by symlinks) immediately?

**Describe the solution you'd like**
The "usual" solution is to write a pid file /run/minio.pid as configured, and to send a HUP to minio to reread its configuration, including the new key and certificates.
```
test -f /etc/minio.pid && kill -HUP `cat /etc/minio.pid`
```

**Describe alternatives you've considered**
I found #13662, but this seems to focus on running minio inside a Kubernetes cluster.

**Comment by klauspost** [comment] 2021-11-16 12:39
@harridu Do you need a PID file? It should be fairly easy to find PID without it.

**Comment by harridu** [comment] 2021-11-16 15:19
Its easy to find **all** pids of minio executables, but you don't know which is the right one to send a signal to.

**Comment by klauspost** [comment] 2021-11-16 16:15
@harridu I don't see how is having a single pid file going to solve that?

Sounds like an unnecessary complication. There isn't much lost in reloading certs for all processes anyway.

**Comment by klauspost** [comment] 2021-11-16 16:16
I am looking into hooking into the signal. Trying to make a clean implementation is the trickiest part.

**Comment by harshavardhana** [comment] 2021-11-16 16:40
Closing as duplicate of #13662 , enhancement for symlinks will be done in the same issue.

**Closed as completed by harshavardhana** 2021-11-16 16:40 UTC
Labels: duplicate, community
