### ISSUE TITLE
[distributed] `mc cp -r ` throws `bucket not found` and continues

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#2520] opened 2016-08-22 12:58 UTC
minio version:

```
Version: 2016-08-22T08:13:15Z
Release-Tag: DEVELOPMENT.2016-08-22T08-13-15Z
Commit-ID: 81da694efccd02231d50991146f64d553ad1fc31
```

Reproducer:

``` bash
$ mc cp -r /usr/src myminio/mybucket/
/usr/src/linux-headers-4.4.0-34/arch/arm/mach-imx/Makefile:  194.11 MB / 248.45 MB   78.13% 179.58 KB/s 5m9s
mc: <ERROR> Failed to copy ‘/usr/src/linux-headers-4.4.0-34/arch/arm/mach-imx/Makefile.boot’. Bucket ‘mybucket’ does not exist.                       
/usr/src/linux-headers-4.4.0-34/zfs/udev/rules.d/Makefile.in:  248.45 MB / 248.45 MB  100.00% 187.32 KB/s 22m38s
```

**Comment by harshavardhana** [comment] 2016-08-22 17:56
Can you post server logs as well?

**Comment by harshavardhana** [comment] 2016-08-22 17:58
This is most probably the same - https://github.com/minio/minio/issues/2501

**Comment by balamurugana** [comment] 2016-08-23 06:57
This happens when two `mc cp -r /usr/src myminio/mybucket` are run.  Log from server1 is as below

```
ERRO[14214] Stat failed on bucket mybucket.               cause=connection is shut down
ERRO[14214] Unable to create an object.                   cause=Bucket not found: mybucket
```

No log is on server2 console.

**Comment by harshavardhana** [comment] 2016-08-23 07:19
> This happens when two mc cp -r /usr/src myminio/mybucket are run. Log from server1 is as below
> 
> ERRO[14214] Stat failed on bucket mybucket.               cause=connection is shut down
> ERRO[14214] Unable to create an object.                   cause=Bucket not found: mybucket
> No log is on server2 console.

Thanks @balamurugana - closing this as duplicate of #2501

**Closed as completed by harshavardhana** 2016-08-23 07:19 UTC
