### ISSUE TITLE
File corrupted when uploaded via SFTP

### ISSUE THREAD

**Issue by mh-ambition-dk** [minio/minio#18415] opened 2023-11-09 10:34 UTC
[MinIO_test.txt](https://github.com/minio/minio/files/13306872/MinIO_test.txt)

When uploading the attached file via SFTP to MinIO it looks like the file is corrupted.

For example here the file is corrupted from line 883 and onwards:

```
881: Hello World -- this is line 881 of the file... Here are some national letters: ÆØÅæøå
882: Hello World -- this is line 882 of the file... Here are some national letters: ÆØÅæøå
883: Heare some national letters: ÆØÅæøå
884: Hello World -- this is line 1059 of the file... Here are some national letters: ÆØÅæøå
885: Hello World -- this is line 1060 of the file... Here are some national letters: ÆØÅæøå
```

The uncorrupted source file look like this:

```
881: Hello World -- this is line 881 of the file... Here are some national letters: ÆØÅæøå
882: Hello World -- this is line 882 of the file... Here are some national letters: ÆØÅæøå
883: Hello World -- this is line 883 of the file... Here are some national letters: ÆØÅæøå
884: Hello World -- this is line 884 of the file... Here are some national letters: ÆØÅæøå
885: Hello World -- this is line 885 of the file... Here are some national letters: ÆØÅæøå
```

The file size is unchanged but data seem to be shuffeled. Its random if it happens or not and where it happens. So you might have to try a few times before it happens.

The problem seems to happen in the SFTP upload process. If I upload the file using MinIO Console I have no problems downloading with SFTP or MinIO Console. But if the file is uploaded using SFTP the file is corrupted both when downloading using MinIO Console and SFTP.

I have tried uploading both using SSH.NET in C# and using FileZilla. The same corruption seem to happen with both.

**Comment by zveinn** [comment] 2023-11-09 11:12
hello!

I've been trying to replicate your issue using the same file but I cannot. I tried uploading and downloading multiple times but it's always consistent. 

- Can you describe your MinIO setup a little better ? 
- What are the configurations like ? 
- are you connecting to MinIO over wifi or the internet ? 
- have you tried pinging the MinIO server to see if there is instability on the network ? 

I would love to debug this further but I need a little more information, maybe a test script that can help me reproduce ?

**Comment by mh-ambition-dk** [comment] 2023-11-09 11:27
Thank you for your fast response!

Here are some feedback from my server admin:

•	What are the configurations like?

helm chart:
NAME                            CHART VERSION   APP VERSION
bitnami/minio                   12.9.1          2023.11.1
standalone mode with SFTP enabled

•	are you connecting to MinIO over wifi or the internet ? 

Internet > Firewall > MinIO

•	have you tried pinging the MinIO server to see if there is instability on the network ? 

No, but its unlikely to be the cause.

I also had trouble reproducing it now but it happened again with the file after maybe 8-10 attempts. Try uploading a larger ZIP-file to reproduce. It seems to fail more often with a large ZIP-file. At least it does for me.

**Comment by zeeZ** [comment] 2023-11-09 12:45
I've seen it in a local cluster, and I've been able to reproduce it locally.

```bash
$ wget https://dl.min.io/server/minio/release/linux-amd64/minio
$ chmod +x minio
$ ssh-keygen -q -N "" -t rsa -b 4096 -f ./id_rsa
$ MINIO_ROOT_USER=admin MINIO_ROOT_PASSWORD=password ./minio server ./data --console-address ":9001" --sftp="address=:8022" --sftp="ssh-private-key=id_rsa"

$ ./minio -v
minio version RELEASE.2023-11-06T22-26-08Z (commit-id=754f7a8a395e87a744050476d8b16c16af50a800)
Runtime: go1.21.3 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

$ mc -v
mc version RELEASE.2023-11-06T04-19-23Z (commit-id=011c61b2547e9db988262f9ef12c64e981c42705)
Runtime: go1.21.3 linux/amd64
Copyright (c) 2015-2023 MinIO, Inc.
License GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

$ mc alias set localhost http://127.0.0.1:9000 admin password
$ mc mb localhost/test

$ head -c 1G </dev/urandom >testfile

$ mc cp testfile localhost/test/testfile_put_mc
$ mc cp localhost/test/testfile_put_mc testfile_put_mc_get_mc

$ sftp -P 8022 admin@127.0.0.1
admin@127.0.0.1's password:
Connected to 127.0.0.1.
sftp> put testfile test/testfile_put_sftp
Uploading testfile to /test/testfile_put_sftp/testfile
testfile                                                                                                                                                 100% 1024MB 171.7MB/s   00:05
sftp> get test/testfile_put_sftp/testfile testfile_put_sftp_get_sftp
Fetching /test/testfile_put_sftp/testfile to testfile_put_sftp_get_sftp
testfile                                                                                                                                                 100% 1024MB  20.9MB/s   00:49
sftp> bye

$ mc cp localhost/test/testfile_put_sftp/testfile testfile_put_sftp_get_mc

$ md5sum testfile*
ecf4527d96bb77e66b51c99b8647d971  testfile
ecf4527d96bb77e66b51c99b8647d971  testfile_put_mc_get_mc
5b6f7460a605c7e4434c9eec9b10aeb1  testfile_put_sftp_get_mc
5b6f7460a605c7e4434c9eec9b10aeb1  testfile_put_sftp_get_sftp
```

Edit: mc uploaded, sftp downloaded file did not get corrupted:

```bash
$ sftp -P 8022 admin@127.0.0.1
admin@127.0.0.1's password:
Connected to 127.0.0.1.
sftp> get test/testfile_put_mc testfile_put_mc_get_sftp
Fetching /test/testfile_put_mc to testfile_put_mc_get_sftp
testfile_put_mc                                                                                                                                          100% 1024MB  21.4MB/s   00:47
sftp> bye

$ md5sum testfile*
ecf4527d96bb77e66b51c99b8647d971  testfile
ecf4527d96bb77e66b51c99b8647d971  testfile_put_mc_get_mc
ecf4527d96bb77e66b51c99b8647d971  testfile_put_mc_get_sftp
5b6f7460a605c7e4434c9eec9b10aeb1  testfile_put_sftp_get_mc
5b6f7460a605c7e4434c9eec9b10aeb1  testfile_put_sftp_get_sftp
```

**Comment by zveinn** [comment] 2023-11-09 13:42
Thank you for the input! 

I will give this a test and get back to you once I'm done

**Comment by zeeZ** [comment] 2023-11-09 14:57
I did the same with the MinIO_test.txt and looking at the diff it became obvious that large chunks of the data **are in a different order** in the corrupted files. All the bytes are there, just jumbled.

**Comment by zveinn** [comment] 2023-11-09 14:58
@mh-ambition-dk @zeeZ 

I was able to duplicate this issue. 

What I did is write a small go program that creates a file with a byte pattern.. the pattern was as follows:
```
uint32(4bytes)+200x0(200bytes)+3x255(3bytes)
```
This created a giant 200MB file with 255x3 as the postfix to every line. I think uploaded them and re-downloaded using the SFTP and it turns out... there is indeed some kind of async/write issue happening when files are being uploaded via the SFTP. 

In the below print  you can see how three segments are essentially places out of order (OOF). 

# Print 
The parser splits the files into lines using the 3x255 as a sepperator, leaving 204 bytes left as the line size. 
The first 4 bytes are uint32 IDs representing the line/segment number as inserted when the file is created.

It's pretty obvious by the printout that some segments are being written to the file in the wrong order.
```bash
OOF| line(806853) prevLen(142) len(204) || prevID(806853) ID(807012) nextID(807013)
____ PREV LINE ____
[0 12 79 197 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
OOF| line(807012) prevLen(121) len(204) || prevID(807170) ID(806854) nextID(806855)
____ PREV LINE ____
[0 12 81 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
OOF| line(807170) prevLen(349) len(204) || prevID(807011) ID(807171) nextID(807172)
____ PREV LINE ____
[0 12 80 99 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

I will investigate this in the coming days and get back to you. 

Thank you for reporting this!

**Comment by zveinn** [comment] 2023-11-11 08:17
@mh-ambition-dk @zeeZ 
we just merged a fix into master #18422 can you give it a try for us ?

**Closed as completed** 2023-11-11 09:06 UTC
Labels: community, fixed

**Comment by mh-ambition-dk** [comment] 2023-11-13 08:27
Amazing -- thanks -- it looks good -- now I can upload a 1+GB file and download again without corruption. Thank you very much!

**Comment by zeeZ** [comment] 2023-11-13 10:50
I haven't been able to reproduce it after the fix, variety of files both in a single instance and cluster seem to be fine now. 👍

**Comment by zveinn** [comment] 2023-11-13 13:08
Glad to hear it!
