### ISSUE TITLE
Unable to authenticate with access keys 

### ISSUE THREAD

**Issue by hu1buerger** [minio/minio#20015] opened 2024-06-29 11:35 UTC
Access keys deployed through the minio dashboard are not recognised.

## Expected Behavior

```python
from minio import Minio

client = Minio(MINIO_SERVICE,
    access_key="KEYS_FROM_SETUP",
    secret_key="KEYS_FROM_SETUP",
)
client.list_buckets()
```

should return all the buckets.

## Current Behavior

```
    raise response_error
minio.error.S3Error: S3 operation failed; code: InvalidAccessKeyId, message: The Access Key Id you provided does not exist in our records., resource: /, request_id: 17DD75AB5D929823, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8
```

## Steps to Reproduce (for bugs)

1. Deploy an authentik container 
2. Deploy a minio container
3. Set authentik as an OpenID source for minio as [described here](https://docs.goauthentik.io/integrations/services/minio/)

4. Open the minio dashboard. 
5. Click on `Access Keys`.
6. Create an access key.

## Context

I am trying to authorise microservices to access data stored in a bucket.

## Your Environment

```
MinIO Object Storage Server
Copyright: 2015-2024 MinIO, Inc.
License: GNU AGPLv3 - https://www.gnu.org/licenses/agpl-3.0.html
Version: RELEASE.2024-06-28T09-06-49Z (go1.22.4 linux/amd64)

API: http://172.21.0.3:9000  http://127.0.0.1:9000 
WebUI: http://172.21.0.3:9001 http://127.0.0.1:9001  

Docs: https://min.io/docs/minio/linux/index.html
Status:         1 Online, 0 Offline. 
STARTUP WARNINGS:
The standard parity is set to 0. This can lead to data loss.
```

minio is running in a docker container with 3bad56718cc9

**Comment by hu1buerger** [comment] 2024-06-29 11:39
Service account keys are working nonetheless.

Edit: no they are not. Only old keys are still working. New ones seem to be kaput.

**Comment by harshavardhana** [comment] 2024-06-30 03:40
Please upgrade your setup and let us know

**Comment by hu1buerger** [comment] 2024-07-01 09:10
The service account credentails seem to be working after the upgrade. Access keys are still not recognised.

**Comment by harshavardhana** [comment] 2024-07-02 09:42
> The service account credentails seem to be working after the upgrade. Access keys are still not recognised.

I have no idea what you are talking about here.  Access keys and service accounts are same.

**Comment by harshavardhana** [comment] 2024-07-02 09:43
if you enable OpenID, then internal IDP users are not available via the Console UI. Closing this issue as non-actionable AFAICS.

**Closed as completed by harshavardhana** 2024-07-02 09:43 UTC
Labels: working as intended, community

**Comment by rodion-serhieiev** [comment] 2024-07-02 11:57
Hi @Hu1buerger ,
In our MinIO deployment, we faced the same issue. We are using OpenID(Keycloak) integration, and we determined that if Access keys were created in the user that receives the STS token from Keycloak, after the expiration of the STS token, the Access keys would not work anymore.
For the Service-to-service connection, we went with a service account.
However, we haven't yet found the solution for integration from user-to-service. When I talk about user-to-service integration, I mean integration like in Clickhouse with the S3 backend for external tables. Due to explosion credentials to Clickhouse in logs, some users log into MinIO and update their STS token. I know this is a terrible solution, but as I said, we are looking for a solution.

**Comment by hu1buerger** [comment] 2024-07-02 12:03
@rodion-serhieiev so you are facing a similar issue?

**Comment by rodion-serhieiev** [comment] 2024-07-02 15:39
In our case, if the owner of the access key that does not work will log in to the MinIO console, then his access key will work until the STS token expires.
If you have a different scenario, then our issues are different.

In my case, the issue is not on the MinIO side as marked @harshavardhana, it is working as intended.
