### ISSUE TITLE
connection may hang when use http1.0

### ISSUE THREAD

**Issue by xxxsen** [minio/minio#7762] opened 2019-06-08 11:25 UTC
minio server dont close the connection occasionally when use http1.0.

## Expected Behavior

minio server close connection normally 

## Current Behavior

minio server hangs connection

## Possible Solution

use http1.1

## Steps to Reproduce (for bugs)

run this cmd but it it not 100% to reproduce

127.0.0.1:1800 is the addr which minio server listen
```shell
for i in `seq 1 100000`; do curl --http1.0 127.0.0.1:1800  ; done
```

## Context

someone who use nginx but not add "proxy_http_version 1.1;" may be affected (nginx "proxy_pass" use http1.0 as default)

## Regression
no

## Your Environment

* Version used (`minio version`):Version: 2019-06-04T01:15:58Z
* Environment name and version (`curl version`):curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3 
* Server type and version:ubuntu 18.04
* Operating System and version (`uname -a`):Linux sen-workstation 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:none

**Comment by harshavardhana** [comment] 2019-06-08 14:12
Yes we reproduced this already as a Go upstream issue since Go 1.12, we do have a fix in #7661 

Closing as duplicate of #7661

**Closed as completed by harshavardhana** 2019-06-08 14:12 UTC
Labels: duplicate, community, triage
