### ISSUE TITLE
admin-api: Issue when heal is attempted while a node is down.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3980] opened 2017-03-27 08:13 UTC
Incorrect error message/false-detection when heal is attempted on a setup in which a node down.
## Expected Behavior

A message which could convey that heal has to be attempted after the node is back.
## Current Behavior

An attempt to heal shows that the object is healed.
## Possible Solution

- The issue could just at the presentation layer or it could be more deeper problem in detection.
## Steps to Reproduce (for bugs)

1. Start a 4 node Minio distributed.
2. Bring a node down.
3. Upload an object.
4. Now try to heal the bucket.

Note: Since the node to be healed is still not up, an attempt to heal should inform that to the user.

## Context

`mc admin heal` testing.
## Your Environment

* Version used: 6e63904048e9d7318c5454268b418b92317ba871

**Comment by krisis** [comment] 2017-03-27 10:02
@harshavardhana I am working on this.

**Comment by deekoder** [comment] 2017-04-03 16:58
If the server is capable of healing and can establish quorum, it should. If we can't return error message.

**Comment by krisis** [comment] 2017-04-04 06:16
## Background
Healing algorithm returns failure only if an attempt to heal any of the disks failed. It returns success even if all disks needing heal were offline.
In its current form, heal admin REST APIs returns the above boolean state making it impossible for clients like `mc` to distinguish between an object being healed completely, partially and not.

## Solution
The fix (so far) is to return `struct { HealedCount int, OfflineCount int}` in addition to `error` for a heal-object and heal-upload operation. `mc` can make use of this to guide their users better.

## Future-proof solution
This brings us to whether it is right by design to provide internal details of the healing process in admin API. @abperiasamy, IIUC we could return an enumerated constant in heal-object and heal-upload API that captures the 3 result states of the heal operation, namely, `CompletelyHealed`, `PartiallyHealed` and `NotHealed`. In addition, we would return `error` to indicate if the healing operation failed to due to other I/O related errors. Does this approach sound right?

**Comment by krisis** [comment] 2017-04-07 06:38
@deekoder I have updated admin-api docs in this PR - https://github.com/minio/minio/pull/4045/files#diff-b8edc1fe50490a19c5d5fd2849477ad9.

**Comment by krisis** [comment] 2017-04-07 06:39
This issue can be closed once `mc` uses these heal states to provide user with rich(er) information about a heal-object or heal-upload admin operation. Waiting on #4045 to be merged. The pkg/madmin changes need to be vendored in.

**Comment by harshavardhana** [comment] 2017-04-10 18:50
> This issue can be closed once mc uses these heal states to provide user with rich(er) information about a heal-object or heal-upload admin operation. Waiting on #4045 to be merged. The pkg/madmin changes need to be vendored in.

Can a `mc` issue be opened for this @krisis ?

**Comment by deekoder** [comment] 2017-04-11 16:52
PR pending.

**Comment by deekoder** [comment] 2017-04-11 16:53
@abperiasamy  needs to review the doc.

**Comment by krisis** [comment] 2017-04-17 13:44
@deekoder This issue can be closed. It is fixed by PR #4045 in minio repo and PR https://github.com/minio/mc/pull/2131 in mc repo.

**Closed as completed** 2017-04-17 16:19 UTC
Labels: fixed, priority: high
