### ISSUE TITLE
HTTP HEAD Request against a default presigned get url is not RFC conform

### ISSUE THREAD

**Issue by MontyGvMC** [minio/minio#6146] opened 2018-07-12 09:39 UTC
Generating a presigned get using the C# minio client (Minio.NetCore 1.1.1)

` 
  return await Client.PresignedGetObjectAsync(bucketname, key, 60000);
`

and deliver the presigned url to a (e.g. Angular 6) single page application.

## Expected Behavior

The single page application should now be able to do the GET request BUT ALSO an HTTP HEAD request. 

## Current Behavior

The current behaviour is that the GET request is allowed but the HEAD request fails with 403 Forbidden.

A way to do this is described in #4746 and seems to be fixed in #4784  .
But the described way in #4746 looks like it would be necessary to explicitly set the http verb to HEAD. Wouldn't that prevent the GET call?

Is it possible to allow both: GET and HEAD by default?

Please correct me if I understood something completly wrong.
Should that already work since #4784?

## Possible Solution

Implement default access rights for HEAD if a presigned GET url is generated.

## Steps to Reproduce (for bugs)

1. create a presigned url
2. deliver it to an Angular 6 SPA application
3. try http.head() and http.get() of angular against the presigned get url
4. experience different results

## Context

The context for this problem is using a presigned GET url to check if a file exists on a minio server by making an HTTP conform HEAD request.

It could be used in a case where a javascript SPA tries to check if the file under the presigned url exists or not. 

In our dedicated case we would use that method to ask minio directly if it has the file for the (short) time between a SPA client uploaded a file and the event notification takes it's way through Minio -> RabbitMQ -> background service -> DB -> Web API -> client SPA (polling the web API).

**Comment by aead** [comment] 2018-07-12 12:05
> Is it possible to allow both: GET and HEAD by default?

No this is not possible since this is not S3 compliant. If you create a presigned URL for a GET request the method (GET, HEAD, PUT) is part of the "signature" / MAC. Changing the method causes the "signature" verification to fail. If you try the *Steps to Reproduce* against AWS it also denies the request.

**Comment by nitisht** [comment] 2018-07-13 07:15
@MontyGvMC Closing this issue as explained by @aead we won't be able to make the changes you asked for - it is not S3 compatible. Feel free to get back if there are further questions.

**Closed as completed by nitisht** 2018-07-13 07:15 UTC
Labels: out of scope, priority: medium
