### ISSUE TITLE
Error when upgrading into mc client 2021

### ISSUE THREAD

**Issue by vsudonet** [minio/minio#12304] opened 2021-05-17 07:42 UTC
## Expected Behavior

Transfer tar gzip file into pipe mc. The previous mc version is ok when I use pipe to transfer compress file.

## Current Behavior

root@host-243:/tmp# tar -zcf  test-minio | /mc pipe backup/bucket/test.tar.gz --debug
tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.
mc: <ERROR> Unable to parse --attr value: specified metadata should be of form key1=value1;key2=value2;... and so on
 (1) pipe-main.go:139 cmd.mainPipe(..) Tags: []
 (0) cp-main_contrib.go:69 cmd.getMetaDataEntry(..)
 Release-Tag:RELEASE.2021-05-12T03-10-11Z | Commit:7d142be7111b | Host:host-243 | OS:linux | Arch:amd64 | Lang:go1.16.3 | Mem:2.9 MB/75 MB | Heap:2.9 MB/67 MB.

## Steps to Reproduce (for bugs)

1. Folder test-minio
2. tar -zcf  test-minio | /mc pipe backup/vfile-keystone-db/test.tar.gz

## Your Environment

Ubuntu 18.04
mc client 2021

**Comment by harshavardhana** [comment] 2021-05-17 07:43
This is fixed in master 60d3646baf17cec7c35741d7dfccc1ffedf0f182 - duplicate of #3718 - use `--attr` as a workaround for now or build from source.

**Closed as completed by harshavardhana** 2021-05-17 07:43 UTC
Labels: duplicate, community, fixed
