### ISSUE TITLE
Uploading a file of around 1 GB results in an error

### ISSUE THREAD

**Issue by mayurjain0312** [minio/minio#3445] opened 2016-12-13 22:24 UTC
I am getting the following exception:
Traceback (most recent call last):
  File "minio-s3.py", line 117, in <module>
    main()
  File "minio-s3.py", line 43, in main
    ExtraArgs={"Metadata": {"mayurjmetakey": "mayurjmetavalue"}})
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 144, in bucket_upload_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 105, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 253, in upload_file
    filename, '/'.join([bucket, key]), e))
boto3.exceptions.S3UploadFailedError: Failed to upload /local/mnt/workspace/mayurj/teststuff/Videos.zip to test/Videos.zip: An error occurred (NoSuchUpload) when calling the CompleteMultipartUpload operation: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.

https://gist.github.com/mayurjain0312/502a18d655b32df6dc905ac939cd0b29

**Comment by krishnasrinivas** [comment] 2016-12-13 23:29
@mayurjain0312  do you run multiple minio-s3.py in parallel?

**Comment by mayurjain0312** [comment] 2016-12-14 02:04
no

**Comment by harshavardhana** [comment] 2016-12-14 18:23
have you been able to test with the NFS options i requested @mayurjain0312 yesterday?

**Comment by mayurjain0312** [comment] 2016-12-14 18:47
I found the behavior to be very inconsistent. Without making any changes, I tried uploading the 1.7 gb file again and it got uploaded without any exceptions. 
But then, I tried uploading 4 gb file, it resulted in the same exception as mentioned above. and after few re-runs, it succeeded. 

Also, I wanted to add that I am getting a lot of log errors on the minio console:

RRO[8479] Unable to write to client.                    cause=write tcp 129.46.71.250:9000->129.46.71.250:53082: write: connection reset by peer source=[object-handlers.go:164:objectAPIHandlers.GetObjectHandler()] stack=fs-v1.go:275:fsObjects.GetObject <autogenerated>:192:(*fsObjects).GetObject object-handlers.go:163:objectAPIHandlers.GetObjectHandler api-router.go:54:(objectAPIHandlers).GetObjectHandler-fm
ERRO[8777] Unable to write to client.                    cause=write tcp 129.46.71.250:9000->129.46.71.250:53245: write: connection reset by peer source=[object-handlers.go:164:objectAPIHandlers.GetObjectHandler()] stack=fs-v1.go:275:fsObjects.GetObject <autogenerated>:192:(*fsObjects).GetObject object-handlers.go:163:objectAPIHandlers.GetObjectHandler api-router.go:54:(objectAPIHandlers).GetObjectHandler-fm
ERRO[8778] Unable to write to client.                    cause=write tcp 129.46.71.250:9000->129.46.71.250:53251: write: connection reset by peer source=[object-handlers.go:164:objectAPIHandlers.GetObjectHandler()] stack=fs-v1.go:275:fsObjects.GetObject <autogenerated>:192:(*fsObjects).GetObject object-handlers.go:163:objectAPIHandlers.GetObjectHandler api-router.go:54:(objectAPIHandlers).GetObjectHandler-fm
ERRO[8778] Unable to write to client.                    cause=write tcp 129.46.71.250:9000->129.46.71.250:53247: write: connection reset by peer source=[object-handlers.go:164:objectAPIHandlers.GetObjectHandler()] stack=fs-v1.go:275:fsObjects.GetObject <autogenerated>:192:(*fsObjects).GetObject object-handlers.go:163:objectAPIHandlers.GetObjectHandler api-router.go:54:(objectAPIHandlers).GetObjectHandler-fm
ERRO[8778] Unable to write to client.                    cause=write tcp 129.46.71.250:9000->129.46.71.250:53246: write: connection reset by peer source=[object-handlers.go:164:objectAPIHandlers.GetObjectHandler()] stack=fs-v1.go:275:fsObjects.GetObject <autogenerated>:192:(*fsObjects).GetObject object-handlers.go:163:objectAPIHandlers.GetObjectHandler api-router.go:54:(objectAPIHandlers).GetObjectHandler-fm
ERRO[8778] Unable to write to client.                    cause=write tcp 129.46.71.250:9000->129.46.

Not sure, if it is related. But I thought it might help.
Minio version:  2016-12-12T23:44:33Z

**Comment by harshavardhana** [comment] 2016-12-14 19:14
This is because client closed the connection @mayurjain0312 - another thing to try is remount `nfs` with "-o sync" 

```
mount -osync <ip>:/<share> /<mount_point>
```

```
localhost:/tmp/nfs on /tmp/mount type nfs4 (rw,relatime,sync,vers=4.0,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=127.0.0.1,local_lock=none,addr=127.0.0.1)
```

**Comment by harshavardhana** [comment] 2016-12-20 10:07
Closing this bug as not reproducible @mayurjain0312 - please open a new github issue if seen again.

**Closed as completed by harshavardhana** 2016-12-20 10:07 UTC
Labels: community
