### ISSUE TITLE
After updating the version, minio will automatically delete the bucket.

### ISSUE THREAD

**Issue by A-BenMao** [minio/minio#18817] opened 2024-01-18 02:28 UTC
## NOTE
After updating the version, minio will automatically delete the bucket.

## Current Behavior
Before upgrading to the new version, I had bucket A. After upgrading to the new version, the minio log would keep refreshing：Attempts to delete bucket A failed.
```
minio[4127911]: API: SYSTEM()
minio[4127911]: Time: 02:01:10 UTC 01/18/2024
minio[4127911]: DeploymentID: a57e5509-5302-411f-a895-8aa3e9418b7c
minio[4127911]: Error: While deleting dangling Bucket (conquerorsblade), Drive 10.10.208.1:9000:/data/minio-sd14 returned an error (volume is not empty) (*fmt.wrapError)
minio[4127911]:       4: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
minio[4127911]:       3: internal/logger/logonce.go:149:logger.LogOnceIf()
minio[4127911]:       2: cmd/peer-s3-server.go:169:cmd.healBucketLocal.func2()
minio[4127911]:       1: github.com/minio/pkg/v2@v2.0.8/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
```
## Possible Solution
It may be that the configurations between versions are incompatible

## Steps to Reproduce (for bugs)
1. Old version: 2023-09-20T22_49_55Z
2. New version: 2024-01-13T07_53_03Z

## Context
```
minio[4127911]: API: SYSTEM()
minio[4127911]: Time: 02:01:10 UTC 01/18/2024
minio[4127911]: DeploymentID: a57e5509-5302-411f-a895-8aa3e9418b7c
minio[4127911]: Error: While deleting dangling Bucket (conquerorsblade), Drive 10.10.208.1:9000:/data/minio-sd14 returned an error (volume is not empty) (*fmt.wrapError)
minio[4127911]:       4: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
minio[4127911]:       3: internal/logger/logonce.go:149:logger.LogOnceIf()
minio[4127911]:       2: cmd/peer-s3-server.go:169:cmd.healBucketLocal.func2()
minio[4127911]:       1: github.com/minio/pkg/v2@v2.0.8/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
```

## Your Environment

* Version used (`minio --version`):
minio version RELEASE.2024-01-13T07-53-03Z (commit-id=993d96feef0e6b93d963932a66e2a50d3157575e)
Runtime: go1.21.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
* Server setup and configuration:
`MINIO_VOLUMES="http://10.10.208.{1...5}:9000/data/minio-sd{1...16}"

MINIO_OPTS="--console-address :80"

MINIO_ROOT_USER=minioadmin

MINIO_SERVER_URL="http://minio.AAAA.com:9000"

MINIO_CONFIG_ENV_FILE=/etc/default/minio

MINIO_ERASURE_SET_DRIVE_COUNT=5

MINIO_STORAGE_CLASS_STANDARD="EC:2"

MINIO_STORAGE_CLASS_RRS="EC:2"

MINIO_STORAGE_CLASS_COMMENT="all class is ec:2"

MINIO_PROMETHEUS_AUTH_TYPE="public"

MINIO_BROWSER_REDIRECT_URL="http://console.minio.AAAA.com"

MINIO_PROMETHEUS_URL="http://10.10.209.38:9090"

MINIO_PROMETHEUS_JOB_ID="minio-cluster"

MINIO_UPDATE='off'

MINIO_NOTIFY_MYSQL_ENABLE="on"

MINIO_NOTIFY_MYSQL_DSN_STRING="root:abcd@1234@tcp(10.10.208.5:3306)/miniodb"

MINIO_NOTIFY_MYSQL_TABLE="event"

MINIO_NOTIFY_MYSQL_FORMAT="access"

MINIO_NOTIFY_MYSQL_MAX_OPEN_CONNECTIONS=5

MINIO_NOTIFY_MYSQL_QUEUE_DIR="/home/events"

MINIO_NOTIFY_MYSQL_QUEUE_LIMIT=100000

MINIO_NOTIFY_MYSQL_COMMENT="object event notify"

MINIO_API_REQUESTS_DEADLINE='20s'

MINIO_BROWSER_LOGIN_ANIMATION='off'

MINIO_BROWSER_SESSION_DURATION='24h'

MINIO_DOMAIN="minio.AAAA.com"
`
* Operating System and version (`uname -a`):
Linux bm-hz-stable-minio1 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2024-01-18 04:32
Yeah this happens for empty buckets, non empty buckets are never deleted however it attempts periodically causing the flood of logs.

Duplicate of #18809

Fixed via #18815

**Closed as completed by harshavardhana** 2024-01-18 04:32 UTC
Labels: community, triage
