### ISSUE TITLE
How to using HTTPS for distributed mode?

### ISSUE THREAD

**Issue by alphaqiu** [minio/minio#4436] opened 2017-05-26 07:57 UTC
Sorry about open a issue about how to using HTTPS for distributed mode.

Im trying generate the private.key and public.crt, but, when starting all nodes, the all waiting for another. So it cause all nodes waiting and waiting. Please help me to guide how to do that with HTTPS. thanks.

**Comment by vadmeste** [comment] 2017-05-26 10:07
@alphaqiu, I think there is a missing error message that is not shown in your case. 

If you generated self-signed certificates, then you will need to put all generated public certificates (public.crt) in .minio/certs/CAs/ directory of all nodes.

Keep us updated.

**Comment by alphaqiu** [comment] 2017-05-26 10:52
It`s working now! 
I reviewed the doc and found it!

> Minio can be configured to connect to other servers, whether Minio nodes or servers like NATs, Redis. If these servers use certificates that are not registered in one of the known certificates authorities, you can make Minio server trust these CAs by dropping these certificates under Minio config path (~/.minio/certs/CAs/ 

Thank you @vadmeste :)

```
private.key
public.crt
CAs/public.crt
```

**Comment by alphaqiu** [comment] 2017-05-26 11:00
@vadmeste And how can i scale out a node dynamiclly? It looks like no way to do that. So when a tenant setuped, it just can be increase physical disk space e.g. lvm. Do i understand this right?

**Comment by vadmeste** [comment] 2017-05-26 11:05
yes @alphaqiu, that's right.

**Comment by vadmeste** [comment] 2017-05-26 17:10
@harshavardhana, this one is duplicated to https://github.com/minio/minio/issues/4408

**Comment by harshavardhana** [comment] 2017-05-26 17:17
Closing as duplicate of #4408 . The error message to be printed when server is not configured properly.

**Closed as completed by harshavardhana** 2017-05-26 17:17 UTC
Labels: duplicate, priority: low
