### ISSUE TITLE
Fallocate failed with zfs on ubuntu

### ISSUE THREAD

**Issue by RaveNoX** [minio/minio#6231] opened 2018-08-02 00:46 UTC
When using zfs on ubuntu there's error on uploading files or other operations which uses fallocate because zfs not support this operation.

Minio running in docker with mounted data path from zfs pool

## Expected Behavior
Files must upload normally with zfs on ubuntu (or any other linux with zfs support)

## Current Behavior
Got error on fallocate here: https://github.com/minio/minio/blob/master/cmd/fallocate_linux.go
Which handled and logged here: https://github.com/minio/minio/blob/master/cmd/fs-v1-helpers.go#L337

In logs it looks like:
```
API: SYSTEM()
Time: 00:28:50 UTC 08/02/2018
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/fs-v1-helpers.go:337:cmd.fsCreateFile()
       2: cmd/fs-v1.go:870:cmd.(*FSObjects).putObject()
       3: cmd/fs-v1.go:780:cmd.(*FSObjects).PutObject()
       4: cmd/object-handlers.go:732:cmd.(ObjectLayer).PutObject-fm()
       5: cmd/web-handlers.go:651:cmd.(*webAPIHandlers).Upload()

API: SYSTEM()
Time: 00:28:50 UTC 08/02/2018
Error: Unexpected error, please report this issue at https://github.com/minio/minio/issues
       1: cmd/web-handlers.go:1196:cmd.toWebAPIError()
       2: cmd/web-handlers.go:1206:cmd.writeWebErrorResponse()
       3: cmd/web-handlers.go:653:cmd.(*webAPIHandlers).Upload()
```

## Possible Solution
1. Remove fallocate (bad idea)
2. Add flag to disable fallocate to config and evniroiment variables (possible option)
3. Extend error handling here:  https://github.com/minio/minio/blob/master/cmd/fs-v1-helpers.go#L337 
and/or here: https://github.com/minio/minio/blob/master/cmd/posix-errors.go#L37 

I'll try to produce pr for 3 option soon.

## Steps to Reproduce (for bugs)
1. Install ubuntu 18.04
2. Install zfs support, create pool
3. Run minio with data path on zfs
4. Try upload file to bucket

## Context
I just want to run minio on linux + zfs

## Your Environment
* Version used (`minio version`): 2018-07-31T02:11:47Z

**Comment by kannappanr** [comment] 2018-08-02 05:13
Duplicate of #6223 . Fix has already been merged into master. Will make a release hopefully tomorrow.

**Closed as completed by kannappanr** 2018-08-02 05:13 UTC
Labels: duplicate, community, regression, priority: medium
