### ISSUE TITLE
Intermittent error: NoSuchBucket

### ISSUE THREAD

**Issue by danilhisamov** [minio/minio#17781] opened 2023-08-02 08:51 UTC
Hi! I faced an intermittent error during repeated test. Some tests are failing with message:
```
ErrorResponse(code = NoSuchBucket, message = The specified bucket does not exist, bucketName = my-bucket, objectName = null, resource = /my-bucket, requestId = 177781C3489A228C, hostId = dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8)
request={method=GET, url=http://localhost:53617/my-bucket?location=, headers=Host: localhost:53617
```

Another interesting thing is that in test class I have written 2 tests which should do the same thing, but they are implemented in different reactive ways. One of them passes repeated invocation (_testSuccess_), another doesn't (_testFail_). In _testFail_ reactive pipeline If I do the double check of bucket existence, in case of failed test it will show:
```
bucket exists: false
create bucket: response 200 OK
bucket exists: false
```

## Expected Behavior
All repeated tests should pass successfully.

## Current Behavior
From time to time, amount of the failed tests is different. In average its 3-5 / 20. The first one from the 20 repeated tests is failing most of the time.

## Steps to Reproduce (for bugs)
I have written a [demo service](https://github.com/danilhisamov/minio_webflux) using Spring Webflux + Minio (async client) + testcontainers to demonstrate.

1. clone project
2. run ./gradlew test in the project root directory

[webfluxminio-app.log](https://github.com/minio/minio/files/12238462/webfluxminio-app.log)
[webfluxminio-minio.log](https://github.com/minio/minio/files/12238464/webfluxminio-minio.log)

## Context
I am trying to upload a file to the Minio using minio-java async client. If bucket doesn't exist, I am trying to create it before the upload.

I have opened an [issue](https://github.com/minio/minio-java/issues/1479) on minio-java firstly, but they said to look for the answers on a S3 server side.

## Your Environment
* Version used (`minio --version`):
minio container - minio/minio:RELEASE.2023-07-18T17-49-40Z. Reproducible at latest tag as well
java client - io.minio:minio:8.5.4
* Server setup and configuration:
Docker Desktop 4.16.2 (95914)
Server Version: 20.10.22
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 1985 MB
* Operating System and version (`uname -a`):
Darwin MacBook-Pro 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64

**Comment by vadmeste** [comment] 2023-08-02 08:57
@danilhisamov there is no sufficient information to reproduce. For now, can you just run `mc admin trace <alias>` and check if the make bucket really reached the cluster ?

**Comment by klauspost** [comment] 2023-08-02 09:11
FWIW This release is *before* https://github.com/minio/minio/pull/17719 and https://github.com/minio/minio/pull/17742 - so it can't be a regression from either of those.

**Comment by danilhisamov** [comment] 2023-08-02 09:33
@vadmeste, I have updated description, added logs from app and minio. It seems that make bucket request reached the cluster right before the end [PUT /my-bucket] (correct me if I am wrong). But app test failed with the same error as in the description

**Comment by clayly** [comment] 2023-08-02 13:55
> @danilhisamov there is no sufficient information to reproduce. For now, can you just run `mc admin trace <alias>` and check if the make bucket really reached the cluster ?

I'm also facing this issue. Is there maybe some caching problem, when bucket or file creation command not executed immediately? Maybe there is some setting which makes sure that command is executed and applied to file system? Looks like problem happens only on certain machines.

**Comment by harshavardhana** [comment] 2023-08-02 21:48
> @vadmeste, I have updated description, added logs from app and minio. It seems that make bucket request reached the cluster right before the end [PUT /my-bucket] (correct me if I am wrong). But app test failed with the same error as in the description

PUT reached after the GET on the bucket so the operation failed correctly. Does you bucket exist prior?

> > @danilhisamov there is no sufficient information to reproduce. For now, can you just run `mc admin trace <alias>` and check if the make bucket really reached the cluster ?
> 
> I'm also facing this issue. Is there maybe some caching problem, when bucket or file creation command not executed immediately? Maybe there is some setting which makes sure that command is executed and applied to file system? Looks like problem happens only on certain machines.

No there is no such caching MakeBucket is like `mkdir` it looks like some kind of a underlying file system issue here.

**Comment by harshavardhana** [comment] 2023-08-02 21:49
```
localhost:53617 [REQUEST s3.GetBucketLocation] [2023-08-02T12:09:39.569] [Client IP: 172.17.0.1]
localhost:53617 [REQUEST s3.GetBucketLocation] [2023-08-02T12:09:39.570] [Client IP: 172.17.0.1]
localhost:53617 [REQUEST s3.GetBucketLocation] [2023-08-02T12:09:39.792] [Client IP: 172.17.0.1]
localhost:53617 [REQUEST s3.PutBucket] [2023-08-02T12:09:39.810] [Client IP: 172.17.0.1]
```

If you see the PUT arrived at the cluster almost a 100ms later than GET request.

**Comment by danilhisamov** [comment] 2023-08-03 06:31
> > @vadmeste, I have updated description, added logs from app and minio. It seems that make bucket request reached the cluster right before the end [PUT /my-bucket] (correct me if I am wrong). But app test failed with the same error as in the description
> 
> PUT reached after the GET on the bucket so the operation failed correctly. Does you bucket exist prior?

No, bucket doesn't exist before the test. Each test creates bucket, puts object into it, removes object, removes bucket.

**Comment by harshavardhana** [comment] 2023-08-03 06:55
Yeah, it doesn't look like anything is wrong here. PUT arrived before the GetBucketLocation() arrived. 

It almost looks like you are trying to create a bucket concurrent to object creation and they are not ordered correctly.

The code is written with some async behavior in mind, not sure how the order is maintained here. Can you write non-async style @danilhisamov and see if it's reproducible?

**Comment by danilhisamov** [comment] 2023-08-03 07:21
> Yeah, it doesn't look like anything is wrong here. PUT arrived before the GetBucketLocation() arrived.

Do you mean the opposite thing? PUT arrived after GetBucketLocation?

```
localhost:53617 [REQUEST s3.GetBucketLocation] [2023-08-02T12:09:39.569] [Client IP: 172.17.0.1]
localhost:53617 [REQUEST s3.GetBucketLocation] [2023-08-02T12:09:39.570] [Client IP: 172.17.0.1]
localhost:53617 [REQUEST s3.GetBucketLocation] [2023-08-02T12:09:39.792] [Client IP: 172.17.0.1]
localhost:53617 [REQUEST s3.PutBucket] [2023-08-02T12:09:39.810] [Client IP: 172.17.0.1]
```

> The code is written with some async behavior in mind, not sure how the order is maintained here. Can you write non-async style @danilhisamov and see if it's reproducible?

Even with async approach, there is another test, which uses different java..Mono methods and works fine. Looks like that from the Minio server side everything works as expected and I need to investigate the client side

**Comment by harshavardhana** [comment] 2023-08-03 15:03
> Do you mean the opposite thing? PUT arrived after GetBucketLocation?

Yes my bad, it is after. I will close this since it's not a server issue at this point.

**Closed as completed by harshavardhana** 2023-08-03 15:03 UTC
Labels: working as intended, community
