### ISSUE TITLE
[distributed] upload of 30gb fails in the middle of transfer

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2523] opened 2016-08-22 14:22 UTC
```
minio@minio1:~/vadmeste/work/bigfiles$ mc mb myvadmeste1/testbucket
Bucket created successfully ‘myvadmeste1/testbucket’.
minio@minio1:~/vadmeste/work/bigfiles$ mc cp 30gb.bin myvadmeste1/testbucket/
mc: <ERROR> Failed to copy ‘30gb.bin’. Bucket ‘testbucket’ does not exist.
30gb.bin:                      22.25 GB / 30.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░┃  74.17% 12.68 MB/s 29m56s
minio@minio1:~/vadmeste/work/bigfiles$ 
```

Bucket `testbucket' does not exist is weird and doesn't appear in the beginning of the transfer.

**Comment by krishnasrinivas** [comment] 2016-08-22 14:35
must be same as https://github.com/minio/minio/issues/2522

**Comment by harshavardhana** [comment] 2016-08-22 17:52
> must be same as #2522

They are multiple issues all are related.

**Comment by harshavardhana** [comment] 2016-08-22 17:54
> Bucket `testbucket' does not exist is weird and doesn't appear in the beginning of the transfer.

Closing this a duplicate of https://github.com/minio/minio/issues/2501

**Closed as completed by harshavardhana** 2016-08-22 17:54 UTC
