### ISSUE TITLE
Dragondisk GUI client is not compatible with minio

### ISSUE THREAD

**Issue by ngelik** [minio/minio#1906] opened 2016-06-15 13:03 UTC
## Expected behaviour

Dragondisk can connect to Minio and list all buckets
## Actual behaviour

Get 400 Bad Request in Dragondisk
## Steps to reproduce the behaviour

Up Minio server
`{
        "version": "4",
        "credential": {
                "accessKey": "some_key",
                "secretKey": "some_sec_key"
        },
        "region": "us-east-1",
        "logger": {
                "console": {
                        "enable": false,
                        "level": "fatal"
                },
                "file": {
                        "enable": true,
                        "fileName": "/minio/minio.log",
                        "level": "debug"
                },
                "syslog": {
                        "enable": false,
                        "address": "",
                        "level": ""
                }
        }
}
`
Setup Dragondisk
## Minio version

Release-Tag: RELEASE.2016-06-03T19-32-05Z
Commit-ID: 73ddb5be758566dde18b519393c7554ae280b074
## System information

Ubuntu 14.04
DragonDisk 1.05 Revision 565

**Comment by koolhead17** [comment] 2016-06-15 18:14
Thanks @ngelik for reporting, let me reproduce it on my end. 😄

**Comment by koolhead17** [comment] 2016-06-16 20:04
@ngelik I am having same error at my side. I have written a email via their website asking if they have implemented signature version 4 of AWS S3, assuring then we could help and work  with them in supporting Minio. Also if you know the developers personally, bring them to our Gitter channel will be happy to help. :)

**Comment by koolhead17** [comment] 2016-06-16 20:50
@ngelik just got reply of my email from the developer, current release does not support V4 signature of AWS S3. He is coming up with updated release by July which will support AWS s3 V4. Once it is out you can run minio server with dragondisk.

I hope it helps. :)

**Comment by AmitM30** [comment] 2016-12-27 07:16
is this resolved? I am using windows and am facing the same issue for a new bucket on S3 that only supports v4.

**Comment by sascha-coenen** [comment] 2017-08-22 15:14
dragondisk hasn't received an update since 2012 (v1.05). Am I missing something? Is the developer continuing the project under a different website? 
http://www.s3-client.com/download-s3-compatible-cloud-client.html
I have the latest version installed and it doesn't work with minio. My dragondisk help dialog shows that version 1.05 was released in 2012

**Comment by vadmeste** [comment] 2017-08-22 15:19
@sascha-coenen, Minio wasn't supporting AWS S3 V2 when this issue was created but it does now. Maybe we want to test this again now but it seems you already did, could you paste us what is the error that you are seeing ?

**Comment by sascha-coenen** [comment] 2017-08-23 03:12
@vadmeste thanks for the info and the quick response. When I connect dragondisk to a minio server, I do see the buckets in dragondisk, but when clicking on a bucket to get to the files, the file list remains empty. In the minio web interface I do see files. Same goes for copying files over. If I copy a local file to a minio bucket using dragondisk, the operation allegedly succeeds but the filelist remains empty. Minio's web interface also doesn't show the file.
To give a little context to my setup: I am playing around with kubernetes (minikube) on my notebook and wanted to deploy a complete architecture landscape on it. I didn't want the kubernetes deployment to have any external dependencies, so I intended to use minio to impersonate S3. 
I copied the dockerfile and entrypoint shell script from the master branch and built a local docker image. (I'm not prone to NIH, just for the sake of the learning experience..) Then I deployed the minio server in standalone mode on Kubernetes as a Stateful Set and defined an Ingress along with entries in the /etc/hosts file to resolve the minion DNS name in Kubernetes and the subdomains for the test buckets I created.

There is a chance that things don't work due to a bug in my setup. But when I read the initial issue thread, I knew that the problem was elsewhere. With what you wrote above, I would assume that having built the docker image from the minio master branch yesterday, to my understanding, I should have a minio version with S3 V2 support, or do I need to take to Dockerfile.release file or some other branch?
If in fact I do have the V2 support in, then maybe there's something wrong on my end...

**Comment by vadmeste** [comment] 2017-11-30 18:31
Closing the issue due to inactivity but it can be reopened again and develop further discussions.

**Closed as completed by vadmeste** 2017-11-30 18:31 UTC
Labels: working as intended, priority: medium

**Comment by zefie** [comment] 2019-01-21 13:37
Just an update. I know DragonDisk is discontinued, but it works on Minio ONLY when using a proxy.

If I connect DragonDisk to my Minio install while Minio is running on 443 with SSL, it fails. (eg  https://domain.com/ goes direct to Minio)

If I run an nginx proxy with SSL on 443 in front of Minio (now on alt port), DragonDisk can operate fine (though once in a while it will complain about signature not matching).

To be fair, DragonDisk probably has some terrible code. I just tried to "Move" a file and it deleted it from the local disk before uploading it then complained it couldn't find the file. Gee, I wonder why. LOL.
