### ISSUE TITLE
deleting a bucket with >500 files results in an error

### ISSUE THREAD

**Issue by cgrabmann** [minio/minio#4770] opened 2017-08-04 13:39 UTC
## Problem
While trying to reproduce (locally) another problem I currently have, I stumbled on this one:

I create a bucket with more then 500 files and when I recursively delete the bucket through the minio-java-client or the minio-client the following errors occur.

#### Server-Error:
```
time="2017-08-04T12:15:48Z" level=error msg="Unable to delete a bucket." cause="remove /export/.minio.sys/buckets/bucket8: directory not empty" source="[bucket-handlers.go:648:objectAPIHandlers.DeleteBucketHandler()]" stack="fs-v1-helpers.go:65:fsRemoveAll fs-v1.go:303:fsObjects.DeleteBucket <autogenerated>:394:(*fsObjects).DeleteBucket bucket-handlers.go:647:objectAPIHandlers.DeleteBucketHandler api-router.go:95:(objectAPIHandlers).DeleteBucketHandler-fm"
```

#### Client-Error:
```
mc: <ERROR> Failed to remove `local\bucket1` recursively. The specified bucket does not exist
```

#### Java-Client-Exception:
```
error occured
ErrorResponse(code=InternalError, message=We encountered an internal error, please try again., bucketName=null, objectName=null, resource=/bucket0, requestId=3L137, hostId=3L137)
request={method=DELETE, url=http://localhost:9100/bucket0, headers=Host: localhost:9100
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20170804T123811Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170804/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=500, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2017-07-24T18-27-35Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14D7A4E217C15F90
Date: Fri, 04 Aug 2017 12:38:11 GMT
Transfer-Encoding: chunked
}

 at io.minio.MinioClient.execute(MinioClient.java:1096)
 at io.minio.MinioClient.executeDelete(MinioClient.java:1222)
 at io.minio.MinioClient.removeBucket(MinioClient.java:2890)
 at at.schenker.taf.manager.web.api.minioTestDeleteFile.deleteOldBuckets(minioTestDeleteFile.java:57)
 at at.schenker.taf.manager.web.api.minioTestDeleteFile.main(minioTestDeleteFile.java:30)
```
	
Every time this errors were observed the folder of the bucket was deleted on the drive, but inside the ".minio.sys/buckets" folder, a folder for that bucket still existed with a few 100 empty folders left.

#### Used setup:
```
Docker for Windows
minio docker container (minio/minio:latest | 634f57bbebf4)
mounted volumes:
	minio-config:/etc/minio
	minio-data:/export
```

#### minio client:
```
Version: 2017-06-15T03:38:43Z
Release-tag: RELEASE.2017-06-15T03-38-43Z
Commit-id: c32b1ea48b651125e33015ea0d1596cb377685a4
```

#### minio java client:
```
'io.minio:minio:3.0.5'
```

**Comment by vadmeste** [comment] 2017-08-04 14:14
@cgrabmann hey,

So you ran Minio linux docker image under Windows, mounted a directory from your local Windows and encountered this issue, right?

By the way, we have a Windows binary of Minio server (https://minio.io/downloads/#minio-server), simple to download and use, Could you test again with it ?

(you can run this `minio.exe -C c:\path\to\minio-config\ server c:\path\to\minio-data\` )

**Comment by harshavardhana** [comment] 2017-08-05 08:10
We will look into this issue @cgrabmann . Do you have anymore further information regarding the issue? 

- Can you provide us the console log for Minio? 
- Any sample directory spread that reproduced it? - is it consistently reproducible? 
- Can you please share the minio-java example code that was used to reproduce this?

**Comment by cgrabmann** [comment] 2017-08-05 10:56
I will gather the infos on Monday when I'm back in the office.

**Comment by cgrabmann** [comment] 2017-08-07 08:12
This are the logs from a fresh docker container when executing the following 2 java classes once:
https://pastebin.com/dAkXrKC9

Java code to create the files:
```java
package testPackage;

import io.minio.MinioClient;

public class CreateMinioTestFiles {

    public static void main(String[] args) {
        try {
            MinioClient minio = new MinioClient("http://localhost:9100", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG");

            for (int i = 0; i < 2; ++i) {
                minio.makeBucket("bucket" + i);

                for (int j = 0; j < 1000; ++j) {
                    minio.putObject("bucket" + i, "file" + i + j + ".json", "file.json");
                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

java code to delete all buckets:
```java
package testPackage;

import com.google.common.collect.Lists;
import io.minio.MinioClient;
import io.minio.Result;
import io.minio.messages.Bucket;
import io.minio.messages.Item;

import java.util.List;
import java.util.stream.Collectors;

public class MinioDeleteBucket {

    public static void main(String[] args) {
        try {
            MinioClient minioClient = new MinioClient("http://localhost:9100", "Q3AM3UQ867SPQQA43P2F", "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG");

            List<String> bucketList = minioClient.listBuckets().stream()
                .map(Bucket::name)
                .collect(Collectors.toList());

            for (String bucket : bucketList) {

                List<Result<Item>> objects = Lists.newArrayList(minioClient.listObjects(bucket));

                for (Result<Item> object : objects) {
                    minioClient.removeObject(bucket, object.get().objectName());
                }

                System.out.println("Removing bucket:" + bucket);

                minioClient.removeBucket(bucket);

                System.out.println("Removed bucket:" + bucket);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
```

Here is the data directory after running the MinioDeleteBucket class:
[minio-data.zip](https://github.com/minio/minio/files/1204216/minio-data.zip)

With this it is consistently reproducible.

When running the minio.exe directly the problem does not occure, but this sadly is not an option for me because the whole project setup depends on docker.

**Comment by harshavardhana** [comment] 2017-08-07 08:50
Thanks @cgrabmann - we do not ship windows docker images how did you build one? are you using regular images released on `hub.docker.com` ? Can you provide following details?

- Docker version
- Windows version
- entire logs reported by minio server on the docker logs? other than the one already provided by you?
- Would you mind testing with the latest release as well? @cgrabmann ?

**Comment by cgrabmann** [comment] 2017-08-07 09:34
since docker for windows is the same as the normal docker but uses hyperv to virtualize a linux server where itself docker is running I use the regular images from `hub.docker.com`.

* Docker version 17.06.0-ce, build 02c1d87
* Windows 10 Pro (10.0.15063 Build 15063)
* I'm not sure which other logs you are looking for, since the logs of the docker daemon only contain information about the start and end of the container and the logs I provided are already pulled from the minio-docker container.
* I already test it again with the newest release pushed on `hub.docker.com` and minio-java-client version 3.0.6

**Comment by harshavardhana** [comment] 2017-08-07 16:46
Thanks @cgrabmann will validate and let you know.

**Comment by harshavardhana** [comment] 2017-08-08 18:02
Are you able to delete the files if you happen to restart the server @cgrabmann ? from what it looks like this is sort of a filesystem issue with hyper-v + docker end.  

I am not able to reproduce this with minio running on a local NTFS disk. Currently the error returned is not correct sending a PR for that instead.

**Comment by cgrabmann** [comment] 2017-08-09 06:36
The uploaded files do not exist after the deletion process only the folders in  .minio.sys are left over (also empty).

When I stop the container I can manually delete the left over directory. It also does not seem to hinder the minio server when I create the bucket again and but files into it. The only problem is the failing of deleting the bucket itself, since the folder in .minio.sys/bucketName is not emptied correctly.

**Comment by harshavardhana** [comment] 2017-08-09 06:41
> When I stop the container I can manually delete the left over directory. It also does not seem to hinder the minio server when I create the bucket again and but files into it. The only problem is the failing of deleting the bucket itself, since the folder in .minio.sys/bucketName is not emptied correctly.

Not manually directly going to backend - are you able to using DeleteBucket API and delete the bucket properly after a minio server restart? @cgrabmann . Can you also confirm this doesn't happen without docker?

**Comment by cgrabmann** [comment] 2017-08-09 14:04
I can confirm this does not happen without docker.

I'm not able to delete the bucket properly after restart because the bucket does not exist any more. The problem is the exception that happens while deleting the bucket.

It just does not fit together:
The bucket could not be deleted (exception), but it is actually gone because I cant access it anymore.

**Comment by harshavardhana** [comment] 2017-08-09 15:51
This is like an interaction issue docker with windows perhaps. Linux emulated POSIX translated calls to NTFS backend might not be doing the same thing as required by Minio.

We could perhaps open a docker issue and check with them. For now don't use docker on windows with minio. We will work on native docker build i.e based on nanoserver from windows which would be the right way to use it.

**Comment by deekoder** [comment] 2017-08-16 23:53
Ok going ahead an closing this as its not actionable to us to fix.

**Closed as completed by deekoder** 2017-08-16 23:53 UTC
Labels: out of scope, priority: high, triage
