### ISSUE TITLE
Question: How to create forever share file url? 

### ISSUE THREAD

**Issue by 4n70w4** [minio/minio#7506] opened 2019-04-10 10:16 UTC
Through the web interface and mc command, I can create only a maximum of 7 days.

I'm confused. I need permanent links to files.

I do not want to make the bucket public.
I don't want an unauthorized user to see a list of all files in bucket.
I do not want the files to be accessible by name.
I want the files to be accessible via a link with a random code.
I need the protection of file names from busting and downloading all files.

![image](https://user-images.githubusercontent.com/38257723/55869149-9bddd180-5b8e-11e9-9e89-5906c54c9ecd.png)

![image](https://user-images.githubusercontent.com/38257723/55869225-c92a7f80-5b8e-11e9-91ab-34a302a97ce2.png)

Similar issue: https://github.com/minio/minio/issues/5180
but similar problems are not solved in it.

**Comment by nitisht** [comment] 2019-04-10 10:21
S3 API limits the presigned URL expiration to 7 days max, ref: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

So it is not possible to create a URL with permanent link.

Closing this issue as working as intended

**Closed as completed by nitisht** 2019-04-10 10:21 UTC
Labels: working as intended

**Comment by 4n70w4** [comment] 2019-04-10 11:53
@nitisht I'm happy for you, what you did as intended.
But it does not solve problems and creates unnecessary restrictions.

I would like to be able to configure the system to fit my needs.

Aggressively closing issues is not polite. Dislike for you.

**Comment by nitisht** [comment] 2019-04-10 12:13
> But it does not solve problems and creates unnecessary restrictions.

S3 compatibility is one of the main goals of MinIO and this behaviour you're expecting is not S3 compatible. Unfortunately I don't think there is much we can do here. 

> Aggressively closing issues is not polite. Dislike for you.

Please accept my sincere apologies, my intention was not to offend you. I closed the issue because this  has been discussed earlier, and MinIO stance about such behaviour not compatible has been conveyed.
