### ISSUE TITLE
S3 Gateway: minio/mc behavior without ListAllMyBuckets permission

### ISSUE THREAD

**Issue by stokowski** [minio/minio#7696] opened 2019-05-27 11:50 UTC
Minio in s3 gateway mode starts, but also returns error when aws user hasn't got ListAllMyBuckets permission:

```
API: SYSTEM()
Time: 11:30:07 UTC 05/27/2019
Error: Prefix access is denied: /
       2: cmd/policy.go:101:cmd.(*PolicySys).refresh()
       1: cmd/policy.go:163:cmd.(*PolicySys).Init()

```

Permission that allows to list all buckets, with that minio s3 gw start without error

```
{
      "Effect": "Allow",
      "Action": "s3:ListAllMyBuckets",
      "Resource": "arn:aws:s3:::*"
}

```

Without this its not possible to add gw host to minio client, but it works fine with other clients (rclone, cyberduck when pointed to proper bucket)

## Expected Behavior
Start without error and add gw host/proper bucket to minio client.

## Current Behavior
Starts with error, trying to refresh access to "/" every 5 mins, cannot connect via minio client.

## Possible Solution
Allow to attach minio gateway s3 to particular bucket or/and stop refreshing access on "/" every 5 mins and hide that in log and allow to add host/bucket to minio client.

## Steps to Reproduce (for bugs)
1. Create few buckets in s3
2. Create few IAM users
3. Attach policies where iam user has access to particular bucket, but don't allow to list all buckets
4. start minio in s3 gateway mode with aws credentials of iam user
5. Check logs, try to add gw host to minio client, try to use other clients (rclone, cyberduck etc)

## Context
I would like to have few buckets and few users, each user has access to only his own bucket. I want to hide the list of buckets that users don't own.

## Regression
Don't know.

## Your Environment
* Version used (`minio version`): RELEASE.2019-05-23T00-29-34Z

**Comment by nitisht** [comment] 2019-05-27 11:58
thanks for reporting we’ll take a look @stokowski

**Comment by harshavardhana** [comment] 2019-05-27 18:36
> Starts with error, trying to refresh access to "/" every 5 mins, cannot connect via minio client.

This is on purpose, what we need to do is avoid printing the error message if the bucket level is already provided. Also adding a bucket level gateway is quite easy to do as well.

It would be as good as providing `https://bucket.s3.amazonaws.com`

**Comment by lostdalek** [comment] 2019-05-29 13:57
Hi,
I have a similar use case with multiple users (admin and application roles) and different buckets usage, so every user can only access their buckets

@harshavardhana 

> Also adding a bucket level gateway is quite easy to do as well.
> It would be as good as providing https://bucket.s3.amazonaws.com

Can you clarify how to  add a bucket level gateway? wondering if it's an issue with my bucket restriction or minio

I tried the following minio commands without success:

**minio gateway s3**
result in: `Error: Prefix access is denied: /`
and doesn't allow me to browse accessible buckets in the webui

**minio gateway s3 https://MY_BUCKET_NAME.s3.amazonaws.com**
result in: `ERROR Unable to initialize gateway backend: Amazon S3 endpoint should be 's3.amazonaws.com'`

**minio gateway s3 https://MY_BUCKET_NAME.s3.us-east-2.amazonaws.com**
result in: `ERROR Unable to initialize gateway backend: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2'.`

running the following docker image:  `RELEASE.2019-05-23T00-29-34Z`
adding env variable `MINIO_REGION=us-east-2` without success

**Comment by thefiddler** [comment] 2019-05-31 13:26
@lostdalek according to @vadmeste you need to the s3:GetBucketLocation permission for bucket-specific minio gateway to work. Can you check if that resolves the issue for you?

Ref: https://github.com/minio/minio/issues/7709#issuecomment-497507729

**Comment by stokowski** [comment] 2019-06-05 20:52
> > Starts with error, trying to refresh access to "/" every 5 mins, cannot connect via minio client.
> 
> This is on purpose, what we need to do is avoid printing the error message if the bucket level is already provided. Also adding a bucket level gateway is quite easy to do as well.
> 
> It would be as good as providing `https://bucket.s3.amazonaws.com`

Sorry, now I get it - I thought that you will implement that in Minio, but I have tested that on example s3 bucket and indeed it works. I was getting failures because I was trying to bind minio gw to some s3-compatible vendor in the same way. So it looks that the problem is somewhere else.

**Comment by lostdalek** [comment] 2019-06-06 07:06
> @lostdalek according to @vadmeste you need to the s3:GetBucketLocation permission for bucket-specific minio gateway to work. Can you check if that resolves the issue for you?
> 
> Ref: [#7709 (comment)](https://github.com/minio/minio/issues/7709#issuecomment-497507729)

@thefiddler saddly it doesn't solve the issue for me, I'm unable to setup bucket level gateway, neither default gateway (same constraints as you -> env is setup by a third party )

**Comment by stokowski** [comment] 2019-06-06 13:19
So, I'm trying to run minio s3 gateway in top of Wasabi. My endpoint looks like:
`https://BUCKET.s3.wasabisys.com` where minio fails on start:

`{"level":"FATAL","time":"2019-06-06T13:15:14.986497495Z","error":{"message":"The specified key does not exist.","source":["cmd/gateway/s3/gateway-s3.go:134:s3.s3GatewayMain()"]}}`

It works when I won't add BUCKET name to the endpoint and use global url. Of course I don't have any problems when I'm using rclone with the same endpoint/creds setup.

I'm not sure, but this can be related to this part of code in `gateway-s3.go newS3 func`:

```
probeBucketName := randString(60, rand.NewSource(time.Now().UnixNano()), "probe-bucket-sign-")
	// Check if the provided keys are valid.
	if _, err = clnt.BucketExists(probeBucketName); err != nil {
		return nil, err
	}
```

**Comment by poornas** [comment] 2019-06-06 14:10
@stokowski, will be sending a fix shortly to allow virtual style endpoint, this is currently not allowed

**Comment by stokowski** [comment] 2019-06-06 17:17
ok, great

**Comment by harshavardhana** [comment] 2019-06-19 15:51
The fix was merged and released. Closing this issue - feel free to reopen if the issue is seen again.

**Closed as completed by harshavardhana** 2019-06-19 15:51 UTC
Labels: community, fixed, priority: medium
