### ISSUE TITLE
refresh file list when file uploads completed

### ISSUE THREAD

**Issue by esarakaitis** [minio/minio#2062] opened 2016-07-01 17:43 UTC
## Expected behavior

When upload completed, you should see the file in the list
## Actual behavior

You must manually refresh the file list
## Steps to reproduce the behavior

upload a file
## Minio version

Version: 2016-06-03T19:32:05Z
Release-Tag: RELEASE.2016-06-03T19-32-05Z
Commit-ID: 73ddb5be758566dde18b519393c7554ae280b074

**Comment by harshavardhana** [comment] 2016-07-01 21:56
// cc @krishnasrinivas we did fix this recently? - do you know the bug that was closed?

**Comment by krishnasrinivas** [comment] 2016-07-02 09:34
@esarakaitis were you using XL backend (i.e multiple export directories) or FS backend (single export)?

**Comment by esarakaitis** [comment] 2016-07-02 13:35
I was using XL. The exact commands I had posted on Gitter.

**Comment by harshavardhana** [comment] 2016-07-05 18:58
Moving this to "Standalone Release" milestone, its a blocker.

**Comment by krishnasrinivas** [comment] 2016-07-11 15:06
@esarakaitis I did this:

```
minio server xl-exports/disk1 xl-exports/disk2 xl-exports/disk3 xl-exports/disk4 xl-exports/disk5 xl-exports/disk6 xl-exports/disk7 xl-exports/disk8 xl-exports/disk9 xl-exports/disk10 xl-exports/disk11 xl-exports/disk12 xl-exports/disk13 xl-exports/disk14 xl-exports/disk15 xl-exports/disk16
```

And I was able to upload objects from the browser, and it worked fine.
What was the size of the object you were trying to upload? Was there anything else unusual? I could not find the command you used on Gitter (Search did not give relevant details) Is it possible for you to give any specific details that can help us reproduce this bug?

**Comment by harshavardhana** [comment] 2016-07-12 22:33
Moving this out of Standalone Release as we cannot reproduce this locally, moving to next milestone.

**Comment by esarakaitis** [comment] 2016-07-12 22:48
Sorry. Out of office.

**Comment by vadmeste** [comment] 2016-07-13 11:29
I am only having this when uploading an empty file

**Comment by harshavardhana** [comment] 2016-08-01 23:23
Closing as duplicate of #2327

**Closed as completed by harshavardhana** 2016-08-01 23:23 UTC
