### ISSUE TITLE
login fail  (original error -> (user_login.go:50: invalid Login))

### ISSUE THREAD

**Issue by pastel001** [minio/minio#12816] opened 2021-07-28 12:32 UTC
## Steps to Reproduce (for bugs)
1.wget https://dl.min.io/server/minio/release/linux-amd64/minio
2.chmod 755 minio
3./minio server --console-address ":9001" /home/minio/data

4.login url : http://10.170.136.206:9001/login  
username and password both  minioadmin
![图片](https://user-images.githubusercontent.com/10250772/127322558-e3d741ec-7db8-457e-93ac-805d19772825.png)
log output like this
![图片](https://user-images.githubusercontent.com/10250772/127322426-5d65024b-5ead-4f2a-b807-b97cb78e4d10.png)

## Your Environment
[root@localhost minio]# ./minio -version
minio version RELEASE.2021-07-22T05-23-32Z
[root@localhost minio]# uname -a
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost minio]#

**Comment by pastel001** [comment] 2021-07-28 12:41
request body:{"accessKey":"minioadmin","secretKey":"minioadmin"}
response:{"code":401,"message":"invalid Login"}

**Comment by vadmeste** [comment] 2021-07-28 12:56
@Pastel001 I am not able to reproduce with the latest MinIO version, RELEASE.2021-07-27T02-40-15Z, could you try with it ?

**Comment by tdewin** [comment] 2021-07-28 14:29
Similar issue here with the variables being set MINIO_ROOT_USER & MINIO_ROOT_PASSWORD, will try with an older version

**Comment by harshavardhana** [comment] 2021-07-28 15:54
@vadmeste you can see from the screenshot they have a proxy configured on the system that is reply back as HTML instead of `<AssumeRoleResponse>`

Do verify make sure to run `mc admin trace alias/` and try logging in. If there is no request seen by MinIO that means you have something else running on port 9000 or some other proxy that is blocking it. 

> Similar issue here with the variables being set MINIO_ROOT_USER & MINIO_ROOT_PASSWORD, will try with an older version

@tdewin can you share your server logs.

**Comment by pastel001** [comment] 2021-07-29 02:29
@vadmeste  @harshavardhana @tdewin 
yes,I have config a proxy on my system,the proxy config like "export http_proxy=http://proxy.xxx.com"
and after add a no proxy config, minio login work well, the config is  "export no_proxy='127.0.0.1,10.170,136.206'"
thanks for everyone.

**Comment by harshavardhana** [comment] 2021-07-29 02:32
> @vadmeste  @harshavardhana @tdewin 
> yes,I have config a proxy on my system,the proxy config like "export http_proxy=http://proxy.xxx.com"
> and after add a no proxy config, minio login work well, the config is  "export no_proxy='127.0.0.1,10.170,136.206'"
> thanks for everyone.

Thanks closing..

**Closed as completed by harshavardhana** 2021-07-29 02:32 UTC
Labels: working as intended, community, upstream (bug)
