### ISSUE TITLE
LDAP permission lingers until minio reboot

### ISSUE THREAD

**Issue by tkg61** [minio/minio#12074] opened 2021-04-16 14:28 UTC
Please let me know if this is in the wrong repo

## Expected Behavior
When a permission/policy is removed from an LDAP user, that user should no longer be able to access the Console webpage.

## Current Behavior
Currently, if a policy is used to grant access to the Console app it will remain attached/valid to the user even if it is unset from that user. The policy correctly blocks users from their buckets. 

## Steps to Reproduce (for bugs)

1. Configure LDAP on minio and Console
2. Grant console access to a user
```
mc admin policy set myminio test-policy user="CN=minio_test_user,OU=Users,DC=test,DC=com"
Policy `test-policy` is set on user `CN=minio_test_user,OU=Users,DC=test,DC=com
```

```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "admin:ServerInfo"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
      "s3:GetBucketLocation",
      "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::testbucket"
   ]
  }
 ]
}
```
3. log into console to confirm access, then log out.
![image](https://user-images.githubusercontent.com/3945114/115037548-9497df80-9e9c-11eb-9c07-e65925470175.png)
4. Unset/remove policy from the user
```
mc admin policy unset myminio test-policy user="CN=minio_test_user,OU=Users,DC=test,DC=com"
Policy `test-policy` is unset on user `CN=minio_test_user,OU=Users,DC=test,DC=com
```
5. log back into console and see permission to do so still is there. Then log out
![image](https://user-images.githubusercontent.com/3945114/115038243-564ef000-9e9d-11eb-89e7-e24907c3cebe.png)

6.  Restart minio server(s)
```
 mc admin service restart myminio
Restart command successfully sent to `myminio`.
Restarted `myminio` successfully.

```
7. try to log back in and user should now be blocked
![image](https://user-images.githubusercontent.com/3945114/115035037-23efc380-9e9a-11eb-93e4-4234ce6da882.png)

## Context
We have been testing why certain users can not access or can't see everything inside of Console at times and why policy changes seem to not effect users. This was reported in Console ticket: https://github.com/minio/console/issues/676 
Restarts of the console app do not fix the issue either.

Note: User used in example has a DN of "minio_user_test" but a username of "minio-user-test" this is not a typo... issues arose when using a DN and username of the same string... another bug?

## Regression
N/A

## Your Environment
* Version used (`minio --version`):
Version: 2021-04-06T23:11:00Z
* Server setup and configuration:
4 node cluster on baremetal
* Operating System and version (`uname -a`):
Linux minio1 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Alevsk** [comment] 2021-04-16 17:14
@tkg61 We were able to replicate the issue, will work on a fix soon

**Comment by Alevsk** [comment] 2021-04-16 23:25
@tkg61 I'm able to reproduce all the steps except 4 and 5


```
4. Unset/remove policy from the user
    mc admin policy unset myminio test-policy user="CN=minio_test_user,OU=Users,DC=test,DC=com"
    Policy `test-policy` is unset on user `CN=minio_test_user,OU=Users,DC=test,DC=com
5. log back into console and see permission to do so still is there. Then log out
```

can you try this on master? perhaps is already fixed.

**Comment by harshavardhana** [comment] 2021-04-16 23:26
This issue was actually fully addressed in #11808

**Comment by tkg61** [comment] 2021-04-20 17:34
Still having this issue after updating to latest version

**Comment by tkg61** [comment] 2021-04-22 18:52
Still an issue in 4-22 release @harshavardhana @Alevsk

**Comment by harshavardhana** [comment] 2021-04-22 20:01
> Still an issue in 4-22 release @harshavardhana @Alevsk

That is not possible @tkg61 we have already tested this locally.

If you already have a session active then that session also will stop working as per our testing. Not sure what might be different in your environment.

**Comment by harshavardhana** [comment] 2021-04-22 20:02
Also make sure you are using the lookup bind mode in LDAP, we are going to deprecate non lookup bind approach soon.

**Comment by tkg61** [comment] 2021-04-22 20:12
I am using the lookup bind and the strange part is that this only effects auth'ing into console, policy updates immediately apply to buckets. 

i will go back a couple versions and see if it stops happening with a specific version

**Comment by vadmeste** [comment] 2021-04-22 20:22
@tkg61 can you paste your ldap config that you set for MinIO server ?

**Comment by tkg61** [comment] 2021-04-22 20:50
```
MINIO_VOLUMES="https://minio{1...4}.domain.local/data{1...18}"

# Use if you want to run MinIO on a custom port.
MINIO_OPTS="--certs-dir /opt/miniocerts --address :443"
# Root user for the server.
MINIO_ROOT_USER=minioadmin
# Root secret for the server.
MINIO_ROOT_PASSWORD=minioadmin

MINIO_IDENTITY_LDAP_SERVER_ADDR='my-dc.domain.local:636'
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="OU=Users,DC=domain,DC=local"
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER="(&(objectclass=group)(member=%d))"
MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE=cn
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
MINIO_IDENTITY_LDAP_LOOKUP_BIND_DN='cn=bind_user,OU=Users,DC=domain,DC=local'
MINIO_IDENTITY_LDAP_LOOKUP_BIND_PASSWORD="BIND_USER_PASS"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_FILTER="(sAMAccountName=%s)"
MINIO_IDENTITY_LDAP_USER_DN_SEARCH_BASE_DN="OU=Users,DC=domain,DC=local"
```

**Comment by tkg61** [comment] 2021-04-22 20:54
i am trying to investigate to see if this is some sort of permission creep on my end after doing so much testing and "loosing" which were applied where (as related to https://github.com/minio/mc/issues/3690 and https://github.com/minio/mc/issues/3691)

**Comment by tkg61** [comment] 2021-04-22 21:57
console version - console-68 version 0.6.8 - c07b7b47
mc version - mc version RELEASE.2021-04-22T17-40-00Z 
minio version - 2021-04-22T15:44:28Z

I believe i see that things are "working" but i want to confirm this is expected... 

First off, i do think on one of my users has permission creep since they are apart of several groups i have tested with and there is some random policy applied that still gives them access. I am thinking about writing bash script to do an ldapsearch loop over each group that my user is apart of, run an "mc admin policy group info..." for each group and then see where i have missed something.

Anyways, i have been able to add and remove policies from a new AD user but the issue is that the logout button is not clearing sessions. i can log out and back in repeatedly even though the policy has been unset from the user. 

If i open up an incognito window the user can't log in which should be correct. If i re-set the policy and log in through the incognito window i can still repeatedly login via the incognito window even after closing it and re-opening (not a new tab, entire window, might just be a chrome issue).

**_.... 5 minutes go by after i keep testing while writing...._**

I believe i have discovered the real issue going on here. All of the above is still valid but i have an idea as to why this is happening. 

In my current configuration, the mc alias is set to go to node1 of my cluster. My console app is pointed at node4 of the cluster (another random result from testing) and I believe there is some sort of delay going on here. 
When switching the console app to use node1 all policy changes happen immediately and things work as expected. In rebooting Minio I assume some policy sync happens and that forces everything to normalize. 

Hope this makes sense and thanks for the help!

**Comment by harshavardhana** [comment] 2021-04-23 06:46
Thanks for the explanation it makes sense

> In my current configuration, the mc alias is set to go to node1 of my cluster. My console app is pointed at node4 of the cluster (another random result from testing) and I believe there is some sort of delay going on here.
When switching the console app to use node1 all policy changes happen immediately and things work as expected. In rebooting Minio I assume some policy sync happens and that forces everything to normalize.

The unset of the policy seems to be not propagated to remote nodes, which is causing the other peers to remember state they loaded from disk.

I will send a fix here it's a silly bug.

**Closed as completed** 2021-04-23 22:11 UTC
Labels: community, fixed
