### ISSUE TITLE
Server panic when webhook return 500 error

### ISSUE THREAD

**Issue by mindhash** [minio/minio#8186] opened 2019-09-05 09:23 UTC
I configured a web hook endpoint and a bucket notification. The webhook endpoint is unimplemented and returns HTTP 500.  

## Expected Behavior

Expected Minio server either
i) to queue up the events and retry webhook call after a while OR 
ii) softly handle failure and continue serving other requests

## Current Behavior

The server generated panic and exited.  

panic: target.Send() failed with 'sending event failed with 500 Internal Server Error'

goroutine 96 [running]:
github.com/minio/minio/pkg/event/target.sendEvents.func1(0xc0000d6272, 0x24, 0x2)
	/q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:107 +0x34b
github.com/minio/minio/pkg/event/target.sendEvents(0x27e75e0, 0xc00046c0e0, 0xc00056e900, 0xc00056e000)
	/q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:128 +0x180
created by github.com/minio/minio/pkg/event/target.NewWebhookTarget
	/q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/webhook.go:225 +0x2a8
## Steps to Reproduce (for bugs)

1. Install Minio (2019-07-10T00:34:56Z) 
2. Start minio: minio server ./data 

3. Configure webhook: 
mc admin config set myminio/ < config.json

4. Configure bucket notification
mc event add myminio/small arn:minio:sqs::1:webhook

## Context

I am looking for a time based capture of bucket sizes. Chose to use webhook over others because of queueing/store capability.  Expect the receiver (of events) to be always online but in case it is offline for a few mins then expect queue to ensure we don't loose events. 

## Your Environment

* Version used (`minio version`): 2019-07-10T00:34:56Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
OSX (Local install)
* Link to your project:

**Comment by nitisht** [comment] 2019-09-05 09:24
@mindhash this is a known issue, marking as duplicate of #8178

**Closed as completed** 2019-09-05 09:25 UTC
Labels: duplicate, community
