### ISSUE TITLE
server: Server times are too far apart error message between multiple minio servers

### ISSUE THREAD

**Issue by stephenchinnadorai** [minio/minio#3999] opened 2017-03-29 15:02 UTC
## Expected Behavior
Servers should be able to connect in distributed mode

## Current Behavior
4 servers running in docker containers on 4 separate VMs - time is a maximum of 4 seconds apart between the servers when tested. 

Docker logs for minio on one of the nodes shows the standard info screen saying 4 online. The remaining three show the following error:
`[03/04] redacted.com:9000:/minio/storage/export : Server times are too far apart`
Given the time differences are minimal, it seems that this may not actually be the problem. I have also run the `date` command inside of the minio docker container and it shows the same results as doing so on the VM.

## Steps to Reproduce (for bugs)
1. Run minio in docker with the `server http://hostname1/export http://hostname2/export ...` command on 4 servers
2. docker logs -f minio
3. observe error message on some of the nodes

## Your Environment

* Version used: 2017-03-16T21:50:32Z
* Environment name and version (e.g. nginx 1.9.1): Docker version 1.12.6, 
* Server type and version: 
* Operating System and version: CentOS Linux release 7.3.1611 (Core)
* Link to your project:

**Comment by harshavardhana** [comment] 2017-03-29 15:51
Servers need to be less than 3 seconds apart so is the message. It's not a bug just an indication that you need to fix your servers to have same time.

**Comment by harshavardhana** [comment] 2017-03-30 06:25
Closing this as not a bug but an intended behavior.

**Closed as completed by harshavardhana** 2017-03-30 06:25 UTC
Labels: working as intended, community
