### ISSUE TITLE
Migrate large number of files to minio

### ISSUE THREAD

**Issue by Meshkati** [minio/minio#8710] opened 2019-12-29 06:51 UTC
## Is your feature request related to a problem? Please describe.

Migrating millions of small files to minio with Minio client is so slow, though reading each file and creating the file in minio has overhead or something.

## Describe the solution you'd like

Archiving files with tar or something and copy them with mc, then minio server extracts them itself and spread it into its cluster.

With a single node minio server, we did a similar thing, we archived the whole files, used rsync to transfer to destination and then unarchived them in the disk that minio works with that ( also rsync with `-z` option does the same ). But in cluster mode, I can't find a similar solution :(

**Comment by nitisht** [comment] 2019-12-29 14:51
can you be more specific @Meshkati 

what was the number of files, how did you measure performance, what is the network connectivity between client and server, what are the details (cpu, mem, network) of your MinIO deployment?

> Archiving files with tar or something and copy them with mc, then minio server extracts them itself and spread it into its cluster.

These can be done on the client side itself

**Comment by Meshkati** [comment] 2019-12-30 18:15
We have 200MB/s on transferring files larger than 50MB on a 4 node minio cluster (16GB ram, 12 cores, SSDs), but when it comes to 1-2 Millions of files with less than 50KB, this rate is less than 1MB/s and it takes so long to upload. We have to migrate about 500 Million files in this size and it became so painful this way.
This behavior is not surprising, it's like transferring these files with scp or rsync without any archiving and compression, it tries to create many files and that takes a long time, but when it comes to archiving and then transferring, it has the overhead of creating 1 file and it uses the bandwidth more efficient.

> These can be done on the client side itself

So the minio client archives and then decompress it on the server? What's the command? :D

**Comment by harshavardhana** [comment] 2019-12-30 19:09
@Meshkati you may be interested in #8715

**Comment by harshavardhana** [comment] 2019-12-30 23:24
Duplicate of #8715

**Closed as completed by harshavardhana** 2019-12-30 23:24 UTC
Labels: duplicate, community, triage
