### ISSUE TITLE
XL: mc session resume - does not resume properly

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1544] opened 2016-05-08 23:30 UTC
```
krishna@minio2:~$ mc cp 200gfile myminio/test1/
200gfile:                       132.84 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  66.42 % 41.12 MB27m38s 200gfile:                       132.88 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  66.44 % 41.12 MB27m37s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume bQtEqAhp’
krishna@minio2:~$ mc session resume bQtEqAhp
200gfile:                       26.93 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  13.46 % 89.48 MB30m58s 200gfile:                       27.05 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  13.53 % 89.63 MB30m57s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume bQtEqAhp’
krishna@minio2:~$ mc session resume bQtEqAhp
200gfile:                       1.46 GB / 200.00 GB ┃█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃   0.73 % 88.75 MB35m31s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume bQtEqAhp’
krishna@minio2:~$ 
```

session not resuming from where it left off, needs to be investigated.

**Comment by harshavardhana** [comment] 2016-05-08 23:42
> krishna@minio2:~$ mc cp 200gfile myminio/test1/
> 200gfile:                       132.84 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  66.42 % 41.12 MB27m38s 200gfile:                       132.88 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  66.44 % 41.12 MB27m37s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume bQtEqAhp’
> krishna@minio2:~$ mc session resume bQtEqAhp
> 200gfile:                       26.93 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  13.46 % 89.48 MB30m58s 200gfile:                       27.05 GB / 200.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃  13.53 % 89.63 MB30m57s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume bQtEqAhp’
> krishna@minio2:~$ mc session resume bQtEqAhp
> 200gfile:                       1.46 GB / 200.00 GB ┃█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃   0.73 % 88.75 MB35m31s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume bQtEqAhp’
> krishna@minio2:~$ 
> session not resuming from where it left off, needs to be investigated.

You can see only 'mc' using 100% CPU during this time, it is calculating md5sum and verifying for each parts.

**Comment by harshavardhana** [comment] 2016-05-08 23:43
> session not resuming from where it left off, needs to be investigated.
> You can see only 'mc' using 100% CPU during this time, it is calculating md5sum and verifying for each parts.

A similar test was done with 1TB file currently running, mc cpu usage was 100% and no data transfer was in progress.

**Comment by krishnasrinivas** [comment] 2016-05-08 23:47
In that case it is mc bug because it shows it as though it is copying from the beginning.
Also minio is using 20-60% cpu,

**Comment by harshavardhana** [comment] 2016-05-08 23:50
> In that case it is mc bug because it shows it as though it is copying from the beginning.
> Also minio is using 20-60% cpu,

It is listing previously uploaded parts ..

**Comment by harshavardhana** [comment] 2016-05-08 23:52
Behavior is sporadic,  not able to reproduce this anymore. 

```
minio@minio2:~/atul/datasets$ mc cp mymino4/atul1/freebase-rdf-latest mymino4/at
ul1/freebase-rdf-latest1
...df-latest: 4.35 GB / 396.03 GB ┃█░░░░░░░░░░░░░░░░┃   1.10 % 19.85 MB5h36m27s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume NfyzzojE’
minio@minio2:~/atul/datasets$ mc session resume NfyzzojE
...df-latest: 5.03 GB / 396.03 GB ┃█░░░░░░░░░░░░░░░░░┃   1.27 % 89.07 MB1h9m58s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume NfyzzojE’
minio@minio2:~/atul/datasets$ mc session resume NfyzzojE
...df-latest: 6.09 GB / 396.03 GB ┃█░░░░░░░░░░░░░░░░┃   1.54 % 80.29 MB1h16m45s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume NfyzzojE’
```

**Comment by harshavardhana** [comment] 2016-05-08 23:54
> In that case it is mc bug because it shows it as though it is copying from the beginning.
> Also minio is using 20-60% cpu,

It could also be listing bug where multipart upload is not listed and mc uploads again - you should do '--debug' to see if the uploadID is constant.

**Comment by harshavardhana** [comment] 2016-05-09 20:37
Were you able to reproduce this again? @krishnasrinivas

**Comment by krishnasrinivas** [comment] 2016-05-11 05:43
@harshavardhana need to check

**Comment by harshavardhana** [comment] 2016-05-11 20:00
> @harshavardhana need to check

were you able to validate this?

**Comment by krishnasrinivas** [comment] 2016-05-11 20:46
did not get a chance yet, if you can't reproduce this you can close this. I will keep it in my todo list to test this later.

**Comment by harshavardhana** [comment] 2016-05-11 21:02
> did not get a chance yet, if you can't reproduce this you can close this. I will keep it in my todo list to test this later.

I only saw it once with Atul since then not been able to reproduce, closing - reopen if you see it again.

**Closed as completed by harshavardhana** 2016-05-11 21:02 UTC
