### ISSUE TITLE
redis notice error

### ISSUE THREAD

**Issue by Luowenlin1314** [minio/minio#10138] opened 2020-07-27 09:48 UTC
![image](https://user-images.githubusercontent.com/34334502/88528349-1dca6600-d031-11ea-964a-9b049800bb6e.png)
![image](https://user-images.githubusercontent.com/34334502/88528387-29b62800-d031-11ea-9be2-041f94f4f493.png)

What's the problem? Who can tell me. ths.

**Comment by vadmeste** [comment] 2020-07-27 10:17
@Luowenlin1314 it looks like you have a directory called 'myminio' in your local machine.

**Comment by harshavardhana** [comment] 2020-07-28 03:57
Yes make sure you don't have a directory named `myminio` - since mc honors your local path first

Closing this issue as not a bug.

**Closed by harshavardhana** 2020-07-28 03:57 UTC
Labels: community, triage
