### ISSUE TITLE
[PR#5160] Minio server crashes when healing

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5538] opened 2018-02-15 18:05 UTC
## Expected Behavior
No crash

## Current Behavior
Crash with this log:
```
[2018-02-15T17:58:34.051924679Z] [ERROR] http://domain:9105/tmp/dist/d-5: open /tmp/dist/d-5/.minio.sys/format.json: too many open files (open /tmp/dist/d-5/.minio.sys/format.json: too many open files)
2018/02/15 18:58:52 http: Accept error: accept tcp [::]:9105: accept4: too many open files; retrying in 5ms
2018/02/15 18:58:52 http: Accept error: accept tcp [::]:9105: accept4: too many open files; retrying in 10ms
2018/02/15 18:58:52 http: Accept error: accept tcp [::]:9105: accept4: too many open files; retrying in 20ms
2018/02/15 18:58:52 http: Accept error: accept tcp [::]:9105: accept4: too many open files; retrying in 40ms
2018/02/15 18:58:52 http: Accept error: accept tcp [::]:9105: accept4: too many open files; retrying in 80ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x78a986]

goroutine 75 [running]:
net/rpc.(*Client).Close(0x0, 0xc42191fd20, 0x20)
        /home/vadmeste/work/go/src/net/rpc/client.go:280 +0x26
github.com/minio/minio/cmd.(*lockServer).lockMaintenance(0xc4202c1590, 0x1bf08eb000)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/lock-rpc-server.go:329 +0x446
github.com/minio/minio/cmd.startLockMaintenance.func1(0xc4202c1590)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/lock-rpc-server.go:82 +0x8e
created by github.com/minio/minio/cmd.startLockMaintenance
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/lock-rpc-server.go:68 +0x3f
```

the backend is attached to this email.
[dist.tar.gz](https://github.com/minio/minio/files/1728789/dist.tar.gz)

## Possible Solution
Do not know

## Steps to Reproduce (for bugs)
1. Unzip the backend in /tmp/dist/
2. Add `127.0.0.1    domain` to /etc/hosts
3. Run the following script which spawns 32 Minio servers + 32 disks
```
#!/bin/bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"

start_port=9100
scheme="http"
addr="domain"
base_path="/tmp/dist/"
args=""

killall -9 minio
# rm -r ${base_path}/d-*


for ((i=0;i<32;i++)); do
    args="$args $scheme://$addr:$[${start_port}+$i]/${base_path}/d-$i"
done

for((i=0;i<32;i++)); do
     (minio server --address ":$[${start_port}+$i]" $args 2>&1 | \
         tee ${base_path}/log-$i.txt) &
done
```

4. mc admin heal myminio/

## Context
Testing large bucket PR

## Your Environment
All

**Comment by harshavardhana** [comment] 2018-02-15 18:07
Duplicate of #5534

**Closed as completed by harshavardhana** 2018-02-15 18:07 UTC
Labels: duplicate, priority: medium
