### ISSUE TITLE
Recommended systemd service file leaves stray process running after shutdown when using NAS Gateway mode

### ISSUE THREAD

**Issue by drauschenbach** [minio/minio#10024] opened 2020-07-11 22:47 UTC
The [recommended systemd service file](https://github.com/minio/minio-service/blob/master/linux-systemd/minio.service) works well in server mode, but in NAS Gateway mode a systemd service shutdown leaves a MinIO process running with the binary file locked.

## Expected Behavior
A reliable method of shutdown is required for headless DevOps environments where upgrades are expected to be possible.

## Current Behavior
DevOps automation fails to upgrade MinIO after a `systemctl stop myservicename`, causing the need for manual intervention.

## Your Environment
Oracle Linux 7
minio-2020-06-14T18-32-17Z-linux-amd64

**Comment by harshavardhana** [comment] 2020-07-14 01:40
> The [recommended systemd service file](https://github.com/minio/minio-service/blob/master/linux-systemd/minio.service) works well in server mode, but in NAS Gateway mode a systemd service shutdown leaves a MinIO process running with config file locks.

How did you figure out it is config locks? can you share more precise reproducible steps? - the systemd service seems to work fine with local testing.

**Comment by ebozduman** [comment] 2020-07-27 12:18
@drauschenbach,

We need more information to reproduce this issue.

I created the recommended service file and started/stopped minio gateway using `systemctl service` command. Both start and stop functionality worked as expected without leaving any process behind.

Please let us know if you can still reproduce the issue. If so, please update the reproduction steps and add any missing details.

**Comment by drauschenbach** [comment] 2020-07-27 18:16
My mistake about a config file being locked. It was actually the binary itself that was locked. I got confused by a Python-specific error message: `OSError: [Errno 26] Text file busy: '/usr/local/bin/minio'`.

I think I have isolated this issue to MinIO hanging when run on a 2nd node for a given NAS volume. The docs says this is supported for HA, but in our case the process locks up, and doesn't respond to any signaling.

So in our environment "systemctl stop minio" rarely, if ever, does anything, and we have to manually visit each server and `kill -9` the processes.

Is there a reason why MinIO could not respond to the usual Ctrl+C signal handling?

**Comment by ebozduman** [comment] 2020-07-28 06:56
@drauschenbach,

I still could not reproduce the issue with 2 nodes.

We need more information and detail on the reproduction steps.

Could you also send us `/etc/default/minio` and `/etc/systemd/system/<minio-service-name>.service` files for all nodes.
How do you start the `minio gateway nas` services on each node?

> Is there a reason why MinIO could not respond to the usual Ctrl+C signal handling?

When and how? I don't understand how you can use CTRL-C signal while you start/stop minio with `systemctl` command? I assume this is a completely separate question.

**Comment by ebozduman** [comment] 2020-07-31 10:07
@drauschenbach,

Ping!
Could you please see my last comment and answer my questions?
Thank you...

**Comment by ebozduman** [comment] 2020-08-05 07:42
Closing this issue at this point since we cannot reproduce it.
Marking it `working as intended` and `won't fix`.

**Closed as completed by ebozduman** 2020-08-05 07:42 UTC
Labels: working as intended, community, out of scope
