### ISSUE TITLE
C# Upload/Download not working when using Amazon S3 Client with umlaut in object name

### ISSUE THREAD

**Issue by LKneringer** [minio/minio#7782] opened 2019-06-13 09:22 UTC
The Amazon S3 client lets me upload and download files with umlauts (ä, ö, ü) in their name, and so does MinIO. However, using the Amazon S3 client while using MinIO throws an exception when the key to store the file at contains an umlaut.

Code using the Amazon S3 client:
```
// Upload works when uploading to Amazon S3
// Exception thrown when uploading to MinIO when the key contains an umlaut
var putObjectRequest = new PutObjectRequest
{
    BucketName = bucketName,
    Key = key, //e.g. Key = "Brücke.jpg"
    FilePath = filePath
};
await client.PutObjectAsync(putObjectRequest);
```
Code using the MinIO client:
```
// Upload always works
await client.PutObjectAsync(bucketName, key, filePath).ConfigureAwait(false);
```

The exception reads:

> Amazon.S3.AmazonS3Exception: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.'
> It contains two inner exceptions, both being about the server returning a (403) Forbidden response.

## Expected Behavior
We expect that the Amazon S3 client would still allow us to upload files using a key with an umlaut to MinIO, given how MinIO does support this feature.

## Current Behavior
An exception is thrown when an umlaut is used while uploading a file to MinIO using the Amazon S3 client.

## Steps to Reproduce (for bugs)
1. Use the code related to the Amazon S3 client above to upload a file to MinIO.
2. Make sure the key contains an umlaut.

## Context
We'd like to be able to change between the real Amazon storage and MinIO on the fly, so we'd appreciate not having to change the client depending on which environment we're using.

## Your Environment

* Version used (`minio version`): 2019-06-13T01:41:13Z
* Nuget packages: [MinIO v3.0.11](https://www.nuget.org/packages/Minio/3.0.11), [AWSSDK.S3 v3.3.102.12](https://www.nuget.org/packages/AWSSDK.S3/3.3.102.13/)
* Operating System and version (`uname -a`): Windows 10 Pro Version 1803
* Link to your project: https://github.com/AlturosDestinations/Alturos.ImageAnnotation

**Comment by kannappanr** [comment] 2019-06-13 11:55
@LKneringer Thanks for filing this issue. We will take a look.

**Comment by poornas** [comment] 2019-06-14 05:14
@LKneringer, was able to repro this issue -  this is a bug with AWS C# sdk as it double encodes the path if not an S3 endpoint. Open issue is https://github.com/aws/aws-sdk-net/issues/933. you might want to downgrade to 3.3.19 version of aws c# sdk as pointed out in that issue and see if the upload works.

**Comment by kannappanr** [comment] 2019-06-14 06:11
Closing this issue as duplicate of https://github.com/minio/minio/issues/6548

**Closed as completed by kannappanr** 2019-06-14 06:11 UTC
Labels: duplicate, community
