### ISSUE TITLE
PutObject XMinioWriteQuorum error despite all disks showing as online in distributed cluster

### ISSUE THREAD

**Issue by jhartley1** [minio/minio#5271] opened 2017-12-05 15:23 UTC
## Expected Behavior

PutObject requests should succeed when write quorum is reached.

## Current Behavior

PutObject requests consistently fail with code: XMinioWriteQuorum and message: "Multiple disks failures, unable to write data." This is occuring under write throughput under 1 per second.

Server log (This same log line repeated with different objects paths): 
`time="2017-12-05T14:59:02Z" level=error msg="Unable to create an object. /redacted/redacted UUID/redacted UUID" cause="Storage resources are insufficient for the write operation." source="[object-handlers.go:612:objectAPIHandlers.PutObjectHandler()]" stack="xl-v1-utils.go:78:reduceQuorumErrs xl-v1-utils.go:91:reduceWriteQuorumErrs xl-v1-metadata.go:507:writeUniqueXLMetadata xl-v1-object.go:619:xlObjects.PutObject <autogenerated>:1:(*xlObjects).PutObject object-handlers.go:610:objectAPIHandlers.PutObjectHandler api-router.go:63:(objectAPIHandlers).PutObjectHandler-fm"`  

Reads still succeed for all data previously written. The current setup has worked for several months, and this issue suddenly arose a few days ago. I have previously restarted nodes with no problems.

## Possible Solution

Already attempted solutions:
* Restart entire cluster (Several times) - No difference
* Run `mc admin heal` for all nodes - This updates the online disks to the correct number 4, but no difference in writes
* Run `mc admin heal` for bucket where we attempt writes - Hangs and then errors on timeout awaiting response headers. Similar to  #4132.

I am prepared to either migrate onto a new instance of Minio, or off Minio to S3 to resolve my issue.
## Steps to Reproduce (for bugs)

I can't provide access to our production system at this time.

## Context

Running Minio for production SaaS service storing raw json blobs, and images. Microservice writes events to minio, and we serve presigned GetObject to users for displaying content.

## Your Environment

* Version used (`minio version`):  
Version: 2017-11-22T19:55:46Z 
Release-Tag: RELEASE.2017-11-22T19-55-46Z 
Commit-ID: d1a6c32d800f1d5b703baad1f8aeede6cf2cdf48
* Environment name and version (e.g. nginx 1.9.1):
Client: Haskell with [amazonka-s3](https://hackage.haskell.org/package/amazonka-s3)
* Server type and version:
4 node distributed cluster, each node with single disk.
`mc admin info` output:
    *  localhost:9000
   Uptime : online since 13 hours ago
  Version : 2017-11-22T19:55:46Z
   Region : us-east-1
 SQS ARNs : <none>
  Network : Incoming 1.2GiB, Outgoing 83MiB
  Storage : Total 373GiB, Free 225GiB, Online Disks: 4, Offline Disks: 0
    *  minio-statefulset-1.minio.default.svc.cluster.local:9000
   Uptime : online since 13 hours ago
  Version : 2017-11-22T19:55:46Z
   Region : us-east-1
 SQS ARNs : <none>
  Network : Incoming 261MiB, Outgoing 20MiB
  Storage : Total 373GiB, Free 225GiB, Online Disks: 4, Offline Disks: 0
    *  minio-statefulset-2.minio.default.svc.cluster.local:9000
   Uptime : online since 13 hours ago
  Version : 2017-11-22T19:55:46Z
   Region : us-east-1
 SQS ARNs : <none>
  Network : Incoming 1.1GiB, Outgoing 174MiB
  Storage : Total 373GiB, Free 225GiB, Online Disks: 4, Offline Disks: 0
    *  minio-statefulset-3.minio.default.svc.cluster.local:9000
   Uptime : online since 13 hours ago
  Version : 2017-11-22T19:55:46Z
   Region : us-east-1
 SQS ARNs : <none>
  Network : Incoming 1.1GiB, Outgoing 73MiB
  Storage : Total 373GiB, Free 225GiB, Online Disks: 4, Offline Disks: 0

* Operating System and version (`uname -a`): 
Docker containers running as statefulset on Kubernetes v1.7.0. Kubernetes cluster on AWS managed with [kops](https://github.com/kubernetes/kops). Deployment yaml functionally identical to [https://github.com/minio/minio/tree/master/docs/orchestration/kubernetes-yaml](https://github.com/minio/minio/tree/master/docs/orchestration/kubernetes-yaml).
`uname -a` for first pod using `kubectl exec`: `Linux minio-statefulset-0 4.4.65-k8s #1 SMP Tue May 2 15:48:24 UTC 2017 x86_64 Linux`
* Link to your project:

**Comment by donatello** [comment] 2017-12-07 01:10
@jhartley1 This is a rather difficult to reproduce issue - could you please try/answer the following and let me know:

1. Determine that there are no disk IO issues - log in to each one of the instances and
   - assuming the minio disk is mounted at /mnt/export, try:
   - `mkdir -p /mnt/export/<bucket-name>/<object-name>`
   - `touch /mnt/export/<bucket-name>/<object-name>/xl.json`
   If either of the above have errors, we need to see if at least 3 disks are working (for writes to succeed          in a 4 disk setup).
2. Does the issue happen on a PUT object request that creates a new object or one that replaces an existing object (or both)?
3. What are the typical file sizes with which the errors are seen? Is the multipart PUT object API being used?
4. After all minio instances have started up, and heal is run (`mc admin heal myminio`), on each minio disk, do you see a file at `.minio.sys/format.json` on each of the 4 disks?

**Comment by jhartley1** [comment] 2017-12-07 01:29
On one of the nodes, the disk ran out of inodes.  I only attempted file creation on one node and I was relying just on disk space metrics from `df`. That was a good call to double check all of them. It seems like that shouldn't be seen as an online disk during health check. Seeing the disks as online put me off guard for a disk error. 

The issue occurred with PUT requests for new small objects (< 1KB), just as you would expect for running out of inodes. Probably a good documentation entry for a troubleshooting section.

Thanks for your help!

**Comment by donatello** [comment] 2017-12-07 01:32
@jhartley1 Ah I see - what file system are you using? We usually recommend xfs.

**Comment by jhartley1** [comment] 2017-12-07 01:34
ext4, as that was the default for the external disks mounted through the volume claim. Is the file system recommendation in the docs?

edit: Glancing around, I don't actually know when the disk is formatted during provisioning.

**Comment by donatello** [comment] 2017-12-07 01:45
@jhartley1 It is not in our docs yet - we will add it. Please migrate to XFS formatted disks. We did have a check for free inodes earlier, but ended up removing it because there seemed to be no clean cross platform solution at the time. We will revisit that decision too. In addition, we will be looking into adding some additional info in the log for quorum errors that would help reveal underlying issues more quickly. Thank you for the detailed report and working with us on the issue. I am closing this out as fixed.

**Closed as completed by donatello** 2017-12-07 01:45 UTC
Labels: priority: medium
