### ISSUE TITLE
feature: minio statistics

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3173] opened 2016-11-04 05:37 UTC
@gebi 's request : stats on number of requests, number of objects, number of clients connected, number of requests currently in flight, number of storage backend, number of faulty storage backends, a latency histogram of access per backend

**Comment by harshavardhana** [comment] 2016-12-01 22:22
https://github.com/felixge/httpsnoop - one such step in this direction.

**Comment by gebi** [comment] 2016-12-02 02:20
unfortunately this doesn't help much.

To double the speed of mino one needs to use a reverse proxy anyway, we eg. use nginx and gather all http related statistics of minio with nginx and a prometheus endpoint written with nginx+lua (including histograms of all url patterns important to us). [nginx-lua-prometheus]

What's not possible to get are latency statistics from the minio storage backend on a per device basis.
Just all those things necessary to debug possible performance degration problems in production.

[nginx-lua-prometheus]: https://github.com/knyar/nginx-lua-prometheus

**Comment by harshavardhana** [comment] 2017-02-06 03:31
Closing as duplicate of https://github.com/minio/minio/issues/3679

**Closed as completed by harshavardhana** 2017-02-06 03:31 UTC
Labels: community
