### ISSUE TITLE
Investigate if profile id needs to be supported in gcs .

### ISSUE THREAD

**Issue by deekoder** [minio/minio#4317] opened 2017-05-10 23:58 UTC
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by deekoder** [comment] 2017-05-11 00:45
Project id is mandatory. If not specified, show help for GCS.

**Comment by poornas** [comment] 2017-05-25 23:44
@deekoder, This is duplicate of  #4417, and was fixed by #4421 . Basically profile is not supported and has been removed from gateway startup options

**Closed as completed** 2017-05-30 16:57 UTC
Labels: priority: high
