### ISSUE TITLE
High load on distributed mode

### ISSUE THREAD

**Issue by ahmadalli** [minio/minio#8049] opened 2019-08-09 05:45 UTC
I have 3 server (2 disks per each server) cluster of minio. When I sync from another minio instance to this cluster, 2 of my 3 nodes gain high load.

I've tried `mc mirror source dest` and `rclone sync source dest --transfers=1024 --checkers=1024` and both causes cluster to go to this state.

## Expected Behavior
having normal load on cluster nodes

## Current Behavior
2 of my 3 nodes gain high load (from 40 to 340) which increases over time

## Steps to Reproduce (for bugs)
1. bring up 3 node cluster with 2 ssd disks: os disk on `/mnt/export1` and second disk on `/mnt/export2`
1. mirror from a minio instance with lots of small files (e.g. 250GB of images less than 1mb each)
1. watch the sever loads

## Context
I'm trying to move from a single node minio to distributed minio to gain more storage and HA.

## Your Environment
* Version used (`minio version`): RELEASE.2019-08-07T01-59-21Z
* Server type and version: distributed server with RELEASE.2019-08-07T01-59-21Z installed on all of them
* Operating System and version (`uname -a`): Ubuntu 18.04, Linux ss2 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x8
6_64 x86_64 GNU/Linux
* Disks:
  - os ssd drive on `/etc/export1`
  - another ssd drive with ext4 format mounted on `/etc/export2`

**Comment by harshavardhana** [comment] 2019-08-09 05:51
Can you provide your MinIO server command line?

**Comment by ahmadalli** [comment] 2019-08-09 05:55
I've used systemd service for it: https://github.com/minio/minio-service/blob/master/linux-systemd/distributed/minio.service

with this: `/etc/default/minio`
```
# Remote volumes to be used for MinIO server.
MINIO_VOLUMES=http://minio.ss{1...3}/mnt/export{1...2}
# Use if you want to run MinIO on a custom port.
MINIO_OPTS="--address :80"
# Access Key of the server.
MINIO_ACCESS_KEY=...
# Secret key of the server.
MINIO_SECRET_KEY=...
```

**Comment by harshavardhana** [comment] 2019-08-09 05:57
Is your disk mounted at /mnt/export1 and /mnt/export2 ?

**Comment by ahmadalli** [comment] 2019-08-09 06:00
`/mnt/export1` is my root disk and the second disk is mounted on `/mnt/export2`

**Comment by ahmadalli** [comment] 2019-08-09 06:05
after restarting minio service, there's still some load (while this instance is not being used at all) on that 2 servers. is it because the cluster is rebalancing and syncing?

**Comment by harshavardhana** [comment] 2019-08-09 06:09
It is because it is crawling to check disk usage on your first disk, if you provide first disk an actual disk it won't crawl and you won't see the load. 

The load will reduce after the usage routine has completed..

**Comment by ahmadalli** [comment] 2019-08-09 06:12
so if I switch `/mnt/export2` with `/mnt/export1`, export1 will become my actual disk and the initial load won't happen?

**Comment by harshavardhana** [comment] 2019-08-09 06:25
No you need them to be two separate disks..  you need actual disk at /mnt/export1, currently it is a sub-directory on your root path /

**Comment by ahmadalli** [comment] 2019-08-09 06:28
ok I'll add another disks to servers and test the cluster again

**Comment by ahmadalli** [comment] 2019-08-13 09:29
I've added another disk. now I have two disks mounted on `/mnt/export1` and `/mnt/export2`. after using `rclone source:bucket dest:bucket --transfers=128 --checkers=128` one of my nodes is having load of `90`

**Comment by ahmadalli** [comment] 2019-08-13 09:36
this time after stopping the transfer the load returned to normal

**Comment by ahmadalli** [comment] 2019-08-17 12:40
I restarted minio on all servers and left system alone for a while (without any load on minio cluster) and when I checked back, two of my has 36 and 44 load

this is my atop results:

minio.ss1:
![image](https://user-images.githubusercontent.com/2167301/63211832-bfeb8980-c111-11e9-85c1-d83f84c416cf.png)

minio.ss2:
![image](https://user-images.githubusercontent.com/2167301/63211835-c7ab2e00-c111-11e9-859d-9a87d4db9283.png)

minio.ss3:
![image](https://user-images.githubusercontent.com/2167301/63211838-d4c81d00-c111-11e9-961e-9c10a10a4f87.png)

**Comment by ahmadalli** [comment] 2019-08-17 13:37
I just found out that the hards are not ssd (sorry I hadn't double checked). I'll report back after adding ssds

**Comment by ahmadalli** [comment] 2019-08-19 04:51
I'm not sure if it's ok even on hdd, these are my disk usages on each node while there's no load on the minio cluster:

node 1 is fine
node 2, load 470:
![image](https://user-images.githubusercontent.com/2167301/63239877-837b7300-c262-11e9-9456-801626088d1d.png)

node 3, load 580:
![image](https://user-images.githubusercontent.com/2167301/63239894-9c842400-c262-11e9-873a-32bd89888bd5.png)

**Comment by fwessels** [comment] 2019-08-20 17:40
Are there hardware differences between the nodes: CPU, memory (RAM), networking? 

Can you clarify whether the loads goes down after the transfer? 

What may also help is to have a load balancer in front on the minio nodes -- if you have configured eg. `mc host config` to just a single node (single IP address), then that node will take the full hit in terms of doing the erasure coding etc. and it would be better if this was equally balanced between all nodes.

**Comment by ahmadalli** [comment] 2019-08-21 09:31
the CPU and memory and networking is the same on all three nodes (8GB RAM and two Intel Xeon E5-2620 0 @ 2.00GHz CPUs)

also there's no transfer running on cluster. I run `service minio start` on all ndoes, wait for a few hours and this happens

I'm using dns load balancing between hosts

**Comment by fwessels** [comment] 2019-08-21 21:33
Is it possible to increase the amount of RAM to for example 32 or 64 GB?

8 GB is pretty much on the low side (given that today even eg. a Raspberry Pi 4 already has 4 GB of RAM)

**Comment by roboticsexpert** [comment] 2019-08-21 21:41
it's not consuming more that 1gig ... @fwessels 

i don't understand how that can be related to the memory

**Comment by fwessels** [comment] 2019-08-21 21:49
Your memory is definitely on the low side (whereas the other specs seem normal) and we are not seeing this behaviour in other situations -- so it may be related to memory, swapping, maybe another process consuming a lot of memory, etc.

**Comment by harshavardhana** [comment] 2019-08-22 09:29
@ahmadalli can you test the latest release? - we have made some improvements in terms of healing.

**Comment by ahmadalli** [comment] 2019-08-22 13:10
@harshavardhana sure. I'll report back the results

**Comment by ahmadalli** [comment] 2019-08-24 14:54
unfortunately our team decided to move on ceph for that matter. sorry I can't provide more info. 
Thanks for your help

**Comment by harshavardhana** [comment] 2019-08-24 17:06
Closing this issue as non reproducible..

**Closed as completed by harshavardhana** 2019-08-24 17:06 UTC
Labels: working as intended, community, priority: medium, incomplete info
