### ISSUE TITLE
[resolved] Virtual-host style is broken with latest release

### ISSUE THREAD

**Issue by detoxhby** [minio/minio#10007] opened 2020-07-10 15:03 UTC
Virtual-host style resolution does not work, no matter of the configuration or permissions. Using different region also irrelevant.

This is a regression as `RELEASE.2020-06-22T03-12-50Z` works fine.

## Expected Behavior
 - export MINIO_DOMAIN=mydomain
 - requests against sub.mydomain.com could handle the `sub` bucket

## Current Behavior
- for every permutation of settings for domain, the following error occours for requests
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Resource>/</Resource><Region>us-east-1</Region><RequestId>16206B832EE1CC1C</RequestId><HostId>807cc10c-af37-49a2-b8eb-6f18ed120dab</HostId></Error>
```

## Possible Solution
downgrade

## Regression
Yes

## Your Environment
* Version used: RELEASE.2020-07-02T00-15-09Z
* Operating System and version (`uname -a`): SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2020-07-10 15:37
Do you have sub bucket available?

**Comment by detoxhby** [comment] 2020-07-10 16:22
I didn't test sub buckets (nor had any).

(mainly because all of the applications die while trying to get the main one and receive error 404)

**Comment by harshavardhana** [comment] 2020-07-10 17:12
This is because of an upstream regression with gorilla/mux introduced here https://github.com/gorilla/mux/pull/447#pullrequestreview-446563877

**Comment by harshavardhana** [comment] 2020-07-11 09:26
Fixed with the latest release. Please read the release notes before upgrade @detoxhby

**Closed as completed by harshavardhana** 2020-07-11 09:26 UTC
Labels: community, fixed, priority: high
