### ISSUE TITLE
how to extract zip file

### ISSUE THREAD

**Issue by yoyomule** [minio/minio#7682] opened 2019-05-22 09:46 UTC
Hello, if  upload a zip file to the minio, can extract the zip file in minio and return an address?

**Comment by nitisht** [comment] 2019-05-22 09:51
There is no S3 API to do so, you'll need to use some third party client to extract the file, closing the issue as working as intended. Feel free to reach out on slack for more such questions

**Closed as completed by nitisht** 2019-05-22 09:51 UTC
Labels: working as intended, community
