### ISSUE TITLE
Object in Webhook events is inconsistent

### ISSUE THREAD

**Issue by mindhash** [minio/minio#8342] opened 2019-10-01 07:14 UTC
We are using webhooks to maintain a rolling avg of bucket sizes.    

## Expected Behavior

The object (json key in event) should contain size of the deleted object.

## Current Behavior

The object key (in events json) is inconsistent across event types. For a delete event, the object size is missing. 

## Possible Solution

Add object attributes (e.g. size) consistently across event types. 

## Steps to Reproduce (for bugs)

1. Configure a webhook with mc config 
2. Setup a bucket notification
3. Upload an object to bucket 
4. Delete the uploaded object (in 3)
5. Review the JSON on receiver side or in queue dir (if receiver is down)

## Your Environment

* Version used (`minio version`):
Version: 2019-09-05T23:24:38Z
Release-Tag: RELEASE.2019-09-05T23-24-38Z
Commit-ID: b52a3e523cc3c4debc0ea2f86386377df5355c81

* Environment name and version (e.g. nginx 1.9.1):
myminio

* Server type and version:
macbook pro 
* Operating System and version (`uname -a`):
osx Darwin Kernel Version 17.7.0
* Link to your project:

**Comment by nitisht** [comment] 2019-10-01 07:18
Thanks we'll take a look @mindhash

**Comment by harshavardhana** [comment] 2019-10-01 15:36
This is as per AWS S3 requirements DeleteObject doesn't have any size field on purpose because Size is not interpreted. 

We won't add extra information unless AWS will add here. This is working as intended.

**Comment by kannappanr** [comment] 2019-10-01 16:55
@mindhash Closing this issue as working as intended. Please feel free to reach out to us at https://slack.min.io for further questions on this.

**Closed as completed by kannappanr** 2019-10-01 16:55 UTC
Labels: working as intended, community, triage
