### ISSUE TITLE
Expired Objects are not deleted from Minio even after setting Lifecycle Configuration

### ISSUE THREAD

**Issue by mohandass-pat** [minio/minio#11311] opened 2021-01-20 09:45 UTC
Expired files are not removed from Minio even after setting Lifecycle Configuration

## Expected Behavior
The objects should be removed from minio after 24 hrs if we set ilm expiry time as 1 day.

## Current Behavior
The objects are not removed from minio even after 6days.

## Example
I have a bucket named as "test-mohan-bucket"
I used this command to set expiry date `./mc ilm add --expiry-days "1" dev-minio/test-mohan-bucket/`

## Attachments

I also attached the ilm details and stat also in below images.
![Screenshot from 2021-01-20 15-13-39](https://user-images.githubusercontent.com/43599092/105156656-227c5c80-5b32-11eb-9fff-c2befdaa762c.png)
![Screenshot from 2021-01-20 15-14-26](https://user-images.githubusercontent.com/43599092/105156784-4c358380-5b32-11eb-84ff-1791e43d90f4.png)

Please kindly help me to resolve this issue.

**Comment by harshavardhana** [comment] 2021-01-20 09:46
Closing as duplicate of #11210

**Closed as completed by harshavardhana** 2021-01-20 09:46 UTC
Labels: duplicate, community
