### ISSUE TITLE
using javascript aws-sdk and AssumeRole for accessing MinIO 

### ISSUE THREAD

**Issue by thomaslange24** [minio/minio#7749] opened 2019-06-05 16:05 UTC
Hi, i need to use the javascript aws-sdk accessing MinIO with PutObject function. But instead of using direct credentials i would like to use the AssumeRole API like in https://github.com/minio/minio/blob/master/docs/sts/assume-role.md but using the javascript sdk. I tried it myself but ended confused about the different parameters the AssumeRole function needs and how to use the resulting credentials for accessing Minio. Can you give an example for that?

**Comment by kannappanr** [comment] 2019-06-06 13:11
Closing this issue as duplicate of https://github.com/minio/cookbook/issues/257

**Closed as completed by kannappanr** 2019-06-06 13:11 UTC
Labels: duplicate, community, priority: medium
