### ISSUE TITLE
stress testing

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3408] opened 2016-12-06 16:25 UTC
https://github.com/dcharbonnier/minio/tree/master/terraform/limited-bandwidth

running `node /root/index.js` on the 'server' will upload (try to...) 500 100Mo files, for now the test fail after ~30

expected : the server does not crash ;-)

**Comment by hackintoshrao** [comment] 2016-12-06 16:36
@dcharbonnier : Can you give access to the machine or logs ? Will investigate.

**Comment by dcharbonnier** [comment] 2016-12-06 17:22
if you take machines with  2Go of ram it take 10s, let's say it's "normal" but with machines of 8Go it crash after 5 minutes, on the terraform, replace the VC1S type by a C2S and you will get 8Go of ram.


```
[  745.483030] dockerd invoked oom-killer: gfp_mask=0x24201ca, order=0, oom_score_adj=-500
[  745.483035] dockerd cpuset=/ mems_allowed=0
[  745.483042] CPU: 0 PID: 6356 Comm: dockerd Not tainted 4.5.7-docker-4 #1
[  745.483045] Hardware name: Online Labs SR/SR, BIOS 00.00.00.0007 03/04/2016
[  745.483047]  0000000000000000 ffff8802746efb10 ffffffff8133f52e ffff880079144280
[  745.483051]  ffff880079144280 ffff8802746efb78 ffffffff81131ab3 ffffffff81c82cb0
[  745.483055]  ffff8802746efbd8 ffff8802746efbd8 0000000000000202 ffff8802746efb50
[  745.483059] Call Trace:
[  745.483067]  [<ffffffff8133f52e>] dump_stack+0x63/0x85
[  745.483073]  [<ffffffff81131ab3>] dump_header.isra.5+0x4f/0x1b9
[  745.483078]  [<ffffffff8177f919>] ? _raw_spin_unlock_irqrestore+0x9/0x10
[  745.483083]  [<ffffffff810e7c71>] oom_kill_process+0x301/0x3f0
[  745.483086]  [<ffffffff810e7601>] ? find_lock_task_mm+0x31/0x70
[  745.483090]  [<ffffffff810e8061>] out_of_memory+0x2a1/0x2e0
[  745.483094]  [<ffffffff810ec60f>] __alloc_pages_nodemask+0x91f/0x960
[  745.483098]  [<ffffffff81344700>] ? __radix_tree_lookup+0x90/0xa0
[  745.483102]  [<ffffffff810e6c12>] filemap_fault+0x3a2/0x4c0
[  745.483107]  [<ffffffff811b2871>] ext4_filemap_fault+0x31/0x50
[  745.483111]  [<ffffffff81106519>] __do_fault+0x59/0xb0
[  745.483114]  [<ffffffff8110b43a>] handle_mm_fault+0xaaa/0x15e0
[  745.483119]  [<ffffffff8100b5c9>] ? read_tsc+0x9/0x20
[  745.483124]  [<ffffffff81042c37>] __do_page_fault+0x157/0x360
[  745.483128]  [<ffffffff810abb3d>] ? SyS_futex+0x6d/0x150
[  745.483131]  [<ffffffff81042e92>] do_page_fault+0x22/0x30
[  745.483135]  [<ffffffff817815f8>] page_fault+0x28/0x30
[  745.483138] Mem-Info:
[  745.483145] active_anon:1976038 inactive_anon:5519 isolated_anon:0
                active_file:132 inactive_file:0 isolated_file:5
                unevictable:364 dirty:0 writeback:0 unstable:0
                slab_reclaimable:1916 slab_unreclaimable:4481
                mapped:352 shmem:5561 pagetables:4451 bounce:0
                free:15925 free_pcp:432 free_cma:0
[  745.483156] DMA free:15840kB min:124kB low:152kB high:184kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15988kB managed:15840kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:0kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
[  745.483158] lowmem_reserve[]: 0 1911 7913 7913
[  745.483168] DMA32 free:29940kB min:15852kB low:19812kB high:23776kB active_anon:1898476kB inactive_anon:3768kB active_file:52kB inactive_file:0kB unevictable:744kB isolated(anon):0kB isolated(file):20kB present:2042880kB managed:1966132kB mlocked:0kB dirty:12kB writeback:0kB mapped:380kB shmem:3800kB slab_reclaimable:2060kB slab_unreclaimable:3896kB kernel_stack:672kB pagetables:4240kB unstable:0kB bounce:0kB free_pcp:1396kB local_pcp:120kB free_cma:0kB writeback_tmp:0kB pages_scanned:8484 all_unreclaimable? yes
[  745.483171] lowmem_reserve[]: 0 0 6002 6002
[  745.483180] Normal free:17920kB min:49556kB low:61944kB high:74332kB active_anon:6005676kB inactive_anon:18308kB active_file:476kB inactive_file:0kB unevictable:712kB isolated(anon):0kB isolated(file):0kB present:6291456kB managed:6146384kB mlocked:0kB dirty:0kB writeback:0kB mapped:1028kB shmem:18444kB slab_reclaimable:5604kB slab_unreclaimable:14028kB kernel_stack:2176kB pagetables:13564kB unstable:0kB bounce:0kB free_pcp:332kB local_pcp:68kB free_cma:0kB writeback_tmp:0kB pages_scanned:3768 all_unreclaimable? yes
[  745.483183] lowmem_reserve[]: 0 0 0 0
[  745.483187] DMA: 0*4kB 0*8kB 0*16kB 1*32kB (U) 1*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15840kB
[  745.483202] DMA32: 334*4kB (UME) 343*8kB (UME) 279*16kB (UME) 111*32kB (UME) 71*64kB (UME) 46*128kB (UME) 25*256kB (UE) 2*512kB (E) 0*1024kB 0*2048kB 0*4096kB = 29952kB
[  745.483217] Normal: 903*4kB (UME) 351*8kB (UME) 285*16kB (UME) 70*32kB (UME) 32*64kB (UME) 19*128kB (UME) 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 17700kB
[  745.483232] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[  745.483234] 6036 total pagecache pages
[  745.483237] 0 pages in swap cache
[  745.483239] Swap cache stats: add 0, delete 0, find 0/0
[  745.483240] Free swap  = 0kB
[  745.483242] Total swap = 0kB
[  745.483243] 2087581 pages RAM
[  745.483245] 0 pages HighMem/MovableOnly
[  745.483247] 55492 pages reserved
[  745.483248] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[  745.483254] [ 1828]     0  1828      443       17       3       2        0         -1000 @xnbd-client
[  745.483258] [ 2643]     0  2643    10628      285      23       3        0         -1000 systemd-udevd
[  745.483261] [ 2650]     0  2650     3052      778      10       3        0             0 haveged
[  745.483264] [ 2656]     0  2656     8820      287      18       3        0             0 systemd-journal
[  745.483268] [ 3589]     0  3589    23842       34      13       3        0             0 lxcfs
[  745.483271] [ 3596]     0  3596     5026       41      13       3        0             0 systemd-logind
[  745.483275] [ 3603]   109  3603    10727      105      25       3        0          -900 dbus-daemon
[  745.483278] [ 4902]   108  4902    64100      130      26       3        0             0 rsyslogd
[  745.483281] [ 4911]     0  4911     6934       67      17       3        0             0 cron
[  745.483285] [ 5078]     0  5078    16404      184      35       3        0         -1000 sshd
[  745.483288] [ 5100]     0  5100     3667       36      11       3        0             0 agetty
[  745.483291] [ 5101]     0  5101     3621       35      11       3        0             0 agetty
[  745.483295] [ 5125]     0  5125     4033      219      10       3        0             0 dhclient
[  745.483298] [ 6212]   106  6212    10090      151      20       4        0             0 ntpd
[  745.483301] [ 6326]     0  6326   183635     5685      78       5        0          -500 dockerd
[  745.483305] [ 6355]     0  6355    91347      625      29       5        0          -500 docker-containe
[  745.483308] [ 7483]     0  7483    68657      166      22       5        0          -500 docker-containe
[  745.483312] [ 7498]     0  7498  2036958  1964775    3935      12        0             0 minio
[  745.483315] [ 7539]     0  7539    23797      233      50       3        0             0 sshd
[  745.483318] [ 7747]     0  7747     5854      371      15       3        0             0 nload
[  745.483322] [ 7748]     0  7748    23797      232      48       3        0             0 sshd
[  745.483325] [ 7957]     0  7957     6265      280      16       3        0             0 htop
[  745.483328] Out of memory: Kill process 7498 (minio) score 968 or sacrifice child
[  745.573282] Killed process 7498 (minio) total-vm:8147832kB, anon-rss:7859100kB, file-rss:0kB, shmem-rss:0kB
[  745.892248] systemd-journal invoked oom-killer: gfp_mask=0x24201ca, order=0, oom_score_adj=0
[  745.892253] systemd-journal cpuset=/ mems_allowed=0
[  745.892260] CPU: 1 PID: 2656 Comm: systemd-journal Not tainted 4.5.7-docker-4 #1
[  745.892262] Hardware name: Online Labs SR/SR, BIOS 00.00.00.0007 03/04/2016
[  745.892265]  0000000000000000 ffff880276b23b10 ffffffff8133f52e ffff880276b28800
[  745.892269]  ffff880276b28800 ffff880276b23b78 ffffffff81131ab3 ffffffff81c82cb0
[  745.892273]  ffff880276b23bd8 ffff880276b23bd8 0000000000000202 ffff880276b23b50
[  745.892277] Call Trace:
[  745.892285]  [<ffffffff8133f52e>] dump_stack+0x63/0x85
[  745.892290]  [<ffffffff81131ab3>] dump_header.isra.5+0x4f/0x1b9
[  745.892295]  [<ffffffff8177f919>] ? _raw_spin_unlock_irqrestore+0x9/0x10
[  745.892300]  [<ffffffff810e7c71>] oom_kill_process+0x301/0x3f0
[  745.892304]  [<ffffffff810e7601>] ? find_lock_task_mm+0x31/0x70
[  745.892307]  [<ffffffff810e8061>] out_of_memory+0x2a1/0x2e0
[  745.892311]  [<ffffffff810ec60f>] __alloc_pages_nodemask+0x91f/0x960
[  745.892315]  [<ffffffff81344700>] ? __radix_tree_lookup+0x90/0xa0
[  745.892319]  [<ffffffff810e6c12>] filemap_fault+0x3a2/0x4c0
[  745.892324]  [<ffffffff811b2871>] ext4_filemap_fault+0x31/0x50
[  745.892327]  [<ffffffff81106519>] __do_fault+0x59/0xb0
[  745.892331]  [<ffffffff8110b43a>] handle_mm_fault+0xaaa/0x15e0
[  745.892335]  [<ffffffff81172148>] ? ep_poll+0x178/0x330
[  745.892339]  [<ffffffff81042c37>] __do_page_fault+0x157/0x360
[  745.892343]  [<ffffffff81042e92>] do_page_fault+0x22/0x30
[  745.892347]  [<ffffffff817815f8>] page_fault+0x28/0x30
[  745.892349] Mem-Info:
[  745.892355] active_anon:1976038 inactive_anon:5519 isolated_anon:0
                active_file:88 inactive_file:0 isolated_file:0
                unevictable:364 dirty:0 writeback:0 unstable:0
                slab_reclaimable:1916 slab_unreclaimable:4481
                mapped:354 shmem:5561 pagetables:4451 bounce:0
                free:16478 free_pcp:0 free_cma:0
[  745.892366] DMA free:15840kB min:124kB low:152kB high:184kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15988kB managed:15840kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:0kB slab_reclaimable:0kB slab_unreclaimable:0kB kernel_stack:0kB pagetables:0kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? yes
[  745.892368] lowmem_reserve[]: 0 1911 7913 7913
[  745.892378] DMA32 free:31280kB min:15852kB low:19812kB high:23776kB active_anon:1898476kB inactive_anon:3768kB active_file:4kB inactive_file:0kB unevictable:744kB isolated(anon):0kB isolated(file):0kB present:2042880kB managed:1966132kB mlocked:0kB dirty:12kB writeback:0kB mapped:388kB shmem:3800kB slab_reclaimable:2060kB slab_unreclaimable:3896kB kernel_stack:640kB pagetables:4240kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:1108 all_unreclaimable? yes
[  745.892380] lowmem_reserve[]: 0 0 6002 6002
[  745.892390] Normal free:18792kB min:49556kB low:61944kB high:74332kB active_anon:6005676kB inactive_anon:18308kB active_file:520kB inactive_file:0kB unevictable:712kB isolated(anon):0kB isolated(file):0kB present:6291456kB managed:6146384kB mlocked:0kB dirty:0kB writeback:0kB mapped:1028kB shmem:18444kB slab_reclaimable:5604kB slab_unreclaimable:14028kB kernel_stack:2096kB pagetables:13564kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:2532 all_unreclaimable? no
[  745.892392] lowmem_reserve[]: 0 0 0 0
[  745.892396] DMA: 0*4kB 0*8kB 0*16kB 1*32kB (U) 1*64kB (U) 1*128kB (U) 1*256kB (U) 0*512kB 1*1024kB (U) 1*2048kB (M) 3*4096kB (M) = 15840kB
[  745.892411] DMA32: 575*4kB (UME) 359*8kB (UME) 293*16kB (UME) 115*32kB (UME) 70*64kB (UME) 46*128kB (UME) 24*256kB (UE) 3*512kB (UE) 0*1024kB 0*2048kB 0*4096kB = 31588kB
[  745.892427] Normal: 904*4kB (UME) 359*8kB (UME) 301*16kB (UME) 94*32kB (UME) 33*64kB (UME) 19*128kB (UME) 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 18856kB
[  745.892441] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[  745.892443] 6038 total pagecache pages
[  745.892446] 0 pages in swap cache
[  745.892448] Swap cache stats: add 0, delete 0, find 0/0
[  745.892449] Free swap  = 0kB
[  745.892451] Total swap = 0kB
[  745.892452] 2087581 pages RAM
[  745.892454] 0 pages HighMem/MovableOnly
[  745.892456] 55492 pages reserved
[  745.892457] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[  745.892463] [ 1828]     0  1828      443       17       3       2        0         -1000 @xnbd-client
[  745.892467] [ 2643]     0  2643    10628      285      23       3        0         -1000 systemd-udevd
[  745.892470] [ 2650]     0  2650     3052      778      10       3        0             0 haveged
[  745.892474] [ 2656]     0  2656     8820      287      18       3        0             0 systemd-journal
[  745.892477] [ 3589]     0  3589    23842       34      13       3        0             0 lxcfs
[  745.892480] [ 3596]     0  3596     5026       41      13       3        0             0 systemd-logind
[  745.892484] [ 3603]   109  3603    10727      105      25       3        0          -900 dbus-daemon
[  745.892487] [ 4902]   108  4902    64100      130      26       3        0             0 rsyslogd
[  745.892490] [ 4911]     0  4911     6934       67      17       3        0             0 cron
[  745.892494] [ 5078]     0  5078    16404      184      35       3        0         -1000 sshd
[  745.892497] [ 5100]     0  5100     3667       36      11       3        0             0 agetty
[  745.892500] [ 5101]     0  5101     3621       35      11       3        0             0 agetty
[  745.892504] [ 5125]     0  5125     4033      219      10       3        0             0 dhclient
[  745.892507] [ 6212]   106  6212    10090      151      20       4        0             0 ntpd
[  745.892511] [ 6326]     0  6326   183635     5685      78       5        0          -500 dockerd
[  745.892514] [ 6355]     0  6355    91347      625      29       5        0          -500 docker-containe
[  745.892517] [ 7483]     0  7483    68657      166      22       5        0          -500 docker-containe
[  745.892521] [ 7531]     0  7498  2036958  1965322    3935      12        0             0 minio
[  745.892524] [ 7539]     0  7539    23797      233      50       3        0             0 sshd
[  745.892528] [ 7747]     0  7747     5854      371      15       3        0             0 nload
[  745.892531] [ 7748]     0  7748    23797      232      48       3        0             0 sshd
[  745.892535] [ 7957]     0  7957     6265      280      16       3        0             0 htop
[  745.892537] Out of memory: Kill process 7961 (minio) score 969 or sacrifice child
[  745.982483] Killed process 7531 (minio) total-vm:8147832kB, anon-rss:7861288kB, file-rss:0kB, shmem-rss:0kB
root@minio-2:~#
```

**Comment by dcharbonnier** [comment] 2016-12-06 17:23
this one is #3403

**Comment by hackintoshrao** [comment] 2016-12-06 17:48
Here's are some useful data from the preliminary information gathering, 

- [Here](https://gist.github.com/hackintoshrao/d17a9c3a11dd62288d7bacf555a88427) is the script which generated load on the server.
- The first set of nodes on which this issue was reported has 2GB memory each. And then it was tried with 8GB and the nodes stood well for more time with greater memory.
- Need to run mem profile first to identify the actual hotspots in the code and then should optimize them.
- Need to take this profile at varying intensity load of same nature.
- Here is a note on runtime mem behavior of a Golang program. 

```
 When the GC does collect memory the profile shrinks,
 but no memory is returned to the system.
 Your future allocations will try to use memory from the pool 
 of previously collected objects before asking the system for more.

 From the outside, this means that your program's memory 
 use will either be increasing, or staying level. What the outside
 system presents as the "Resident Size" of your program is the
 number of bytes of RAM is assigned to your program whether
 it's holding in-use go values or collected ones.
```

**Comment by harshavardhana** [comment] 2016-12-07 11:44
Closing as duplicate of #3403

**Closed as completed by harshavardhana** 2016-12-07 11:44 UTC
