### ISSUE TITLE
Using GetPreSignedURL method with AWS S3 SDK and setting content type results in SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by albracko** [minio/minio#20058] opened 2024-07-09 07:55 UTC
When using AWS S3 SDK there seems to be a bug in verification of the signature it once you set `ContentType` property on `GetPreSignedUrlRequest`. If this property is not set everything works fine, but the issue is that all content in the bucket is now without `ContentType`.

## Expected Behavior
Setting `ContentType` property on `GetPreSignedUrlRequest` object should result in successful upload of the object to minio

## Current Behavior
`SignatureDoesNotMatch` error code is returned if this property is set

## Your Environment

* Version used : minio version RELEASE.2024-07-04T14-25-45Z (commit-id=107d951893c3e02982f200dcbb09d9e953c2b73f)
* Server setup and configuration: runing inside docker with default settings
* Operating System and version : docker version 4.30.0 
* Development language: .NET C#

**Comment by vadmeste** [comment] 2024-07-09 09:51
@albracko it would be great if you can share a sample reproducer code

**Comment by klauspost** [comment] 2024-07-09 10:48
Yeah, or `mc admin trace -v ALIAS` of your server when you send the request.

**Comment by harshavardhana** [comment] 2024-07-09 14:49
Duplicate of 

https://github.com/minio/minio/issues/19887#issuecomment-2152031589

**Closed as completed by harshavardhana** 2024-07-09 14:49 UTC
Labels: working as intended, community
