### ISSUE TITLE
goroutine running on other thread; stack unavailable while uploading via S3v4

### ISSUE THREAD

**Issue by rsoutar** [minio/minio#4429] opened 2017-05-25 07:59 UTC
I got an issue with minio when running 12 disks with 1 node. I have upload a files to minio using S3 api. I kept crashing daily.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
error

goroutine 29074998 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29074941 [runnable]:
os.Open(0xf26ab90820, 0x49, 0x14f3b40, 0xc67e40, 0xc420438360)
/home/builder/.gimme/versions/go1.7.5.linux.amd64/src/os/file.go:249
github.com/minio/minio/cmd.readDir(0xf26ab90820, 0x49, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/builder/mygo/src/github.com/minio/minio/cmd/posix-list-dir-nix.go:119 +0x12a
github.com/minio/minio/cmd.(*posix).ListDir(0xc420402e70, 0xdf3b5f, 0xe, 0xf18f1ec540, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/builder/mygo/src/github.com/minio/minio/cmd/posix.go:444 +0x371
github.com/minio/minio/cmd.retryStorage.ListDir(0x12847c0, 0xc420402e70, 0x1, 0xf4240, 0x4c4b40, 0xdf3b5f, 0xe, 0xf18f1ec540, 0x25, 0xf18f1ec564, ...)
/home/builder/mygo/src/github.com/minio/minio/cmd/retry-storage.go:183 +0x72
github.com/minio/minio/cmd.(*retryStorage).ListDir(0xc4201624b0, 0xdf3b5f, 0xe, 0xf18f1ec540, 0x25, 0x25, 0x1, 0x25, 0x25, 0x25)
<autogenerated>:932 +0xaf
github.com/minio/minio/cmd.cleanupDir.func1(0xf18f1ec540, 0x25, 0x24, 0xde7eb5)
/home/builder/mygo/src/github.com/minio/minio/cmd/object-api-common.go:215 +0xe1
github.com/minio/minio/cmd.cleanupDir(0x1284860, 0xc4201624b0, 0xdf3b5f, 0xe, 0xf498fc5590, 0x24, 0x45d9b1, 0xc420144070)
/home/builder/mygo/src/github.com/minio/minio/cmd/object-api-common.go:231 +0x1d1
github.com/minio/minio/cmd.xlObjects.deleteObject.func1(0xc4205420c0, 0xdf3b5f, 0xe, 0xf498fc5590, 0x24, 0xed7a782180, 0xc, 0xc, 0x1, 0x1284860, ...)
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:765 +0x94
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29074981 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29074996 [runnable]:
github.com/minio/minio/cmd.xlObjects.deleteObject.func1(0xc4204360f0, 0xdf3b5f, 0xe, 0xf5471e0f00, 0x24, 0xf32ac8e180, 0xc, 0xc, 0x3, 0x1284860, ...)
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:763
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29075003 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29074945 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29075000 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29074978 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29075004 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

## Your Environment

* Version used (`2017-05-05T01:14:51Z`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version: Supermicro 512GB Memory, 4TB*12 
* Operating System and version (`Linux 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`):
* Link to your project:

**Comment by rsoutar** [comment] 2017-05-25 08:01
I've run dd to see disk performance.
`sudo dd if=/dev/zero of=bigfile bs=1M count=1024 oflag=direct`
`1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 7.34869 s, 146 MB/s`

**Comment by harshavardhana** [comment] 2017-05-25 14:59
Do you have the entire stack @rsoutar ?

**Comment by rsoutar** [comment] 2017-05-25 16:30
Do you mean about the log? 

I only have what I got there. Been running minio using screen.

**Comment by harshavardhana** [comment] 2017-05-25 16:32
> Do you mean about the log?
> 
> I only have what I got there. Been running minio using screen.

what was the exact operation that you were performing? @rsoutar it looks like you were deleting objects if you have a script or tool that you were using this with please let us know.

**Comment by rsoutar** [comment] 2017-05-25 16:46
We have php to convert mp4 to HLS format and upload it to minio which contains around 60-70 small files at a time. There's no delete operation on minio.

**Comment by harshavardhana** [comment] 2017-05-25 16:57
@rsoutar without any delete operations, deleteObject() is never invoked. But stack is clearly mentioning that. I wonder if you do have any rouge process which is doing this.  

```
goroutine 29074981 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29074996 [runnable]:
github.com/minio/minio/cmd.xlObjects.deleteObject.func1(0xc4204360f0, 0xdf3b5f, 0xe, 0xf5471e0f00, 0x24, 0xf32ac8e180, 0xc, 0xc, 0x3, 0x1284860, ...)
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:763
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29075003 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29074945 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6

goroutine 29075000 [running]:
goroutine running on other thread; stack unavailable
created by github.com/minio/minio/cmd.xlObjects.deleteObject
/home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1-object.go:769 +0x1a6
```

Can you share the directory hierarchy with us?

**Comment by rsoutar** [comment] 2017-05-25 17:03
It's [bucket] / Moviename / quality (ie, 360p) / media / files

mello-series/becc-dr-008-0005/360p/5922942f94dcbf000c36a6b6/output.m3u8

**Comment by fwessels** [comment] 2017-05-30 16:23
Please change title to "Error while deleting object"

("goroutine running on other thread; stack unavailable" simply means that the runtime goroutine that is "dumping" the state is not able to print the stack for goroutines that are running on other threads due to not being able to access the stack of that particular thread. So it has nothing to do with being out of memory or something).

**Comment by fwessels** [comment] 2017-05-30 17:28
@rsoutar we are looking into the issue, and we have a couple of questions:
- are you doing the upload of the individual files (70 to 80) per movie in parallel or sequentially?
- are you uploading multiple movies in parallel? 
- is there more call stack? Ie did you scroll upwards or just copied the output of the visible part of the screen?

**Comment by rsoutar** [comment] 2017-06-01 11:09
@fwessels Yes. We upload individual files in parallel. 

I do not have more call stack due to I ran minio using screen. I cannot scroll up. If it ways to run minio and have a separate log file?

**Comment by fwessels** [comment] 2017-06-02 17:37
@rsoutar thanks for the info.

Given the fact that you are uploading in parallel, it may be the case that we are hitting the max number of OS threads (defaults to 10000) and you would see something like this in the top of your error dump:
```
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion
```

We may enhance some design aspects so as to avoid unnecessary creation of OS threads, but it would be good to know if (in your case) you are hitting this limit.

Are you able to compile a version of minio that increases this default (unfortunately there is no environment variable that allows this to be changed)?

It would just involve changing main.go in the root of the project as per:
```
--- a/main.go
+++ b/main.go
@@ -26,6 +26,7 @@ import (
        "fmt"
        "os"
        "runtime"
+ "runtime/debug"
 
        version "github.com/hashicorp/go-version"
        "github.com/minio/mc/pkg/console"
@@ -65,5 +66,7 @@ func main() {
                console.Fatalln("Go runtime version check failed.", err)
        }
 
+ debug.SetMaxThreads(50000)
+
        minio.Main(os.Args)
 }
```

It would be great if you could test with this to see if you keep getting the same errors. Let us know if you need any other assistance.

**Comment by fwessels** [comment] 2017-06-12 16:46
@rsoutar reaching out again, could you do a test with a custom version of minio as described above?

**Comment by deekoder** [comment] 2017-06-16 17:21
@rsoutar closing this issue since we need your help to proceed further on investigating root cause. Please reopen if you have this information and ping us back anytime.

**Closed as completed by deekoder** 2017-06-16 17:21 UTC
Labels: working as intended, priority: high
