### ISSUE TITLE
Error: Unable to initialize IAM sub-system after upgrade and roll back to RELEASE.2021-04-22T15-44-28Z

### ISSUE THREAD

**Issue by titansmc** [minio/minio#13132] opened 2021-09-02 08:11 UTC
I was running `RELEASE.2021-04-22T15-44-28Z` and as per the suggestions in Slack, I have upgraded to the latest version, after start it shows:
```
 Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: config file not found)

Error: Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/: Decrypting config failed madmin: invalid encryption algorithm ID, possibly credentials are incorrect (*fmt.wrapError)
```
(I am not using encryption for Minio)
then the suggestion was to roll back to previous version, but now the problem is that I cannot get the users or policies, with the admin credentials I can see the buckets, but not much more.
 
I also get errors like this:
```
Error: Disk: https://ops-object02.embl.de:443/minio/9  -> chat-gbcs/users/wci6t9gcf3gyuknio14t9p3brr/profile.png/5e0afccc-f3cd-4523-be88-e00e1eebeb7b/part.1 - content hash does not match - expected 3505114a67050b595024513981f7bc163aed51b18c1a9e80db7d619549538d33, got c6213856974ff9eab14c9c68006096e3262d7e96d7009724518d7fc17ec62437 (*errors.errorString)
```

## Expected Behavior
Upgrade would have worked

## Current Behavior
only root user can see the buckets

## Steps to Reproduce (for bugs)
1. from RELEASE.2021-04-22T15-44-28Z upgrade to latest
2.roll back when failing

## Context
I have some users that are not able to connect.

## Regression
don't know

## Your Environment

* Version used (`minio --version`): RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration: CentOS 7 (2 nodes with 96 drives each)
* Operating System and version (`uname -a`): 3.10.0-1127.el7.x86_64

I am attaching the format.json files 
https://oc.embl.de/index.php/s/F1qXZf6S06bZBcS
https://oc.embl.de/index.php/s/PA2AAjt0LQWOBgF

**Comment by harshavardhana** [comment] 2021-09-02 08:25
> * Version used (`minio --version`): RELEASE.2021-04-22T15-44-28Z
> * Server setup and configuration: CentOS 7 (2 nodes with 96 drives each)
> * Operating System and version (`uname -a`): 3.10.0-1127.el7.x86_64

We do not allow rollbacks @titansmc not sure how you upgraded but the upgrade should be seamless, I just tested an upgrade and things seem to work fine. 

Which version to which version did you upgrade to? and what was the reason for upgrade?

**Comment by titansmc** [comment] 2021-09-02 08:34
We upgraded from `RELEASE.2021-04-22T15-44-28Z` to `RELEASE.2021-08-31T05-46-54Z`. I have just replaced the binary and start the servers. The reason for the upgrade was that the total number of disks didn't match the online+offline, so a colleague in the chat suggested me to upgrade, but then I got:
```
 Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: config file not found)

Error: Unable to initialize sub-systems: Unable to migrate all config at .minio.sys/config/: Decrypting config failed madmin: invalid encryption algorithm ID, possibly credentials are incorrect (*fmt.wrapError)
```
he checked with some guys and said better rollback if possible.

**Comment by harshavardhana** [comment] 2021-09-02 10:05
@titansmc that should have never happened can you grab `tar czf <backend>/.minio.sys/config` and share it here?

**Comment by harshavardhana** [comment] 2021-09-02 10:07
To recover from this it is safe to `rm -rf <backend>/.minio.sys/config` and restart both MinIO nodes. Do this once you shut the server down - once done you can upgrade to the latest release.  But make sure to capture the backend files and share here.. 


> ```
> Error: Disk: https://ops-object02.embl.de:443/minio/9  -> chat-gbcs/users/wci6t9gcf3gyuknio14t9p3brr/profile.png/5e0afccc-f3cd-4523-be88-e00e1eebeb7b/part.1 - content hash does not match - expected 3505114a67050b595024513981f7bc163aed51b18c1a9e80db7d619549538d33, got c6213856974ff9eab14c9c68006096e3262d7e96d7009724518d7fc17ec62437 (*errors.errorString)
> ```

This is perfectly fine as long as your objects are readable, they will be healed automatically if they have quorum. 

NOTE: upgrade -> downgrade is not allowed for these reasons alone.

**Comment by titansmc** [comment] 2021-09-02 10:15
is it safe to delete `<backend>/.minio.sys/config` and I will still have users and policies available?
just to recap:
- stop servers
- backup config
- wipe config
- start server
- content and user/policies should be there
- upgrade to latest

**Comment by harshavardhana** [comment] 2021-09-02 16:38
> is it safe to delete `<backend>/.minio.sys/config` and I will still have users and policies available?
> just to recap:
> 
> * stop servers
> * backup config
> * wipe config
> * start server
> * content and user/policies should be there
> * upgrade to latest

Nope unfortunately those parts are gone, if you really want just config to be removed then make sure to only purge `.minio.sys/config/config.json`. 

There is no guarantee that IAM users are still there, you can try.  It is easier to purge everything in that folder and recreate all the users/policies again assuming you have some backup.

**Comment by titansmc** [comment] 2021-09-03 08:20
so there is no way to extract users and policies from the config directory  before wiping it out?

**Comment by harshavardhana** [comment] 2021-09-03 09:24
> so there is no way to extract users and policies from the config directory before wiping it out?

There may be a way to but you need to share it with us so that we can try to extract it in some manner. But the safest is wipe it and restart - recreate them using `mc admin user add ...`

I have locally tried to reproduce but I can't reproduce - so it means that you did something that led to this on your end. Either you had some issue on the drives that was before the upgrade. 

Or just that you upgraded one server while the other was not yet upgraded something like that.

**Comment by harshavardhana** [comment] 2021-09-16 16:00
> > so there is no way to extract users and policies from the config directory before wiping it out?
> 
> There may be a way to but you need to share it with us so that we can try to extract it in some manner. But the safest is wipe it and restart - recreate them using `mc admin user add ...`
> 
> I have locally tried to reproduce but I can't reproduce - so it means that you did something that led to this on your end. Either you had some issue on the drives that was before the upgrade.
> 
> Or just that you upgraded one server while the other was not yet upgraded something like that.

Assuming that this cluster has been manually recovered, closing this issue. 

If you have the data that I requested please share with us.

**Closed as completed by harshavardhana** 2021-09-16 16:00 UTC
Labels: community, waiting for info
