### ISSUE TITLE
[not our bug] Can't connect to GCS (Google cloud storage) using Minio .NET client

### ISSUE THREAD

**Issue by katycodesstuff** [minio/minio#10173] opened 2020-07-31 10:00 UTC
## Expected Behavior
Should be able to connect via MinioClient to S3-compatible storage GCS and upload/read files from bucket.

## Current Behavior
Any method call from client throws exception with message "MinIO API responded with message=The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.""

## Possible Solution
I've explored specifying region, using user keys and service account keys. Data length should be correct as the MinioClient is working when I connect to Minio Server and Amazon AWS. So I'm thinking MinioClient is generating an incorrect signature for GCS. Minio CLI is able to read & write to GCS.

## Steps to Reproduce (for bugs)
Example request to list buckets. (Any request throws this exception)
 "MinIO API responded with message=The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.""

`var client = new MinioClient("storage.googleapis.com",
                "myaccesskey",
                "mysecretkey").WithSSL();
 var list = await client.ListBucketsAsync();`

## Context
Attempting to read & write to GCS bucket from my C# .NET app.

## Regression
No

## Your Environment

* Version used: NuGet - "Minio" Version="3.1.13" and "3.1.10"
* Server setup and configuration: N/A (attempting to use MinioClient with GCS directly)
* Operating System and version (`uname -a`): N/A

**Comment by harshavardhana** [comment] 2020-07-31 15:40
Duplicate of the same issue in minio-dotnet project 

https://github.com/minio/minio-dotnet/issues/447

**Closed as completed by harshavardhana** 2020-07-31 15:40 UTC
Labels: duplicate
