### ISSUE TITLE
NoSuchBucket error since RELEASE.2019-04-04T18-31-46Z

### ISSUE THREAD

**Issue by stefan-as** [minio/minio#7497] opened 2019-04-08 15:17 UTC
## Expected Behavior
Find all valid buckets, as Minio did before RELEASE.2019-04-04T18-31-46Z

## Current Behavior
Some buckets are not found any longer.

## Steps to Reproduce (for bugs)
1. name a bucket `tests-u7qDIFZFQoWRbWAvjPXzLA`
2. Upgrade to minio.RELEASE.2019-04-04T18-31-46Z

## Context
Using minio as an elasticsearch S3 repository, snapshot backend fails since RELEASE.2019-04-04T18-31-46Z. Formerly valid buckets are not found any longer and snapshot routine fails in consequence.

## Regression
Yes, worked with RELEASE.2019-03-27T22-35-21Z

## Your Environment
* Version used (`minio version`):
```
Version: 2019-04-04T18:31:46Z
Release-Tag: RELEASE.2019-04-04T18-31-46Z
Commit-ID: 0146a9d592194c2141851565ba7bb8bf90351b8b
```
* Operating System and version (`uname -a`):
`4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment] 2019-04-08 15:20
> * name a bucket `tests-u7qDIFZFQoWRbWAvjPXzLA`

These bucket names were never valid @stefan-as and it cannot be allowed as well it is part of a stricter validation which we had to add due to security requirements.

**Comment by stefan-as** [comment] 2019-04-08 15:33
Filed a bug report for elasticsearch https://github.com/elastic/elasticsearch/issues/40968

**Comment by harshavardhana** [comment] 2019-04-08 15:43
Capitalized bucket names are deprecated in AWS as well other than the us-east-1 regions, we do allow existing buckets though with capitalized names. 

But do not allow creating new ones which do not follow the AWS spec.

**Comment by kannappanr** [comment] 2019-04-09 18:42
@stefan-as Closing this issue as working as intended. Please feel free to reach out to us if you have more questions.

**Closed as completed** 2019-04-09 18:42 UTC
Labels: working as intended, community, priority: medium

**Comment by stefan-as** [comment] 2019-05-07 08:23
Issue is solved by the current release `RELEASE.2019-05-02T19-07-09Z`. Root cause was not the bucket name itself, but broken virtual host style mode. In consequence, buckets from Host header were not recognized and valid object names were treated as bucket names.

**Comment by sofib** [comment] 2019-09-25 09:16
I get the same host header issue for signed urls on version RELEASE.2019-09-18T21-55-05Z

**Comment by harshavardhana** [comment] 2019-09-25 09:25
> I get the same host header issue for signed urls on version RELEASE.2019-09-18T21-55-05Z

Please open a new issue with more details.
