### ISSUE TITLE
Can't run minio chart in distributed mode

### ISSUE THREAD

**Issue by pawelbojanowski** [minio/minio#8733] opened 2020-01-02 12:41 UTC
I cannot make minio running successfully (without constant restart) in my k8s cluster.

## Expected Behavior
I'm trying to deploy stable/minio chart with minimal settings, just `mode: distributed`

## Current Behavior
Helm install is successful, but pods got into restart loop. I see this in logs:
```
Error: lookup minio-test-3.minio-test-svc.default.svc.cluster.local on 10.128.168.3:53: no such host
minio-test-0 minio        host=minio-test-3.minio-test-svc.default.svc.cluster.local, elapsedTime=1 minute elapsed
minio-test-0 minio        5: cmd/endpoint.go:344:cmd.Endpoints.UpdateIsLocal()
minio-test-0 minio        4: cmd/endpoint.go:529:cmd.CreateEndpoints()
minio-test-0 minio        3: cmd/endpoint-ellipses.go:293:cmd.createServerEndpoints()
minio-test-0 minio        2: cmd/server-main.go:126:cmd.serverHandleCmdArgs()
minio-test-0 minio        1: cmd/server-main.go:277:cmd.serverMain()
```

## Steps to Reproduce (for bugs)
1. `helm upgrade --install minio-test stable/minio --set mode=distributed --version=4.0.3`
2. `kubectl get pods | grep minio-test` <- observe restarts

## Your Environment

* Version used (`minio version`): 4.0.3 (tried also with chart version 4.0.1, also been trying with `minio:edge` image).
* Environment name and version: kubernetes cluster

**Comment by kannappanr** [comment] 2020-01-02 13:22
@pawelbojanowski We will take a look and get back to you. Thanks for reporting the issue

**Comment by harshavardhana** [comment] 2020-01-03 18:59
Just ran this on a GKE cluster works like a charm, are you sure your Kubernetes cluster is not misbehaving? 

```
~ helm upgrade --install minio-test stable/minio --set mode=distributed --version=5.0.1
Release "minio-test" does not exist. Installing it now.
```

```
kubectl logs minio-test-0
Waiting for all other servers to be online to format the disks.
Waiting for all other servers to be online to format the disks.
Attempting encryption of all config, IAM users and policies on MinIO backend
Status:         4 Online, 0 Offline. 
Endpoint:  http://10.12.1.31:9000  http://127.0.0.1:9000

Browser Access:
   http://10.12.1.31:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

```
~ kubectl get pods -l release=minio-test
NAME           READY   STATUS    RESTARTS   AGE
minio-test-0   1/1     Running   0          105s
minio-test-1   1/1     Running   0          105s
minio-test-2   1/1     Running   0          105s
minio-test-3   1/1     Running   0          105s
```

Closing this as working as intended for now.

**Closed as completed by harshavardhana** 2020-01-03 18:59 UTC
Labels: working as intended, community
