### ISSUE TITLE
Panic in CompleteMultipartUpload when uploading large files

### ISSUE THREAD

**Issue by socketbind** [minio/minio#6492] opened 2018-09-19 20:24 UTC
Hi,

Uploading somewhat large (>11GB) files into Minio using multipart upload can cause panics.

The panic log looks like this:
API: PutObjectPart(bucket=input, object=1812614t1/1812614t1.mp4)
Time: 12:40:18 UTC 09/19/2018
RequestID: 1555CD2C0504C3D2
RemoteHost: 192.168.120.22
UserAgent: Minio (linux; amd64) minio-go/v6.0.6
Error: open /data/.minio.sys/multipart/778f71d7cda8be7fc238d707d550faec26e4fa00984b6fd7a0d39a04002590cf/19601a06-548e-47bd-96cf-dde559d23158/00174.8efe62a48c10b9a1e32b16f945f7832f: no such file or directory
       uploadID=19601a06-548e-47bd-96cf-dde559d23158, partPath=/data/.minio.sys/multipart/778f71d7cda8be7fc238d707d550faec26e4fa00984b6fd7a0d39a04002590cf/19601a06-548e-47bd-96cf-dde559d23158/00174.8efe62a48c10b9a1e32b16f945f7832f, filepath=/data/.minio.sys/tmp/a5e2e61d-51d4-4b33-bdcb-d62b945721c5/19601a06-548e-47bd-96cf-dde559d23158.b095007f-1e99-498c-91c2-d64f8251726d
       1: cmd/logger/logger.go:294:logger.LogIf()
       2: cmd/fs-v1-multipart.go:118:cmd.(*FSObjects).backgroundAppend()
2018-09-19 12:40:19.454439 I | http: panic serving 10.42.87.211:36646: runtime error: invalid memory address or nil pointer dereference
goroutine 602471 [running]:
net/http.(*conn).serve.func1(0xc4203f10e0)
	/opt/go/src/net/http/server.go:1726 +0xd0
panic(0x12777e0, 0x202a710)
	/opt/go/src/runtime/panic.go:502 +0x229
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:771 +0x93
panic(0x12777e0, 0x202a710)
	/opt/go/src/runtime/panic.go:502 +0x229
github.com/minio/minio/cmd.(*FSObjects).CompleteMultipartUpload(0xc42019e380, 0x1591380, 0xc4202fa9f0, 0xc4203f4186, 0x5, 0xc4203f418c, 0x17, 0xc4203f41ad, 0x24, 0xc4210bd800, ...)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1-multipart.go:590 +0x1beb
github.com/minio/minio/cmd.(ObjectLayer).CompleteMultipartUpload-fm(0x1591380, 0xc4202fa9f0, 0xc4203f4186, 0x5, 0xc4203f418c, 0x17, 0xc4203f41ad, 0x24, 0xc4210bd800, 0xb3, ...)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:1702 +0x114
github.com/minio/minio/cmd.objectAPIHandlers.CompleteMultipartUploadHandler(0x14bd2e0, 0x14bd2d8, 0x158a380, 0xc420018140, 0xc4200b2500)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:1706 +0x78f
github.com/minio/minio/cmd.(objectAPIHandlers).CompleteMultipartUploadHandler-fm(0x158a380, 0xc420018140, 0xc4200b2500)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/api-router.go:58 +0x57
net/http.HandlerFunc.ServeHTTP(0xc4203e50a0, 0x158a380, 0xc420018140, 0xc4200b2500)
	/opt/go/src/net/http/server.go:1947 +0x44
github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4204e2050, 0x158a380, 0xc420018140, 0xc4200b2500)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107 +0xdc
github.com/minio/minio/cmd.requestIDHeaderHandler.ServeHTTP(0x157fb80, 0xc4204e2050, 0x158a380, 0xc420018140, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:742 +0x9e
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1581ce0, 0xc420526d60, 0x158a380, 0xc420018140, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:757 +0xdc
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc4203c3060, 0x1581d60, 0xc420526d90, 0x158a380, 0xc420018140, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:628 +0x88
github.com/minio/minio/cmd.rateLimit.ServeHTTP(0xc420614960, 0x1581b60, 0xc4203c3080, 0x158a380, 0xc420018140, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:722 +0x123
github.com/minio/minio/cmd.pathValidityHandler.ServeHTTP(0x1581c80, 0xc4203c30a0, 0x158a380, 0xc420018140, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:615 +0x1b8
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1581c60, 0xc420526dc0, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:554 +0xba
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1581c00, 0xc420526e30, 0x50004000000, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:71 +0xde
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1581d00, 0xc4203c30c0, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:96 +0xa7
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1581cc0, 0xc420526e40, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x8a
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1581bc0, 0xc420526e60, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:248 +0x92
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1581ca0, 0xc420526e70, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:306 +0x78
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1581c40, 0xc420526e90, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:275 +0x73
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1581b80, 0xc420526ea0, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:376 +0x1af
github.com/minio/minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc4203c3160, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/opt/go/src/net/http/server.go:1947 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1582ce0, 0xc4203c3160, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:505 +0xd2
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1581d40, 0xc420526f40, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:287 +0x157
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1581b40, 0xc420526f60, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:139 +0xa7
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1581d20, 0xc420526f70, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:774 +0x8d
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:114 +0xe7
net/http.HandlerFunc.ServeHTTP(0xc42051f180, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/opt/go/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc42024c240, 0x158fe00, 0xc4209061c0, 0xc420cfa100)
	/opt/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4203f10e0, 0x15912c0, 0xc4200d27c0)
	/opt/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2795 +0x27b

Judging by the source code, this is the line that fails:
fsRemoveFile(ctx, file.filePath)
I presume that the file variable becomes null somehow because the file handle is no longer available in fs.appendFileMap. As I'm not familiar with the source code I'm not exactly sure how this can happen during runtime.

Uploads are mostly done with the Minio client. As a side effect I'm also seeing a the /data/.minio.sys/tmp directory grow with files until all disk space is exhausted. These files are seemingly never cleaned up. Memory usage is also rather high at 9GB of RAM. There is still plenty of RAM left though.

## Expected Behavior

Multipart upload for large files should succeed without any errors.

## Current Behavior

Panics are frequent and are causing upload to fail.

## Steps to Reproduce (for bugs)

I'm still trying to reproduce this issue in a simpler environment than the Rancher cluster we are currently running in. Simply running the official container image locally using plain Docker engine will not reproduce the issue.

## Your Environment

* Version used (`minio version`): RELEASE.2018-08-25T01-56-38Z
* Environment name and version (e.g. nginx 1.9.1): Running inside a Docker container managed by Rancher 1.6 and the Cattle orchestrator. Storage is backed by NFS
* Server type and version: Debian GNU/Linux
* Operating System and version (`uname -a`): 9

**Comment by harshavardhana** [comment] 2018-09-19 20:30
Thanks for opening the issue, this is a duplicate of #6429

**Closed as completed by harshavardhana** 2018-09-19 20:30 UTC
Labels: duplicate, community
