### ISSUE TITLE
XL: GetObject timesout for large file

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1551] opened 2016-05-09 05:46 UTC
```
krishna@minio2:~$ mc cat myminio/test1/200gfile|md5sum
mc: <ERROR> Unable to read from ‘myminio/test1/200gfile’. net/http: request canceled (Client.Timeout exceeded while reading body)
71c68029eabd2f50ab1dec1f88b3c273  -
krishna@minio2:~$ 
```

**Comment by krishnasrinivas** [comment] 2016-05-09 12:23
Happened on an isolated server too (i.e there were no other tests being run in parallel that could consume resources):

```
azureuser@minio-test:/mnt$ mc cat myminio/test1/200gfile | md5sum
mc: <ERROR> Unable to read from ‘myminio/test1/200gfile’. net/http: request canceled (Client.Timeout exceeded while reading body)
5560688d0d9d6772d1b921c32f4a9df4  -
azureuser@minio-test:/mnt$
```

Disks were 30MBps though.

**Comment by harshavardhana** [comment] 2016-05-09 20:43
> Happened on an isolated server too (i.e there were no other tests being run in parallel that could consume resources):
> 
> azureuser@minio-test:/mnt$ mc cat myminio/test1/200gfile | md5sum
> mc: <ERROR> Unable to read from ‘myminio/test1/200gfile’. net/http: request canceled (Client.Timeout exceeded while reading body)
> 5560688d0d9d6772d1b921c32f4a9df4  -
> azureuser@minio-test:/mnt$
> Disks were 30MBps though.

If there is data being written to the client this wouldn't happen,  this could be a separate problem. Since all the readers and writers are streams in GetObject() there is something else going on which we are not seeing. 

Can you reproduce this with "--debug" and wireshark the traffic to see if we get data at all?  minio server CPU usage?

**Comment by krisis** [comment] 2016-05-13 05:01
This problem is reproducible consistently. While debugging this issue I noticed that we are not closing the readCloser objects streaming the multipart chunks of the object. Fixing this 'leak' results in `mc cp` to progress further than before. But it still fails with the same timeout error message.

**Comment by harshavardhana** [comment] 2016-05-18 01:06
> This problem is reproducible consistently. While debugging this issue I noticed that we are not closing the readCloser objects streaming the multipart chunks of the object. Fixing this 'leak' results in mc cp to progress further than before. But it still fails with the same timeout error message.

Can we add a tentative date here? @krishnasrinivas @krisis

**Comment by harshavardhana** [comment] 2016-05-18 01:28
Closing since this issue was fixed by closing the reader properly during, if reproduced again - please reopen as new bug.

**Comment by krishnasrinivas** [comment] 2016-05-18 04:22
@harshavardhana problem still exists

**Comment by harshavardhana** [comment] 2016-05-18 04:59
> @harshavardhana problem still exists

Re-opening add the profiling outputs here - if they have been captured.

**Comment by krisis** [comment] 2016-05-18 05:06
Following is the blocking profile visualization captured for a (successful) copy of 10GB from minio-server to local disk.

[block.1.pdf](https://github.com/minio/minio/files/269689/block.1.pdf)

I will check if GetObject times out for larger object sizes and attach the corresponding blocking profile capture.

**Comment by harshavardhana** [comment] 2016-05-18 21:51
The problem is not server side from what it looks like golang http client just gives up after 8minutes. 

```
mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 64424509440
Accept-Ranges: bytes
Content-Type: application/octet-stream
Date: Wed, 18 May 2016 21:40:24 GMT
Etag: "f7ee34d7177499906de965b2b2d10ef4-6144"
Last-Modified: Wed, 18 May 2016 21:02:31 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: SE4SFK2HEFOQ30PQ

mc: <DEBUG> Response Time:  73.699616ms

...001/testbucket/60gb: 45.85 GB / 60.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░░┃  76.42 % 100.34 MB2m16s
mc: <ERROR> Failed to copy ‘http://127.0.0.1:9001/testbucket/60gb’. net/http: request canceled (Client.Timeout exceeded while reading body)
 (4) cp-main.go:346 main.doCopySession.func1(..) Tags: [http://127.0.0.1:9001/testbucket/60gb]
 (3) cp-main.go:207 main.doCopy(..) Tags: [newfile]
 (2) common-methods.go:85 main.putTargetStreamFromAlias(..) Tags: [, newfile]
 (1) client-fs.go:165 main.(*fsClient).Put(..) Tags: [newfile.part.minio]
 (0) client-fs.go:963 main.(*fsClient).toClientError(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:minio3 | OS:linux | Arch:amd64 | Lang:go1.6 | Mem:13MB/21MB | Heap:13MB/16MB
...001/testbucket/60gb: 47.08 GB / 60.00 GB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█░░░░░░░░░░░░░┃  78.47 % 100.29 MB2m4s mc: <ERROR> Session safely terminated. To resume session ‘mc session resume SicHAEzg’
```

**Comment by harshavardhana** [comment] 2016-05-18 21:51
Trying with curl to validate the theory.

**Comment by harshavardhana** [comment] 2016-05-18 22:03
Theory validates the issue is in using http.ClientTimeout and we should fix this for minio-go as well as 'mc'. 

```
minio@minio3:~$ wget "http://127.0.0.1:9001/testbucket/60gb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YRDRWWQLEWS9OBJ31GZ2%2F20160518%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160518T215158Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=adcafa01ab9a2677d4f49b75a393a335080e6d650c422f644201307d7b387e7a"
The name is too long, 273 chars total.
Trying to shorten...
New name is 60gb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YRDRWWQLEWS9OBJ31GZ2%2F20160518%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160518T215158Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=adcafa01ab9a2677d4f49b75a39.
--2016-05-18 14:52:03--  http://127.0.0.1:9001/testbucket/60gb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YRDRWWQLEWS9OBJ31GZ2%2F20160518%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160518T215158Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=adcafa01ab9a2677d4f49b75a393a335080e6d650c422f644201307d7b387e7a
Connecting to 127.0.0.1:9001... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64424509440 (60G) [application/octet-stream]
Saving to: ‘60gb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YRDRWWQLEWS9OBJ31GZ2%2F20160518%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160518T215158Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=adcafa01ab9a2677d4f49b75a39’

60gb?X-Amz-Algorithm=AWS4-HMAC-SH 100%[===========================================================>]  60.00G   109MB/s    in 10m 14s

2016-05-18 15:02:18 (100 MB/s) - ‘60gb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=YRDRWWQLEWS9OBJ31GZ2%2F20160518%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20160518T215158Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=adcafa01ab9a2677d4f49b75a39’ saved [64424509440/64424509440]
```

**Closed as completed** 2016-05-18 22:03 UTC
