### ISSUE TITLE
S3 Select WHERE clause on an array of objects doesn't work properly

### ISSUE THREAD

**Issue by andreimerfu** [minio/minio#9064] opened 2020-02-28 07:14 UTC
When I try to select just an element from an array, Select API doesn't return anything.

## Expected Behavior
```json
   {
      "element_type": "__elem__merfu",
      "element_id": "d868aefe-ef9a-4be2-b9b2-c9fd89cc43eb",
      "attributes": {
        "__attr__image_dpi": 300,
        "__attr__image_size": [
          2550,
          3299
        ],
        "__attr__image_index": 2,
        "__attr__image_format": "JPEG",
        "__attr__file_extension": "jpg",
        "__attr__data": null
      }
    }
```

## Current Behavior
```
Stats details bytesScanned:
932
Stats details bytesProcessed:
932
```

## Steps to Reproduce (for bugs)

1. Upload a JSON file into a MinIO bucket. Example: 
```json{
  "name": "small_pdf1.pdf",
  "lume_id": "9507193e-572d-4f95-bcf1-e9226d96be65",
  "elements": [
    {
      "element_type": "__elem__image",
      "element_id": "859d09c4-7cf1-4a37-9674-3a7de8b56abc",
      "attributes": {
        "__attr__image_dpi": 300,
        "__attr__image_size": [
          2550,
          3299
        ],
        "__attr__image_index": 1,
        "__attr__image_format": "JPEG",
        "__attr__file_extension": "jpg",
        "__attr__data": null
      }
    },
    {
      "element_type": "__elem__merfu",
      "element_id": "d868aefe-ef9a-4be2-b9b2-c9fd89cc43eb",
      "attributes": {
        "__attr__image_dpi": 300,
        "__attr__image_size": [
          2550,
          3299
        ],
        "__attr__image_index": 2,
        "__attr__image_format": "JPEG",
        "__attr__file_extension": "jpg",
        "__attr__data": null
      }
    }
  ],
  "data": "asdascasdc1234e123erdasdas"
  }
```
2. Call Select API using this python script:
```python3
#!/usr/bin/env/env python3
import boto3

s3 = boto3.client('s3',
                  endpoint_url='http://localhost:9000',
                  aws_access_key_id='ACCESS_KEY_ID',
                  aws_secret_access_key='secret',
                  region_name='us-east-1')

r = s3.select_object_content(
    Bucket='ignite',
    Key='amadeus14',
    ExpressionType='SQL',
    Expression="select * from s3object[*].elements[*] s where s.element_type = '__elem__merfu'",
    InputSerialization={
        'JSON': {
            "Type": "DOCUMENT",
        }
    },
    OutputSerialization={'JSON': {} }
)
for event in r['Payload']:
    if 'Records' in event:
        records = event['Records']['Payload'].decode('utf-8')
        print(records)
    if 'Stats' in event:
        statsDetails = event['Stats']['Details']
        print("Stats details bytesScanned: ")
        print(statsDetails['BytesScanned'])
        print("Stats details bytesProcessed: ")
        print(statsDetails['BytesProcessed'])
```

## Context
I can't select only few objects from a large JSON file using the file structure above.

## Your Environment

* Version used (`minio version`):
`DEVELOPMENT.2020-02-24T14-00-18Z`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Linux 7501c794cc00 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 Linux
(Docker container)
* Link to your project:

**Comment by nitisht** [comment] 2020-02-28 07:15
Thanks for reporting @andreimerfu we'll take a look

**Comment by klauspost** [comment] 2020-03-02 14:40
Did you have a chance to run this against S3?

`select * from s3object[*].elements[*] s` selects an array. The select tests AFAICT run against this array, so there it will either return the entire array or nothing.

For this to work would require significant changes to the engine as far as I can tell.

**Comment by klauspost** [comment] 2020-03-02 14:44
<details><summary>Reproducer for `s3select.TestJSONQueries`:</summary>

```
		{
			name:  "document",
			query: "",
			requestXML: []byte(`
<?xml version="1.0" encoding="UTF-8"?>
<SelectObjectContentRequest>
    <Expression>select * from s3object[*].elements[*] s where s.element_type = '__elem__merfu'</Expression>
    <ExpressionType>SQL</ExpressionType>
    <InputSerialization>
        <CompressionType>NONE</CompressionType>
        <JSON>
            <Type>DOCUMENT</Type>
        </JSON>
    </InputSerialization>
    <OutputSerialization>
        <CSV>
        </CSV>
    </OutputSerialization>
    <RequestProgress>
        <Enabled>FALSE</Enabled>
    </RequestProgress>
</SelectObjectContentRequest>
			`),
			withJSON: `{
  "name": "small_pdf1.pdf",
  "lume_id": "9507193e-572d-4f95-bcf1-e9226d96be65",
  "elements": [
    {
      "element_type": "__elem__image",
      "element_id": "859d09c4-7cf1-4a37-9674-3a7de8b56abc",
      "attributes": {
        "__attr__image_dpi": 300,
        "__attr__image_size": [
          2550,
          3299
        ],
        "__attr__image_index": 1,
        "__attr__image_format": "JPEG",
        "__attr__file_extension": "jpg",
        "__attr__data": null
      }
    },
    {
      "element_type": "__elem__merfu",
      "element_id": "d868aefe-ef9a-4be2-b9b2-c9fd89cc43eb",
      "attributes": {
        "__attr__image_dpi": 300,
        "__attr__image_size": [
          2550,
          3299
        ],
        "__attr__image_index": 2,
        "__attr__image_format": "JPEG",
        "__attr__file_extension": "jpg",
        "__attr__data": null
      }
    }
  ],
  "data": "asdascasdc1234e123erdasdas"
}`,
			wantResult: `"[{""element_type"":""__elem__merfu"",""element_id"":""d868aefe-ef9a-4be2-b9b2-c9fd89cc43eb"",""attributes"":{""__attr__image_dpi"":300,""__attr__image_size"":[2550,3299],""__attr__image_index"":2,""__attr__image_format"":""JPEG"",""__attr__file_extension"":""jpg"",""__attr__data"":null}}]"`,
		},
```

</p>
</details>

**Comment by klauspost** [comment] 2020-03-02 15:07
@andreimerfu I would recommend doing the select part client-side or use separate objects. This approach doesn't scale well anyway, since the entire object would need to be loaded.

You can still do `SELECT * FROM s3object s WHERE '__elem__merfu' IN s.elements[*].element_type` to only return results if there is an element with that type.

**Comment by andreimerfu** [comment] 2020-03-03 08:09
@klauspost I tested this query `select * from s3object[*].elements[*] s where s.element_type = '__elem__merfu'` in S3 and it works. So, MinIO doesn't have support for this type of query yet, right?
 Also, I think that I cannot select the entire object because this one it's very big ( ~10-50gb )

**Comment by klauspost** [comment] 2020-03-03 13:56
Thanks for testing! As you can see above we are looking into the issue.

But either way 10-50GB will be an issue for most servers since documents aren't streaming. 

I don't know if there is a reasonable way to convert it to NDJSON for you - that is by far the most reasonable way to deal with this amount of data.

**Comment by klauspost** [comment] 2020-03-11 11:41
Fixed in https://github.com/minio/minio/pull/9076

**Closed as completed by klauspost** 2020-03-11 11:41 UTC
Labels: community, fixed, triage
