### ISSUE TITLE
minio cluster with four nodes replication configuration

### ISSUE THREAD

**Issue by Auggie321** [minio/minio#11004] opened 2020-12-01 01:14 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

# minio environment:
use binary minio and mc , deploy minio cluster with four nodes, each nodes have two disk partitions /data{1,2};

# issues:
mc mb minio1/test1 --region=us-east-1

then /data1,/data2 will have test1 bucket, each of cluster nodes have bucket too.
i mean just create one bucket, got 8 replications. (local has two, per node has two, total 2*4=8)

how to set minio cluster's  bucket replication in 3, or 4 manually;
from https://docs.minio.io/docs/minio-bucket-replication-guide.html , there not clear about replcation details.

**Comment by Auggie321** [comment] 2020-12-01 01:50
add
mc version RELEASE.2020-11-25T23-04-07Z
minio version RELEASE.2020-11-25T22-36-25Z

**Comment by kannappanr** [comment] 2020-12-08 00:07
@Auggie321 This is a single MinIO cluster.

**Comment by Auggie321** [comment] 2020-12-08 01:20
@kannappanr  sorry, i am not clear about your reply. is there more documention explain it, thanks.

**Comment by harshavardhana** [comment] 2020-12-25 07:07
MinIO doesn't support replication within a cluster instead it supports multi-site bucket replication and with in a cluster erasure coding. 

Closing this as MinIO is working as intended.

**Closed as completed by harshavardhana** 2020-12-25 07:07 UTC
Labels: working as intended, community
