### ISSUE TITLE
Concurrent multipart-upload of objects using minio-py SDK fails with NoSuchUpload

### ISSUE THREAD

**Issue by krisis** [minio/minio#3110] opened 2016-10-27 12:21 UTC
Uploading object of size 65MB concurrently using minio-py SDK and `xargs` fails with NoSuchUpload error intermittently.
## Expected Behavior

Upload of objects should succeed without errors.
## Current Behavior

Multipart upload fails with the following error intermittently.
`upload failure - got error: ResponseError: code: NoSuchUpload`
## Steps to Reproduce (for bugs)

1. `docker-compose up` from minio server source repo.
2. `mc mb <alias>/kp-test-minio-py`
3. `seq 5  | xargs -n 1 -P 32 -I{} -t python small-objects-test.py --count 5`
4. Use [small-objects-test.py](https://gist.github.com/krisis/031ef243a1033156a7671d2b76872f01)
## Context

Was trying to upload objects of size 65MB in parallel to test if multipart upload is safe from races.
## Your Environment

- Version used: 

```
Version: 2016-10-27T03:13:33Z
Release-Tag: DEVELOPMENT.2016-10-27T03-13-33Z
Commit-ID: 30dc11a931010cdca52dddddb7b06fafbe0db8b2
```
- Environment name and version (e.g. nginx 1.9.1): 
- Server type and version: `docker-compose` based

**Comment by harshavardhana** [comment] 2016-10-27 16:01
Looks like this is what @donatello fixed recently?

**Comment by donatello** [comment] 2016-10-27 16:46
If this happens during concurrent uploads it is not a bug. When complete-multipart-uploads race on the same uploadid one completes and the other gets this error code. It is reasonable.

**Comment by krisis** [comment] 2016-10-28 01:40
@donatello yeah, that makes sense. I verified that the contents of the objects uploaded are intact. We can close this issue.

**Comment by harshavardhana** [comment] 2016-10-28 01:41
> @donatello yeah, that makes sense. I verified that the contents of the objects uploaded are intact. We can close this issue.

Closing.

**Closed as completed by harshavardhana** 2016-10-28 01:41 UTC
