### ISSUE TITLE
[distributed] able to run minio server with duplicate disks

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#2516] opened 2016-08-22 11:31 UTC
Below is the example command.

``` bash
minio server --address=:60000 m2.minio.io:/home/bala/d1 m2.minio.io:/home/bala/d1 m3.minio.io:/home/bala/d1 m3.minio.io:/home/bala/d1
```

**Comment by harshavardhana** [comment] 2016-08-22 11:35
> minio server --address=:60000 m2.minio.io:/home/bala/d1 m2.minio.io:/home/bala/d1 m3.minio.io:/home/bala/d1 m3.minio.io:/home/bala/d1

Currently server doesn't error out since the initialization happens lazily, if you do 'mc ls' you would see an error message and server is not accessible. 

We need to fix this there is a bug on this to error out in various conditions before we even begin the server startup.

**Comment by harshavardhana** [comment] 2016-08-22 19:18
Closing this as duplicate of - https://github.com/minio/minio/issues/2502

**Closed as completed by harshavardhana** 2016-08-22 19:18 UTC
