### ISSUE TITLE
minio memory increased everyday and _MINIO_PROFILER not working

### ISSUE THREAD

**Issue by lcnsir** [minio/minio#8322] opened 2019-09-27 03:28 UTC
minio image version: RELEASE.2019-04-03T17-59-57Z

I run minio in a k8s platform.

And there is a service who get frames/data from kafka then compress it finially store the data into minio frenquently

The service implemented by minio-go:6.0.25

with the exmple method:

```
	minioClient, err := minio.New(config.endpoint, config.accessKey, config.secertKey, config.useSSL)
	if err != nil {
		log.Fatalln(err)
	}
	minioClient.SetCustomTransport(&http.Transport{
		MaxIdleConns:    10,
		IdleConnTimeout: 30 * time.Second,
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	})
	client.conn = minioClient
	return &client, nil
```
to get the client

then push data in the daemon

```
	_, err = client.conn.FPutObject(BucketName, objectName, tmpGZfile, minio.PutObjectOptions{ContentType: contentType})
	if err != nil {
		log.Fatalln(err)
	}
```

Then I found minio memory increase every day and then 

I add 

```
        - name: _MINIO_PROFILER
          value: mem
```
want to get the memory profile

but when I login to the container

the profile file  is generated but the file is empty

```
bash-4.2$ cat /tmp/profile656423381/mem.pprof
bash-4.2$
```

**Comment by harshavardhana** [comment] 2019-09-27 03:50
Upgrade to latest @lcnsir we have improved memory usage quite a bit..

**Comment by harshavardhana** [comment] 2019-09-27 03:50
Also profiler is moved to command line `mc admin profile --type mem`

**Comment by lcnsir** [comment] 2019-09-27 09:47
@harshavardhana 
 
After I upgrade to the version `RELEASE.2019-09-26T19-42-35Z`

The memory usage still consume highly and quickly

Any suggestion? Is this will be a memory leak ? 

And one changes is that I started minio by
```
      securityContext:
        fsGroup: 5001
        runAsUser: 5001
```

Is that related with the memory increase issue ?

**Comment by harshavardhana** [comment] 2019-09-27 15:31
Note: MinIO allocates 10MiB per read and writes on a bufPool . This memory is reused so for example if you have 1000 concurrent connections you will see 10G memory usage.

Are you saying you see more than this ? Also how are you seeing memory usage?

**Comment by nitisht** [comment] 2019-10-02 13:48
Closing this as working as intended, please reopen if you have further inputs

**Closed as completed by nitisht** 2019-10-02 13:48 UTC
Labels: working as intended, community, triage

**Comment by lcnsir** [comment] 2019-10-15 01:42
@harshavardhana sorry for the later response, I have replace with latest version of minio in my cluster

but the memory usage still increased and I seeing the memory usage by `kubectl command`

```
kubectl top po xxx-minio-0 -nkube-system
NAME                            CPU(cores)   MEMORY(bytes)
xxxr-minio-0                      428m         1060Mi
```

**Comment by harshavardhana** [comment] 2019-10-15 01:43
@lcnsir this is perfectly fine 1GiB is nothing for storage nodes. are you expecting MinIO to use less memory than this?

**Comment by lcnsir** [comment] 2019-10-15 01:47
@harshavardhana  
yes,  but when I restart the pod the memory usage is just 40+ MB...and the memory usage keeps grows day by day,


If I increase the data inputed by a minio go client the memory usage will be increased more. 


what's your mean about per read and writes on a bufPool

if I have a code of go minio client

```
	minioClient, err := minio.New(config.endpoint, config.accessKey, config.secertKey, config.useSSL)
	if err != nil {
		log.Fatalln(err)
	}
	minioClient.SetCustomTransport(&http.Transport{
		MaxIdleConns:    10,
		IdleConnTimeout: 30 * time.Second,
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	})
	client.conn = minioClient
	return &client, nil
```

and this client always reused in a while loop server, and keeps to wirte data into minio,  will the memory usage in minio should be increased always ?

**Comment by harshavardhana** [comment] 2019-10-15 01:52
It doesn't increase in this fashion @lcnsir - MinIO erasure coding uses 10MiB buffer per stream so if you are uploaded 1000 concurrent streams it will use 1000 * 10 = 10GiB memory. Now, this memory is not given back to GC because MinIO reuses same 10GiB for the next 1000 concurrent operations. So if your concurrent operations increase the memory is always allocated and reused again and again.  

you will always know that there is a top-level limit based on the client's concurrent requirement. If you can show that just uploading a single stream leaks memory then it makes sense, but without that I don't think what you are seeing is unusual.

**Comment by lcnsir** [comment] 2019-10-15 05:49
@harshavardhana could you show me what is 1 or more concurrent stream, for the minio-client.
 code

the client upload the file by
```
client.conn.FPutObject(Bucket, objectName, tmpGZfile, minio.PutObjectOptions{ContentType: contentType})
```
which the client genreated by above code in standard way.


in a while loop

it got data from kafka, then upload data to minio in the while loop,  How could I accept the calculate the concurrent streams number?

Thanks

**Comment by NeoyeElf** [comment] 2020-03-24 02:12
> It doesn't increase in this fashion @lcnsir - MinIO erasure coding uses 10MiB buffer per stream so if you are uploaded 1000 concurrent streams it will use 1000 * 10 = 10GiB memory. Now, this memory is not given back to GC because MinIO reuses same 10GiB for the next 1000 concurrent operations. So if your concurrent operations increase the memory is always allocated and reused again and again.
> 
> you will always know that there is a top-level limit based on the client's concurrent requirement. If you can show that just uploading a single stream leaks memory then it makes sense, but without that I don't think what you are seeing is unusual.

will the 10G memory be released?

**Comment by harshavardhana** [comment] 2020-03-24 02:13
> will the 10G memory be released?

It will never be released, it will be reused.

**Comment by NeoyeElf** [comment] 2020-03-24 02:17
> > will the 10G memory be released?
> 
> It will never be released, it will be reused.

If I have to limit the memory minio used, any suggestions? maybe use a queue to limit the concurrency?

**Comment by harshavardhana** [comment] 2020-03-24 02:35
If you want to limit then we are bringing the change in PR #9196
