### ISSUE TITLE
Uploading file,Resource requested is unreadable

### ISSUE THREAD

**Issue by wuyuan0717** [minio/minio#13213] opened 2021-09-15 08:57 UTC
When I try to upload multiple files,, I always get the following error response:

`io.minio.errors.MinioException: Resource requested is unreadable, please reduce your request rate`

## Your Environment

* Version used (`minio --version`): 2021-05-18T00:53:28Z
* Operating System and version (`uname -a`): Linux u-oss-xt-02 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
* bandwidth: 
<img width="335" alt="1631696269(1)" src="https://user-images.githubusercontent.com/14838846/133403565-d5e3ab7d-5891-42ef-8cbd-b52f8e0a7ec8.png">

**Comment by klauspost** [comment] 2021-09-15 10:55
@wuyuan0717 Please upgrade to latest and retry.

If there are still errors please also provide your setup, like number of servers, filesystems, etc. Also post errors from the server logs.

**Comment by wuyuan0717** [comment] 2021-09-17 00:50
This problem occurs in the formal environment. In order to maintain stability, the version cannot be upgraded. and there is no error information related to it in the log file

**Comment by wuyuan0717** [comment] 2021-09-17 00:57
Another problem is that the following error message appears：

`API: SYSTEM()
Time: 21:03:52 CST 09/14/2021
DeploymentID: 6f8cbacd-c812-4e95-9244-d88d33ed3e19
Error: EOF (*errors.errorString)
       1: cmd/iam-etcd-store.go:573:cmd.(*IAMEtcdStore).watch()`
My cluster is 4 nodes, 2 disks per node, and Federationmode is used

**Comment by klauspost** [comment] 2021-09-17 09:44
@wuyuan0717 We do not provide community support for older installs. Please upgrade or see our [subscription options](https://min.io/pricing).

I am not sure if the error is related to your problem. 

I would expect the cause of this error to almost always be logged. It could be your file system, but since you didn't provide that information it is just a guess.

Since there is no information to go on here I will close it. If you see the problem with the latest version feel free to open another issue.

**Closed as completed by klauspost** 2021-09-17 09:44 UTC
Labels: community, triage, waiting for info
