### ISSUE TITLE
 after custom the policy and apply to a new user, but I can't see any bucket when I login the website

### ISSUE THREAD

**Issue by Logan80s** [minio/minio#9552] opened 2020-05-08 08:11 UTC
after  custom the policy and apply to a new user, and I can't see any bucket when I login the website

## Expected Behavior

when i login as newuser,then i should see bucket test1,and can only download files in the bucket
## Current Behavior

I can't see any bucket when I login the website
## Steps to Reproduce (for bugs)

steps like:
1. [root@host4 opt]# ./mc admin policy add local  getbucketonly getbucketonly.json 
Added policy `getbucketonly` successfully.
2. [root@host4 opt]# ./mc admin user add local newuser newuser123       
Added user `newuser` successfully.
3. [root@host4 opt]# ./mc admin policy set local getbucketonly user=newuser       
 Policy getbucketonly is set on user `newuser`

the  getbucketonly.json  detail:
{
 "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::test1/*"
      ],
      "Sid": ""
    }
  ]
}

## Your Environment

* Version used (`minio version`):
minio version RELEASE.2020-04-23T00-58-49Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Linux host4 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by anthu** [comment] 2020-05-08 08:32
This policy is not enough.
Refer to the S3 Policy documentation and try the following:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "s3:ListAllMyBuckets"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::*"
      ],
      "Sid": ""
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:GetBucketLocation",
        "s3:ListBucket"
      ],
      "Effect": "Allow",
      "Resource": [
        "arn:aws:s3:::test1/*",
        "arn:aws:s3:::test1"
      ],
      "Sid": ""
    }
  ]
}
```

**Comment by harshavardhana** [comment] 2020-05-08 15:46
> This policy is not enough.
> Refer to the S3 Policy documentation and try the following:
> 
> ```
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Action": [
>         "s3:ListAllMyBuckets"
>       ],
>       "Effect": "Allow",
>       "Resource": [
>         "arn:aws:s3:::*"
>       ],
>       "Sid": ""
>     },
>     {
>       "Action": [
>         "s3:GetObject",
>         "s3:GetBucketLocation",
>         "s3:ListBucket"
>       ],
>       "Effect": "Allow",
>       "Resource": [
>         "arn:aws:s3:::test1/*",
>         "arn:aws:s3:::test1"
>       ],
>       "Sid": ""
>     }
>   ]
> }
> ```

As per @anthu thanks for posting, you need List permissions to see the buckets not just Get

Closing this issue as working as intended.

**Closed as completed by harshavardhana** 2020-05-08 15:46 UTC
Labels: working as intended, community

**Comment by Logan80s** [comment] 2020-05-09 07:45
> This policy is not enough.
> Refer to the S3 Policy documentation and try the following:
> 
> ```
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Action": [
>         "s3:ListAllMyBuckets"
>       ],
>       "Effect": "Allow",
>       "Resource": [
>         "arn:aws:s3:::*"
>       ],
>       "Sid": ""
>     },
>     {
>       "Action": [
>         "s3:GetObject",
>         "s3:GetBucketLocation",
>         "s3:ListBucket"
>       ],
>       "Effect": "Allow",
>       "Resource": [
>         "arn:aws:s3:::test1/*",
>         "arn:aws:s3:::test1"
>       ],
>       "Sid": ""
>     }
>   ]
> }
> ```

thanks , It works

**Comment by Logan80s** [comment] 2020-05-09 07:50
@anthu @harshavardhana  thanks man, it works
by the way , I have some problems in using the minio, some features I can't found  in the minio document , for example, how can I resume breakpoint while uploading or downloanding large file  by using the Java SDK.and would you please show me some examples,or show me the right link ,thanks again
