### ISSUE TITLE
XL: PutObject - investigate upload speed

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1927] opened 2016-06-18 06:52 UTC
upload speed is 50MBps, investigate - disable bitrot, compare against FS.

**Comment by harshavardhana** [comment] 2016-06-24 22:46
Looks like this a duplicate of - https://github.com/minio/minio/issues/1928 . Closing and assigning that to @krisis

**Closed as completed by harshavardhana** 2016-06-24 22:46 UTC
