### ISSUE TITLE
Minio returns AccessDenied on public resource

### ISSUE THREAD

**Issue by dominicporteous** [minio/minio#4957] opened 2017-09-23 12:03 UTC
With 2 minio instances (via docker, shared volumes between the two) sitting behind a loadbalancer, when policy is updated on resource to be public (with the requests being handled round-robin) it appears the second instance, that being the one not handling the policy update http request, does not pick up the config changes from the other container, even though the buckets policy.json is the same for each container (stored at /data/.minio.sys/buckets/test/policy.json)

_N.B. Docker container is running with MINIO_BROWSER=off_

## Expected Behavior

When resource is set as public via `mc policy public`, the resource should be accessible in the browser at the expected URI.

## Current Behavior

When resource is set as public via `mc policy public`, on one container instance, the instance is accessible via http whereas the other container (which did not handle the http request to update policy) is showing 401 Access Denied. 

## Possible Solution
Perhaps a timed hot-reload of the config?

## Steps to Reproduce (for bugs)

(Requires a dockerised minio setup to reproduce)

1. Upload item to bucket via mc command line ( e.g. cp clouds_transparent_50.png test/test )
2. Check policy is set to none by default ( mc policy test/test/clouds_transparent_50.png )
3. Check via browser resource is in-accessible. Should return access denied xml. ( e.g. http://minioinstance/test/clouds_transparent_50.png)
4. Update policy to public ( mc policy public test/test/clouds_transparent_50.png )
3. Check via browser resource is now accessible. Should return resource, but every second request will return access denied xml instead of resource.

Note: Restarting the container which didn't handle the request, will fix the issue, but I dont think that is a viable solution going forward.

## Context

With 2 minio instances (via docker, shared volumes between the two) sitting behind a loadbalancer, when policy is updated on resource to be public (with the requests being handled round-robin) it appears the second instance, that being the one not handling the policy update http request, does not pick up the config changes from the other container, even though the buckets policy.json is the same for each container (stored at /data/.minio.sys/buckets/test/policy.json).

_N.B. Docker container is running with MINIO_BROWSER=off_

## Your Environment

* Version used
Version: 2017-09-23T04:15:58Z
Release-Tag: DEVELOPMENT.2017-09-23T04-15-58Z
Commit-ID: aceaa1ec48cd6bbf557aa0e8bfe52093f51b40d0

* Environment name and version (e.g. nginx 1.9.1):
Dockerised minio, using official docker image, running behind ngnix loadbalancer

* Server type and version:
As above, using latest tag.

* Operating System and version (`uname -a`):
Container is alpine linux as per official image.

Host is Ubuntu 16.04:
`Linux fa7dab4ec975 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 Linux`

* Link to your project:
n/a

**Comment by harshavardhana** [comment] 2017-09-23 18:03
Duplicate of https://github.com/minio/minio/issues/4458

**Comment by harshavardhana** [comment] 2017-09-26 07:34
Closing this as duplicate of #4458

**Closed as completed by harshavardhana** 2017-09-26 07:34 UTC
Labels: duplicate, priority: medium, triage
