### ISSUE TITLE
Panic in S3 Select

### ISSUE THREAD

**Issue by donatello** [minio/minio#8481] opened 2019-11-04 21:34 UTC
## Expected Behavior

MinIO should not crash

## Current Behavior

MinIO crashes when running the same query again with mc when we interrupt it the first time.

## Steps to Reproduce (for bugs)

1. `mc sql -e 'select * from s3object s ' --json-input "Type=LINES"  minio/bucket/some.json`
2. Hit Ctrl+C on mc before mc finishes its output.
3. Run same command again.
4. minIO server crashes with:

```
panic: read /home/aditya/data/bucket/some.json: file already closed

goroutine 211 [running]:
github.com/bcicen/jstream.newScanner.func1(0xc000054a00, 0x7f4d03be2ec0, 0xc000485ca0)
        /q/.q/sources/gopath/pkg/mod/github.com/bcicen/jstream@v0.0.0-20190220045926-16c1f8af81c2/scanner.go:48 +0x180
created by github.com/bcicen/jstream.newScanner
        /q/.q/sources/gopath/pkg/mod/github.com/bcicen/jstream@v0.0.0-20190220045926-16c1f8af81c2/scanner.go:32 +0xe5
```

## Context

Testing s3 select.

## Regression

Most likely yes, but not sure.

## Your Environment

```
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
```

**Comment by klauspost** [comment] 2019-11-05 11:07
It seems like a generic race when closing the streams. On one of my runs I got this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x110f4cc]

goroutine 19939 [running]:
github.com/klauspost/readahead.(*buffer).buffer(...)
        e:/gopath/pkg/mod/github.com/klauspost/readahead@v1.3.0/reader.go:385
github.com/klauspost/readahead.(*reader).Read(0xc000397180, 0xc0006f3020, 0xfff, 0xfff, 0xc0003f5800, 0xc000e4bf10, 0x4073ff)
        e:/gopath/pkg/mod/github.com/klauspost/readahead@v1.3.0/reader.go:256 +0xac
github.com/minio/minio/cmd.(*GetObjectReader).Read(0xc0006f0000, 0xc0006f3020, 0xfff, 0xfff, 0xc0005d2088, 0xc0005d2138, 0xc0000447d8)
        e:/gopath/src/github.com/minio/minio/cmd/object-api-utils.go:709 +0x63
github.com/minio/minio/pkg/s3select.(*countUpReader).Read(0xc000175f00, 0xc0006f3020, 0xfff, 0xfff, 0xc000083020, 0xc000e4bf88, 0x1120101)
        e:/gopath/src/github.com/minio/minio/pkg/s3select/progress.go:34 +0x58
github.com/minio/minio/pkg/s3select.(*countUpReader).Read(...)
        e:/gopath/src/github.com/minio/minio/pkg/s3select/progress.go:34
github.com/minio/minio/pkg/s3select.(*progressReader).Read(0xc000175f60, 0xc0006f3020, 0xfff, 0xfff, 0x100, 0x0, 0x0)
        e:/gopath/src/github.com/minio/minio/pkg/s3select/progress.go:56 +0x65
github.com/bcicen/jstream.newScanner.func1(0xc0006f2000, 0x9be2658, 0xc000175f60)
        e:/gopath/pkg/mod/github.com/bcicen/jstream@v0.0.0-20190220045926-16c1f8af81c2/scanner.go:37 +0x7f
created by github.com/bcicen/jstream.newScanner
        e:/gopath/pkg/mod/github.com/bcicen/jstream@v0.0.0-20190220045926-16c1f8af81c2/scanner.go:32 +0xec
```

Seems related and looks like a use after close. Edit: Confirmed, this is a read after Close.

Seems like jstream is particularly nasty: https://github.com/bcicen/jstream/blob/master/scanner.go#L48

**Closed as completed** 2019-11-05 22:20 UTC
Labels: community, fixed, triage
