### ISSUE TITLE
Documentation for bucket notification targets configuration

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3085] opened 2016-10-25 16:11 UTC
Currently we have documentation https://docs.minio.io/docs/minio-client-complete-guide#events which only tells how to add/remove/list events.

We don't have documentation on how to configure targets and it's various parameters needed in the config.json i.e:

```
    "notify": {
        "amqp": {
            "1": {
                "enable": false,
                "url": "",
                "exchange": "",
                "routingKey": "",
                "exchangeType": "",
                "mandatory": false,
                "immediate": false,
                "durable": false,
                "internal": false,
                "noWait": false,
                "autoDeleted": false
            }
        },
        "nats": {
            "1": {
                "enable": false,
                "address": "",
                "subject": "",
                "username": "",
                "password": "",
                "token": "",
                "secure": false,
                "pingInterval": 0
            }
        },
        "elasticsearch": {
            "1": {
                "enable": false,
                "url": "",
                "index": ""
            }
        },
        "redis": {
            "1": {
                "enable": false,
                "address": "",
                "password": "",
                "key": ""
            }
        },
        "postgresql": {
            "1": {
                "enable": false,
                "connectionString": "",
                "table": "",
                "host": "",
                "port": "",
                "user": "",
                "password": "",
                "database": ""
            }
        }
    }

```

**Comment by harshavardhana** [comment] 2016-10-25 16:13
Closed duplicate of #2286

**Closed as completed by harshavardhana** 2016-10-25 16:13 UTC
