### ISSUE TITLE
Setting policy to `download` on any prefix in bucket enables anonymous listing on the whole bucket

### ISSUE THREAD

**Issue by stiletto** [minio/minio#2379] opened 2016-08-07 20:12 UTC
For example `listtest` bucket on play.minio.io has policy set to `none`
when `listtest/download-allowed/` is set to `download`, we can use `curl -i https://play.minio.io:9000/listtest` to see all files in the bucket, including ones from `listtest/download-NOT-allowed/`

**Comment by harshavardhana** [comment] 2016-08-07 20:58
> For example listtest bucket on play.minio.io has policy set to none
> when listtest/download-allowed/ is set to download, we can use curl -i https://play.minio.io:9000/listtest to see all files in the bucket, including ones from listtest/download-NOT-allowed/

Can you paste your 'mc version' - are you using the latest?

**Comment by harshavardhana** [comment] 2016-08-13 09:01
ping @hackintoshrao

**Comment by hackintoshrao** [comment] 2016-08-13 09:55
@harshavardhana : Not able to reproduce with the latest master of both `mc` and `minio`.

**Comment by harshavardhana** [comment] 2016-08-13 19:26
> @harshavardhana : Not able to reproduce with the latest master of both mc and minio.

can you try the latest releases?

**Comment by stiletto** [comment] 2016-08-14 13:27
I was unable to reproduce this with mc from master, only with latest binary release from minio.io
This was a minio-go 2.0.1 bug and it has already been fixed in https://github.com/minio/minio-go/pull/441

**Comment by hackintoshrao** [comment] 2016-08-15 01:39
@harshavardhana : Not able to reproduce with latest releases on the website, but it has other policy related, the permissions are not listed and set properly. It'll be great to replace them with new releases.

**Comment by harshavardhana** [comment] 2016-08-17 01:53
Closing this as fixed..

**Closed as completed by harshavardhana** 2016-08-17 01:53 UTC
