### ISSUE TITLE
Health endpoints non responsive while minio is writing to disk on slow backend

### ISSUE THREAD

**Issue by jperville** [minio/minio#7222] opened 2019-02-11 17:13 UTC
## Expected Behavior

Curling health endpoints (eg. `/minio/health/live`) should not block when minio is writing data to a slow disk backend.

## Current Behavior

Curling health endpoints (eg. `/minio/health/live`) block when minio is writing data to a slow disk backend.

## Possible Solution

After receiving a chunk of data, minio probably blocks until the received data is persisted to disk.
A workaround is to configure the clients to upload in small chunks (eg. 5Mb) which are flushed more often rather than in a very large chunk (> 1Gb) which take a long time to persist on a loaded backend filesystem.

## Steps to Reproduce (for bugs)

1. run minio instance persisting to a slow storage backend
   `docker run --rm -ti --name minio -e MINIO_ACCESS_KEY=aaaaaaaaaaaaaaaaaaaa -e MINIO_SECRET_KEY=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -p 9000:9000 -v /mnt/slow:/data minio/minio server /data`
2. upload large file in a single chunk
  `s3cmd put --multipart-chunk-size-mb=500 /oldsystem/home/julien/iso/CentOS-7-x86_64-DVD-1511.iso s3://test/`
3. query the /minio/health/live route using curl shortly after a chunk is accepted (while minio tries to persist to disk the chunk)
  `time curl -sSL --fail http://localhost:9000/minio/health/live`
4. notice that the curl query blocks for a few seconds

Attention : to reproduce, need a really slow filesystem for minio backend (see Context below)

## Context

We're running minio over a slow NFS v3 backend (dedicated server at OVH using [OVH NAS HA](https://www.ovh.co.uk/nas/) which exports a ZFS pool that we mount as NFS v3 with nfs options (`local_lock=none`) else minio won't start.

When trying to upload large (over 1 Gb files) from our applications, we noticed that minio gets restarted by kubernetes. After investigating, the reason was that we had liveness and readiness probes with a timeoutSeconds of 1, while minio was taking much longer to respond under load. After 3 failed liveness probes, kubernetes would destroy the minio pod and our upload failed.

As a workaround, we configured our s3 client library (the https://github.com/fog/fog-aws library) to explicitly split the file being uploaded into 5 Mb chunks instead of trying to upload as a single chunk (amazon s3 allows up to 5Gb per chunk).

## Regression

No

## Your Environment

* Version used (`minio version`): RELEASE.2019-02-06T21-16-36Z
* Environment name and version (e.g. nginx 1.9.1): ruby 2.4 code using the `fog/aws` v3.3.0 library to access minio
* Server type and version: centos 7.x
* Operating System and version (`uname -a`): Linux minio-14-dnnh7 4.19.8-1.el7.elrepo.x86_64 #1 SMP Sat Dec 8 10:07:47 EST 2018 x86_64 Linux

**Comment by harshavardhana** [comment] 2019-02-11 17:39
Liveness checks will fail if the backend is down or completely slow to respond, it is better to turn it off if you are not interested.

**Comment by nitisht** [comment] 2019-02-13 13:11
closing this as working as intended @jperville , do feel free to get back if you think otherwise..

**Closed as completed by nitisht** 2019-02-13 13:11 UTC
Labels: working as intended, community, priority: medium

**Comment by victornoel** [comment] 2019-06-05 15:37
@harshavardhana @nitisht  we are using minio in front of an azure blob storage and it seems we are hitting the present issue because minio is taking a long time to push to azure (the file is big) which makes the liveness probe fail after enough time.

Two questions:
- Is it maybe related to #7042 and why it's not pushing to azure in multple chunks?
- Would you have some ideas as what would be the correct way to handle such a situation? We would prefer not disable the liveness probe.

Thanks

**Comment by harshavardhana** [comment] 2019-06-05 16:03
How large is the file @victornoel ?  How did you figure large file upload is the issue? . Also please open a new issue with answers to my questions asked here.

**Comment by victornoel** [comment] 2019-06-06 08:55
@harshavardhana thx, here it is #7754
