### ISSUE TITLE
mc.exe produces weird output during Jenkins jobs

### ISSUE THREAD

**Issue by alexellis** [minio/minio#3740] opened 2017-02-13 11:21 UTC
Jenkins jobs provide a "console log / output" from the steps it runs during a build. I'm using mc.exe to copy some build artifacts into a workspace before doing a build.

## Expected Behavior
```
"myminio/temp/xmlpdf11.dll" -> "c:/jenkins/workspace/SomeBuild/temp/xmlpdf11.dll"
```

## Current Behavior

```
â€˜myminio/temp/xmlpdf11.dllâ€™ -> â€˜c:/jenkins/workspace/SomeBuild/temp/xmlpdf11.dllâ€™
```

## Possible Solution

Detect terminal or lack thereof and produce legible/clear output for this scenario.

## Steps to Reproduce (for bugs)

1. Create a Jenkins master on Windows (maybe just run the Jenkinsci Docker image)
2. Create a job with a Windows Batch build step and invoke `mc.exe cp`

## Context

This provides confusing output for people using the builds and additional non-sense characters in the build output.

## Your Environment

- Windows 2012 R2 / 6.3
- Terminal: cmd.exe
- mc version:

```
Version: 2017-02-06T20:16:19Z
Release-tag: RELEASE.2017-02-06T20-16-19Z
Commit-id: 2c8115de4edc5612525488b1b3b804689d336d01
```

**Comment by harshavardhana** [comment] 2017-02-13 16:50
This is expected on consoles which pretend to be proper consoles but don't behave like one. We have an option for this I.e --no-color to turn off color printing. This would avoid tbe problem.

**Comment by alexellis** [comment] 2017-02-13 17:00
Doesn't seem to improve the output. I was using it with --quiet too?

**Comment by harshavardhana** [comment] 2017-02-13 18:00
> Doesn't seem to improve the output. I was using it with --quiet too?

It won't help looks like the issue is with the UTF-8 character we use for quoting the strings - most modern terminals do support it.  See if there is a workaround by adding like 

```
TERM=xterm
```

as environment variable for jenkins console.

**Comment by harshavardhana** [comment] 2017-02-20 02:33
Closing this in favor of https://github.com/minio/mc/issues/2028

**Closed as completed by harshavardhana** 2017-02-20 02:33 UTC
Labels: community
