### ISSUE TITLE
Case of missing some files after uploading large amount of data

### ISSUE THREAD

**Issue by dcharbonnier** [minio/minio#3784] opened 2017-02-21 18:38 UTC
## Expected Behavior
I expect to retrieve my file after uploading them

## Current Behavior
Version RELEASE.2017-02-16T01-47-30Z is corrupting the files, it return a 200 on a PUT but then the server return 503 or 404 depending of the case.
3 files on 100000's so don't expect to spot it with a simple test.

**Comment by harshavardhana** [comment] 2017-02-21 19:57
@dcharbonnier are you using multipart or single PUT to upload the files ?

**Comment by harshavardhana** [comment] 2017-02-21 20:01
Also any logs that you might share would be helpful . We can look at the backend directly and see if the files really uploaded or not. It PUT said 200 it is guaranteed that the file is indeed written to disk. GET receiving 404 or 503 is either quorum related issue which is perhaps generated due to some network issue.

**Comment by harshavardhana** [comment] 2017-02-21 20:45
https://gist.github.com/dcharbonnier/7bbf9195f803866cba608f8a20a542fc - missing files looks like a successful rename.

**Comment by harshavardhana** [comment] 2017-02-21 20:59
Relevant `xl.json` value 

```
{"version":"1.0.0","format":"xl","stat":{"size":4224360,"modTime":"2017-02-21T12:41:30.87916948Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":1,"distribution":[3,4,1,2],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce"}]},"minio":{"release":"RELEASE.2017-02-16T01-47-30Z"},"meta":{"md5Sum":"2a5fb825c508bc66870b63a86f0b2566"},"parts":[{"number":1,"name":"part.1","etag":"","size":4224360}]}
```

```
time="2017-02-21T15:28:24Z" level=error msg="Unable to create an object." cause="#has incomplete body" source="[object-handlers.go:479:objectAPIHandlers.PutObjectHandler()]" stack="erasure-createfile.go:44:erasureCreateFile xl-v1-object.go:558:xlObjects.PutObject <autogenerated>:848:(*xlObjects).PutObject object-handlers.go:476:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm"
time="2017-02-21T15:26:25Z" level=error msg="Unable to write to client." cause="Storage resources are insufficient for the read operation." source="[object-handlers.go:161:objectAPIHandlers.GetObjectHandler()]" stack="erasure-readfile.go:110:getReadDisks erasure-readfile.go:239:erasureReadFile xl-v1-object.go:285:xlObjects.GetObject <autogenerated>:845:(*xlObjects).GetObject object-handlers.go:160:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm"
time="2017-02-21T15:26:25Z" level=error msg="Unable to calculate checksum working-files/6e9f7e13-790e-4627-b403-981ac5cf9895/part.1" cause="file not found" source="[erasure-readfile.go:317:isValidBlock()]"
time="2017-02-21T15:26:25Z" level=error msg="Unable to read part.1 of the object `working-files/6e9f7e13-790e-4627-b403-981ac5cf9895`." cause="Read failed. Insufficient number of disks online" source="[xl-v1-object.go:287:xlObjects.GetObject()]" stack="erasure-readfile.go:110:getReadDisks erasure-readfile.go:239:erasureReadFile xl-v1-object.go:285:xlObjects.GetObject <autogenerated>:845:(*xlObjects).GetObject object-handlers.go:160:objectAPIHandlers.GetObjectHandler api-router.go:56:(objectAPIHandlers).GetObjectHandler-fm"
```

**Comment by vadmeste** [comment] 2017-02-21 21:14
@dcharbonnier, can you paste the second xl.json content ?

**Comment by dcharbonnier** [comment] 2017-02-21 22:21
```
node1.st2:
    {"version":"1.0.0","format":"xl","stat":{"size":4224360,"modTime":"2017-02-21T12:41:30.87916948Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":4,"distribution":[3,4,1,2],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"8fac12381e3c7d05b6ea418913438ba6f76438c841f1740bdf664a93963114d0835db79e99f4dc04105c938dc5856661c2b54a3011d1fb242341b10ac74ffd46"}]},"minio":{"release":"RELEASE.2017-02-16T01-47-30Z"},"meta":{"md5Sum":"2a5fb825c508bc66870b63a86f0b2566"},"parts":[{"number":1,"name":"part.1","etag":"","size":4224360}]}
node2.st2:
    {"version":"1.0.0","format":"xl","stat":{"size":4224360,"modTime":"2017-02-21T12:41:30.87916948Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":2,"parity":2,"blockSize":10485760,"index":1,"distribution":[3,4,1,2],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce"}]},"minio":{"release":"RELEASE.2017-02-16T01-47-30Z"},"meta":{"md5Sum":"2a5fb825c508bc66870b63a86f0b2566"},"parts":[{"number":1,"name":"part.1","etag":"","size":4224360}]}
node0.st2:
    cat: /minio/working-files/b8527691-9fb8-45b8-af2c-a45cca3953d0/xl.json: No such file or directory
node3.st2:
    cat: /minio/working-files/b8527691-9fb8-45b8-af2c-a45cca3953d0/xl.json: No such file or directory
```

**Comment by vadmeste** [comment] 2017-02-22 11:03
I don't think the bug comes from rename() because this latter is atomic. The question is why we have part.1 empty with mismatched checksum.

**Comment by vadmeste** [comment] 2017-02-22 11:18
> I don't think the bug comes from rename() because this latter is atomic. The question is why we have part.1 empty with mismatched checksum.

Sorry, the checksum is correct, but both of xl.json has the same modtime so both of xl.json are generated at the same time, it looks like the problem is inside erasureCreateFile.

**Comment by vadmeste** [comment] 2017-02-22 13:59
By the way, I think we need to discuss the fact that PutObject is relying on quorum in different places. A node which fails to accomplish one action shouldn't continue to work as nothing is happened.

**Comment by dcharbonnier** [comment] 2017-02-22 15:11
warning, don't consider too fast that a node is out, a network error does not mean the node is failing. You put a lot of errors related to supposed communication problems between the hosts but at the same time, the download of the files never fail for a network error between the client and the host

**Comment by harshavardhana** [comment] 2017-02-26 20:03
Fixes - #3795 #3804 address this problem.  @dcharbonnier we will be making a new release until then if possible can you try ":edge" and validate if the issue doesn't occur anymore?

**Comment by dcharbonnier** [comment] 2017-02-26 20:29
Amazing will check intensively tomorrow, thx

**Comment by harshavardhana** [comment] 2017-03-01 06:06
@dcharbonnier were you able to validate - do we proceed and close this bug?

**Comment by harshavardhana** [comment] 2017-03-01 22:22
Closing this as fixed, @dcharbonnier feel free to re-open if you see issues again.

**Closed as completed by harshavardhana** 2017-03-01 22:22 UTC
Labels: priority: severe, community

**Comment by dcharbonnier** [comment] 2017-03-03 06:53
Looks good, the errors rate reduced so much that its not possible to say if it's because tge clusters bever encountered the race condition again or if the problem is fixed.

**Comment by harshavardhana** [comment] 2017-03-03 07:01
> Looks good, the errors rate reduced so much that its not possible to say if it's because tge clusters bever encountered the race condition again or if the problem is fixed.

Please keep monitoring - we will be available to help in anyway we can.
