### ISSUE TITLE
Total Capacity - can't figure out if this is a mistake or if I'm just not doing something correctly

### ISSUE THREAD

**Issue by virtuman** [minio/minio#3925] opened 2017-03-18 06:11 UTC
Just tried deploying minio on docker swarm and getting some very mixed messages.

I launched the sample docker-compose with the command as described in the 
https://github.com/minio/minio/tree/master/docs/orchestration/docker-swarm
>> docker stack deploy --compose-file=docker-compose.yaml minio_stack

however after it launched, I'm getting this message that only 4.4 GB is available out of 226GB, but based on the attached logs it seems somewhat invalid. Both the logs and the UI display same value of 4.4GB being available.

```
Created minio configuration file at /root/.minio

 Minio is 50 days 18 hours 35 minutes old
 Update: docker pull minio/minio

time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio2 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio3 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio2 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio3 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio2 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio3 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio2 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio3 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio2 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio3 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio2 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
time="2017-03-18T05:53:08Z" level=error msg="Failed to lookup host" cause="lookup minio3 on 127.0.0.11:53: no such host" source="[object-api-common.go:153:isLocalStorage()]"
Initializing data volume for first time. Waiting for other servers to come online (elapsed 19s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 40s)
Initializing data volume for first time. Waiting for other servers to come online (elapsed 56s)
Initializing data volume for first time. Waiting for first server to come online (elapsed 1m10s)
Initializing data volume for first time. Waiting for first server to come online (elapsed 1m10s)

Initializing data volume.
[01/04] http://minio1:9000/export - 113 GiB online
[02/04] http://minio2:9000/export - 226 GiB online
[03/04] http://minio3:9000/export - 204 GiB online
[04/04] http://minio4:9000/export - 205 GiB online

Endpoint:  http://10.255.0.16:9000  http://10.255.0.15:9000  http://10.0.0.9:9000  http://10.0.0.8:9000  http://172.18.0.3:9000  http://127.0.0.1:9000
AccessKey: AKIAzzzzzzzzzzE
SecretKey: wJalrXzzzzzzzzzXAzzzzY
Region:    us-east-1
SQS ARNs:  <none>

Browser Access:
   http://10.255.0.16:9000  http://10.255.0.15:9000  http://10.0.0.9:9000  http://10.0.0.8:9000  http://172.18.0.3:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.255.0.16:9000 AKIA...........E wJalrXUtnFE..........Y

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide

Drive Capacity: 4.4 GiB Free, 226 GiB Total
Status:         4 Online, 0 Offline. We can withstand [2] more drive failure(s).
```

**Comment by krishnasrinivas** [comment] 2017-03-18 06:39
@virtuman looks like a bug, we'll investigate.

**Comment by harshavardhana** [comment] 2017-03-18 06:52
> Minio is 50 days 18 hours 35 minutes old

Can you update your docker image? we have recently made a release which you should try and let us know if this is reproducible still - Thanks

**Comment by harshavardhana** [comment] 2017-03-23 05:24
> Can you update your docker image? we have recently made a release which you should try and let us know if this is reproducible still - Thanks

@virtuman were you able to validate with latest release?

**Comment by harshavardhana** [comment] 2017-03-30 06:34
Closing this issue @virtuman - please re-open if you observe the issue again. Thanks

**Closed as completed by harshavardhana** 2017-03-30 06:34 UTC
Labels: working as intended, community
