### ISSUE TITLE
unexpected EOF (*errors.errorString)

### ISSUE THREAD

**Issue by littlesweetlove** [minio/minio#12832] opened 2021-07-30 03:06 UTC
## Expected Behavior
PutObjectPart succeeded

## Current Behavior
```
API: PutObjectPart(bucket=file-server, object=file-server/CitiesSkylines.zip)
Time: 10:24:15 CST 07/30/2021
DeploymentID: b64d8501-b56e-4c54-ba82-46ae7af3dc95
RequestID: 169670562C1138BC
RemoteHost: 192.168.2.214
Host: 192.168.2.61:8008
UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Error: unexpected EOF (*errors.errorString)
       4: cmd\fs-v1-helpers.go:316:cmd.fsCreateFile()
       3: cmd\fs-v1-multipart.go:318:cmd.(*FSObjects).PutObjectPart()
       2: cmd\object-handlers.go:2757:cmd.objectAPIHandlers.PutObjectPartHandler()
       1: net\http\server.go:2069:http.HandlerFunc.ServeHTTP()
```

```
API: PutObjectPart(bucket=file-server, object=file-server/CitiesSkylines.zip)
Time: 10:24:15 CST 07/30/2021
DeploymentID: b64d8501-b56e-4c54-ba82-46ae7af3dc95
RequestID: 16967020D8C84824
RemoteHost: 192.168.2.214
Host: 192.168.2.61:8008
UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
Error: unexpected EOF (*errors.errorString)
       4: cmd\fs-v1-helpers.go:316:cmd.fsCreateFile()
       3: cmd\fs-v1-multipart.go:318:cmd.(*FSObjects).PutObjectPart()
       2: cmd\object-handlers.go:2757:cmd.objectAPIHandlers.PutObjectPartHandler()
       1: net\http\server.go:2069:http.HandlerFunc.ServeHTTP()
```
## Steps to Reproduce (for bugs)
```
 /**
             * Generate the upload address from this code
             */
            for (int i = 1; i <= partCount; i++) {
                reqParams.put("partNumber", String.valueOf(i));
                String uploadUrl = customMinioClient.getPresignedObjectUrl(
                        GetPresignedObjectUrlArgs.builder()
                                .method(Method.PUT)
                                .bucket(minioProperties.getBucket())
                                .object(objectName)
                                .expiry(1, TimeUnit.DAYS)
                                .extraQueryParams(reqParams)
                                .build());
                partList.put(""+i,uploadUrl);
            }

```
Response example:
```
{
    "code": 200,
    "message": "success",
    "data": {
        "uploadId": "0696ea58-cd55-47f4-9a77-b653749e3a55",
        "uploadUrls": {
            "1": "http://192.168.2.61:8008/file-server//gydg?uploadId=0696ea58-cd55-47f4-9a77-b653749e3a55&partNumber=1&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210730%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210730T025333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=6b2b889e0eb6bb2c23f12cd118104a7f952b5bd3a00122ae68682b9903016cdc",
            "2": "http://192.168.2.61:8008/file-server//gydg?uploadId=0696ea58-cd55-47f4-9a77-b653749e3a55&partNumber=2&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210730%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210730T025333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=0f7d62a69ea6903f9af4e66b26cc2485936677ef071d5ac3a242563bf7c48def"
        }
    }
}
```
uploadpart example:

```
PUT http://192.168.2.61:8008/file-server//gydg?uploadId=0696ea58-cd55-47f4-9a77-b653749e3a55&partNumber=1&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210730%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210730T025333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=6b2b889e0eb6bb2c23f12cd118104a7f952b5bd3a00122ae68682b9903016cdc \
--header 'Content-Type: application/octet-stream' \
--data-binary '@/D:/jpgone'
```

```
PUT http://192.168.2.61:8008/file-server//gydg?uploadId=0696ea58-cd55-47f4-9a77-b653749e3a55&partNumber=2&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20210730%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20210730T025333Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=0f7d62a69ea6903f9af4e66b26cc2485936677ef071d5ac3a242563bf7c48def\
--header 'Content-Type: application/octet-stream' \
--data-binary '@/D:/jpgone'
```

## Your Environment

* Version used (RELEASE.2021-07-12T02-44-53Z):
* Server setup and configuration:
* Operating System and version (`windows10`):

**Comment by littlesweetlove** [comment] 2021-07-30 03:34
By the way ,The merged file is damaged.

**Comment by harshavardhana** [comment] 2021-07-30 04:23
> API: PutObjectPart(bucket=file-server, object=file-server/CitiesSkylines.zip)
> Time: 10:24:15 CST 07/30/2021
> DeploymentID: b64d8501-b56e-4c54-ba82-46ae7af3dc95
> RequestID: 169670562C1138BC
> RemoteHost: 192.168.2.214
> Host: 192.168.2.61:8008
> UserAgent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
> Error: unexpected EOF (*errors.errorString)
>        4: cmd\fs-v1-helpers.go:316:cmd.fsCreateFile()
>        3: cmd\fs-v1-multipart.go:318:cmd.(*FSObjects).PutObjectPart()
>        2: cmd\object-handlers.go:2757:cmd.objectAPIHandlers.PutObjectPartHandler()
>        1: net\http\server.go:2069:http.HandlerFunc.ServeHTTP()

Your client is incorrectly implemented @littlesweetlove - you are not sending all the sizes here it is failing with io.UnexpectedEOF because your client is prematurely closing the connection.

Of course, the object will be corrupted because you are trying to finish the transaction incorrectly. The file is incomplete..

**Comment by littlesweetlove** [comment] 2021-07-30 04:58
what does mean "you are not sending all the sizes"

**Comment by harshavardhana** [comment] 2021-07-30 06:02
> what does mean "you are not sending all the sizes"

Try upload the object with `mc` and tell me if you can reproduce the issue. If not you need to first fix your client code to send all the content. 

Server is seeing io.UnexpectedEOF because all the content is not sent, client prematurely closes the connection before sending all the content.

**Comment by littlesweetlove** [comment] 2021-07-30 07:54
Well,Is not minio issues,other issues.Thinks you teach me.Next step I will make Breakpoint upload or download

**Closed as completed** 2021-07-30 07:54 UTC
Labels: working as intended, community

**Comment by lynch2git** [comment] 2021-09-22 11:49
hello, I also encountered this problem, how did you solve it ? @littlesweetlove

**Comment by lynch2git** [comment] 2021-09-26 12:36
I have solved this problem. I don’t know the cause of the problem. I changed the version of minio from RELEASE.2021-09-15T04-54-25Z to RELEASE.2020-12-03T05-49-24Z to solve it.
