### ISSUE TITLE
Disable Metrics / Add authentication

### ISSUE THREAD

**Issue by SteveEdson** [minio/minio#7493] opened 2019-04-07 11:42 UTC
I wasn't aware that minio was exposing metrics about my server publicly, without authentication. Is it possible to disable this, or add authentication to it?

I'm running it behind Traefik, so I'm aware I can do it that way, I'd just rather have this built into Minio itself.

## Expected Behavior
Metrics can be disabled / add authentication

## Current Behavior
Public and enabled by default

## Your Environment
Docker minio - `image: minio/minio:RELEASE.2019-03-27T22-35-21Z`

**Comment by kannappanr** [comment] 2019-04-07 20:08
@SteveEdson Thanks for filing this issue. Will check internally and get back to you with what we decide.

**Comment by hamid-elaosta** [comment] 2019-04-09 08:36
@SteveEdson please tell me this isn't on the main port? If not, at least we can firewall the port for an easy solution.

I'm going to have to check this when I get to a PC.

**Comment by SteveEdson** [comment] 2019-04-09 08:39
Yep, same port that Minio runs on. In theory, every instance of Minio is also reporting metrics at `/minio/prometheus/metrics`

**Comment by hamid-elaosta** [comment] 2019-04-09 08:43
Ugh, and it's unauthenticated?

That's a bother. 

Minio: please at an option to disable this, an open metrics endpoint is not acceptable in my "environment".

**Comment by harshavardhana** [comment] 2019-04-09 08:46
Prometheus exporter endpoints are expected to be unauthenticated by default, this is the most idiomatic way to do it.

**Comment by SteveEdson** [comment] 2019-04-09 08:53
> "endpoints are expected to be unauthenticated by default"

That's one thing, but even if I agree or disagree with that, how do we turn it off / authenticate it?

There's a difference between Prometheus endpoints being unauthenticated by default, and enabled by default.

**Comment by harshavardhana** [comment] 2019-04-09 09:06
> There's a difference between Prometheus endpoints being unauthenticated by default, and enabled by default.

It is enabled by default just as traefik enables it by default on /metrics, and yes we don't provide an option to disable it because the reasoning is quite simply when would you not want to monitor your MinIO deployments, all production deployments always need it. 

I don't see anyone adding authenticated layers for /metrics endpoints - popular examples

- https://coreos.com/etcd/docs/latest/op-guide/monitoring.html 
- https://www.cockroachlabs.com/docs/stable/monitor-cockroachdb-with-prometheus.html

Moving this to working as intended for now.

**Comment by hamid-elaosta** [comment] 2019-04-09 09:11
> "endpoints are expected to be unauthenticated by default"

That's a sweeping statement that I'm afraid doesn't apply for security focused industry.

I understand that security is not the main focus of Minio , but it needs more focus than it currently has.

We_always_ use Prometheus authenticated. I need an option to disable it, at least, or require authentication.

Now I know this is as it is; im forced to manage it in a reverse proxy, which is more effort and logistical challenge to a container deployment.

Best case, metrics should be on a separate management port, authenticated by default with an option to disable it entirely.

**Comment by SteveEdson** [comment] 2019-04-09 09:14
Traefik doesn't enable it by default, you have to add the config option as defined at:

https://docs.traefik.io/configuration/metrics/

> "when would you not want to monitor your MinIO deployments"

That's not the problem, I don't want **others** to be able to monitor **my** instance.

**Comment by harshavardhana** [comment] 2019-04-09 16:05
> > "endpoints are expected to be unauthenticated by default"

First, this line is quoted out of context the entire word before this line is removed @SteveEdson and @hamid-elaosta the entire statement was following

> Prometheus exporter endpoints are expected to be unauthenticated by default

With that established, there is a good reason for this as I explained above, that most software implementing Prometheus endpoints all of them implement unauthenticated endpoints. 

- etcd
- cockroachdb 
- coredns

and many more

The primary reason is to do with is how Prometheus poller extracts data out - https://prometheus.io/docs/operating/security/

> Traefik doesn't enable it by default, you have to add the config option as defined at:

My bad because I assumed that

```
./traefik_linux-amd64 --help | grep metrics |head -1
    --metrics                                     Enable a metrics exporter                                                        (default "true")
```

That it's always enabled, maybe this should be `false` as presented on the command line - while that maybe it is still unauthenticated. There is no authentication involved in /metrics. So if you do have traefik running and /metrics enabled anyone can monitor your traefik instance.

> I understand that security is not the main focus of Minio , but it needs more focus than it currently has.

It is not that we didn't debate this before internally before implementing an unauthenticated endpoint, we had a stricter signature v4 based authentication for metrics before and we saw community members started writing Prometheus exporter - which started taking access key/secret key credentials. 

Taking credentials like this on a Prometheus exposes your instance more than what /metrics can do and completely defeats the security aspect of an authenticated endpoint.

So we reviewed other widely deployed projects such as etcd, cockroachdb - /metrics is always available by default and is unauthenticated. So we moved to an unauthenticated endpoint simplifying the overall usage for all our kubernetes deployments.

> That's not the problem, I don't want **others** to be able to monitor **my** instance.

@SteveEdson I am unable to understand what is **others** here, one can always monitor an HTTP service regardless of /metrics enabled or otherwise. I don't see how you will get that with `traefik` either. There are other endpoints such as /healthcheck, /readiness endpoints which are all unauthenticated as well.

**Comment by SteveEdson** [comment] 2019-04-09 16:24
> "most software implementing Prometheus endpoints all of them implement unauthenticated endpoints."

CoreDNS mainly runs on port 53 though, metrics are exposed on port 9253, so I'd have the option of not exposing that port, and therefore metrics to the public.

CoachroachDB exposes metrics through its Admin UI, on port 8080, not on its main ports, so again, I'd have the option of not exposing port 8080 to the public, therefore preventing anyone getting access to my metrics.

> "There is no authentication involved in /metrics. So if you do have traefik running and /metrics enabled anyone can monitor your traefik instance."

Not true, I can set the following config in Traefik and have my metrics only through authenticated users.

```toml
[entryPoints]
  [entryPoints.traefik]
  address = ":9002"
    [entryPoints.traefik.auth.basic]
    users = ["username:password"]

[metrics.prometheus]
    entryPoint = "traefik"
```

> "@SteveEdson I am unable to understand what is others here"

Other people that I don't want getting access to my metrics, other than me.

**Comment by harshavardhana** [comment] 2019-04-09 16:39
> Not true, I can set the following config in Traefik and have my metrics only through authenticated users.
> 
> ```toml
> [entryPoints]
>   [entryPoints.traefik]
>   address = ":9002"
>     [entryPoints.traefik.auth.basic]
>     users = ["username:password"]
> ```

This authentication is for your entire traefik deployment, this is not for /metrics alone @SteveEdson - how can you make this work with S3 clients? and Basic authentication is not an authentication you can rely on anyone can know this without a TLS connection. 

> CoreDNS mainly runs on port 53 though, metrics are exposed on port 9253, so I'd have the option of not exposing that port, and therefore metrics to the public.
> 

This I agree since its a DNS service it needs to be on a different port.

> CoachroachDB exposes metrics through its Admin UI, on port 8080, not on its main ports, so again, I'd have the option of not exposing port 8080 to the public, therefore preventing anyone getting access to my metrics.
> 

The reason we do on same port is simplicity, having multiple ports is not a requirement for MinIO.

**Comment by hamid-elaosta** [comment] 2019-04-09 17:12
> First, this line is quoted out of context the entire word before this line is removed @SteveEdson and @hamid-elaosta the entire statement was following.

Apologies, there was no malicious intention and I see how it looks like I was quoting it out of context. This was short because I was typing on mobile without access to advanced editing functions on Github, or a proper keyboard for that matter.

> Prometheus exporter endpoints are expected to be unauthenticated by default

Expectation by an industry largely unconcerned with security at the level those of us that are concerned with it require, doesn't mean the rest of us should be ignored. In fact, implementing any of the options that would solve our issue does not exclude everyone else from running the way they desire.

What this really comes down to is that we, as users of Minio, are asking for a solution to not leaving Minio's metrics open to anyone who has the address of our instances on the internet.

Whether that means authentication, a separate port or simply just a flag to turn it off, it would really help us with delivering on our security requirements, and any of them is better than the position we're currently in.

**Comment by harshavardhana** [comment] 2019-04-09 17:20
Okay understood. Thanks will get back after discussing with rest of the team.

**Comment by Leosirth** [comment] 2019-04-19 22:22
I don't know if Prometheus support endpoints with authentication.
If not, maybe the best way to implement this is to have a dedicated port for the metrics.

In that way the minio server port can be externally exposed, while the metrics port could be restricted to only local access.

**Comment by SteveEdson** [comment] 2019-04-19 23:00
Prometheus supports a variety of authentication methods including http auth
and bearer tokens within the authorisation header, yes.

**Comment by harshavardhana** [comment] 2019-04-20 05:40
We are planning to implement bearer token based approach.

**Comment by thomasf** [comment] 2019-09-23 09:10
I don't know how common this practice is but I almost always expose metrics end points along with other non production stuff on it's own listening port.. It's just a more convenient way to keep internal infrastructure stuff separated from potential public http protocols.  This way it's much easier to hard firewall/route monitoring stuff onto it's own network without having to involve a http router. Both methods are probably fine for different people though, it depends a bit on how your networking infrastructure is set up.

**Comment by harshavardhana** [comment] 2019-09-23 09:35
> I don't know how common this practice is but I almost always expose metrics end points along with other non production stuff on it's own listening port.. It's just a more convenient way to keep internal infrastructure stuff separated from potential public http protocols. This way it's much easier to hard firewall/route monitoring stuff onto it's own network without having to involve a http router. Both methods are probably fine for different people though, it depends a bit on how your networking infrastructure is set up.

We would like to avoid running a single MinIO service on multiple ports one for incoming traffic and another for just metrics alone. We just solved it by using the HTTP endpoint/router based approach.

master branch has now support for authentication, closing this issue.

**Closed as completed by harshavardhana** 2019-09-23 09:35 UTC
Labels: community, fixed, priority: medium
