### ISSUE TITLE
Total crash of mino instances

### ISSUE THREAD

**Issue by xcdr** [minio/minio#8488] opened 2019-11-06 09:25 UTC
Hi.

I have 3 minio nodes with 8 disks each, minio is running on FreeBSD 12, disks are JBOD with ZFS on each disk.

Minio started with following setup:
```
minio_env="GOMAXPROCS=6 MINIO_ACCESS_KEY=XXX MINIO_SECRET_KEY=YYY"
minio_disks="http://192.168.216.18{1...3}/mnt/minio/{1...8}"
```

I have ~4.5TB of files which  are jpeg photos synced with `mc mirror` command at full speed ~80MB/s.

## Expected Behavior
Successfull sync or readable log entries.

## Current Behavior

When I try sync again by `mc mirror --overwrite --remove . minio-3s` sync speed is ~150kB/s (maybe not many transfered files?) and two minio nodes crash after some time.

Third of nodes never crashed but all nodes are identical.

I have no idea what's going on, I can't see network or hardware issues.

Attached log files from minio-1 and minio-2, on minio-3 log is always empty.
* [minio-1.log.gz](https://github.com/minio/minio/files/3813527/minio-1.log.gz)
* [minio-2.log.gz](https://github.com/minio/minio/files/3813528/minio-2.log.gz)

Statuses from `mc admin info server minio-3s` on all nodes are strange, current:
```
  Version: 2019-10-12T01:39:57Z
  Storage: Used 8.0 TiB, Free 5.7 TiB
  Drives: 8/8 OK
```

But after full sync without errors the same command show only 3TiB

## Your Environment
```
root@minio-1:~ # minio version
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
```

```
root@minio-1:~ # freebsd-version
12.0-RELEASE-p11
```

**Comment by nitisht** [comment] 2019-11-06 13:04
Based on the logs looks like both `...182` and `...183` are not reachable since the beginning @xcdr are you sure MinIO was successfully running before mirror was started?

**Comment by Praveenrajmani** [comment] 2019-11-06 13:48
I can see this log here

```
API: SYSTEM()
Time: 22:45:17 CET 11/05/2019
DeploymentID: c56fa2b4-426a-429f-ac34-88afd499b3b1
Error: Server not initialized, please try again
       peerAddress=192.168.216.183:9000
       1: /wrkdirs/usr/ports/www/minio/work/minio-RELEASE.2019-10-12T01-39-57Z/cmd/notification.go:468:cmd.(*NotificationSys).ServerInfo.func1()
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x8029ea45a m=2 sigcode=65543
```
Can you try increase the user process limits?

**Comment by Praveenrajmani** [comment] 2019-11-06 13:53
@nitisht Can you re-assign me? unassigned by mistake..

**Comment by xcdr** [comment] 2019-11-06 14:42
@nitisht Yes, 

> Based on the logs looks like both `...182` and `...183` are not reachable since the beginning @xcdr are you sure MinIO was successfully running before mirror was started?

Yes, works well and crashed after ~7 hours of `mc mirror`

> Can you try increase the user process limits?

Procstat show me 34203 max user processes:
```
root@minio-1:~ # procstat -l 66507|grep process
66507 minio            maxprocesses           34203            34203
```

Current number of minio threads is 333 after 30min of mirroring:
```
root@minio-1:~ # ps -H 66507 | wc -l
     333
```
I can set higher number of max proc but this is very high limit. Minio should controll the number of processes and not allowed more than configured somewhere.

I currently observe numberr of processess and connections.

PS. sensible log entries, not crash dump is very desirable.

**Comment by xcdr** [comment] 2019-11-06 15:15
Number of threads is groving, 712 at this moment.

This is normal or something wrong with closing http connections?

```
root@minio-1:~ # netstat -an4 | grep 9000 | grep -c ESTABLISHED
1181
```
Number of ESTABLISHED connections from and to port 9000 is also groving.

**Comment by Praveenrajmani** [comment] 2019-11-06 16:23
@xcdr looks like you are hitting `kernel.pid_max` sysctl limit. Can you increase that? And also can you set `CGO_ENABLED=0` and increase the `GOMAXPROCS=6` if that didn't work.. This can probably be the cause.

**Comment by harshavardhana** [comment] 2019-11-06 17:32
The problem is you have some system level limits @xcdr and you are pushing the server beyond this limit.

pthead_create failure means there is a lot I/O threads being created to handle your incoming requests.

So you may need to remove GOMAXPROCS=6 and also try increasing system level ulimits

**Comment by xcdr** [comment] 2019-11-06 23:01
> @xcdr looks like you are hitting `kernel.pid_max` sysctl limit. Can you increase that? And also can you set `CGO_ENABLED=0` and increase the `GOMAXPROCS=6` if that didn't work.. This can probably be the cause.

I cannot increase pid_max, this is max value:
```
root@minio-1:~ # sysctl kern.pid_max
kern.pid_max: 99999
```
FreeBSD generates PID random, not incremental as Linux.

I increase max number of processes tomorrow but I cannot understand why first mirror was OK and problem is with incremental mirror.

After some experiments I suppose this is related to mirror speed. Number of processes also looks too high for comparing directories from only one client! In my opinion I shouldn't hit limits in that simple case.

**Comment by xcdr** [comment] 2019-11-07 15:49
I investigated today limits for minio accounts and there is no limits.

Limit 34203 of max processes is calculated on the fly by system based on amount of memory which is 32GB.

I added GOMAXPROCS because I want to limit minio for 6 cores, unset this variable nothing changes (added after problem occurs).

I already running `mc mirror` many small files ~0.5TB and minio instances is ~57 against 37 after daemon started - this is far below number of processes when yesterday doing incremental mirroring.

**Comment by Praveenrajmani** [comment] 2019-11-07 16:37
@xcdr Did you check `sysctl kernel.pid_max`?

**Comment by xcdr** [comment] 2019-11-07 19:55
> @xcdr Did you check `sysctl kernel.pid_max`?

Yes, I wrote about it two post above :-)

Continuation for my post above:

Second mirror runs > 4h and there is 74 only minio processes, I suspect the problem is only when mc mirror is run again on the same files and every file is compared. 

When finish I try run mc mirror again and compare with rclone (for exclusion bug in minio client).

Independly I belevie that behavior of minio server is ugly, no limits, warnings, startup times in log file and finally stack trace. Minio shoundn't overwrite log file when start again this break any log tracking, especially with tools such monit.

**Comment by Praveenrajmani** [comment] 2019-11-08 05:35
Did it happen even after you unset the GOMAXPROCS? @xcdr and what was the process count when you ran mc mirror on the same files?

**Comment by Praveenrajmani** [comment] 2019-11-08 07:24
@xcdr There is a golang issue on this - https://github.com/golang/go/issues/24484. Most likely to be fixed in go1.14

**Comment by Praveenrajmani** [comment] 2019-11-08 07:30
Can you also try recompiling with `CGO_ENABLED=0`? This might work

**Comment by xcdr** [comment] 2019-11-08 10:03
> Can you also try recompiling with `CGO_ENABLED=0`? This might work

I use FreeBSD package but I checked that CGO_ENABLED=0 is enabled by default in Makefile used to build this port.

> Did it happen even after you unset the GOMAXPROCS? @xcdr and what was the process count when you ran mc mirror on the same files?

Nothing change when GOMAXPROCS is set or no, when is unset then only more cpu usage and faster crash :-)

* I have no time for perfect test but when I try mc mirror I see that number of minio processes only grown, when I break mirroring number of processed not decreased.

* when I mirroring data then minio doesn't count space usage, recount is doing only when I stop mirroring and restart one of minio daemons

* sync using rclone doesn't increase number of minio instances and looks good at this moment

I wonder why minio not release unused resources when I break mc mirror and why doesn't recalculate disk usage.

Anyway it looks that mc mirror doing DOS on minio server when running second time on the same large data.

I leave rclone running for longer and check later how many minio instances is running (49 already)

UPDATE1: there is ~380 minio instances after 2 hours runnin rclone sync on 4.5TB data  and rclone purge on other smaller bucket.
UPDATE2: ~1k minio instances after 6 hours (mc doing the same number after ~1 hour)

**Comment by harshavardhana** [comment] 2019-11-08 15:08
We will try to reproduce it, this looks unusual.

**Comment by xcdr** [comment] 2019-11-08 16:13
OK.

Some info about data that might help You:
Small files (photos) with dir path depth=4, each dir contains ~0.5k files.
Data size ~4.5TB with ~10 million of files.

First mirroring was OK with full sped ~80MB/s, problem occurs when mirroring run second time (for incremental data), transfer was low ~500kB/s (maybe no much changes).

It doesn't matter when mc connected to first node or via nginx proxy with round robin balancer.

I have identical 3 nodes with 8x2.5'' WD-RED 750GB (slow disks) JBOD, each disk formatted using ZFS.

Server: FreeBSD 12 is default clean install, minio installed from package: `minio-2019.10.12.01.39.57`.

Client: Ubuntu 14.04 and 18.04, mc version `2019-10-09T22:54:57Z`.

Better behavior with rclone (but at thin moment sync is not finished/creashed yet):
```
rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.4
```

**Comment by xcdr** [comment] 2019-11-09 10:18
Today at ~6 am crashed minio-1, rclone works on minio-2 and minio-3.

Second mirror is much, much longer than first to empty bucket (first one was completed at one night).

UPDATE: minio-3 crashed at 11:28 am, rsync still mirroring, 3 times longer than first mirror and not finished.

**Comment by Praveenrajmani** [comment] 2019-11-10 07:07
@xcdr Can you submit memory & cpu profiles here for the analysis? You can use `mc` to create memory and cpu profiles. Check `mc admin profile -h`. You could start profiling by `mc admin profile start --type mem <alias>/` and stop it by `mc admin profile stop <alias>`

**Comment by Praveenrajmani** [comment] 2019-11-10 09:14
@xcdr @harshavardhana I analyzed a memory profile on the following scenario. Dropping down the details for reference

-- Mirroring an already mirrored source and destination (with no diff) - 4 nodes with 1 disk each

<b> Type: inuse_space </b> 

<b><i> localhost:9001 </i></b>

![image](https://user-images.githubusercontent.com/5410427/68541465-e72abd80-03c5-11ea-9242-391fd06da612.png)

<b><i> localhost:9002 </i></b>

![image](https://user-images.githubusercontent.com/5410427/68541569-21488f00-03c7-11ea-8c8d-1fff34ffc333.png)

<b><i> localhost:9003 </i></b>

![image](https://user-images.githubusercontent.com/5410427/68541560-ee060000-03c6-11ea-9ae9-e064a30c9b24.png)

<b><i> localhost:9004 </i><b>

![image](https://user-images.githubusercontent.com/5410427/68541632-d8450a80-03c7-11ea-9aa3-69c26af9e89d.png)

And `top | grep mc` is dropping the processes when stopped

**Comment by Praveenrajmani** [comment] 2019-11-10 09:39
As far as i can see the above figures, there is nothing unusual.. The notable recording is the `bpool.(*BytePoolCap).Get` which will be cleared away in a certain GC time interval

**Comment by xcdr** [comment] 2019-11-11 08:27
Yes, I'll try in about a hour after breakfast. I must restart processes a this moment because ~8.00 am crashed minio-1 and yesterday crashed minio-2.

**Comment by xcdr** [comment] 2019-11-11 12:45
There are profiles for mem and cpu.
* [profile-cpu.zip](https://github.com/minio/minio/files/3831330/profile-cpu.zip)
* [profile-mem.zip](https://github.com/minio/minio/files/3831331/profile-mem.zip)

When mem profile was running I stopped and started sync again. When I stopped there are ~800 avg threads, not decreased after stop sync and not increased after start.

**Comment by Praveenrajmani** [comment] 2019-11-11 14:09
![image](https://user-images.githubusercontent.com/5410427/68592768-da879180-04b9-11ea-9c0c-3e6d24a653ba.png)

The only memory spike i can see is `151848kB 60.42% 60.42%   151848kB 60.42%  github.com/ncw/directio.AlignedBlock` which is pretty much related to the pthread failure discussed above or even can be the physical limits. We could get a lead if we know the exact number of os threads at the time of the crash. You could give us the prometheus metric value - `go_threads` at the time of the crash. 

I think this is a golang bug as per golang/go#24484 and should be fixed probably in go1.14.

**Comment by xcdr** [comment] 2019-11-12 21:27
OK, I haven't prometheus in this environment but I should install this week and give You some stats.

Tell me how minio works on production with this bug?

My setup is rather small, data also is not very big and I unable make stable solution for production environment.

**Comment by harshavardhana** [comment] 2019-12-18 23:00
New version has been released PTAL @xcdr we have overhauled the listen bucket implementation etc. Things would have changed dramatically. 

For now closing this issue please re-open if seen again.

**Closed as completed by harshavardhana** 2019-12-18 23:00 UTC
Labels: community, fixed, triage
