### ISSUE TITLE
Click on the name, size, Last Modified  bug

### ISSUE THREAD

**Issue by zhen-ke** [minio/minio#3817] opened 2017-03-01 04:52 UTC
Click on the name, size, Last Modified when sorting, there will be copying the current file to copy the situation

<img width="1222" alt="2017-03-01 12 50 41" src="https://cloud.githubusercontent.com/assets/11960036/23446395/e3db47bc-fe7d-11e6-838a-4e40a265359c.png">

**Comment by harshavardhana** [comment] 2017-03-01 06:01
This issue is fixed by https://github.com/minio/minio/commit/fcad4a44fd01279955921a8c4054820d396021da

**Closed as completed by harshavardhana** 2017-03-01 06:01 UTC
Labels: community

**Comment by harshavardhana** [comment] 2017-03-01 06:04
Also closed as duplicate of https://github.com/minio/minio/issues/3809
