### ISSUE TITLE
cannot login to minio console

### ISSUE THREAD

**Issue by flixr** [minio/minio#12646] opened 2021-07-08 16:54 UTC
I upgraded from the previous RELEASE.2021-06-17T00-10-46Z to the latest RELEASE.2021-07-08T01-15-01Z and now I cannot log into the new integrated console (which looks super nice according to screenshots btw) with any of my existing user credentials (including root credentials).
Access via e.g. `mc` commandline tool works fine.

## Expected Behavior
I can login to the console, with any existing user. Just like with the browser before.

## Current Behavior
I get an Unauthorized message.

## Steps to Reproduce (for bugs)

1. updated to RELEASE.2021-07-08T01-15-01Z
2. try to login on web console -> I get redirected to the random port (which I can access) -> unauthorized

## Context

Running minio as binary via systemd: `/usr/local/bin/minio server --address :443 --certs-dir /etc/minio/certs /mnt/disk{1...4}/data`
The cert is a letsencrypt wildcard cert for our domain. I access minio via https://minio.ourdomain.com.

In the logs I see:
```
Jul 08 16:32:13 rc-minio01 minio[140598]: original error -> (user_login.go:50: invalid Login)
Jul 08 16:32:13 rc-minio01 minio[140598]: debugging error: Post "https://10.0.0.31:443/": x509: cannot validate certificate for 10.0.0.31 because it doesn't contain any IP SANs
```

## Regression

Yes

## Your Environment

* Version used (`minio --version`): RELEASE.2021-07-08T01-15-01Z
* Server setup and configuration: Ubuntu 20.04.2 LTS, running minio as binary with systemd, backed by four disks
* Operating System and version (`uname -a`): `Linux rc-minio01 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment] 2021-07-08 17:00
> ```
> Jul 08 16:32:13 rc-minio01 minio[140598]: debugging error: Post "https://10.0.0.31:443/": x509: cannot validate certificate for 10.0.0.31 because it doesn't contain any IP SANs
> ```

You are using incorrect certificates @flixr first, you need to fix that - your certs do not have any IP SANs information. If you have a domain cert then start MinIO server with that domain cert properly so that console can talk to 

For example if your domain is example.com start the server with `minio server --address example.com:443`

**Comment by harshavardhana** [comment] 2021-07-08 17:05
> Running minio as binary via systemd: `/usr/local/bin/minio server --address :443 --certs-dir /etc/minio/certs /mnt/disk{1...4}/data`

Run `minio server --address "minio.ourdomain.com:443" --certs-dir /etc/minio/certs /mnt/disk{1...4}/data` and it shall work fine - or add your IP to your certs.

**Comment by flixr** [comment] 2021-07-08 17:08
:+1: 
Thanks for the super quick response, that works! At least the login...

But before I could also access the browser via the https port 433, now I apparently need a separate port...
So is there now no way to allow access to the web console via same port as with the browser before?

Also for some users I have a policy set so that they can only access their own bucket, but with these users now no bucket is visible in the console anymore...

**Comment by ravindk89** [comment] 2021-07-08 17:09
@harshavardhana I'm going to update the docs for this, since we're not currently calling out this requirement for certs w/o IP SAN - can we generally recommend that for certs w/o that field, set `--address "DOMAIN:443`, where DOMAIN is covered by the wildcard?

Like assuming I have a wildcard cert for `*.example.net`, would `--address minio.example.net:443` work (assuming internally minio.example.net resolves correctly)

**Comment by harshavardhana** [comment] 2021-07-08 17:10
> But before I could also access the browser via the https port 433, now I apparently need a separate port...
> So is there now no way to allow access to the web console via same port as with the browser before?

There is no way to do that anymore @flixr we have moved on from that. 

> Also for some users I have a policy set so that they can only access their own bucket, but with these users now no bucket is visible in the console anymore...

what is the policy that you are talking about?  is it anonymous ?

**Comment by flixr** [comment] 2021-07-08 17:14
> Like assuming I have a wildcard cert for `*.example.net`, would `--address minio.example.net:443` work (assuming internally minio.example.net resolves correctly)

Yes, that works.

**Comment by flixr** [comment] 2021-07-08 17:19
> There is no way to do that anymore @flixr we have moved on from that.

Hm... thats a bummer... wondering how I can now give access to the console for our "outside" users...
This should have been clearly stated in the release notes, would be great if you can update them so others don't update pre-maturely and run into the same problem...

> what is the policy that you are talking about? is it anonymous ?

No, just a policy assigned to a group allowing access to a bucket with the same name as the user, and the users added to that group:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}/*"
            ]
        }
    ]
}
```

**Comment by harshavardhana** [comment] 2021-07-08 17:25
> Hm... thats a bummer... wondering how I can now give access to the console for our "outside" users...
> This should have been clearly stated in the release notes, would be great if you can update them so others don't update pre-maturely and run into the same problem...

If you don't want this feature you shouldn't really update and update in the future when you have figured out all the necessary details - we make releases every week as cadence. We do not expect you to keep upgrading willy nilly.  If you have a production requirement that is please test locally first that all the things that you expect work properly in a dev/stage environment. 

If they don't work ask questions - upgrading production and then figuring this out is really naive. 

> No, just a policy assigned to a group allowing access to a bucket with the same name as the user, and the users added to that group:

Hmm, this should work fine not sure what could be a problem here, will check and get back.

**Comment by ravindk89** [comment] 2021-07-08 17:26
@flixr https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#minio-server-console-address you can set a static console port if you want to - its up to you to make sure that port does not conflict with any other port on the host.

**Comment by flixr** [comment] 2021-07-08 17:32
@harshavardhana I understand... I just tested the api access before and from the release notes just didn't expect that the console works so differently. So yes, my bad... still, a bit more hints about this in the release notes would have helped a lot.
In any case the web ui access is not crucial for us right now...

Regarding the policy: thanks for checking... let me know if I can provide more details.

@ravindk89 thanks, yes... I did that.

**Comment by harshavardhana** [comment] 2021-07-08 17:44
I was able to reproduce the problem seems like the issue is because of `dynamic` variables @flixr - and console UI is trying to interpret this policy JSON incorrectly.

**Comment by harshavardhana** [comment] 2021-07-08 17:51
Moved the issue to #12651 for better context closing this as the original issue was TLS related here.

**Closed as completed by harshavardhana** 2021-07-08 17:51 UTC
Labels: community, priority: medium

**Comment by cs3gallery** [comment] 2021-07-23 21:03
I hate to open this issue back up but would like a little more clarification in regards to clustering. How should this be done on a clustered unit? Do we use the domain of each node or the domain that is set under MINIO_DOMAIN variable which is also being used on my reverse proxy? Thoughts?

**Comment by harshavardhana** [comment] 2021-07-23 22:28
> I hate to open this issue back up but would like a little more clarification in regards to clustering. How should this be done on a clustered unit? Do we use the domain of each node or the domain that is set under MINIO_DOMAIN variable which is also being used on my reverse proxy? Thoughts?

MINIO_DOMAIN is meant for Bucket DNS support it has nothing to do with authentication here. You might be confused with something else here..
