### ISSUE TITLE
Error while uploading: "cause=invalid argument"

### ISSUE THREAD

**Issue by gowithplanb** [minio/minio#4778] opened 2017-08-05 18:36 UTC
While uploading files from CB clients, sometimes the occurence of the following error can be seen in the logs:

Aug  5 13:12:31 scp01 minio[2169]: time="2017-08-05T13:12:31+02:00" level=error msg="Unable to create an object. /***PATH_TO_FILE_REDACTED***" cause="invalid argument" source="[object-handlers.go:545:objectAPIHandlers.PutObjectHandler()]" stack="fs-v1.go:557:fsObjects.PutObject <autogenerated>:402:(*fsObjects).PutObject object-handlers.go:531:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm"

## Expected Behavior
File should upload as expected without any errors. This was not observed two releases ago (pre Refactor HTTP releases).

## Current Behavior
Error in the logs indicating invalid argument as cause. The file however is created:
-rw------- 1 minio minio 428384 Aug  5 13:12 ***FILENAME_REDACTED***

## Possible Solution
A bugfix :)

## Steps to Reproduce (for bugs)
Unsure what causes this error. No information from client available unfortunately.

## Context
Use of CloudBerry client, in this case a MacOS client but I have seen this error caused by a Windows client too recently.

## Your Environment
* Version used (`minio version`): Version: 2017-08-05T00:00:53Z
* Operating System and version (`uname -a`): Debian Linux

**Comment by harshavardhana** [comment] 2017-08-05 21:33
Thanks for opening the bug @gowithplanb we will take a look.

**Comment by harshavardhana** [comment] 2017-08-08 18:45
@gowithplanb would you be interested in running a silo binary just to test fcntl locks? From the code path it looks like few things should have happened.

- A file descriptor if it was not valid should have been EBADFD. 
- A file descriptor was accessed with incorrect args in syscall.Flock() results in EINVAL.

Latter is what is happening but all the args are passed down correctly , the only reason i can think of is backend filesystem returning this for the time being.  What is the backend FS under use here @gowithplanb ?

**Comment by harshavardhana** [comment] 2017-08-11 02:48
Right now the only variable that has changed from our conversations is the backend version for MooseFS.

Since we haven't changed anything in this part of the code base since last many releases, even the one that you were using before. 

Error is being returned by is following code

```         
metaFile, err := fs.rwPool.Create(fsMetaPath)                                                                                                                       
```

A create cannot ever return EINVAL unless some weird conditions happened, let me explain below. There are two reasons this can happen

- fcntl flags are wrong
- the fd() became invalid, ie someone closed it before fcntl was attempted. 

In second case i see EBADFD from my local tests - but i have tried many variants the only way i see is
fcntl generating EINVAL is through if wrong flags were set but the code path is not setting any wrong flags at all. 

Now to proceed further lets do this by using `strace`  , please run this command

```
mkfifo /tmp/catcher; cat /tmp/catcher | gzip -9c > /tmp/strace.txt.gz & strace -fvttTyy -s 256 -o /tmp/catcher minio server <export>
```

Or attach to an existing process

```
mkfifo /tmp/catcher; cat /tmp/catcher | gzip -9c > /tmp/strace.txt.gz & strace -fvttTyy -s 256 -o /tmp/catcher -p <minio_pid>
```

Now you can perform the CBB backup and once you have reproduced the errors in the Minio logs. Stop the strace and please attach the captured **/tmp/strace.txt.gz** here.

**Comment by harshavardhana** [comment] 2017-08-15 00:28
@gowithplanb were you able to collect strace outputs that we requested?

**Comment by ebozduman** [comment] 2017-08-25 03:07
@gowithplanb : the issue is decided to be closed temporarily as `won't fix` for the time being. 
If you can collect the strace outputs we've requested and provide it to us, we can re-open it.

**Closed as completed by ebozduman** 2017-08-25 03:07 UTC
Labels: out of scope, priority: high

**Comment by harshavardhana** [comment] 2017-08-28 05:54
We are working with @gowithplanb and MooseFS team tracking issue with MooseFS upstream - [***redacted link***]

**Comment by gowithplanb** [comment] 2017-08-30 18:40
This issue was not caused by the Minio deamon but by a race condition in the underlying MooseFS filesystem. A beta version of MooseFS client 3.0.98-1 with a fix confirmed the issue is solved now. Thanks to the MooseFS team for digging into this critical bug very fast and @harshavardhana for helping debug Minio to find the cause of the issue we actually had in the first place with the CB client.
