### ISSUE TITLE
Mirroring a cluster to a single instance doesn't work

### ISSUE THREAD

**Issue by davidgeorgealex** [minio/minio#4991] opened 2017-09-28 07:24 UTC
I have a Minio cluster that contains 3 instances, each with 2 disks (so 6 disks in total) and a Minio instance in single mode. I want to be able to mirror the files uploaded in the cluster to the Minio in single mode. For this I run `mc mirror` from one instance from the cluster to the Minio in single mode mode.

## Expected Behavior
The files uploaded in the cluster, from any instance, should be mirrored to the Minio in single mode.

## Current Behavior
Only the files uploaded to the instance that was using in the `mc mirror` command goes to the Minio in single mode.

## Steps to Reproduce (for bugs)
1. Run the docker-compose file uploaded (uploaded in txt, because .yml is not permitted - change the suffix before running) that contains the Minio cluster and Minio in single mode setup
[docker-compose.txt](https://github.com/minio/minio/files/1339833/docker-compose.txt)
2. Check if the instances are accessible from the browser (localhost:9001-9004)
3. Create two buckets in the cluster (bb1 and bb2)
4. docker run --network=<<networkNameUsedByTheInitialInstances>> -it --entrypoint=/bin/sh minio/mc:RELEASE.2017-06-15T03-38-43Z
5. mc config host add source http://minio1:9000 minio minio123
6. mc config host add target http://minioSingle:9000 minio minio123
7. mc mirror -w --force --remove source target
8. Upload a file using http://localhost:9002/minio/bb1/ and one using http://localhost:9001/minio/bb1/
9. You can see that only the file uploaded from the :9001 will be visible (:9001 is the instance that was provided in the mirror command), even if you can see both files in the cluster.

## Context
I want to mirror a minio cluster to a single instance without carrieng from which instance in the cluster the file gets uploaded.

## Your Environment

* Version used (`minio version`): the versions are in the docker-compose file and in the mc run command
* Environment name and version (e.g. nginx 1.9.1): Ubuntu 16.04.2 LTS

**Comment by davidgeorgealex** [comment] 2017-09-28 07:31
The issue is present with the edge version as well (use for both minio and mc)

**Comment by harshavardhana** [comment] 2017-09-28 07:44
Just tested a local distributed instance,  mc cp to a different instance seems to be working fine. @davidgeorgealex . Checking through browser uploads.

**Comment by harshavardhana** [comment] 2017-09-28 07:45
Browser uploads seems to be working as well. NOTE i am running a local instance distributed setup not in docker, will try to replicate docker now.

**Comment by harshavardhana** [comment] 2017-09-28 08:34
Reproduced it using docker compose, investigating further..

**Comment by harshavardhana** [comment] 2017-10-02 07:38
@davidgeorgealex sorry for the delay, will send a fix for this - this week.  Thanks for reaching out to me to slack.

**Comment by davidgeorgealex** [comment] 2017-10-02 07:45
@harshavardhana No problem. Have a great day!

**Comment by harshavardhana** [comment] 2017-10-05 09:25
@davidgeorgealex so i have a work-around solution for the time being, while we fix this problem on our end. while i traced back the history on this issue, the bug has occurred and pretty much affects some of our releases since April of this year. 

```de204a0a52e6b13fec2d25b73102239891e6de35``` there were some fixes to mitigate this problem, but looks like its not fixed yet.

Work-around is here for you for the time being. 

```yml
version: '2'

services:
  minio1:
    container_name: minio1
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
    - minio11:/export1
    - minio12:/export2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address "minio1:9000" http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2 http://minio3/export1 http://minio3/export2
  minio2:
    container_name: minio2
    image: minio/minio
    ports:
      - "9002:9000"
    volumes:
    - minio21:/export1
    - minio22:/export2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address "minio2:9000" http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2 http://minio3/export1 http://minio3/export2
  minio3:
    container_name: minio3
    image: minio/minio
    ports:
      - "9003:9000"
    volumes:
    - minio31:/export1
    - minio32:/export2
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address "minio3:9000" http://minio1/export1 http://minio1/export2 http://minio2/export1 http://minio2/export2 http://minio3/export1 http://minio3/export2
  minioSingle:
      container_name: minioSingle
      image: minio/minio
      ports:
        - "9004:9000"
      volumes:
      - minioS:/export
      environment:
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio123
      command: server /export

volumes:
  minio11:
  minio12:
  minio21:
  minio22:
  minio31:
  minio32:
  minioS:
```

**Comment by harshavardhana** [comment] 2017-10-05 09:26
Notice `--address` is specified explicitly which is the work-around right now @davidgeorgealex  - let me know if it works for you.

**Comment by davidgeorgealex** [comment] 2017-10-05 12:00
Hi @harshavardhana,
I can confirm that the work-around is working like a charm!

Thanks,
George

**Comment by davidgeorgealex** [comment] 2017-10-05 13:41
@harshavardhana Using this brings another problem:(. The images that I'm using contains also mc. Since the image can be used on any container, I use `mc config host add local http://localhost:9000 ...` to be independent from the container name/ip. Providing `--address` will make the `http://localhost:9000` to not work anymore. There is another alternative to specify `I want the mc to point to this machine with 9000 as port`. Tried with 127.0.0.1 as well.

**Comment by harshavardhana** [comment] 2017-10-05 15:49
Not yet @davidgeorgealex .you need to add another haproxy config in front. Haproxy would talk to any node and it would work fine..

**Comment by davidgeorgealex** [comment] 2017-10-06 05:20
@harshavardhana Since I use `alpine` as OS, I can run `hostname -i` to get the IP address and then use this in `mc config host add` which works even if localhost/127.0.0.1 doesn't. And since I'm running using docker containers, this should be independent of the infrastructure where is deployed.

**Comment by harshavardhana** [comment] 2017-10-06 05:27
Well we already have a fix. So anything you do will be temporary.

**Comment by davidgeorgealex** [comment] 2017-10-06 05:28
Happy to hear that.. thanks for the effort!

**Closed as completed** 2017-10-09 03:23 UTC
Labels: fixed, priority: high, triage
