### ISSUE TITLE
Investigate the effect of new host for Google Storage APIs on Minio

### ISSUE THREAD

**Issue by challarao** [minio/minio#7677] opened 2019-05-21 06:22 UTC
Communication from Google:

> Hello Google Cloud Storage Customer,
> We are writing to let you know that starting June 20, 2019, Cloud Storage will allow JSON API requests to be sent to storage.googleapis.com in addition to www.googleapis.com (the current endpoint).
> What do I need to know?
> On June 20, 2019, we will begin updating the Cloud Client Libraries and gsutil to use the new endpoint; storage.googleapis.com. After the update, your JSON API requests will start using the new endpoint.
> What do I need to do?
> **If your production or test code doesn't check for endpoint-specific details, no action is required on your part.**
> If your production or test code checks for endpoint-specific details, you will need to modify them before June 20, 2019 as follows:
> •	If your code checks that the ‘baseUrl’ or ‘rootUrl’ fields in the JSON API Discovery document point to www.googleapis.com, you will need to modify those checks to allow either storage.googleapis.com or www.googleapis.com. Note that the oauth2 scopes fields in the Discovery document will not change and will continue to point to www.googleapis.com. 
> •	If your code checks that the ‘selfLink’ field in bucket or object metadata points to www.googleapis.com, you will need to modify that check to allow either storage.googleapis.com or www.googleapis.com. 
> •	If you access Cloud Storage through a firewall, you will need to ensure that requests to storage.googleapis.com are allowed by your firewall rules. 
> 

(emphasis mine)

**What I want to know:**

Does it break the existing Minio deployments that use the GCS gateway in any way?

**If yes:**

Is there a work around?

**If no:**

What is minio's position on this?

**Comment by nitisht** [comment] 2019-05-21 06:24
Thanks for reporting @challarao we'll take a look

**Comment by sinhaashish** [comment] 2019-10-18 07:53
@challarao  MinIo uses `cloud.google.com/go v0.37.2` Cloud Client library so there is no effect to MinIo gcs until we update the client library. As far as `oauth2` is concerned  i tested the `AssumeRoleWithWebIdentity` using Google and it is working as inteded. [ Refer](https://github.com/minio/minio/blob/master/docs/sts/web-identity.md) . 
Moreover  the docs says:
>Note that the oauth2 scopes fields in the Discovery document will not change and will continue to point to www.googleapis.com.

so there no change needed for `oath2`.
We can close this issue.

**Comment by harshavardhana** [comment] 2019-10-22 18:11
Closing this working as intended

**Closed as completed by harshavardhana** 2019-10-22 18:11 UTC
Labels: working as intended, community, priority: medium
