### ISSUE TITLE
[notify] mysql: user changing `format` field after first time initialization shows an error (possibly for postgresql and other?)

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4253] opened 2017-05-04 18:13 UTC
## Expected Behavior
The user can change the format after choosing it the first time.

## Current Behavior
The user cannot change format after choosing it the first time. For example, if he selects "access" and then he decides to switch to "namespace" later, he will get the following error:

```
FATA[0001] Initializing object layer failed              cause=Unable to initialize event notification. MySQL: create UPSERT prepared statement failed with: Error 1054: Unknown column 'key_name' in 'field list' source=[server-main.go:276:serverMain()]
```

## Possible Solution
It is better to keep notification data safe and create a separate table for each format 

## Steps to Reproduce (for bugs)
1. Start from fresh mysql database
2. Enable mysql notify in config.json, set format to 'access'
3. Start Minio
4. Stop Minio
5. Change format to 'namespace' in config.json
6. Start minio again

## Context
Testing for release.

## Your Environment
All

**Comment by donatello** [comment] 2017-05-04 21:11
This is an expected behaviour.

The way Minio writes data to the db (mysql/postgres/redis/elasticsearch) is different in namespace and access formats. Once it starts writing data in a particular format, if the format is changed, Minio refuses to start as the table format does not match what is expected. This way we avoid any kind of corruption in the databases.

If the user wants to switch formats they need to either provide a different table name (one which does not exist is ok), or they need to delete the existing table.

**Comment by harshavardhana** [comment] 2017-05-04 21:59
Closing as working as intended.

**Closed as completed by harshavardhana** 2017-05-04 21:59 UTC
Labels: working as intended, priority: medium

**Comment by LinQing2017** [comment] 2020-02-14 09:41
When I use an older version of the image, I can use the MC command to configure MySQL notifications.
However, when I set  **format = access**, the following error occurred

**mc: <ERROR> Cannot set 'notify_mysql:test table=events format=namespace dsn_string=root:Ruijie_123@tcp(172.24.33.77:3306)/minio_event' to server. Error 1071: Specified key was too long; max key length is 3072 bytes.**

I think it's because the server exceeded the MySQL limit when creatingtables!!

Please tell me how to solve this problem!!!
