### ISSUE TITLE
XL/format: Handle if JBOD inconsistent returns failure

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2181] opened 2016-07-11 23:19 UTC
Requires inspecting objects to know the disk position and re-populate the UUID

**Comment by harshavardhana** [comment] 2016-07-11 23:21
Same case should be handled for a situation where some disks are offline/unavailable but we have quorum.

**Comment by GarimaKapoor** [comment] 2016-07-19 02:50
Duplicate of #2182

**Closed as completed by GarimaKapoor** 2016-07-19 02:50 UTC
