### ISSUE TITLE
XL: Functional load test failure.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1782] opened 2016-05-28 07:59 UTC
**TestGetObjectClosedTwice** and **TestFPutObject** from the exec-concurrent load tests are failing on the rewrite-xl branch.

**Comment by harshavardhana** [comment] 2016-05-30 02:16
This is fixed.. there is a problem in how the locking is handled. The issue is between GetObject and RemoveObject()

**Comment by GarimaKapoor** [comment] 2016-06-02 16:53
If the issue is fixed we should close it! If the problem is somewhere else we should open the appropriate bug!

**Closed as completed** 2016-06-02 17:05 UTC
