### ISSUE TITLE
[distribute] reconnection process to a server that comes back up is unreliable

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#3236] opened 2016-11-10 15:21 UTC
Steps that produced this problem:
1. 3:3 DXL setup
2. restart 3, 6
3. `mc mb` of any number of buckets did not create volumes on 3 and 6

This issue is not reproducible. But the code review needs to be done to know under what situation this can happen.

**Comment by harshavardhana** [comment] 2016-11-10 15:46
In-fact reconnect never happened @krishnasrinivas it required one more call for the status to be cleared up.

**Comment by harshavardhana** [comment] 2016-11-11 15:44
Can we test this with latest master?

**Comment by donatello** [comment] 2016-11-11 19:23
Unable to reproduce on latest master.

_But the possible cause you were seeing is that after restart, before the server is initialized and ready, you may have been trying to create the bucket from a server that is up._

So in my test script - https://gist.github.com/donatello/4ec6e12001b192707fffe11f2da71173 - I am waiting for server to be initialized by doing `mc cat` and then attempting to create buckets. Once the test is complete, you can verify that volumes are created on all disks with a shell command like:

```
# # Run in parent of all minio disks (called minio{1..8} here)
# for i in $(seq 80); do find minio* | grep bucket-number-${i} | wc -l ; done  | wc -l
```

In this setup, I could not reproduce this issue (but as you say @krishnasrinivas it may be difficult to reproduce).

**Comment by harshavardhana** [comment] 2016-11-11 20:01
> Unable to reproduce on latest master.
> 
> But the possible cause you were seeing is that after restart, before the server is initialized and ready, you may have been trying to create the bucket from a server that is up.
> 
> So in my test script - https://gist.github.com/donatello/4ec6e12001b192707fffe11f2da71173 - I am waiting for server to be initialized by doing mc cat and then attempting to create buckets. Once the test is complete, you can verify that volumes are created on all disks with a shell command like:
> 
> # # Run in parent of all minio disks (called minio{1..8} here)
> 
> # for i in $(seq 80); do find minio\* | grep bucket-number-${i} | wc -l ; done  | wc -l
> 
> In this setup, I could not reproduce this issue (but as you say @krishnasrinivas it may be difficult to reproduce).

Closing this will re-open when we end up reproducing this issue.

**Closed as completed by harshavardhana** 2016-11-11 20:01 UTC
