### ISSUE TITLE
starting minio server with new export directory gives old secret key and access key

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1560] opened 2016-05-09 12:39 UTC
Steps to reproduce
1. run `minio server /d0`
2. stop the server
3. run `minio server /d1`
4. shows previously used access/secret keys

Is it expected?

**Comment by harshavardhana** [comment] 2016-05-09 18:43
> Steps to reproduce
> 1. run minio server /d0
> 2. stop the server
> 3. run minio server /d1
> 4. shows previously used access/secret keys
> 
> Is it expected?

This is expected - you have to provide a new "-C" "--config-dir" option.

**Comment by harshavardhana** [comment] 2016-05-10 01:55
Changing access keys just for disk changes is not a good idea and unwarranted/unexpected, since the keys are copied over to the clients, tools, applications and browsers remember them. 

The purpose is to keep it simple, to be able to migrate to new set of cluster carrying same credentials etc.  Even changing keys directly through config, setting env variables, setting them to a preferred username and password from browser - are all allowed because of this simple flat nature. 

Closing this as it's not a bug.

**Closed as completed by harshavardhana** 2016-05-10 01:55 UTC
Labels: priority: low
