### ISSUE TITLE
minio 4K object performance issue with QLC NVMe disk

### ISSUE THREAD

**Issue by gwnet** [minio/minio#9704] opened 2020-05-26 02:43 UTC
## Expected Behavior

Hello here is my test result. only one drive. the performance IOPS of small write and reads are not so good. what is the bottleneck?
[root@localhost s3-benchmark]# ./s3-benchmark.ubuntu -a minioadmin -b jeff-s3-benchmark -s minioadmin -u http://127.0.0.1:9000 -t 40 -d 120 -z 4k 
Wasabi benchmark program v2.0
Parameters: url=http://127.0.0.1:9000, bucket=jeff-s3-benchmark, region=us-east-1, duration=120, threads=40, loops=1, size=4k
2020/05/26 03:22:14 WARNING: createBucket jeff-s3-benchmark error, ignoring BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
	status code: 409, request id: 16125BC844751157, host id: 
Loop 1: PUT time 120.0 secs, objects = 356939, speed = 11.6MB/sec, 2974.2 operations/sec. Slowdowns = 0
Loop 1: GET time 120.0 secs, objects = 586197, speed = 19.1MB/sec, 4884.7 operations/sec. Slowdowns = 0
Loop 1: DELETE time 60.6 secs, 5889.6 deletes/sec. Slowdowns = 0
[root@localhost s3-benchmark]# 

## Current Behavior

4K small objects load test, HW cpu, storage is idle a lot. it should have better score.

## Possible Solution

instruct us how to check the bottleneck at minio side?

## Steps to Reproduce (for bugs)

1. just run 4K S3 benchmark load test
2. run fio on the disk, then you will see the different and gap
3.
4.

## Your Environment

* Version used (`minio version`):
wget https://dl.min.io/server/minio/release/linux-amd64/minio
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
intel skylake server
* Operating System and version (`uname -a`):
[root@localhost s3-benchmark]# uname -a
CentOS 7, other OS apply too
Linux localhost.localdomain 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Link to your project:

**Comment by harshavardhana** [comment] 2020-05-26 03:38
@gwnet the issue is super incomplete, while you have used the template the entire issue is left empty with no setup details no minio version being used?  How are we supposed to help you?

**Comment by gwnet** [comment] 2020-05-26 03:58
@harshavardhana let me know if this updated version make sense? maybe you can try run the 4K load from your side quickly too. you will see my suffer.

**Comment by harshavardhana** [comment] 2020-05-26 04:06
> @harshavardhana let me know if this updated version make sense? maybe you can try run the 4K load from your side quickly too. you will see my suffer.

what is the setup are you using FS mode, Erasure code, distributed ? how many clients?

**Comment by gwnet** [comment] 2020-05-26 05:33
@harshavardhana I use xfs file system, no EC, one machine one nvme QLC disk. one test client, I just see s3 benchmarks tool. use 40 threads.

==below is perf output of bad performance, for large object 10M, I did not see all minio threads block on something together. 
I will share my perf log later

**Comment by gwnet** [comment] 2020-05-26 05:37
Samples: 1M of event 'cycles:ppp', Event count (approx.): 135167104096681977                                                                                                               
  Children      Self  Command  Shared Object      Symbol                                                                                                                                  ◆
-   74.45%     0.00%  minio    minio              [.] 0xffffffffffc5f9e1                                                                                                                  ▒
   + 0x5f9e1                                                                                                                                                                              ▒
+   65.95%     0.00%  minio    minio              [.] 0xfffffffffff08705                                                                                                                  ▒
+   65.95%     0.00%  minio    minio              [.] 0xfffffffffff0ce64                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0xfffffffffff09914                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x000000000000b90b                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000db4773                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000c52a4c                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000db4b73                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000c4e403                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000db52b3                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000c52da3                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000dad2b3                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000b8aea1                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000db4e43                                                                                                                  ▒
+   65.81%     0.00%  minio    minio              [.] 0x0000000000c504d5                                                                                                                  ▒
+   65.68%     0.00%  minio    minio              [.] 0x00000000009eac3f                                                                                                                  ▒
+   65.68%     0.00%  minio    minio              [.] 0x0000000000db4db3                                                                                                                  ▒
+   65.68%     0.00%  minio    minio              [.] 0x0000000000c4fa95                                                                                                                  ▒
+   65.68%     0.00%  minio    minio              [.] 0x0000000000db4c93                                                                                                                  ▒
+   65.68%     0.00%  minio    minio              [.] 0x0000000000c4ed52                                                                                                                  ▒
+   65.68%     0.00%  minio    minio              [.] 0x0000000000db4d23                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000c4f14c                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000db4c03                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000c4ea88                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000db0813                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000be9451                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000db4ae3                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000c4dfb3                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000db4a4c                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000c4dd1f                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000db4ed3                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000c50914                                                                                                                  ▒
+   65.58%     0.00%  minio    minio              [.] 0x0000000000db4f63                                                                                                                  ▒
+   65.52%     0.00%  minio    minio              [.] 0x0000000000c510d1                                                                                                                  ▒
+   65.52%     0.00%  minio    minio              [.] 0x0000000000db50fc

**Comment by harshavardhana** [comment] 2020-05-26 05:39
> @harshavardhana I use xfs file system, no EC, one machine one nvme QLC disk. one test client, I just see s3 benchmarks tool. use 40 threads.
> 
> ==below is perf output of bad performance, for large object 10M, I did not see all minio threads block on something together.
> I will share my perf log later

can you run `fio` on the same drive 4K files with 40 threads? with randomIO profile?

**Comment by gwnet** [comment] 2020-05-26 05:48
hello here is my fio 4K test result, it can be very high, more than 10 times than minio BW. and HW CPU is a lot of idle.
===fio result
[root@localhost mongoose]# fio -filename=/dev/nvme3n1 -direct=1 -iodepth 256 -thread -rw=write -ioengine=libaio -bs=4k -size=7000G -numjobs=20 -runtime=60 -group_reporting -name=mytest
mytest: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=256
...
fio-3.19
Starting 20 threads
Jobs: 20 (f=20): [W(20)][0.0%][w=318MiB/s][w=81.5k IOPS][eta 10d:22h:31m:00s]
mytest: (groupid=0, jobs=20): err= 0: pid=160457: Tue May 26 06:31:57 2020
  write: IOPS=81.7k, BW=319MiB/s (335MB/s)(18.7GiB/60056msec)
    slat (usec): min=2, max=1125, avg= 9.16, stdev= 2.74
    clat (usec): min=16, max=403188, avg=62655.46, stdev=36108.80
     lat (usec): min=26, max=403197, avg=62664.75, stdev=36108.68
    clat percentiles (msec):
     |  1.00th=[   21],  5.00th=[   32], 10.00th=[   36], 20.00th=[   43],
     | 30.00th=[   46], 40.00th=[   49], 50.00th=[   53], 60.00th=[   56],
     | 70.00th=[   61], 80.00th=[   69], 90.00th=[  116], 95.00th=[  142],
     | 99.00th=[  194], 99.50th=[  222], 99.90th=[  326], 99.95th=[  342],
     | 99.99th=[  372]
   bw (  KiB/s): min=87982, max=595138, per=100.00%, avg=327208.66, stdev=5824.17, samples=2380
   iops        : min=21987, max=148782, avg=81794.76, stdev=1456.02, samples=2380
  lat (usec)   : 20=0.01%, 50=0.01%, 100=0.03%, 250=0.11%, 500=0.11%
  lat (usec)   : 750=0.08%, 1000=0.06%
  lat (msec)   : 2=0.17%, 4=0.17%, 10=0.19%, 20=0.07%, 50=43.09%
  lat (msec)   : 100=42.39%, 250=13.32%, 500=0.21%
  cpu          : usr=1.77%, sys=5.49%, ctx=3613943, majf=0, minf=29077
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=0,4906444,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
  WRITE: bw=319MiB/s (335MB/s), 319MiB/s-319MiB/s (335MB/s-335MB/s), io=18.7GiB (20.1GB), run=60056-60056msec

Disk stats (read/write):
  nvme3n1: ios=44/4905365, merge=0/0, ticks=12/307180480, in_queue=320890061, util=100.00%

**Comment by gwnet** [comment] 2020-05-26 05:55
===here is 4K minio test perf result, any thought? looks like not one system issue, just minio code issue?

+   19.56%     0.00%  minio    [kernel.kallsyms]  [k] __mutex_lock_slowpath                                                                                                               ▒
+   19.09%     0.00%  minio    minio              [.] 0xffffffffffc5db06                                                                                                                  ▒
+   18.72%     0.13%  minio    [kernel.kallsyms]  [k] tick_sched_timer                                                                                                                    ▒
+   18.52%     0.00%  minio    [kernel.kallsyms]  [k] tick_sched_handle                                                                                                                   ▒
+   18.46%     0.00%  minio    [kernel.kallsyms]  [k] update_process_times                                                                                                                ▒
+   17.36%     1.71%  minio    [kernel.kallsyms]  [k] scheduler_tick                                                                                                                      ▒
+   17.12%     0.07%  minio    [kernel.kallsyms]  [k] __schedule                                                                                                                          ▒
+   16.54%     0.00%  minio    minio              [.] 0xffffffffffc7ecca                                                                                                                  ▒
+   15.94%     0.00%  minio    minio              [.] 0x0000000000c42e8c                                                                                                                  ▒
+   15.34%     0.00%  minio    minio              [.] 0x0000000000c2ef91                                                                                                                  ▒
+   13.26%     0.00%  minio    minio              [.] 0xffffffffffc96321                                                                                                                  ▒
+   12.98%     0.00%  minio    [unknown]          [.] 0x294830244c8b4824                                                                                                                  ▒
+   12.90%     0.00%  minio    [kernel.kallsyms]  [k] sys_write                                                                                                                           ▒
+   12.79%     0.00%  minio    [kernel.kallsyms]  [k] vfs_write                                                                                                                           ▒
+   12.79%     0.00%  minio    [kernel.kallsyms]  [k] do_sync_write                                                                                                                       ▒
+   12.56%     0.00%  minio    minio              [.] 0xffffffffffc9d9a7                                                                                                                  ▒
+   12.42%     0.00%  minio    minio              [.] 0x0000000000d214e7                                                                                                                  ▒
+   12.35%     0.00%  minio    [kernel.kallsyms]  [k] schedule                                                                                                                            ▒
+   12.15%     0.00%  minio    [kernel.kallsyms]  [k] xfs_file_aio_write                                                                                                                  ▒
+   11.93%     0.00%  minio    [kernel.kallsyms]  [k] generic_write_sync                                                                                                                  ▒
+   11.93%     0.07%  minio    [kernel.kallsyms]  [k] xfs_file_fsync                                                                                                                      ▒
+   10.75%     0.00%  minio    minio              [.] 0xffffffffffc5da7b                                                                                                                  ▒
+   10.70%     0.00%  minio    minio              [.] 0x0000000000c4295e                                                                                                                  ▒
+   10.37%     0.00%  minio    minio              [.] 0x0000000000c42e49                                                                                                                  ▒
+   10.37%     0.00%  minio    minio              [.] 0x0000000000c2dc7b                                                                                                                  ▒
+   10.37%     0.00%  minio    minio              [.] 0x0000000000cc4379                                                                                                                  ▒
+   10.37%     0.00%  minio    minio              [.] 0x0000000000cc47e4                                                                                                                  ▒
+   10.06%     0.00%  minio    minio              [.] 0xffffffffffc3723e                                                                                                                  ▒
+    9.46%     0.00%  minio    minio              [.] 0x0000000000cc41ed                                                                                                                  ▒
+    9.46%     0.00%  minio    minio              [.] 0x0000000000cc40b5                                                                                                                  ▒
+    9.41%     2.37%  minio    [kernel.kallsyms]  [k] perf_event_task_tick                                                                                                                ▒
+    9.36%     0.00%  minio    minio              [.] 0x0000000000c38b74                                                                                                                  ▒
+    9.28%     0.00%  minio    minio              [.] 0x0000000000c43136                                                                                                                  ▒
+    8.88%     0.00%  minio    minio              [.] 0xffffffffffc3757d                                                                                                                  ▒
+    8.74%     0.00%  minio    minio              [.] 0x000000000
           0x10510d1                                                                                                                                                                      ▒
           0x11b50fc                                                                                                                                                                      ▒
           0x10512fc                                                                                                                                                                      ▒
           0x11b5223                                                                                                                                                                      ▒
           0x1052966                                                                                                                                                                      ▒
           0x11b5193                                                                                                                                                                      ▒
           0x10526d2                                                                                                                                                                      ▒
           0x3607a2                                                                                                                                                                       ▒
           0x309914                                                                                                                                                                       ▒
           0x119acd0                                                                                                                                                                      ▒
           0x118d0f1                                                                                                                                                                      ▒
           0x118cfb8                                                                                                                                                                      ▒
           0x11c0293                                                                                                                                                                      ▒
           0x10aae19                                                                                                                                                                      ▒
           0x11c2fd7                                                                                                                                                                      ▒
         + 0x1041c9b                                                                                                                                                                      ▒
+    6.52%     0.00%  minio    [kernel.kallsyms]  [k] sys_newfstatat                                                                                                                      ▒
+    6.52%     0.00%  minio    [kernel.kallsyms]  [k] SYSC_newfstatat                                                                                                                     ▒
+    6.46%     0.00%  minio    [kernel.kallsyms]  [k] filename_lookup                                                                                                                     ▒
+    6.46%     0.00%  minio    [kernel.kallsyms]  [k] path_lookupat                                                                                                                       ▒
+    6.38%     0.00%  minio    [kernel.kallsyms]  [k] vfs_fstatat                                                                                                                         ▒
+    6.35%     0.20%  minio    [kernel.kallsyms]  [k] _xfs_log_force_lsn                                                                                                                  ▒
+    6.32%     0.07%  minio    [kernel.kallsyms]  [k] user_path_at                                                                                                                        ▒
+    6.25%     0.00%  minio    [kernel.kallsyms]  [k] user_path_at_empty                                                                                                                  ▒
+    6.13%     0.00%  minio    minio              [.] 0xffffffffffc9e4f0                                                                                                                  ▒
+    6.13%     0.00%  minio    minio              [.] 0xffffffffffca1c10                                                                                                                  ▒
+    6.13%     0.00%  minio    [kernel.kallsyms]  [k] sys_mkdirat                                                                                                                         ▒
+    5.83%     0.00%  minio    minio              [.] 0xfffffffffff60744                                                                                                                  ▒
+    5.83%     0.00%  minio    minio              [.] 0xfffffffffff604b3                                                                                                                  ▒
+    5.70%     0.00%  minio    minio              [.] 0xfffffffffff66384                                                                                                                  ▒
+    5.62%     0.00%  minio    [kernel.kallsyms]  [k] lookup_slow                                                                                                                         ▒
+    5.49%     0.00%  minio    minio              [.] 0xffffffffffc0c431                                                                                                                  ▒
+    5.49%     0.00%  minio    minio              [.] 0xffffffffffc0cda9                                                                                                                  ▒
+    5.39%     0.00%  minio    [kernel.kallsyms]  [k] filemap_write_and_wait_range                                                                                                        ▒
+    5.33%     0.46%  minio    [kernel.kallsyms]  [k] perf_pmu_enable                                                                                                                     ▒
+    5.29%     0.00%  minio    minio              [.] 0xffffffffffc5d3c3                                                                                                                  ▒
Tip: Show user configuration overrides: perf config --user --list

**Comment by harshavardhana** [comment] 2020-05-26 05:57
> fio -filename=/dev/nvme3n1 -direct=1 -iodepth 256 -thread -rw=write -ioengine=libaio -bs=4k -size=7000G -numjobs=20 -runtime=60 -group_reporting -name=mytest

This is not correct @gwnet this is writing to same file you need to write to many files simultaneously. 

Also you should use randwrite not sequential write,  performance seems terrible for NVMe even with sequential write.

**Comment by gwnet** [comment] 2020-05-26 07:42
@harshavardhana I am writting the nvme device as block device. I know what you meaning. I will test the random write at block level. it is the same write many files. wait me

**Comment by gwnet** [comment] 2020-05-26 07:45
for randwrite, the BW is even higher, this is strange to me too, maybe it is QLC. 
so minio S3 benchmark tool will create random IO? for each file, you will be seq IO, right?
[root@localhost bin]# fio -filename=/dev/nvme3n1 -direct=1 -iodepth 256 -thread -rw=randwrite -ioengine=libaio -bs=4k -size=7000G -numjobs=20 -runtime=60 -group_reporting -name=mytest
mytest: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=256
...
fio-3.19
Starting 20 threads
Jobs: 20 (f=20): [w(20)][100.0%][w=966MiB/s][w=247k IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=20): err= 0: pid=170092: Tue May 26 08:29:40 2020
  write: IOPS=265k, BW=1034MiB/s (1084MB/s)(60.6GiB/60056msec)
    slat (usec): min=2, max=5848, avg=10.27, stdev=11.79
    clat (usec): min=17, max=72746, avg=19262.26, stdev=4043.00
     lat (usec): min=27, max=72754, avg=19272.69, stdev=4042.82
    clat percentiles (usec):
     |  1.00th=[14353],  5.00th=[15008], 10.00th=[15270], 20.00th=[15926],
     | 30.00th=[16712], 40.00th=[17695], 50.00th=[18482], 60.00th=[19792],
     | 70.00th=[20841], 80.00th=[21890], 90.00th=[23987], 95.00th=[26084],
     | 99.00th=[35914], 99.50th=[38011], 99.90th=[40109], 99.95th=[42730],
     | 99.99th=[47973]
   bw (  MiB/s): min=  729, max= 1216, per=100.00%, avg=1035.48, stdev= 5.42, samples=2380
   iops        : min=186735, max=311398, avg=265075.19, stdev=1386.74, samples=2380
  lat (usec)   : 20=0.01%, 50=0.01%, 100=0.01%, 250=0.02%, 500=0.02%
  lat (usec)   : 750=0.02%, 1000=0.03%
  lat (msec)   : 2=0.10%, 4=0.07%, 10=0.10%, 20=62.34%, 50=37.27%
  lat (msec)   : 100=0.01%
  cpu          : usr=7.73%, sys=22.62%, ctx=7519765, majf=0, minf=9699782
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=0.1%, 32=0.1%, >=64=100.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.1%
     issued rwts: total=0,15897026,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=256

Run status group 0 (all jobs):
  WRITE: bw=1034MiB/s (1084MB/s), 1034MiB/s-1034MiB/s (1084MB/s-1084MB/s), io=60.6GiB (65.1GB), run=60056-60056msec

Disk stats (read/write):
  nvme3n1: ios=0/15837768, merge=0/0, ticks=0/304638204, in_queue=330824815, util=100.00%

**Comment by klauspost** [comment] 2020-05-26 13:48
Hi! I am closing this as there is no issue as such, but just a matter of performance optimization.

Feel free to drop by slack https://slack.min.io/ - maybe people from the community can share experiences with you.

If you need assistance for a detailed system review we offer a subscription service: https://min.io/pricing or write `hello@minio.io`.

**Closed as completed by klauspost** 2020-05-26 13:48 UTC
Labels: working as intended, community

**Comment by gwnet** [comment] 2020-05-27 11:57
great, I already logon the slack. and send message, can anyone help me? for small object performance on minio?
