### ISSUE TITLE
Latest broke volume running on docker

### ISSUE THREAD

**Issue by rmsj** [minio/minio#9555] opened 2020-05-08 10:07 UTC
I had this working until yesterday when I had to rebuild my services and I've noticed there was a new version - running on dev environment, with the latest version.

## Expected Behavior
minio should start as usual with mounted volumes.

## Current Behavior
Whenever I try to use volumes, which I was before the update I got an error:

**_minio_1          | ERROR Unable to initialize backend: Unable to write to the backend
minio_1          |       > Please ensure MinIO binary has write permissions for the backend
minio_1          |       HINT:
minio_1          |         Use 'sudo chown root /export && sudo chmod u+rxw /export' to provide sufficient permissions._**

## Possible Solution
No idea.
Since it's a dev environment, I just removed the volumes and can keep going for now.

## Steps to Reproduce (for bugs)

docker compose:

**minio:
    image: minio/minio:latest
    ports:
      - 9010:9010
    #volumes:
      #- ./docker/volumes/minio/export:/export
    command: server --address ":9010" /export
    environment:
      MINIO_ACCESS_KEY: somekey
      MINIO_SECRET_KEY: secret123
    networks:
      - some_network**

## Your Environment

* Version used (`minio version`): latest docker image
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): running as a docker service. Host is mac, Catalina.
* Link to your project:

**Comment by anthu** [comment] 2020-05-08 10:13
reported in #9549

**Comment by screencomuser** [comment] 2020-05-08 10:18
A fix is not forthcoming, since the released fix appears to be "Improved message when O_DIRECT is not supported"

How can we enable O_DIRECT on Docker for Mac so we can use Minio again? Apparently macOS doesn’t support a file mode called O_DIRECT, which leaves a lot of developers stuck at the 2020-05-01 version :-)

**Comment by anthu** [comment] 2020-05-08 10:21
I'm afraid to say you can't for the moment.
https://github.com/docker/desktop-feedback/issues/11

The only what I can suggest you right now is to use the MacOS binary directly

**Comment by anthu** [comment] 2020-05-08 10:22
or don't mount the host volume
or run a sidecar with rsync

I don't really know, if this will be reverted, see my comment in #9554 .

**Comment by screencomuser** [comment] 2020-05-08 10:23
😿 

I'll just pin the latest version that does work on development. Luckily we don't have our cloud running on macOS.

**Comment by anthu** [comment] 2020-05-08 10:26
What mounts are you using? we haven't upgraded the servers yet

**Comment by screencomuser** [comment] 2020-05-08 10:41
The latest version is working on Ubuntu 18.04 with a regular bind mount. It's only the development side on macOS that's giving us trouble.

We've decided to use the minio/minio:RELEASE.2020-05-01T22-19-14Z in our docker-compose.override.yml for development.

**Comment by harshavardhana** [comment] 2020-05-08 15:45
Closing this as duplicate of #9554

**Closed as completed by harshavardhana** 2020-05-08 15:45 UTC
Labels: community, triage
