### ISSUE TITLE
server: [gateway] Support for Backblaze B2

### ISSUE THREAD

**Issue by klausenbusk** [minio/minio#4072] opened 2017-04-08 02:30 UTC
Hello

I think a lot of user could find a S3 gateway for B2 very useful, as there is a lot of backups tools for S3 and B2 is very cheap (0,005$/GB).

Rclone Go package could be used for integrating with the API: https://godoc.org/github.com/ncw/rclone/b2 https://godoc.org/github.com/ncw/rclone/b2/api

**Comment by pascalandy** [comment] 2017-05-21 03:49
Absolute must for me :)

**Comment by ralph327** [comment] 2017-06-09 17:43
This is not being actively worked on, correct?

**Comment by harshavardhana** [comment] 2017-06-09 17:45
> This is not being actively worked on, correct?

@ralph327 it is not - it is under future milestone.

**Comment by ralph327** [comment] 2017-06-09 17:48
Okay. I'll try to tackle this in the coming weeks.

**Comment by harshavardhana** [comment] 2017-10-02 23:57
https://gist.github.com/harshavardhana/87c0f98c5e3c81ccc03f2ca4463af4b8 here is the document explaining B2 support and need some help in testing the support. 

Test binary is available https://data.minio.io:10000/minio-b2/linux-amd64/minio (only for Linux amd64)

Feel free to ask any questions you might have.

**Comment by harshavardhana** [comment] 2017-10-03 01:54
> Test binary is available https://data.minio.io:10000/minio-b2/linux-amd64/minio (only for Linux amd64)
> 
> Feel free to ask any questions you might have.

Re-uploaded a newer binary there was bug in previous binary. Thanks to @krisis for reproducing it. It should be fixed in the latest upload.

**Comment by HeavyHorst** [comment] 2017-10-11 09:57
I've downloaded the test binary and everything works fine.
VERSION:
  2017-10-03T07:18:00Z

After running the proxy for some days (2?) i see errors like this:
```
msg="Unable to list buckets." cause="b2_list_buckets: 401: expired_auth_token: Authorization token has expired"
```
and must restart the proxy to make it work again.

**Comment by harshavardhana** [comment] 2017-10-11 10:17
> I've downloaded the test binary and everything works fine.
> VERSION:
> 2017-10-03T07:18:00Z
> 
> After running the proxy for some days (2?) i see errors like this:
> 
> msg="Unable to list buckets." cause="b2_list_buckets: 401: expired_auth_token: Authorization token has expired"
> and must restart the proxy to make it work again.

From what it looks like the library that i am using should fetch the new token again transparently. Let me see how it can be done. Thanks for testing and letting us know @HeavyHorst

**Comment by HeavyHorst** [comment] 2017-10-11 11:32
@harshavardhana 
I'm using the same library (kurin/blazer not minio/blazer) in one of my projects.
I'm using the client from the b2 package and not the base package directly.

```go
import b2api "github.com/kurin/blazer/b2"
...
client, err := b2api.NewClient(context.Background(), accountIDOpt, appKeyOpt)
```

I have not seen any issues like that with this client (server is running for several months without issues).

**Comment by harshavardhana** [comment] 2017-10-11 16:34
Yes the problem is using lower level interface, which doesn't have a refresh mechanism.

**Comment by harshavardhana** [comment] 2017-10-11 19:06
@HeavyHorst updated the PR should be fixed now.. binaries are not updated yet though.

**Comment by HeavyHorst** [comment] 2017-10-12 07:24
Great, thanks!
I've build the binary myself and will try it asap.

**Closed as completed** 2017-10-13 10:56 UTC
Labels: fixed, priority: medium

**Comment by pascalandy** [comment] 2018-04-04 05:00
That sounds great. Thanks for the good work folks !!
