### ISSUE TITLE
mc command gives different disks available information

### ISSUE THREAD

**Issue by titansmc** [minio/minio#12308] opened 2021-05-17 14:06 UTC
when checking the disks status, it gives me different output each time

## Expected Behavior
be consistent, and disks not marked as online, be shown as offline. 

## Current Behavior
Asking the node2 gives me different results each time: 
```
[root@ops-object02 ~]#  mc admin info node2
●  ops-object01.domain.de:443
   Uptime: 7 minutes 
   Version: 2021-04-22T15:44:28Z
   Network: 2/2 OK 
   Drives: 95/95 OK 

●  ops-object02.domain.de:443
   Uptime: 7 minutes 
   Version: 2021-04-22T15:44:28Z
   Network: 2/2 OK 
   Drives: 95/95 OK 

6.0 TiB Used, 44 Buckets, 6,850,126 Objects
190 drives online, 0 drives offline
[root@ops-object02 ~]#  mc admin info node2
●  ops-object01.embl.de:443
   Uptime: 7 minutes 
   Version: 2021-04-22T15:44:28Z
   Network: 2/2 OK 
   Drives: 95/95 OK 

●  ops-object02.embl.de:443
   Uptime: 7 minutes 
   Version: 2021-04-22T15:44:28Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

6.0 TiB Used, 44 Buckets, 6,850,126 Objects
191 drives online, 0 drives offline
```
and asking the node 1 too, but different:
```
[root@ops-object01 ~]# mc admin info node1
●  ops-object02.domain.de:443
   Uptime: 11 minutes 
   Version: 2021-04-22T15:44:28Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

●  ops-object01.domain.de:443
   Uptime: 11 minutes 
   Version: 2021-04-22T15:44:28Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

6.0 TiB Used, 44 Buckets, 6,883,550 Objects
192 drives online, 0 drives offline
[root@ops-object01 ~]# mc admin info node1
●  ops-object02.domain.de:443
   Uptime: 12 minutes 
   Version: 2021-04-22T15:44:28Z
   Network: 2/2 OK 
   Drives: 95/95 OK 

●  ops-object01.domain.de:443
   Uptime: 12 minutes 
   Version: 2021-04-22T15:44:28Z
   Network: 2/2 OK 
   Drives: 95/95 OK 
```

This is constantly appearing int the logs:
```
ops-object01.domain.de  Time: 14:06:54 UTC 05/17/2021
ops-object01.domain.de  DeploymentID: 50f73ea1-7aa8-4b55-8b58-9776bac7048a
ops-object01.domain.de  Error: disk not found:  (*errors.errorString)
ops-object01.domain.de         2: cmd/erasure.go:180:cmd.getDisksInfo.func1()
ops-object01.domain.de         1: pkg/sync/errgroup/errgroup.go:122:errgroup.(*Group).Go.func1()
```

## Context
I am trying to find out which drives are failing

## Regression
probably yes

## Your Environment

* Version used (`minio --version`): RELEASE.2021-04-22T15-44-28Z
* Server setup and configuration: 2 nodes cluster with 96 drives each
* Operating System and version (`uname -a`): Linux  3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment] 2021-05-17 14:18
@titansmc If disks are flickering off/online it will be reflected on the stats. You are seeing the status as it is reflected on the server you are asking.

There is an n * m relation relation where n is the number of servers and m is the number of disks, since each server tracks the status of each local+remote disk. If a disk is unreachable or is marked offline because of an error on a server that is reflected when you ask that server.

I can't tell you what the problem is with your disk without a deeper investigation that is out of scope here.

**Closed as completed by klauspost** 2021-05-17 14:18 UTC
Labels: working as intended, community
