### ISSUE TITLE
Not possible to download a file when removing the content of one export dir

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2072] opened 2016-07-02 16:42 UTC
```
$ rm -rf /mnt/p8/fs1/* && minio server /mnt/p8/fs1/export{1..16}
$ mc mb myminio/bucket && mc cp /mnt/p8/5gb.bin myminio/bucket
$ rm -rf /mnt/p8/fs1/export12/*
$ mc ls myminio/bucket/5gb.bin
[2016-07-02 17:21:00 CET] 5.0GiB 5gb.bin
$ mc cat myminio/bucket/5gb.bin
mc: <ERROR> Unable to read from ‘myminio/bucket/5gb.bin’. Bucket ‘bucket’ does not exist.
```

5gb.bin can be listed but not downloaded.

Isn't minio supposed to deliver this file transparently when one disk fails? (1/16)

**Comment by krishnasrinivas** [comment] 2016-07-02 16:52
This should be a bug

**Comment by harshavardhana** [comment] 2016-07-03 01:46
To be fixed by July 4th.

**Comment by GarimaKapoor** [comment] 2016-07-07 05:30
Please update the new timeline.

**Comment by harshavardhana** [comment] 2016-07-07 06:18
> Please update the new timeline.

Should be done by July 7th

**Comment by harshavardhana** [comment] 2016-07-07 07:07
> Minio Cloud Storage member
> vadmeste commented 5 days ago
> $ rm -rf /mnt/p8/fs1/\* && minio server /mnt/p8/fs1/export{1..16}
> $ mc mb myminio/bucket && mc cp /mnt/p8/5gb.bin myminio/bucket
> $ rm -rf /mnt/p8/fs1/export12/*
> $ mc ls myminio/bucket/5gb.bin
> [2016-07-02 17:21:00 CET] 5.0GiB 5gb.bin
> $ mc cat myminio/bucket/5gb.bin
> mc: <ERROR> Unable to read from ‘myminio/bucket/5gb.bin’. Bucket ‘bucket’ does not exist.
> 5gb.bin can be listed but not downloaded.
> 
> Isn't minio supposed to deliver this file transparently when one disk fails? (1/16)

Not able to reproduce this with current 'master' , do you have the setup handy where i can take a look?

**Comment by krishnasrinivas** [comment] 2016-07-07 13:18
@vadmeste can you check again on master, because this is not reproducible. On which commit did you see the behavior, curious to know which commit fixed it.

**Comment by vadmeste** [comment] 2016-07-07 16:42
@krishnasrinivas @harshavardhana, with the last master, this happens _sometimes_, I did mc cat myminio/bucket/5gb.bin many times before I got this "mc: <ERROR> Unable to read from ‘myminio/bucket/5gb.bin’. Bucket ‘bucket’ does not exist."

**Comment by krishnasrinivas** [comment] 2016-07-07 16:48
In that case what is happening is:

```
// readXLMetadata - returns the object metadata `xl.json` content from                 
// one of the disks picked at random.                                                  
func (xl xlObjects) readXLMetadata(bucket, object string) (xlMeta xlMetaV1, err error)\
 {                                                                                     
        for _, disk := range xl.getLoadBalancedQuorumDisks() {                         
                if disk == nil {                                                       
                        continue                                                       
                }                                                                      
                xlMeta, err = readXLMeta(disk, bucket, object)                         
                if err != nil {                                                        
                        // For any reason disk is not available continue and read from\
 other disks.                                                                          
                        if err == errDiskNotFound || err == errFaultyDisk {            
                                continue                                               
                        }                                                               
                        return xlMetaV1{}, err                                         
                }                                                                      
                break                                                                  
        }                                                                              
        return xlMeta, nil                                                             
}
```

here, we `continue` only for errDiskNotFound and errFaultyDisk. But we get errVolumeNotFound
because `rm -rf /mnt/p8/fs1/export12/*` does not remove export directory, just the bucket directory.

**Comment by harshavardhana** [comment] 2016-07-07 19:19
> // readXLMetadata - returns the object metadata `xl.json` content from  
> // one of the disks picked at random.  
> func (xl xlObjects) readXLMetadata(bucket, object string) (xlMeta xlMetaV1, err error)\
>  {  
>         for _, disk := range xl.getLoadBalancedQuorumDisks() {  
>                 if disk == nil {  
>                         continue  
>                 }  
>                 xlMeta, err = readXLMeta(disk, bucket, object)  
>                 if err != nil {  
>                         // For any reason disk is not available continue and read from\
>  other disks.  
>                         if err == errDiskNotFound || err == errFaultyDisk {  
>                                 continue  
>                         }  
>                         return xlMetaV1{}, err  
>                 }  
>                 break  
>         }  
>         return xlMeta, nil

This is hard to differentiate, this can easily happen when a fresh disk is added we could possibly ignore the error just like errDiskNotFound  and change a logic a bit differently.

**Comment by krishnasrinivas** [comment] 2016-07-07 19:50
> This is hard to differentiate, this can easily happen when a fresh disk is added we could possibly ignore the error just like errDiskNotFound and change a logic a bit differently.

or `continue` on every error i.e check disks one by one till there is a success.

or do `metaArr, errs := xl.readAllXLMetadata(bucket, object)` like how GetObject does and return info from the highest version

**Comment by harshavardhana** [comment] 2016-07-07 20:56
> or continue on every error i.e check disks one by one till there is a success.
> 
> or do metaArr, errs := xl.readAllXLMetadata(bucket, object) like how GetObject does and return info from the highest version

Yeah doing that , looks like that is better approach.

**Comment by harshavardhana** [comment] 2016-07-07 21:46
> or continue on every error i.e check disks one by one till there is a success.
> 
> or do metaArr, errs := xl.readAllXLMetadata(bucket, object) like how GetObject does and return info from the highest version
> Yeah doing that , looks like that is better approach.

Another problem here is that ideally these conditions should be resolved by self-heal since it is a clean case for this to happen, so the current code everywhere is not thinking about the healing errors until healing comes in we need to have a mechanism to handle these.

**Closed as completed** 2016-07-08 05:10 UTC
