### ISSUE TITLE
Sometimes Objects or Buckets cannot be accessed when using multiple Minio servers with a shared storage as Backend

### ISSUE THREAD

**Issue by christianbaun** [minio/minio#4834] opened 2017-08-19 07:30 UTC
I face a strange problem when using two Minio servers (Version 2017-08-05T00:00:53Z) with a shared storage as backend and a seperate machine running NGINX as load balancer as frontend. The used hardware are RaspberyPi2 single board computers running Raspbian 7.8 -- I know it is old, but it usually runs super stable.

The NGINX configuration is 

```
$ cat /etc/nginx/sites-available/default
upstream minio_servers {
        	server 10.0.0.110:9000 ;
                server 10.0.0.111:9000 ;
	}

server {
	listen   9000; 
	server_name pi109;

	location / {
		proxy_buffering off;
		proxy_set_header Host $http_host;
		proxy_pass http://minio_servers;    
	}
}
```

I use s3cmd (version 1.6.1) on a seperate machine for interaction. 

Problem: Sometimes (not all the time! Every approx. 50th operation), existing Objects or Buckets cannot be accessed.

I tried using NFS and GlusterFS (version 3.5.3).  

These are error messages from Minio:

One error message when I try using NFS:

`ERRO[1162] Unable to create an object. /s3perf-testbucket/s3perf-testfile1.txt  cause=open /nfs_volume/.minio.sys/buckets/s3perf-testbucket/s3perf-testfile1.txt/fs.json: no such file or directory source=[object-handlers.go:545:objectAPIHandlers.PutObjectHandler()] stack=fs-v1.go:557:fsObjects.PutObject <autogenerated>:402:(*fsObjects).PutObject object-handlers.go:542:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm`

One error message when I try using GlusterFS:

`ERRO[0223] Unable to delete a bucket.                    cause=open /glusterfs32repl2/objectstorage/.minio.sys/buckets/s3perf-testbucket: stale NFS file handle source=[bucket-handlers.go:648:objectAPIHandlers.DeleteBucketHandler()] stack=fs-v1-helpers.go:65:fsRemoveAll fs-v1.go:306:fsObjects.DeleteBucket <autogenerated>:396:(*fsObjects).DeleteBucket bucket-handlers.go:647:objectAPIHandlers.DeleteBucketHandler api-router.go:95:(objectAPIHandlers).DeleteBucketHandler-fm`

I found this issue by measuring the performance of my installation via [s3perf](https://github.com/christianbaun/s3perf). It is a simple script which does just 1) create a bucket 2) upload 10 files 3) fetch the list of objects 4) download the objects 5) erase the objects 6) erase the bucket. After 2 or 3 runs of s3perf, the issue appears.

Best Regards
   Christian 

Update 1: Upgrading [s3cmd](https://github.com/s3tools/s3cmd) to revision 2.0.0 did not solve this issue.

**Comment by krisis** [comment] 2017-08-28 22:07
@christianbaun could you provide us the mount options you used for NFS v3 and GlusterFS?

**Comment by harshavardhana** [comment] 2017-08-29 00:02
`gluster volume info` also would be helpful and also please provide us the tar.gz of `/var/log/glusterfs`.

**Comment by christianbaun** [comment] 2017-08-29 06:28
Here we have the GlusterFS-related information:
[var_log_glusterfs.tar.gz](https://github.com/minio/minio/files/1259284/var_log_glusterfs.tar.gz)

```
$ cat /etc/fstab | grep glusterfs32
pi110:volume32repl2 /glusterfs32repl2 glusterfs defaults,_netdev,transport=tcp,log-level=WARNING,log-file=/var/log/gluster32repl2.log 0 0
$ mount | grep gluster
pi110:volume32repl2 on /glusterfs32repl2 type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
```


```
$ sudo gluster volume info
Volume Name: volume32repl2
Type: Distributed-Replicate
Volume ID: f6d9ac9b-cbf2-4168-a197-272523e1478c
Status: Started
Number of Bricks: 16 x 2 = 32
Transport-type: tcp
Bricks:
Brick1: pi110:/mnt/gluster/brick3
Brick2: pi111:/mnt/gluster/brick3
Brick3: pi112:/mnt/gluster/brick3
Brick4: pi113:/mnt/gluster/brick3
Brick5: pi114:/mnt/gluster/brick3
Brick6: pi115:/mnt/gluster/brick3
Brick7: pi116:/mnt/gluster/brick3
Brick8: pi117:/mnt/gluster/brick3
Brick9: pi118:/mnt/gluster/brick3
Brick10: pi119:/mnt/gluster/brick3
Brick11: pi120:/mnt/gluster/brick3
Brick12: pi121:/mnt/gluster/brick3
Brick13: pi122:/mnt/gluster/brick3
Brick14: pi123:/mnt/gluster/brick3
Brick15: pi124:/mnt/gluster/brick3
Brick16: pi125:/mnt/gluster/brick3
Brick17: pi126:/mnt/gluster/brick3
Brick18: pi127:/mnt/gluster/brick3
Brick19: pi128:/mnt/gluster/brick3
Brick20: pi129:/mnt/gluster/brick3
Brick21: pi130:/mnt/gluster/brick3
Brick22: pi131:/mnt/gluster/brick3
Brick23: pi132:/mnt/gluster/brick3
Brick24: pi133:/mnt/gluster/brick3
Brick25: pi134:/mnt/gluster/brick3
Brick26: pi135:/mnt/gluster/brick3
Brick27: pi136:/mnt/gluster/brick3
Brick28: pi137:/mnt/gluster/brick3
Brick29: pi138:/mnt/gluster/brick3
Brick30: pi139:/mnt/gluster/brick3
Brick31: pi140:/mnt/gluster/brick3
Brick32: pi141:/mnt/gluster/brick3
```

**Comment by christianbaun** [comment] 2017-08-29 06:31
The mount options on client side for the NFS share were:

`$ sudo mount -o rw,noatime,soft,intr,retrans=3,proto=tcp,async 10.0.0.109:nfs_volume /nfs_volume/`

On server side we have this:

```
pi@pi109 ~ $ cat /etc/exports | grep nfs_volume
/nfs_volume/  10.0.0.0/255.255.255.0(rw,sync,no_root_squash,no_subtree_check)
pi@pi109 ~ $ sudo exportfs 
/nfs_volume   	10.0.0.0/255.255.255.0
```

**Comment by harshavardhana** [comment] 2017-11-30 18:04
can you try with the latest GlusterFS release @christianbaun ?

**Comment by christianbaun** [comment] 2017-12-05 09:27
The effort to update the 32 node cluster now is to high for me now. Sorry. :-(

**Comment by krisis** [comment] 2018-01-29 17:48
@christianbaun Did you get a chance to update your cluster? Did you see this issue again after update?

**Comment by harshavardhana** [comment] 2018-01-29 18:28
A possible duplicate of https://github.com/minio/minio/issues/5467

**Comment by harshavardhana** [comment] 2018-02-23 23:27
@christianbaun looks like @jonandernovella has figured out right settings that in #5467 closing this issue.

**Closed as completed by harshavardhana** 2018-02-23 23:27 UTC
Labels: duplicate, priority: high
