### ISSUE TITLE
[gateway] Figure out gateway-testing in travis

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4414] opened 2017-05-23 22:15 UTC
Reported by @deekoder

Currently travis code coverate has gone down because gateway does not have tests. Need to check if we should do functional testing in travis and if so, figure out how functional testing can be done in travis to help the coverage report.

Currently we have 3 backends:
S3: we can use play for travis testing
Azure: we can use minioblob account for testing
GCS: need to figure out how to provide GCS credentials in travis

**Comment by harshavardhana** [comment] 2017-05-23 22:24
The problem is not just functional testing, in-fact there are lack of unit tests i.e large blobs of code can be converted to unit tests.. 

This is what we discussed yesterday, mint is going to cover the functional testing and we need to write more unit tests. on the server side.

**Comment by krishnasrinivas** [comment] 2017-05-23 22:56
gateway-azure.go already has unit tests
gateway-s3.go does not have unit tests

> The problem is not just functional testing, in-fact there are lack of unit tests i.e large blobs of code can be converted to unit tests..

Cursory glance at the GatewayLayer (gateway-azure.go and gateway-s3.go) methods shows that these methods are small. In which case the only way to improve code coverage of gateway significantly is by functional tests.

**Comment by harshavardhana** [comment] 2017-05-23 23:02
> Cursory glance at the GatewayLayer (gateway-azure.go and gateway-s3.go) methods shows that these methods are small. In which case the only way to improve code coverage of gateway significantly is by functional tests.

It might not be the case there are many areas to improve from where i can see - some code can be combined together.  Apart from this there are more areas to increase code coverage for example bucket notification code for 

- kafka
- mysql
- postgres
- AMQP . etc
... 

To look for the full list 

- https://codecov.io/gh/minio/minio/tree/master/cmd
- https://codecov.io/gh/minio/minio/tree/master/pkg

**Comment by deekoder** [comment] 2017-05-23 23:49
since nitish is exploring possibilities with terraform and travis we can assign this to him for now.

**Comment by ab** [comment] 2017-05-24 02:18
Presumably reported by @abperiasamy  :smile:

**Comment by harshavardhana** [comment] 2017-05-24 02:53
> Presumably reported by @abperiasamy

Thanks @ab - This was funny!

**Comment by krishnasrinivas** [comment] 2017-05-24 05:18
> Presumably reported by @abperiasamy

Oops! anyhow, I wanted to put it as @deekoder not @abperiasamy ... fixed it!

**Closed as completed** 2017-06-01 21:03 UTC
Labels: priority: medium
