### ISSUE TITLE
Ctrl-C does not kill minio immediately

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4476] opened 2017-06-05 22:15 UTC
In distributed-XL, upon Ctrl-C minio does not exit immediately when there are 0 active connections:

```
minio server --address localhost:9001 http://localhost:9001/home/krishna/xl/disk1 http://localhost:9002/home/krishna/xl/disk2 http://localhost:9003/home/krishna/xl/disk3 http://localhost:9004/home/krishna/xl/disk4

Initializing data volume.
[01/04] http://localhost:9001/home/krishna/xl/disk1 - 92 GiB online
[02/04] http://localhost:9002/home/krishna/xl/disk2 - 92 GiB online
[03/04] http://localhost:9003/home/krishna/xl/disk3 - 92 GiB online
[04/04] http://localhost:9004/home/krishna/xl/disk4 - 92 GiB online

Endpoint:  http://localhost:9001
AccessKey: SXO8VW2OFKKP2OG7AC85 
SecretKey: CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3 

Browser Access:
   http://localhost:9001

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://localhost:9001 SXO8VW2OFKKP2OG7AC85 CKWSSgrUgvfUMTaNBkB63exet4WW+uNhQvi91Bc3

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 75 GiB Free, 183 GiB Total
Status:         4 Online, 0 Offline. We can withstand [2] more drive failure(s).
^CReceived signal to exit.
Waiting for active connections to terminate - press Ctrl+C to quit immediately.
krishna@escape:~$
```

Also this behavior is not seen all the time.

**Comment by harshavardhana** [comment] 2017-06-05 22:17
I am not able to reproduce this @krishnasrinivas is it consistent?

**Comment by krishnasrinivas** [comment] 2017-06-05 22:23
@harshavardhana yes, i am able to reproduce this issue. Setup is dist-XL on the same machine.

**Comment by harshavardhana** [comment] 2017-06-05 23:10
Are you trying to do Ctrl-C before the cluster is initialized or after? 

```
 ~/run-dist.sh
Initializing data volume for first time. Waiting for other servers to come online (elapsed 14s)

Initializing data volume.
[01/04] https://localhost:9001/tmp/1/1 - 55 GiB online
[02/04] https://localhost:9002/tmp/2/2 - 55 GiB online
[03/04] https://localhost:9003/tmp/3/3 - 55 GiB online
[04/04] https://localhost:9004/tmp/4/4 - 55 GiB online

Endpoint:  https://localhost:9004
AccessKey: minioblob 
SecretKey: bTBZOLvG/MdKxWunuKVCpj5ZEsMVIPEOwG0liAVf1D4CRTBE6REVCJ48mvoZFsjcYwLQ801M8ivjtmFo44bvYg== 
Region:    us-east-1
SQS ARNs:  arn:minio:sqs:us-east-1:2:redis arn:minio:sqs:us-east-1:1:redis

Browser Access:
   https://localhost:9004

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio https://localhost:9004 minioblob bTBZOLvG/MdKxWunuKVCpj5ZEsMVIPEOwG0liAVf1D4CRTBE6REVCJ48mvoZFsjcYwLQ801M8ivjtmFo44bvYg==

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 30 GiB Free, 110 GiB Total
Status:         4 Online, 0 Offline. We can withstand [2] more drive failure(s).

^CReceived signal to exit.
```

Because i am able to run this approach fine all the time.

**Comment by harshavardhana** [comment] 2017-06-05 23:11
```
 cat ~/run-dist.sh
#!/bin/bash

$(minio server --address localhost:9001 https://localhost:9001/tmp/1/1 https://localhost:9002/tmp/2/2 https://localhost:9003/tmp/3/3 https://localhost:9004/tmp/4/4)&
$(minio server --address localhost:9002 https://localhost:9001/tmp/1/1 https://localhost:9002/tmp/2/2 https://localhost:9003/tmp/3/3 https://localhost:9004/tmp/4/4)&
$(minio server --address localhost:9003 https://localhost:9001/tmp/1/1 https://localhost:9002/tmp/2/2 https://localhost:9003/tmp/3/3 https://localhost:9004/tmp/4/4)&
minio server --address localhost:9004 https://localhost:9001/tmp/1/1 https://localhost:9002/tmp/2/2 https://localhost:9003/tmp/3/3 https://localhost:9004/tmp/4/4
```
My script.

**Comment by harshavardhana** [comment] 2017-06-08 02:29
This title needs to be changed, server indeed dies but dies after 10-15secs based on our ReadTimeout.  But has a sequence of steps to reproduce this issue. But there is also a situation where the timeout has happened then subsequently the server indeed exists properly. 

https://github.com/minio/minio/pull/4500 is a related fix which exposed some other issue.

**Comment by deekoder** [comment] 2017-06-08 16:57
We need to revisit trapping ctrl+c signal for distributed minio. We have to handle this in admin api in the future.

**Comment by balamurugana** [comment] 2017-08-08 19:24
Fixed by https://github.com/minio/minio/pull/4636

**Closed as completed by balamurugana** 2017-08-08 19:24 UTC
Labels: priority: medium
