### ISSUE TITLE
bug: Server panic with `https` request when run locally.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#2535] opened 2016-08-23 02:59 UTC
## Expected behaviour

Atleast not to crash and produce meaningful error. 
## Actual behaviour

Crashes with the following error.

```
goroutine 3261 [running]:
net/http.(*conn).serve.func1(0xc82011e880)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1389 +0xc1
panic(0xbee780, 0xc8200100e0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:426 +0x4e9
crypto/tls.(*Conn).serverHandshake(0xc82007c900, 0x0, 0x0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/handshake_server.go:43 +0x4d6
crypto/tls.(*Conn).Handshake(0xc82007c900, 0x0, 0x0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:1035 +0x169
net/http.(*conn).serve(0xc82011e880)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1405 +0x382
created by net/http.(*Server).Serve
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:2137 +0x44e
2016/08/22 19:55:19 http: panic serving 192.168.1.92:60382: runtime error: invalid memory address or nil pointer dereference
goroutine 3379 [running]:
net/http.(*conn).serve.func1(0xc82011f100)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1389 +0xc1
panic(0xbee780, 0xc8200100e0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:426 +0x4e9
crypto/tls.(*Conn).serverHandshake(0xc82007d500, 0x0, 0x0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/handshake_server.go:43 +0x4d6
crypto/tls.(*Conn).Handshake(0xc82007d500, 0x0, 0x0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:1035 +0x169
net/http.(*conn).serve(0xc82011f100)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1405 +0x382
created by net/http.(*Server).Serve
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:2137 +0x44e
2016/08/22 19:55:19 http: panic serving 192.168.1.92:60384: runtime error: invalid memory address or nil pointer dereference
goroutine 3380 [running]:
net/http.(*conn).serve.func1(0xc82011f200)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1389 +0xc1
panic(0xbee780, 0xc8200100e0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:426 +0x4e9
crypto/tls.(*Conn).serverHandshake(0xc82007d800, 0x0, 0x0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/handshake_server.go:43 +0x4d6
crypto/tls.(*Conn).Handshake(0xc82007d800, 0x0, 0x0)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/crypto/tls/conn.go:1035 +0x169
net/http.(*conn).serve(0xc82011f200)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1405 +0x382
created by net/http.(*Server).Serve
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:2137 +0x44e
```

The complete is at `play/rao/output.txt`
## Steps to reproduce the behaviour

Build from latest master at 2da0cfc9049babe0e43e0e6f55ab3528f8d9c629 , and issue `curl https://localhost/testbucket`
## Minio version

latest master at 2da0cfc9049babe0e43e0e6f55ab3528f8d9c629
## System information

Minio servers.

**Comment by harshavardhana** [comment] 2016-08-23 03:26
Closing as duplicate of #2536

**Closed as completed by harshavardhana** 2016-08-23 03:26 UTC
