### ISSUE TITLE
Unable to set policy for bucket through Ruby AWS SDK

### ISSUE THREAD

**Issue by marclennox** [minio/minio#2350] opened 2016-08-03 15:38 UTC
I'm trying to set a bucket policy using the ruby SDK, passing in the following policy document.

``` json
{
  "Version":"2012-10-17",
  "Statement":[
    {
      "Sid":"AddPerm",
      "Effect":"Allow",
      "Principal": "*",
      "Action":["s3:GetObject"],
      "Resource":["arn:aws:s3:::examplebucket/*"]
    }
  ]
}
```

I'm getting the following error

`An error occurred (InvalidPolicyDocument) when calling the PutBucketPolicy operation: The content of the form does not meet the conditions specified in the policy document.`

Any idea what is wrong with my policy document?

**Comment by koolhead17** [comment] 2016-08-03 17:32
hello @marclennox please share the code, we will test it at our end.

**Comment by marclennox** [comment] 2016-08-03 17:47
I can replicate the same error using the AWS CLI as follows:

`aws --endpoint-url http://127.0.0.1:9000 s3api put-bucket-policy --bucket examplebucket --policy file://policy.json`

**Comment by marclennox** [comment] 2016-08-03 17:48
Note that I'm using Minio in XL mode with 6 disks.

**Comment by harshavardhana** [comment] 2016-08-03 18:07
> Note that I'm using Minio in XL mode with 6 disks.

Thanks @marclennox will update you in a bit.

**Comment by harshavardhana** [comment] 2016-08-03 18:17
@marclennox the problem is the 'Principal' field here - can you try this? 

```
$ cat /tmp/policy.json 
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AddPerm",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "*"
        ]
      },
      "Action": [
        "s3:GetObject"
      ],
      "Resource": [
        "arn:aws:s3:::testbucket/*"
      ]
    }
  ]
}
```

More convenient way rather than writing your own `policy.json` it is easier to use - https://docs.minio.io/docs/minio-client-complete-guide#policy - would also avoid user errors.

**Comment by marclennox** [comment] 2016-08-03 19:06
That worked, thanks @harshavardhana and @koolhead17.

I'm trying to do this within our application so ideally stick to the aws ruby sdk for all operations.

**Comment by koolhead17** [comment] 2016-08-03 19:09
sounds great @marclennox Feel free to add your use case with Minio https://github.com/minio/awesome-minio 😄

**Comment by harshavardhana** [comment] 2016-08-03 19:10
> That worked, thanks @harshavardhana and @koolhead17.
> 
> I'm trying to do this within our application so ideally stick to the aws ruby sdk for all operations.

Closing.

**Closed as completed by harshavardhana** 2016-08-03 19:10 UTC
