### ISSUE TITLE
Is there any way to change the limit on the cache object size?

### ISSUE THREAD

**Issue by sgrosu** [minio/minio#6603] opened 2018-10-10 09:04 UTC
I have realized that the maximum size of the objects in the minio cache is a function of the free space on the minio cache disk - only objects a 100 times smaller that the remaining free space get cached.
Is there any way to tweak / circumvent this constraint?

## Expected Behavior
Minio should cache objects of any sizes

## Current Behavior
Minio only caches objects 100 times smaller that the remaining free space on the minio cache disk

## Possible Solution
Maybe add an environment variable allowing the tweaking of this setting

## Steps to Reproduce (for bugs)
This is clearly not a bug, just not flexible for all use-cases.

## Context
We are transferring quite big files (3- 4 TB) so we have a hard time to finf the appropriate storage for minio cache disks

## Your Environment
Centos 7.4
Minio latest - mode: minio azure gateway
XEN virtual machine

**Comment by poornas** [comment] 2018-10-10 19:49
@sgrosu, this restriction was a rough heuristic to ensure there is always enough space on the cache.Currently the only other lever to free up space is reduce the cache expiry duration or increase MINIO_CACHE_MAXUSE (max usable space for cache). How much space is being used for cache?

**Comment by deekoder** [comment] 2018-10-11 19:10
@sgrosu let us know if there's any further questions. Closing this as working as intended.

**Closed as completed by deekoder** 2018-10-11 19:10 UTC
Labels: working as intended, community, priority: medium

**Comment by sgrosu** [comment] 2018-10-12 08:33
We are planning to move ~ 4 TB large files - which would mean we need PB worth of caching disks. We would not necessary move lots of them, but would like to be able to read them from different locations, hence the utility of the cache. I would like to get away without having to use a PB size cache disk.

That being said, are you going to remove the limitation in the next release, or make it configurable? And, if yes, when is the next release due?

Thanks very much!

**Comment by poornas** [comment] 2018-10-12 20:55
@sgrosu, we can remove this restriction in the next release. Next release will be fairly soon.
