### ISSUE TITLE
ListObjectVersions sometimes returns versions in the wrong order

### ISSUE THREAD

**Issue by mrry** [minio/minio#16008] opened 2022-11-04 16:45 UTC
## Expected Behavior

ListObjectVersions should match the S3 semantics of returning objects in the reverse order of when they are created.

This behavior is [mentioned in the S3 docs for ListObjectVersions](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html#:~:text=The%20following%20request%20returns%20objects%20in%20the%20order%20they%20were%20stored%2C%20returning%20the%20most%20recently%20stored%20object%20first%20starting%20with%20the%20value%20for%20key%2Dmarker.), and is the behavior that I see most of the time when running MinIO in standalone mode.

I am running in a Docker container, version `minio/minio@sha256:048de4353078028d55c569a0ab54f4254973b8386c522e816176201798191391`, which is `:latest` as of today).

## Current Behavior

Occasionally, ListObjectVersions will return an object version that has been overwritten with `"IsLatest": true`, and ordered before the newer version.

## Possible Solution

I haven't tracked down the code responsible for version ordering. However:

Although the version IDs are in the wrong order, the `LastModified` fields for each version are in reverse chronological order. In other words, if we make two sequential PutObject calls `P_1`, `P_2`, the version written by `P_1` sometimes has a later timestamp than the version written by `P_2`. 

## Steps to Reproduce (for bugs)

Install dependencies:

```shell
$ pip install boto3 numpy
```

Run the following script:

```python
import boto3
import numpy
import uuid

bucket = "test"

# Create a bucket with versioning enabled.
client = boto3.client('s3', endpoint_url="http://localhost:9000")
client.create_bucket(Bucket=bucket)
client.put_bucket_versioning(Bucket=bucket, VersioningConfiguration={"Status":"Enabled"})

# The issue occurs only occasionally, so create multiple prefixes with multiple versions.
for p in range(1000000):
  prefix = str(uuid.uuid4())
  
  put_versions = []
  put_versions.append(client.put_object(Bucket=bucket, Key=prefix))
  
  for i in range(10):
    list_versions = [v for v in client.list_object_versions(Bucket=bucket, Prefix=prefix)["Versions"]]

    # The versions returned by `list_object_versions()` (newest first) should be the reverse of the versions in `put_versions` (newest last).
    numpy.testing.assert_array_equal([v["VersionId"] for v in list_versions], [v["VersionId"] for v in put_versions[::-1]])

    put_versions.append(client.put_object(Bucket=bucket, Key=prefix))
```

## Context

This is preventing me from deploying a system that depends on version consistency using MinIO.

## Regression

Is this issue a regression? Unknown

## Your Environment

* Version used: `Version: RELEASE.2022-10-29T06-21-33Z (go1.19.2 linux/amd64)`
* Server setup and configuration: running on Docker (on macOS):

```
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
```

...although the issue has also arisen when running in CI pipelines on CodeFresh.

**Comment by harshavardhana** [comment] 2022-11-04 16:58
is this a single drive setup? @mrry can you test with multi-drive i.e more than 4 disks?

**Comment by mrry** [comment] 2022-11-04 17:02
@harshavardhana I'm seeing the problem running `minio server /data` in Docker on my (single drive) laptop and in CI.

Unfortunately I don't have a multi-disk system available to test it.

**Comment by harshavardhana** [comment] 2022-11-04 17:03
you can simulate it via `minio server /data{1...4}`  @mrry - I think the issue is because of this - single node single drive was missing some locking semantics

```
commit 0d49b365ff3a76e323602db12e43815b31576c8d
Author: Harshavardhana <harsha@minio.io>
Date:   Tue Nov 1 16:41:01 2022 -0700

    converge SNSD deployments into single code (#15988)

```

**Comment by mrry** [comment] 2022-11-04 17:16
Ah, thanks for that hint. When I run with `/data{1...4}` I still see the same issue with that repro script.

**Comment by harshavardhana** [comment] 2022-11-04 18:18
I tried this on a local disk I am unable to reproduce the problem @mrry - it looks like some persistent layer issue in your container environment. 

Have you tried without running in docker containers by attaching a local disk to your container?

**Comment by mrry** [comment] 2022-11-04 21:36
I just tried running locally on my laptop (`Version: RELEASE.2022-10-29T06-21-33Z (go1.19.2 darwin/amd64)`), in single-disk mode, and it seemed to work reliably (at least, after many tries, I couldn't reproduce the failure).

I also tried running in a container using a mounted host directory as the storage dir, and again using a tmpfs mount as the storage dir. In both cases, I got out-of-order versions returned.

Is there a recommended way to make this work with Docker?

**Comment by harshavardhana** [comment] 2022-11-05 19:13
> I just tried running locally on my laptop (`Version: RELEASE.2022-10-29T06-21-33Z (go1.19.2 darwin/amd64)`), in single-disk mode, and it seemed to work reliably (at least, after many tries, I couldn't reproduce the failure).
> 
> I also tried running in a container using a mounted host directory as the storage dir, and again using a tmpfs mount as the storage dir. In both cases, I got out-of-order versions returned.
> 
> Is there a recommended way to make this work with Docker?

I will have to what is up with Docker. It must be some layering that is ignoring our O_SYNC semantics.

**Comment by harshavardhana** [comment] 2022-11-05 19:14
Oh you are running container on macOS?

**Comment by mrry** [comment] 2022-11-05 20:07
> Oh you are running container on macOS?

For my local testing, yes. But it's failing the same way in our CI, which is based on Codefresh, and I don't think that's macOS-based.

**Comment by harshavardhana** [comment] 2022-11-05 20:20
> > Oh you are running container on macOS?
> 
> For my local testing, yes. But it's failing the same way in our CI, which is based on Codefresh, and I don't think that's macOS-based.

I will check what this is. It looks like some kind of filesystem behavior that is buggy in docker layering.

Have you tried attaching a real FS like ext4 or XFS disk to your container for persistence ?

**Comment by harshavardhana** [comment] 2022-11-07 17:44
I tried podman and docker both 

```
podman run --rm -d -p 9000:90000 quay.io/minio/minio server /data
```

and unable to reproduce it on a Linux system. 

Can you try running this on a Linux system? @mrry

**Comment by harshavardhana** [comment] 2022-11-09 09:50
So I tried both podman, docker on Linux platform and also baremetal setup on Linux. Without containers macOS also works - I cannot reproduce the problem that you are describing, I do not have access to any other kind of systems.

I will perhaps close this issue for now, since this is not something that affects our primary deployment platform.

**Closed as completed by harshavardhana** 2022-11-09 09:50 UTC
Labels: community, waiting for info

**Comment by mrry** [comment] 2022-11-09 23:41
Can you share the docker-on-Linux configuration that worked for you? It's possible we can replicate that in our CI.

Also, can you shed a little light on the versioning implementation? What filesystem behavior does it rely on, so that we might be able to find a working configuration? 

Looking at https://blog.min.io/minio-versioning-metadata-deep-dive/, it sounds like the problem might come from this part:
>Object versions are strictly sorted by “Modification Time”, meaning the time the object version was uploaded.

... if there's a possibility that the modification time could go backward? I've had a look in the source to see where this comes from, but any pointers would be useful. Perhaps there's an assertion we could add that new objects always have `ModTime` greater than all existing versions.

**Comment by harshavardhana** [comment] 2022-11-10 05:04
> Also, can you shed a little light on the versioning implementation? What filesystem behavior does it rely on, so that we might be able to find a working configuration?

Nothing specific we want O_SYNC to be honored @mrry 

> ... if there's a possibility that the modification time could go backward? I've had a look in the source to see where this comes from, but any pointers would be useful. Perhaps there's an assertion we could add that new objects always have `ModTime` greater than all existing versions.

It is possible if you have a time skew on your systems at times.
