### ISSUE TITLE
Support of IP restrictions in bucket policy conditions

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4368] opened 2017-05-18 18:41 UTC
Users should be able to restrict/forbid access by ip addresses (ipv4, ipv6) using bucket policy conditions.

Spec link:
http://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-3

**Comment by harshavardhana** [comment] 2017-05-18 18:44
Closing as duplicate of #4369

**Closed as completed by harshavardhana** 2017-05-18 18:44 UTC
Labels: duplicate
