### ISSUE TITLE
Unstable erasure cluster in case of (simulated) node-crash

### ISSUE THREAD

**Issue by tommyhaas1** [minio/minio#6318] opened 2018-08-20 11:26 UTC
Hi, 

currently i'm running the following setup:

- erasure mode with 6 nodes/1 disk each, EC4:2

Test cases:

- case1) 
shutting down minio normally on one node -> no problem, minio cluster is still accepting uploads,  one node is marked as offline (as it should be)

- case2) 
blocking port 9000 via iptables (kinda simulating a server crash) on one node makes cluster completely unstable, put operations fail with: "Multiple disks failures, unable to write data" after a loooong timeout. even mc admin info <bucket> is not able to resolve that one node is just unavailable and mark it as offline to continue using just the remaining nodes

Iptables rule to simulate server crash:
- iptables -A INPUT -p tcp --destination-port 9000 -j DROP

After doing that on one node (out of 6) minio cluster is unuseable.

Commands will fail (no matter on which remaining node):
- mc admin info <bucket>
- mc cp testfile bucket/testfile

Version: 2018-08-18T03:49:57Z
OS: Ubuntu: 18.04

**Comment by harshavardhana** [comment] 2018-08-20 15:57
Thanks for opening the issue we will reproduce it.

**Comment by balamurugana** [comment] 2018-08-31 11:49
Below is the behavior when a node is unreachable.

Setup:
* Fedora 28 4 KVM nodes/1 disk

All nodes available:

```bash
$ time mc cp minio test/mybucket/minio.bin
`minio` -> `test/mybucket/minio.bin`
Total: 22.68 MB, Transferred: 22.68 MB, Speed: 57.99 MB/s

real	0m0.480s
user	0m0.198s
sys	0m0.044s
```

When node4 is unreachable by using iptables:
```bash
$ time mc cp minio test/mybucket/minio.bin
`minio` -> `test/mybucket/minio.bin`
Total: 22.68 MB, Transferred: 22.68 MB, Speed: 68.24 MB/s

real	2m36.518s
user	0m0.138s
sys	0m0.083s

$ time mc cp minio test/mybucket/minio.bin
`minio` -> `test/mybucket/minio.bin`
Total: 22.68 MB, Transferred: 22.68 MB, Speed: 71.32 MB/s

real	0m0.380s
user	0m0.123s
sys	0m0.047s

$ time mc cp minio test/mybucket/minio.bin
`minio` -> `test/mybucket/minio.bin`
Total: 22.68 MB, Transferred: 22.68 MB, Speed: 70.93 MB/s

real	0m0.438s
user	0m0.137s
sys	0m0.057s
```

When node4 is down by simulating network disconnect:
```bash
$ virsh domif-setlink node4 vnet3 down
```
`mc cp` timings
```bash
$ time mc cp minio test/mybucket/minio.bin
`minio` -> `test/mybucket/minio.bin`
Total: 22.68 MB, Transferred: 22.68 MB, Speed: 68.25 MB/s

real	1m6.423s
user	0m0.137s
sys	0m0.048s

$ time mc cp minio test/mybucket/minio.bin
`minio` -> `test/mybucket/minio.bin`
Total: 22.68 MB, Transferred: 22.68 MB, Speed: 74.39 MB/s

real	0m2.720s
user	0m0.139s
sys	0m0.059s

$ time mc cp minio test/mybucket/minio.bin
`minio` -> `test/mybucket/minio.bin`
Total: 22.68 MB, Transferred: 22.68 MB, Speed: 65.57 MB/s

real	0m0.433s
user	0m0.133s
sys	0m0.090s
```

The timeout to identify node network failure is `1 * time.Minute` for each RPC module (lock, storage, etc).  Mostly two minutes timeout is seen at maximum for first call (one minute for lock and one minute for storage).

This is normal behavior as per current timeout configuration.

**Comment by deekoder** [comment] 2018-09-06 01:04
@tommyhaas1 please let us know, how we could help you further.

**Comment by tommyhaas1** [comment] 2018-09-06 19:39
Hi,

and thanks for your comment! 
Basically i would say the timeout is way to high! What would be the disadvantage of setting it per default to just a few seconds or make it configurable?
I tried again and i'm getting this timeout mostly everytime if one node is blocked by iptables:

```
root@storage1 ~ # time mc cp random1.bin storage/test/
random1.bin:                       56.34 MB / 56.34 MB  100.00% 33.63 MB/s 1s
real    0m1.764s
user    0m0.446s
sys     0m0.107s
```

^^ this is normal, no iptables block applied
results down below with one 1 blocked node (out of 6), max. timeout was >3mins(!)

```
root@storage1 ~ # time mc cp random1.bin storage/test/
random1.bin:                       56.34 MB / 56.34 MB  100.00% 938.57 KB/s 1m1s
real    1m24.342s
user    0m0.455s
sys     0m0.135s
root@storage1 ~ # time mc cp random1.bin storage/test/
random1.bin:                       56.34 MB / 56.34 MB  100.00% 38.40 MB/s 1s
real    3m1.603s
user    0m0.392s
sys     0m0.139s
root@storage1 ~ # time mc cp random1.bin storage/test/
random1.bin:                       56.34 MB / 56.34 MB  100.00% 37.74 MB/s 1s
real    1m1.566s
user    0m0.440s
sys     0m0.125s
root@storage1 ~ # time mc cp random1.bin storage/test/
random1.bin:                       56.34 MB / 56.34 MB  100.00% 38.67 MB/s 1s
real    0m1.530s
user    0m0.464s
sys     0m0.108s
root@storage1 ~ # time mc cp random1.bin storage/test/
random1.bin:                       56.34 MB / 56.34 MB  100.00% 37.77 MB/s 1s
real    1m1.573s
user    0m0.456s
sys     0m0.115s
root@storage1 ~ # time mc cp random1.bin storage/test/
random1.bin:                       56.34 MB / 56.34 MB  100.00% 37.93 MB/s 1s
real    1m1.561s
user    0m0.449s
sys     0m0.123s
```


Even mc admin cmd failed (xxx.4.123.202 is the node with iptable block):


```
root@storage1 ~ # time mc admin info storage
●  xxx.4.123.208:9000
   Uptime : online since 24 minutes ago
  Version : 2018-09-01T00:38:25Z
   Region : eu-central-1
 SQS ARNs : <none>
    Stats : Incoming 226MiB, Outgoing 24KiB
  Storage : Used 1.3TiB
    Disks : 5, 1


●  xxx.251.124.5:9000
   Uptime : Server is offline
    Error : Post http://xxx.251.124.5:9000/minio/admin: read tcp xxx.4.123.208:41616->xxx.251.124.5:9000: i/o timeout

●  xxx.9.37.77:9000
   Uptime : Server is offline
    Error : Post http://xxx.9.37.77:9000/minio/admin: read tcp xxx.4.123.208:53246->xxx.9.37.77:9000: i/o timeout

●  xxx.4.123.202:9000
   Uptime : Server is offline
    Error : Post http://xxx.4.123.202:9000/minio/admin: dial tcp xxx.4.123.202:9000: i/o timeout

●  xxx.4.63.74:9000
   Uptime : Server is offline
    Error : Post http://xxx.4.63.74:9000/minio/admin: read tcp xxx.4.123.208:54672->xxx.4.63.74:9000: i/o timeout

●  xxx.9.119.110:9000
   Uptime : Server is offline
    Error : Post http://xxx.9.119.110:9000/minio/admin: read tcp xxx.4.123.208:56704->xxx.9.119.110:9000: i/o timeout


real    1m0.048s
user    0m0.019s
sys     0m0.000s
```

**Comment by CAFxX** [comment] 2018-10-12 05:12
> Basically i would say the timeout is way to high! What would be the disadvantage of setting it per default to just a few seconds or make it configurable?

I agree. At the very least the timeouts should be configurable. And maybe if tcp-keepalives or other heartbeats were enabled, this kind of network partitions would be detectable much more reliably and quickly (an RPC call may take a long time for many reasons -e.g. if it involves disk I/O- but a heartbeat should always take a very small, constant time to be processed - so e.g. you could still keep the RPC timeouts around 1 minute, but detect in ~5 seconds a network partition by sending a heartbeat every second and considering the connection dead if no heartbeats are received within 5 seconds)

**Comment by harshavardhana** [comment] 2019-02-07 01:42
We have moved to HTTP rest client style since some releases now, there are no active connections kept other than HTTP transports keep alive conns in connection pooling. We have much less state in a running process and everything is streams based.

Closing this as fixed for now please test again and let us know @tommyhaas1 @CAFxX

**Closed as completed by harshavardhana** 2019-02-07 01:42 UTC
Labels: working as intended, community, priority: medium
