### ISSUE TITLE
[resolved] Unable to put object using AWS S3 Java Client and version enabled bucket

### ISSUE THREAD

**Issue by RStapley** [minio/minio#9949] opened 2020-06-30 21:25 UTC
## Expected Behavior

When putting an object into a versioned bucket it adds the object to the bucket. 

## Current Behavior

I get an exception:
software.amazon.awssdk.services.s3.model.S3Exception: A header you provided implies functionality that is not implemented (Service: S3, Status Code: 501, Request ID: 161D6036D0CFAE23)

More stack trace: https://gist.github.com/RStapley/26fc475127d25653f1b607e380a38a1a

## Possible Solution

I may take a stab at looking into this, but am currently unfamiliar with the code. 

## Steps to Reproduce (for bugs)

1. Build master branch Docker image:
```
RS025541@W1839171 MINGW64 ~/Desktop/minio-master
$ docker build ./minio-master
Sending build context to Docker daemon  22.46MB
Step 1/17 : FROM golang:1.13-alpine as builder
 ---> cea245765db1
Step 2/17 : LABEL maintainer="MinIO Inc <dev@min.io>"
 ---> Using cache
 ---> ecd0b012010f
Step 3/17 : ENV GOPATH /go
 ---> Using cache
 ---> f6a8c3331bf6
Step 4/17 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> 219f1309408e
Step 5/17 : ENV GO111MODULE on
 ---> Using cache
 ---> afc9d574d0c5
Step 6/17 : RUN       apk add --no-cache git &&      git clone https://github.com/minio/minio && cd minio &&      git checkout master && go install -v -ldflags "$(go run buildscripts/gen-ldflags.go)"
 ---> Using cache
 ---> 6b97553224c9
Step 7/17 : FROM alpine:3.12
 ---> a24bb4013296
Step 8/17 : ENV MINIO_UPDATE off
 ---> Using cache
 ---> e38c5bdbac42
Step 9/17 : ENV MINIO_ACCESS_KEY_FILE=access_key     MINIO_SECRET_KEY_FILE=secret_key     MINIO_KMS_MASTER_KEY_FILE=kms_master_key     MINIO_SSE_MASTER_KEY_FILE=sse_master_key
 ---> Using cache
 ---> ca47d4546719
Step 10/17 : EXPOSE 9000
 ---> Using cache
 ---> 3f3046e3e770
Step 11/17 : COPY --from=builder /go/bin/minio /usr/bin/minio
 ---> Using cache
 ---> e2f5e5903720
Step 12/17 : COPY --from=builder /go/minio/CREDITS /third_party/
 ---> Using cache
 ---> 53eab419483b
Step 13/17 : COPY --from=builder /go/minio/dockerscripts/docker-entrypoint.sh /usr/bin/
 ---> Using cache
 ---> 8d36ddec5fad
Step 14/17 : RUN       apk add --no-cache ca-certificates 'curl>7.61.0' 'su-exec>=0.2' &&      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf
 ---> Using cache
 ---> cc233d792021
Step 15/17 : ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
 ---> Using cache
 ---> 773a0b3ac16f
Step 16/17 : VOLUME ["/data"]
 ---> Using cache
 ---> 4cdac3d0d767
Step 17/17 : CMD ["minio"]
 ---> Using cache
 ---> c99f1cf65557
Successfully built c99f1cf65557
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

```

2.  Run the docker image
```
RS025541@W1839171 MINGW64 ~/Desktop/minio-master
$ docker run -p 9000:9000 c99f1cf65557 server /data
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'

```

3. I tried the Java and .NET SDK with the same result.

In both cases if I do not do the putBucketVersioning call I can add objects with no other change to the code. 

.NET example: https://github.com/RStapley/MinioBugExampleVersionedBucket

Here is the Java code:
```Java
    S3ClientBuilder builder = S3Client.builder();

    builder.credentialsProvider(CeBlobCredentialsProvider.create("minioadmin", "minioadmin"));
    builder.region(Region.US_EAST_2);
    builder.endpointOverride(URI.create("http://localhost:9000"));

    S3Configuration confBuilder = S3Configuration
        .builder()
        .pathStyleAccessEnabled(true)
        .build();

    builder.serviceConfiguration(confBuilder);
    builder.httpClient(
      UrlConnectionHttpClient.builder()
          .buildWithDefaults(
              AttributeMap.builder().put(TRUST_ALL_CERTIFICATES, Boolean.TRUE).build()));

    S3Client client = builder.build();

    CreateBucketRequest cbr = CreateBucketRequest.builder().bucket("testbucket").build();
    client.createBucket(cbr);

    PutBucketVersioningRequest versioningRequest = PutBucketVersioningRequest.builder().bucket("testbucket").versioningConfiguration(
        VersioningConfiguration.builder().status(BucketVersioningStatus.ENABLED).build()).build();

    client.putBucketVersioning(versioningRequest);

    String key = "123";
    String testContent = "testContent";

    PutObjectRequest por = PutObjectRequest.builder().bucket("testbucket").key(key).build();
    RequestBody requestBody = RequestBody.fromString(testContent);
    client.putObject(por, requestBody);
```

## Context

Trying to use Minio as a docker image to isolate my local development ecosystem from Amazon S3. 

## Regression

No

## Your Environment

* Version used (`minio version`): Current master
* Environment name and version (e.g. nginx 1.9.1): Java with Maven and .NET both running on Windows 10 with Docker desktop community 2.3.0.3
* Server type and version: 
* Operating System and version (`uname -a`): Windows 10 build 18363
* Link to your project:

**Comment by harshavardhana** [comment] 2020-06-30 21:27
> Step 6/17 : RUN       apk add --no-cache git &&      git clone https://github.com/minio/minio && cd minio &&      git checkout master && go install -v -ldflags "$(go run buildscripts/gen-ldflags.go)"

When you clone the repo it is not using master branch - the default HEAD is `release` branch - to compile from source you need to` git clone ` and then `git checkout master` 

Please do so, versioning would work. Closing this issue as working as intended.

**Closed as completed by harshavardhana** 2020-06-30 21:27 UTC
Labels: working as intended, fixed
