### ISSUE TITLE
[duplicate] Files in the .minio.sys/buckets directory start to occupy more than the entire storage

### ISSUE THREAD

**Issue by mrsrvman** [minio/minio#10091] opened 2020-07-20 06:57 UTC
Files in the .minio.sys/buckets directory start to occupy more than the entire storage
Metadata is not always removed when a file is deleted.

ncdu 1.12 ~ Use the arrow keys to navigate, press ? for help
--- /backup/offline ----------------------------------------------------------------------------------------------------------------------------------------------------
   87.3 GiB [##########] /stats
   20.4 GiB [##        ] /.minio.sys
   20.0 GiB [##        ] /dns2
    5.8 GiB [          ] /dns1
    2.6 GiB [          ] /url-s
    2.6 GiB [          ] /ssl
  190.7 MiB [          ] /pg-backup-test
Total disk usage: 139.0 GiB  Apparent size: 120.3 GiB  Items: 7961736

--- /backup/offline/.minio.sys -----------------------------------------------------------------------------------------------------------------------------------------
   20.4 GiB [##########] /buckets
  228.0 KiB [          ] /config
 Total disk usage:  20.4 GiB  Apparent size:  10.8 GiB  Items: 5302477

## Possible Solution

Use a different storage type and remove metadata when deleting files.

## Steps to Reproduce (for bugs)

1.  Start using minio to store backups that are produced using xtrabackup and xbcloud.
2.  After a while, a picture is obtained - there are many files in the directory .minio.sys/buckets
3.
4.

## Regression
 YES

## Your Environment

* Version used (`minio --version`): RELEASE.2020-07-20T02-25-16Z
* Server setup and configuration: 
* Operating System and version (`uname -a`): Linux backup1 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

**Comment by mrsrvman** [comment] 2020-07-20 06:58
https://github.com/minio/minio/issues/5803
https://github.com/minio/minio/issues/8586

**Comment by harshavardhana** [comment] 2020-07-20 07:00
Closing as duplicate of https://github.com/minio/minio/issues/9897

**Closed as completed by harshavardhana** 2020-07-20 07:00 UTC
Labels: duplicate, community, triage
