### ISSUE TITLE
Error using minio as s3 replacement

### ISSUE THREAD

**Issue by iamchathu** [minio/minio#2667] opened 2016-09-11 11:42 UTC
## Expected behaviour

I have a NodeJS app which uses Amazon S3 as file storage. I started tring minio.
So I changed AWS S3's endpoint had many tries.

This the final code I ended in : 

``` js

let s3conf = {};
if (process.env.NODE_ENV != 'production') {
    s3conf.endpoint = 'http://192.168.1.102:9000/';
    s3conf.s3ForcePathStyle = true;
    s3conf.AccessKey = 'myaccesskey';
    s3conf.SecretKey = 'mysecret';
    s3conf.sslEnabled = false;
    s3conf.signatureVersion = 'v4';
}

const s3 = new AWS.S3(s3conf);
```

Now I'm getting an error 

``` js
InternalError: We encountered an internal error, please try again.
    at Request.extractError (/.../node_modules/aws-sdk/lib/services/s3.js:538:35)
    at Request.callListeners (/.../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/.../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/.../node_modules/aws-sdk/lib/request.js:668:14)
    at Request.transition (/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
```
## Minio version
- 2016-08-21T02:44:47Z
## System information

Minio Hosted in Windows 8.1 64 bit
NodeJS app running on Mac OS 10.9

**Comment by koolhead17** [comment] 2016-09-11 16:15
hello @iamchathu can you try this and let us know what are you getting? 

```
let s3conf = {};
if (process.env.NODE_ENV != 'production') {
    s3conf.endpoint = 'http://192.168.1.102:9000';
    s3conf.s3ForcePathStyle = true;
    s3conf.AccessKey = 'myaccesskey';
    s3conf.SecretKey = 'mysecret';
    s3conf.signatureVersion = 'v4';
}

const s3 = new AWS.S3(s3conf);
```

**Comment by harshavardhana** [comment] 2016-09-11 17:20
> Now I'm getting an error
> 
> InternalError: We encountered an internal error, please try again.
>     at Request.extractError (/.../node_modules/aws-sdk/lib/services/s3.js:538:35)
>     at Request.callListeners (/.../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
>     at Request.emit (/.../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>     at Request.emit (/.../node_modules/aws-sdk/lib/request.js:668:14)
>     at Request.transition (/.../node_modules/aws-sdk/lib/request.js:22:10)
>     at AcceptorStateMachine.runTo (/.../node_modules/aws-sdk/lib/state_machine.js:14:12)

what is the operation did you peform? can you paste the whole code?

**Comment by iamchathu** [comment] 2016-09-11 18:37
I'm using multer-s3 and I performed upload file.

**Comment by harshavardhana** [comment] 2016-09-11 18:52
> I'm using multer-s3 and I performed upload file.

Can you paste the whole code - we will use that to reproduce this issue locally? - thanks

**Comment by iamchathu** [comment] 2016-09-11 18:58
``` js
"use strict";
const multerS3 = require('multer-s3');
const AWS = require('aws-sdk');
const Path = require('path');
const s3config = require('../config/s3config');

let s3conf = {};
if (process.env.NODE_ENV != 'production') {
    s3conf.endpoint = 'http://192.168.8.102:9000/';
    s3conf.s3ForcePathStyle = true;
    s3conf.AccessKey = 'myaccesskey';
    s3conf.SecretKey = 'mysecret';
    s3conf.sslEnabled = false;
    s3conf.signatureVersion = 'v4';
}

const s3 = new AWS.S3(s3conf);

console.log(s3);

AWS.config.update({
    region: 'ap-southeast-1'
});

const uploadStorage = function(folderName) {
    return multerS3({
        s3: s3,
        bucket: s3config.S3_BUCKET_NAME,
        acl: 'public-read',
        contentType: multerS3.AUTO_CONTENT_TYPE,
        metadata: function(req, file, cb) {
            cb(null, {
                created: new Date().toString()
            });
        },
        key: function(req, file, cb) {
            cb(null, folderName + '/' + Date.now().toString() + Path.extname(file.originalname));
        }
    });
};

module.exports = uploadStorage;

```

I'm using 
"multer": "^1.2.0",
"multer-s3": "^2.3.2"

Then is use about uploadStorage as

``` js
const s3storage = require('../helpers/multers3')(s3config.IMAGE_FOLDER);

const upload = multer({
    storage: s3storage
});
```

**Comment by harshavardhana** [comment] 2016-09-11 19:21
Perfect thanks a lot @iamchathu

**Comment by krishnasrinivas** [comment] 2016-09-11 20:14
@iamchathu can you comment out the following lines and check:

```
AWS.config.update({
    region: 'ap-southeast-1'
});
```

if it does not work, do the following and check:

```
AWS.config.update({
    region: 'us-east-1'
});
```

**Comment by krishnasrinivas** [comment] 2016-09-11 20:16
`acl: 'public-read',`

Note that minio does not support acls for objects instead it supports bucket policies:
https://docs.minio.io/docs/minio-client-complete-guide#policy

**Comment by iamchathu** [comment] 2016-09-11 20:32
@krishnasrinivas 

I commented 

``` js
acl: 'public-read',
```

and 

``` js
AWS.config.update({
    region: 'ap-southeast-1'
});
```

And updated uncommenting ap-southeast-1 to us-east-1 but still the error stays same.

**Comment by harshavardhana** [comment] 2016-09-11 20:40
> I commented
> 
> acl: 'public-read',
> and
> 
> AWS.config.update({
>     region: 'ap-southeast-1'
> });
> And updated uncommenting ap-southeast-1 to us-east-1 but still the error stays same.

We are validating this locally @iamchathu

**Comment by iamchathu** [comment] 2016-09-11 20:42
@harshavardhana Thank you

**Comment by donatello** [comment] 2016-09-12 00:51
@iamchathu - It appears that your error may be due to a bug in `multer` or `multer-s3`.

Based on your code, I tried the following:

``` js
"use strict";
const multerS3 = require('multer-s3');
const AWS = require('aws-sdk');
const Path = require('path');
const multer = require('multer')
const express = require('express')
// const s3config = require('../config/s3config');

let s3conf = {};
if (process.env.NODE_ENV != 'production') {
    s3conf.endpoint = 'http://127.0.0.1:9000';
    s3conf.s3ForcePathStyle = true;
    s3conf.accessKeyId = 'myaccesskey';
    s3conf.secretAccessKey = 'mysecret';
    s3conf.sslEnabled = false;
    s3conf.signatureVersion = 'v4';
    s3conf.region = 'us-east-1';
    s3conf.logger = console;
    // s3conf.s3DisableBodySigning = false;
}

const s3 = new AWS.S3(s3conf);

//console.log(s3);

// AWS.config.update({
//     region: 'ap-southeast-1'
// });

const uploadStorage = function(folderName) {
    return multerS3({
        s3: s3,
        bucket: 'test1',
        //acl: 'public-read',
        contentType: multerS3.AUTO_CONTENT_TYPE,
        metadata: function(req, file, cb) {
            cb(null, {
                created: new Date().toString()
            });
        },
        key: function(req, file, cb) {
            cb(null, folderName + '/' + Date.now().toString() + Path.extname(file.originalname));
        }
    });
};

// module.exports = uploadStorage;

//Validate S3 Configuration by listing buckets!
s3.listBuckets(function(err, data) {
    if (err) console.log('***FAILURE***:  ', err, err.stack); // an error occurred
    else     console.log('***SUCCESS***:  ', data);           // successful response
});

var app = express();

const upload = multer({
    storage: uploadStorage('/tmp/1')
});

app.post('/upload', upload.single('photos'), function(req, res, next) {
    res.send('Successfully uploaded ' + req.files.length + ' files!');
});

app.listen('3000');

```

When I run it:

``` shell
$ node test.js 
[AWS s3 200 0.041s 0 retries] listBuckets({})
***SUCCESS***:   { Buckets: 
   [ { Name: 'photos',
       CreationDate: Sun Sep 11 2016 10:37:17 GMT-0700 (PDT) } ],
  Owner: { DisplayName: 'minio', ID: 'minio' } }
```

My Minio local instance has just one bucket named photos. So the above output is correct.

The `express` webserver is listening on port 3000 - so now I try a curl:

``` shell
$ curl -v -XPOST http://localhost:3000/upload -F 'userid=1' -F 'photos=@/tmp/1/abc.jpg'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> POST /upload HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 291
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------7381826080741b02
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 259
< Date: Mon, 12 Sep 2016 00:42:53 GMT
< Connection: keep-alive
* HTTP error before end of send, stop sending
< 
Error: connect ECONNREFUSED 127.0.0.1:443<br> &nbsp; &nbsp;at Object.exports._errnoException (util.js:907:11)<br> &nbsp; &nbsp;at exports._exceptionWithHostPort (util.js:930:20)<br> &nbsp; &nbsp;at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
* Closing connection 0
```

This is most likely the same error that you were seeing. 
It appears that `express` wants to connect to port 443 of 127.0.0.1 even though the Minio server is running on port 9000.

The server logs in the meanwhile look like:

``` shell
$ node test.js 
[AWS s3 200 0.041s 0 retries] listBuckets({})
***SUCCESS***:   { Buckets: 
   [ { Name: 'photos',
       CreationDate: Sun Sep 11 2016 10:37:17 GMT-0700 (PDT) } ],
  Owner: { DisplayName: 'minio', ID: 'minio' } }


[AWS s3 404 0.003s 0 retries] headBucket({ Bucket: 'test1' })
[AWS s3 301 0.074s 3 retries] putObject({ Body: <Buffer 61 62 63 0a 31 32 33 0a>,
  Bucket: 'test1',
  Key: '/tmp/1/1473640973483.jpg',
  ACL: 'private',
  CacheControl: null,
  ContentType: 'application/octet-stream',
  Metadata: { created: 'Sun Sep 11 2016 17:42:53 GMT-0700 (PDT)' } })
Error: connect ECONNREFUSED 127.0.0.1:443
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)


```

The problem is not the AWS S3 library or the Minio server, because a simple connection to Minio server using aws-sdk for javascript works fine (the request to listBuckets).

It appears that the cause is in `multer*` libs. Hope this helps.

**Comment by harshavardhana** [comment] 2016-09-15 08:52
Closing this as `multer-s3` package issue, please reopen if this is reported back as Minio server problem.

**Closed as completed by harshavardhana** 2016-09-15 08:52 UTC
Labels: community
