### ISSUE TITLE
change access key deletes files

### ISSUE THREAD

**Issue by HeberArratia** [minio/minio#7790] opened 2019-06-14 16:45 UTC
## Expected Behavior

When changing MINIO_ACCESS_KEY and MINIO_SECRET_KEY, the files that min.io showed me with a previous access configuration disappear.

Is there any way to avoid this behavior? 
I think the archives should be maintained.

## Current Behavior

Files are lost when you modify the keys.

## Context

I'm using docker-compose

## Your Environment

My docker-compose file:

```
minio:
      image: minio/minio
      hostname: minio1
      container_name: minio
      ports:
      - "9000:9000"
      environment:
      - MINIO_ACCESS_KEY=ex123
      - MINIO_SECRET_KEY=example123
      volumes:
      - ~/mnt/data:/data
      - ~/mnt/config:/root/.minio
      networks:
      - backend
      command: server /export
```

**Comment by kannappanr** [comment] 2019-06-14 20:13
@HeberArratia I am not sure what you mean by `Files are lost when you modify the keys.` How do you modify the keys.

Also, in your docker-compose file

```
volumes:
      - ~/mnt/data:/data
```
You are mounting ~/mnt/data to `/data`, but that is not being used as the command uses `/export` directory

**Comment by HeberArratia** [comment] 2019-06-14 20:17
Thanks for your reply @kannappanr 

When I modify the variables MINIO_ACCESS_KEY and MINIO_SECRET_KEY, the files I had stored in min.io are lost

**Comment by harshavardhana** [comment] 2019-06-14 20:19
>       - ~/mnt/config:/root/.minio

You mean here? @HeberArratia - we don't take `config.json` from the config directory anymore. `config.json` resides in the backend. 

```
~ minio server  |grep config-dir
  --config-dir value, -C value  [DEPRECATED] path to legacy configuration directory (default: "/home/harsha/.minio")
```

**Comment by kannappanr** [comment] 2019-06-14 20:19
once you modify, do you do ` docker-compose up` ? If that is the case, it is probably a different instance

**Comment by kannappanr** [comment] 2019-06-14 20:21
If you change `command: server /export` to `command: server /data`, this might work. Once you make this change, you create buckets and object then change the Access and Secret key, then do `docker-compose up`, you should see the buckets and objects

**Comment by HeberArratia** [comment] 2019-06-14 20:30
This works!! Thanks @kannappanr 

I changed `command: server /export` to `command: server /data`

Thank @harshavardhana

**Comment by ebozduman** [comment] 2019-06-14 21:57
Closing. Works as intended.

**Closed as completed by ebozduman** 2019-06-14 21:57 UTC
Labels: working as intended, community
