### ISSUE TITLE
Gateway doesn't encrypt files with SSE_S3

### ISSUE THREAD

**Issue by darkleaf** [minio/minio#11262] opened 2021-01-12 15:02 UTC
I run:
1) Hashicorp Vault
2) KES
3) minio server 
4) minio gateway s3 with "single encryption (at the gateway)"

I want to put files into the gateway and watch encrypted files on the server.

## Expected Behavior

When I put a file on the gateway I expect the file is encrypted on the server.  

## Current Behavior

I put a file on the gateway and get the file being unencrypted on the server and an error.

```
# gateway
Error: Object not found: test/example.pdf/.minio/data/.minio/dare.meta (cmd.ObjectNotFound)
       3: cmd/gateway/s3/gateway-s3-sse.go:389:s3.(*s3EncObjects).DeleteObject()
       2: cmd/gateway/s3/gateway-s3-sse.go:452:s3.(*s3EncObjects).PutObject()
       1: cmd/web-handlers.go:1281:cmd.(*webAPIHandlers).Upload()

# server
Error: remove /Users/mikhail/Projects/dellin/experiments/minio/storage/test/example.pdf/.minio/dare.meta: not a directory (*os.PathError)
       5: cmd/fs-v1-helpers.go:420:cmd.fsDeleteFile()
       4: cmd/fs-v1.go:1322:cmd.(*FSObjects).DeleteObject()
       3: cmd/object-handlers-common.go:292:cmd.deleteObject()
       2: cmd/object-handlers.go:2776:cmd.objectAPIHandlers.DeleteObjectHandler()
       1: net/http/server.go:2042:http.HandlerFunc.ServeHTTP()
```

## Steps to Reproduce (for bugs)

1) Install Vault, KES as described here https://github.com/minio/kes/wiki/Hashicorp-Vault-Keystore
2) run a server
```
MINIO_ROOT_USER=user MINIO_ROOT_PASSWORD=password ./minio server --address=:8000 ./storage
```
3) run a gateway
```
MINIO_ROOT_USER=user MINIO_ROOT_PASSWORD=password \
MINIO_KMS_KES_ENDPOINT=https://127.0.0.1:7373 \
MINIO_KMS_KES_KEY_FILE=app.key \
MINIO_KMS_KES_CERT_FILE=app.cert \
MINIO_KMS_KES_CA_PATH=server.cert \
MINIO_KMS_KES_KEY_NAME=my-app-key \
./minio gateway s3 http://127.0.0.1:8000
```

I also set up  `MINIO_KMS_AUTO_ENCRYPTION=on` and `MINIO_GATEWAY_SSE=s3` but it is useless.

Also, I tried to set up Vault without KES with `MINIO_KMS_VAULT_*` envs as described [here](https://docs.min.io/docs/minio-gateway-for-s3.html) and [here](https://docs.min.io/docs/minio-vault-legacy.html).

## Your Environment

It is reproduced on RELEASE.2020-11-25T22-36-25Z and  RELEASE.2021-01-08T21-18-21Z on native macOS and docker for mac.

Darwin iMac-Mihail.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64 i386 iMac18,3 Darwin

Also, there is no clear guide to install a gateway with encryption.

**Comment by harshavardhana** [comment] 2021-01-12 18:14
Closing as duplicate of #11232

**Closed as completed by harshavardhana** 2021-01-12 18:14 UTC
Labels: community, triage

**Comment by darkleaf** [comment] 2021-01-12 18:40
@harshavardhana please note that it reproduces on RELEASE.2020-11-25T22-36-25Z and #11024 was merged only in December.
