### ISSUE TITLE
upload fails with `Specified Multipart doesn't exist during ` round robin chaos test.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3169] opened 2016-11-03 16:18 UTC
Upload of 1GB object using `mc cp` fails when round robin Chaos test is running. It fails with 
```sh
mc: <ERROR> Failed to copy ‘/root/rao/1gb’. The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.`
```

Here is the [mc debug log](https://play.minio.io:9000/rao/chaos-upload-fail.txt)

The upload worked fine  before the chaos test was underway.

## Expected Behavior

Not to fail when Round robin chaos test is going on.

## Steps to Reproduce (for bugs)

1. Start Chaos test 
  ```sh
./master --endpoints="minio2:9997,minio3:9997,minio4:9997,minio5:9997,minio6:9997,minio7:9997,minio8:9997" -recover=3  -rounds=30
   ``` 
   The setup is ready in test nodes, click [here](https://github.com/minio/chaos) for more info running Minio chaos test.

2. Run upload operation after starting the chaos test.
 ```sh
   mc cp /root/rao/1gb chaos1/rao/ 
 ```

## Context

 Testing Minio's fault tolerance capability using [Minio Chaos](https://github.com/minio/chaos)
## Your Environment
Linux boxes on packet. 8 Node setup.
* Version used: master at e6965ca066973861c923e477cc7df8fce89431dd .

**Comment by harshavardhana** [comment] 2016-11-03 18:27
ping @vadmeste - this looks like the same issue as you reproduced.

**Comment by hackintoshrao** [comment] 2016-11-03 19:03
Further attempts to upload the same file after the chaos test is stopped too is failing,

``` sh
$ mc cp /root/rao/1gb chaos1/rao/ 
mc: <ERROR> Failed to copy ‘/root/rao/1gb’. Object key is missing, object key cannot be empty
```

[Here](https://play.minio.io:9000/rao/chaos-put2.txt) is the mc debug log.

An attempt to upload the same file into a different bucket works.

``` sh
# This works.
$ mc cp /root/rao/1gb chaos1/rao-diff-bucket/ 
```

**Comment by harshavardhana** [comment] 2016-11-03 19:15
This error is wrong 

```
mc: <DEBUG> GET /rao/1gb?max-parts=1000&part-number-marker=0&uploadId=b088ae6c-c84f-4168-a209-1d4b30d5e5c6 HTTP/1.1
Host: minio1:9199
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161103/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161103T185337Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Thu, 03 Nov 2016 18:53:24 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: EMDF2U1ULP92KOEY

f3
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/rao/1gb</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  9.014755ms

[2K
[Amc: <ERROR> Failed to copy ‘/root/rao/1gb’. Object key is missing, object key cannot be empty
 (3) cp-main.go:346 cmd.doCopySession.func1(..) Tags: [/root/rao/1gb]
 (2) cp-main.go:207 cmd.doCopy(..) Tags: [http://minio1:9199/rao/1gb]
 (1) common-methods.go:87 cmd.putTargetStreamFromAlias(..) Tags: [chaos1, http://minio1:9199/rao/1gb]
 (0) client-s3.go:563 cmd.(*s3Client).Put(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:minio-client1.local.lan | OS:linux | Arch:amd64 | Lang:go1.7.1 | Mem:1.4MB/14MB | Heap:1.4MB/10MB
```

**Comment by hackintoshrao** [comment] 2016-11-03 19:24
> This error is wrong . 

@harshavardhana :  I'm getting that error when I'm trying to upload the object which failed during chaos test.

**Comment by donatello** [comment] 2016-11-03 19:41
Yes it's the same issue as #3149. I am able reproduce it. Will work on it.

**Comment by GarimaKapoor** [comment] 2016-11-05 17:16
@donatello can you give the timeline for the fix.

**Comment by donatello** [comment] 2016-11-07 00:24
The reason for this behavior is detailed here - https://github.com/minio/minio/issues/3149#issuecomment-258722816 - in short, the upload to the object will work if you start a new multipart upload.

@GarimaKapoor The reason for the bug is now clear, so this issue could probably closed today or tomorrow based on what we decide to do for it.

**Comment by donatello** [comment] 2016-11-10 22:11
The root cause is the stale upload id on one of the servers. It happens precisely, when a multipart object PUT is completed when a server is down (but was up when the PUT started). This is being handled by cleaning up uploads.json at start-up as @harshavardhana said. 

Additionally `mc` is going to handle this error and start a new upload when the upload id turns out to be stale.

If I didn't miss anything in the summary above, we can close this issue.

**Comment by hackintoshrao** [comment] 2016-11-11 08:37
Does that mean that the fix is in `mc` to handle this differently ?

**Comment by harshavardhana** [comment] 2016-11-11 14:37
No Karthic it will be healing which will fix this during startup of a given server.

**Comment by hackintoshrao** [comment] 2016-11-11 17:02
> it will be healing which will fix this during startup of a given server.

Is it fixed now ? So that I know what to expect .

**Comment by harshavardhana** [comment] 2016-11-11 17:51
> Is it fixed now ? So that I know what to expect .

No it is not fixed yet, will be fixed soon.

**Comment by harshavardhana** [comment] 2016-11-17 06:21
Part of quick healing has been merged fixing of inconsistent `uploads.json` is pending, will take this up.

**Comment by GarimaKapoor** [comment] 2016-11-17 17:19
@harshavardhana is this issue is duplicate of #3176 ?

**Comment by harshavardhana** [comment] 2016-11-17 17:56
No @GarimaKapoor the situations are different. #3176 actually happened on a single node XL setup.

**Comment by GarimaKapoor** [comment] 2016-11-21 19:50
@harshavardhana do we have a fix for this?

**Comment by harshavardhana** [comment] 2016-11-21 19:51
> @harshavardhana do we have a fix for this?

Yes working on it locally..

**Comment by harshavardhana** [comment] 2016-11-22 03:33
This patch is kind of ready but the problem is fundamental it is expensive to heal `uploads.json` as part of quickHeal -  It seems like this belongs to deep healing which we decided to do after this release in a proper healing implementation.

Need further discussion on this.

**Comment by harshavardhana** [comment] 2016-11-22 21:17
This will be fixed when healing is implemented. Moving out of distributed release.

**Comment by GarimaKapoor** [comment] 2016-12-04 21:30
@harshavardhana are we tracking mc admin issue in mc repo. Then we can close this issue.

**Comment by harshavardhana** [comment] 2016-12-04 21:33
> @harshavardhana are we tracking mc admin issue in mc repo. Then we can close this issue.

Yes right now it is listed here so that when the `mc` patches are in it gets automatically closed as reference.

**Comment by harshavardhana** [comment] 2016-12-20 23:06
Closing as duplicate of #3395

**Closed as completed by harshavardhana** 2016-12-20 23:06 UTC
