### ISSUE TITLE
STS LDAP should allow an AD user to login with their username

### ISSUE THREAD

**Issue by timhughes** [minio/minio#9593] opened 2020-05-13 16:09 UTC
## Expected Behavior
When using Active Directory or another LDAP server which does not allow anonymous binds and does not have a DN that contains the users **username**, I would expect to be able to setup minio to allow users to login with their `username` and not have to use something along the lines of their **Firstname Surname**

Authentication against Active Directory should use `sAMAccountName` or `uid` for the 
**username** rather than `cn`.  

Using the ldap test code availavble at https://github.com/minio/minio/blob/master/docs/sts/ldap.go I would expect to be able to use the following command:
```
go run ldap.go -u fry -p fry -sts-ep http://localhost:9000
```
Rather than what is required currently which is 
```
go run ldap.go -u 'Philip J. Fry' -p fry -sts-ep http://localhost:9000
```

## Current Behavior

As far as I can tell, minio sts ldap makes the assumption that the username is
part of the Distinguished Name (DN) in the ldap directory. In many LDAP servers
such as Active Directory (AD) this is not the case. In AD the DN contains the
users `cn` which is a free-form field and commonly like like `Philip J. Fry`
rather than `fry` and therefore the DN looks like 
`cn=Philip J. Fry,ou=people,dc=planetexpress,dc=com`.

## Possible Solution

To get this to work you generally need to have a bind user which can look up the user trying to authenticate. This is because most secure setups of LDAP/AD do not allow anonymous binds. The other way on an AD server is to use the
**username@KERBEROS.REALM** method which in this case could be `fry@PLANETEXPRESS.COM`. I tried this method by making `MINIO_IDENTITY_LDAP_USERNAME_FORMAT=%s@PLANETEXPRESS.COM` and stepped through the code with a debugger but then found that minio used this for the group lookup and I ended up with a `MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER=(&(objectclass\=group)(member\=fry@PLANETEXPRESS.COM))` which is not going to work for group lookups.

## Steps to Reproduce (for bugs)

This uses the docker image from https://github.com/rroemhild/docker-test-openldap and that projects README.md shows the structure of a normal user in a structure similar to AD but you would need to use `uid` instead of `sAMAccountName` 

### Server setup

```shell

docker rm test-ldap
docker run -p 1389:389 -p 1636:636 --name test-ldap --detach rroemhild/test-openldap
docker ps

mkdir -p export/{bucket1,bucket2}
touch export/{bucket1,bucket2}/emptyfile.txt


export MINIO_IDENTITY_LDAP_SERVER_ADDR=localhost:1389
export MINIO_IDENTITY_LDAP_USERNAME_FORMAT=cn\=%s,ou\=people,dc\=planetexpress,dc\=com
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN=dc\=planetexpress,dc\=com
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER=(&(objectclass\=group)(member\=%s))
export MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE=cn
export MINIO_IDENTITY_LDAP_STS_EXPIRY=60h
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
export MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
export MINIO_ACCESS_KEY=minioadmin
export MINIO_SECRET_KEY=minioadmin

minio server ./export
```

### Client setup
```shell

mc config host add myminio http://127.0.0.1:9000 minioadmin minioadmin

cat <<EOF> allaccess.json
{
  "Statement": [
    {
      "Resource": [
        "arn:aws:s3:::*"
      ],
      "Action": [
        "s3:*"
      ],
      "Effect": "Allow"
    }
  ],
  "Version": "2012-10-17"
}
EOF

mc admin policy add myminio allaccess allaccess.json

## Have to set the policy on the value of CN rather than sAMAccountName ##
# mc admin policy set myminio allaccess user=fry
mc admin policy set myminio allaccess user='Philip J. Fry'


go get -v github.com/minio/minio-go
wget https://raw.githubusercontent.com/minio/minio/master/docs/sts/ldap.go

## The following command is what should work ##
# go run ldap.go -u fry -p fry -sts-ep http://localhost:9000
go run ldap.go -u 'Philip J. Fry' -p fry -sts-ep http://localhost:9000
```

## Context
Part of this issue i believe has been fixed on https://github.com/minio/minio/issues/9435. I decided to open a new ticket and try and explain a bit more clearly now that I have a much better understanding of the issue rather than reopen that ticket.

## Your Environment

* Version used (`minio version`): https://github.com/minio/minio/tree/1756b7c6ffbe580cd1708216978f01698b0481c4
* Server type and version: Fedora 32 (Workstation Edition)
* Operating System and version (`uname -a`): Linux localhost 5.6.11-300.fc32.x86_64 #1 SMP Wed May 6 19:12:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jdheyburn** [comment] 2020-06-15 13:33
This looks to be related to #9178 - in that both tickets are requested bind user to perform username logins in AD.

**Comment by harshavardhana** [comment] 2020-06-15 16:02
> This looks to be related to #9178 - in that both tickets are requested bind user to perform username logins in AD.

Yes it is, we may do it in future.

**Comment by jdheyburn** [comment] 2020-07-15 19:14
Still an issue, please do not close

**Comment by harshavardhana** [comment] 2020-07-27 16:00
Closing as duplicate of #10112

**Closed as completed by harshavardhana** 2020-07-27 16:00 UTC
Labels: community, triage

**Comment by timhughes** [comment] 2020-07-27 19:25
Hi @harshavardhana I don't think this is a duplicate of #10112 unless you are fixing both together. This one would be fixed by creating the ability to use a generic bind_user. #10112 looks like an easy win. It just needs the loop to exit with success if any of the patterns are successful rather that fail if any fail.

**Comment by harshavardhana** [comment] 2020-07-27 19:27
> Hi @harshavardhana I don't think this is a duplicate of #10112 unless you are fixing both together. This one would be fixed by creating the ability to use a generic bind_user. #10112 looks like an easy win. It just needs the loop to exit with success if any of the patterns are successful rather that fail if any fail.

It is to consolidate LDAP issues into one, all issues if and when they get fixed will be fixed comprehensively.
