### ISSUE TITLE
Some questions about the design and implementation of disks status monitor in distributed MinIO

### ISSUE THREAD

**Issue by yangwwii** [minio/minio#9254] opened 2020-04-02 06:53 UTC
Hi MinIO experts,
It might be not the right way to ask question by raising issues. Sorry for that. Actually I have some questions about the design and implementation of disks status monitor in distributed MinIO. Looking forward for your reply, thanks.
I’m wondering,
1.	In which way service instances monitor other disks is connected or not?
2.	Does it support all-disk status probe periodically? If yes, how often? If no, what cases will trigger the disk status probe?
3.	while in the file uploading, one of the disk get offline, Will MinIO terminate the upload task to the offline disk intermediately.

**Comment by ebozduman** [comment] 2020-04-08 07:30
Hi @yangwwii 

Disclaimer: Please keep in mind that the following explanations may change in the  near future, since we continuously try to improve our code, if we believe a better/faster way is possible.

 - Question 1. & 2. Each disk keeps its own status in a `Status` field and this field is checked to decide if a disk is online or offline.

 - Question 3. If a disk fails while uploading a file, MinIO continues without changing its course, since MinIO is fault tolerant and the file will be still available. So, everything is going to work as if nothing has happened. 
At the same time, MRF (Most Recently Failed) heal operation is started if the issue is fixable. So, MRF's job is to heal  temporary failures on the spot. However, if it is not possible, that is if the disk is permanently dead, then we don't do anything. 
If the permanently dead disk is replaced at some point with a good one and then if MinIO server is restarted, then user may try to manually heal the data (while the file is still available) on the new disk by using `mc admin heal -r` command.
Otherwise, MinIO fixes these broken pieces in its next periodic full heal run, which happens once every 30 days.

Please don't hesitate to join our general Slack channel and ask your questions there. We are always there to help.

**Comment by ebozduman** [comment] 2020-04-08 07:34
Closing this issue since there is nothing to be fixed.

**Closed as completed by ebozduman** 2020-04-08 07:34 UTC
Labels: working as intended, community
