### ISSUE TITLE
Unexpected behavior when a node shutdown

### ISSUE THREAD

**Issue by kfirfer** [minio/minio#11140] opened 2020-12-19 04:29 UTC
Hello,

Im experiencing Unexpected behavior when I shutting down one node ungracefully

Having 3 kubernetes nodes (k8s version 1.18.13), setup with helm chart version 8.0.8 (latest) ,
The NginX load balancer in front of the pods are round robin
This are the overridden helm chart values I deployed with:

```
accessKey: XXXXXXX
secretKey: XXXXXXX

mode: distributed

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - minio-test.tatzan.com
  tls:
    - hosts:
        - "*.tatzan.com"

drivesPerNode: 2
replicas: 3

persistence:
  size: 10Gi

defaultBucket:
  enabled: true
  name: kfir

resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 2Gi
    cpu: 4000m

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - minio
        topologyKey: "kubernetes.io/hostname"

tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
```

### Test 1:
I tested with shutdown one node, and start it up again 

And the MinIO browser shows this 1/3 of the times : 

![Selection_005](https://user-images.githubusercontent.com/7741545/101996034-988dd800-3cd7-11eb-9f95-0ccd91ee7093.jpg)

Tooks around 2-4 minutes to come back normally (when the shutdown node is up again)

### Test 2:

I tested another situation when I leave one node down without start it up
Refreshing the MinIO file browser and could see 1/2 of times that files are missing:

![Selection_006](https://user-images.githubusercontent.com/7741545/101996647-db9e7a00-3cdc-11eb-9b39-deb29ce46d21.jpg)

![Selection_007](https://user-images.githubusercontent.com/7741545/101996691-de996a80-3cdc-11eb-87dc-a5d18bcd1d02.jpg)

**Comment by harshavardhana** [comment] 2020-12-19 04:33
> ingress:
>   enabled: true
>   annotations:
>     kubernetes.io/ingress.class: nginx
>   hosts:
>     - minio-test.tatzan.com
>   tls:
>     - hosts:
>         - "*.tatzan.com"
> 
> drivesPerNode: 2
> replicas: 3

AFAICS @kfirfer your incorrect ingress configuration is the issue here. You need to add a clusterIP LB behind here such that when the node is shutdown k8s is able to remove them automatically in a matter of 30secs.

**Comment by kfirfer** [comment] 2020-12-19 04:39
@harshavardhana 
I using the chart as is , does it should support that out of the box ?

**Comment by kfirfer** [comment] 2020-12-19 04:41
@harshavardhana 
I tried also with kubctl port-forward direct to the clusterIP service/Pods, same thing...

**Comment by harshavardhana** [comment] 2020-12-19 05:59
Yes this should work fine, it almost looks like @kfirfer a configuration issue. You should look at our MinIO operator https://github.com/minio/operator

**Comment by nitisht** [comment] 2021-01-28 15:49
@kfirfer I tried this locally and can't seem to repro this with latest MinIO release. Can you confirm?

**Comment by harshavardhana** [comment] 2021-01-30 02:00
Closing as possible duplicate of #11239

**Closed as completed by harshavardhana** 2021-01-30 02:00 UTC
Labels: duplicate, community
