### ISSUE TITLE
XL: multipart upload fails when one of source file data is incremental to another

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1593] opened 2016-05-11 06:03 UTC
Steps to reproduce
1. start minio server

```
minio server /mnt/sd{b..i}1/bala/mydisk
```
1. create a bucket

```
mc mb myminio/mybucket
```
1. have two files and one is just incremental content

```
dd if=/dev/zero of=zero100 bs=1M count=100
dd if=/dev/zero of=zero101 bs=1M count=101
```
1. use mc to upload these files like

```
mc zero100 myminio/mybucket/zero& mc zero101 myminio/mybucket/zero&
```

We get

```
mc: <ERROR> Failed to copy ‘zero100’. The specified multipart upload does not exist.
mc: <ERROR> Session safely terminated. To resume session ‘mc session resume cgwvakbv’
```

**Comment by balamurugana** [comment] 2016-05-13 01:10
Top level locking doesn't fix this issue.  It requires deep code check.

**Comment by harshavardhana** [comment] 2016-05-18 02:04
Closing as duplicate of #1624

**Closed as completed by harshavardhana** 2016-05-18 02:04 UTC
