### ISSUE TITLE
New Policy Disappears, expected?

### ISSUE THREAD

**Issue by ghost** [minio/minio#7826] opened 2019-06-25 01:11 UTC
When I follow the guide for creating long term multi-user access I create a policy but then it seems to disappear after a little while. I'm running a distributed cluster.

## Expected Behavior

**FRIST**
sudo mc admin policy list minio
.                   
readonly            
readwrite           
writeonly           

**SECOND**
sudo mc admin policy add minio getonly getonly.json
Added policy `getonly` successfully.

**THIRD**
sudo mc admin policy list minio
readwrite           
writeonly           
.                   
getonly             
readonly

**FOURTH (a little while later**
sudo mc admin policy list minio
readwrite           
writeonly           
.                   
getonly             
readonly

## Current Behavior

**FRIST**
sudo mc admin policy list minio
.                   
readonly            
readwrite           
writeonly           

**SECOND**
sudo mc admin policy add minio getonly getonly.json
Added policy `getonly` successfully.

**THIRD**
sudo mc admin policy list minio
readwrite           
writeonly           
.                   
getonly             
readonly

**FOURTH**
sudo mc admin policy list minio
readwrite           
writeonly           
.                   
readonly 

## Possible Solution

Bug or expected?

## Steps to Reproduce (for bugs)

I just followed the steps on the attached link, and then see stages above.

https://docs.min.io/docs/minio-multi-user-quickstart-guide.html

## Context

I'm trying to setup and test user access so that I don't have to give out the root key

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

Ubuntu 16.04.06 (client and server)
mc version RELEASE.2019-06-12T20-35-20Z
Minio Version 2019-06-11T00:44:33Z (three nodes)

**Comment by harshavardhana** [comment] 2019-06-25 02:54
This is fixed in the latest release @hassbabaie - closing as duplicate of https://github.com/minio/minio/issues/7769

**Closed as completed by harshavardhana** 2019-06-25 02:54 UTC
Labels: community, fixed, triage
