### ISSUE TITLE
Secure every bucket with AccessKey and SecreyKey 

### ISSUE THREAD

**Issue by arikbidny** [minio/minio#5824] opened 2018-04-15 11:38 UTC
1 Accesskey and 1 Secreykey for each bucket problem 

## Expected Behavior
AccessKey and SecreyKey for each bucket

## Current Behavior
Same AccessKey and SecreyKey for all buckets 

## Context
We want to use more secure solution then 1 accesskey and 1 secreykey for all buckets, We want to secure every bucket separately, Is it possible? 
thanks

## Your Environment
* Version used - 2018-04-12T23:41:09Z
* Environment name and version (e.g. nginx 1.9.1): Rhel 7.3
* Operating System and version (`uname -a`): Rhel 7.3

**Comment by nitisht** [comment] 2018-04-15 11:44
@arikbidny right now it is not possible to do so, but we are already working on a solution. You can follow the discussion [here](https://github.com/minio/minio/issues/5305)

**Comment by harshavardhana** [comment] 2018-04-15 15:12
Closing as duplicate of #5305

**Closed as completed by harshavardhana** 2018-04-15 15:12 UTC
