### ISSUE TITLE
Upload folder with files via CyberDuck

### ISSUE THREAD

**Issue by Andrey198** [minio/minio#2846] opened 2016-10-04 11:42 UTC
Good day.

Trying to upload folder with files in it via CyberDuck.
It returns an error: _Object contains unsupported characters. Unsupported characters are '^*|._

In minio console (Windows server) i've got:
_{"cause":"Object name invalid: asf.s#en-us/","level":"error","msg":"Unable to create an object.","time":"2016-10-04T14:36:27+03:00"}_

In this test-case: **asf.s** - already created bucket before downloading. **en-us** - folder to be uploaded. In folder **en-us** i have 1 file.

No unsupported characters in there.

If i connected to Amazon S3, i can upload many folders and many subfolders and no problem with it.

Software: CyberDuck ver. 5.1.0 (20872)
config.json has "region": "us-east-1",

Where is a problem?

p.s. no problems with uploading files separately. Even more than 1 files at once - ok. 

Thanx!

**Comment by Andrey198** [comment] 2016-10-04 13:22
Update: cant create any folder manually from CyberDuck and copy folder with or without files.
CyberDuck tell me about unsupported simbols :-( 
Trying to tune CyberDuck, but no luck at now

**Comment by koolhead17** [comment] 2016-10-04 13:33
hello @Andrey198 is this issue somewhat closer to https://github.com/minio/minio/issues/2551?
thanks again.

**Comment by Andrey198** [comment] 2016-10-04 14:09
somewhat closer, but I dont need to move to Minio empty folders. My folders are more than zero-bytes

And I can put non-zero folders to minio like this (with mc):

_C:\minio>mc cp --recursive boot myminio/test
...otres.dll:  17.10 MB / 17.10 MB [=====================] 100.00% 2.27 MB/s 7s_

Am I right: CyberDuck when puts folder with files, before start transfer, try to create empty folder and then get an error?

**Comment by Andrey198** [comment] 2016-10-04 14:29
If so, then U need to correct this instruction https://docs.minio.io/docs/how-to-use-cyberduck-with-minio 
Or write about this issue: cant create folders in exisisting bucket from CyberDuck

Why _cp -recursive_ is working?

p.s.  CyberDuck can create new buckets as well.

**Comment by harshavardhana** [comment] 2016-10-04 15:40
> Why cp -recursive is working?

Cyberduck's problem is that it tries to create a directory before it starts uploading file. On Minio we don't support such type of objects. 

'mc' handles this transparently by directly creating the object and handles the path translation properly.

**Comment by Andrey198** [comment] 2016-10-05 06:30
> On Minio we don't support such type of objects

Do U plan to support this scenario for Minio? If so, when?

Thanx again.

**Comment by harshavardhana** [comment] 2016-10-05 09:16
> Do U plan to support this scenario for Minio? If so, when?

We don't plan to support this type of behavior in near future.

**Comment by harshavardhana** [comment] 2016-10-09 02:08
> Do U plan to support this scenario for Minio? If so, when?

Looking at a way to fix this in Cyberduck transparently.

**Comment by harshavardhana** [comment] 2016-10-09 02:12
Closing this as duplicate of  #2551

**Closed as completed by harshavardhana** 2016-10-09 02:12 UTC
Labels: community
