### ISSUE TITLE
[distributed] mc mirror failed

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2522] opened 2016-08-22 13:31 UTC
did `mc mirror go/src myminio/testbucket`

after certain amount of inactivity did `mc mirror go/src myminio/testbucket` again which gave:

```
krishna@escape:~$ mc mirror go/src myminio/testbucket
mc: <ERROR> Failed on 'http://127.0.0.1:9000/testbucket/' The specified bucket does not exist
krishna@escape:~$
```

http dump:

```
---------------------------
REQUEST : GET path:/testbucket/?max-keys=1000
Host: 127.0.0.1:9000
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160822T132651Z
Accept-Encoding: gzip
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=SXO8VW2OFKKP2OG7AC85/20160822/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=d703bf0b65b5cca3a61854d25f597c3498b2c585d3c59cd82535cf8966f66e89
Expect: 100-continue


-----
RESPONSE STATUS: 404 Not Found
Date: Mon, 22 Aug 2016 13:26:51 GMT
Content-Type: text/xml; charset=utf-8
Accept-Ranges: bytes
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: SIBW9CSXUVE5CGPI

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key></Key><BucketName></BucketName><Resource>/testbucket/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
--------------------------

```

I did `krishna@escape:~$ mc mirror go/src myminio/testbucket` again which worked this time.

**Comment by krishnasrinivas** [comment] 2016-08-22 13:32
server logs:

```
ERRO[1151] Unable to list objects.                       cause=connection is shut down
ERRO[1152] Stat failed on bucket testbucket.             cause=connection is shut down
ERRO[1152] Unable to list objects.                       cause=Bucket not found: testbucket

```

**Comment by harshavardhana** [comment] 2016-08-22 17:55
Closing this as duplicate of https://github.com/minio/minio/issues/2501

**Closed as completed by harshavardhana** 2016-08-22 17:55 UTC
