### ISSUE TITLE
Events not deleted in postgres with format="namespace"

### ISSUE THREAD

**Issue by eco-minio** [minio/minio#10554] opened 2020-09-23 23:55 UTC
When deleting objects from a bucket, event count in postgres does not reflect amount of objects in bucket
## Expected Behavior
Database notification events should be equal to objects in bucket

## Current Behavior
Sporadically events dangle in database

## Possible Solution
unknown

## Steps to Reproduce (for bugs)
1. Start postgres - `docker run -ti --rm -p 5432:5432 -e POSTGRES_PASSWORD=minio123 --name postgres2 postgres `
2. Create "minio_events" table
3. Start clean minio instance MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio server /tmp/pg{1...4} 
4.Configure notifcations to postgres per https://docs.minio.io/docs/minio-bucket-notification-guide.html#PostgreSQL
```
mc admin config set min notify_postgres:1 enable=on connection_string="host=localhost port=5432 dbname=minio_events user=postgres password=minio123 sslmode=disable" table="bucketevents" format="namespace"
mc admin restart min
mc event add min/ion arn:minio:sqs::1:postgresql
mc event list min/ion
arn:minio:sqs::1:postgresql   s3:ObjectCreated:*,s3:ObjectRemoved:*,s3:ObjectAccessed:*   Filter: 
```
Upload 1000 objects in bucket

Check event count in postgres
```
SELECT COUNT(*) FROM bucketevents;
 count 
-------
  1000
```
Delete objects from bucket, check postgres again
```
SELECT COUNT(*) FROM bucketevents;
 count 
-------
     2

SELECT * FROM bucketevents;
 ion/344.file | {"Records": [{"s3": {"bucket": {"arn": "arn:aws:s3:::ion", "name": "ion", "ownerIdentity": {"principalId": "minio"}}, "object": {"key": "344.file", "eTag": "c954525e95c2fe9e10d64d625618a394", "size": 26, "sequencer": "16378E0C617351F3", "contentType": "application/octet-stream", "userMetadata": {"content-type": "application/octet-stream"}}, "configurationId": "Config", "s3SchemaVersion": "1.0"}, "source": {"host": "127.0.0.1", "port": "", "userAgent": "MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-18T00:13:21Z"}, "awsRegion": "", "eventName": "s3:ObjectAccessed:Head", "eventTime": "2020-09-23T23:39:36.379Z", "eventSource": "minio:s3", "eventVersion": "2.0", "userIdentity": {"principalId": "minio"}, "responseElements": {"content-length": "26", "x-amz-request-id": "16378E0C615DB787", "x-minio-deployment-id": "b479cd7b-1062-4234-8e68-10ca39184f45", "x-minio-origin-endpoint": "http://<localip>:9000"}, "requestParameters": {"region": "", "accessKey": "minio", "sourceIPAddress": "127.0.0.1"}}]}
 ion/450.file | {"Records": [{"s3": {"bucket": {"arn": "arn:aws:s3:::ion", "name": "ion", "ownerIdentity": {"principalId": "minio"}}, "object": {"key": "450.file", "eTag": "c954525e95c2fe9e10d64d625618a394", "size": 26, "sequencer": "16378E0C8793FAD1", "contentType": "application/octet-stream", "userMetadata": {"content-type": "application/octet-stream"}}, "configurationId": "Config", "s3SchemaVersion": "1.0"}, "source": {"host": "127.0.0.1", "port": "", "userAgent": "MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-18T00:13:21Z"}, "awsRegion": "", "eventName": "s3:ObjectAccessed:Head", "eventTime": "2020-09-23T23:39:37.018Z", "eventSource": "minio:s3", "eventVersion": "2.0", "userIdentity": {"principalId": "minio"}, "responseElements": {"content-length": "26", "x-amz-request-id": "16378E0C8783EBE1", "x-minio-deployment-id": "b479cd7b-1062-4234-8e68-10ca39184f45", "x-minio-origin-endpoint": "http://<local ip>:9000"}, "requestParameters": {"region": "", "accessKey": "minio", "sourceIPAddress": "127.0.0.1"}}]}
```
mc ls confirms no objects in bucket
## Context
Reported by community today

## Regression
AFAIK yes

## Your Environment

* Version used (`minio --version`): 
minio version RELEASE.2020-09-23T19-18-30Z
* Server setup and configuration:
Single node EC per repro steps above
* Operating System and version (`uname -a`):
Ubuntu 20.04, postgres in docker container was latest

**Comment by harshavardhana** [comment] 2020-09-23 23:58
Closing as duplicate of #10553

**Closed as completed by harshavardhana** 2020-09-23 23:58 UTC
Labels: duplicate, community
