### ISSUE TITLE
On Ubuntu 16.04, Minio service falis to start - tls: bad certificate error

### ISSUE THREAD

**Issue by finid** [minio/minio#5098] opened 2017-10-21 22:02 UTC
## Expected Behavior
After setting up Minio with a Let's Encrypt certificate, the service should start successfully.

## Current Behavior
Instead, Minio fails to start, giving out the following error:

```
level=error msg="Error in reading from new TLS connection local-ip:52096 at server remote-ip:9000" cause="remote error: tls: bad certificate" source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
```

## Steps to Reproduce (for bugs)

1. install Minio 
2. Correctly configured Minio as a systemd service
3. Here's my `/etc/default/minio` file

```
MINIO_ACCESS_KEY=TBBAWH1L
MINIO_SECRET_KEY=Ll7RnfS47ggv JG CtjSafuZv3xuY1X
MINIO_VOLUMES="/mnt/minio-m-nyc1-01/store-m"
MINIO_OPTS="-C /etc/minio --address ip-address:443"
```
4. Set up a domain with a Let's Encrypt certificate. The certificate files have been copied to `/etc/minio/certs` either as `public.crt` and `private.key` or `fullchain.pem` and `privkey.pem`. Same error in either case.

## Context
Trying to set up Minio so I could access it from A browser via HTTPS. 

## Your Environment

* Version used (`minio version`): 2017-09-29T19:16:56Z
* Server type and version:
* Operating System and version (`uname -a`): Ubuntu 16.04

**Comment by vadmeste** [comment] 2017-10-21 23:27
hey @finid.

Does your browser show any message/warning ?

**Comment by harshavardhana** [comment] 2017-10-21 23:33
> level=error msg="Error in reading from new TLS connection local-ip:52096 at server remote-ip:9000" cause="remote error: tls: bad certificate" source="[listener.go:188:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"

This most probably happens because. 

```go
		if len(certMsg.certificates) == 0 {
  			// The client didn't actually send a certificate
  			switch c.config.ClientAuth {
  			case RequireAnyClientCert, RequireAndVerifyClientCert:
  				c.sendAlert(alertBadCertificate)
  				return errors.New("tls: client didn't provide a certificate")
  			}
  		}
```

Client perhaps didn't send certificate.

**Comment by vadmeste** [comment] 2017-10-21 23:46
@harshavardhana, I think this is a regular error, not a bug.. 

Most likely the client didn't like the certificate sent by the server. 

I was able to reproduce this easily: I tried to access to the server using a domain name different to the one registered in the letsencrypt certificate.

**Comment by harshavardhana** [comment] 2017-11-30 17:58
This is an expected behavior, closing. Client doesn't have the right certificates.

**Comment by vadmeste** [comment] 2017-11-30 17:58
:+1:

**Closed as completed by harshavardhana** 2017-11-30 17:58 UTC
Labels: working as intended, priority: medium
