### ISSUE TITLE
Recommend a better encryption scheme

### ISSUE THREAD

**Issue by Kung-Fu-Master** [minio/minio#12324] opened 2021-05-19 08:00 UTC
It's better to use the standard HKDF to run a key-derivation algorithm to generate the KEK(Key Encryption Key). Adding two components (counter, length) in key derivation is a well-established crypto BKM for KDFs ensuring robust domain separation for keys and it will help to reliably (even if RNG fails/under attacker's control) separate keys if/when MinIO needs to derive several keys of same/different lengths for a given bucket/path.

HKDF reference link: https://tools.ietf.org/html/rfc5869

**Comment by klauspost** [comment] 2021-05-19 08:02
Duplicate of #12323 - please edit that instead.

**Closed as completed by klauspost** 2021-05-19 08:02 UTC
Labels: duplicate, community, triage
