### ISSUE TITLE
Can't create user from minio console

### ISSUE THREAD

**Issue by LowcaPromocji** [minio/minio#12869] opened 2021-08-04 09:03 UTC
Can't create user from minio console logged by SSO with admin IAM policy.
## Expected Behavior

User should be created

## Current Behavior

![obraz](https://user-images.githubusercontent.com/9919079/128153048-0b312843-8b2c-4178-8c2f-7b2f30bd1d4b.png)
Logs:
`
original error -> (admin_users.go:52: Access Denied.)
`

## Steps to Reproduce (for bugs)

1. Version used RELEASE.2021-07-27T02-40-15Z
2. SSO configured
3. Admin policy added:
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "admin:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
`
4. User logged with admin policy can create groups, buckets etc but not users.

## Your Environment
Minio version RELEASE.2021-07-27T02-40-15Z, docker container used.

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by LowcaPromocji** [comment] 2021-08-04 09:06
What's more, is there a possibility to create Service Accounts from mc for SSO users? MC returns me error like this:
`./mc.exe admin user svcacct add --access-key XXXXXXXXXXX --secret-key YYYYYYYYYYYY myminio admin_sso_user`

`mc.exe: <ERROR> Unable to add a new service account. The specified user does not exist. (Specified user does not exist).`

**Comment by ravindk89** [comment] 2021-08-04 14:47
>  minio console logged by SSO with admin IAM policy.

By this do you mean you have your MinIO deployment set up to use an external identity provider?

**Comment by harshavardhana** [comment] 2021-08-05 05:31
There isn't much information go to around here.. no indication of what SSO was used no settings etc.

If SSO is enabled only service accounts can be created, no users. Since users are in SSO not on MinIO.

This may be an UI issue.

**Comment by kannappanr** [comment] 2021-08-12 20:46
@LowcaPromocji We do not have enough information to reproduce the issue. What is the SSO being used here? Please provide exact information for us to reproduce the issue.

**Comment by harshavardhana** [comment] 2021-08-12 21:36
> @LowcaPromocji We do not have enough information to reproduce the issue. What is the SSO being used here? Please provide exact information for us to reproduced the issue.

Lets close this @kannappanr - revisit when there is enough data.

**Closed as completed by harshavardhana** 2021-08-12 21:36 UTC
Labels: community, incomplete info
