### ISSUE TITLE
minio client hangs on certain buckets after certain operations

### ISSUE THREAD

**Issue by kannappanr** [minio/minio#5023] opened 2017-10-05 22:09 UTC
When you do a combination of "mc find watch" on one terminal and "mc cp" on another, mc hangs on certain commands on the bucket where this operation was performed.

## Expected Behavior
At any given point, mc cp and ls command should not hang on any bucket

## Current Behavior
Once the server gets into this state, mc cp and mc ls commands hang on those buckets, on which these operations were performed.

From then on, whenever you do a mc cp onto any other bucket on the server, that also starts exhibiting the same behavior.

## Steps to Reproduce (for bugs)
Environment: Connecting to my local Minio server

Bucket Name: ``` test ```
Bucket  has the following files
```
datafile-100-kB
datafile-11-MB
datafile-33-kB
datafile-6-MB
datafile-1.03-MB
datafile-1-b
datafile-5-MB
listfiles.go
datafile-10-kB
datafile-1-MB
datafile-65-MB
list.go
listfiles.go
```
____________________________________________
On terminal 1
enter the following command
```
mc find myminio/test --watch
```
You should only see
```
/test/datafile-1-MB
```
Now keep pressing Ctrl +C, until it displays the last file
```
/test/datafile-1-MB
^C
/test/datafile-1-b
^C
/test/datafile-1.03-MB
^C
/test/datafile-10-kB
^C
/test/datafile-100-kB
^C
/test/datafile-11-MB
^C
/test/datafile-33-kB
^C
/test/datafile-5-MB
^C
/test/datafile-6-MB
^C
/test/datafile-65-MB
^C
/test/list.go
^C
/test/listfiles.go
```

At this point on Terminal 2, enter the following command
```
mc cp list.go myminio/test
```
on Terminal 1, you should see this
```
panic: close of closed channel

goroutine 40 [running]:
github.com/minio/mc/cmd.(*watchObject).Close(0xc4202a49e0)
	/home/test/gopath/src/github.com/minio/mc/cmd/watch.go:84 +0x2f
github.com/minio/mc/cmd.(*s3Client).Watch.func2(0xc4202a49e0, 0xc4202b0f00, 0xc4202b0de0, 0xc42030f060, 0xc4202b0d80)
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:495 +0xc9a
created by github.com/minio/mc/cmd.(*s3Client).Watch
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:495 +0x90e
```

-------------------------------------
On terminal 1, enter the following command
```
mc find myminio/test --watch
```
you should see
```
/test/datafile-1-MB
```
now, on terminal 2, enter the following command multiple times

```
mc cp list.go myminio/test
```
on the first terminal you will see
```
/test/datafile-1-MB
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
^C
/test/datafile-1-b
panic: send on closed channel
	panic: close of closed channel

goroutine 5 [running]:
github.com/minio/mc/cmd.(*watchObject).Close(0xc42000c4c0)
	/home/test/gopath/src/github.com/minio/mc/cmd/watch.go:84 +0x2f
panic(0x8aa440, 0xc42032cac0)
	/home/test/go/src/runtime/panic.go:489 +0x2cf
github.com/minio/mc/cmd.(*s3Client).Watch.func2(0xc42000c4c0, 0xc42001a2a0, 0xc42001a180, 0xc4202f19a0, 0xc42001a120)
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:461 +0x964
created by github.com/minio/mc/cmd.(*s3Client).Watch
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:495 +0x90e

```
------------------------
on terminal 1, enter the following command 
```
mc find myminio/test --watch
```
you should see
```
/test/datafile-1-MB
```
now, on terminal 2, enter the following command multiple times

on the first terminal you will see
```
/test/datafile-1-MB
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
myminiomyminio/test/list.go
```
Basically, for every single mc cp on terminal 2, now you will start seeing multiple lines being displayed on terminal 1. This is an indication that something is wrong in the server.

now press Ctrl +C on terminal 1

you should see
```
/test/datafile-1-b
```
on terminal 2, enter the following command
```
mc cp list.go myminio/test
```
you will see the following panic on terminal 1
```
panic: send on closed channel
	panic: close of closed channel

goroutine 37 [running]:
github.com/minio/mc/cmd.(*watchObject).Close(0xc4202ed920)
	/home/test/gopath/src/github.com/minio/mc/cmd/watch.go:84 +0x2f
panic(0x8aa440, 0xc42035e500)
	/home/test/go/src/runtime/panic.go:489 +0x2cf
github.com/minio/mc/cmd.(*s3Client).Watch.func2(0xc4202ed920, 0xc4202c9560, 0xc4202c9440, 0xc4202ed560, 0xc4202c93e0)
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:461 +0x964
created by github.com/minio/mc/cmd.(*s3Client).Watch
	/home/test/gopath/src/github.com/minio/mc/cmd/client-s3.go:495 +0x90e
```

-------------------

Now on terminal 1, enter the following command

```
mc find myminio/test --watch
```
```
/test/datafile-1-MB
```
press Ctrl + C again

On terminal 2, enter the mc cp command again

Now the cp command should hang

press Ctrl + C on terminal 2 

On terminal 3, enter 
```
mc ls myminio/test 
```
you should see the command hang

## Your Environment

* Version used (`minio version`): 2017-09-29T19:16:56Z
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Linux ubuntu-ltp 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by kannappanr** [comment] 2017-10-05 22:11
[output-from first failure.txt](https://github.com/minio/minio/files/1361005/output-from.first.failure.txt)
Attached is the output seen on the server during one of the failure reproduction iteration.

**Comment by kannappanr** [comment] 2017-10-06 22:39
[run_log.txt](https://github.com/minio/minio/files/1364053/run_log.txt)
Attached is the output from a different reproduction of the issue.

**Comment by krisis** [comment] 2017-10-07 00:12
Root cause:
The server side implementation of ListenBucketNotification uses channels to send notification events from the origin of the event like PutObject to the ListenBucketHandler (used by `mc find --watch` internally). The channels are stored in a map which is protected by a mutex. ListenBucketHandler does the following when a client closes connection.
- sendBucketNotification returns immediately after a failed write (over HTTP). This means we have a channel that has a sender with no receiver
- removes reference to the channel from the map
- closes the channel.

On the other hand, a concurrent PutObjectHandler does the following,
- send notification event on channels read from the map (note: this is inside the critical section)
- release the namespace mutex lock

In this scenario, PutObjectHandler is blocked, holding the mutex protecting the map of channels and the namespace mutex since the channels used to send notification is blocked (remember, it has no receiver).

This will be fixed in two phases. For immediate relief, we will fix it by making the send over the channel non-blocking. Subsequently, we need to remove the intermediary channels and directly send notification over the underlying http.ResponseWriter object.

**Closed as completed** 2017-11-16 18:56 UTC
Labels: priority: high
