### ISSUE TITLE
upgrade from RELEASE.2020-10-03T02-19-42Z to RELEASE.2020-12-10T01-54-29Z

### ISSUE THREAD

**Issue by alizaya** [minio/minio#11085] opened 2020-12-11 15:28 UTC
## Expected Behavior
I want to upgrade the minion because of an error that I think is a bug and that was the cached files cant be deleted and I have to restart nodes to delete cached files. so I decided to upgrade maybe solve this but when I upgrade minio with docker tag I got an error
`Error: Marking http://minio2:9000/minio/storage/minio3/v22 temporary offline; caused by Post "http://minio2:9000/minio/storage/minio3/v22/checkfile?disk-id=72022524-9a4f-491e-9243-1aac6027fa0a&file-path=users&volume=public": net/http: timeout awaiting response headers (*fmt.wrapError)
`
my environment is minio clusters with 3 nodes and 3 disks in them.
another question , is minio alright with odd nodes?

**Comment by klauspost** [comment] 2020-12-11 15:54
This is a network error where "minio2" cannot be reached. Maybe check if your network setup stable.

**Comment by alizaya** [comment] 2020-12-11 19:14
yes it is stable.

**Comment by harshavardhana** [comment] 2020-12-15 05:20
@alizaya most probably the issue is due to healing taking long time to restart - you should try latest master

**Comment by harshavardhana** [comment] 2020-12-15 19:19
Fixed in #11097 #11098

**Closed as completed by harshavardhana** 2020-12-15 19:19 UTC
Labels: community, fixed
