### ISSUE TITLE
xl:  'mc ls' results in 500 internal server error

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1451] opened 2016-05-02 08:27 UTC
- `mc mb myminio/test/` 
- `mc cp a.sh myminio/test/`

The XL setup has 5 data and parity disks 

Now deleting the folder corresponding to the file `a.sh` on disks containing the parity. 
- `rm -r /mnt/sd[g-k]1/ec-dir/test/a.sh/` (sdg1-sdk1 contains parity files)

Now do 
-  `mc ls myminio/test/`

It throws `500 internal server error` 

Here is something more interesting, 
Copy one more file to the same bucket. 
-  `mc cp b.sh myminio/test/`
  Now do 
-  `mc ls myminio/test/`
  This works and you get both the files 
  `a.sh`
  
  `b.sh` 

but if you try 
-  `mc ls myminio/test/a.sh`

It again throws `500 internal server error`. 

On trying 
- `mc cp -r myminio/smalltest/ /tmp/`

It fails with 
`mc: <ERROR> Failed to copy ‘http://localhost:9000/smalltest/a.sh’. The specified key does not exist.`

**Comment by harshavardhana** [comment] 2016-05-03 23:44
> Here is something more interesting, 
> Copy one more file to the same bucket.
> 
> mc cp b.sh myminio/test/ Now do
> mc ls myminio/test/
> This works and you get both the files 
> a.sh
> 
> b.sh

The problem is that list errors out simply because of errors i.e for example  

`b.sh` is valid since it has all the parts the success err == nil nullifies the previous err != nil for `a.sh` - this is unexpected, unreadable files shouldn't be listed at all that is the bug. 

-- Harsha

**Comment by harshavardhana** [comment] 2016-05-05 21:00
fixed by #1491

**Closed as completed by harshavardhana** 2016-05-05 21:00 UTC
