### ISSUE TITLE
[distributed] Too many go routines in Sleep during chaos test with exec-concurrent load.

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#3299] opened 2016-11-21 04:40 UTC
- During chaos test with the load of `time ./exec-concurrent TestGetObjectSeekEnd` at a concurrency of 50, too many go routines are left behind in sleep state.

## Expected Behavior

- The number of Go routines alive the system shouldn't increase significantly with each run of the test.
- Shouldn't leave behind  go routines in sleep state after the test. It increases almost linearly with run.

## Current Behavior

- During chaos test with the load of `time ./exec-concurrent TestGetOjectSeekEnd` at a concurrency of 50, too many go routines are left behind in sleep state.
- There are originating from `dsync`. 
- Here is the link of the final stack strace from the server. 
- $grep sleep final-stack-trace.log | wc -l
   ```
    172 
   ```
- Most of them continue to sleep for a long time. 
  ` $ grep sleep final-stack-trace.log`
   ```
   goroutine 454962 [sleep, 28 minutes]:
   goroutine 96025 [sleep, 31 minutes]:
   goroutine 1192901 [sleep, 26 minutes]:
   goroutine 134673 [sleep, 31 minutes]:
   goroutine 453734 [sleep, 28 minutes]:
   goroutine 454728 [sleep, 28 minutes]:
   goroutine 148438 [sleep, 31 minutes]:
   goroutine 1199861 [sleep, 26 minutes]:
   goroutine 213224 [sleep, 28 minutes]:
   goroutine 77019 [sleep, 31 minutes]:
   goroutine 95842 [sleep, 31 minutes]:
   goroutine 213765 [sleep, 28 minutes]:
   goroutine 96523 [sleep, 31 minutes]:
   goroutine 150642 [sleep, 31 minutes]:
   goroutine 1200500 [sleep, 26 minutes]:
   goroutine 1200532 [sleep, 26 minutes]:
   goroutine 150565 [sleep, 31 minutes]:
   goroutine 150422 [sleep, 31 minutes]:
   goroutine 1195415 [sleep, 26 minutes]:
   goroutine 454258 [sleep, 28 minutes]:
   goroutine 96400 [sleep, 31 minutes]:
   goroutine 82412 [sleep, 31 minutes]:
   goroutine 150502 [sleep, 31 minutes]:
   goroutine 213917 [sleep, 28 minutes]:
   goroutine 456229 [sleep, 28 minutes]:
   goroutine 96026 [sleep, 31 minutes]:
   goroutine 213744 [sleep, 28 minutes]:
   goroutine 96498 [sleep, 31 minutes]:
   goroutine 1381700 [sleep, 26 minutes]:
   goroutine 213766 [sleep, 28 minutes]:
   goroutine 604545 [sleep, 28 minutes]:
   goroutine 453920 [sleep, 28 minutes]:
   goroutine 1195560 [sleep, 26 minutes]:
   goroutine 1371061 [sleep, 26 minutes]:
   goroutine 604099 [sleep, 28 minutes]:
   goroutine 1365561 [sleep, 26 minutes]:
   goroutine 213599 [sleep, 28 minutes]:
   goroutine 213645 [sleep, 28 minutes]:
   goroutine 1200606 [sleep, 26 minutes]:
   goroutine 589740 [sleep, 28 minutes]:
   goroutine 1371644 [sleep, 26 minutes]:
   goroutine 1302257 [sleep, 26 minutes]:
   goroutine 604482 [sleep, 28 minutes]:
   goroutine 606268 [sleep, 28 minutes]:
   goroutine 604653 [sleep, 28 minutes]:
   goroutine 454186 [sleep, 28 minutes]:
   goroutine 606289 [sleep, 28 minutes]:
   goroutine 1370812 [sleep, 26 minutes]:
   goroutine 454821 [sleep, 28 minutes]:
   goroutine 1381864 [sleep, 26 minutes]:
   goroutine 1198621 [sleep, 26 minutes]:
    ```
- With almost 10 runs of the test the number of go routines in the system increases to over 500.
- Here is the [link](https://play.minio.io/rao/3299/final-stack-trace.log) to the final stack trace.
## Steps to Reproduce (for bugs)

1. Set up 8 node distributed Minio.
2.  Run chaos test on the 7 nodes, 
     `./master --endpoints="minio2:9997,minio3:9997,minio4:9997,minio5:9997,minio6:9997,minio7:9997,minio8:9997" -start-minio -recover=1  -rounds=10 -minio-port=9199`

3. Run `exec-concurrent TestGetOjectSeekEnd` test. [Click here](https://github.com/minio/perftest/tree/master/exec-concurrent) for more info on exec-concurrent tests.

## Context

- Chaos test with exec-concurrent load.
## Your Environment

* Version used: Latest master at 0b9f0d14a193961c87e2950dd439648de36fb651

**Comment by harshavardhana** [comment] 2016-11-21 04:42
Ping @krisis - are you taking this as well since ReadAt related bug is assigned to you.

**Comment by krisis** [comment] 2016-11-21 05:19
@harshavardhana yes, I will be working with @hackintoshrao to recreate this issue.

**Comment by hackintoshrao** [comment] 2016-11-21 06:18
Similar issues with `./exec-concurrent TestGetObjectClosedTwice` test too, 

- [Here](https://play.minio.io:9000/rao/final-stack-trace-1.log) is the complete stack trace.
- Following is the highlights of the stack trace.
    -  ```sh
        $ grep "dsync" final-stack-trace.log | wc -l
         1256
       ```
   -  ```sh
        $ grep "sleep" final-stack-trace.log | wc -l
         290
       ```
    -  ```sh
        $ grep "sendRelease" final-stack-trace.log | wc -l
         578
       ```

**Comment by hackintoshrao** [comment] 2016-11-22 17:34
- The issue is currently not seen with `./exec-concurrent TestGetObjectSeekEnd`.
- It can be seen with `./exec-concurrent TestGetObjectClosedTwice` and atleast one node should be going up/down. 
- Also `./exec-concurrent  TestGetObjectClosedTwice` hangs if any one of the node is going up/down.

**Comment by harshavardhana** [comment] 2016-11-23 06:42
Moving this out of distributed release as decided..

**Comment by krisis** [comment] 2016-11-28 11:36
With fix (https://github.com/minio/dsync/pull/34) in dsync, this issue was not reproducible as described. The test case executed using exec-concurrent binary were killed by OOM killer. Minio server was not hung and responded to chaos-test's health check, start and stop actions. Fixing excessive memory consumption of exec-concurrent tests is a separate issue.

**Closed as completed** 2016-11-29 07:03 UTC
