### ISSUE TITLE
RequestTimeout for s3.DeleteMultipleObjects

### ISSUE THREAD

**Issue by furkalor** [minio/minio#10750] opened 2020-10-24 09:40 UTC
RequestTimeout: A timeout occurred while trying to lock a resource, please reduce your request ratedata/events-compact/accounts__XLDIR__
## Expected Behavior

Objects should be deleted within several milliseconds
## Current Behavior

A timeout occurred while trying to lock a resource
## Steps to Reproduce (for bugs)

The problem appears unexpectedly

## Context

20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "POST /dataplatform/?delete HTTP/1.1[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Host: minio-dev.minio.local:44344[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "amz-sdk-invocation-id: 20c7946b-5336-3222-66b1-96e6e579a8a4[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "amz-sdk-retry: 1/15/495[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Authorization: AWS4-HMAC-SHA256 Credential=dataplatform/20201023/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=b576feecda96c07c2a91ed7ea8db9a44d104a44859067913ec5302768e355a96[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Content-MD5: 7/IOpBaZnuCQ4N0tbaYJPg==[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Content-Type: application/xml[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "User-Agent: Hadoop 3.3.0, aws-sdk-java/1.11.750 Linux/4.15.0-88-generic OpenJDK_64-Bit_Server_VM/25.265-b01 java/1.8.0_265 scala/2.11.12 vendor/Oracle_Corporation[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "X-Amz-Date: 20201023T125239Z[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Content-Length: 466[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "Connection: Keep-Alive[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "[\r][\n]"
20/10/23 12:52:39 DEBUG wire: http-outgoing-2 >> "truedata/events-compact/accounts/y=2020/m=10/d=22/_temporary/data/events-compact/accounts/y=2020/m=10/d=22/data/events-compact/accounts/y=2020/m=10/data/events-compact/accounts/y=2020/data/events-compact/accounts/data/events-compact/data/"

01:28:42.776 [200 OK] s3.DeleteMultipleObjects minio-dev.softswiss.net:44344/dataplatform/?delete 116.202.236.210 5m0.542663s ↑ 563 B ↓ 598 B

{
"deploymentid": "dd9e7396-a828-4e6c-bb79-83c64ecc8b7c",
"level": "ERROR",
"errKind": "MINIO",
"time": "2020-10-23T17:47:20.82458902Z",
"api": {
"name": "NetOBDInfo",
"args": {}
},
"remotehost": "10.0.1.3",
"host": "minio-dev-3.minio.local:4433",
"requestID": "1640B03A14195E26",
"userAgent": "Go-http-client/2.0",
"error": {
"message": "stream error: stream ID 1; CANCEL",
"source": [
"cmd/peer-rest-server.go:425:cmd.(*peerRESTServer).NetOBDInfoHandler()",
"net/http/server.go:2042:http.HandlerFunc.ServeHTTP()"
]
}
}
## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-10-18T21-54-12Z
* Server setup and configuration: 

* * ●  minio-dev-2.minio.local:4433
   Uptime: 3 days 
   Version: 2020-10-18T21:54:12Z
   Network: 3/3 OK 
   Drives: 4/4 OK 

* * ●  minio-dev-3.minio.local:4433
   Uptime: 3 days 
   Version: 2020-10-18T21:54:12Z
   Network: 3/3 OK 
   Drives: 4/4 OK 

* * ●  minio-dev-1.minio.local:4433
   Uptime: 3 days 
   Version: 2020-10-18T21:54:12Z
   Network: 3/3 OK 
   Drives: 4/4 OK 

1.0 TiB Used, 7 Buckets, 156,403 Objects
12 drives online, 0 drives offline

* Operating System and version (`uname -a`): Linux minio-dev-1 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2020-10-24 23:01
From what it looks like you have overlapping prefixes here, is DeleteMultipleObjects sending multiple requests to delete for the same objects?

**Comment by furkalor** [comment] 2020-10-26 09:40
This kind of request worked earlier. Also, a full cluster restart helps to solve this problem, and everything can work without problems for several days. But eventually the problem appears.

**Comment by furkalor** [comment] 2020-10-26 09:41
What should I provide you, in addition, to help find the root cause?

**Comment by harshavardhana** [comment] 2020-10-27 06:56
A sample spark program would be very helpful, and does the size of the data matter? how easy it is to reproduce?

**Comment by furkalor** [comment] 2020-10-27 12:49
Actually, the problem might appear at the last stage of our data pipeline - cleanup. We just want to delete temporary data. I've already provided you the request which we use. In most cases, the problem appears within several days.

**Comment by harshavardhana** [comment] 2020-10-27 16:42
> Actually, the problem might appear at the last stage of our data pipeline - cleanup. We just want to delete temporary data. I've already provided you the request which we use. In most cases, the problem appears within several days.

That will be harder to reproduce.

**Comment by harshavardhana** [comment] 2020-11-07 05:12
> Actually, the problem might appear at the last stage of our data pipeline - cleanup. We just want to delete temporary data. I've already provided you the request which we use. In most cases, the problem appears within several days.

@furkalor please try with latest release and let us know if it's still reproducible.

**Comment by harshavardhana** [comment] 2020-11-19 19:27
> @furkalor please try with latest release and let us know if it's still reproducible.

Closing this as the issue is fixed, please re-open if not

**Closed as completed by harshavardhana** 2020-11-19 19:27 UTC
Labels: community, fixed
