### ISSUE TITLE
fs-backend: putObject panic

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1599] opened 2016-05-11 19:21 UTC
```
ERRO[0067] PutObject failed.                             Error={Cause:Object name invalid: kris191#" Type:main.ObjectNameInvalid}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x77aecf]

goroutine 355 [running]:
panic(0xa0a500, 0xc82000e120)
    /home/krishna/go/src/runtime/panic.go:464 +0x3e6
bufio.(*Writer).WriteString(0x0, 0xb458a0, 0x19, 0x919240, 0x0, 0x0)
    /home/krishna/go/src/bufio/bufio.go:660 +0x3f
net/http.(*expectContinueReader).Read(0xc820212760, 0xc82050c000, 0x1, 0x8000, 0x4b6bc6, 0x0, 0x0)
    /home/krishna/go/src/net/http/server.go:636 +0xc7
io.(*LimitedReader).Read(0xc82041b3a0, 0xc82050c000, 0x1, 0x8000, 0x8000, 0x0, 0x0)
    /home/krishna/go/src/io/io.go:426 +0xbd
io.copyBuffer(0x7f1c675eb1a0, 0xc82041b380, 0x7f1c675eaff8, 0xc82041b3a0, 0xc82050c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /home/krishna/go/src/io/io.go:380 +0x247
io.Copy(0x7f1c675eb1a0, 0xc82041b380, 0x7f1c675eaff8, 0xc82041b3a0, 0xc82041b380, 0x0, 0x0)
    /home/krishna/go/src/io/io.go:350 +0x64
io.CopyN(0x7f1c675eb1a0, 0xc82041b380, 0x7f1c675eb268, 0xc820212760, 0x1, 0xc8207ffe00, 0x0, 0x0)
    /home/krishna/go/src/io/io.go:326 +0xf7
main.objectAPIHandlers.PutObjectHandler.func1(0xc8200860a8, 0xc820182e00, 0x1, 0xc8203851e0)
    /home/krishna/gocode/src/github.com/minio/minio/object-handlers.go:579 +0x2a0
created by main.objectAPIHandlers.PutObjectHandler
    /home/krishna/gocode/src/github.com/minio/minio/object-handlers.go:602 +0x9e2

```

**Comment by harshavardhana** [comment] 2016-05-11 19:52
This is a Golang expect100Continue bug, reproduced it locally before duplicate of #1553

**Closed as completed by harshavardhana** 2016-05-11 19:52 UTC
