### ISSUE TITLE
k8s integration: create official helm chart for distributed Minio server installation on Kubernetes

### ISSUE THREAD

**Issue by nitisht** [minio/minio#3444] opened 2016-12-13 18:07 UTC
## Expected Behavior
Helm is a package manager for Kubernetes. Need to create an official Helm Chart that enables users to install distributed Minio on their Kubernetes cluster via Helm commands.

## Current Behavior

No Helm installer available currently. 

## Possible Solution
Follow the guide to create new [Helm Charts](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md) and add the chart to [Kubernetes/charts/incubator repo](https://github.com/kubernetes/charts/tree/master/incubator).

## Context
Minio should be easy to get started with on a Kubernetes cluster. Having a Helm installer will simplify the process.

**Comment by harshavardhana** [comment] 2016-12-13 18:14
Closing has duplicate of #3443

**Comment by nitisht** [comment] 2017-01-12 16:56
Fixed with https://github.com/kubernetes/charts/pull/348

Minio Helm Chart is now available at https://github.com/kubernetes/charts/tree/master/stable/minio

**Closed as completed** 2017-01-12 16:58 UTC
