### ISSUE TITLE
minio startup with error message: Unable to access uploads.json, MultipartUpload()

### ISSUE THREAD

**Issue by lifematrix** [minio/minio#4821] opened 2017-08-16 02:24 UTC
Hey, I am new to minio.
I just upload multiple large files to minio server for testing, and interrupt it by ctrl-C.
When I restart minio, it raise a  error message like:

```
time="2017-08-16T10:09:18+08:00" 
level=error 
msg="Unable to access uploads.json /workvol/home1/minio/repos/.minio.sys/multipart/.... /uploads.json" 
cause="file not found" 
source="[fs-v1-multipart.go:47:fsObjects.isMultipartUpload()]" 
stack="fs-v1-helpers.go:168:fsStatFile fs-v1-multipart.go:42:fsObjects.isMultipartUpload fs-v1-multipart.go:218:(fsObjects).(github.com/minio/minio/cmd.isMultipartUpload)-fm tree-walk.go:167:doTreeWalk tree-walk.go:238:startTreeWalk.func1 /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/asm_amd64.s:2086:runtime.goexit"
```
I guess it is caused by incomplete uploads, and run the command

```
mc rm --incomplete --recursive --force   BUCKET_NAME
```
and restart minio again. However,  the error message still appear.

What  should I do to solve it?

Thanks for any suggestion.

Steven

**Comment by harshavardhana** [comment] 2017-08-16 02:29
This is a harmless message @lifematrix and can be ignored - we need to suppress and not print this and it is not useful for user to do anything at this point in time. 

It is because recursively some other routine has already deleted the necessary files. Just to be sure can you do `ls /workvol/home1/minio/repos/.minio.sys/multipart/*/*` and see if there are lots of files left over? 

Thanks

**Comment by lifematrix** [comment] 2017-08-16 03:02
Thanks for you quick reply.

I have deleted files  in ```/workvol/home1/minio/repos/.minio.sys/multipart/*/*``` recursively, and error message disappear.

By the way, I wonder if  a long-time uploads is interrupted or fail , what should do to prevent any problems?

Thanks

**Comment by harshavardhana** [comment] 2017-08-16 05:56
> By the way, I wonder if a long-time uploads is interrupted or fail , what should do to prevent any problems?
> 
> Thanks

It shouldn't there is an active routine which cleans up on a timely basis - it must be that there is a bug somewhere which leaves certain stale files do you know exactly how to reproduce this? 

Thanks @lifematrix

**Comment by Julusian** [comment] 2017-09-12 10:18
I have found that I am affected by this bug to a much more extreme level.
I have around 150000 empty folders left behind from previous uploads. Minio looks to be reporting this error for each one of those. This was causing it to produce a huge log file on startup and was being killed because it would eat up all of the available disk space. It was also being rather intensive on system resources during this process. After cleaning out the multipart folder, resource usage and minio are both stable again.


![2017-09-12_10-43-27](https://user-images.githubusercontent.com/1327476/30320830-ca5f1922-97ab-11e7-9d90-ef6228d8a072.png)

![2017-09-12_10-51-09](https://user-images.githubusercontent.com/1327476/30320864-e916610e-97ab-11e7-9a33-380d35985339.png)

**Comment by harshavardhana** [comment] 2017-09-12 16:19
Thanks for the report we will take a look.

**Comment by harshavardhana** [comment] 2017-11-30 18:05
Is this still an issue? @Julusian

**Comment by Julusian** [comment] 2017-11-30 18:25
This appears to be working fine now.
I have tried the latest docker build with the same set of empty folders I reported the issue with and I am not seeing anything in the log or any massive spikes in cpu/ram usage.

**Comment by harshavardhana** [comment] 2017-11-30 18:26
Thanks @Julusian closing this issue as fixed.

**Closed as completed by harshavardhana** 2017-11-30 18:26 UTC
Labels: priority: low, fixed
