### ISSUE TITLE
Not able to create directory in Minio bucket with Hadoop API

### ISSUE THREAD

**Issue by KuladeepK** [minio/minio#6276] opened 2018-08-13 10:19 UTC
Hi Team,

We are trying to create a folder in MINIO bucket with hadoop API. But it is not creating in the bucket or it is not throwing any error. This we have tried with both Java program and hdfs dfs -mkdir command.

Please check the attached code which we tried to create the folder.

```
package s3a;

import java.net.URI;

import org.apache.hadoop.fs.FileStatus;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;

public class S3AMinio {
	public static void main(String args[]) {
		S3AMinio sf = new S3AMinio();
		sf.writeFile();
	}

	public void writeFile() {
		try {
			String nnUrl = "s3a://xxxxx/test";
			org.apache.hadoop.conf.Configuration conf = new org.apache.hadoop.conf.Configuration();
			conf.set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem");
			conf.set("fs.s3a.access.key", "xxxxx");
			conf.set("fs.s3a.secret.key", "xxxxx");
			conf.set("fs.s3a.endpoint", "http://xx.xx.x.xx:9009");
			conf.set("fs.s3a.path.style.access", "true");
			Path path = new Path(nnUrl);
			FileSystem fs = FileSystem.get(new URI(nnUrl), conf);
			fs.mkdirs(path);
			FileStatus fileStatus[] = fs.listStatus(path);
			System.out.println("length:" + fileStatus.length);
			String fileStr = null;
			for (FileStatus fStatus : fileStatus) {
				fileStr = fStatus.getPath().toString();
				System.out.println("----------------  :" + fileStr);
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
```
@nitisht @rambg

**Comment by nitisht** [comment] 2018-08-13 10:29
Thanks @KuladeepK we'll try to reproduce it on our side. Will let you know how it goes

**Comment by nitisht** [comment] 2018-08-13 13:35
@rambg @KuladeepK as discussed on Slack, Minio server version is pretty old `RELEASE.2017-10-27T18-59-02Z` Please use the latest Minio version and let us know how it goes.

**Comment by rambg** [comment] 2018-08-13 13:41
@nitisht Thank you! We are able to create directory with latest minio(2018-08-02 23:16). 

@KuladeepK We can close this issue. Thank you!

**Comment by kannappanr** [comment] 2018-08-13 13:51
@rambg @KuladeepK Closing this issue as working as intended. Please feel free to reach out to us, if you have more questions.

**Closed as completed by kannappanr** 2018-08-13 13:51 UTC
Labels: working as intended, priority: medium
