### ISSUE TITLE
Can't enable TLS when using docker under OS X

### ISSUE THREAD

**Issue by felipeek** [minio/minio#7907] opened 2019-07-10 17:25 UTC
## Expected Behavior
When running the minio server **docker image** under **OS X host**, the server should use TLS when the certificates are provided in `/root/.minio/certs` folder.

## Current Behavior
Even when the certificates are provided, the server runs without TLS.

## Steps to Reproduce (for bugs)
1. Create a folder called `tls` in your working directory
2. Create a folder called `certs` inside `tls`.
3. Copy your private key `private.key` to `certs`
4. Copy your certificate `public.crt` to `certs`
5. Run `docker run -p "9000:9000" -e MINIO_ACCESS_KEY=sgwak -e MINIO_SECRET_KEY=sgwsk123 -v $(realpath ./tls):/root/.minio minio/minio server /data`
6. If the host is **OS X**, minio server will ignore the certificates and will not use TLS.

## Context
When doing the exact same steps using **Ubuntu** as the host machine, it **works** (minio server uses `https`). However, if the host is **OS X**, minio server uses `http`. In both Ubuntu and OS X, I checked the container and both the private key and the certificate are correctly placed under `/root/.minio/certs`.

Private key and certificate permissions inside the container:
```
drwxr-xr-x    4 root     root         128 Jul  9 20:41 .
drwxr-xr-x    3 root     root          96 Jul  9 20:41 ..
-rw-------    1 root     root        3.2K Jul  9 20:41 private.key
-rw-r--r--    1 root     root        2.0K Jul  9 20:41 public.crt
```

## Your Environment

* Version used (`minio version`):
Official docker image `minio/minio:RELEASE.2019-07-10T00-34-56Z`
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
Darwin C02WJ18WHTD8 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
* Link to your project:

**Comment by harshavardhana** [comment] 2019-07-10 17:28
Duplicate of #7887

**Closed as completed by harshavardhana** 2019-07-10 17:28 UTC
Labels: duplicate, community, triage
