### ISSUE TITLE
browser: Scrolling down a long list of objects makes the whole list disappears.

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4144] opened 2017-04-18 17:48 UTC
## Expected Behavior
To be able to find my directory and open it

## Current Behavior
Having one directory and 1000 files under my bucket, scrolling down until the end of list made the whole list disappears, only the directory remains in the list. 

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. `minio server /tmp/fs`
2. `mc mb myminio/testbucket; touch myfile`
3. `for i in $(seq 1 1000); do mc cp myfile myminio/testbucket/$i; done ; mc cp myfile myminio/testbucket/mydir/`
4. Open Minio Browser in Google Chrome, scroll down the list.

## Context
Manual testing

## Your Environment
* master
* Ubuntu 16.04, Chromium 57.0

Notice, I didn't test with the new UX

**Comment by deekoder** [comment] 2017-04-18 18:33
Sounds like an UX issue.

**Comment by deekoder** [comment] 2017-04-24 16:34
Does reproduce for 1000+ objects.

**Comment by krishnasrinivas** [comment] 2017-04-25 19:05
caused by https://github.com/minio/minio/pull/3813

**Comment by harshavardhana** [comment] 2017-05-04 17:35
Fixed by #4252

**Closed as completed** 2017-05-05 16:31 UTC
Labels: priority: severe, regression, fixed
