### ISSUE TITLE
Public bucket can be reach on minio web browser without authentication

### ISSUE THREAD

**Issue by hellracer** [minio/minio#8425] opened 2019-10-21 05:16 UTC
# Create a bucket

`mc mb minio/s3`

# Set basic policy

`mc policy set public minio/s3`

# Browse the bucket from browser

http://bucket.mydomain.com/minio/s3

The URL is accessible without providing the key

## Expected Behavior
This shouldn't work there must be an authentication

## Current Behavior
Once you hit http://bucket.mydomain.com/minio/s3 the bucket is accessible via the minio web browser

## Possible Solution / Workaround

disable minio_browser

**Comment by harshavardhana** [comment] 2019-10-21 06:25
if you have set `public` access on your bucket why should it throw authentication? @hellracer

**Comment by kannappanr** [comment] 2019-10-21 07:47
Closing this as working as intended. If you do need authentication, you should not make it public. Please reach out to us at https://slack.min.io for further such questions.

**Closed as completed by kannappanr** 2019-10-21 07:47 UTC
Labels: working as intended
