### ISSUE TITLE
[distributed] minio slow in listing files on jelastic cloud servers

### ISSUE THREAD

**Issue by sych74** [minio/minio#3409] opened 2016-12-06 18:57 UTC
Testing Minio XLDist. Provisioned 8 servers. 

```
server http://192.168.9.11/export http://192.168.8.56/export http://192.168.8.93/export http://192.168.8.247/export http://192.168.9.5/export http://192.168.4.179/export http://192.168.4.168/export http://192.168.8.97/export --address :$PORT
```

After halt of one node getting the following error at another node

```
time="2016-12-06T18:45:48Z" level=error msg="Unable to fetch disk info for &cmd.retryStorage{remoteStorage:(*cmd.networkStorage)(0xc420241f20)}" cause="disk not found" source="[xl-v1.go:160:getDisksInfo()]"
Loading...
```
And files disappear at this live node as well. 

In native docker implementation seems like no issues. However we found ARP network packages

```
12:17:37.289318 ARP, Request who-has minio_minio3_1.minio_default tell 172.18.0.1, length 28
12:17:37.641318 ARP, Request who-has minio_minio6_1.minio_default tell 172.18.0.1, length 28
12:17:37.793312 ARP, Request who-has minio_minio2_1.minio_default tell 172.18.0.1, length 28
```

Does it minio send them?  It can be the cause.
Thanks

**Comment by harshavardhana** [comment] 2016-12-06 19:20
> And files disappear at this live node as well.

Can you tell us more meaning files disappearing?

**Comment by sych74** [comment] 2016-12-06 19:29
sorry for unclear description - it's absent is UI, just empty folder

<img src="http://b97b19eb0e7d002ebb6f3d223b618c8f.app.jelastic.com/xssu/cross/download/RDYYHFAyVlJeU1hAMQZsQ0RMWxAFREJBAUM4H3VzfwcQEEdYDwIBQmNTTEBI">

but there are files on the filesystem 
```
ls /export/docker/
README.md  eclipse-inst-linux64.tar.gz	google-chrome-stable_current_amd64.deb	putty1.jpg
```

**Comment by harshavardhana** [comment] 2016-12-06 19:50
Can you see of `mc ls ` works ? @sych74

**Comment by harshavardhana** [comment] 2016-12-06 20:32
> README.md  eclipse-inst-linux64.tar.gz	google-chrome-stable_current_amd64.deb	putty1.jpg

OH wait it looks like distributed is not running?  the files are kept as files objects on XL are kept as directories and there is a custom format.

**Comment by harshavardhana** [comment] 2016-12-06 20:33
Can you move the "--address" to beginning on the CLI ? i.e 

```
server --address :$PORT http://192.168.9.11/export http://192.168.8.56/export http://192.168.8.93/export http://192.168.8.247/export http://192.168.9.5/export http://192.168.4.179/export http://192.168.4.168/export http://192.168.8.97/export
````

**Comment by sych74** [comment] 2016-12-06 23:42
the same behavior after I changed the port... also important to notice that I can see the files via UI when all 8 nodes are live, but when one is down, let's say N8, I can not see files via node N7, so they are related to each other. there are more logs 

```
VERSION:
2016-11-26T02:23:47Z
Created minio configuration file at /.minio
Initializing data volume. Waiting for minimum 5 servers to come online.
Initializing data volume. Waiting for minimum 5 servers to come online.
Initializing data volume. Waiting for minimum 5 servers to come online.
Initializing data volume. Waiting for minimum 5 servers to come online.
Initializing data volume. Waiting for minimum 5 servers to come online.
Initializing data volume for first time. Waiting for other servers to come online
Disk 192.168.8.97:80:/export is still unreachable, with error disk not found
Initializing data volume for first time. Waiting for other servers to come online
[2K
[A
Initializing data volume.
[01/08] http://192.168.9.11:80/export - 472 GiB online
[02/08] http://192.168.8.56:80/export - 472 GiB online
[03/08] http://192.168.8.93:80/export - 472 GiB online
[04/08] http://192.168.8.247:80/export - 472 GiB online
[05/08] http://192.168.9.5:80/export - 472 GiB online
[06/08] http://192.168.4.179:80/export - 472 GiB online
[07/08] http://192.168.4.168:80/export - 472 GiB online
[08/08] http://192.168.8.97:80/export - 472 GiB online
```

**Comment by harshavardhana** [comment] 2016-12-06 23:59
did you see the backend i am talking about @sych74 ? did you upload files after you configured the system or before?

**Comment by sych74** [comment] 2016-12-07 08:00
> OH wait it looks like distributed is not running? the files are kept as files objects on XL are kept as directories and there is a custom format.

maybe this can be helpful 
```
cat /export/.minio.sys/format.json 
{"version":"1","format":"xl","xl":{"version":"1","disk":"bbb7f0f5-7470-4eeb-99a6-13aeeee389ae","jbod":["bbb7f0f5-7470-4eeb-99a6-13aeeee389ae","ca6d88a2-a223-42f2-b56b-fa75ccf82afd","34b0faa4-e7a7-4fab-8d9b-1ef66a603e0d","904aa5d2-0637-4c69-8cd2-3ca4ff899576","2ab485f6-3c75-4ccf-a48d-1b8bc13805aa","29b843f3-6018-456b-ae4f-89e66c4073bd","9bd266fa-f2b6-4361-bd48-64d6315b69ff","1c39cedf-6c11-45ad-92ea-d9d2e12da518"]}}
```

> did you see the backend i am talking about 

Not sure that I understood this point

> did you upload files after you configured the system or before?

After. How to run re-config and how to check that config is right?

Thanks

**Comment by harshavardhana** [comment] 2016-12-07 11:49
@sych74 one you have uploaded the object can you check the backend? 

i.e to go "/export" 

```
ls /export/<bucketname>/<objectname>/
```

> {"version":"1","format":"xl","xl":{"version":"1","disk":"bbb7f0f5-7470-4eeb-99a6-13aeeee389ae","jbod":["bbb7f0f5-7470-4eeb-99a6-13aeeee389ae","ca6d88a2-a223-42f2-b56b-fa75ccf82afd","34b0faa4-e7a7-4fab-8d9b-1ef66a603e0d","904aa5d2-0637-4c69-8cd2-3ca4ff899576","2ab485f6-3c75-4ccf-a48d-1b8bc13805aa","29b843f3-6018-456b-ae4f-89e66c4073bd","9bd266fa-f2b6-4361-bd48-64d6315b69ff","1c39cedf-6c11-45ad-92ea-d9d2e12da518"]}}

This looks correct.  Will verify on our end.

**Comment by sych74** [comment] 2016-12-07 11:52
```
ls /export/docker/putty1.jpg/
part.1	xl.json
```

```
cat /export/docker/putty1.jpg/xl.json 
{"version":"1.0.0","format":"xl","stat":{"size":131233,"modTime":"2016-12-02T18:15:45.617071647Z"},"erasure":{"algorithm":"klauspost/reedsolomon/vandermonde","data":4,"parity":4,"blockSize":10485760,"index":1,"distribution":[1,2,3,4,5,6,7,8],"checksum":[{"name":"part.1","algorithm":"blake2b","hash":"fe7cd2d20cd73becd467eb72ec3bc8e0af74cbad09f17dc05ed0dc7be3f7f6148a8aa849ec97df2ee6b716e8dca4cffc6f6fef21ebe05e012137131098a6dc13"}]},"minio":{"release":"RELEASE.2016-11-26T02-23-47Z"},"meta":{"content-type":"image/jpeg","md5Sum":"e1058e913cd5807873e6ea0a6fc68364"},"parts":[{"number":1,"name":"part.1","etag":"e1058e913cd580787
```

**Comment by harshavardhana** [comment] 2016-12-07 11:57
This looks correct @sych74 will validate on our end..

**Comment by QA-Jelastic** [comment] 2016-12-07 17:11
We have tried Minio-client before one container is stopped and after.

With all of working containers ‘mc ls’ takes <1 sec.
$ time ./mc ls demo2/docker/
[2016-12-06 15:38:52 EET]  46MiB apache-jmeter-3.0.zip
[2016-12-06 15:38:53 EET]  31MiB mysql-workbench-community-6.0.9-1ubu1310-amd64.deb
[2016-12-06 15:38:54 EET] 1.5MiB netbeans-1.4.1.nbm
[2016-12-06 15:38:50 EET] 4.6MiB ws10.jtl

real	0m0.821s

After one container is stopped the first ‘mc ls’ request takes 16-20 minutes. 
$ time ./mc ls demo2/docker/
[2016-12-06 15:38:52 EET]  46MiB apache-jmeter-3.0.zip
[2016-12-06 15:38:53 EET]  31MiB mysql-workbench-community-6.0.9-1ubu1310-amd64.deb
[2016-12-06 15:38:54 EET] 1.5MiB netbeans-1.4.1.nbm
[2016-12-06 15:38:50 EET] 4.6MiB ws10.jtl

real	16m9.888s

The further ‘mc ls’ requests takes 18-24 sec.:
$ time ./mc ls demo2/docker/
[2016-12-06 15:38:52 EET]  46MiB apache-jmeter-3.0.zip
[2016-12-06 15:38:53 EET]  31MiB mysql-workbench-community-6.0.9-1ubu1310-amd64.deb
[2016-12-06 15:38:54 EET] 1.5MiB netbeans-1.4.1.nbm
[2016-12-06 15:38:50 EET] 4.6MiB ws10.jtl

real	0m21.552s

At that time in UI we get {jsonrpc: "2.0", error: {code: 0, message: "disk not found", data: null}, id: 1}  for “Web.ListObjects” method.

**Comment by harshavardhana** [comment] 2016-12-07 18:32
Thanks @sych74 - will validate, looks like a regression. Will report what is the issue.

**Comment by harshavardhana** [comment] 2016-12-09 08:54
@sych74 - i just tried with the latest master i.e `minio/minio:edge` i am not able to reproduce this behavior. I can see the buckets and files in-tact.  We haven't really fixed any bug in this regard though. Also i am not able to observe the sluggishness behavior as well - was there any i/o on the server when this was going on? 

Can you provide us the logs from the nodes on which you are accessing the browser? perhaps like `docker logs` etc?

**Comment by QA-Jelastic** [comment] 2016-12-13 10:19
I’ve sent an invitation to dev@minio.io to share environment  ‘Minio4x’ with you. You can view logs in /var/log/run.log.

**Comment by harshavardhana** [comment] 2016-12-13 19:52
Thanks will take a look @sych74 @QA-Jelastic

**Comment by harshavardhana** [comment] 2016-12-13 20:12
Okay so i tested it is just that the UI seems to be loading slowly which we need to see why if the network is slow. Apart from that taking a node down is working fine. 

![j-elastic](https://cloud.githubusercontent.com/assets/622699/21157208/6acf7aba-c12d-11e6-84ab-7c60d7d92cf8.png)
![minio-cluster](https://cloud.githubusercontent.com/assets/622699/21157207/6acc930e-c12d-11e6-9996-40e2a8309f89.png)

**Comment by harshavardhana** [comment] 2016-12-13 20:18
Was able to generate a presigned URL - ``https://minio4x.demo.jelastic.com/docker/Anderson_Terry_Kal_Toh.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=admin%2F20161213%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20161213T201709Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=c865f52941f7d6645decc491c2c339f5e2c038659280745fce9ff270e24dc46a" a new file that i uploaded.

**Comment by harshavardhana** [comment] 2016-12-13 20:19
There is a lot of network delay though which we need to investigate @sych74 @QA-Jelastic - is there a possibility to get "iperf" output between the containers?

**Comment by harshavardhana** [comment] 2016-12-13 20:23
Was able to download the file as well 

```
Connecting to minio4x.demo.jelastic.com (minio4x.demo.jelastic.com)|164.132.8.32|:443... connected.
HTTP request sent, awaiting response... 
200 OK
Length: 758266 (740K) [application/pdf]
Saving to: ‘/tmp/new.pdf’

/tmp/new.pdf                          42%[============================>                                        ] 311.66K  26.9KB/s    eta 16s 

$ md5sum /tmp/new.pdf
1e0b7e41acd1774838ba3b610a50cfee  /tmp/new.pdf

$ md5sum ~/Downloads/Anderson_Terry_Kal_Toh.pdf 
1e0b7e41acd1774838ba3b610a50cfee  /home/harsha/Downloads/Anderson_Terry_Kal_Toh.pdf
```

**Comment by harshavardhana** [comment] 2016-12-18 21:41
Checking back on this @sych74 @QA-Jelastic .. were you able to gather network throughput?  - Thanks

**Comment by harshavardhana** [comment] 2016-12-20 10:13
> Checking back on this @sych74 @QA-Jelastic .. were you able to gather network throughput? - Thanks

Checking back again. Was there anything interesting found?

**Comment by ihorman** [comment] 2016-12-21 09:09
Dear @harshavardhana,
iperf results are the following

1<-->2 TCP				
node99787-minio4x:~# iperf -c 192.168.8.170 -t 50 -i 10 -d				
[ ID] Interval       Transfer     Bandwidth				
[  4]  0.0-50.0 sec  21.4 GBytes  3.67 Gbits/sec				
[  6]  0.0-50.0 sec  17.1 GBytes  2.93 Gbits/sec				
	 			
2<-->3 TCP				
node99788-minio4x:~#  iperf -c 192.168.8.37 -t 50 -i 10 -d				
[ ID] Interval       Transfer     Bandwidth				
[  4]  0.0-50.0 sec  16.4 GBytes  2.81 Gbits/sec				
[  6]  0.0-50.0 sec  13.7 GBytes  2.36 Gbits/sec				
				
1<-->3 TCP				
node99787-minio4x:~# iperf -c 192.168.8.37 -t 50 -i 10 -d				
[ ID] Interval       Transfer     Bandwidth				
[  6]  0.0-50.0 sec  20.4 GBytes  3.51 Gbits/sec				
[  4]  0.0-50.0 sec  18.5 GBytes  3.18 Gbits/sec				
				
1-->2 UDP				
node99787-minio4x:~# iperf -c 192.168.8.170 -t 50 -i 10 -u -b 10m				
[  3] Server Report:				
[  3]  0.0-50.0 sec  59.5 MBytes  9.99 Mbits/sec   0.417 ms    0/42465 (0%)				
[  3]  0.0-50.0 sec  1 datagrams received out-of-order				
				
1-->3 UDP				
node99787-minio4x:~# iperf -c 192.168.8.37 -t 50 -i 10 -u -b 10m				
[  3] Server Report:				
[  3]  0.0-50.0 sec  59.5 MBytes  9.99 Mbits/sec   0.045 ms    0/42468 (0%)				
[  3]  0.0-50.0 sec  1 datagrams received out-of-order	

Looks like UDP is indeed slow

**Comment by harshavardhana** [comment] 2016-12-21 09:12
> 1-->2 UDP
> node99787-minio4x:~# iperf -c 192.168.8.170 -t 50 -i 10 -u -b 10m
> [ 3] Server Report:
> [ 3] 0.0-50.0 sec 59.5 MBytes 9.99 Mbits/sec 0.417 ms 0/42465 (0%)
> [ 3] 0.0-50.0 sec 1 datagrams received out-of-order
> 
> 1-->3 UDP
> node99787-minio4x:~# iperf -c 192.168.8.37 -t 50 -i 10 -u -b 10m
> [ 3] Server Report:
> [ 3] 0.0-50.0 sec 59.5 MBytes 9.99 Mbits/sec 0.045 ms 0/42468 (0%)
> [ 3] 0.0-50.0 sec 1 datagrams received out-of-order
> 
> Looks like UDP is indeed slow

It is possible to access these servers directly for further testing? @ihorman

**Comment by ihorman** [comment] 2016-12-21 10:01
@harshavardhana, sure, can you please send me your public SSH key to ihorman@gmail.com? I will send you back the details how to connect

**Comment by harshavardhana** [comment] 2016-12-21 17:55
> @harshavardhana, sure, can you please send me your public SSH key to ihorman@gmail.com? I will send you back the details how to connect

@ihorman just sent my keys to this email address. Thanks for giving us the access.

**Comment by harshavardhana** [comment] 2016-12-27 22:44
Performance between nodes seems to be 2GB/sec and 10GB/sec

```
# iperf -c 192.168.8.224
------------------------------------------------------------
Client connecting to 192.168.8.224, TCP port 5001
TCP window size: 19.6 KByte (default)
------------------------------------------------------------
[  3] local 192.168.8.170 port 53682 connected with 192.168.8.224 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  2.39 GBytes  2.05 Gbits/sec
``` 

```
# iperf -c 192.168.8.224
------------------------------------------------------------
Client connecting to 192.168.8.224, TCP port 5001
TCP window size: 19.6 KByte (default)
------------------------------------------------------------
[  3] local 192.168.8.37 port 54166 connected with 192.168.8.224 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec  12.7 GBytes  10.9 Gbits/sec
``` 

```
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 85.3 KByte (default)
------------------------------------------------------------
[  4] local 192.168.8.224 port 5001 connected with 192.168.8.170 port 53682
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.0 sec  2.39 GBytes  2.05 Gbits/sec
[  5] local 192.168.8.224 port 5001 connected with 192.168.8.37 port 54166
[  5]  0.0-10.0 sec  12.7 GBytes  10.9 Gbits/sec
```

Looks like the network performance is fine.  There was a memory leak issue which we fixed recently. Do i have the rights to re-deploy this cluster with the latest server?

**Comment by harshavardhana** [comment] 2016-12-28 00:46
Was able to re-deploy the servers seems to be working fine now. Was not able to re-deploy 4th server and test. There is one problem which i observed that reconnecting disks had some issue and one of the server was not able to initialize object API layer. 

Will review the code to see for any obvious problems, we haven't seen this issue in our tests..

**Comment by harshavardhana** [comment] 2016-12-30 01:44
> Was able to re-deploy the servers seems to be working fine now. Was not able to re-deploy 4th server and test. There is one problem which i observed that reconnecting disks had some issue and one of the server was not able to initialize object API layer.
> 
> Will review the code to see for any obvious problems, we haven't seen this issue in our tests..

We fixed a bug related to this issue in "edge" release and also there is one more patch pending..

**Comment by sych74** [comment] 2016-12-31 03:47
@harshavardhana thank you for the update, we will test it right after the holidays.

**Comment by harshavardhana** [comment] 2016-12-31 04:11
> @harshavardhana thank you for the update, we will test it right after the holidays.

All the patches have been updated to "edge" so it should help - i don't have permissions to update and test. So please let us know how it goes. 

Thanks.

**Comment by QA-Jelastic** [comment] 2017-01-11 17:17
We've tried 'edge' image, but unfortunately delays remained when we removed a half of nodes. The most of time takes ListObjects(up to 1min) and StorageInfo(~12s). 
Minio client has same delays $ time ./mc ls edge3/docker
[2017-01-11 18:38:00 EET]  46MiB apache-jmeter-3.0.zip
[2017-01-11 18:37:57 EET] 3.3MiB diaspora-master.zip
[2017-01-11 18:38:14 EET] 1.5MiB joxi-3.0.9_amd64.deb

real	1m7.131s

**Comment by harshavardhana** [comment] 2017-01-11 17:54
> We've tried 'edge' image, but unfortunately delays remained when we removed a half of nodes. The most of time takes ListObjects(up to 1min) and StorageInfo(~12s).
> Minio client has same delays $ time ./mc ls edge3/docker
> [2017-01-11 18:38:00 EET] 46MiB apache-jmeter-3.0.zip
> [2017-01-11 18:37:57 EET] 3.3MiB diaspora-master.zip
> [2017-01-11 18:38:14 EET] 1.5MiB joxi-3.0.9_amd64.deb
> 
> real	1m7.131s

@QA-Jelastic  this amount of delay is not possible, would it be possible get full access basically being able to start and tear down the infrastructure?

**Comment by QA-Jelastic** [comment] 2017-01-12 13:54
You can install Minio server from manifest.jps I’ve attached. (Click on the Import button at the top tools pane of the dashboard and select the unpacked manifest).
To reproduce the delays just remove 2 nodes by Topology wizard.
Or use environment i've shared with you.
[manifest.jps.zip](https://github.com/minio/minio/files/701671/manifest.jps.zip)

**Comment by harshavardhana** [comment] 2017-01-12 16:20
> You can install Minio server from manifest.jps I’ve attached. (Click on the Import button at the top tools pane of the dashboard and select the unpacked manifest).
> To reproduce the delays just remove 2 nodes by Topology wizard.
> Or use environment i've shared with you.

Thanks @QA-Jelastic

**Comment by GarimaKapoor** [comment] 2017-01-19 02:19
@harshavardhana are we still investigating this?

**Comment by hackintoshrao** [comment] 2017-01-19 12:36
Taking this up, will validate this.

**Comment by hackintoshrao** [comment] 2017-01-21 02:38
@QA-Jelastic : I've taken up this issue to investigate. Can you please join our channel  https://slack.minio.io and ping me (@hackintoshrao on the channel). Need some help with getting through Jelastic environment.

**Comment by hackintoshrao** [comment] 2017-02-06 03:53
Conducted tests to validate whether the issue is surfacing from within Minio's code base. After the tests it is clear that the issue is very specific to the Jelastic's environment and the issue doesn't exist in general.

**Comment by harshavardhana** [comment] 2017-02-20 02:49
> Conducted tests to validate whether the issue is surfacing from within Minio's code base. After the tests it is clear that the issue is very specific to the Jelastic's environment and the issue doesn't exist in general.

Closing this as setup issue.

**Closed as completed by harshavardhana** 2017-02-20 02:49 UTC
Labels: working as intended
