### ISSUE TITLE
Root disk detection incorrectly fails startup

### ISSUE THREAD

**Issue by adamlamar** [minio/minio#10741] opened 2020-10-22 21:57 UTC
## Expected Behavior

When starting minio after an upgrade from `RELEASE.2019-09-26T19-42-35Z` to `RELEASE.2020-10-18T21-54-12Z-11`, minio should not refuse startup.

## Current Behavior

When upgrading from the above versions, minio first starts up and performs migration tasks. Minio will be up, but some replicas get stuck with the "Trying to acquire lock" message. Restarting all replicas with `kubectl delete pod -l app=minio` causes all replicas to loop on this message:

```
Disk `/storage` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Disk `http://minio-5.minio:9000/storage` is a root disk. Please ensure the disk is mounted properly, refusing to use root disk.
Waiting for a minimum of 3 disks to come online (elapsed 9m21s)
```

However, the replicas each have their own volume at /storage. There is no mixing of root and non-root disks:
```
# for i in `seq 0 5`; do kubectl exec -ti minio-$i -- /bin/sh -c 'df -h | grep storage'; done
/dev/nvme0n1p1          193.8G     74.7G    119.1G  39% /storage
/dev/nvme0n1p1          193.8G     76.4G    117.4G  39% /storage
/dev/nvme0n1p1          193.8G     75.4G    118.4G  39% /storage
/dev/nvme0n1p1          193.8G     76.4G    117.4G  39% /storage
/dev/nvme0n1p1          193.8G     75.4G    118.4G  39% /storage
/dev/nvme0n1p1          193.8G     74.7G    119.1G  39% /storage
```

## Steps to Reproduce (for bugs)

1. Run `RELEASE.2019-09-26T19-42-35Z` with 6 replicas
2. Upgrade to `RELEASE.2020-10-18T21-54-12Z-11` by stopping all replicas (no rolling upgrade)
3. Note migrations tasks occurring, some replicas not coming up fully
4. Restart all replicas again, note persistent failure

## Context

Trying to upgrade existing clusters

## Regression

Yes

## Your Environment

* Version used (`minio --version`): `RELEASE.2020-10-18T21-54-12Z-11`
* Server setup and configuration: kubernetes
* Operating System and version (`uname -a`): Ubuntu 18.04

**Comment by harshavardhana** [comment] 2020-10-22 21:59
> /dev/nvme0n1p1          193.8G     74.7G    119.1G  39% /storage
> /dev/nvme0n1p1          193.8G     76.4G    117.4G  39% /storage
> /dev/nvme0n1p1          193.8G     75.4G    118.4G  39% /storage
> /dev/nvme0n1p1          193.8G     76.4G    117.4G  39% /storage
> /dev/nvme0n1p1          193.8G     75.4G    118.4G  39% /storage
> /dev/nvme0n1p1          193.8G     74.7G    119.1G  39% /storage

This is a root disk because all disks are the same @adamlamar - the detection is correct.

**Comment by harshavardhana** [comment] 2020-10-22 22:01
> * Run `RELEASE.2019-09-26T19-42-35Z` with 6 replicas
> * Upgrade to `RELEASE.2020-10-18T21-54-12Z-11` by stopping all replicas (no rolling upgrade)
> * Note migrations tasks occurring, some replicas not coming up fully
> * Restart all replicas again, note persistent failure

There is really no migration tasks that happen the issue is that you are mixing root disks with other drives, 
we cannot use such a mixture - either use root disks everywhere or provide different disks for each instance.

**Comment by adamlamar** [comment] 2020-10-22 22:06
I see. Here's some more information about the setup:
* 3 physical nodes running kubernetes
* 6 minio replicas
* 2 minio replicas run per physical node 
* All replicas use hostPath which translate to the same underlying root disk

So what's happening is that _some_ replicas are sharing the same root disk:
* minio-0 + minio-5
* minio-1 + minio-3
* minio-2 + minio-4

Is there a way to workaround the root disk detection, or improve it to account for this case?

**Comment by harshavardhana** [comment] 2020-10-22 22:16
> I see. Here's some more information about the setup:
> 
> * 3 physical nodes running kubernetes
> * 6 minio replicas
> * 2 minio replicas run per physical node
> * All replicas use hostPath which translate to the same underlying root disk
> 
> So what's happening is that _some_ replicas are sharing the same root disk:
> 
> * minio-0 + minio-5
> * minio-1 + minio-3
> * minio-2 + minio-4
> 
> Is there a way to workaround the root disk detection, or improve it to account for this case?

Unfortunately, we cannot allow this type of setup, root disks are not meant to store your files. We have explicitly rejected this mixed-use case because in production using root disk has disastrous consequences. 

We cannot guarantee stability - you would have to re-do your setup.

**Comment by adamlamar** [comment] 2020-10-22 22:28
I can definitely understand the intent around not allowing mixed setups with root and non-root disks. In particular I can see one potential disastrous case where a system restarts but the dedicated disk is not mounted correctly for some reason, and then the new objects being written to the wrong internal location.

For our use case, we run 6 replicas on 3 nodes because we want consistent semantics with systems like zookeeper, kubernetes, etc, where we can continue to tolerate writes with the loss of a single node in a 3 node cluster. Running 2x minio replicas allows that, since the minimum distributed mode requires 4 replicas (otherwise we'd just run 3).

In terms of stability, running this way has worked well for us for a long time. I guess the root disk detection has become more strict in the last year?

**Comment by harshavardhana** [comment] 2020-10-22 22:30
> In terms of stability, running this way has worked well for us for a long time. I guess the root disk detection has become more strict in the last year?

yes, we made it stricter because we had production issues with multiple customers where we incorrectly ended up using root disk. The intent is harder to know when everything is automated in modern cloud native environment. 

So for us to be safe we moved to a stricter model.

**Comment by adamlamar** [comment] 2020-10-22 22:37
Would it make sense to have a feature where we can tell minio that a specific disk is ok, despite that disk not matching minio's notion of a safe setup? Maybe we could match on its FS UUID or label, similar to /etc/fstab?

**Comment by harshavardhana** [comment] 2020-10-22 22:55
> Would it make sense to have a feature where we can tell minio that a specific disk is ok, despite that disk not matching minio's notion of a safe setup? Maybe we could match on its FS UUID or label, similar to /etc/fstab?

It is hard the way the only way is to create a new partition out of the root device i.e not mounted at `/` and use that instead.

**Comment by adamlamar** [comment] 2020-10-22 23:00
Yeah I could see a few different approaches like a secondary partition on the root disk or possibly mounting a loopback device.

Related to the root disk detection, I checked and we only see the error during upgrade. Fresh clusters running two replicas per node don't exhibit the problem ¯\_(ツ)_/¯

**Comment by klauspost** [comment] 2020-10-23 09:14
Closing as working as intended.

**Closed as completed by klauspost** 2020-10-23 09:14 UTC
Labels: working as intended, community, triage
