### ISSUE TITLE
`XMinioInvalidObjectName` despite valid filename `qfeMpHdtZIPi3K5EPiL8qvTFsTPnJAUQ.jpg`

### ISSUE THREAD

**Issue by arubacao** [minio/minio#3390] opened 2016-12-03 21:02 UTC
`XMinioInvalidObjectName` despite valid filename `qfeMpHdtZIPi3K5EPiL8qvTFsTPnJAUQ.jpg`

## Expected Behavior
File should be put in bucket

## Current Behavior
`XMinioInvalidObjectName` error

## Possible Solution
Looks like minio has a problem with creating an empty (?) directory. see php stack `#14 - #16`

## Steps to Reproduce (for bugs)
1. Install [Laravel](https://laravel.com/docs/5.3)
2. Use [Laravel Media Library](https://docs.spatie.be/laravel-medialibrary/v4/introduction)
3. Use `minio/minio` docker container
4. Try to associate file to eloquent model using the media library

## Context
I just need a S3 compatible service for CI.  
This setup works perfect with AWS S3 & [Scality S3](https://github.com/scality/S3).  
Since Scality did the trick for me, I didn't bother further investigation. However, I wanted to leave an issue if you guys do.

## Relevant Logs:
PHP/Laravel Stack:
```
GuzzleHttp\Exception\ClientException: Client error: `PUT http://192.168.99.100:9001/docker-local/5/` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioInvalidObjectName</Code><Message>Object name contains unsuppor (truncated...)
 in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#6 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#7 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(266): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#11 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#12 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#13 /var/www/html/vendor/aws/aws-sdk-php/src/S3/S3ClientTrait.php(27): GuzzleHttp\Promise\Promise->wait()
#14 /var/www/html/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(568): Aws\S3\S3Client->upload('docker-local', '5/', '', 'private', Array)
#15 /var/www/html/vendor/league/flysystem-aws-s3-v3/src/AwsS3Adapter.php(193): League\Flysystem\AwsS3v3\AwsS3Adapter->upload('5/', '', Object(League\Flysystem\Config))
#16 /var/www/html/vendor/league/flysystem/src/Filesystem.php(261): League\Flysystem\AwsS3v3\AwsS3Adapter->createDir('5', Object(League\Flysystem\Config))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(363): League\Flysystem\Filesystem->createDir('5')
#18 /var/www/html/vendor/spatie/laravel-medialibrary/src/Filesystem.php(131): Illuminate\Filesystem\FilesystemAdapter->makeDirectory('5/')
#19 /var/www/html/vendor/spatie/laravel-medialibrary/src/Filesystem.php(50): Spatie\MediaLibrary\Filesystem->getMediaDirectory(Object(Spatie\MediaLibrary\Media), false)
#20 /var/www/html/vendor/spatie/laravel-medialibrary/src/Filesystem.php(38): Spatie\MediaLibrary\Filesystem->copyToMediaLibrary('/tmp/media-libr...', Object(Spatie\MediaLibrary\Media), false, 'Q40zmYOAlqqLDiX...')
#21 /var/www/html/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(328): Spatie\MediaLibrary\Filesystem->add('/tmp/media-libr...', Object(Spatie\MediaLibrary\Media), 'Q40zmYOAlqqLDiX...')
#22 /var/www/html/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(285): Spatie\MediaLibrary\FileAdder\FileAdder->toCollectionOnDisk('profile_images', '')
#23 /var/www/html/app/Http/Controllers/User/ProfileImageController.php(66): Spatie\MediaLibrary\FileAdder\FileAdder->toCollection('profile_images')
```

Minio Docker Logs:
```
time="2016-12-03T20:43:45Z" level=error msg="Unable to create an object." cause="Object name invalid: docker-local#5/" source="[object-handlers.go:447:objectAPIHandlers.PutObjectHandler()]" stack="fs-v1.go:355:fsObjects.PutObject <autogenerated>:195:(*fsObjects).PutObject object-handlers.go:444:objectAPIHandlers.PutObjectHandler api-router.go:58:(objectAPIHandlers).PutObjectHandler-fm"
```

## Your Environment
php-fpm:7.0 (docker container)
minio/minio:latest (docker container)
Laravel 5.3
Laravel Media Library
AWS SDK für PHP / [league/flysystem-aws-s3-v3](https://github.com/thephpleague/flysystem-aws-s3-v3)

Cheers

**Comment by harshavardhana** [comment] 2016-12-03 21:21
This is expected we don't support objects that end with  "/" in them.  The problem is `fysystem-aws-s3-v3` treats object storage like POSIX and there is no needed to do that.  We will send a fix upstream to - https://github.com/thephpleague/flysystem-aws-s3-v3 

`PUT http://192.168.99.100:9001/docker-local/5/` - the issue occurs for this object.

**Comment by harshavardhana** [comment] 2016-12-03 21:25
It also essential to notice that we can reduce one more PUT call to the server we can just upload the object directly without creating an unnecessary parent, since its a flat namespace parent is automatically created based on the resource path.

**Comment by arubacao** [comment] 2016-12-03 21:52
Thanks for the quick response.  
Yeah that's what I was guessing as well.  
I was playing around and was able to successfully execute this command (folder `folder` doesn't exist)
```
Storage::disk('minio')->put('folder/file.txt', 'Contents');
```
which also relies on https://github.com/thephpleague/flysystem-aws-s3-v3.
I'm going to investigate why the previous command even tries to create a directory.
Cheers

**Comment by arubacao** [comment] 2016-12-03 22:32
Quick wrap-up:
Both the Laravel Media Library & therefore the [thephpleague/flysystem](https://github.com/thephpleague/flysystem) are designed for multiple drivers.  

1. Each driver has to implement a [`createDir`](https://github.com/thephpleague/flysystem/blob/master/src/FilesystemInterface.php#L211) method.  
2. [`$this->upload($dirname . '/', '', $config);`](https://github.com/thephpleague/flysystem-aws-s3-v3/blob/a2737a99f7dd60b20ae1c6db06e663c68b5bbe24/src/AwsS3Adapter.php#L204) gets executed from `thephpleague/flysystem-aws-s3-v3`'s `createDir` method
3. Laravel Media Library calls the [`makeDirectory`](https://github.com/spatie/laravel-medialibrary/blob/master/src/Filesystem.php#L131) [(which calls `createDir` on the driver)](https://github.com/illuminate/filesystem/blob/master/FilesystemAdapter.php#L361) method every time a new file gets associated to a model.

To be honest, I don't even know which library should get a PR 😄 
However I think that it does make sense for most driver - somehow also AWS S3 - to be able to create empty directories.

PS: Laravel Media Library is a third-party library https://docs.spatie.be/laravel-medialibrary/v4/introduction

**Comment by harshavardhana** [comment] 2016-12-03 23:18
> To be honest, I don't even know which library should get a PR 
> However I think that it does make sense for most driver - somehow also AWS S3 - to be able to create empty directories.

Yes AWS S3 indeed supports it but directories have no real meaning for example on S3 objects  like this can exist 

```
laravel/images/5/
laravel/images/5/1.img
laravel/images/5
```

Notice that there is an object called "5" and also another object called "5/"  and you try to use `aws cli` to copy "laravel" directory and fails to copy all the objects inside "5" since now it was created as a file while it is expected as a directory - no POSIX systems support something like this.

This is a bad practice and anyone can end up in this situation.  So in minio we ask to no do such mistakes and not treat object storage like POSIX.  

Now to fix the problem it is an architecture overhaul, they might not even like it. Will see how to fix it.

**Comment by harshavardhana** [comment] 2016-12-20 10:16
Closing this as working as intended.

**Closed as completed by harshavardhana** 2016-12-20 10:16 UTC
Labels: working as intended, community

**Comment by harshavardhana** [comment] 2017-01-21 18:02
> Quick wrap-up:
> Both the Laravel Media Library & therefore the thephpleague/flysystem are designed for multiple drivers.
> 
> Each driver has to implement a createDir method.
> $this->upload($dirname . '/', '', $config); gets executed from thephpleague/flysystem-aws-s3-v3's createDir method
> Laravel Media Library calls the makeDirectory (which calls createDir on the driver) method every time a new file gets associated to a model.
> To be honest, I don't even know which library should get a PR 
> However I think that it does make sense for most driver - somehow also AWS S3 - to be able to create empty directories.

@arubacao this should work with the current master.

**Comment by arubacao** [comment] 2017-01-22 16:00
Thanks for the heads up.
I also fixed this issue for me some time ago on the third-party library (but forgot to mention it here):
https://github.com/spatie/laravel-medialibrary/commit/6a38600f2ac34ef361236c159230f40e3080e8d3
