### ISSUE TITLE
Not able to access HDFS through Gateway - unexpected sequence number

### ISSUE THREAD

**Issue by rikatz** [minio/minio#8437] opened 2019-10-23 19:55 UTC
## Expected Behavior
I've been trying to use Minio as HDFS for my cluster. The expected behavior is this works fine :P

## Current Behavior
While creating the cluster, I'm facing some strange error: 

```
ERROR Unable to initialize gateway backend: mkdir /.minio.sys/tmp: unexpected sequence number
```

My cluster uses Kerberos, so I've correctly logged into Kerberos with kinit, as this can be seen in klist command:

```
klist 
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: katz@DATALAKE.TESTE

Valid starting       Expires              Service principal
10/23/2019 16:44:08  10/24/2019 02:44:08  krbtgt/DATALAKE.TESTE@DATALAKE.TESTE
	renew until 10/30/2019 16:44:06
```

When trying to start Minio, the following happens:

```
./minio gateway  hdfs hdfs://gateway.spo.server:8022
ERROR Unable to initialize gateway backend: mkdir /.minio.sys/tmp: unexpected sequence number
```

I've also recompiled Minio into the version present in master branch, and I'm using it directly in the OS (outside any container).

SELinux and IPTables from the environment are disabled.

The HDFS is Cloudera CDH 5.15.1
Operating System: CentOS 7

## Possible Solution
I've tried changing some pieces of code to check if this works fine. Apparently the error is generated by minio/hdfs library but couldn't figure out where.  

## Context
Trying to deliver an S3 Bucket instead of a direct HDFS access :)

## Your Environment
* Version used (`minio version`): 
./minio version
Version: 2019-10-23T19:42:44Z
Release-Tag: DEVELOPMENT.2019-10-23T19-42-44Z
Commit-ID: ddc908207df4839c5e7cc8f025b00f7f1b76e1d6

* Server type and version: CentOS 7 
* Operating System and version (`uname -a`):
Linux testes3hdfs 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Thanks you!!

**Comment by harshavardhana** [comment] 2019-10-23 20:02
Closing as duplicate of #8206 , kerberos support is not fully completed and requires more work.

**Closed as completed by harshavardhana** 2019-10-23 20:02 UTC
Labels: duplicate, community, triage
