### ISSUE TITLE
Upload file on some disk nodes are missing？

### ISSUE THREAD

**Issue by GLTSC** [minio/minio#9359] opened 2020-04-16 05:49 UTC
Is your feature request related to a problem? Please describe.
MINIO cluster service, 4 nodes, 16 disks
If I upload file (high concurrency), the files on some disk nodes are missing, but the file writing returned by minio-go api is successful, and there is no problem in reading and using the file through minio. 
The background automatic heal is running. Will eventually complete the missing files (very slowly)
I wonder if this is a default strategy of minio? Or is there something wrong with my use?

Version used (minio version): minio version RELEASE.2020-03-09T18-26-53Z
Minio started with following setup:

minio_env="GOMAXPROCS=6 MINIO_ACCESS_KEY=XXX MINIO_SECRET_KEY=YYY"
minio_disks="http://192.168.156.18{1...4}/mnt/minio/{1...4}"

**Comment by harshavardhana** [comment] 2020-04-16 05:56
> I wonder if this is a default strategy of minio? Or is there something wrong with my use?

There is nothing wrong @GLTSC this is expected behavior, also it looks like some nodes are disconnected here otherwise MinIO will always write to all disks within a given erasure set. In your case, the set is 16 drives, the tolerance by default is you can lose up to 7 disks and still be able to write. 

PS: Please use the issue template cleanly when submitting issues, it takes an insane amount of time for us to sift through daily issues being reported - reply to each issue in a timely manner. There is an etiquette that needs to be followed when reporting open source issues and the issue reported here is the prime example of how one should not report an issue. This helps us help you properly. 

I am sorry but I would have to close this issue - if you simply want to ask questions just join our https://slack.min.io we have an active community and these are answered in no time.

**Closed as completed by harshavardhana** 2020-04-16 05:56 UTC
Labels: working as intended, upstream (bug)

**Comment by GLTSC** [comment] 2020-04-16 06:18
OK,thank you!
