### ISSUE TITLE
Upload of large file over the S3 API hangs

### ISSUE THREAD

**Issue by benfab** [minio/minio#4705] opened 2017-07-20 16:13 UTC
## Expected Behavior

Being able to upload large file (5.57GB) over the Minio S3 API.

## Current Behavior

I am struggling to upload a large file (5.57GB) to Minio. The upload over the S3 API is hanging and I see the following message in the logs:

```
Jul 20 17:50:05 st0cvm7000069 journal: time="2017-07-20T15:50:05Z" level=error msg="Unable to create object part." cause="#has incomplete body" source="[object-handlers.go:817:objectAPIHandlers.PutObjectPartHandler()]" stack="fs-v1-helpers.go:272:fsCreateFile fs-v1-multipart.go:523:fsObjects.PutObjectPart <autogenerated>:339:(*fsObjects).PutObjectPart object-handlers.go:814:objectAPIHandlers.PutObjectPartHandler api-router.go:46:(objectAPIHandlers).PutObjectPartHandler-fm"
```

As note, uploading small files or the same large file over the UI works fine.

## Your Environment
* Version used: Docker image ' minio\minio:latest' 
* Server type and version: Mino single node
* Operating System and version (`uname -a`): CentOS Linux release 7.3.1611 (Core)
* Note: there is a load balancer between Minio and the client

**Comment by krishnasrinivas** [comment] 2017-07-20 16:23
@benfab what client are you using to upload the large object? Can you paste the relevant code?

**Comment by donatello** [comment] 2017-07-20 16:26
This seems to be minio-go related - at least I am able to reproduce this with `mc`.

**Comment by benfab** [comment] 2017-07-21 08:06
@krishnasrinivas I am facing the issue with both API and mc client.

Here the command I am using from a Windows client.
`.\mc.exe cp --debug .\bosh-stemcell-3363.25-vsphere-esxi-ubuntu-trusty-go_agent.tgz minio/bucket
`

The error from the CLI:
`
...sty-go_agent.tgz:  64.00 MB / 406.82 MB [=======>                                        ]  15.73% 388.93 KB/s 15m2s
mc.exe: <ERROR> Failed to copy `.\bosh-stemcell-3363.25-vsphere-esxi-ubuntu-trusty-go_agent.tgz`. Put http://<redacted>/bosh-stemcell-3363.25-vsphere-esxi-ubuntu-trusty-go_agent.tgz?partNumber=3&uploadId=c1ff2271
-ef97-4b85-a166-7d0a343c5ff0: write tcp 139.15.0.254:59665->185.112.177.146:80: wsasend: An existing connection was forc
ibly closed by the remote host.
 (3) /home/builder/mygo/src/github.com/minio/mc/cmd/cp-main.go:324 cmd.doCopySession(..) Tags: [.\bosh-stemcell-3363.25-
vsphere-esxi-ubuntu-trusty-go_agent.tgz]
 (2) /home/builder/mygo/src/github.com/minio/mc/cmd/common-methods.go:154 cmd.uploadSourceToTargetURL(..) Tags: [http://
<redacted>/bosh-stemcell-3363.25-vsphere-esxi-ubuntu-trusty-go_agent.tgz]
 (1) /home/builder/mygo/src/github.com/minio/mc/cmd/common-methods.go:98 cmd.putTargetStreamFromAlias(..) Tags: [minio,
http://<redacted>/bosh-stemcell-3363.25-vsphere-esxi-ubuntu-trusty-go_agent.tgz]
 (0) /home/builder/mygo/src/github.com/minio/mc/cmd/client-s3.go:620 cmd.(*s3Client).Put(..)
 Release-Tag:RELEASE.2017-06-15T03-38-43Z | Commit:c32b1ea48b65 | Host:PCAJH254 | OS:windows | Arch:amd64 | Lang:go1.7.5
 | Mem:203MB/287MB | Heap:203MB/273MB
mc.exe: <ERROR> Session safely terminated. `

**Comment by donatello** [comment] 2017-07-21 15:52
> @krishnasrinivas I am facing the issue with both API and mc client.

Could you explain how you attempted the upload via the API?

**Comment by donatello** [comment] 2017-07-26 10:10
@benfab - could you try the latest release of minio (released just this week) and mc and try to see if the issue persists?

I am trying to reproduce this issue but it not happening consistently for me. I saw the crash just once so far but with the previous release and not with current one. I was able to upload a 6gb file using mc to the server ~20 times without and issue on the latest release.

**Comment by donatello** [comment] 2017-07-26 10:10
Additionally, if you have any other way to reproduce this issue, please provide all steps to do so.

**Comment by deekoder** [comment] 2017-08-02 02:14
@benfab  we will close this issue. If you think its still reproducible please don't hesitate to reopen it and we can look into it.

**Closed as completed by deekoder** 2017-08-02 02:14 UTC
Labels: working as intended, priority: medium, triage
