### ISSUE TITLE
Linked PEM certs fail to be used

### ISSUE THREAD

**Issue by designermonkey** [minio/minio#8763] opened 2020-01-07 13:55 UTC
## Expected Behavior

When using a utility like certbot to generate certificates for a server, a sysadmin should be able to symlink to those certificates to allow certbot auto renewal to function correctly.

## Current Behavior

Those certbot certs must be physically copied to the minio certs directory. Symbolic links are not followed.

## Steps to Reproduce (for bugs)

1. Create a certificate with certbot (any method).
2. Symlink the certificate and key to the minio certs directory.
3. Attempt to start minio in ssl mode.

## Your Environment

* Version used (`minio version`): 2019-12-19T22:52:26Z
* Operating System and version (`uname -a`): Ubuntu 18.04

**Comment by harshavardhana** [comment] 2020-01-07 17:15
Just symlinking certs folder is not enough we exactly look for files named `private.key` and `public.crt` if you do this with certbot MinIO will automatically reload upon cert renewals.

**Comment by kannappanr** [comment] 2020-01-07 23:06
@designermonkey Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io if you have further questions.

**Comment by designermonkey** [comment] 2020-01-08 08:58
I’m not symlinking the certs folder, I’m linking each certificate and key as I stated in the initial issue.

**Comment by designermonkey** [comment] 2020-01-08 08:59
Also, minio does reload, but the bug is it is not following symlibks and states the certs are invalid as they are links @harshavardhana

**Comment by harshavardhana** [comment] 2020-01-08 16:16
Symlink is already supported which version are you using ? Also can you update the issue description?

**Comment by designermonkey** [comment] 2020-01-08 21:45
Sorry, I'm lost as to what I have to update? The details are there in the description, as is the version we are using.

**Comment by harshavardhana** [comment] 2020-01-08 21:48
> Sorry, I'm lost as to what I have to update? The details are there in the description, as is the version we are using.

@designermonkey can you use the latest version tell us if that this issue is still reproducible?

**Comment by designermonkey** [comment] 2020-01-09 11:47
I will work with our ops team asap to see if we can update one of the machines that showed the issue. We have machines in dev, testing and production all showing the same issue, so it's not an isolated case.

**Comment by kannappanr** [comment] 2020-01-09 21:52
@designermonkey I was unable to reproduce the issue even with the version reported by you

```
ln -s /home/admin/gopath/src/github.com/minio/minio/localhost+2.pem /tmp/certs/public.crt
ln -s /home/admin/gopath/src/github.com/minio/minio/localhost+2-key.pem /tmp/certs/private.key

~/Desktop/minio.RELEASE.2019-12-19T22-52-26Z server -S /tmp/certs /tmp/mks

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of MinIO released 2 weeks ago ┃
┃ Update: Run `mc admin update`                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Endpoint:  https://192.168.1.98:9000 https://127.0.0.1:9000    
AccessKey: minio 
SecretKey: minio123 
```

**Comment by harshavardhana** [comment] 2020-01-22 22:07
Seems to be working as intended @designermonkey - please verify if the symlinks are allowed to be followed and have read access.

**Comment by designermonkey** [comment] 2020-01-23 09:52
They have read access, but **still don't work** on our affected servers. I am struggling to get our ops team to update them to the newest release. I will chase again today.

**Comment by harshavardhana** [comment] 2020-01-23 10:35
can you try like what was posted by @kannappanr ? and see if its reproducible?

**Comment by harshavardhana** [comment] 2020-02-14 08:23
Feel free to let us know, I have tested this with multiple variations and seems to be working fine.

Will close this for now, feel free to update us your upgrade and how the testing went.

**Closed as completed by harshavardhana** 2020-02-14 08:23 UTC
Labels: working as intended, community, priority: medium
