### ISSUE TITLE
Error after replace disk Error: sio: data is not authentic

### ISSUE THREAD

**Issue by titansmc** [minio/minio#10755] opened 2020-10-24 23:21 UTC
Multiple errors are showing after replace of 2 disks on a 2 nodes cluster (96 disks each server).

## Expected Behavior
Autohealing starting to recover the failed drives

## Current Behavior
```
minio_1  | Error: Unable to initialize IAM sub-system, some users may not be available sio: data is not authentic
```
```
 Error: sio: data is not authentic
```
```
Error: msgp: attempted to decode type "int" with method for "str"
```

## Steps to Reproduce (for bugs)
Replace disks, and reboot servers

## Context
It happened with the minio version from 3th of October, after it wasn't coming online, I've decided to upgrade to latest minio but it just keeps the same. Now , no data is found and no users can log in.

## Regression
Probably yes

## Your Environment

* Version used (`minio --version`):  minio/minio:RELEASE.2020-10-18T21-54-12Z
* Server setup and configuration: docker compose
* Operating System and version (`uname -a`):
```
[root@ops-object02 minio]# uname -a
Linux ops-object02.embl.de 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@ops-object02 minio]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
```

**Comment by harshavardhana** [comment] 2020-10-25 01:02
> It happened with the minio version from 3th of October, after it wasn't coming online, I've decided to upgrade to latest minio but it just keeps the same. Now , no data is found and no users can log in.

This is because of a healing regression, already fixed in #10748  @titansmc best way to recover right now is

- shutdown the server 
- generate a dummy format.json `minio server /tmp{1...2}/disk{1...96}`
- copy each `format.json` in the same order to all the drives 

NOTE: have you had previously replaced drives? if yes then you need to be careful - in such a situation blind replacement of `format.json` mentioned in the previous step won't work.

If this is the case please attach your `format.json`'s across drives such that we can fix it. 

> Replace disks, and reboot servers

You don't need to reboot servers after replacing drives, this is the reason it triggered this problem.

**Comment by harshavardhana** [comment] 2020-10-25 05:44
Here are the effected releases 

```
~ git tag --contains b0e1d4ce78
RELEASE.2020-09-05T07-14-49Z
RELEASE.2020-09-08T23-05-18Z
RELEASE.2020-09-10T22-02-45Z
RELEASE.2020-09-16T04-22-35Z
RELEASE.2020-09-17T04-49-20Z
RELEASE.2020-09-21T22-31-59Z
RELEASE.2020-09-23T19-18-30Z
RELEASE.2020-09-26T03-44-56Z
RELEASE.2020-10-03T02-19-42Z
RELEASE.2020-10-09T22-55-05Z
RELEASE.2020-10-12T21-53-21Z
RELEASE.2020-10-18T21-54-12Z
```

**Comment by titansmc** [comment] 2020-10-25 10:26
Hi @harshavardhana , thanks for your help. Yes, I did replace 3 hard drive previously and I noticed that healing was working not very good. 
Here is a link to a tar file that contains format.json for each drive on each server:
https://oc.embl.de/index.php/s/7VyiImWlkVMoQs8

The problem I have and that is why I am rebooting the servers is because I run the cluster with docker-compose so when I replace a hard drive I need to insert new one and format it, to format it it needs to be unmounted and if minio has opened files it doesn't let me unmount it.How is the proper sequence for replacing failed drives?

Thanks a lot.

**Comment by harshavardhana** [comment] 2020-10-25 17:21
> Hi @harshavardhana , thanks for your help. Yes, I did replace 3 hard drive previously and I noticed that healing was working not very good.
> Here is a link to a tar file that contains format.json for each drive on each server:
> https://oc.embl.de/index.php/s/7VyiImWlkVMoQs8
> 
> The problem I have and that is why I am rebooting the servers is because I run the cluster with docker-compose so when I replace a hard drive I need to insert new one and format it, to format it it needs to be unmounted and if minio has opened files it doesn't let me unmount it.How is the proper sequence for replacing failed drives?
> 
> Thanks a lot.

If you just had replaced 3 drives then you can follow the procedure i explained before.

**Comment by titansmc** [comment] 2020-10-25 18:54
I replaced 3 drives before and 2 more a before this issue showed up, so 5 in total. Is it safe to go ahead and replace the current format.json files with the brand new generated as you mentioned ?

**Comment by harshavardhana** [comment] 2020-10-25 19:08
> I replaced 3 drives before and 2 more a before this issue showed up, so 5 in total. Is it safe to go ahead and replace the current format.json files with the brand new generated as you mentioned ?

AFAICS that is the only option here

**Comment by harshavardhana** [comment] 2020-10-25 19:10
> Hi @harshavardhana , thanks for your help. Yes, I did replace 3 hard drive previously and I noticed that healing was working not very good.
> Here is a link to a tar file that contains format.json for each drive on each server:
> https://oc.embl.de/index.php/s/7VyiImWlkVMoQs8
> 
> The problem I have and that is why I am rebooting the servers is because I run the cluster with docker-compose so when I replace a hard drive I need to insert new one and format it, to format it it needs to be unmounted and if minio has opened files it doesn't let me unmount it.How is the proper sequence for replacing failed drives?
> 
> Thanks a lot.

You don't have to use Docker for just two nodes, you are better off using systemd managed bare metal setup.

You can happily replace drives without MinIO getting restarted, hot swapping is supported by MinIO.

We have also fixed the issue in master will release soon such that this doesn't occur in the future.

**Comment by titansmc** [comment] 2020-10-25 19:13
Thanks. Should I stop the server to replace the format.json files?

**Comment by harshavardhana** [comment] 2020-10-25 20:51
> Thanks. Should I stop the server to replace the format.json files?

yes you have to stop all servers and replace all of them in order - and start services again.

**Comment by titansmc** [comment] 2020-10-26 08:30
Hi,
I have replaced the format.json files in order and I get the following error on both servers:
```
o_1  | Waiting for all MinIO sub-systems to be initialized.. lock acquired
minio_1  | Attempting encryption of all config, IAM users and policies on MinIO backend
minio_1  | Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: config file not found)
```

**Comment by harshavardhana** [comment] 2020-10-26 09:01
> Hi,
> I have replaced the format.json files in order and I get the following error on both servers:
> 
> ```
> o_1  | Waiting for all MinIO sub-systems to be initialized.. lock acquired
> minio_1  | Attempting encryption of all config, IAM users and policies on MinIO backend
> minio_1  | Waiting for all MinIO sub-systems to be initialized.. possible cause (Unable to migrate all config at .minio.sys/config/: config file not found)
> ```

@titansmc you can now create a file 

Have `mc` configured first
```
~ echo "region name=" >> region
~ mc admin import alias/ < region
~ mc admin service restart alias/
```

Let me know if this helps?

**Comment by titansmc** [comment] 2020-10-26 09:04
It says:
```
xemacs@alatxa:~$ mc admin import alias/ < region
mc: <ERROR> `import` is not a mc command. See `mc --help`. 
```
```
xemacs@alatxa:~$ mc --version
mc version RELEASE.2020-10-03T02-54-56Z
```

**Comment by titansmc** [comment] 2020-10-26 09:15
Ok, there was a typo, I did:

```
xemacs@alatxa:~$ mc admin config import alias/ < region
Setting new key has been successful.
Please restart your server with `mc admin service restart alias/`.

xemacs@alatxa:~$ mc admin service restart alias/
Restart command successfully sent to `alias/`.
Restarted `alias/` successfully.
```
and I am not seeing those errors. only a few like:
```
API: SYSTEM(bucket=autophagosomes, object=10spdbaf/images/local/fibsem-10spdbaf-raw.n5/setup0/timepoint0/s0/2/17/5)
Time: 09:12:46 UTC 10/26/2020
DeploymentID: 30049ea2-276a-48d0-adca-dbca1035a5bf
Error: open /minio/1/autophagosomes/10spdbaf/images/local/fibsem-10spdbaf-raw.n5/setup0/timepoint0/s0/2/17/5/xl.meta: no data available
       disk=/minio/1
       2: cmd/erasure-metadata-utils.go:133:cmd.readAllFileInfo.func1()
       1: pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
```

Only one user is currently detected:
```
xemacs@alatxa:~$ mc admin user list alias/ 
disabled   hennies-user          hennies-user
```
and a few policies as well.

**Comment by harshavardhana** [comment] 2020-10-26 09:40
> Only one user is currently detected:

You may have to re-create them @titansmc

**Comment by harshavardhana** [comment] 2020-10-26 09:42
> Error: open /minio/1/autophagosomes/10spdbaf/images/local/fibsem-10spdbaf-raw.n5/setup0/timepoint0/s0/2/17/5/xl.meta: no data available

Are you using XFS or ext4 here? - this doesn't look like a disk FS or some form of network FS being used here.

**Comment by titansmc** [comment] 2020-10-26 09:43
I am using XFS like this:
```
/dev/mapper/mpathge     xfs       2,8T   46G  2,7T   2% /minio/72
/dev/mapper/mpathfa     xfs       2,8T   46G  2,7T   2% /minio/41
/dev/mapper/mpathgm     xfs       2,8T   11G  2,8T   1% /minio/90
/dev/mapper/mpathev     xfs       2,8T   46G  2,7T   2% /minio/35
/dev/mapper/mpathgj     xfs       2,8T   48G  2,7T   2% /minio/77
```

**Comment by harshavardhana** [comment] 2020-10-26 09:46
> /dev/mapper/mpathge     xfs       2,8T   46G  2,7T   2% /minio/72
> /dev/mapper/mpathfa     xfs       2,8T   46G  2,7T   2% /minio/41
> /dev/mapper/mpathgm     xfs       2,8T   11G  2,8T   1% /minio/90
> /dev/mapper/mpathev     xfs       2,8T   46G  2,7T   2% /minio/35
> /dev/mapper/mpathgj     xfs       2,8T   48G  2,7T   2% /minio/77

Looks like your LVM is returning some error here @titansmc - but in any case, your cluster is recovered now. 
You may have to restore other things that are missing such as users.

We will release MinIO tomorrow which shall avoid this completely from ever occurring.

**Closed as completed by harshavardhana** 2020-10-26 09:46 UTC
Labels: community, triage

**Comment by titansmc** [comment] 2020-10-26 09:51
I am not using LVM here, only for formatting and mounting the disk into the OS. Since I am using default erasure code (2 nodes with 96 disks each one) this look like there was data loose and I don't understand why if for this to happen there should be half of the disks failing.

There is no way I can restore users? Policies is something I can recover since I have them all in git, but users is going to be almost impossible.

**Comment by harshavardhana** [comment] 2020-10-26 09:59
> I am not using LVM here, only for formatting and mounting the disk into the OS. Since I am using default erasure code (2 nodes with 96 disks each one) this look like there was data loose and I don't understand why if for this to happen there should be half of the disks failing.

There is nothing we can do that bug is unfortunate which you happen to hit. The only way for us to avoid it in the future. We are testing a theory to allow the recovery of some existing content but it may not be available tomorrow. It happened because the order of the drives changed underneath due to the `drive replacement + reboot` behavior that you attempted which introduced a situation where the remote server was considered offline during the drive replacement process which leads to a change in order. 

> There is no way I can restore users? Policies is something I can recover since I have them all in git, but users is going to be almost impossible.

Unfortunately no not at the moment.

**Comment by titansmc** [comment] 2020-10-26 10:50
is there a way to check whether there was some data loose ?

**Comment by titansmc** [comment] 2020-10-26 13:19
Every time I restart the server it says :

Found drives to heal 14, proceeding to heal content...

How can I check healing status? mc admin info was always showing "all good" but data seem to not be that good.

```
xemacs@alatxa:~/sourcecode$ mc admin info embl/ 
●  ops-object02.domain.de:443
   Uptime: 10 minutes 
   Version: 2020-10-18T21:54:12Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

●  ops-object01.domain.de:443
   Uptime: 28 minutes 
   Version: 2020-10-18T21:54:12Z
   Network: 2/2 OK 
   Drives: 96/96 OK 

3.3 TiB Used, 31 Buckets, 5,354,441 Objects
192 drives online, 0 drives offline
```

**Comment by harshavardhana** [comment] 2020-10-26 16:39
> Every time I restart the server it says :
> 
> Found drives to heal 14, proceeding to heal content...
> 
> How can I check healing status? mc admin info was always showing "all good" but data seem to not be that good.
> 
> ```
> xemacs@alatxa:~/sourcecode$ mc admin info embl/ 
> ●  ops-object02.domain.de:443
>    Uptime: 10 minutes 
>    Version: 2020-10-18T21:54:12Z
>    Network: 2/2 OK 
>    Drives: 96/96 OK 
> 
> ●  ops-object01.domain.de:443
>    Uptime: 28 minutes 
>    Version: 2020-10-18T21:54:12Z
>    Network: 2/2 OK 
>    Drives: 96/96 OK 
> 
> 3.3 TiB Used, 31 Buckets, 5,354,441 Objects
> 192 drives online, 0 drives offline
> ```

mc admin info --json would indicate this @titansmc I think you shouldn't restart servers are this moment and leave the cluster as is.
