### ISSUE TITLE
Minio crashes with nil pointer dereference in CompleteMultipart

### ISSUE THREAD

**Issue by challarao** [minio/minio#7057] opened 2019-01-09 10:05 UTC
We are trying to:
1. Upload a large artifact (around 250 GB)
2. Using multipart
3. Disks -1, minio running in Kubernetes.  Minio pod mounted to a 500 GB disk, 390 GB free.

## Expected Behavior
1. Should complete the multipart upload successfully.

## Current Behavior
Failing with nil pointer de-reference in the following file:

https://github.com/minio/minio/blob/RELEASE.2018-09-25T21-34-43Z/cmd/fs-v1-multipart.go#L574

Logs below:

/opt/go/src/runtime/panic.go:502 +0x229

```
github.com/minio/minio/cmd.(*FSObjects).CompleteMultipartUpload(0xc420356310, 0x15eb280, 0xc422bdc000, 0xc4208b0826, 0x14, 0xc4208b083b, 0x35, 0xc4208b087a, 0x24, 0xc4232fa000, ...)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1-multipart.go:574 +0x1beb
```

```
2019-01-08 17:55:19.142531 I | http: panic serving 192.168.3.4:41468: runtime error: invalid memory address or nil pointer dereference

goroutine 112304 [running]:

net/http.(*conn).serve.func1(0xc4203e39a0)

	/opt/go/src/net/http/server.go:1726 +0xd0

panic(0x12c1280, 0x20a8af0)

	/opt/go/src/runtime/panic.go:502 +0x229

github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:771 +0x93

panic(0x12c1280, 0x20a8af0)

	/opt/go/src/runtime/panic.go:502 +0x229

github.com/minio/minio/cmd.(*FSObjects).CompleteMultipartUpload(0xc420356310, 0x15eb280, 0xc422d5f890, 0xc422033386, 0x14, 0xc42203339b, 0x35, 0xc4220333da, 0x24, 0xc420be2000, ...)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/fs-v1-multipart.go:574 +0x1beb

github.com/minio/minio/cmd.(ObjectLayer).CompleteMultipartUpload-fm(0x15eb280, 0xc422d5f890, 0xc422033386, 0x14, 0xc42203339b, 0x35, 0xc4220333da, 0x24, 0xc420be2000, 0x2710, ...)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:1771 +0x114

github.com/minio/minio/cmd.objectAPIHandlers.CompleteMultipartUploadHandler(0x15132d0, 0x15132c8, 0x15e4000, 0xc42063ccc0, 0xc420fa8300)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:1775 +0x78f

github.com/minio/minio/cmd.(objectAPIHandlers).CompleteMultipartUploadHandler-fm(0x15e4000, 0xc42063ccc0, 0xc420fa8300)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/api-router.go:58 +0x57

net/http.HandlerFunc.ServeHTTP(0xc42058ab60, 0x15e4000, 0xc42063ccc0, 0xc420fa8300)

	/opt/go/src/net/http/server.go:1947 +0x44

github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200b8230, 0x15e4000, 0xc42063ccc0, 0xc420fa8300)

	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107 +0xdc

github.com/minio/minio/cmd.requestIDHeaderHandler.ServeHTTP(0x15d9240, 0xc4200b8230, 0x15e4000, 0xc42063ccc0, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:742 +0x9e

github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x15db4e0, 0xc420086c60, 0x15e4000, 0xc42063ccc0, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:757 +0xdc

github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc420194b60, 0x15db560, 0xc420086cd0, 0x15e4000, 0xc42063ccc0, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:628 +0x88

github.com/minio/minio/cmd.rateLimit.ServeHTTP(0xc420586780, 0x15db360, 0xc420194b80, 0x15e4000, 0xc42063ccc0, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:722 +0x123

github.com/minio/minio/cmd.pathValidityHandler.ServeHTTP(0x15db480, 0xc420194ba0, 0x15e4000, 0xc42063ccc0, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:615 +0x1b8

github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x15db460, 0xc420086d20, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:554 +0xba

github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x15db400, 0xc420086d50, 0x50004000000, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:71 +0xde

github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x15db500, 0xc420194cc0, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:96 +0xa7

github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x15db4c0, 0xc420086da0, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x8a

github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x15db3c0, 0xc420086db0, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:248 +0x92

github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x15db4a0, 0xc420086dc0, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:306 +0x78

github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x15db440, 0xc420086dd0, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:275 +0x73

github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x15db380, 0xc420086de0, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:376 +0x1af

github.com/minio/minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190 +0xfe

net/http.HandlerFunc.ServeHTTP(0xc420194d60, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/opt/go/src/net/http/server.go:1947 +0x44

github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x15dc560, 0xc420194d60, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:505 +0xd2

github.com/minio/minio/cmd.authHandler.ServeHTTP(0x15db540, 0xc420086e60, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:287 +0x157

github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x15db340, 0xc420086e70, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:139 +0xa7

github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x15db520, 0xc420086e80, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:774 +0x8d

github.com/minio/minio/cmd/http.(*Server).Start.func1(0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:115 +0xe7

net/http.HandlerFunc.ServeHTTP(0xc420244180, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/opt/go/src/net/http/server.go:1947 +0x44

net/http.serverHandler.ServeHTTP(0xc420112360, 0x15e9ac0, 0xc4201b4620, 0xc420fa8000)

	/opt/go/src/net/http/server.go:2694 +0xbc

net/http.(*conn).serve(0xc4203e39a0, 0x15eb1c0, 0xc420326040)

	/opt/go/src/net/http/server.go:1830 +0x651

created by net/http.(*Server).Serve

	/opt/go/src/net/http/server.go:2795 +0x27b
```

## Regression
It seems that it worked previously a month ago with the same version of minio.

## Your Environment
* Version used: RELEASE.2018-09-25T21-34-43Z
* Linux

**Comment by harshavardhana** [comment] 2019-01-09 11:31
https://github.com/minio/minio/issues/6429 possible duplicate and perhaps fixed in later releases @challarao

**Comment by challarao** [comment] 2019-01-09 11:41
Thanks @harshavardhana. We will see if the issue is reproducible in the latter versions.

**Comment by kannappanr** [comment] 2019-01-09 21:56
@challarao marking this issue as duplicate of #6429 and closing this issue. Please feel free re-open the issue if that is not the case.

**Closed as completed by kannappanr** 2019-01-09 21:56 UTC
Labels: duplicate, community, priority: medium
