### ISSUE TITLE
Abnormal display of console page

### ISSUE THREAD

**Issue by dwwendy** [minio/minio#16733] opened 2023-03-01 06:18 UTC
The version of minio is RELEASE. 2023-01-12T02-06-16. The display on the management interface is inconsistent with the display of data in the actual cluster. For example, some buckets contain data, but the page displays 0

**Comment by ravindk89** [comment] 2023-03-01 17:23
I'm fairly certain this is expected behavior because of how our Scanner works.

MinIO uses a scanner process that, over time, scans the entire namespace of buckets, prefixes, and objects. This scanner is a low-priority process that yields to high I/O to avoid resource contention - that is, we assume most users want their S3 workloads to prioritize over metrics adoption.

Since metric collection is "lazy", it can take some time for displayed metrics to fully update. The exact performance depends on the available node resources, size of cluster,a nd complexity of bucket hierarchy. There's no hard-and-fast rule. 

If you're using a recent `mc` version you can use `mc admin scanner status ALIAS` to see what the Scanner is doing, how many objects it has scanned, and how long it takes to complete a full scan. You should check that first.

If it looks like the scanner is misbehaving, we'd need you to provide a lot more data:

- How you are starting MinIO
- The Topology
- How your buckets and objects are laid out
- Object size distribution
- Hardware config.

**Comment by ravindk89** [comment] 2023-03-02 16:14
I'm going to close this issue for now. If you can check the notes above and provide more information indicating a scanner issue, feel free to re-open this.

**Closed as completed by ravindk89** 2023-03-02 16:14 UTC
Labels: working as intended, community, incomplete info, waiting for info

**Comment by dwwendy** [comment] 2023-03-07 02:13
Hello!


thank you. Normally, does this scan confirm the time based on the size of the bucket?





痞子威
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "minio/minio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月3日(星期五) 凌晨0:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [minio/minio] Abnormal display of console page (Issue #16733)





 
Closed #16733 as completed.
