### ISSUE TITLE
/minio.sys/buckets contains my storage clone

### ISSUE THREAD

**Issue by linuxserver2016** [minio/minio#8586] opened 2019-11-29 11:02 UTC
## Expected Behavior

Prevent My data from getting copied in to  /minio.sys/buckets directory

## Current Behavior

an exact clone of my storage objects gets mirrored under /minio.sys/buckets directory

## Possible Solution

remove them and put a cron to automate the process

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

The Disk utilization is too high because of the two clones of same Data

## Your Environment

* Version used (`minio version`):  2019-06-13T01:41:13Z
* Environment name and version: APACHE & LITESPEED, PHP (7.1,7.2) (web application)
* Server type and version: Bare Metal Server 
* Operating System and version (`uname -a`): Centos 6 & centos 7
* Link to your project:

**Comment by nitisht** [comment] 2019-11-29 13:27
@linuxserver2016 `.minio.sys/buckets` contains object related metadata, not the data itself.

**Comment by harshavardhana** [comment] 2019-11-29 17:34
This is by design closing working as intended.

**Closed as completed by harshavardhana** 2019-11-29 17:34 UTC
Labels: working as intended, community

**Comment by linuxserver2016** [comment] 2019-11-30 10:08
v

> @linuxserver2016 `.minio.sys/buckets` contains object related metadata, not the data itself.

If I Delete the object related metadata from  ".minio.sys/buckets" would it affect the data?

@harshavardhana @nitisht

**Comment by harshavardhana** [comment] 2019-11-30 19:39
No it won't @linuxserver2016

**Comment by linuxserver2016** [comment] 2019-12-02 09:09
If i loose meta data, would it affect the response speed of my objects? @harshavardhana

**Comment by harshavardhana** [comment] 2019-12-02 17:26
No it won't
