### ISSUE TITLE
Pre-signed URLs do respect the time specified

### ISSUE THREAD

**Issue by dharapvj** [minio/minio#14491] opened 2022-03-07 12:12 UTC
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

We have minio HA running via operator in kubernetes cluster. We have created ingress for tenants (nginx ingress controller) and have overrode the MINIO_SERVER_URL to use ingress domain name so that pre-signed URL is generated with correct domain name.

If we create new pre-signed url with expiry time of 2 days or more .. it works in a new incognito browser. But it gives error after **2 hours** it gives following error:
`InvalidAccessKeyId`
![image](https://user-images.githubusercontent.com/1920926/157032070-43626ecf-9512-4399-8f44-a9dd40eef0c5.png)

## Expected Behavior

Presigned urls should work until set time.

## Current Behavior

Presigned urls work for short amount of time - after which they give errors.

## Steps to Reproduce (for bugs)

1. deploy a tenant via HA minio. (override MINIO_SERVER_URL via storage configuration secret)
2. deploy a ingress with same url as that specified in MINIO_SERVER_URL secret
3. create pre-signed url with expiry time long like 2 days.
4. access it in inconito window and confirm that it works.
5. access the same url after around 2 ours and receive error

## Your Environment

* Version used (`minio --version`): `RELEASE.2021-10-13T00-23-17Z`
* Server setup and configuration: minio pod accessed via ingress
* Operating System and version (`uname -a`): kubernetes cluster

**Comment by klauspost** [comment] 2022-03-07 12:58
The error doesn't seem to indicate that the presigned URL expired, but that the access key used to generate it no longer is valid.

Please share how you are generating the presigned url, and whether the original access key is still available.

**Comment by harshavardhana** [comment] 2022-03-08 00:20
> * create pre-signed url with expiry time long like 2 days.

is the presigned URL created using console UI? @dharapvj

**Comment by edwardzjl** [comment] 2022-03-09 06:45
I have the same issue.

I configured minio to use sso login, by an Oauth service.

It seems that after the oauth access token expires, the pre-signed url started to return 403:

```xml
<Error>
  <Code>InvalidAccessKeyId</Code>
  <Message>The Access Key Id you provided does not exist in our records.</Message>
  <Key>b9f94c54-b680-423c-8d61-d517ef539d45/project/oriPredict.csv</Key>
  <BucketName>platform</BucketName>
  <Resource>/platform/b9f94c54-b680-423c-8d61-d517ef539d45/project/oriPredict.csv</Resource>
  <RequestId>16DAA2F0057DD8AF</RequestId>
  <HostId>0d8c9f37-8769-472f-b591-06fec4ab88a6</HostId>
</Error>
```



> > * create pre-signed url with expiry time long like 2 days.
> 
> is the presigned URL created using console UI? @dharapvj

Yes it is created on console UI, by the share button.

**Comment by harshavardhana** [comment] 2022-03-09 09:43
> Yes it is created on console UI, by the share button.

Then this is a limitation with Console UI and MinIO it's not yet supported - closing as a duplicate of 
https://github.com/minio/console/issues/922

**Closed as completed by harshavardhana** 2022-03-09 09:43 UTC
Labels: priority: low, community, waiting for info
