### ISSUE TITLE
[distributed] format.json initialization should require all disks to be available

### ISSUE THREAD

**Issue by krisis** [minio/minio#2462] opened 2016-08-17 02:39 UTC

**Comment by vadmeste** [comment] 2016-08-21 15:24
We still want to be able to run the server if one or more disks are unavailable, how minio should behave in this case ?

**Comment by vadmeste** [comment] 2016-08-22 12:03
@krisis ?

**Comment by krisis** [comment] 2016-08-22 17:50
@vadmeste There are two points in the deployment of a multi-node setup where there could be a few nodes/disks unavailable.
- At the very beginning, the first time we start the cluster. In this case, we could enforce that all nodes/disks must be available, until the point `format.json` is written on all the disks.
- When a minio server instance is restarted to find that one or more instances in the cluster are not reachable. In this case, we could continue operations as long as quorum is available.

Does that make sense?

**Comment by vadmeste** [comment] 2016-08-22 18:01
@krisis, I understand your point, but I don't see why we should consider these two cases, can't we merge them into only one ? There is also the case when we replace failed disks with new fresh ones.

**Comment by krisis** [comment] 2016-08-22 18:33
@vadmeste I checked the pseudo-code representation of handling `format.json` in the event of one or more disk failures, written with single-node multi-disk setup (XL) in mind. See `cmd/format-config-v1.go`.  There is no reason why this shouldn't extend naturally to multi-node multi-disk setup (distributed). In summary, I agree with you on merging the two cases, especially when we get this without adding extra line of code.

**Comment by vadmeste** [comment] 2016-08-22 19:52
@harshavardhana, Reinitializing corrupted and fresh disks is working as expected, you can close this issue.

**Comment by awwalker** [comment] 2016-08-23 03:27
@vadmeste change should be in format-config-v1.go such that config is written only if all disks are online, quorum is not sufficient.

**Comment by harshavardhana** [comment] 2016-08-27 10:21
Closing this as duplicate of #2502

**Closed as completed by harshavardhana** 2016-08-27 10:21 UTC
