### ISSUE TITLE
XL: GetObject returns corrupt data

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1939] opened 2016-06-20 15:34 UTC
previously we were doing:

```
58                  curEncBlockSize := getEncodedBlockLen(curBlockSize, eInfo.DataBlocks)               
59                  offsetEncOffset := getEncodedBlockLen(startOffset, eInfo.DataBlocks)
...
enBlocks[blockIndex] = make([]byte, curEncBlockSize)
```

curEncBlockSize was used for ReadFile block-size

it's now changed to:

```
enBlocks[blockIndex] = make([]byte, eInfo.BlockSize)
```

this causes problem demoed here:
Upload a big file (big enough that each part is > 10MB

```
krishna@escape:~$ curl http://localhost:9000/mybucket -F x-amz-credential=SXO8VW2OFKKP2OG7AC85/20160620/us-east-1/s3/aws4_request -F x-amz-date=20160620T152338Z -F x-amz-signature=40dedbb521ff06c20819346507eaf57726af9fde36e96becb2704d9ace5d3b64 -F bucket=mybucket -F policy=eyJleHBpcmF0aW9uIjoiMjAxNi0wNi0yN1QxNToyMzozOC40MzJaIiwiY29uZGl0aW9ucyI6W1siZXEiLCIkYnVja2V0IiwibXlidWNrZXQiXSxbImVxIiwiJGtleSIsImFzZCJdLFsiZXEiLCIkeC1hbXotZGF0ZSIsIjIwMTYwNjIwVDE1MjMzOFoiXSxbImVxIiwiJHgtYW16LWFsZ29yaXRobSIsIkFXUzQtSE1BQy1TSEEyNTYiXSxbImVxIiwiJHgtYW16LWNyZWRlbnRpYWwiLCJTWE84VlcyT0ZLS1AyT0c3QUM4NS8yMDE2MDYyMC91cy1lYXN0LTEvczMvYXdzNF9yZXF1ZXN0Il1dfQ== -F x-amz-algorithm=AWS4-HMAC-SHA256 -F key=asd -F file=@/tmp/asd
<?xml version="1.0" encoding="UTF-8"?>
<PostResponse xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Location>/mybucket/asd</Location><Bucket>mybucket</Bucket><Key>asd</Key><ETag>9b7cda5510db7b288641b4a2ef008ae3</ETag></PostResponse>krishna@escape:~$ 
```

now md5sum mismatches:

```
krishna@escape:~$ mc cat myminio/mybucket/asd | md5sum
26a2df5c1857a656f870e81b83bc878a  -
krishna@escape:~$ md5sum /tmp/asd
9b7cda5510db7b288641b4a2ef008ae3  /tmp/asd
krishna@escape:~$ 
```

**Comment by balamurugana** [comment] 2016-06-20 18:15
https://github.com/minio/minio/issues/1941 may fix this issue.

**Comment by harshavardhana** [comment] 2016-06-21 00:03
Closing as duplicate of #1946

**Closed as completed by harshavardhana** 2016-06-21 00:03 UTC
