### ISSUE TITLE
server misbehaving (*net.DNSError) when deploying expanded cluster in docker swarm 

### ISSUE THREAD

**Issue by HaykManukyanAvetiky** [minio/minio#13067] opened 2021-08-25 10:31 UTC
I am trying to set up expanded (2 pool) minio cluster on docker swarm and getting wired error  

## Current Behavior
None of container start, and each of them throws wired error :
API: SYSTEM()
 Time: 09:54:58 UTC 08/25/2021
Error: lookup minio7 on 127.0.0.11:53: server misbehaving (*net.DNSError)
      host=minio7, elapsedTime=18 seconds elapsed
       5: cmd/endpoint.go:447:cmd.Endpoints.UpdateIsLocal()
     4: cmd/endpoint.go:601:cmd.CreateEndpoints()
       3: cmd/endpoint-ellipses.go:373:cmd.createServerEndpoints()
      2: cmd/server-main.go:147:cmd.serverHandleCmdArgs()
        1: cmd/server-main.go:448:cmd.serverMain()

interesting point that each container seems to complain for opposite set for DNS error, e.g 
minio1..4 complains only for minio5..8 and vice versa 

## My Environment
I have an docker swarm with 2 machines , manager and worker
Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.1
deployment command , docker stack deploy -c "compose file" minio-test

# compose file 
```version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2021-08-25T00-41-18Z
  command: server --console-address ":9001" http://minio{1...4}/data http://minio{5...8}/data
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    deploy:
      placement: { constraints: ["node.role == worker"] }
    volumes:
      - data1-1:/data
      # - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    deploy:
      placement: { constraints: ["node.role == manager"] }
    volumes:
      - data2-1:/data
      # - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    deploy:
      placement: { constraints: ["node.role == worker"] }
    volumes:
      - data3-1:/data
      # - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    deploy:
      placement: { constraints: ["node.role == manager"] }
    volumes:
      - data4-1:/data
      # - data4-2:/data

  minio5:
    <<: *minio-common
    hostname: minio5
    deploy:
      placement: { constraints: ["node.role == worker"] }
    volumes:
      # - data1-1:/data
      - data1-2:/data

  minio6:
    <<: *minio-common
    hostname: minio6
    deploy:
      placement: { constraints: ["node.role == manager"] }
    volumes:
      # - data2-1:/data
      - data2-2:/data

  minio7:
    <<: *minio-common
    hostname: minio7
    deploy:
      placement: { constraints: ["node.role == worker"] }
    volumes:
      # - data3-1:/data
      - data3-2:/data

  minio8:
    <<: *minio-common
    hostname: minio8
    deploy:
      placement: { constraints: ["node.role == manager"] }
    volumes:
      # - data4-1:/data
      - data4-2:/data

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
      - minio5
      - minio6
      - minio7
      - minio8

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:```

**Comment by harshavardhana** [comment] 2021-08-25 15:26
@HaykManukyanAvetiky looks like your DNS is not resolving

You need to fix that.

**Comment by harshavardhana** [comment] 2021-09-03 08:07
@HaykManukyanAvetiky - I would suggest you to use k8s instead of `docker swarm` - there are known issues with `docker swarm` with failed DNS propagation etc.

Perhaps you can try adding 

```
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
```

For `minio5...minio8` and then vice-versa. 

Closing this issue since I tried the setup locally, I can't reproduce this with `docker-compose`.

**Closed by harshavardhana** 2021-09-03 08:07 UTC
Labels: community, triage

**Comment by HaykManukyanAvetiky** [comment] 2021-09-03 08:12
Yes, Already start k8s setup
