### ISSUE TITLE
Wrong monitoring stats of disk usage

### ISSUE THREAD

**Issue by bakaut** [minio/minio#8854] opened 2020-01-18 22:16 UTC
## Expected Behavior

Prometeus  monitoring stats of disk usage stats show ```/opt/data/51``` disk usage, not ```/```
```disk_storage_used{disk="/opt/data/51"} 1.755652096e+09```
```
[root@51 ~]# du -hs /opt/data/51
108K	/opt/data/51
```
## Current Behavior

Wrong monitoring stats of disk usage. Prometeus monitoring stats show ```/``` disk usage
```disk_storage_used{disk="/opt/data/51"} 1.755652096e+09```
```
[root@51 ~]# df -h
Файловая система        Размер Использовано  Дост Использовано% Cмонтировано в
devtmpfs                  223M            0  223M            0% /dev
tmpfs                     235M            0  235M            0% /dev/shm
tmpfs                     235M         9,6M  225M            5% /run
tmpfs                     235M            0  235M            0% /sys/fs/cgroup
/dev/mapper/centos-root    47G         1,7G   46G            4% /
/dev/sda1                1014M         197M  818M           20% /boot
tmpfs                      47M            0   47M            0% /run/user/0
```
## Possible Solution

Change code to display  stats shown in paramert ```disk_storage_used{disk="/opt/data/51"} 1.755652096e+09``` not ```/```
## Steps to Reproduce (for bugs)

1. Run minio distributed server via reverse proxy nginx  [install docs](https://docs.min.io/docs/setup-nginx-proxy-with-minio.html)
2. Take a look ``` df -h``` and  ``` du -hs /opt/data/51 ```
3. Take a look  prometeus stats ```disk_storage_used{disk="/opt/data/51"} 1.755652096e+09```
4.

## Your Environment

* Version used (`minio version`): RELEASE.2020-01-13T22-49-03Z
* Environment name and version (e.g. nginx 1.9.1): nginx version: openresty/1.15.8.2
* Server type and version: VM, Centos 7
* Operating System and version (`uname -a`): 3.10.0-1062.7.1.el7.x86_64
* Link to your project:

**Comment by harshavardhana** [comment] 2020-01-18 22:18
what you are using is not wrong the disk-usage is showing the usage of the drive where the path comes from you are interested in `mc admin info` value which is the real usage on the backend which is not yet exposed on prometheus metrics.

We will be doing that in future.

**Comment by bakaut** [comment] 2020-01-18 22:40
```mc admin info``` show wrong info too

```
"disks": [
                    {
                        "path": "/opt/data/51",
                        "state": "ok",
                        "uuid": "3e3ddcfc-9866-4610-b41e-0cfb2000c253",
                        "totalspace": 50432839680,
                        "usedspace": 1756078080
                    },
                    {
                        "path": "/opt/data/52",
                        "state": "ok",
                        "uuid": "406655ed-e92a-47f7-bf0e-3efd89248e29",
                        "totalspace": 50432839680,
                        "usedspace": 1756078080
                    }
                ]

```

**Comment by harshavardhana** [comment] 2020-01-18 22:44
It's not wrong it's showing the drive total space, not your actual usage @bakaut the actual usage is different and is calculated every 12hrs

```
~ mc admin info play
●  play.minio.io
   Uptime: 1 day 
   Version: 2020-01-17T22:08:02Z
   Network: 1/1 OK 
   Drives: 4/4 OK 

2.0 GiB Used, 139 Buckets, 11,229 Objects
4 drives online, 0 drives offline
```

The following output is disk space not the directory usage
```
~ mc admin info play --json | jq .info.servers[].disks
[
  {
    "path": "/home/play/data1",
    "state": "ok",
    "uuid": "c1f8dbf8-39c8-46cd-bab6-2c87d18db06a",
    "totalspace": 8378122240,
    "usedspace": 1215680512
  },
  {
    "path": "/home/play/data2",
    "state": "ok",
    "uuid": "9616d28f-5f4d-47f4-9c6d-4deb0da07cad",
    "totalspace": 8378122240,
    "usedspace": 1215680512
  },
  {
    "path": "/home/play/data3",
    "state": "ok",
    "uuid": "4c822d68-4d9a-4fa3-aabb-5bf5a58e5848",
    "totalspace": 8378122240,
    "usedspace": 1215680512
  },
  {
    "path": "/home/play/data4",
    "state": "ok",
    "uuid": "95b5a33c-193b-4a11-b13a-a99bc1483182",
    "totalspace": 8378122240,
    "usedspace": 1215680512
  }
]
```

The actual usage
```
~ mc admin info play --json | jq .info.usage
{
  "size": 2133318901
}
```

**Comment by harshavardhana** [comment] 2020-01-18 22:48
This is working as intended, please join us on https://slack.min.io for further clarification.

**Comment by nitisht** [comment] 2020-01-20 16:42
closing this based on previous comments

**Closed as completed by nitisht** 2020-01-20 16:42 UTC
Labels: working as intended
