### ISSUE TITLE
[distributed]: incorrect message when bucket does not exist

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#2496] opened 2016-08-19 17:10 UTC
```
krishna@escape:~$ mc cp /etc/passwd myminio6/testbucket
mc: <ERROR> Failed to copy ‘/etc/passwd’. Object key is missing, object key cannot be empty
krishna@escape:~$ mc mb myminio6/testbucket
Bucket created successfully ‘myminio6/testbucket’.
krishna@escape:~$ mc cp /etc/passwd myminio6/testbucket
/etc/passwd:    2.15 KB / 2.15 KB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 153.68 KB/s 0krishna@escape:~$ 
```

Incorrect error during `mc cp` if the bucket does not exist. Should have got `NoSuchBucket`

**Comment by harshavardhana** [comment] 2016-08-19 19:20
Not able to reproduce this with latest 'mc' 

```
$ mc cp /etc/passwd dist-harsha/test
mc: <ERROR> Failed to copy ‘/etc/passwd’. Object key is missing, object key cannot be empty
```

```
mc cp /etc/passwd dist-harsha/test
mc: <ERROR> Failed to copy ‘/etc/passwd’. Object key is missing, object key cannot be empty
```

**Comment by krishnasrinivas** [comment] 2016-08-19 19:22
> Not able to reproduce this with latest 'mc'
> 
> $ mc cp /etc/passwd dist-harsha/test
> mc: <ERROR> Failed to copy ‘/etc/passwd’. Object key is missing, object key cannot be empty

@harshavardhana you are able to repro it `Object key is missing, object key cannot be empty`

**Comment by harshavardhana** [comment] 2016-08-19 19:48
> @harshavardhana you are able to repro it Object key is missing, object key cannot be empty

Oh yes its an 'mc' bug the behavior is strange. 

```
$ mc cp --debug /etc/passwd dist-harsha/test

mc: <DEBUG> GET /test/?location= HTTP/1.1
Host: 65.19.167.91:42001
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=abcd123/20160819/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160819T194708Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 19 Aug 2016 19:47:08 GMT
Server: Minio/DEVELOPMENT.2016-08-19T19-12-51Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: OYMCT9QBU6Z25XJB

f6
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key></Key><BucketName></BucketName><Resource>/test/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  4.68822ms

mc: <ERROR> Failed to copy ‘/etc/passwd’. Object key is missing, object key cannot be empty
 (3) cp-main.go:346 cmd.doCopySession.func1(..) Tags: [/etc/passwd]
 (2) cp-main.go:207 cmd.doCopy(..) Tags: [http://65.19.167.91:42001/test]
 (1) common-methods.go:85 cmd.putTargetStreamFromAlias(..) Tags: [dist-harsha, http://65.19.167.91:42001/test]
 (0) client-s3.go:616 cmd.(*s3Client).Put(..)
 Commit:DEVELOPMENT. | Release-Tag:DEVELOPMENT.GOGET | Host:minio1 | OS:linux | Arch:amd64 | Lang:go1.6 | Mem:1.5MB/9.6MB | Heap:1.5MB/5.7MB
minio@minio1:~/gopath/src/github.com/minio$ mc cp --debug /etc/passwd dist-harsha/test
```

```
$ mc cp --debug /etc/passwd dist-harsha/test/

mc: <DEBUG> GET /test/?location= HTTP/1.1
Host: 65.19.167.91:42001
User-Agent: Minio (linux; amd64) minio-go/2.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=abcd123/20160819/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160819T194736Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 19 Aug 2016 19:47:36 GMT
Server: Minio/DEVELOPMENT.2016-08-19T19-12-51Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: UQ57KF7P173YIOKI

f6
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key></Key><BucketName></BucketName><Resource>/test/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  4.574241ms

mc: <ERROR> Failed to copy ‘/etc/passwd’. Bucket ‘test’ does not exist.
 (3) cp-main.go:346 cmd.doCopySession.func1(..) Tags: [/etc/passwd]
 (2) cp-main.go:207 cmd.doCopy(..) Tags: [http://65.19.167.91:42001/test/passwd]
 (1) common-methods.go:85 cmd.putTargetStreamFromAlias(..) Tags: [dist-harsha, http://65.19.167.91:42001/test/passwd]
 (0) client-s3.go:608 cmd.(*s3Client).Put(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:minio1 | OS:linux | Arch:amd64 
```

**Comment by harshavardhana** [comment] 2016-08-19 20:40
Closing this and moving this to mc

**Closed as completed by harshavardhana** 2016-08-19 20:40 UTC

**Comment by kahing** [comment] 2016-09-20 06:06
a similar problem occur when you head the bucket anonymously. aws s3 returns 404 and play.minio.io returns 403:

```
---[ REQUEST POST-SIGN ]-----------------------------
HEAD http://play.minio.io:9000/goofys-test2 HTTP/1.1
Host: play.minio.io:9000
User-Agent: aws-sdk-go/1.0.0 (go1.7; linux; amd64)


-----------------------------------------------------
2016/09/19 23:05:22.943659 s3.DEBUG DEBUG: Response s3/HeadBucket Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 403 Forbidden
Connection: close
Accept-Ranges: bytes
Content-Type: text/plain; charset=utf-8
Date: Tue, 20 Sep 2016 06:05:22 GMT
Server: Minio/DEVELOPMENT.2016-09-16T07-48-17Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 4WBP09CQXPC4DIB0
```

vs

```
---[ REQUEST POST-SIGN ]-----------------------------
HEAD http://s3.amazonaws.com/goofys-test2 HTTP/1.1
Host: s3.amazonaws.com
User-Agent: aws-sdk-go/1.0.0 (go1.7; linux; amd64)


-----------------------------------------------------
2016/09/19 23:03:45.835491 s3.DEBUG DEBUG: Response s3/HeadBucket Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Tue, 20 Sep 2016 06:03:45 GMT
Server: AmazonS3
X-Amz-Id-2: Nzv7nMx/i3TdNh1G8BKMP/Sh8+iIL1238+JWRss+Yznu9brhUBQoiDQ0sCMGHNrZsj0rKLEPuJk=
X-Amz-Request-Id: 4D76CA991D9D664F
```
