### ISSUE TITLE
Minio returns 403 on not existing files

### ISSUE THREAD

**Issue by blacksavior** [minio/minio#3753] opened 2017-02-16 14:23 UTC
## Expected Behavior
HTTP-Code 404 on requesting a non existing file
eg http://myHost/myBucket/wrongFile.jpg

## Current Behavior
403 Forbidden with Body:
`<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied.</Message>
    <Key></Key>
    <BucketName></BucketName>
    <Resource>/myBucket/wrongFile.jpg</Resource>
    <RequestId>3L137</RequestId>
    <HostId>3L137</HostId>
</Error>`

## Your Environment
Docker Image: minio/minio
Version 2017-01-25T03:14:52Z

**Comment by vadmeste** [comment] 2017-02-16 14:32
@blacksavior, this is expected if you are not sending authenticated requests. Can you tell us why do you think Minio should send 404 ?

**Comment by blacksavior** [comment] 2017-02-16 14:44
Hi and thanks for the fast answer. The Bucket is configured as read only. So everyone in the LAN segment can fetch all files from it without key/secret. In this context we do not understand, why the user is allowed to get files, but not allowed to see if one is missing. Further we have followup processes like image scaler. If such a process gets an 403 it must process it as an server side error, an missconfiguration on our side and the scaler can response with 500 and inform the admins. If it gets an 404 from minio, the user just requested an wrong image... so the scaler can response with 404 too. 

Best Regards Oliver

**Comment by vadmeste** [comment] 2017-02-16 14:57
@blacksavior, in my case, Minio returns http 404 when I configure a bucket as read only using mc. Can you tell us how are you setting your bucket as read only ?

**Comment by blacksavior** [comment] 2017-02-16 15:06
We set the policy via the minio browser. 

No we tried to get the policies via "mc policy myHost/myBucket" an we saw.... nothing. No policies. In minio Browser e saw "*" with read only. We tried to set a new Policy via mc and got an conflict. Then we removed the policy via Minio Browser and then set a new one via mc... now it works. We get 404s on missing files. 

Thanks for the fast help!

I think there my be a bug in the Minio Browser?!

**Comment by harshavardhana** [comment] 2017-02-16 17:31
@blacksavior - most probably it's a bug in browser code. We will verify and fix it thanks for opening the bug.

**Comment by harshavardhana** [comment] 2017-02-20 02:23
> Your Environment
> 
> Docker Image: minio/minio
> Version 2017-01-25T03:14:52Z

Can you test with the latest release @blacksavior ?

**Comment by harshavardhana** [comment] 2017-02-26 20:09
Not able to reproduce with current master closing this bug. 

Set the browser read-only policy

![policy-readonly](https://cloud.githubusercontent.com/assets/622699/23343187/4ff223b2-fc1c-11e6-8c19-178d83961525.png)

With `mc`

```sh
mc policy list myminio/ferenginar
ferenginar/* => readonly
```

Then try to download a non-existent file

```sh
curl http://localhost:9000/ferenginar/1.jpg
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/ferenginar/1.jpg</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```

**Closed as completed by harshavardhana** 2017-02-26 20:09 UTC
Labels: community
