### ISSUE TITLE
if the MINIO_ROOT_USER is changed, all its existing "service accounts" are orphaned

### ISSUE THREAD

**Issue by Aaron-PanJi** [minio/minio#17568] opened 2023-07-04 09:23 UTC
## Expected Behavior
none

## Current Behavior
If the MINIO_ROOT_USER is changed while it has one or more "service accounts" (the ones you create with mc admin user svcacct add), those service accounts are not migrated to the new user, and continue to exist.

This can easily be verified by using mc admin user svcacct info myminio "orphan_service_account", which will return that the account exists, but under the old value of MINIO_ROOT_USER.

As far as I know, because the old MINIO_ROOT_USER no longer exists (and therefore has no access from MinIO's perspective), these orphaned users have no access beyond the ability to log in.

## Possible Solution
When the value of MINIO_ROOT_USER is changed these service accounts should be migrated to the new root user.

If this is not possible, we must at least delete them, so that they don't clog up the cluster (and also prevent new service accounts from being created with the same name in the future, as they are unique cluster-wide).

## Steps to Reproduce (for bugs)
none

## Your Environment

* Version used (`minio --version`): RELEASE.2023-06-29T05-12-28Z

**Comment by klauspost** [comment] 2023-07-04 09:53
From a security perspective we can't migrate the users AFAICT, since the current behavior is expected and could be actively utilized. Deleting them seems like a risky, potentially destructive operation since a configuration mistake could delete all of them - and you can't just temporarily change the root user to disable all access.

So not really a fan of either of the proposed alternatives.

**Comment by harshavardhana** [comment] 2023-07-04 14:37
Looks like a duplicate of #17565

**Closed by harshavardhana** 2023-07-04 14:37 UTC
Labels: community, triage

**Comment by thesuperzapper** [comment] 2023-07-04 19:53
@harshavardhana @klauspost this account is clearly a bot, it's very strange, it literally replicated my issue word-for-work: https://github.com/minio/minio/issues/17565

I have reported them to github, but its just a heads up.

**Comment by harshavardhana** [comment] 2023-07-04 21:48
@thesuperzapper that's fine you are good.
