### ISSUE TITLE
Creating a new bucket with mc doesn't work.

### ISSUE THREAD

**Issue by Rillian-Grant** [minio/minio#6271] opened 2018-08-12 13:45 UTC
Creating a new bucket with mc doesn't work.

## Current Behavior

When you run:
```
mc mb somebucket 
```
It returns: Bucket created successfully ...

But this buket does not get created.

## Your Environment

This was run on a RPi 3B+
# I was using mc and minio compiled from github using go get.

**Comment by nitisht** [comment] 2018-08-12 14:29
hey @Rillian-Grant can you try `mc mb myminio/somebucket` (`myminio` is the alias) [Ref: https://docs.minio.io/docs/minio-client-quickstart-guide.html]

**Comment by kannappanr** [comment] 2018-08-12 23:38
@Rillian-Grant The command you are trying would end up creating a local directory named `somebucket`. `mc` also works on local filesystem. 

You can store credentials for multiple `minio/S3` services using and mc and would need to access the buckets within a certain `s3` server as described in the previous comment.

I am closing this issue as working as intended. Please feel free to reach out to us, if you have further questions.

**Closed as completed by kannappanr** 2018-08-12 23:38 UTC
Labels: working as intended, community, priority: medium
