### ISSUE TITLE
minio client killed due to out-of-memory when using `mc copy`

### ISSUE THREAD

**Issue by 15laterals** [minio/minio#11780] opened 2021-03-13 15:30 UTC
Running `mc cp -r my_data/ data/test/` starts out consuming 27 GB of memory, then increases to ~80 GB of memory for a period of time before finally taking off and consuming ~128 GB of memory resulting in the client being killed by `oom_reaper`.

## Expected Behavior
The `mc cp` operation should complete while using less than 128 GB of memory. 

## Current Behavior
The `mc cp` operation consumes increasing amounts of memory until it is ultimately killed by the kernel.
From `dmesg`:
```
[79609.746941] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-2.scope,task=mc,pid=67035,uid=1000
[79609.747047] Out of memory: Killed process 67035 (mc) total-vm:127929908kB, anon-rss:115418676kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:227112kB oom_score_adj:0
[79611.162750] oom_reaper: reaped process 67035 (mc), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

## Steps to Reproduce (for bugs)
1. Start minio server using something like: `minio server /mnt/minio-data{0...9}`
2. On the same machine, create a directory to store some data, then create a bunch of ~400 MB files to copy using something like:
```
mkdir my_data
cd my_data
for n in $(seq 0 1000)
do
    fallocate -l 400m data${n}.bin
done
```
3. Create a bucket to cp the data to using something like: `mc mb <MINIO_SERVER>/test`
4. Copy the data using the minio client w/ something like: `mc cp -r my_data/ data/test/`
5. Observe the client fire off ~150-250 threads (`pstree $PID`) which collectively consume increasing amounts of memory

## Context
Testing server setup and copying files to the minio server

## Regression
Unsure, I haven't tried other versions

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2021-03-10T05-11-33Z; mc version RELEASE.2021-03-12T03-36-59Z
* Server setup and configuration: Ubuntu 20.04, transferring data from an NVMe drive on the server to a 10 HDD minio array.
* Operating System and version (`uname -a`): Linux beast1 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment] 2021-03-13 17:39
Set GOMAXPROCS=4 or something to avoid high memory usage when system doesn't have enough memory.

**Comment by harshavardhana** [comment] 2021-03-13 17:40
Also a duplicate of https://github.com/minio/mc/issues/3376

**Closed as completed by harshavardhana** 2021-03-13 17:39 UTC
Labels: community, triage

**Comment by 15laterals** [comment] 2021-03-14 02:19
Thanks @harshavardhana , sure enough that works to prevent memory running away to the point that the `oom_reaper` has to come along and take care of things. That said, it seems surprising that even w/ `GOMAXPROCS=1` the `mc` client ends up using 50-60 GB of RAM, and that in the default condition (without setting `GOMAXPROCS`) it ended up exhausting 128 GB of RAM?

**Comment by harshavardhana** [comment] 2021-03-14 02:37
> Thanks @harshavardhana , sure enough that works to prevent memory running away to the point that the `oom_reaper` has to come along and take care of things. That said, it seems surprising that even w/ `GOMAXPROCS=1` the `mc` client ends up using 50-60 GB of RAM, and that in the default condition (without setting `GOMAXPROCS`) it ended up exhausting 128 GB of RAM?

Unfortunately we need memory for mc - we plan to fix it in time.. just set GOMAXPROCS for now.
