### ISSUE TITLE
[distributed] s3verify Abort Upload test fails

### ISSUE THREAD

**Issue by krisis** [minio/minio#3031] opened 2016-10-21 11:51 UTC
## Expected behaviour

Abort Multipart Upload s3verify test passes on Minio distributed setup
## Actual behaviour

```
s3verify: <DEBUG> DELETE /s3verify-tmp-bkt0/s3verify/multipart/abort?uploadId=57cacf7f-b777-47ca-8e1c-970bfdc8f322 HTTP/1.1
Host: 147.75.201.115:9000
User-Agent: Minio (linux; amd64) s3verify/1.0.0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161021/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161021T112937Z
Accept-Encoding: gzip

s3verify: <DEBUG> HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 21 Oct 2016 11:29:37 GMT
Server: Minio/DEVELOPMENT.2016-10-20T06-42-19Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 4JM5AAZMPNKHND8T

12c
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Key></Key><BucketName></BucketName><Resource>/s3verify-tmp-bkt0/s3verify/multipart/abort</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

s3verify: <DEBUG> Response Time:  14.418387ms

s3verify: <DEBUG> DELETE /s3verify-tmp-bkt0/s3verify/multipart/abort?uploadId=57cacf7f-b777-47ca-8e1c-970bfdc8f322 HTTP/1.1
Host: 147.75.201.115:9000
User-Agent: Minio (linux; amd64) s3verify/1.0.0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161021/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161021T112937Z
Accept-Encoding: gzip

s3verify: <DEBUG> HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Fri, 21 Oct 2016 11:29:37 GMT
Server: Minio/DEVELOPMENT.2016-10-20T06-42-19Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: G2LOIGMSYOSLL5YP

176
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message><Key></Key><BucketName></BucketName><Resource>/s3verify-tmp-bkt0/s3verify/multipart/abort</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

s3verify: <DEBUG> Response Time:  24.587466ms

[20/20] Multipart (Abort Upload):                 [FAIL]
Unexpected Status Received: wanted 204, got 404

```
## Steps to reproduce the behaviour
- Run `s3verify` on Minio distribued setup.
## Minio version

Latest master
## System information

GNU/Linux

**Comment by harshavardhana** [comment] 2016-10-21 14:07
Is this reproducible on FS or single node XL?

**Comment by krisis** [comment] 2016-10-21 14:12
@harshavardhana it is not reproducible in FS or in single-node XL.

**Comment by harshavardhana** [comment] 2016-10-22 06:40
This is something related to what @donatello recently experienced as well symptoms are rather same - https://github.com/minio/minio/issues/3014

**Comment by vadmeste** [comment] 2016-10-22 15:47
> it is not reproducible in FS or in single-node XL.

@krisis, can you check again? I am not able to reproduce it with distributed 4 and 16 disks.

**Comment by krisis** [comment] 2016-10-24 05:26
@vadmeste, I am unable to reproduce this on single-node XL or FS anymore. Incidentally, I am unable to recreate it with a local docker-compose based setup with 4 disks too.

**Comment by harshavardhana** [comment] 2016-10-24 06:01
> @vadmeste, I am unable to reproduce this on single-node XL or FS anymore. Incidentally, I am unable to recreate it with a local docker-compose based setup with 4 disks too.

Can you increase the number to 16 servers?

**Comment by GarimaKapoor** [comment] 2016-10-25 21:48
@vadmeste please update the status of this issue.

**Comment by vadmeste** [comment] 2016-10-26 09:14
@krisis, did you try with 16 disks ?

@GarimaKapoor, waiting for @krisis answer.. wasn't able to reproduce this bug.

**Comment by krisis** [comment] 2016-10-26 11:05
@vadmeste I couldn't reproduce the bug with 16 disks docker-compose based setup.

**Comment by krisis** [comment] 2016-10-26 11:06
I couldn't reproduce the issue with a 16 disks docker-compose based setup.

**Comment by harshavardhana** [comment] 2016-10-26 15:46
Closing the issue for now.

**Closed as completed by harshavardhana** 2016-10-26 15:46 UTC
