### ISSUE TITLE
Can't delete bucket 

### ISSUE THREAD

**Issue by annkam** [minio/minio#11152] opened 2020-12-22 06:50 UTC
![image](https://user-images.githubusercontent.com/18022078/102856493-29dc1780-4459-11eb-832a-9b91d3c007f0.png)

However, it's not gone. When I run `mc ls` on this bucket, it says that it's empty. Also, it takes more than an hour to call `mc ls` on this bucket:

```
$ time mc ls staas-direct/cfl

real    70m13,476s
user    0m0,307s
sys     0m0,812s
```

If I inspect the data dir on Minio node, I can see that there are still some files there.
Minio bucket metrics report that there're 6 millions of objects consuming 257 Gb. At the same time, ListObjects returns nothing...
Is there any way to delete this  bucket besides from deleting all files directly from the filesystem? I don't think it's a normal solution. I've been struggling to delete this bucket for weeks.

My setup is 12-node cluster, version is 2020-10-28T08-16-50Z

**Comment by harshavardhana** [comment] 2020-12-22 06:52
mc rb --force --versions @annkam

**Comment by annkam** [comment] 2020-12-22 06:59
Did you mean `mc rm`? `mc rb` doesn't have such flag. I will try this, but I can't delete this bucket since RELEASE.2020-05-01T22-19-14Z and versioning is not enabled.

**Comment by harshavardhana** [comment] 2020-12-22 07:38
> Did you mean `mc rm`? `mc rb` doesn't have such flag. I will try this, but I can't delete this bucket since RELEASE.2020-05-01T22-19-14Z and versioning is not enabled.

you are using such an old `mc` it won't support versioning flags, the reason your bucket listing takes long because you have created lots of delete markers and versions. 

Update your `mc` and perform `mc ls --versions` call to see what all objects are lying around.

**Comment by annkam** [comment] 2020-12-22 07:40
mc is RELEASE.2020-11-17T00-39-14Z, it's not that old, newer than the server. No --versions flag for `mc rb` command. That's why I asked if you meant `mc rm`.
I wrote that I can't delete the bucket since my server was on RELEASE.2020-05-01T22-19-14Z and later and I have never enabled versioning for this bucket.

```
$ mc rb --help
NAME:
  mc rb - remove a bucket

USAGE:
  mc rb [FLAGS] TARGET [TARGET...]

FLAGS:
  --force                       force a recursive remove operation on all object versions
  --dangerous                   allow site-wide removal of objects
  --config-dir value, -C value  path to configuration folder (default: "/home/ereshkigal/.mc")
  --quiet, -q                   disable progress bar display
  --no-color                    disable color theme
  --json                        enable JSON lines formatted output
  --debug                       enable debug output
  --insecure                    disable SSL certificate verification
  --help, -h                    show help
```

```
$ mc version info staas-direct/cfl
staas/cfl is un-versioned
```

**Comment by kannappanr** [comment] 2020-12-22 07:52
@annkam How are your objects distributed for the `cfl` bucket. Is it a flat namespace with most of the objects directly under this bucket?
Just to be clear, your `mc` version is `RELEASE.2020-11-17T00-39-14Z` and did you upgrade your minio version from `RELEASE.2020-05-01T22-19-14Z` to `2020-10-28T08-16-50Z` ?

**Comment by annkam** [comment] 2020-12-22 07:53
Yes, unfortunately, all the objects are lying in the bucket root. 
> Just to be clear, your mc version is RELEASE.2020-11-17T00-39-14Z and did you upgrade your minio version from RELEASE.2020-05-01T22-19-14Z to 2020-10-28T08-16-50Z ?

Yes, that's correct.

**Comment by annkam** [comment] 2020-12-22 08:02
It happens all the time - it's a regular situation that we can't delete some folders in different buckets - `mc rm` reports success and the folders are still there. This behavior causes problems with many software like Spark or Dremio. Again, versioning is not enabled. We solve this by deleting files directly from the file system on each node and now we can't delete even an "empty" (according to `mc ls`) bucket and I don't really want to use the direct deletion from the filesystem approach again, I want to understand why is this happening and if it's a bug.

**Comment by annkam** [comment] 2020-12-22 08:14
We experienced such problems with releases RELEASE.2020-05-01T22-19-14Z, RELEASE.2020-10-28T08-16-50Z  and RELEASE.2020-12-16T05-05-17Z.

**Comment by harshavardhana** [comment] 2020-12-22 09:16
@annkam we don't have a way to reproduce them - neither we have seen this with any other customers we have. Unless you can reproduce this conclusively and provide us a reproducer. I don't think I can help you any further.

**Comment by harshavardhana** [comment] 2021-01-12 10:36
Nothing actionable from our end closing, no way to reproduce the issue.

**Closed as completed by harshavardhana** 2021-01-12 10:36 UTC
Labels: community, triage

**Comment by salacr** [comment] 2021-01-25 13:55
Just FIY this is definitely a bug I have simmilar issue #10288. (already closed as cannot reproduce), also I have this funny message when I tried it with the newest client:
```
mc: <ERROR> Failed to remove `develop/wasabi-benchmark-bucket`, continuing.. Please reduce your request
Removed `develop/wasabi-benchmark-bucket` successfully.
```
