### ISSUE TITLE
config.json shows the expiration 1970-01-01T00:00:00Z

### ISSUE THREAD

**Issue by selvakumardreams** [minio/minio#7789] opened 2019-06-14 14:55 UTC
Expiration date & time show too old.

System current date: Fri Jun 14 16:27:13 CEST 2019

## Expected Behavior
"credential": {
		"accessKey": "",
		"secretKey": "",
		"expiration": "2019-09-14T00:00:00Z",
		"status": "enabled"
	},

## Current Behavior
"credential": {
		"accessKey": "",
		"secretKey": "",
		"expiration": "1970-01-01T00:00:00Z",
		"status": "enabled"
	},

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
Version: 2019-06-13T01:41:13Z
Release-Tag: RELEASE.2019-06-13T01-41-13Z
Commit-ID: c22439c82e5679175a99b051d10fac48cd311af0

* Environment name and version (e.g. nginx 1.9.1):
GNU/Linux
* Server type and version:
* Operating System and version (`uname -a`):
Linux  4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by harshavardhana** [comment] 2019-06-14 16:13
This is expected @selvakumardreams it means that your root creds do not expire.

**Comment by kannappanr** [comment] 2019-06-14 19:50
@selvakumardreams Closing this issue as working as intended. Please feel free to re-open if you feel otherwise

**Closed as completed by kannappanr** 2019-06-14 19:50 UTC
Labels: working as intended, community
