### ISSUE TITLE
Cannot delete object from Minio

### ISSUE THREAD

**Issue by csbarry** [minio/minio#11704] opened 2021-03-04 21:12 UTC
When trying to delete a file from minio I receive a 503 service not availabe error, but there are currently minio reads and writes occuring during this process so we know the system is up and running.

I can do an ls on the file, but I cannot stat the file

mc rm  s3-nvme//services-splunk-ffc-prod/filelocation6879_ff/db/74/1e/67~C30BD5FC-B802-4827-B3D4-4C038839D7F3/guidSplunk-C30BD5FC-B802-4827-B3D4-4C038839D7F3/Sources.data
mc: <ERROR> Failed to remove `s3-nvme//services-splunk-ffc-prod/filelocation6879_ff/db/74/1e/67~C30BD5FC-B802-4827-B3D4-4C038839D7F3/guidSplunk-C30BD5FC-B802-4827-B3D4-4C038839D7F3/Sources.data`. 503 Service Unavailable
 
 mc ls   s3-nvme//services-splunk-ffc-prod/filelocation6879_ff/db/74/1e/67~C30BD5FC-B802-4827-B3D4-4C038839D7F3/guidSplunk-C30BD5FC-B802-4827-B3D4-4C038839D7F3/Sources.data
[2021-02-26 19:23:04 GMT]  46KiB Sources.data

 mc stat  s3-nvme//services-splunk-ffc-prod/filelocation6879_ff/db/74/1e/67~C30BD5FC-B802-4827-B3D4-4C038839D7F3/guidSplunk-C30BD5FC-B802-4827-B3D4-4C038839D7F3/Sources.data
mc: <ERROR> Unable to stat `s3-nvme//services-splunk-ffc-prod/filelocation6879_ff/db/74/1e/67~C30BD5FC-B802-4827-B3D4-4C038839D7F3/guidSplunk-C30BD5FC-B802-4827-B3D4-4C038839D7F3/Sources.data`. Target `s3-nvme//services-splunk-ffc-prod/filelocation6879_ff/db/74/1e/67~C30BD5FC-B802-4827-B3D4-4C038839D7F3/guidSplunk-C30BD5FC-B802-4827-B3D4-4C038839D7F3/Sources.data` not found.

Hwever I can still the data on the disks on the servers

## Expected Behavior
The file should be expunged from within minio

## Current Behavior
As above error 503 service not available occurs, only on this file I can remove other files within the same bucket and folder

## Context
Application writing to minio is now failing due to the error to update / remove file

## Regression
No

## Your Environment
24 node cluster running on ubuntu 18.04
Minio version 2021-03-01T04

**Comment by csbarry** [comment] 2021-03-05 12:05
I just uploaded a test file to see what stat would do, and I seem to have the same error with that file

mc stat s3-nvme//chrisb/testfile
mc: <ERROR> Unable to stat `s3-nvme//chrisb/testfile`. Target `s3-nvme//chrisb/testfile` not found.

mc ls s3-nvme//chrisb/testfile  --json
{
 "status": "success",
 "type": "file",
 "lastModified": "2021-03-04T17:13:41.426Z",
 "size": 52428800,
 "key": "testfile",
 "etag": "d429a3918607c37b746b0223afc53398",
 "url": "https://minio-poc:443/chrisb/testfile",
 "versionOrdinal": 1
}

However I can delete this file, unlike the file that we are unable to delete.

mc rm s3-nvme//chrisb/testfile
Removing `s3-nvme//chrisb/testfile`.

mc ls s3-nvme//chrisb/
-

**Comment by csbarry** [comment] 2021-03-08 15:48
Can I have an update on this issue please?

**Comment by harshavardhana** [comment] 2021-03-09 21:23
> Can I have an update on this issue please?

Currently working on other high-priority issues, will get back here - feel free to share the logs from the server where the delete fails - will circle back based on that.

**Comment by csbarry** [comment] 2021-03-12 10:38
We have managed to expunge the offending files from the back end, by stopping minio and then deleting the files off the disks and starting Minio up again.
This has allowed us to unblock the problems that were preventing us moving forward with Minio POC.

**Comment by harshavardhana** [comment] 2021-03-21 05:20
We couldn't reproduce it and we haven't seen any reports elsewhere.

Closing this as a non issue at the moment.

**Closed as completed by harshavardhana** 2021-03-21 05:20 UTC
Labels: working as intended, community, incomplete info
