### ISSUE TITLE
[fs] atomic completeMulipartUpload on AUFS/Overlay filesystem?

### ISSUE THREAD

**Issue by olalonde** [minio/minio#3118] opened 2016-10-28 05:40 UTC
I have tests which use [aws-sdk-js](https://github.com/aws/aws-sdk-js) and minio/minio (latest version) running in docker (Docker for Mac). Here's my docker-compose.yml file:

```
minio:
  image: minio/minio
  command: server /export
  ports:
    - "9000:9000"
  environment:
    - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
    - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    - "MINIO_ENABLE_FSMETA=true"
```

One of my tests, completes a multipart upload, waits for that request to complete and immediately tries to download the file. Most of the time, this works fine but sometimes I get the following error when downloading the file:

``` javascript
error: { StreamContentLengthMismatch: Stream content length mismatch. Received 1409024 of 1431345bytes.
    at PassThrough.checkContentLengthAndEmit (node_modules/aws-sdk/lib/request.js:599:15)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  message: 'Stream content length mismatch. Received 1409024 of 1431345 bytes.',
  code: 'StreamContentLengthMismatch',
  time: 2016-10-28T05:28:58.280Z }
```

This error is thrown by aws-sdk-js when a response it received had less bytes than the `Content-Length` header I believe. I've verified that the Content-Length it returns is the actual size of the file. Is there any reason why minio would return the right Content-Length but return an incomplete file or close the connection early before all bytes have been transferred?

Docker for Mac uses AUFS as a storage layer and `rename` operation is a bit funky (it can throw unexpectedly sometimes). Just a guess.

**Comment by olalonde** [comment] 2016-10-28 05:45
I haven't been able to reproduce the issue when running minio locally on OS X (not on Docker) so far. But it's hard to tell because it looks like a race issue and even on Docker I'm not always seeing that error.

**Comment by olalonde** [comment] 2016-10-28 05:47
From http://aufs.sourceforge.net/aufs.html

> To rename(2) directory may return EXDEV even if both of src and tgt are on the same aufs. When the rename-src dir exists on multiple branches and the lower dir has child(ren), aufs has to copyup all his children. It can be recursive copyup. Current aufs does not support such huge copyup operation at one time in kernel space, instead produces a warning and returns EXDEV. Generally, mv(1) detects this error and tries mkdir(2) and rename(2) or copy/unlink recursively. So the result is harmless. If your application which issues rename(2) for a directory does not support EXDEV, it will not work on aufs. Also this specification is applied to the case when the src directroy exists on the lower readonly branch and it has child(ren).

**Comment by harshavardhana** [comment] 2016-10-28 06:19
Thanks @olalonde

**Comment by krishnasrinivas** [comment] 2016-10-28 06:21
@olalonde does minio print any logs related to this?
Also can you check if mounting host directory in to the container's /export fixes the problem? (mostly it does, like you said it is mostly an aufs related issue, mostly rename)

**Comment by krishnasrinivas** [comment] 2016-10-30 08:33
@olalonde can you post your test script here?

**Comment by olalonde** [comment] 2016-10-31 00:01
My test script does a bunch of other things, but I'll try to see if I can reproduce with something more simple

**Comment by olalonde** [comment] 2016-10-31 00:09
If you git clone https://github.com/blockai/s3-tus-store/, run `npm install; docker-compose up -d` and then run `while 1; do npm test && sleep 1; done;`, you should see the error after a couple of times:

```
TAP version 13
# setup
# testing with minPartSize = 5242880
# info - unknown upload
ok 1 should be truthy
# create foo (minPartSize + 1)
# create another upload for same key
ok 2 should not be equal
# info after create
ok 3 should be equal
ok 4 should be equal
ok 5 should be equal
# append random data (minPartSize bytes)
ok 6 should be equal
# info after first append
ok 7 should be equal
ok 8 should be equal
# wrong offset passed to append
ok 9 should be truthy
# append last byte (!)
ok 10 should be equal
ok 11 should be equal
ok 12 should be equal
# info after upload complete
ok 13 should be equal
ok 14 should be equal
# readStream foo
not ok 15 StreamContentLengthMismatch: Stream content length mismatch. Received 5177027 of 5242881 bytes.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [StreamContentLengthMismatch: Stream content length mismatch. Received 5177027 of 5242881 bytes.] message: 'Stream content length mismatch. Received 5177027 of 5242881 bytes.', code: 'StreamContentLengthMismatch', time: Sun Oct 30 2016 17:05:02 GMT-0700 (PDT) }
    at: Duplexify._destroy (/Users/olalonde/code/blockai/s3-tus-store/node_modules/duplexify/index.js:183:15)
    stack: |-
      StreamContentLengthMismatch: Stream content length mismatch. Received 5177027 of 5242881 bytes.
          at PassThrough.checkContentLengthAndEmit (/Users/olalonde/code/blockai/s3-tus-store/node_modules/aws-sdk/lib/request.js:599:15)
          at emitNone (events.js:91:20)
          at PassThrough.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  ...
not ok 16 test exited without ending
  ---
    operator: fail
  ...
not ok 17 test exited without ending
  ---
    operator: fail
  ...
not ok 18 test exited without ending
  ---
    operator: fail
  ...
```

`DEBUG=s3-tus-store:* npm test` should give a bit more verbose output.

Unfortunately, it will not fail every time and it's hard to tell what's going on because the actual test code is in https://github.com/blockai/abstract-tus-store/blob/master/src/tests/index.js. Basically, it completes the multipart upload when [appending the last byte](https://github.com/blockai/abstract-tus-store/blob/master/src/tests/index.js#L95) and then tries to [read the key](https://github.com/blockai/abstract-tus-store/blob/master/src/tests/index.js#L110) of that completed multipart upload.

Here's where the call to the aws-sdk-js library is: https://github.com/blockai/s3-tus-store/blob/master/src/index.js#L254. If you have `DEBUG=s3-tus-store:*` set, you should see `s3.completeMultipartUpload end` before the read stream test is executed, confirming that the multipart upload should have been successfully completed by then.

I've tested with Docker for Mac and:

``` bash
$ node --version
v6.6.0
$ docker --version
Docker version 1.12.1, build 6f9534c
$ docker-compose --version
docker-compose version 1.8.0, build f3628c7
```

**Comment by koolhead17** [comment] 2016-11-01 12:19
@harshavardhana  is this is a bug or an aufs limitation that needs to be documented under docker section, please advice.

**Comment by harshavardhana** [comment] 2016-11-01 16:41
We need to test and validate. Then document the behavior.

**Comment by krishnasrinivas** [comment] 2016-11-03 15:08
@olalonde i ran `npm test` in a while loop and it consistently ran fine. i ran minio on aufs as well as externally host mapped directory. It ran fine:

```
> s3-tus-store@1.2.4 pretest /home/krishna/dev/s3-tus-store
> npm run lint


> s3-tus-store@1.2.4 lint /home/krishna/dev/s3-tus-store
> eslint src/ test/


> s3-tus-store@1.2.4 test /home/krishna/dev/s3-tus-store
> nyc npm run test:fast


> s3-tus-store@1.2.4 test:fast /home/krishna/dev/s3-tus-store
> babel-tape-runner test/*.test.js

TAP version 13
# setup
# testing with minPartSize = 5242880
# info - unknown upload
ok 1 should be truthy
# create foo (minPartSize + 1)
# create another upload for same key
ok 2 should not be equal
# info after create
ok 3 should be equal
ok 4 should be equal
ok 5 should be equal
# append random data (minPartSize bytes)
ok 6 should be equal
# info after first append
ok 7 should be equal
ok 8 should be equal
# wrong offset passed to append
ok 9 should be truthy
# append last byte (!)
ok 10 should be equal
ok 11 should be equal
ok 12 should be equal
# info after upload complete
ok 13 should be equal
ok 14 should be equal
# readStream foo
ok 15 should be equivalent
# finish second upload
# readStream foo after second upload finished
ok 16 should be equivalent
# readStream onInfo callback
ok 17 should be equal
ok 18 should be equivalent
ok 19 should be equivalent
# non latin chars in metadata
ok 20 should be equal
# beforeComplete is called
ok 21 should be equivalent
ok 22 should be equivalent
ok 23 should be equivalent
ok 24 should be equal
ok 25 should be equal
ok 26 should be equal
# teardown

1..26
# tests 26
# pass  26

# ok

-----------------------|----------|----------|----------|----------|----------------|
File                   |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------------|----------|----------|----------|----------|----------------|
All files              |    93.77 |    70.51 |    95.71 |    95.14 |                |
 eos.js                |    85.71 |    83.33 |      100 |      100 |                |
 index.js              |    96.95 |       75 |      100 |    96.38 |... 202,212,222 |
 tmp-file.js           |    90.63 |       50 |      100 |      100 |                |
 write-part-by-part.js |    89.53 |    64.29 |       85 |    90.91 |... 196,197,204 |
-----------------------|----------|----------|----------|----------|----------------|
```

But my test was on ubuntu.

Was there anything parallel that would access minio server?

Is the following error consistent:

```
not ok 15 StreamContentLengthMismatch: Stream content length mismatch. Received 5177027 of 5242881 bytes.
```

i.e does it always receive only 5177027 when error occurs?

Is there any log on minio server when this error happens?

**Comment by olalonde** [comment] 2016-11-03 18:50
@krishnasrinivas you have to run the tests for a couple of times before any error happens (nothing else is using minio). I'm not seeing any logs using `docker-compose logs minio`, does minio write logs somewhere on disk?

**Comment by krishnasrinivas** [comment] 2016-11-03 18:54
@olalonde note:

> @olalonde i ran npm test in a while loop and it consistently ran fine. i ran minio on aufs as well as externally host mapped directory.

also you can set the "level" to "error" in config.json

```
        "logger": {
                "console": {
                        "enable": true,
                        "level": "error"
                },
```

**Comment by olalonde** [comment] 2016-11-03 18:59
The number isn't consistent:

```
# readStream foo
not ok 15 StreamContentLengthMismatch: Stream content length mismatch. Received 5230355 of 5242881 bytes.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [StreamContentLengthMismatch: Stream content length mismatch. Received 5230355 of 5242881 bytes.] message: 'Stream content length mismatch. Received 5230355 of 5242881 bytes.', code: 'StreamContentLengthMismatch', time: Thu Nov 03 2016 11:55:40 GMT-0700 (PDT) }
    at: Duplexify._destroy (/Users/olalonde/code/blockai/s3-tus-store/node_modules/duplexify/index.js:184:15)
    stack: |-
      StreamContentLengthMismatch: Stream content length mismatch. Received 5230355 of 5242881 bytes.
```

```
# readStream foo
not ok 15 StreamContentLengthMismatch: Stream content length mismatch. Received 5136067 of 5242881 bytes.
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      { [StreamContentLengthMismatch: Stream content length mismatch. Received 5136067 of 5242881 bytes.] message: 'Stream content length mismatch. Received 5136067 of 5242881 bytes.', code: 'StreamContentLengthMismatch', time: Thu Nov 03 2016 11:57:08 GMT-0700 (PDT) }
    at: Duplexify._destroy (/Users/olalonde/code/blockai/s3-tus-store/node_modules/duplexify/index.js:184:15)
    stack: |-
      StreamContentLengthMismatch: Stream content length mismatch. Received 5136067 of 5242881 bytes.
          at PassThrough.checkContentLengthAndEmit (/Users/olalonde/code/blockai/s3-tus-store/node_modules/aws-sdk/lib/request.js:599:15)
          at emitNone (events.js:91:20)
          at PassThrough.emit (events.js:185:7)
          at endReadableNT (_stream_readable.js:974:12)
          at _combinedTickCallback (internal/process/next_tick.js:74:11)
          at process._tickDomainCallback (internal/process/next_tick.js:122:9)
  ...
```

Have you tried running the tests for a couple of minutes? I'm using

```
$ while 1; do npm run test:fast && sleep 1; done                                                                                                                       
```

Most of the time there is no error.

![rs](https://cloud.githubusercontent.com/assets/416585/19980912/103c5512-a1bd-11e6-8846-c03add90991d.gif)

**Comment by olalonde** [comment] 2016-11-03 19:01
Where is config.json on the filesystem? I can try to mount it as a volume in docker-compose and edit it.

**Comment by krishnasrinivas** [comment] 2016-11-03 19:06
```
krishna@escape:~/dev/s3-tus-store$ cat docker-compose.yml 
minio:
  image: minio/minio:edge
  ports:
    - "9000:9000"
  volumes:
    - ./test/.minio/data:/export
    - ./test/.minio/config:/root/.minio
  command: server /export
  environment:
    - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
    - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
krishna@escape:~/dev/s3-tus-store$ 

```

it will be here:
`./test/.minio/config/config.json`

**Comment by krishnasrinivas** [comment] 2016-11-03 19:13
> Have you tried running the tests for a couple of minutes? 

yes

@olalonde can you do this: run https://github.com/krishnasrinivas/httpdump to dump the http requests/responses? you can run `httpdump -l :8000 -f localhost:9000` so that it forwards all the requests that it gets on 8000 to 9000 where minio runs. Your tests will need to set endpoint to `endpoint = 'http://127.0.0.1:8000'`

**Comment by krishnasrinivas** [comment] 2016-11-03 19:18
@olalonde you can download httpdump binary from here https://krisupload.s3.amazonaws.com/public/httpdump

**Comment by olalonde** [comment] 2016-11-03 19:25
Ok, just did: https://gist.github.com/d6b44f3ad4c308d67f68242dc8ea1822

The error happens around here:

```
---------------------------
REQUEST : GET path:/s3-tus-store/foo
Host: 127.0.0.1:8000
Authorization: AWS4-HMAC-SHA256 Credential=AKIAIOSFODNN7EXAMPLE/20161103/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=af8ba290a3d819f4f01d10c0c98bf15c77b20604edb7b05f227cbfcb17fe7c35
Connection: close
User-Agent: aws-sdk-nodejs/2.6.14 darwin/v6.6.0
Content-Length: 0
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20161103T192044Z

INFO[0136] Round trip: http://localhost:9000/s3-tus-store/foo, code: 200, duration: 2.039381ms

-----
RESPONSE STATUS: 200 OK
Content-Type: application/octet-stream
Date: Thu, 03 Nov 2016 19:20:44 GMT
Content-Length: 5242881
Last-Modified: Thu, 03 Nov 2016 19:20:44 GMT
Server: Minio/RELEASE.2016-10-22T00-50-41Z (linux; amd64)
Vary: Origin
Accept-Ranges: bytes
X-Amz-Request-Id: WF9QP677U4T2HPTP

ERRO[0136] Error copying upstream response Body: unexpected EOF
```

Tested with following command:

```
export S3_ENDPOINT=http://127.0.0.1:8000  
while 1; do npm run test:fast && sleep 1; done
```

**Comment by olalonde** [comment] 2016-11-03 19:28
If I'm reading the log correctly, Minio closes the HTTP connection too early? (https://gist.github.com/anonymous/5d5d7a83efbaefddda9078e27d04c070#file-gistfile1-txt-L583)

**Comment by olalonde** [comment] 2016-11-03 19:32
I trimmed the log a bit.. Here's the log for the failing test: https://gist.github.com/5d5d7a83efbaefddda9078e27d04c070 and here's one where the test is passing: https://gist.github.com/b463284e27eabf90c08433cfddc88f35

**Comment by krishnasrinivas** [comment] 2016-11-03 19:55
@olalonde thanks

**Comment by harshavardhana** [comment] 2016-11-11 15:57
// cc @balamurugana

**Comment by harshavardhana** [comment] 2016-12-02 01:04
```
  s3-tus-store:index offset = 4 +0ms
  s3-tus-store:index Completing upload! +0ms
  s3-tus-store:index saveUploadForKey { uploadId: '1e4fdff5-69af-4483-93b9-d91981dcd8b8',
  upload: { key: 'foo', uploadLength: 4, metadata: { somekey: 'someval' } } } +0ms
  s3-tus-store:index s3.completeMultipartUpload start { completeUploadParams: 
   { Key: 'foo',
     Bucket: 's3-tus-store',
     MultipartUpload: { Parts: [Object] },
     UploadId: '1e4fdff5-69af-4483-93b9-d91981dcd8b8' } } +7ms
  s3-tus-store:index s3.completeMultipartUpload end +8ms
  s3-tus-store:index createReadStream { key: 'foo' } +0ms
``` 

Consistently being able to run this on Linux kernel with the latest release. no issues. Did like a 1000 run will try this on OS X as well and report.

**Comment by harshavardhana** [comment] 2016-12-02 01:45
Not able to reproduce on OS X either with latest release around 1000 runs completed without issues, closing this bug. @olalonde please re-open if seen again.

**Closed as completed by harshavardhana** 2016-12-02 01:45 UTC
