### ISSUE TITLE
Signature V4 generated by JavaScript aws-sdk v3 is not valid for min.io

### ISSUE THREAD

**Issue by egorFiNE** [minio/minio#11743] opened 2021-03-09 12:21 UTC
V4 signature generated by JavaScript aws-sdk v2 (the previous version) is accepted as valid by minio, while V4 signature generated by the newer aws-sdk v3 returns SignatureDoesNotMatch from minio server. 

[testcase.zip](https://github.com/minio/minio/files/6108417/testcase.zip)

## Expected Behavior

File is downloaded from local minio using signed GET url . 

## Current Behavior

File is not downloaded from local minio using signed GET url. I get the `SignatureDoesNotMatch` reply instead.

## Steps to Reproduce (for bugs)

1. Install minio at localhost:9000, create bucket, create user with credentials, grant access to the bucket
2. Install last node.js version
3. Extract attached zip into a folder
4. cd into folder, run `npm install`
5. edit test.mjs, put proper access credentials, region, endpoint, etc
5. `node test.mjs`
6. You will get two URLs, one generated by older SDK, another generated by the current version, both signatures are V4
7. curl both of them

## Your Environment

node v15.10.0, minio version RELEASE.2021-03-04T00-53-13Z. 

Both JS aws-sdk are latest versions.

**Comment by harshavardhana** [comment] 2021-03-09 21:33
this is because of the wrong implementation in aws-sdk-v2 - they willfully are rejecting their own spec 

Older implementation used x-amz-signed-headers appropriately where as the new one adds some junk information now such as adding `x-amz-user-agent` instead. 

> GET /incoming/doesnmatter.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=minio%2F20210309%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20210309T212208Z&X-Amz-Expires=900&X-Amz-Signature=cdddb1b9d73c8fbfedb85de825a2d247c701256593e44450071c877516bb0ad5&X-Amz-SignedHeaders=host&x-amz-user-agent=aws-sdk-js%2F3.8.0%20os%2Flinux%2F5.4.0-66-generic%20lang%2Fjs%20md%2Fnodejs%2F15.11.0%20api%2Fs3%2F3.8.0&x-id=GetObject HTTP/1.1


This means that when you are making such a request you should make sure that x-amz-user-agent is also provided as part of the HTTP header for the server to validate the signature. 

Just doing `curl` doesn't set these headers and we cannot blindly ignore `x-amz-signed-headers` and assume whatever is sent by client to be correct - this defeats the AWS S3 signature spec requirement for x-amz-signed-headers. 

It looks like aws-sdk-js should be fixed here to avoid using `x-amz-user-agent` as part of the signed-headers. Looks like a regression in the newer SDKs

**Comment by harshavardhana** [comment] 2021-03-09 22:39
Okay so found out the original problem  the canonical request generated by aws-sdk-js-v3 is wrong 

```
GET
/incoming/doesnmatter.txt
X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=minio%2F20210309%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20210309T222012Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&x-amz-user-agent=aws-sdk-js%2F3.8.0%20os%2Flinux%2F5.4.0-66-generic%20lang%2Fjs%20md%2Fnodejs%2F15.11.0%20api%2Fs3%2F3.8.0&x-id=GetObject
host:10.0.0.67

host
UNSIGNED-PAYLOAD
```

NOTE: the host header has a port missing i.e `:9000` - the canonical request needs to have port in-tact when it's generating the presigned request. Looks like they have introduced regressions

```diff
@@ -16,6 +16,7 @@ class S3RequestPresigner {
     }
     async presign(requestToSign, { unsignableHeaders = new Set(), unhoistableHeaders = new Set(), ...options } = {}) {
         unsignableHeaders.add("content-type");
+	console.log(requestToSign);
         // S3 requires SSE headers to be signed in headers instead of query
         // See: https://github.com/aws/aws-sdk-js-v3/issues/1576
         Object.keys(requestToSign.headers)
@@ -25,10 +26,10 @@ class S3RequestPresigner {
             unhoistableHeaders.add(header);
         });
         requestToSign.headers[constants_1.SHA256_HEADER] = constants_1.UNSIGNED_PAYLOAD;
-        if (!requestToSign.headers["host"]) {
-            requestToSign.headers.host = requestToSign.hostname;
+        requestToSign.headers.host = requestToSign.hostname;
+	if (requestToSign.port) {
+	    requestToSign.headers.host = requestToSign.hostname+":"+requestToSign.port;
         }
-	console.log(requestToSign);
         return this.signer.presign(requestToSign, {
             expiresIn: 900,
             unsignableHeaders,

```

Fixes the issue, please open this issue on aws-sdk-js-v3

**Closed as completed by harshavardhana** 2021-03-09 22:39 UTC
Labels: community, upstream (bug)

**Comment by egorFiNE** [comment] 2021-03-10 08:54
@harshavardhana  thank you. Reported https://github.com/aws/aws-sdk-js-v3/issues/2121.
