### ISSUE TITLE
gateway nas - partially aggregated multipart uploads remain in .minio.sys/tmp when using multiple MinIO instances

### ISSUE THREAD

**Issue by rluetzner** [minio/minio#13270] opened 2021-09-22 14:04 UTC
## Expected Behavior

After a multipart upload has been completed no traces of it should remain in the MinIO metabucket.

## Current Behavior

When using multiple MinIO instances in 'gateway nas' mode with a load balancer multiple subfolders with a partially aggregated file remain in `.minio.sys/tmp`.
While uploading a 350MB file to 12 load balanced MinIO instances sharing the same backend, I ended up with 2.3GB of wasted disk space. This space will only be retrieved > 24h later when the cleanup function removes these files from .minio.sys/tmp.
When we are uploading many large objects with multipart upload this will quickly fill up any available disk space.

## Possible Solution

The 'gateway nas' mode initializes unique subfolders for each MinIO instance started (using UUIDs). This is most probably meant to prevent conflicting access to the same file.
fs-v1-multipart.go contains a function called `backgroundAppend()` which is executed as a go routine every time PutObjectPart() is called. The function checks for existing chunks and starts aggregating them in order. This is most probably meant to increase the performance of `CompleteMultipartUpload()` which in case of a single instance would end up with a finished object in .minio.sys/tmp.
Because we are using multiple instances the `backgroundAppend()` run as a go routine starts aggregating files from the existing chunks in host specific subfolders in .minio.sys/tmp. This should probably be a locked file with a name that is consistent across all hosts (e.g. the upload-ID).

## Steps to Reproduce (for bugs)

1. Start multiple minio instances with different ports in gateway nas mode, e.g. `minio gateway nas --address 9000 ./data`.
2. Use a load balancer, e.g. [sidekick](https://github.com/minio/sidekick): `./sidekick --health-path "/minio/health/live" http://localhost:900{0...3}`.
3. Generate a big file to upload, e.g. `truncate -s 350M test.txt`
3. Use [mc](https://github.com/minio/mc) to upload the test file.
4. Take a look at .minio.sys/tmp.

## Context

I've noticed in a VM test setup that my disks filled up quickly. I provisioned 1GB disks to hold the MinIO backend data, but was unable to upload a single 350MB object.

## Regression

Is this issue a regression? Probably not...

## Your Environment

* Version used: RELEASE.2021-09-18T18-09-59Z
* Server setup and configuration: multiple hosts load balanced with Sidekick, but should be easily reproducible on a single host.
* Operating System and version: `Linux fs-testcluster-robert2-n1 5.3.18-24.61-default #1 SMP Wed Apr 14 10:10:07 UTC 2021 (c41a65c) x86_64 x86_64 x86_64 GNU/Linux` --> This is a SLES system.

**Comment by harshavardhana** [comment] 2021-09-22 17:49
> The 'gateway nas' mode initializes unique subfolders for each MinIO instance started (using UUIDs). This is most probably meant to prevent conflicting access to the same file.
> fs-v1-multipart.go contains a function called `backgroundAppend()` which is executed as a go routine every time PutObjectPart() is called. The function checks for existing chunks and starts aggregating them in order. This is most probably meant to increase the performance of `CompleteMultipartUpload()` which in case of a single instance would end up with a finished object in .minio.sys/tmp.
> Because we are using multiple instances the `backgroundAppend()` run as a go routine starts aggregating files from the existing chunks in host specific subfolders in .minio.sys/tmp. This should probably be a locked file with a name that is consistent across all hosts (e.g. the upload-ID)

@rluetzner how often does it happen? does your client send an abortMultipartUpload() ?

**Comment by harshavardhana** [comment] 2021-09-22 17:52
> * Start multiple minio instances with different ports in gateway nas mode, e.g. `minio gateway nas --address 9000 ./data`.
> * Use a load balancer, e.g. [sidekick](https://github.com/minio/sidekick): `./sidekick --health-path "/minio/health/live" http://localhost:900{0...3}`.

If you are load balancing across servers this will create new parts on different `.minio.sys/tmp` differently, to coalesce multipart properly. You should send requests to the same nodes for multipart operation to complete.

The issue looks like due to this behavior as parts kept getting sent to different nodes, they only coalesce at the end only on one server.

**Comment by rluetzner** [comment] 2021-09-22 17:56
Interesting. I don't have much experience with load balancers, but I know for sure that Sidekick doesn't offer an option to send all requests to the same node. There is also no issue with corruption or conflicts. Just a bunch of incomplete files that use up disk space. 

Is this expectation documented somewhere? I was unaware if the fact that all multipart requests must be sent to the same host.

**Comment by harshavardhana** [comment] 2021-09-22 19:08
> Is this expectation documented somewhere? I was unaware of the fact that all multipart requests must be sent to the same host.

Only in the case of NAS gateway, but it is possible to avoid this behavior.

**Comment by rluetzner** [comment] 2021-09-23 07:17
> Only in the case of NAS gateway, but it is possible to avoid this behavior.

Sorry, but I'm not sure I understand. You're saying this isn't actually a bug in MinIO and is working as intended and I should use a different load balancer?

I've looked at enough code to understand where the problem comes from. I understand that sending all multipart uploads for a single upload ID to only one of the nodes will get rid of the problem I observed. I'm still trying to understand if this behavior was intended when the backgroundAppend() was implemented or if the function should actually work differently for 'gateway nas'.

So I have two different suggestions.

1. Implement file locking for backgroundAppend() and use a consistent file name. This will fix the behavior I observed in 'gateway nas' and 'server' mode. IMHO the locking overhead should be negligible. Any other gateway implementations and an erasure coded setup are unaffected by such a change.
2. Extend the documentation and usage for 'gateway nas' and 'server' to include "Ensure that in a load balanced setup all multipart requests belonging to the same upload ID are sent to the same target."

As you probably already guessed I would much prefer solution 1. Pushing a workaround for this behavior to the load balancer is not very user-friendly. From a user perspective I would expect to be able to distribute chunked uploads to a bunch of servers. This would be acceptable if I knew there was a technical reason to do so, i.e. files would get corrupted when uploaded to different hosts. Then it would be better to say "Don't use 'gateway nas' in a load balanced setup at all." The code comments I've read until now do tell me however that multiple fs instances are very much expected, e.g.

```
// Assign a new UUID for FS minio mode. Each server instance
// gets its own UUID for temporary file transaction.
```

taken from fs-v1.go:144.

**Comment by harshavardhana** [comment] 2021-09-23 07:22
> Sorry, but I'm not sure I understand. You're saying this isn't actually a bug in MinIO and is working as intended and I should use a different load balancer?

It is working as intended but we need to fix the behavior here which is not anticipated.

**Comment by harshavardhana** [comment] 2021-09-23 07:58
> 1. Implement file locking for backgroundAppend() and use a consistent file name. This will fix the behavior I observed in 'gateway nas' and 'server' mode. IMHO the locking overhead should be negligible. Any other gateway implementations and an erasure coded setup are unaffected by such a change.

We can't do that since we don't know the offsets that have been persisted there is a concurrency problem here, but it is possible to fix this by clearing up other UUIDs slightly differently.

**Comment by harshavardhana** [comment] 2021-10-04 07:02
Okay so as currently implemented every 12 hours all the pending previously coalesced uploads get cleaned up that are 24 hours and older. 

So in essence they will stay around for 1+days and will get cleaned up in different intervals.  AFAICS this implementation is currently working as intended and there is no other cleaner way to do it without overly complicating NAS gateway deployments. 

This behavior currently satisfies all our existing customers we won't be really changing this behavior anyways for now. 

So realistic deployments might not see this problem.

**Comment by harshavardhana** [comment] 2021-10-04 07:37
FWIW you can set the custom values for these expirations after #13354 is released. Closing this issue however since the behavior is already in place to handle this scenario just that default values are meant for ideal production deployments with sufficient space.

**Closed as completed by harshavardhana** 2021-10-04 07:37 UTC
Labels: working as intended, community
