### ISSUE TITLE
Failed GET, PUT and DELETE requests due to "Failed to delete lock info entry" Error

### ISSUE THREAD

**Issue by curantes** [minio/minio#5311] opened 2017-12-20 15:04 UTC
I initiated a new `mc mirror` from our backup server (FreeBSD) for our minio cluster which is 10 TB in size and is split into 1000 buckets. This storage mostly consist of PDF files (invoices). Initial backup was made yesterday but was interrupted so it had copied 1 TB of the data.

This morning our backup `mc mirror` was interuppted because of mc taking all RAM. We were forced to reboot the backup server. This caused very high load on all minioservers in our 16 node cluster and the first set of 1000 error logs shown below. I think this might have triggered the issue. The `mc mirror` was accessing the minio cluster through a Haproxy.

When we killed the `mc mirror` with `kill -9` we got the high load and also 1000 errors of logs:
```
time="2017-12-20T08:12:09+01:00" level=error msg="Unable to write notification to client." cause="write tcp 10.98.92.119:9091->10.98.92.140:46954: write: broken pipe" source="[bucket-notification-handlers.go:247:sendBucketNotification()]"
```
![screenshot from 2017-12-20 15-46-20](https://user-images.githubusercontent.com/6643262/34212715-79f568a2-e59d-11e7-8f04-3830ea5ecc8e.png)

And later on we got the other error of: 
```
level=error msg="Failed to delete lock info entry (param = {615 220615/2017/1220/a6ee15f3-45b3-4f04-ace4-18e0551a79e8.txt}; opsID = HNOOGZUYR9JFFY1H)" cause="No entry in lock info for <Operation ID> HNOOGZUYR9JFFY1H, <volume> 615, <path> 220615/2017/1220/a6ee15f3-45b3-4f04-ace4-18e0551a79e8.txt" source="[namespace-lock.go:183:(*nsLockMap).lock()]" stack="lock-instrument.go:249:(*nsLockMap).deleteLockInfoEntryForOps namespace-lock.go:181:(*nsLockMap).lock namespace-lock.go:330:(*lockInstance).GetLock object-handlers.go:528:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm"
```
![screenshot from 2017-12-20 15-44-53](https://user-images.githubusercontent.com/6643262/34212764-94835224-e59d-11e7-8266-46ee0bd7cd48.png)

Also during this I have been doing a heal of the cluster with a bash loop to heal one bucket at a time which have been running for at least 14 days without any issues previously. This was initiated from our first node (prod-arkivplats01.fnox.se) all other request go through the Haproxy.

We were also running a lot of stat requests to check if all files have been moved during a previous migration from an old NFS server.

Below are some graphs of load and memory usage of minio servers during our issues.

![load](https://user-images.githubusercontent.com/6643262/34211990-22f28c44-e59b-11e7-83ef-923803b75d61.png)
![mem](https://user-images.githubusercontent.com/6643262/34211993-26cf08a6-e59b-11e7-9fdf-565316ce00b4.png)

## Expected Behavior
Minio distributed should be able to heal by it self when issues occurs. 

## Current Behavior
Received a lot of errors of "Failed to delete lock in entry" which causes issues in PUT and DELETE requests.

## Steps to Reproduce (for bugs)

1. Setup a 16 nodes cluster on CentOS7 with 1000 buckets and approx 30000 files in each buckets
2. Setup a FreeBSD server with minio-client (OS probably does not matter)
3. Setup a haproxy to load balance minio cluster
4. Initiate a mc mirror -w on freeBSD server to mirror the cluster through the loadbalancer from minio to filesystem on FreeBSD
5. After a while interrupt the mirror with CTRL-C

## Your Environment

* Version used (`minio version`): 2017-09-29T19:16:56Z
* Environment name and version (e.g. nginx 1.9.1): CentOS 7
* Server type and version: VMware VSphere 6.5 VM, 1 Core, 4 GB of memory
* Operating System and version (`uname -a`): Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Nodes count: 16
* Storage size in minio: 10 TB 
* Number of buckets: 1000

**Comment by krisis** [comment] 2017-12-21 13:01
>  I have been doing a heal of the cluster with a bash loop to heal one bucket at a time 

@curantes  could you provide the bash loop you run to heal one bucket at a time?

**Comment by curantes** [comment] 2017-12-21 15:02
@krisis
```bash
#!/bin/bash
set -e
echo "[$(date "+%F %H:%M:%S")] Initiate minio cluster heal"
for bucket in {000..999}; do
	echo "[$(date "+%F %H:%M:%S")] Initiate heal of $bucket"
	/usr/local/bin/mc admin heal --recursive local/$bucket || {
		echo "minio heal bucket: $bucket failed. bailing out."
		exit 1
	}
	echo "[$(date "+%F %H:%M:%S")] Done heal of $bucket"
done
echo "[$(date "+%F %H:%M:%S")] Done minio cluster heal"
```

**Comment by jonaz** [comment] 2017-12-22 06:07
I would like to add that after this incident the cluster is behaving strange. Yesterday afternoon we tried resuming backup with mc mirror but it just times out on some files when we tried feching them from node 02,03 and 06. But if we tried mc cat on any other of the 16 nodes it worked. 

The message logged on the nodes timing out was: 
```
time="2017-12-21T16:13:40+01:00" level=error msg="Failed to delete lock info entry (param = {027 214027/2017/1220/a3b47438-ee27-4779-871a-fae6d22198af.txt}; opsID = 37ZNI0A2ONAYYIGZ)" cause="No entry in lock info for <Operation ID> 37ZNI0A2ONAYYIGZ, <volume> 027, <path> 214027/2017/1220/a3b47438-ee27-4779-871a-fae6d22198af.txt" source="[namespace-lock.go:183:(*nsLockMap).lock()]" stack="lock-instrument.go:249:(*nsLockMap).deleteLockInfoEntryForOps namespace-lock.go:181:(*nsLockMap).lock namespace-lock.go:349:(*lockInstance).GetRLock xl-v1-healing.go:538:xlObjects.HealObject <autogenerated>:1011:(*xlObjects).HealObject admin-handlers.go:708:adminAPIHandlers.HealObjectHandler admin-router.go:64:(adminAPIHandlers).HealObjectHandler-fm"
```

We have now resolved that file so it can be stat'ed and read from all nodes by restarting 02,03 and 06 (in addition to the original rolling restart we did on the 2017-12-20 to get rid of most errors).

**Comment by krisis** [comment] 2018-01-05 06:33
@curantes, I have the following questions. It will help me identify possible code paths responsible for this issue.
1. Where is the `mc mirror` command run? (i.e is it on the FreeBSD server or one of the 16 Linux nodes)
2. Is there one `mc mirror` process per bucket? If possible, please share how you run `mc mirror` including command line arguments. N B please remove sensitive information if any.
3. Did you notice any of the minio nodes going down when (or before) you stopped the `mc mirror` command?

**Comment by curantes** [comment] 2018-01-05 09:09
@krisis answer to  your follow up questions below.

> 1. Where is the mc mirror command run? (i.e is it on the FreeBSD server or one of the 16 Linux nodes)

It is running from the FreeBSD server (FreeNAS)
> 2. Is there one mc mirror process per bucket? If possible, please share how you run mc mirror including command line arguments. N B please remove sensitive information if any.

`/mnt/zfs01/home/fnoxdrift/bin/minio-client mirror -w prod-cluster /mnt/zfs01/minio-prod`
note that minio-client binary is from latest released and have been compiled by me and not the version shipped in FreeBSD
> 3. Did you notice any of the minio nodes going down when (or before) you stopped the mc mirror command?

All Nodes was up and running with no issues prior

**Comment by curantes** [comment] 2018-01-05 13:16
@krisis We actlually had similar issue again today. I have updated info about how to recreate this. This is what happend to us before and today. And as last time we had to do rolling restart of mino to get the locks cleared.

**Comment by krisis** [comment] 2018-01-05 15:55
@curantes, next time you `kill` the server to clear locks, use `kill -SIGABRT <pid>`.  This should provide stack trace of the Minio server process, giving us some clues on which operation is holding a lock.

**Comment by jonaz** [comment] 2018-01-08 06:27
@krisis  last time it happened we had issues with GET operations aswell. Not 100% of GET failed but quite a few. I took some samples of random files during the outage and some i where able to read and some i wasnt.

**Comment by krisis** [comment] 2018-01-08 10:50
@jonaz It is expected that GET operations would fail when you hit this issue. Thanks for updating the synopsis. Next time you observe that the server is 'locking up', kill it using `kill -SIGABRT <pid>`. This should print the process backtrace, which will help us pinpoint the operation that caused the 'locking up' in the first place.

**Comment by krisis** [comment] 2018-01-08 12:25
@curantes @jonaz Could you paste output of `mc admin lock list local/bucket`,  for as many`bucket`s as possible in logs like `msg="Failed to delete lock info entry (param = {bucket ...`?
If we can associate recent operations on the path to object, we can infer which operation is (possibly) not relinquishing the lock.

**Comment by jonaz** [comment] 2018-01-08 15:12
We cannot now since we have restarted all nodes until the lock dissapeared. But if it happens again we will keep loop over all server and print the locks to a file.

**Comment by curantes** [comment] 2018-01-10 07:30
relates to #5023

**Comment by harshavardhana** [comment] 2018-01-10 14:18
> relates to #5023

Thanks for letting us know @curantes

**Comment by krisis** [comment] 2018-01-19 11:30
@curantes could you confirm that this issue is not present in minio version RELEASE.2017-11-22T19-55-46Z or later?

**Comment by krisis** [comment] 2018-01-29 17:54
@curantes, symptoms mentioned in the description and from conversations on slack it is clear that the root cause is the same as https://github.com/minio/minio/issues/5023. Since it is fixed I am closing this issue as well. Feel free reopen this issue if it appears after updating to RELEASE.2017-11-22T19-55-46Z or later.

**Closed as completed by krisis** 2018-01-29 17:54 UTC
Labels: fixed, priority: medium

**Comment by curantes** [comment] 2018-01-30 14:55
@krisis Sorry for late reply, Yes this issue have been resolved since upgrade to latest released minio.

Thank you for your help.
