### ISSUE TITLE
Hang associated with many object uploads at once

### ISSUE THREAD

**Issue by adamlamar** [minio/minio#10413] opened 2020-09-03 19:15 UTC
## Expected Behavior
When uploading 10k or more objects at once from many sources, minio should not intermittently hang.

## Current Behavior
I have an application that uploads objects to minio roughly once per minute. In one configuration, about 2,000 objects are uploaded concurrently from 128 sources, totaling about 5GB of data. Normally this process completes in about 5-10 seconds, and generally works as expected.

Minio configuration: 8 replicas in distributed mode running in kubernetes with a container limit of 12 CPUs for each replica. Disks are local SSDs exposed via hostPath.

Here is a prometheus graph of the uploads with normal behavior. Any given minio replica serves less than 300 concurrent requests:
<img width="1030" alt="01-minio-prometheus-upload-normal" src="https://user-images.githubusercontent.com/13948507/92154232-b6979280-ede2-11ea-9c8a-c45bb091d758.png">

The same application in a different configuration produces about 10,000 objects and uploads them once per minute. Prometheus graph:
<img width="1188" alt="02-minio-prometheus-upload-high-connections" src="https://user-images.githubusercontent.com/13948507/92154416-00807880-ede3-11ea-919e-acac4d025828.png">

Note that the concurrent connection count goes much higher when the object count increases, and we see spotty coverage of metrics. The spotty metric coverage is because the prometheus endpoint actually hangs due to the object upload load:
<img width="394" alt="03-minio-prometheus-hang" src="https://user-images.githubusercontent.com/13948507/92154892-c2d01f80-ede3-11ea-8c0e-eb235455d324.png">

I confirmed with `curl -v http://$MINIO_IP/minio/prometheus/metrics` from multiple hosts that the TCP connection usually is established immediately, but the HTTP endpoint can take anywhere from 1 to 30+ seconds to respond (prometheus gives up after 10s).

Even if I turn off the application performing object writes, it takes a while for minio to recover on its own:
<img width="1380" alt="04-minio-prometheus-long-recovery" src="https://user-images.githubusercontent.com/13948507/92155111-180c3100-ede4-11ea-93d1-8543f7414609.png">

But restarting all minio replicas will restore normal operation, including the prompt collection of prometheus metrics.

I tried lower the max number of concurrent uploads from the application to 10 (for a total of 128x10 = 1280 connections to the cluster) which succeeds at first, but starts hanging within a few minutes. Prometheus metric collection fails as well (see the lack of data points on the last few minutes of the graph)
<img width="1382" alt="05-minio-prometheus-lower-concurrent-uploads" src="https://user-images.githubusercontent.com/13948507/92155676-fa8b9700-ede4-11ea-8eae-54044bc3ee36.png">

I don't have any good error messages from the application, but I know its using the AWS Java SDK and is retrying uploads pretty often.

Some other interesting observations:
* When objects are being written, I can still use the UI to upload files. Small files upload normally, but my test 30MB and 600MB files would experience long delays while uploading. It would upload a few MBs, pause for tens of seconds, upload a few more MBs, pause again, etc.
* Likewise, the subsequent delete of the 600MB object took about 3.5 minutes
* List and download operations are not affected - they respond as normal

I also happened to grab some `mc admin top locks` output:

```
/ # mc admin top locks minio
Time                  Type    Resource
56 minutes            WRITE   .minio.sys/leader
2 minutes             READ    bucket/flink/path/to/object/ef588801-1793-49cd-aba1-8e027436a39e
```

## Possible Solution

I don't know much about minio's codebase, but this seems like it could be related to lock contention under load.

## Steps to Reproduce (for bugs)

I can work on a standalone program to reproduce the issue, but may take a day or two.

## Context

The application uploading objects often fails due to this issue.

## Regression

No

## Your Environment

* Version used (`minio --version`): RELEASE.2020-08-18T19-41-00Z
* Server setup and configuration: n1-standard-32 and n1-standard-96 instances on GCP
* Operating System and version (`uname -a`): Ubuntu 16.04 - 4.15.0-1080-gcp

**Comment by harshavardhana** [comment] 2020-09-03 19:43
If you really want to control the throttling you should throttle the requests such that your drives are capable of handling the requests

The only explanation here is that your servers under-provisioned for the workload you want https://github.com/minio/minio/tree/master/docs/throttle

> / # mc admin top locks minio
> Time                  Type    Resource
> 56 minutes            WRITE   .minio.sys/leader
> 2 minutes             READ    bucket/flink/path/to/object/ef588801-1793-49cd-aba1-8e027436a39e

This is nothing special @adamlamar here to look at. 

> I don't know much about minio's codebase, but this seems like it could be related to lock contention under load.

I don't think that is the issue there is no contention here.

**Comment by adamlamar** [comment] 2020-09-03 19:51
I'll check out the throttling guide. I did throttle the number of connections from the client to a max of 10 which kept the concurrent connections per minio replica to the same range as the successful case, but it still hangs.

Do you have an explanation for why prometheus metrics collection hangs? Surely that should continue to work regardless of the load on the disk?

**Comment by adamlamar** [comment] 2020-09-03 19:52
Also, why do list and read operations work ok, but uploads and deletes don't?

**Comment by harshavardhana** [comment] 2020-09-03 19:56
> Do you have an explanation for why prometheus metrics collection hangs? Surely that should continue to work regardless of the load on the disk?

Prometheus reaches the disks to get the latest status, there is also something else which is sort of hung you should get profile outputs here 

- `mc admin profile start --type goroutines myminio/testbucket && sleep 5mins && mc admin profile stop` 
- `mc admin profile start` to capture cpu, mem, block profile 

> Also, why do list and read operations work ok, but uploads and deletes don't?

That really doesn't make sense, so let's gather some profile. 

Also please make sure to upgrade to the latest release, lets debug what we have the latest in the release.

**Comment by adamlamar** [comment] 2020-09-03 20:24
Thanks, let me upgrade the test environment and I'll get back to you with those profiles.

**Comment by adamlamar** [comment] 2020-09-03 23:55
Here's a couple of profiles running `RELEASE.2020-09-02T18-19-50Z`:
[minio-profile-no-maxconn-goroutine.zip](https://github.com/minio/minio/files/5171884/minio-profile-no-maxconn-goroutine.zip)
[minio-profile-no-maxconn.zip](https://github.com/minio/minio/files/5171886/minio-profile-no-maxconn.zip)

I turned on the application, started the goroutine profile, and when that one finished, I did the cpu/mem/block profiles. The goroutine one started quickly, but the other took 10-15 minutes before I saw the `mc: Profile data successfully started.` message. I let both run for 5 minutes as requested above.

One other piece of information - I do see the accept() queue filling and draining when the cluster is in this state, and sometimes this does cause dropped TCP SYN packets. But I see it at zero and ~128 and lots of other values in between.

```
# ss -tanl | grep 9000
LISTEN     72     128         :::9000                    :::*

# ss -tanl | grep 9000
LISTEN     130    128         :::9000                    :::*

# ss -tanl | grep 9000
LISTEN     0      128         :::9000                    :::*
```

Also, I turned off the application so no more reads or writes are occurring, but minio still hasn't recovered in terms in the number of current requests dropping back down. Most replicas are still showing between 1-3k:
![05-minio-prometheus-long-recovery2](https://user-images.githubusercontent.com/13948507/92184117-85808780-ee0d-11ea-9525-18a3d42304d9.png)

EDIT: one last thing I'm noticing is a _ton_ of minio to minio connections in SYN_SENT state which have persisted for more than an hour after the last object write. Running `netstat -antp | grep SYN_SENT | awk '{ print $5 }' | sort | uniq -c` produces

```
    130 10.0.0.101:9000
   3129 10.0.0.104:9000
   4008 10.0.0.116:9000
   5494 10.0.0.125:9000
   6579 10.0.0.136:9000
   7891 10.0.0.137:9000
     41 10.0.0.99:9000
```

**Comment by klauspost** [comment] 2020-09-04 09:19
Server 5 seems overloaded. It is the server handling locks, so requests are just piling up.

Only goroutines were collected from this server so pinpointing exact CPU usage is tricky.

**Comment by klauspost** [comment] 2020-09-04 09:53
Your numbers doesn't add up to me. Looking at the servers I see:

* Server 0: 3120 in progress PutObject calls.
* Server 1: 2646 in progress PutObject calls.
* Server 2: 4911 in progress PutObject calls.
* Server 3: 2811 in progress PutObject calls.
* Server 4: 1833 in progress PutObject calls.

...etc, so far above the 2000 total calls you expect.

Are the clients doing aggressive retries? It seems like they all fire at once and when they don't get a reply they just retry piling even harder on the problem.

**Comment by klauspost** [comment] 2020-09-04 11:10
https://github.com/minio/minio/pull/10321 will make sure that if `PutObject` calls are aborted, the lock request will also be cancelled.

The current context disconnect is here: https://github.com/minio/minio/blob/1e2ebc9945259ba2a15d48d791daa2b68f8c82c9/cmd/lock-rest-client.go#L66

which is fixed by the PR above.

**Comment by adamlamar** [comment] 2020-09-04 16:17
> far above the 2000 total calls you expect

Yes, I forgot to mention that the profiles were taken with the almost always failing application configuration - 10k total objects per minute from a total of 128 sources. Each source can establish up to 500 max connections ([as configured by default using presto](https://prestodb.io/docs/current/connector/hive.html#configuration)). 

The application configuration that only produces 2k objects per minute works most of the time, but I didn't capture profiles for that.

> Are the clients doing aggressive retries?

I don't have as much visibility as I'd like into the application, but I can tell the sources are retrying - maybe up to 30 times before giving up, when necessary. I'm not totally sure why they decide to retry, but my _guess_ is they expect the server to reply more quickly. 

> if PutObject calls are aborted, the lock request will also be cancelled.

This sounds encouraging - I'd be happy to test out this functionality once its ready.

**Comment by adamlamar** [comment] 2020-09-04 18:24
@klauspost FWIW I deployed the docker tag `10321-0cd8ae8` on my test cluster, but not seeing any difference in behavior. We still have thousands of connections in `SYN_SENT` state, spotty prometheus metrics collection, etc. Any other information I can provide or tests I can run?

In the meantime I'll work on a standalone program that can reproduce the problem.

**Comment by adamlamar** [comment] 2020-09-04 18:54
Correction: once I removed the object write load, the number of in-flight requests as reported by minio has dropped much faster than it did previously:
<img width="1375" alt="06-minio-shorter-recovery" src="https://user-images.githubusercontent.com/13948507/92275599-9502dd80-eeac-11ea-8b2b-7aa4479421fa.png">
The current official release still hadn't recovered fully after waiting overnight, whereas the branch was well on its way within 30 minutes.

**Comment by adamlamar** [comment] 2020-09-09 20:06
@klauspost I wrote a quick go program that reproduces the issue: https://gist.github.com/adamlamar/ce21808b195cc3865260efd94bdeeeff

The program is pretty consistently successful at concurrently uploading batches of 1000 or 2000 objects once per minute, but going to 3000 and more tends to cause minio to hang. During the first three batches, all 3000 objects are uploaded within ~25s, so it seems likely that the hardware can handle the load without issue. But on batch 4, it takes about 2.5 minutes to complete the upload, and batch 5 never completes (at least not after waiting 30 minutes or so).

Anything I can help with to get to the bottom of this issue?

**Comment by harshavardhana** [comment] 2020-09-13 20:03
I suspect the actual PR to fix this is #10474

**Comment by adamlamar** [comment] 2020-09-14 16:17
Thanks @harshavardhana! I would like to test our your PR branch, but looks like the image doesn't exist on dockerhub anymore. Last time I was able to pull the image directly but I guess I didn't catch it quickly enough this time.

**Comment by harshavardhana** [comment] 2020-09-15 05:45
Feel free to give `minio/minio:edge` a try @adamlamar

**Comment by adamlamar** [comment] 2020-09-15 16:01
I tried out `minio/minio:edge` and there was a definite improvement! Interestingly, my [test program](https://gist.github.com/adamlamar/ce21808b195cc3865260efd94bdeeeff) was able to upload 3000 objects per batch, but there was also still a consistent hang. It would upload for about ~17 seconds, then I'd see no POST requests complete for just under 2 minutes, and then all of a sudden the rest of the requests would complete almost immediately. Minio seemed to be stable during this period (no gaps in prometheus metrics collection).

However, increasing the batch size to 5000 led to hangs similar to the old behavior.

**Comment by harshavardhana** [comment] 2020-09-15 16:12
> I tried out `minio/minio:edge` and there was a definite improvement! Interestingly, my [test program](https://gist.github.com/adamlamar/ce21808b195cc3865260efd94bdeeeff) was able to upload 3000 objects per batch, but there was also still a consistent hang. It would upload for about ~17 seconds, then I'd see no POST requests complete for just under 2 minutes, and then all of a sudden the rest of the requests would complete almost immediately. Minio seemed to be stable during this period (no gaps in prometheus metrics collection).
> 
> However, increasing the batch size to 5000 led to hangs similar to the old behavior.

Would you be able to capture profiles with - now it would be interesting to see what is leading to this behavior

```
mc admin profile start --type cpu,mem,block,goroutines
``` 
?

**Comment by adamlamar** [comment] 2020-09-15 17:48
Sure, here's the result of `mc admin profile start --type cpu,mem,block,goroutines minio/mybucket && sleep 300 && mc admin profile stop minio/mybucket`:

[minio-profile-3000-obj-pause.zip](https://github.com/minio/minio/files/5226748/minio-profile-3000-obj-pause.zip)

I started the profile prior to running my test program, and the profile ended during one of the pause periods where no POSTs are completing.

Also, for reference:
```
$ minio --version
minio version DEVELOPMENT.2020-09-15T00-35-56Z
```

Here's the output from my test program:
```
2020/09/15 17:30:01 Successfully uploaded 855 bytes with key loadtest/3rdEqt87jc8wOdoDkosjolFwDgtvpa in 29.824808389s
2020/09/15 17:30:01 Successfully uploaded 584 bytes with key loadtest/wTpalLPJzFEWTVxhoyyqxPfKufJ6z7 in 29.821639406s
2020/09/15 17:30:01 Successfully uploaded 946 bytes with key loadtest/ou227S7wJSpNn0idBxS2j6p2KPOr1e in 29.762223627s
2020/09/15 17:30:01 Successfully uploaded 991 bytes with key loadtest/zK44yFvZ08MLng1xzcn9QAnSGf5285 in 29.434578164s
<long pause>
2020/09/15 17:31:43 Successfully uploaded 453 bytes with key loadtest/xcsQKsFpEPx3gUP3QIWgG4KA0daUt4 in 2m12.329319887s
2020/09/15 17:31:43 Successfully uploaded 716 bytes with key loadtest/CPIavX5O5Ny0rRdwQOBzX77fm2ZW8Y in 2m12.637961683s
```

**Comment by klauspost** [comment] 2020-09-15 18:41
Nothing much going on, seems the servers were mostly idle.

@harshavardhana Some servers have quite a lot waiting on quota loading config (or rather getting lock for ot)? Isn't the config cached? Could it be a lost lock?

![image](https://user-images.githubusercontent.com/5663952/93249904-4b5ea080-f792-11ea-8093-8739c29ef29f.png)

`go tool pprof -focus=convertLegacyConfigs -base profile-minio-1.minio_9000-block-before.pprof profile-minio-1.minio_9000-block.pprof`

I don't have time to look into it today, but if you also don't I can look tomorrow.

**Comment by harshavardhana** [comment] 2020-09-15 18:43
> @harshavardhana Some servers have quite a lot waiting on quota loading config (or rather getting lock for ot)? Isn't the config cached? Could it be a lost lock?

This should have happened quite early, not sure why this is stuck. Also, this being stuck shouldn't stop the object uploads. AFAICS servers were restarted if this is showing up.

**Comment by klauspost** [comment] 2020-09-15 18:51
@adamlamar Last time there was 8 servers. This only has data from 6. Are they showing up in `mc admin info` all the time? Nothing logged on the servers?

**Comment by adamlamar** [comment] 2020-09-15 19:31
@klauspost I did move to a 6 node cluster just because its easier to setup with our automation and test independently, but I can re-run with 8 if you need it. For the captured profile, 6 servers form the full cluster.

I didn't notice any restarts during the test, but just a quick glance at k8s suggests that that minio-3 did restart at some point, and there was a long stack trace (I haven't found the beginning of it in the logs)

**Comment by harshavardhana** [comment] 2020-09-15 19:34
> I didn't notice any restarts during the test, but just a quick glance at k8s suggests that that minio-3 did restart at some point, and there was a long stack trace (I haven't found the beginning of it in the logs)

yes that is something that has happened here @adamlamar do you have sufficient memory on these nodes? are you restricting the nodes in some way?

**Comment by adamlamar** [comment] 2020-09-15 21:18
Ok, I finally found the top of the stack trace for minio-3:

```
runtime: failed to create new OS thread (have 1458 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc
```

minio-3 only restarted once though, but we almost always see the ~2 min pause on every batch.

The minio replicas are using about 1.7GB memory and they're not being OOMKilled, but I can give them some more memory just in case and then re-run the test. (Edit: they are running with k8s resource limits enabled - currently 4Gi for memory, 4 vCPU, but each replica is using less than one CPU core when under load)

**Comment by harshavardhana** [comment] 2020-09-15 21:37
> runtime: failed to create new OS thread (have 1458 already; errno=11)
> runtime: may need to increase max user processes (ulimit -u)
> fatal error: newosproc

This is a thread exhaustion issue you have a top-level thread limit at the host/cgroups level - 
you have basically under-provisioned cluster for what you are trying to do. 

> (Edit: they are running with k8s resource limits enabled - currently 4Gi for memory, 4 vCPU, but each replica is using less than one CPU core when under load)

If you have 4Gi memory and you are trying to upload 1000's on concurrent operations you are bound
to die because erasure coding needs approximately 10MiB per request buffer to read from for its blockSize
adding parity its 10MiB more and also other buffers needed at the disk layer where we read in 4MiB chunks.

So to upload 1000 concurrent operations you would need safely around 20Gi worth of memory, you are severely
under-provisioning your servers and overloading them. If you need more performance you need to bring more RAM
, more CPU to this cluster. 

Using limits also is a bad idea - https://github.com/kubernetes/kubernetes/issues/67577 there are known issues with limits which lead to unexpected throttling for an application like MinIO which needs to be a high powered workhorse.

**Comment by harshavardhana** [comment] 2020-09-15 21:38
So AFAICS we have resolved the problem to a sufficient extent in the latest master, rest is just a provisioning issue.

**Comment by adamlamar** [comment] 2020-09-16 01:37
I can understand your concerns about having adequate available memory and CPU, but note that these objects are all less than 1k in size. The total size of all objects together is less than 10MB.

I removed the CPU and memory limits entirely and installed  on 6x `c5.9xlarge` instances (36 vCPU, 72GB RAM) to remove resourcing as a factor. The uploads do complete faster (3s vs 17s) and it doesn't always pause. But I still see the ~2 minute long pause behavior even on these instances:

```
...
2020/09/16 01:12:03 Successfully uploaded 743 bytes with key loadtest/8doShUDDeIcrYwV3kSgAP8uBngI3q7 in 3.119888595s
<long pause>
2020/09/16 01:14:01 Successfully uploaded 600 bytes with key loadtest/iiBvJnmT4DDxy87qQk4YdcpaL7pVlL in 2m1.774624305s
...
```

During the pause period, CPU usage is very low - about 2%.

**Comment by harshavardhana** [comment] 2020-09-16 01:44
> I can understand your concerns about having adequate available memory and CPU, but note that these objects are all less than 1k in size. The total size of all objects together is less than 10MB.

That still doesn't matter that still leaves 4MiB allocation needed at storage layer @adamlamar - assuming that 1KiB is somehow just 1KiB throughout is a bit naive since MinIO is doing a lot of heavy lifting and limiting that without adequate understanding you will shoot yourself in the foot. 

> I removed the CPU and memory limits entirely and installed on 6x `c5.9xlarge` instances (36 vCPU, 72GB RAM) to remove resourcing as a factor. The uploads do complete faster (3s vs 17s) and it doesn't always pause. But I still see the ~2 minute long pause behavior even on these instances:

As I expected remove throttling you are getting the better throughput.

> and it doesn't always pause. But I still see the ~2 minute long pause behavior even on these instances:

This pause is because the server died i.e some inflight requests timedout @adamlamar you need to fix that too, there is something else that also limits thread creation on your system which adds to the situation that you are in. 

> During the pause period, CPU usage is very low - about 2%.

This is because something has crashed already and all network operations have stopped for a 1minute of dial timeout internal to MinIO.

**Comment by adamlamar** [comment] 2020-09-16 03:26
> That still doesn't matter that still leaves 4MiB allocation needed

I understand and agree there is overhead. As configured with the c5.9xlarge instances (6 x 72GB = 432GB total cluster memory), there is over 100MB of memory available per request with a batch size of 3000 (432GB / 3000 = ~140MB). That's at least double your original estimate, correct?

> remove throttling you are getting the better throughput

Yes, I agree that removing the container limit may improve throughput somewhat, but it unfortunately doesn't solve the pause issue.

> This pause is because the server died

The minio replicas are not dying:

```
Every 2.0s: kubectl get pods | grep minio                                                                                                                                                                   ip-10-202-8-243: Wed Sep 16 03:06:21 2020

minio-0                                    1/1     Running      0          68m
minio-1                                    1/1     Running      0          67m
minio-2                                    1/1     Running      0          66m
minio-3                                    1/1     Running      0          65m
minio-4                                    1/1     Running      0          65m
minio-5                                    1/1     Running      0          64m
minio-loadtest-65688d54c-5dg5d             1/1     Running      0          51m
```

I saw minio-3 crash once with the thread exhaustion error, but not since, even under load.

**Comment by harshavardhana** [comment] 2020-09-16 03:27
> > That still doesn't matter that still leaves 4MiB allocation needed
> 
> I understand and agree there is overhead. As configured with the c5.9xlarge instances (6 x 72GB = 432GB total cluster memory), there is over 100MB of memory available per request with a batch size of 3000 (432GB / 3000 = ~140MB). That's at least double your original estimate, correct?
> 
> > remove throttling you are getting the better throughput
> 
> Yes, I agree that removing the container limit may improve throughput somewhat, but it unfortunately doesn't solve the pause issue.
> 
> > This pause is because the server died
> 
> The minio replicas are not dying:
> 
> ```
> Every 2.0s: kubectl get pods | grep minio                                                                                                                                                                   ip-10-202-8-243: Wed Sep 16 03:06:21 2020
> 
> minio-0                                    1/1     Running      0          68m
> minio-1                                    1/1     Running      0          67m
> minio-2                                    1/1     Running      0          66m
> minio-3                                    1/1     Running      0          65m
> minio-4                                    1/1     Running      0          65m
> minio-5                                    1/1     Running      0          64m
> minio-loadtest-65688d54c-5dg5d             1/1     Running      0          51m
> ```
> 
> I saw minio-3 crash once with the thread exhaustion error, but not since, even under load.

Ah then let's keep the cluster in this situation and then proceed to the real problem. Let's capture the 
profile now since this is the real cluster where we should reproduce if any bugs or hangs.

**Comment by adamlamar** [comment] 2020-09-16 04:23
Sounds good, here's two profiles:

* [minio-profile-3000-obj-no-container-limit.zip](https://github.com/minio/minio/files/5229623/minio-profile-3000-obj-no-container-limit.zip) - 3000 object uploads, but on the c5.9xlarge nodes with k8s container limits disabled - I'm not sure if this one will be substantially different than the previous, and also I didn't notice any pauses during this period
* [minio-profile-pause-period.zip](https://github.com/minio/minio/files/5229628/minio-profile-pause-period.zip) - here I captured 30s of execution when the uploads were paused

**Comment by harshavardhana** [comment] 2020-09-16 05:21
Is pause the only issue that you have now @adamlamar ? and no hangs?

**Comment by adamlamar** [comment] 2020-09-16 16:30
Yes, the upload pause is the only remaining issue. Prometheus metrics collection is stable after #10474 AFAICT

**Comment by harshavardhana** [comment] 2020-09-16 16:40
> Yes, the upload pause is the only remaining issue. Prometheus metrics collection is stable after #10474 AFAICT

@klauspost were you able to look at the profile output? It does look weird because I couldn't find anything waiting.

**Comment by harshavardhana** [comment] 2020-10-10 03:12
The upload pauses also should be fixed in latest releases, please test and let us know.

**Comment by adamlamar** [comment] 2020-10-10 16:22
Thanks for the note @harshavardhana - I ran my test program again but unfortunately not much difference on `RELEASE.2020-10-09T22-55-05Z`:

```
2020/10/10 16:16:39 Successfully uploaded 208 bytes with key loadtest/1RBPuI1f7gIzY17uJ9Ao3EX5UsyPnR in 19.927702807s
2020/10/10 16:16:39 Successfully uploaded 560 bytes with key loadtest/3kfObOxmflkInGRn2W6oGYtbY9N4eo in 20.039351055s
<long pause>
2020/10/10 16:18:33 Successfully uploaded 680 bytes with key loadtest/Jy8csaeH0MmUq7tdY6b2uOELqf5PyW in 2m14.022876604s
2020/10/10 16:18:33 Successfully uploaded 843 bytes with key loadtest/H0VcmJH6fXlcoKwVyh3TvLy6n9m5FL in 2m14.233812282s
```

**Comment by harshavardhana** [comment] 2020-10-10 16:23
> Thanks for the note @harshavardhana - I ran my test program again but unfortunately not much difference on `RELEASE.2020-10-09T22-55-05Z`:
> 
> ```
> 2020/10/10 16:16:39 Successfully uploaded 208 bytes with key loadtest/1RBPuI1f7gIzY17uJ9Ao3EX5UsyPnR in 19.927702807s
> 2020/10/10 16:16:39 Successfully uploaded 560 bytes with key loadtest/3kfObOxmflkInGRn2W6oGYtbY9N4eo in 20.039351055s
> <long pause>
> 2020/10/10 16:18:33 Successfully uploaded 680 bytes with key loadtest/Jy8csaeH0MmUq7tdY6b2uOELqf5PyW in 2m14.022876604s
> 2020/10/10 16:18:33 Successfully uploaded 843 bytes with key loadtest/H0VcmJH6fXlcoKwVyh3TvLy6n9m5FL in 2m14.233812282s
> ```

Would it possible to capture `mc admin trace -a`  for the entire duration of the run? And attach it here.

**Comment by adamlamar** [comment] 2020-10-11 03:07
Sure, here you go! The trace begins about 5 seconds before any uploads, and uploads start at the top of the minute.

[trace.txt.gz](https://github.com/minio/minio/files/5360524/trace.txt.gz)

**Comment by harshavardhana** [comment] 2020-10-11 03:16
> Sure, here you go! The trace begins about 5 seconds before any uploads, and uploads start at the top of the minute.

It almost looks like client didn't send any request for 2mins? @adamlamar - do you have the sample code? 

```
22:06:15.550 [200 OK] s3.PutObject minio.minio:9000/mybucket/loadtest/oIaAAbYTg7LCCITLF6KaaHnq9mxmzm 100.96.21.133     1.340991s    ↑ 428 B ↓ 259 B
22:08:10.689 [200 OK] s3.PutObject minio.minio:9000/mybucket/loadtest/WnDmz1ZEtnPSxiKJEla4M8EsdVXhiO 100.96.21.133     2.870732s    ↑ 756 B ↓ 259 B
```

**Comment by harshavardhana** [comment] 2020-10-11 03:25
Also you are creating like really small files @adamlamar your drives seem to be not even capable of delivering proper performance they are slow even for simple rename operations

```
-path=b991bfa9-b090-49cf-9983-87341179a70e&source-volume=.minio.sys%2Ftmp  100.96.87.107     6.673224s    ↑ 58 B ↓ 0 B
-path=7da9f4b6-3063-4aac-b2dc-efb1b450da83&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.317479s    ↑ 58 B ↓ 0 B
-path=3d9e2ddf-c506-40d1-8d26-69d4a928ca4b&source-volume=.minio.sys%2Ftmp  100.96.87.107     6.694367s    ↑ 58 B ↓ 0 B
-path=159f9ccf-0e29-4a05-be9c-58696df33eff&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.199398s    ↑ 58 B ↓ 0 B
-path=da43ded6-4cbf-430c-9d12-d8abd5a17829&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.337127s    ↑ 58 B ↓ 0 B
-path=613171b3-66cb-4fb0-8257-38fa45736e3d&source-volume=.minio.sys%2Ftmp  100.96.48.67      1.323418s    ↑ 58 B ↓ 0 B
-path=232b9307-56bf-473b-bc3b-facae2dd0f3d&source-volume=.minio.sys%2Ftmp  100.96.48.67      1.243617s    ↑ 58 B ↓ 0 B
-path=1031eb23-3ea9-4d22-a42f-a71ec6556013&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.20847s     ↑ 58 B ↓ 0 B
-path=52c03423-599b-48ca-a165-cc15457bdc87&source-volume=.minio.sys%2Ftmp  100.96.48.67      2.015378s    ↑ 58 B ↓ 0 B
-path=f5072062-d9a7-4b7b-97b1-dcffbe2937fc&source-volume=.minio.sys%2Ftmp  100.96.87.107     5.176753s    ↑ 58 B ↓ 0 B
-path=93d11c0c-9d08-4fd7-8498-8450e17af915&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.198302s    ↑ 58 B ↓ 0 B
-path=b1415a44-4cb7-4a1f-8ee8-2f9596a3325e&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.212265s    ↑ 58 B ↓ 0 B
-path=05423fb4-7cfd-494a-aee8-63d02dcc7748&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.20321s     ↑ 58 B ↓ 0 B
-path=0a4747e1-e8e3-4fea-bd25-ac76b42b46dd&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.203792s    ↑ 58 B ↓ 0 B
-path=76256e48-8867-4509-be00-e4356a36ebb6&source-volume=.minio.sys%2Ftmp  100.96.48.67      1.340169s    ↑ 58 B ↓ 0 B
-path=3e0afa1a-be8d-4bf4-8414-d6ca06805302&source-volume=.minio.sys%2Ftmp  100.96.87.107     5.039523s    ↑ 58 B ↓ 0 B
-path=61e180df-8f07-445a-9414-f9bd0326a31f&source-volume=.minio.sys%2Ftmp  100.96.48.67      4.06878s     ↑ 58 B ↓ 0 B
-path=e19bccd1-3786-4345-aeaa-33a79af0d72f&source-volume=.minio.sys%2Ftmp  100.96.48.67      3.319251s    ↑ 58 B ↓ 0 B
-path=62bb7e8a-a452-4939-bf81-e46b1986d3d9&source-volume=.minio.sys%2Ftmp  100.96.48.68      3.431755s    ↑ 58 B ↓ 0 B
-path=aa2575e8-6603-4233-b693-b78edf530f24&source-volume=.minio.sys%2Ftmp  100.96.87.107     5.925896s    ↑ 58 B ↓ 0 B
-path=122a867e-10d9-42af-aada-ff612f983e42&source-volume=.minio.sys%2Ftmp  100.96.48.67      5.938899s    ↑ 58 B ↓ 0 B
-path=0c7d78e3-4130-4edd-8e31-6ca35f75d018&source-volume=.minio.sys%2Ftmp  100.96.87.107     6.041207s    ↑ 58 B ↓ 0 B
-path=6970b357-4174-4a6b-86e4-8d534072461d&source-volume=.minio.sys%2Ftmp  100.96.48.68      1.206333s    ↑ 58 B ↓ 0 B
-path=a19a5a7d-debe-4319-aec0-b05e97f9e74f&source-volume=.minio.sys%2Ftmp  100.96.87.107     5.15586s     ↑ 58 B ↓ 0 B
-path=136d1a8b-0717-495e-adbe-2d9b4986a122&source-volume=.minio.sys%2Ftmp  100.96.48.67      4.921394s    ↑ 58 B ↓ 0 B
-path=9891d3ec-7e3c-41e9-a4b1-e80e10fd5138&source-volume=.minio.sys%2Ftmp  100.96.48.68      8.81417s     ↑ 58 B ↓ 0 B
```

I think you should check your setup, AFAICS see the server didn't even see the request come in for 2mins almost looks like a client side issue, once that is addressed you should look at drives - they seem to be really slow. Unless this is some virtualized setup looks like you are getting pretty bad performance for simple drives.

**Comment by harshavardhana** [comment] 2020-10-11 03:31
Also, the workload looks not suitable for the hardware that you have it's creating like files < 1KiB - this is terrible for almost all drives that you buy in the market for cheap. You need NVMe drives to get any decent performance for these objects. 

If this is your regular workload pattern then you shouldn't be really using MinIO cluster without NVMe's.

**Comment by adamlamar** [comment] 2020-10-11 04:34
Yes the sample test program is here: https://gist.github.com/adamlamar/ce21808b195cc3865260efd94bdeeeff

In the test above, the program is creating 3000 concurrent connections (or whatever objectCount is set to) to the cluster simultaneously. So when you see the program outputting 2m20s, that's how long it took minio to serve that single request. The client isn't doing the requests in sequence, but rather all at once. The client receives a number of responses for about ~15s, and then minio stops responding for a while.

In terms of performance, even with these disks, I actually find it more than acceptable with the exception of this pause. During the time minio is actively responding to requests, I'm observing about 140 PUTs of these small objects per second. Ideally minio would continue to make progress on these requests at the same rate until all connections have been served. But the problem is that minio is actively responding for 20s, and inactive for about 2 minutes.

**Comment by adamlamar** [comment] 2020-10-11 04:41
Just another data point:

* When objectCount in the program is set to 1000, objects upload in about 7-10s almost every time, with no variance.
* When objectCount is set to 1500, objects upload in about 11s
* When objectCount is set to 1750, objects upload in about 16s (though sometimes it pauses)
* When objectCount is set to 2000, objects upload in about 2m20s (almost always)

**Comment by harshavardhana** [comment] 2020-10-11 04:45
> Yes the sample test program is here: https://gist.github.com/adamlamar/ce21808b195cc3865260efd94bdeeeff
> 
> In the test above, the program is creating 3000 concurrent connections (or whatever objectCount is set to) to the cluster simultaneously. So when you see the program outputting 2m20s, that's how long it took minio to serve that single request. The client isn't doing the requests in sequence, but rather all at once. The client receives a number of responses for about ~15s, and then minio stops responding for a while.
> 

That's not possible at all @adamlamar because the trace would show if there is a 2min delay on any actively waiting request. There are no such waits because there is no request sent to the server up to 2mins from the client. 

Can you add a trace on the client-side to see if the request is indeed sent? 

> In terms of performance, even with these disks, I actually find it more than acceptable with the exception of this pause. During the time minio is actively responding to requests, I'm observing about 140 PUTs of these small objects per second. Ideally minio would continue to make progress on these requests at the same rate until all connections have been served. But the problem is that minio is actively responding for 20s, and inactive for about 2 minutes.

I actually beg to differ this is a pretty terrible setup actually we multiple setups in 100PiBytes in production and never see such a level of latency per calls. Disks are either too slow like slow SATA drives or about to die or are being shared by some other entity.

You may try remounting your drives with `-onoatime` to gain more performance for small files.

**Comment by harshavardhana** [comment] 2020-10-11 05:35
Took the liberty of running the tests against a 2 node 4 drive NVMe setup here are the results

```
2020/10/11 05:27:59 Successfully uploaded 177 bytes with key loadtest/FUvQF5NsKhPcsfbw69bMbtYbUbJUgv in 805.397129ms
2020/10/11 05:27:59 Successfully uploaded 977 bytes with key loadtest/hEHbDlZOFQQRdebDTgCIMZQ60O7uAJ in 726.502819ms
2020/10/11 05:27:59 Uploaded 2300 objects

real    0m1.241s
user    0m12.061s
sys     0m1.620s
```

I suspect the pause is because the client is retrying something on an error and it's not giving up - tries again after 2mins.

**Closed as completed** 2020-10-12 21:19 UTC
Labels: community, priority: medium
