### ISSUE TITLE
Trying to start Min.io server using a nfs share

### ISSUE THREAD

**Issue by valdecircarvalho** [minio/minio#7916] opened 2019-07-12 01:27 UTC
## Expected Behavior

I'm trying to start minio server using a nfs share and but I'm getting the message: **ERROR Unable to initialize backend: Insufficient permissions to access path, `/nfs/minio/.minio.sys/tmp/9e92fea8-0431-435c-a39a-1fa3b773235c`.**

## Steps to Reproduce (for bugs)
1. Setup a NFS file share (I'm using AWS Storage Gateway as a NFS target).
2. Create a user minio-user with the command: sudo useradd --system minio-user --shell /sbin/nologin
3. Create a dir for mount using the command sudo mkdir /nfs/minio
4. Give permission to user minio-user to the mount dir sudo chown minio-user:minio-user /nfs/minio/
5. Mount the nfs share --> sudo mount -t nfs -o nolock,hard 192.168.1.145:/minio-data.homelabsrvbr /nfs/minio/
6. Start the server --> minio server  /nfs/minio

Got the error: ERROR Unable to initialize backend: Insufficient permissions to access path, `/nfs/minio/.minio.sys/tmp/9e92fea8-0431-435c-a39a-1fa3b773235c`.
      > Please ensure the specified path can be accessed.

## Context
Minio cannot start using a NFS file share.

## Your Environment
* Version used (`minio version`):
Version: 2019-07-10T00:34:56Z
Release-Tag: RELEASE.2019-07-10T00-34-56Z
Commit-ID: 9d49688c87e9c7c3f769833c3a8697d16349f6c0

* Environment name and version (e.g. nginx 1.9.1): N/A
* Server type and version: VM
* Operating System and version (`uname -a`): Linux lab-minio-01 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project: N/A

**Comment by harshavardhana** [comment] 2019-07-12 01:45
is your user allowed to write access to the NFS mount @valdecircarvalho ?

**Comment by valdecircarvalho** [comment] 2019-07-12 02:04
> is your user allowed to write access to the NFS mount @valdecircarvalho ?

@harshavardhana hi! 

I have followed the instalation procedures and create a system user for min.io like this:
**sudo useradd --system minio-user --shell /sbin/nologin**
then I give the permissions to this system user like this:
**sudo chown minio-user:minio-user /nfs/minio/**

**Comment by harshavardhana** [comment] 2019-07-12 02:07
I don't think that will work with NFS, NFS can bring it's own restrictions. Have you verified this user can write to the mount and rename directories etc ?

**Comment by valdecircarvalho** [comment] 2019-07-12 02:22
> I don't think that will work with NFS, NFS can bring it's own restrictions. Have you verified this user can write to the mount and rename directories etc ?
Any user can write to this mount. I manage to login with this user (minio-user) and it can read/write/delete files in this share.

**Comment by harshavardhana** [comment] 2019-07-12 02:28
Can you show some sample commands which worked ?

**Comment by harshavardhana** [comment] 2019-07-12 02:30
Also try to `mkdir -p /nfs/minio/.minio.sys/tmp/9e92fea8-0431-435c-a39a-1fa3b773235  as `minio-user`

**Comment by valdecircarvalho** [comment] 2019-07-12 02:31
> Can you show some sample commands which worked ?

Sorry, I didn´t get it. What do you mean?

I can log witht the user
minio-user@lab-minio-01:/nfs/minio$ ls
1.txt  2.txt  3.txt  4.txt  admin.txt  joao.txt
minio-user@lab-minio-01:/nfs/minio$ touch harshavardhana.dummy
minio-user@lab-minio-01:/nfs/minio$ ls
1.txt  2.txt  3.txt  4.txt  admin.txt  harshavardhana.dummy  joao.txt
minio-user@lab-minio-01:/nfs/minio$

**Comment by harshavardhana** [comment] 2019-07-12 02:35
Thanks  is `minio` server running as the same user ? If yes then can you `strace -f -v minio server /nfs/minio` and attach the console output here ?

**Comment by valdecircarvalho** [comment] 2019-07-12 02:47
> strace -f -v minio server /nfs/minio
its a huge output... here are the first few lines...
I can add everything if needed


administrator@lab-minio-01:~$ strace -f -v minio server /nfs/minio
execve("/usr/local/bin/minio", ["minio", "server", "/nfs/minio"], ["LS_COLORS=rs=0:di=01;34:ln=01;36"..., "SSH_CONNECTION=192.168.1.111 567"..., "LESSCLOSE=/usr/bin/lesspipe %s %"..., "LANG=C.UTF-8", "XDG_SESSION_ID=1", "USER=administrator", "PWD=/home/administrator", "HOME=/home/administrator", "LC_CTYPE=C.UTF-8", "LC_TERMINAL=iTerm2", "SSH_CLIENT=192.168.1.111 56779 2"..., "LC_TERMINAL_VERSION=3.3.0beta13", "SSH_TTY=/dev/pts/0", "MAIL=/var/mail/administrator", "TERM=xterm-256color", "SHELL=/bin/bash", "SHLVL=1", "LOGNAME=administrator", "XDG_RUNTIME_DIR=/run/user/1000", "PATH=/usr/local/sbin:/usr/local/"..., "LESSOPEN=| /usr/bin/lesspipe %s", "_=/usr/bin/strace"]) = 0
arch_prctl(ARCH_SET_FS, 0x2cc55b0)      = 0
sched_getaffinity(0, 8192, [0, 1])      = 8
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f45f94c3000
mmap(0xc000000000, 67108864, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000000000
mmap(0xc000000000, 67108864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xc000000000
mmap(NULL, 33554432, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f45f74c3000
mmap(NULL, 2164736, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f45f72b2000
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f45f72a2000
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f45f7292000
rt_sigprocmask(SIG_SETMASK, NULL, [], 8) = 0
sigaltstack(NULL, {ss_sp=NULL, ss_flags=SS_DISABLE, ss_size=0}) = 0
sigaltstack({ss_sp=0xc000002000, ss_flags=0, ss_size=32768}, NULL) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
gettid()                                = 736
rt_sigaction(SIGHUP, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=0x45ef00, sa_mask=~[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x45f030}, NULL, 8) = 0
rt_sigaction(SIGINT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x45ef00, sa_mask=~[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x45f030}, NULL, 8) = 0
rt_sigaction(SIGQUIT, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=0x45ef00, sa_mask=~[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x45f030}, NULL, 8) = 0
rt_sigaction(SIGILL, NULL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x45ef00, sa_mask=~[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x45f030}, NULL, 8) = 0

**Comment by harshavardhana** [comment] 2019-07-12 02:50
please add everything @valdecircarvalho  attach it like a text file.

**Comment by valdecircarvalho** [comment] 2019-07-12 02:57
@harshavardhana I just figure out something.
If I run the command with the minio-user it works...s



> please add everything @valdecircarvalho attach it like a text file.
Here it goes!!! =) 
[strace-minio.log](https://github.com/minio/minio/files/3384802/strace-minio.log)

**Comment by harshavardhana** [comment] 2019-07-12 03:06
> If I run the command with the minio-user it works...s
> 
> >

That is what I was trying to get to, feel free to close the issue - if you don't have any other issue.

**Comment by harshavardhana** [comment] 2019-07-12 04:14
Closing this as per your last comment @valdecircarvalho - please reopen if it's not working as intended.

**Closed as completed by harshavardhana** 2019-07-12 04:14 UTC
Labels: working as intended, community, triage
