### ISSUE TITLE
Probleme in IAM Policy

### ISSUE THREAD

**Issue by antony14110** [minio/minio#13891] opened 2021-12-13 01:14 UTC
Hello,
Users authenticated by OpenID must have access to their bucket (bucket name provided by the "scope" value of the jwt token).
They inherit a policy to see that their bucket but, despite the s3:* action, I do not see the option to download the file in the bucket. Why ?
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Deny",
"Action": [
"s3:DeleteBucket",
"s3:CreateBucket"
],
"Resource": [
"arn:aws: s3 ::: *"
]
},
{
"Effect": "Allow",
"Action": [
"s3:GetBucketLocation",
"s3:ListAllMyBuckets"
],
"Resource": [
"arn:aws:s3::: "
]
},
{
"Effect": "Allow",
"Action": [
"s3:"
],
"Resource": [
"arn:aws:s3:::${jwt: scope} *"
]
}
]
}
The user can see
bucket_name
"Created: 2021-12-07T02:35:28Z
Access: R/W"
But when he go to the bucket : He don't see the elements and he can't upload a new document.
The bucket's properties are :
Access Policy: | Public
Replication: | Disabled
Object Locking: | Disabled
Encryption: | Disabled
Versioning:Enable
Quota: Disable
name: console
image: minio/console:v0.12.6

**Comment by harshavardhana** [comment] 2021-12-13 01:23
Closing as duplicate of https://github.com/minio/console/issues/1320

**Closed as completed by harshavardhana** 2021-12-13 01:23 UTC
Labels: duplicate, community
