### ISSUE TITLE
[fixed] Using the AWSS3 to get a PreSignedURL, returns a url that when fetched fails with signature error.

### ISSUE THREAD

**Issue by gossmer** [minio/minio#10361] opened 2020-08-26 20:35 UTC
Using the AWSS3 located at https://github.com/aws-amplify/aws-sdk-ios
 
When I use the API to request a pre-signed URL request (AWSS3GetPreSignedURLRequest) an error is returned from the link returned when used in any browser. I can download the bucket/key with “AWSS3TransferManager.s3TransferManager, with the same information.
 
Here is the error returned in Chrome:
 <Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
    <Key>Overview.pdf</Key>
    <BucketName>bob</BucketName>
    <Resource>/bob/Overview.pdf</Resource>
    <RequestId>162EDEF603590C10</RequestId>
    <HostId>043892e2-2355-41df-b808-4741e07f3727</HostId>
 </Error>
 
 
Here is sample swift code:
            let getPreSignedURLRequest = AWSS3GetPreSignedURLRequest()
            getPreSignedURLRequest.httpMethod = AWSHTTPMethod.GET
            getPreSignedURLRequest.key = key
            getPreSignedURLRequest.bucket = bucket
            getPreSignedURLRequest.expires = Date(timeIntervalSinceNow: 3600)
            
            AWSS3PreSignedURLBuilder.s3PreSignedURLBuilder(forKey: kS3Key).getPreSignedURL(getPreSignedURLRequest).continueWith { (task:AWSTask<NSURL>) -> Any? in
                if let error = task.error as NSError? {
                    print("created signed failed with error: \( error)")
                    return nil
                } else if let preSignedURLString = task.result?.absoluteString {
                    print("preSignedURLString to: \(preSignedURLString)")
                }
                return nil
            }
        }
 
 
The link return in the print("preSignedURLString to: \(preSignedURLString)") fails on all browsers with an invalid signature.
 

 no

## Your Environment
VERSION
2020-03-09T18:26:53Z
PLATFORM
Host: minio-6645c6c98f-lwn92 | OS: linux | Arch: amd64
RUNTIME
Version: go1.13.8 | CPUs: 8

**Comment by ebozduman** [comment] 2020-09-05 01:58
@gossmer,

Could you try generating a presigned URL for an object using directly with a minio sdk or directly on AWS S3 without having a 3rd party in the middle?
When I tried it with minio, the generated presigned URLs worked.

**Comment by yarinm** [comment] 2020-10-08 08:49
@ebozduman I'm having the exact same issue. 
Using the minio sdk I get a working URL, when it's being generated by the S3 SDK I have the signature error mentioned above.

**Comment by ebozduman** [comment] 2020-10-08 22:45
@yarinm,

I see. I'll try to reproduce the issue using aws sdk then.

Please provide your exact reproduction steps from your environment, like was it a specific aws sdk (Go, JavaScript, Python, Ruby etc) or was it more than one sdk; attach your script if you used one or the command-line command/s used...
Or did you also  use the same https://github.com/aws-amplify/aws-sdk-ios ?

**Comment by yarinm** [comment] 2020-10-11 05:33
No, I used the go aws sdk and the aws cli and had the same issues.
I run minio using the docker image: `minio/minio:RELEASE.2020-09-17T04-49-20Z`

you reproduce it by trying to presign an object using the CLI: `aws s3 presign s3://bucket/objectname` and try and download it using curl.

**Comment by ebozduman** [comment] 2020-10-11 06:20
@yarinm,
Thank you for the information. I'll look into it.

**Comment by ebozduman** [comment] 2020-10-14 08:16
@yarinm,

Obviously, if you see any problem when you directly use aws cli with **no minio involvement**, then either you have some kind of a setting issue in your environment, or this is an issue with amazon's aws cli. 

I still wanted to give it a try and repeat exactly the same aws cli command to generate presigned url for an s3 object:
```
$ aws s3 presign s3://ersan/issue
https://ersan.s3.amazonaws.com/issue?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxx%2F20201013%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201013T080105Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=yyy
```
When I copy/paste the generated presigned url onto a browser, it downloads the file in my `"~/Downloads"` directory as expected. Tried 3 browsers, Safari, Chrome, and FireFox. The same with `curl` command. Just make sure you encapsulate the generated presigned url in quotes, like:

```
$ curl "<https://<generated-presigned-url>"
```

Needless to say, you also need to set the access and secret keys of your amazon account in your setting to be able to generate the presigned url successfully. 
You have 2 options:
 1. You can set them up as environment variables, `"export AWS_ACCESS_KEY_ID=xxx"` and `"export AWS_SECRET_ACCESS_KEY=yyy"`, or
2. Run `"aws configure"` command to set them up.

I'll close this issue, if you agree. If not, please tell me why you think this is a minio problem.

**Comment by bchatelard** [comment] 2020-10-14 11:41
I have the same issue.

The signature you use using `aws s3 presign` works fine.

The issue is with signature generated by a client where the `x-amz-user-agent` is set (ex: aws-sdk-js-v3 running on the client side).
The generated signature works fine with many s3 providers (tested on aws s3, wasabi, digitalocean), but is not working in minio.

After a quick investigation it appears that this is caused by the signature code that is not taking into account any of the 'x-amz' headers in the query param (see https://github.com/minio/minio/blob/master/cmd/signature-v4.go#L274-L276 ).

I believe this could also be an issue with other headers, but this one has been added recently ( https://github.com/aws/aws-sdk-js-v3/pull/997 ).

**Comment by bchatelard** [comment] 2020-10-14 11:44
I have made this sandbox that prints the signature in the console https://codesandbox.io/s/brave-waterfall-q6ve1 you should be able to reproduce and test this against a local minio.

**Comment by innix** [comment] 2020-10-22 12:17
I'm having same problem with Amazon's .NET S3 SDK. Here's how to reproduce:

## Spin up local MinIO server

```bash
$ MINIO_ACCESS_KEY='27IFPQOBPO84EFEFQE9Y' \
  MINIO_SECRET_KEY='J7jpBnXUM2HI9CflxVOmHT0+BvDNsB8xvwPzkd0V' \
  MINIO_REGION='eu-west-2' \
  minio server ./data/
```

## Create new .NET console project

```bash
$ dotnet new console --name presign-demo-app
$ cd presign-demo-app
$ dotnet add package AWSSDK.S3 -v 3.5.3.6
```

## Write Program.cs class

Replace everything in `Program.cs` with:

```csharp
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.Net.Http;
using System.Threading.Tasks;

internal class Program
{
    private const string accessKey = "27IFPQOBPO84EFEFQE9Y";
    private const string secretKey = "J7jpBnXUM2HI9CflxVOmHT0+BvDNsB8xvwPzkd0V";

    private static async Task Main(string[] args)
    {
        var config = new AmazonS3Config
        {
            RegionEndpoint = RegionEndpoint.EUWest2,
            ServiceURL = "http://127.0.0.1:9000",
            ForcePathStyle = true
        };
        var client = new AmazonS3Client(accessKey, secretKey, config);

        // Create presigned URL.
        var req = new GetPreSignedUrlRequest()
        {
            BucketName = "uploads",
            Key = "foo/bar.txt",
            Verb = HttpVerb.PUT,
            Protocol = Protocol.HTTP,
            Expires = DateTime.UtcNow.AddHours(6)
        };
        string preSignedUrl = client.GetPreSignedURL(req);
        Console.WriteLine("Presigned URL: " + preSignedUrl + "\n\n");

        // Upload text file to presigned URL.
        var c = new HttpClient();
        HttpResponseMessage res = await c.PutAsync(preSignedUrl, new StringContent("Hello world!"));
        string resBody = await res.Content.ReadAsStringAsync();
        Console.WriteLine("Status code: " + (int)res.StatusCode);
        Console.WriteLine("Response body: " + resBody);
    }
}
```

## Run the app

```bash
$ dotnet run
```

### Output

This is what I get when running it:

```
innix@innix-pc:/mnt/c/Users/innix/Desktop/test/presign-demo-app$ dotnet run
Presigned URL: http://127.0.0.1:9000/uploads/foo/bar.txt?AWSAccessKeyId=27IFPQOBPO84EFEFQE9Y&Expires=1603388127&Signature=EkdVmVy81XHhd4TiERQu%2F3tCfEo%3D


Status code: 403
Response body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>foo/bar.txt</Key><BucketName>uploads</BucketName><Resource>/uploads/foo/bar.txt</Resource><Region>eu-west-2</Region><RequestId>16404D5C943A4000</RequestId><HostId>1c1bd3ff-77d3-43b6-8022-0aaa16ddbfb5</HostId></Error>
```

**Comment by innix** [comment] 2020-10-22 12:28
Also tried with Go's AWS SDK using same settings, and that actually works fine.

```go
package main

import (
	"bytes"
	"io/ioutil"
	"log"
	"net/http"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/credentials"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
)

const (
	accessKey = "27IFPQOBPO84EFEFQE9Y"
	secretKey = "J7jpBnXUM2HI9CflxVOmHT0+BvDNsB8xvwPzkd0V"
)

func main() {
	sess, err := session.NewSession(&aws.Config{
		Credentials:      credentials.NewStaticCredentials(accessKey, secretKey, ""),
		Region:           aws.String("eu-west-2"),
		Endpoint:         aws.String("http://127.0.0.1:9000"),
		S3ForcePathStyle: aws.Bool(true),
	})
	svc := s3.New(sess)

	req, _ := svc.PutObjectRequest(&s3.PutObjectInput{
		Bucket: aws.String("uploads"),
		Key:    aws.String("foo/bar2.txt"),
	})
	urlStr, err := req.Presign(6 * time.Hour)

	if err != nil {
		log.Println("Failed to sign request", err)
	}

	log.Println("Presigned URL: ", urlStr)
	putObject(urlStr, "Hello world! Go version!")
}

func putObject(url, contents string) {
	r, _ := http.NewRequest(http.MethodPut, url, bytes.NewBufferString(contents))
	resp, err := http.DefaultClient.Do(r)
	if err != nil {
		log.Fatal("PUT request err", err)
	}

	respBody, err := ioutil.ReadAll(resp.Body)
	log.Println("Status code:", resp.StatusCode)
	log.Println("Response body:", err, string(respBody))
}
```

Output: 
```
innix@innix-pc:/mnt/c/Users/innix/Desktop/test/presign-demo-app-golang$ go run main.go
2020/10/22 13:24:23 Presigned URL:  http://127.0.0.1:9000/uploads/foo/bar2.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=27IFPQOBPO84EFEFQE9Y%2F20201022%2Feu-west-2%2Fs3%2Faws4_request&X-Amz-Date=20201022T122423Z&X-Amz-Expires=21600&X-Amz-SignedHeaders=host&X-Amz-Signature=0cd7a48d3949a355a519df10ef3450774b1d25c0286e6364b42ea3bece7438da
2020/10/22 13:24:23 Status code: 200
2020/10/22 13:24:23 Response body: <nil>
```

**Comment by harshavardhana** [comment] 2020-11-03 20:00
> I have the same issue.
> 
> The signature you use using `aws s3 presign` works fine.
> 
> The issue is with signature generated by a client where the `x-amz-user-agent` is set (ex: aws-sdk-js-v3 running on the client side).
> The generated signature works fine with many s3 providers (tested on aws s3, wasabi, digitalocean), but is not working in minio.
> 
> After a quick investigation it appears that this is caused by the signature code that is not taking into account any of the 'x-amz' headers in the query param (see https://github.com/minio/minio/blob/master/cmd/signature-v4.go#L274-L276 ).
> 
> I believe this could also be an issue with other headers, but this one has been added recently ( [aws/aws-sdk-js-v3#997](https://github.com/aws/aws-sdk-js-v3/pull/997) ).

this is not the issue - the issue is related to aws-sdk-js-v3 has introduced a regression in their new API change, they are not preserving the port as part of the `host` signature which needs to be preserved as per the spec. 

Only when it's port 80, 443 (std ports) it doesn't need to be part of it. This can be clearly seen by printing the request information they constructed with getRequest()

They broke this similarly with aws-sdk-java-v2 implementation which was fixed. Although we need to honor `x-amz-user-agent`  of the encoded query string.

**Comment by harshavardhana** [comment] 2020-11-03 20:03
For example running minio on port 80 simply works fine

```
~ curl "http://localhost/wip/picture.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=minio%2F20201103%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20201103T200145Z&X-Amz-Expires=900&X-Amz-Signature=f2cbaa7a8fb49f03902de803e60f4057e7b09c462820f07120e3829199515ad2&X-Amz-SignedHeaders=host&x-amz-user-agent=aws-sdk-js-v3-%40aws-sdk%2Fclient-s3%2F1.0.0-gamma.8%20Mozilla%2F5.0%20%28X11%3B%20Linux%20x86_64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F86.0.4240.75%20Safari%2F537.36&x-id=GetObject"

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key>picture.jpeg</Key><BucketName>wip</BucketName><Resource>/wip/picture.jpeg</Resource><RequestId>164417F647D9CE1A</RequestId><HostId>6504773c-3b8b-4ecc-af50-bf3d360ba49f</HostId></Error>
```

https://codesandbox.io/s/upbeat-goldberg-29c07?file=/src/App.js - the changes here

**Comment by harshavardhana** [comment] 2020-11-03 20:04
From our end we only need to fix the `x-amz-user-agent` which seems to have been recently introduced @ebozduman 

```
 git diff
diff --git a/cmd/signature-v4.go b/cmd/signature-v4.go
index f7b280fda..efa212eaa 100644
--- a/cmd/signature-v4.go
+++ b/cmd/signature-v4.go
@@ -261,12 +261,7 @@ func doesPresignedSignatureMatch(hashedPayload string, r *http.Request, region s
                key := strings.ToLower(k)
 
                // Handle the metadata in presigned put query string
-               if strings.Contains(key, "x-amz-meta-") {
-                       query.Set(k, v[0])
-                       continue
-               }
-
-               if strings.Contains(key, "x-amz-server-side-") {
+               if strings.Contains(key, "x-amz-meta-") || strings.Contains(key, "x-amz-server-side-") || strings.HasPrefix(key, "x-amz-user-agent") {
                        query.Set(k, v[0])
                        continue
                }
@@ -274,6 +269,7 @@ func doesPresignedSignatureMatch(hashedPayload string, r *http.Request, region s
                if strings.HasPrefix(key, "x-amz") {
                        continue
                }
+
                query[k] = v
        }
 
```

**Closed as completed** 2020-12-02 10:02 UTC
Labels: community, fixed, priority: medium
