### ISSUE TITLE
Requests timeout when a node fails in Kubernetes

### ISSUE THREAD

**Issue by julienp** [minio/minio#8881] opened 2020-01-22 10:31 UTC
## Expected Behavior

Requests should work as normal, provided enough nodes are still up.

## Current Behavior

When a Kubernetes node fails requests hang for 1 minute (tested with `mc cp`).

To get DNS for the pods in the stateful set there is a headless service`minio-svc` with `publishNotReadyAddresses: true`, making the pods accessible via their endpoint: `minio-X.minio-svc.minio.svc.cluster.default`.

However, in the case of a node failure, the pods running on that node will be stuck in a Terminating state (https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/#delete-pods), and their endpoints will not be removed from the headless service. This means they still resolve in DNS, and so Minio tries to reach them and will have to wait for a timeout when trying to connect.

## Possible Solution

The service with `publishNotReadyAddresses` is required to make readiness checks work (https://github.com/minio/minio/pull/8727). If we want to only include ready pods, we have a catch-22 on startup. Elasticsearch works around this by having the readiness probe respond differently during the startup phase: https://github.com/elastic/helm-charts/blob/master/elasticsearch/templates/statefulset.yaml#L197

## Steps to Reproduce (for bugs)
1. Deploy minio via the stateful set on Kubernetes 
2. `shutdown -now` one of the nodes with a minio pod

Note that by default Kubernetes will wait 300seconds before considering the node gone. The problem already happens during this time. Once the node becomes `Not Ready`, the minio pod will move to terminating status and the problem persists until the node is removed manually from the cluster.

## Your Environment
Version: minio/minio:latest DIGEST:sha256:53c65fca691336b77b74180937d8d6f7845ef1afea0e0ae9780598835d7a5979
Environment: Kubernetes 1.17
Server: Linux b54-06 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nitisht** [comment] 2020-01-22 10:35
Thank you for the detailed report @julienp we'll investigate this

**Comment by harshavardhana** [comment] 2020-01-22 18:06
@julienp have you tried without `publishNotReadyAddress` tag ?

**Comment by R-omk** [comment] 2020-02-05 12:22
I have the same problem, in my case, having the option `publishNotReadyAddresses: true` does not matter.

It is enough to simply delete the pod in a regular way or perform a node drain, which leads to the graceful shutdown of the pod.

Requests to the minio cluster stuck in  processing for exactly 1 minute.

See at  output of `mc admin trace minio` 

![Selection_462](https://user-images.githubusercontent.com/1633879/73841193-1e750300-482b-11ea-984c-8338e22bb5b2.png)

RELEASE.2020-01-25T02-50-51Z
Environment: Kubernetes 1.17

**Comment by harshavardhana** [comment] 2020-02-05 14:05
1minute is the dial timeout, the problem is DNS resolves to a non-existent IP. This is more or less a routing issue at k8s layer.

If the DNS didn't resolve we do get an earlier timeout than 1minute.

**Comment by R-omk** [comment] 2020-02-05 14:28
When the pod starts up again, it consumes a lot of processor resources (100% -260%) for the first couple of minutes, while the storage has only 1 bucket in which there is 1 small file. Why is this happening?

**Comment by harshavardhana** [comment] 2020-02-05 14:32
It's because server starts few automated routines by sending messages across the systems.

This is expected and shouldn't be considered anything for you to worry about. Let's stick to the issue at hand anything else if needs further discussion open a separate issue @R-omk

**Comment by R-omk** [comment] 2020-02-05 14:41
So, how I can safely stop one minio process for maintenance on the host node  without downtime in minio cluster? @harshavardhana

**Comment by harshavardhana** [comment] 2020-02-05 14:47
There is no downtime you see a wait time for 1minute and then subsequent calls don't wait. 1minute is expected for now.

**Comment by R-omk** [comment] 2020-02-05 14:53
1 minute is unacceptably long for real production systems, while we are talking about a standard scenario of use without emergency situations.

**Comment by harshavardhana** [comment] 2020-02-05 14:57
1minute is acceptable timeout your node is not fully down, if you want it to be better then you need to make sure to scale the replica to a smaller value. 

This allows for DNS entries to be non-existent allowing servers to not attempt resolution and timeout faster.

Taking pods down in k8s needs to be done properly, from what I can see taking down a pod is not the same as you would scale the replica count to a smaller value.

**Comment by harshavardhana** [comment] 2020-02-05 15:07
Any system has a timeout, be it TCP,  your application, etc. If you want some form of a sub microsecond outage detection it is not practically possible.

What is your acceptable timeout? Also the new dial timeout is now 15secs which version of MinIO are you running?

**Comment by R-omk** [comment] 2020-02-05 15:16
If we are talking about graceful completion I assume that some mechanism is needed where the node trap signals and sends notifications (about temporary down)  to the other nodes in the cluster.

In the case of an  unexpected failure, I expect the erasure code algorithm do fallback to worked node as fast as possible (I suppose for readonly request can be more fast then for rw requests)

**Comment by R-omk** [comment] 2020-02-05 15:25
In kubernetes there is an excellent mechanism providing the necessary number of nodes.

https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#how-disruption-budgets-work
https://github.com/helm/charts/blob/4e81b41/stable/minio/templates/poddisruptionbudget.yaml

It would be nice if it could work as expected, without various consequences such as long timeouts.

**Comment by harshavardhana** [comment] 2020-02-05 15:39
MinIO is a HTTP server with all endpoints equally capable of handling same requests, internally MinIO locking, storage operations also use HTTP operations there is no back and forth notification. No unnecessary heartbeat mechanism needed. Every HTTP request is a new state, which either completes or don't. This keeps the system always predictable and always strictly consistent.

Everything is stateless on the wire, no active connection is ever maintained so whenever an operation happens based on HTTP connection pool if a connection is active it is repurposed if not a new Conn is created with a dial timeout.

IdleConnTimeout timeout is 30secs
TLSHandshakeTimeout is 10secs
DialTimeout is 15secs

All of this is handled by Go net/http, we kept the system very simple with much of the logic of load balancing left to application layer such as nginx, haproxy or k8s load balancer. Using appropriate liveness checks readiness checks.

All the scenarios you mentioned are already handled and should work like any distributed system should work if not better. 

Each situation entails here different timeouts, there is no one value for all situations and different code paths trigger different timeouts. 

So I would suggest you upgrade to latest and see what is the DialTimeout by just taking the pod down. Another test change the replica count by disallowing internal service DNS to be created for that pod, this can be done for a given deployment automatically as well.

As fast as possible is not really possible in any scenario, there are quorum checks which need to happen to see if erasure state is acceptable. To know if the node went down we do need to reach the node.

**Comment by R-omk** [comment] 2020-02-05 16:27
In any case, there should be a circuit breaker that prevents uncontrolled spawning of new connections to node which is down.

If this can be controlled manually, this could be one of the options for resolving the issue.
For example via mc admin.

**Comment by harshavardhana** [comment] 2020-02-05 16:29
Marking node as down is something which can be done using `mc admin`

**Comment by R-omk** [comment] 2020-02-05 16:47
But for read-only requests, there is no need to wait all of 15 seconds. If it fails to establish a connection in 0.2 seconds, it can try to get parts of the data from other nodes which already has established connections.

Where 0.2s is just fallback timeout, but not a real tcp timeout.

If the other nodes also have no established connections, it can continue to try in roud robin until the main request deadline is reached, 0.2 seconds for each, or until the first suitable one establishes a connection.

**Comment by harshavardhana** [comment] 2020-02-05 16:56
Lets see if this is possible, we don't have much control over net/http here @R-omk

**Comment by boazberman** [comment] 2020-02-06 17:28
We are having similar flakyness and errors issues on a Linux installation (no docker)

**Closed as completed** 2020-03-22 05:10 UTC
Labels: community, triage
