### ISSUE TITLE
[gateway-gcs] Upload using curl fails with Access Denied on a bucket with 'upload' policy

### ISSUE THREAD

**Issue by krisis** [minio/minio#4403] opened 2017-05-23 11:51 UTC
## Expected Behavior

Upload should succeed since the policy allows for anonymous upload.

## Current Behavior

```
➜  ~ mc policy mygcs/policy-upload                                  
Access permission for `mygcs/policy-upload` is `upload`

➜  ~ curl -T "/etc/lsb-release"  http://localhost:9000/policy-upload
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key></Key><BucketName></BucketName><Resource>/policy-upload</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
```
## Steps to Reproduce (for bugs)

1.  `mc policy upload mygcs/policy-upload`
2.  `curl --request PUT --upload-file "/etc/lsb-release" -k http://localhost:9000/policy-upload`
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment] 2017-05-23 15:40
Duplicate of #4321 - its a larger issue no such bucket policy works. @krisis

**Comment by poornas** [comment] 2017-05-23 21:38
The curl command should have used a "/" after bucketname - that's why there is an access denied. If curl command is corrected, the request fails because gateway gcs has not yet implemented anonymous put.

```
$ curl -T '/Users/krispy/Downloads/au.js' http://localhost:9000/policy-upload/
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><Key></Key><BucketName></BucketName><Resource>/policy-upload/au.js</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>%                             $ 
```

**Comment by deekoder** [comment] 2017-11-16 03:12
We discused this and decided that we won't apply these  policy changes to backends where they dont apply.

**Closed as completed by deekoder** 2017-11-16 03:12 UTC
Labels: out of scope, priority: medium
