### ISSUE TITLE
[distributed] multipart resume functional test in minio-java times out

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#2524] opened 2016-08-22 14:45 UTC
multipart resume test using minio-java fails with timeout.  The failure happens with default timeout and 30 seconds timeout.

minio version:

```
Version: 2016-08-22T08:13:15Z
Release-Tag: DEVELOPMENT.2016-08-22T08-13-15Z
Commit-ID: 81da694efccd02231d50991146f64d553ad1fc31
```

Actual error:

``` java
Test: multipart: putObject(String bucketName, String objectName, String fileName)
Test: multipart resume: putObject(String bucketName, String objectName, String fileName)
java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:207)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
        at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
        at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
        at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
        at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
        at com.squareup.okhttp.Call.getResponse(Call.java:287)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at io.minio.MinioClient.execute(MinioClient.java:838)
        at io.minio.MinioClient.executeDelete(MinioClient.java:1050)
        at io.minio.MinioClient.removeObject(MinioClient.java:1562)
        at FunctionalTest.putObject_test3(FunctionalTest.java:188)
        at FunctionalTest.main(FunctionalTest.java:681)
Caused by: java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:203)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        ... 18 more
```

**Comment by balamurugana** [comment] 2016-08-23 12:29
The test removes uploaded file after multipart put object.  I see https://github.com/minio/minio/blob/distributed/cmd/xl-v1-object.go#L727 blocks forever.

**Comment by balamurugana** [comment] 2016-08-23 13:25
Further debugging leads to https://github.com/minio/minio/blob/distributed/cmd/namespace-lock.go#L127

**Comment by balamurugana** [comment] 2016-08-23 13:53
Found that https://github.com/minio/minio/blob/distributed/cmd/namespace-lock.go#L110 returns `nsLk` which is causing the problem.

As the unit test does upload and remove file, at the time of remove it get existing lock which causes blocking infinitely.

**Comment by harshavardhana** [comment] 2016-08-27 10:20
Closing this as duplicate of #2526

**Closed as completed by harshavardhana** 2016-08-27 10:20 UTC
